### ISSUE TITLE
Typo in solution

### ISSUE THREAD

**Issue by cmcgurk** [MicrosoftDocs/OfficeDocs-Support#1000]
There is a typo in the command in the solution - it should be as follows:

Get-EmailAddressPolicy | Update-EmailAddressPolicy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bcdb060-e482-4e80-5e78-c466c51014da
* Version Independent ID: a216adf3-22b1-dfb2-269a-b76b28355dd9
* Content: [Upgrade the legacy email address policy - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/hybrid-configuration-wizard-errors/legacy-email-address-policy-not-automatically-updated)
* Content Source: [Exchange/ExchangeHybrid/hybrid-configuration-wizard-errors/legacy-email-address-policy-not-automatically-updated.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/hybrid-configuration-wizard-errors/legacy-email-address-policy-not-automatically-updated.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for the feedback. The article is updated.
