### ISSUE TITLE
SQL Native Client Appears to Reject Spaces in Column Names

### ISSUE THREAD

**Issue by CubeSpark** [MicrosoftDocs/OfficeDocs-Support#1001]
### **The inventory of objects involved in this issue are as follows,**

1.  Locally Installed Microsoft Office Access 2013, 64-bit SKU
2.  One Windows Domain Controller Physical machine named BEACH
3.  One Operating System, comprising 64-bit **Windows 2008 R2 SP2** (fully patched)
4.  One local development Domain named BEACHGOO
5.  Domain and BEACH Administrative Rights for User Account **CubeSpark**
6.  The Developer Edition SQL Server (SQL Server 2012 Developer Edition 64-Bit) with the following @@Version

> Microsoft SQL Server 2012 (SP4-GDR) (KB4532098) - 11.0.7493.4 (X64)
> Dec 24 2019 19:33:24
> Copyright (c) Microsoft Corporation
> Developer Edition (64-bit) on Windows NT 6.1 (Build 7601: Service Pack 1) (Hypervisor)

SQL Server is functioning perfectly in my development sandbox.

**User Anecdote and Experience of the Defect is as follows,**
The application is a fully-tested Access 2013 application that tracks multiple business entities in support of a software deployment catalogue.  Within the project are 20 VBA Modules and 10 Class Modules.  We have references to ADODB and DAO Libraries. There are 30 Linked Tables and 22 pass-through queries that execute stored procedures and retrieve rowsets from SQL Server Views.   The SQL Native Client 11 is used, and the connect properties of the table definitions and the query definitions are as follows:
ODBC;DRIVER=SQL Server Native Client 11.0;
ServerSPN=sqlservice@beachgoo.com;
AnsiNPW=No; QuotedId=No;
AutoTranslate=No;
Network=DBMSSOCN;
DATABASE=Turbid;
WSID=BEACH;
APP=Microsoft Office 2013;
Trusted_Connection=Yes;
SERVER=BEACH;
Description=Trials;

All linked tables work perfectly **except** those which refer to Views having spaces in the names of the Columns, which, in TSQL, is supported with delimiters such as [Spaced Column Name] or "Spaced Column Name".

Within Access 2013, there is full support for spaces in the names of columns with no delimitation during design time. 
The views, represented in Access with Linked Tables having a DAO Connect property with connection string above ERROR OUT on any attempt to retrieve the rowset.  The error is:

**_ODBC--call failed.
[Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name [Spaced], (#207)
Application can't open the table in datasheet view**

After a bit more investigation, it turned that Access 2013 supports spaces in non-linked, local Access 2013 column names, and so does SQL Server, but the NATIVE CLIENT DOES NOT ALLOW IT.  In the View Definition on SQL Server, the delimiters utilized are square brackets, which alias a column name and add a space in the middle to save money that would be disbursed by report developers who rename _non-business-friendly_ columns at $100 per hour. 

The SQL Native Client 11 appears to **only** support column identifiers **with no spaces**.   If there are columns on SQL Server objects referenced through the Native Client and having a column alias with a space in its name, the SQL Native Client pushes the error down to Access 2013. The Access Application itself has NO problem with spaces in column names, but if it is a linked table, there are issues. I removed the space from the column Alias, and re-linked the table. Then it worked.

The following view declaration on SQL Server shows one column that does NOT work on Access 2013 as a Linked Table.

CREATE VIEW Mappings AS
SELECT
MyBusiness AS [My Business]
FROM
[Views].[Mappings];

I am faulting the SQL Native Client that comes with SQL Server 2012.  I am NOT faulting Access 2013, and I am NOT faulting the Database Engine.  This is a transport issue - hence I blame the Native Client.

Here are the Native Client Details:
**SQL Native Client Version 2011.110.7493.04 **SQLNCLI11.DLL**,  Date 12/25/2019**

Does anyone there have any suggestions, or is this DLL support dropped?

**Comment by nam31** [comment]
@CubeSpark The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@CubeSpark We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
