### ISSUE TITLE
can not resolve my problem

### ISSUE THREAD

**Issue by yoke88** [MicrosoftDocs/OfficeDocs-Support#1003]
can not resolve my problem, even i follow the steps here.

i  also tried to upgrade my server to exchange 2016 cu19, and no luck

any else steps or workground?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18a6f2e-2e68-51d2-b1e7-1e3a15073238
* Version Independent ID: 0b637e4f-aaac-9ea1-4e17-2b1ac500a868
* Content: [Can't access OWA/EAC with expired OAuth certificate - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/cannot-access-owa-or-ecp-if-oauth-expired)
* Content Source: [Exchange/ExchangeServer/administration/cannot-access-owa-or-ecp-if-oauth-expired.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/administration/cannot-access-owa-or-ecp-if-oauth-expired.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. You can contact [Exchange Support](https://support.serviceshub.microsoft.com/supportforbusiness/onboarding?origin=%2Fsupportforbusiness%2Fcreate) for more help if the issue persists.
