### ISSUE TITLE
Set-CsUser command can be used in SfB Online Remote PowerShell with other parameters as well.

### ISSUE THREAD

**Issue by Sagamare** [MicrosoftDocs/OfficeDocs-Support#1004]
Set-CsUser command can be used with other parameters as well like set-csuser -identity SIP -EnterpriseVoiceEnabled -HostedVoicemail -LineURI etc.

Ref : https://docs.microsoft.com/en-us/powershell/module/skype/set-csuser?view=skype-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56edcf22-6d0b-efbe-2c0b-86facc42d73f
* Version Independent ID: 9423378d-e8b6-bcaf-7c87-c9c62d933c6c
* Content: [Skype for Business Online admins can't use Set-CsUser cmdlet - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/online-configuration/admins-cant-use-set-csuser)
* Content Source: [SkypeforBusiness/SkypeOnline/online-configuration/admins-cant-use-set-csuser.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeOnline/online-configuration/admins-cant-use-set-csuser.md)
* Service: **skype-for-business-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment and feedback. The article is updated with the link of the cmdlet added.
