### ISSUE TITLE
Page doesn't help with older versions of Word

### ISSUE THREAD

**Issue by saleslogistix** [MicrosoftDocs/OfficeDocs-Support#1005]
Subject line says it all. In older versions of Word, the Trust Center doesn't have the file-block section. So, where's the registry setting that handles this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0c196e7-3737-4050-26e3-cce09c51536b
* Version Independent ID: b3f2465a-aa3f-5c6e-893b-e92b93882f7c
* Content: [Error message in Office when a file is blocked by registry policy settings - Office](https://docs.microsoft.com/en-us/office/troubleshoot/settings/file-blocked-in-office)
* Content Source: [Office/Client/settings/file-blocked-in-office.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/settings/file-blocked-in-office.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. You can try to edit the settings in Group Policy as follows:

![image](https://user-images.githubusercontent.com/16147799/103495051-54c06580-4e74-11eb-948d-e04ca510befb.png)

If it doesn't help, you can contact [Office Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.office-support) for more help.
