### ISSUE TITLE
Enterprise Root CAs mean nothing?

### ISSUE THREAD

**Issue by BestBackwards** [MicrosoftDocs/OfficeDocs-Support#1006]
I'd like to ask why there has been a change to the way Outlook on mobile devices approves certificates. 

In accordance with [this Office.com support article](https://support.microsoft.com/en-gb/office/you-can-t-sign-in-to-office-mobile-by-using-an-android-device-156c048d-79e4-4278-84a1-60dec34fa16b) it is purpotedly possible to trust your own root CA on the device, then sign into the Outlook app without the invalid certificate warning. The information provided in [this documentation](https://docs.microsoft.com/en-us/exchange/troubleshoot/client-connectivity/insecure-connection-secure-connection-unavailable-outlook-ios-android) from Microsoft now contradicts this and gives administrators no option to work around this new software limitation.

I further suspect no consideration was made by Microsoft on the user-facing impact of this.

**Comment by dariomws** [comment]
Hi @BestBackwards, thank you for your feedback.

The first article doesn't mention Outlook mobile, and it's related to Office apps. When you use Outlook mobile to connect to Exchange Online and Exchange Server on-premises, it relies on the cloud, so it'll trust the Certification Authority.
If you need to connect to a non-Exchange service, I think you should be able to add your own trusted root CA certificate to the Android store.

**Comment by BestBackwards** [comment]
@dariomws This image from the first linked documentation contains Outlook https://support.content.office.net/en-us/media/025d5c35-7516-437b-8417-5cc21e82cc3f.png.

**Comment by dariomws** [comment]
@BestBackwards did you try to add the root CA to your mobile device? What services or servers are you adding to Outlook mobile?

**Comment by nam31** [comment]
@BestBackwards We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

**Comment by BestBackwards** [comment]
Apologies, thought it was implied. 

1. Added Enterprise CA certificate to the device and confirmed this was installed by visiting HTTPS web pages on the device (protected with a certificate issued by the installed CA) proving it trusts the CA.
2. When trying to add the Outlook mailbox for an account on a self-hosted Exchange environment (protected with a certificate issued by the installed CA) the certificate is not trusted because the Outlook app does not read certificates from the device's locally trusted CAs.

Either this is expected behaviour, or this is a fault. 

Please could you try this yourself, using a certificate issued by a non-public CA? We have been using Active Directory Certificate Services to generate the Exchange cert.

**Comment by dariomws** [comment]
I think the best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information provided at [Get support](https://docs.microsoft.com/microsoft-365/business-video/get-help-support). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness). Here we are limited to documentation issues and improvements.
