### ISSUE TITLE
Where is the "\Temp" folder located?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-Support#101]
This statement, "Office Setup automatically creates log files in your \Temp folder." doesn't exactly point me to the location of the log files. I'm installing Office using Intune on windows 10 pro. No logs were generated in "%temp%" or "%systemroot%\temp" when logged in as the assigned intune user. Intune probably doesn't run the installer as the local user, but the Intune support team wasn't sure where to find the logs other than pointing me to this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 214f1cfc-f6e3-d85a-3035-817b66fba1a9
* Version Independent ID: 3f7252d1-99a9-258d-77c9-e1018ac82ce3
* Content: [How to use a setup log to troubleshoot setup problems in Office - Office](https://docs.microsoft.com/en-us/office/troubleshoot/activation-installation/office-setup-issues)
* Content Source: [Office/Client/activation-installation/office-setup-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/activation-installation/office-setup-issues.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by ofortun** [comment]
I had Click to Run setup logs in the C:\Windows\Temp folder named after the computer name then hyphenated by a date/time stamp. Good luck.

**Comment by MaryQiu1987** [comment]
Fixed the issue
