### ISSUE TITLE
Guid should contain 32 digits with 4 dashes

### ISSUE THREAD

**Issue by phvogel** [MicrosoftDocs/OfficeDocs-Support#1010]
I cannot directly set the GUID as described in this article, and receive the following error:
Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).

Instead I had to do a [Guid]::Parse() first:

$guid = [Guid]::Parse("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")
Set-RemoteMailbox -Identity "my.mailbox@customer.com" -ExchangeGuid $guid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a372b7df-1bff-a6cd-b1d6-261bf08167da
* Version Independent ID: 9a651a1d-a044-ebb1-b9a2-e60834bd9ed9
* Content: [MigrationPermanentException when moving mailbox - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/move-mailboxes/migrationpermanentexception-when-moving-mailboxes)
* Content Source: [Exchange/ExchangeHybrid/move-mailboxes/migrationpermanentexception-when-moving-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/move-mailboxes/migrationpermanentexception-when-moving-mailboxes.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by phvogel** [comment]
Actually its [Guid]"xxxxxxxx-..."

**Comment by msbemba** [comment]
@phvogel Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1375

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1375 
Thank you
