### ISSUE TITLE
Remove-DistributionGroupMember not recognized

### ISSUE THREAD

**Issue by mhughes-l1** [MicrosoftDocs/OfficeDocs-Support#1012]
Remove-DistributionGroupMember is not recognized in Powershell.
_Remove-DistributionGroupMember : The term 'Remove-DistributionGroupMember' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again._

Powershell Version - 5.1.14409.1018
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f28407b-5739-ee8c-7127-9f05473c4260
* Version Independent ID: 8fecff9b-57bf-4c44-3118-fea874bb5962
* Content: [Can't remove members that exceed the limit - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/groups-and-distribution-lists/cannot-remove-members-exceeding-limit)
* Content Source: [Exchange/ExchangeOnline/groups-and-distribution-lists/cannot-remove-members-exceeding-limit.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/groups-and-distribution-lists/cannot-remove-members-exceeding-limit.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment and feedback. For the cmdlet, you can see [Remove-DistributionGroupMember](https://docs.microsoft.com/powershell/module/exchange/remove-distributiongroupmember?view=exchange-ps) for more information.
