### ISSUE TITLE
View search popularity report

### ISSUE THREAD

**Issue by Kyrryl** [MicrosoftDocs/OfficeDocs-Support#1013]
Hi! In the article it is not mentioned where users can find search popularity (for example, top query for the day) reports. Popularity trends it is a different feature. 

Could you please fill the iniformation on timely manner? Since as a support engineer, it is hard to explain customer regarding lack of the information.

Thanks in advance.
Kind regards,
Kyryl

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c72bac10-5200-d1b3-1ec7-cf1acadeb576
* Version Independent ID: 06e4868b-61fc-0f91-1e49-50ba9e50864d
* Content: [Classic usage and popularity reports to be discontinued - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sites/classic-usage-popularity-reports-discontinued#feedback)
* Content Source: [SharePoint/SharePointOnline/sites/classic-usage-popularity-reports-discontinued.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sites/classic-usage-popularity-reports-discontinued.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @AnupamFrancis
* Microsoft Alias: **anfra**

**Comment by VLG17** [comment]
Hi @Kyrryl , do you need more than what's under "Site settings > Popularity trends > Usage" or what you can call using the [GetItemAnalytics Graph API](https://docs.microsoft.com/en-us/graph/api/itemanalytics-get).

Are you looking for a way to search these reports? According to [this article](https://docs.microsoft.com/en-us/sharepoint/view-search-usage-reports), you could use **Site > Site Settings > Site collection Administration > Search Reports** where you can access and download usage data for the last 31 days and past 12 months

It will help you get answers to the following questions, which is what you are looking for, right?

> What are the top queries on my site per day or per month?

> How many search queries are users performing on average?

> Which queries are getting low clicks as they're simply not showing up in any results?

> How often are query rules firing and how often are people clicking promoted results?

**Comment by VLG17** [comment]
@Kyrryl did the information provided above help answer your questions?

**Comment by nam31** [comment]
@Kyrryl We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you
