### ISSUE TITLE
A formula returns "#VALUE!": Error applies to Microsoft 365 Apps for enterprise as well

### ISSUE THREAD

**Issue by gusai-streamroot** [MicrosoftDocs/OfficeDocs-Support#1014]
Issue [SUMIF, COUNTIF, and COUNTBLANK functions return "#VALUE!" Error](https://docs.microsoft.com/en-gb/office/troubleshoot/excel/formula-returns-value-error) affects "Microsoft 365 Apps for enterprise" as well.

Need to add this into section:
`Applies to:
Microsoft Office Excel 2007, Microsoft Excel 2002 Standard Edition, Microsoft Excel 2000 Standard Edition, Microsoft Excel 2010, Microsoft Excel 2013`

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7da49aac-ffac-0815-8cfe-869513b56552
* Version Independent ID: 933d4922-5463-03a2-7faa-f3e5d50a875c
* Content: [Formula returns '#VALUE!' error - Office](https://docs.microsoft.com/en-gb/office/troubleshoot/excel/formula-returns-value-error#feedback)
* Content Source: [Office/Client/excel/formula-returns-value-error.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/formula-returns-value-error.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments. As the article applies to Excel, **Excel for Office 365** is added to the Applies to section.
