### ISSUE TITLE
"Applies to" section should be corrected to SharePoint Online only

### ISSUE THREAD

**Issue by takawazo** [MicrosoftDocs/OfficeDocs-Support#1015]
In the section of "Applies to", it should have only "SharePoint Online"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a93f5a-6e89-4811-9c34-41932077e4eb
* Version Independent ID: 7598878f-e9b4-2fc7-f20a-37438e010dc1
* Content: [Everyone except external users group is removed on Office 365 - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sharing-and-permissions/everyone-except-external-user-removed)
* Content Source: [SharePoint/SharePointOnline/sharing-and-permissions/everyone-except-external-user-removed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sharing-and-permissions/everyone-except-external-user-removed.md)
* Service: **sharepoint-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments. The article is updated.
