### ISSUE TITLE
no HELP file in Excel 2016

### ISSUE THREAD

**Issue by danbromberg** [MicrosoftDocs/OfficeDocs-Support#1016]
My **Excel 2016** works just fine except there is no HELP file (i.e., PF1 does not work).
Will the Registry changes described in [this article](https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/office-feature-disabled) fix this problem?
Thanks,
Dan
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 997991a1-a38a-155a-1c6d-c71a878fea4b
* Version Independent ID: 3510de34-861f-de2d-821d-6e5e2431a4dd
* Content: [This feature has been disabled by your administrator error in Microsoft Office - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/office-feature-disabled)
* Content Source: [Microsoft365/admin/access-management/office-feature-disabled.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/access-management/office-feature-disabled.md)
* Service: **sharepoint-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. You can reference [Where is the product Help in Office](https://support.microsoft.com/office/199950c6-1260-44fe-ba2e-e95968d05397) or contact [Excel Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.excel) for more help.

**Comment by danbromberg** [comment]
Simonxjx:
 Why did you close my issue?!? What you suggested still does **NOT** allow me to use HELP within Excel ?!? So thanks for your suggestion but it did not solve my problem with Excel.
 Shouldn't I (the originator of this issue) be the only one allowed to close the issue I opened?!?
Dan

**Comment by simonxjx** [comment]
If the issue presists, can you contact [Excel Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.excel) for more help

**Comment by danbromberg** [comment]
Thank you for your response.
Dan

**Comment by nam31** [comment]
Hi @danbromberg , are you still facing the issue reported here?

**Comment by danbromberg** [comment]
This issue was resolved, but I have a new Excel issue: all my images in a
sheet were replaced with an error message: "THE IMAGE PART WITH
RELATIONSHIP ID WAS NOT FOUND IN THE FILE".

I have no idea why they vanished?!?!
Dan

**Comment by nam31** [comment]
@danbromberg The best way to get your issue resolved is to contact Microsoft Support. 
If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 
Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
