### ISSUE TITLE
Sign in loop instructions for Google Chrome wrong

### ISSUE THREAD

**Issue by ngbrown** [MicrosoftDocs/OfficeDocs-Support#1017]
The instructions for enabling third party cookies for Google Chrome at https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#google-chrome seem to be at least partially for Internet Explorer.

The correct instructions would refer to the Chrome Settings and searching for "cookies", much like the [Microsoft Edge instructions](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#microsoft-edge).

The text:

```
1. In Windows Control Panel, open Internet Options.

2. In the Internet Options window, select Security > Trusted Sites > Sites.

3. Add the following sites:
```

should be something like this:

```
In the Chrome Settings window, select Cookies and other site data.

In the same window, under Sites that can always use cookies, select Add to add the following sites. Check "Including third-party cookies on this site":
```

![Screenshot - 2021-01-08_11-57-45](https://user-images.githubusercontent.com/228987/104053575-c10ad400-51a8-11eb-975b-c47099328f40.png)
![Screenshot - 2021-01-08_11-58-30](https://user-images.githubusercontent.com/228987/104053637-db44b200-51a8-11eb-82aa-f90acc369685.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c17faf2-0e38-0a98-454c-3c2c4387b37f
* Version Independent ID: d9153b98-dc39-fdd1-a798-07da0caaaa64
* Content: [Microsoft Teams is stuck in a login loop in Edge, Internet Explorer or Google Chrome - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#resolution)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment and feedback. The article is updated accordingly.
