### ISSUE TITLE
macOS Outlook open shared calendars doesn't work

### ISSUE THREAD

**Issue by nadworny** [MicrosoftDocs/OfficeDocs-Support#1018]
Unfortunately, this workaround doesn't work with Outlook 16.46 (and the current non-beta version) as "Group similar folders..." is not available:
![image](https://user-images.githubusercontent.com/1425919/104194978-56fd6380-5422-11eb-88b2-494a0fb72ca9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93d47644-35c4-308b-e8f4-d1ab20ff3199
* Version Independent ID: 3c2e669e-16a5-1424-f56a-58eb5409d7e9
* Content: [Open Shared Calendar option is unavailable - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/calendars/cannot-open-a-shared-calendar-in-outlook-2016)
* Content Source: [Outlook/Mac/calendars/cannot-open-a-shared-calendar-in-outlook-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Mac/calendars/cannot-open-a-shared-calendar-in-outlook-2016.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. If the workaound doesn't work, you can contact [Outlook Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=6dd15f3c-b096-436f-95dc-6f4ad08e1980) for more help.

**Comment by msbemba** [comment]
@nadworny Thank you for your f@eedback. This document applies to outlook 2016. I have added a note to the document stating if you are using Outlook 2019 the option is replaced with show all mail account fodlers. This can be tracked via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1418

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1418 
Thank you

**Comment by nadworny** [comment]
Thank you, it works already with the newest version.
