### ISSUE TITLE
mistake in instructions?

### ISSUE THREAD

**Issue by saraporter** [MicrosoftDocs/OfficeDocs-Support#1019]
I think the directions in this article are wrong and it is supposed to be Add and not Remove.  If it doesn't have text/html then you wouldn't need to remove it-  take a look at this- https://docs.microsoft.com/en-us/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps

-AllowedMimeTypes

The AllowedMimeTypes parameter specifies the MIME extensions of attachments that allow the attachments to be saved locally or viewed from Outlook on the web. The default values are:

	image/bmp
	image/gif
	image/jpeg
	image/png

To enter multiple values and overwrite any existing entries, use the following syntax: Value1,Value2,...ValueN. If the values contain spaces or otherwise require quotation marks, use the following syntax: "Value1","Value2",..."ValueN".
To add or remove one or more values without affecting any existing entries, use the following syntax: @{Add="Value1","Value2"...; Remove="Value3","Value4"...}.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b95f13c4-bcf9-5c41-784d-18ec336e2559
* Version Independent ID: 4dec44a0-03d4-42c7-6dfc-71ce099bd995
* Content: [We can't display your message right now error in Outlook Web App - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/office-message-encryption/cannot-display-message)
* Content Source: [Microsoft365/compliance/office-message-encryption/cannot-display-message.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/compliance/office-message-encryption/cannot-display-message.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello @saraporter ,
I believe removing is a correct action here. It states that "To resolve this problem, reset the MIME types that are associated with the default Outlook Web App policy to the default values." and by default, text/html is not in the AllowedMimeTypes list.
Thank you!

**Comment by nam31** [comment]
@saraporter Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
