### ISSUE TITLE
MFA didn't work

### ISSUE THREAD

**Issue by comradechrome** [MicrosoftDocs/OfficeDocs-Support#1020]
[Enter feedback here]
I'm getting error 456, but disabling MFA did not fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d04aaf0-5d39-1120-a22d-a183f2c4bcbe
* Version Independent ID: 6b3b2e31-7bd9-6de4-6384-80c992997a12
* Content: [Can't set up Office 365 account in Outlook - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/profiles-and-accounts/cannot-set-up-office-365-account-outlook)
* Content Source: [Outlook/Client/profiles-and-accounts/cannot-set-up-office-365-account-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/profiles-and-accounts/cannot-set-up-office-365-account-outlook.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by AmandaAZ** [comment]
Thanks for contacting Microsoft. I understand that the issue can't fixed by this article. If it is the case, you can contact [Outlook Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.outlook) for more help.
