### ISSUE TITLE
Errors in powershell

### ISSUE THREAD

**Issue by SharePointMichael** [MicrosoftDocs/OfficeDocs-Support#1021]
The powershell and article on this page are incorrect.  First in the first script it says to replace {0} in the script but there is no {0}. Instead it should say replace "webapplication" with the name of your web application.

If you copy the code in the second block the line that says $Guid = [guid]::NewGuid() foreach ($Issuer in $Issuers) doesn't work, you have to hit enter before the foreach and put it on its own line or it wont run.

On the line $NameCopy = $Issuer.Name  $NewIssuerName = $Guid   there should be a carriage return before  $NewIssuerName = $Guid

--- 
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c80eda87-604d-e321-9754-c9f0447513c4
* Version Independent ID: 96f8b7ae-aceb-4b53-cccd-4a994081fdad
* Content: [Provider-hosted add-ins stop working and HTTP 401 error after you configure SharePoint farm hybrid features - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/provider-hosted-add-ins-stop-working-and-http-401-error-after-configure-farm-hybrid-features)
* Content Source: [SharePoint/SharePointServer/administration/provider-hosted-add-ins-stop-working-and-http-401-error-after-configure-farm-hybrid-features.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointServer/administration/provider-hosted-add-ins-stop-working-and-http-401-error-after-configure-farm-hybrid-features.md)
* Service: **sharepoint-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments. The article is updated.
