### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by matthew-richards** [MicrosoftDocs/OfficeDocs-Support#1024]
The registry key referred to as:

HKEY_CURRENT_USER\software\Policies\microsoft\windows\CurrentVersion\Internet

Should be: 

HKEY_CURRENT_USER\software\Policies\microsoft\windows\CurrentVersion\Internet Explorer

I was bug testing some PowerShell and noticed the discrepancy. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5d6d6a1-58c6-e610-06fd-38ff027772f9
* Version Independent ID: 1c6cf9e9-0a72-6f13-d0bc-20f9261492ee
* Content: [HTTPS linked images in HTML emails display the red X - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/message-body/https-linked-images-in-html-emails-show-red-x)
* Content Source: [Outlook/Client/message-body/https-linked-images-in-html-emails-show-red-x.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/https-linked-images-in-html-emails-show-red-x.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@matthew-richards , i  enabled this policy via group policy editor, and i conformed those registry keys are specified in the article is correct.

**Comment by MaratMussabekov** [comment]
Hello,
just checked it, the provided in the article registry path is correct.
Thank you

**Comment by nam31** [comment]
@matthew-richards Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
