### ISSUE TITLE
Check your database

### ISSUE THREAD

**Issue by aaronhamilton** [MicrosoftDocs/OfficeDocs-Support#1025]
This error also appears when your SharePoint database server has run out of space. Definitely check that first !!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8a8160-6b6e-7d8c-4ce8-4b91de15239e
* Version Independent ID: 84d69666-3c35-03e1-be70-eea2d5d3e33d
* Content: [The URL is invalid error when you upload a file to a SharePoint list - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/lists-and-libraries/url-invalid-upload-file-to-list)
* Content Source: [SharePoint/SharePointOnline/lists-and-libraries/url-invalid-upload-file-to-list.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/lists-and-libraries/url-invalid-upload-file-to-list.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@nam31 working on this one.
