### ISSUE TITLE
Add Office 365 for Government domain to list of exclusion 

### ISSUE THREAD

**Issue by ianmf6** [MicrosoftDocs/OfficeDocs-Support#1026]
[Enter feedback here]

The following domain needs to be included in the exclusion list for Micrisoft Teams to work on Government instance when blocking third party cookies.

[*.]microsoft.us
[*.]microsoftonline.us

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c17faf2-0e38-0a98-454c-3c2c4387b37f
* Version Independent ID: d9153b98-dc39-fdd1-a798-07da0caaaa64
* Content: [Microsoft Teams is stuck in a login loop in Edge, Internet Explorer or Google Chrome - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#resolution)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
Closing via #1453 
Thank you
