### ISSUE TITLE
Additional Scenario to Add

### ISSUE THREAD

**Issue by robsaddler** [MicrosoftDocs/OfficeDocs-Support#1028]
This also happens when pasting from Excel to an Access table when the source worksheet name contains a single quote.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85483394-0194-dbb2-3261-63bdba0d0e6d
* Version Independent ID: 9770a875-4f9f-46f3-a601-5bbfa5a759da
* Content: [Unable to copy and paste from Excel into Access - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/clipboard-data-damaged)
* Content Source: [Office/Client/access/clipboard-data-damaged.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/clipboard-data-damaged.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by MaratMussabekov** [comment]
Hello, checked, when sheet contains single quote, I cannot paste, when worksheet contains it - working ok. Can you please check again?
Thank you

**Comment by MaratMussabekov** [comment]
Hello @robsaddler ,
did you have time to check it?
Thank you

**Comment by nam31** [comment]
@robsaddler We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
