### ISSUE TITLE
Doesn't launch, no output

### ISSUE THREAD

**Issue by Sbatushe** [MicrosoftDocs/OfficeDocs-Support#1029]
Doesn't launch at all, no debug messages. 
I installed the .deb package using gdebi, theese are my specs:

```
 root@T410
 OS: Debian 10 buster
 Kernel: x86_64 Linux 4.19.0-13-amd64
 Uptime: 1h 12m
 Packages: 2003
 Shell: fish 3.0.2
 Resolution: 1440x900
 DE: XFCE
 WM: i3
 GTK Theme: Arc-Darkest-Solarized [GTK2]
 Icon Theme: Vibrancy-Full-Dark-Blue
 Font: Noto Sans 11
 CPU: Intel Core i7 M 620 @ 4x 2.667GHz [50.0°C]
 GPU: NVS 3100M
 RAM: 981MiB / 7838MiB
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3cd9606-53da-774d-da5c-e5d1ac271958
* Version Independent ID: bc9b5be3-bd0a-96e6-1281-639a46904ff9
* Content: [Known issues for Teams when run on Linux - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/known-issues/linux-known-issues)
* Content Source: [Teams/known-issues/linux-known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/known-issues/linux-known-issues.md)
* Service: **msteams**
* GitHub Login: @McCoyBot
* Microsoft Alias: **v-todmc**

**Comment by Sbatushe** [comment]
Managed to fix it, I don't know the cause of the problem, but flatpak version is working

**Comment by nam31** [comment]
@Sbatushe The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content
Thank you.

**Comment by nam31** [comment]
@Sbatushe Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
