### ISSUE TITLE
Word could not create the work file. Check the temp environment variable

### ISSUE THREAD

**Issue by fmbakop** [MicrosoftDocs/OfficeDocs-Support#103]
![Word issue](https://user-images.githubusercontent.com/54575882/63755656-f8782980-c8ae-11e9-8744-97c7c0db8fe6.PNG)

Hi Team,

One of my user is currently experiencing the attached issue.i went through the following troubleshooting steps:
- Office repair has not worked ( quick and online) 
– Went to the following location: C:\Users\%USERPROFILE%\AppData\Local\Microsoft\Windows, INetCacheContent.Word folder already exist 
-Via Regedit, check that the cache location was (INetCacheContent.Word ). all seems in order.

i even deleted all documents from the Temp folder in the C: drive.

Is there a fix. Now i know that turning off the Preview panel option will stop the opo up from appearing but in this case that is not an option.

**Comment by nam31** [comment]
@fmbakop The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@fmbakop We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
