### ISSUE TITLE
It dosen't make sense , this is Ms Access

### ISSUE THREAD

**Issue by nathanaelmbale** [MicrosoftDocs/OfficeDocs-Support#1030]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 118e8ff5-12e2-b81b-cc54-34481d906811
* Version Independent ID: bbdf3df0-60b9-8fce-9a70-2f7a0fc65f85
* Content: [Query must have at least one destination field error when you run a query - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/query-must-have-at-least-one-destination-field)
* Content Source: [Office/Client/access/query-must-have-at-least-one-destination-field.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/query-must-have-at-least-one-destination-field.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your feedback and comment. Can you proivde more details? If the workaround does not work, you can contact [Access Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.access) for more help.

**Comment by nam31** [comment]
@nathanaelmbale The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content ?
Thank you.

**Comment by nam31** [comment]
@nathanaelmbale We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
