### ISSUE TITLE
Directions are incomplete - don't say how to find slide with missing fonts.

### ISSUE THREAD

**Issue by markhayworth** [MicrosoftDocs/OfficeDocs-Support#1033]
Directions on page do not say that it does not work unless you are viewing the page with the missing fonts.  How do I locate the slides with the missing fonts?  I have over a hundred slides and about 10 missing fonts.  Why can't I replace them all at once?  Now I'm going to have to check each of almost 200 slides to see if the missing fonts are on that slide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 866a99af-58d6-feea-ed84-25c2cfc12046
* Version Independent ID: ca6c58ef-b872-f7db-5c03-e30641a38c40
* Content: [Some fonts are not embedded when you save a PowerPoint 2010 or above presentation in an earlier format - Office](https://docs.microsoft.com/en-us/office/troubleshoot/powerpoint/fonts-not-embedded)
* Content Source: [Office/Client/powerpoint/fonts-not-embedded.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/powerpoint/fonts-not-embedded.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. If the workaround does not help your issue, you can contact [PowerPoint Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.powerpoint) for more help.
