### ISSUE TITLE
Missing info

### ISSUE THREAD

**Issue by rfoust** [MicrosoftDocs/OfficeDocs-Support#1038]
So it says " In order to recover the mailbox, the user must relicense the Azure user object. That will reconnect the mailbox as long as it's within 30 days from the disconnect date." **but it doesn't explain how to disable the Exchange license on the user and have the mailbox go into a soft deleted state.** Or more specifically, I just want to know that a re-attachable mailbox still exists.

Using this method, there is no way to know that an existing "hard-deleted" mailbox exists. This is problematic because if temp contractor leaves a PHI-related job role and within 30 days comes back to a new unrelated job, there's no way to know that potential PHI data will be retained and carried over when the mailbox is re-provisioned (in my case we're in a hybrid environment).  It will just reattach the old mailbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f4294ff-0cd4-adbf-f036-5497a4a00bc2
* Version Independent ID: a69cba1b-af58-021c-6cb3-7a2a33e85251
* Content: [No soft-deleted mailbox after license removal - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/user-and-shared-mailboxes/no-soft-deleted-mailbox-after-license-removal)
* Content Source: [Exchange/ExchangeOnline/user-and-shared-mailboxes/no-soft-deleted-mailbox-after-license-removal.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/user-and-shared-mailboxes/no-soft-deleted-mailbox-after-license-removal.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. If the article does not help, you can contact [support](https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide) for more help.
