### ISSUE TITLE
Skype for Business update fails - make an uninstaller.

### ISSUE THREAD

**Issue by JGFMK** [MicrosoftDocs/OfficeDocs-Support#1039]
[Enter feedback here]

Skype for business does not update correctly. Please produce a dmg or pkg to automate these steps - so I can re-instant and not be bombarded with update notifications that never complete successfully
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5738299a-feb3-740e-aa42-5814f797a607
* Version Independent ID: e5373833-2a2e-0c3b-03fb-933de37c0d42
* Content: [How to do a clean uninstallation of Skype for Business on Mac - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/server-install-or-uninstall/clean-uninstallation)
* Content Source: [SkypeforBusiness/SkypeServer/server-install-or-uninstall/clean-uninstallation.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeServer/server-install-or-uninstall/clean-uninstallation.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your feedback. You can try to uninstall Skype for Business via [here](https://support.microsoft.com/office/uninstall-skype-for-business-28c4a036-7f22-406c-b7f4-87894cbaf902#OS_Type=Mac). If it still does not help, you can contact [SFB support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.skype-for-business) for more help.

**Comment by nam31** [comment]
@JGFMK Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
