### ISSUE TITLE
"Submit and view feedback for this product" links to SharePoint UserVoice, not OneDrive

### ISSUE THREAD

**Issue by joshtransient** [MicrosoftDocs/OfficeDocs-Support#1040]
Button to the left of the one I clicked to get here ("This product") links to SharePoint's UserVoice, which does not have OneDrive categories. Recommend updating this to onedrive.uservoice.com instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81263839-b5c0-3024-8d33-43bbf6dc8170
* Version Independent ID: ed15d83f-a2c2-e808-309d-496483772ae0
* Content: [Troubleshoot OneDrive for Business sync issues - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sync/troubleshoot-sync-issues#repair-a-sync-connection)
* Content Source: [SharePoint/OneDrive/sync/troubleshoot-sync-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/OneDrive/sync/troubleshoot-sync-issues.md)
* Product: **onedrive**
* GitHub Login: @lucciz01
* Microsoft Alias: **v-zolu**

**Comment by jlriesco** [comment]
This is a good suggestion. We'll update the article with it.
Thank you,
Jose
