### ISSUE TITLE
Upload blocked - for no reason - out of nowhere

### ISSUE THREAD

**Issue by mntorq** [MicrosoftDocs/OfficeDocs-Support#1041]
This is needlessly strict.  This worked until recently.

There should be no issue having a OneDrive for Business and Personal account.  

Access to the file & the sync belongs to the folder it lives in.  

Get this fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5e0ee51-7cae-be88-5932-f40100e29140
* Version Independent ID: fdd0a8cb-3f97-a9e3-72d3-15a5db334a8e
* Content: [Office 365 (Upload blocked) error when syncing between different tenants in OneDrive - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sync/upload-blocked-error-in-o365)
* Content Source: [SharePoint/OneDrive/sync/upload-blocked-error-in-o365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/OneDrive/sync/upload-blocked-error-in-o365.md)
* Product: **onedrive**
* GitHub Login: @McCoyBot
* Microsoft Alias: **v-todmc**

**Comment by RAJU2529** [comment]
@mntorq . Any error messages you have received?

**Comment by mntorq** [comment]
At the top, this only occurs in Visio:

**UPLOAD BLOCKED**   We ran into a problem with this file and can't save any new changes.  Please save a copy to avoid losing your work.  [Save a Copy] 

Save a Copy is a button.

I just tested it - and if I modify the diagram - and manually hit Save, it does save & sync in OneDrive

**Comment by RAJU2529** [comment]
@mntorq . please verify, is there modified settings in Group policy editor for visio suite and also check visio related registry keys.
Also check the full settings in Visio settings throughout.

**Comment by mntorq** [comment]
My PC is not subject to corporate Group Policy, and I've not set any manually that would alter this behavior.

I do not see any Visio reg entries beyond InstallRoot, ConfigChangeID
Quite a few under Experimental, but nothing intelligible.

**Comment by RAJU2529** [comment]
@mntorq . in this record video and upload in online storage and paste the link here.
it will be useful to give solutions from Visio Expert users.

**Comment by amincoo21** [comment]
If ur using One drive for desktop and you get the ( Upload blocked ) message on 365 Office - Open your web browser login to office 365 - select Onedrive - select the profile icon top right and log out from Onedrive (just from Onedrive). reopen your office product and message should be gone

**Comment by VLG17** [comment]
@mntorq This should have been fixed in a previous release, according to [this thread](https://techcommunity.microsoft.com/t5/office-365/visio-files-saved-in-onedrive-cause-upload-blocked-error/m-p/2131456/page/2). Are you still seeing this issue, or can you also confirm it's fixed?

**Comment by mntorq** [comment]
I have not experienced the issue recently - I'm guessing it's been fixed.

Thanks,
John

________________________________

**Comment by RAJU2529** [comment]
@mntorq . Then close this issue from your side.

**Comment by VLG17** [comment]
@mntorq thank you for your reply. Is it ok if we go ahead and close this issue?

**Comment by mntorq** [comment]
Yes, I have not experienced the issue in a while.  It must have been patched out.

________________________________
