### ISSUE TITLE
Document Update Request - The Note section regarding mailbox redirect rule needs more explanation

### ISSUE THREAD

**Issue by qaehtesh** [MicrosoftDocs/OfficeDocs-Support#1042]
Document Update Request - The Note section regarding mailbox redirect rule needs more explanation.
I have customer raising concern that the  Note section regarding mailbox redirect rule needs more explanation perhaps with an example as this redirect rule skipping transport rule could result in potential security risk.

Proposed example of an explanation for Note section is  as below,

---
ーーーーーーーーー
Note-
When redirected by an Outlook or OotW redirect rule, the sender evaluated by the transport rule is the sender of the original email and not the mailbox on which the rule is set.

Example-When blocking automatic forwarding in a transport rule, redirected emails may not be blocked if the sender property is added as a condition as shown below.

Example:
Conditions to apply this rule
If the message: Is of the following types: Auto-forward
And the property specified by the sender contains the following words CustomAttribute1: BlockAutoForward
Take the following actions:Reject the message with a description: "Auto Forward is prohibited."
ーーーーーーーーー

Please review and accommodate if feasible.
This is also part of following RFC with engineering team(https://o365exchange.visualstudio.com/DefaultCollection/IP%20Engineering/_workitems/edit/1846049)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83fdda33-b6a9-4aea-e53e-d663f5638ff0
* Version Independent ID: e7e651c2-384a-5714-09a8-b8880152bed3
* Content: [A transport rule doesn't match if user mailbox rules automatically forward messages - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/email-delivery/autoforward-mail-exclusions-not-honored-transport-rule)
* Content Source: [Exchange/ExchangeOnline/email-delivery/autoforward-mail-exclusions-not-honored-transport-rule.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/email-delivery/autoforward-mail-exclusions-not-honored-transport-rule.md)
* Service: **exchange-online**
* GitHub Login: @TobyTu
* Microsoft Alias: **arindamt**

**Comment by msbemba** [comment]
@qaehtesh Thank you for your feedback. We have added more information to the note via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1390

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1390
Thank you
