### ISSUE TITLE
REALLY HELPFUL

### ISSUE THREAD

**Issue by Kenastark** [MicrosoftDocs/OfficeDocs-Support#1046]
[Easy to follow steps but i believe a mistake was made to the new group name. It should be "Administer" instead of the word "Switchboard" as the article stated. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33820164-58cc-8b5e-1b85-410444d2f97f
* Version Independent ID: b4066df3-70eb-97d7-56b4-b582d4d5843a
* Content: [Switchboard Manager option doesn't appear - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/switchboard-manager-option-disappears)
* Content Source: [Office/Client/access/switchboard-manager-option-disappears.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/switchboard-manager-option-disappears.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by simonxjx** [comment]
Close this one as it is fixed.
