### ISSUE TITLE
Intune option

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/OfficeDocs-Support#1048]
Can you please explain how you would configure the "Cached Exchange Mode Sync Settings" via Intune/MEM.
I want to be able to force Outlook to only cache mail for 3 months (not the default 12 months).

I looked in the built-in Intune admin templates (which I believe come from Outlook 2016 ADMX) but it only has a few settings, crucially not the one that lets you set the time period.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83d3d674-d9a9-f5bb-96c8-17968827e41d
* Version Independent ID: b497b804-c05b-ca61-d773-4e95e27763ab
* Content: [Plan and configure Cached Exchange Mode in Outlook 2016 for Windows - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/installation/cached-exchange-mode#configure-cached-exchange-mode-for-outlook-2016)
* Content Source: [Outlook/Client/Installation/cached-exchange-mode.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/Installation/cached-exchange-mode.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by MaratMussabekov** [comment]
Hello,
you cannot do it directly (at least for now).
I would recommend a workaround - create a script that sets registry keys to configure cached mode and distribute it using MEM (for 3 months, the value of **syncwindowsetting** at **HKEY_CURRENT_USER\software\policies\microsoft\office\16.0\outlook\cached mode** should be 3)

Thank you

**Comment by nam31** [comment]
@thommck Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
