### ISSUE TITLE
Powershell please

### ISSUE THREAD

**Issue by laurentopia** [MicrosoftDocs/OfficeDocs-Support#105]
The GUI is notoriously hard to navigate due to the various generations coexisting with incomplete features, also due to the lack of search and the labyrinthine layout. 
So when providing an information, always include the powershell equivalent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8a8160-6b6e-7d8c-4ce8-4b91de15239e
* Version Independent ID: 84d69666-3c35-03e1-be70-eea2d5d3e33d
* Content: [The URL is invalid error when you upload a file to a SharePoint list - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/lists-and-libraries/url-invalid-upload-file-to-list#feedback)
* Content Source: [SharePoint/SharePointOnline/lists-and-libraries/url-invalid-upload-file-to-list.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/lists-and-libraries/url-invalid-upload-file-to-list.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by claudialake** [comment]
laurentopia, thank you for this feedback. I have forwarded it to the product team.
