### ISSUE TITLE
Unable to export date format fields

### ISSUE THREAD

**Issue by Andy04721** [MicrosoftDocs/OfficeDocs-Support#1050]
Date fields are not exported correctly. It is showing as '#######' in the text file.

**Comment by jlriesco** [comment]
Could you please mention to which article you are referring?
thanks,
Jose

**Comment by nam31** [comment]
@Andy04721 The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@Andy04721 We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
