### ISSUE TITLE
Extremely confusing article

### ISSUE THREAD

**Issue by RDG88** [MicrosoftDocs/OfficeDocs-Support#1051]
Article needs better guidance.
Make it clear that you need the Windows Server Language pack and NOT windows 10 language pack.
Give some guidance how to deploy the Capability offline and that you can use the same cab file for the Capability.

Also put in the article how to set the user language back to en-us...

And don't mix 2 languages with the commands, is confusing:

e.g. 

"c:\temp\Microsoft-Windows-Client-Language-Pack_x64_fr-fr.cab"
/CapabilityName:Language.Basic~~~te-IN~0.0.1.0
??? why use 2 languages

make it more clear like:

DISM /Online /Add-Package /PackagePath:"c:\temp\Microsoft-Windows-Server-Language-Pack_x64_nl-nl.cab"
DISM /Online /Add-Capability /capabilityname:Language.Basic~~~nl-nl~0.0.1.0 /Source:"c:\temp\" /LimitAccess

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98ef6c94-9d80-976f-8f8d-476ec998c860
* Version Independent ID: d5612cca-c87a-761c-90eb-230c527175d7
* Content: [Error (Can't connect. Please try again later) when searching people in OWA in Exchange Server 2019 - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/client-connectivity/can%27t-connect-error-searching-people-owa)
* Content Source: [Exchange/ExchangeServer/client-connectivity/can't-connect-error-searching-people-owa.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/client-connectivity/can't-connect-error-searching-people-owa.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @TobyTu
* Microsoft Alias: **jcoiffin**

**Comment by RAJU2529** [comment]
@RDG88 . Thanks for pointing out.  I will fix now

**Comment by msbemba** [comment]
@RDG88 Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1376

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1376 
Thank you
