### ISSUE TITLE
Should mention non-existent leapyear for 1900 date system

### ISSUE THREAD

**Issue by JNCressey** [MicrosoftDocs/OfficeDocs-Support#1052]
The section for more information about the 1900 date system should mention that it includes the date February 29, 1900. And should explain that for dates after that date, the serial number is 2 more than the number of days since January 1, 1900 - rather than the 1 more that "starting with [a serial number of] 1 for January 1, 1900" would suggest.

1900 not being a leap year is breifly mentioned as a design reason in the 1904 date system information, but, to make any sense of that, a reader would have to already know about the extra day in the 1900 date system.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8462f7c-3fcb-c891-cca9-8c1ff894d4b0
* Version Independent ID: 78b5d0d6-6de5-e495-20a6-c5b9c34046f7
* Content: [Differences between the 1900 and the 1904 date system - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/1900-and-1904-date-system)
* Content Source: [Office/Client/excel/1900-and-1904-date-system.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/1900-and-1904-date-system.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Added a link to: [Excel incorrectly assumes that the year 1900 is a leap year](https://docs.microsoft.com/en-us/office/troubleshoot/excel/1900-and-1904-date-system)
