### ISSUE TITLE
Powershell error

### ISSUE THREAD

**Issue by efpob** [MicrosoftDocs/OfficeDocs-Support#1055]
On Exchange 2013, running the Task Scheduler script gives:

Add-PSSnapIn : Cannot load Windows PowerShell snap-in Microsoft.Exchange.Management.PowerShell.E2010 because of the following error: Could not load file or assembly 'file:///C:\Program File
s\Microsoft\Exchange Server\V15\bin\Microsoft.Exchange.PowerShell.Configuration.dll' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime
and cannot be loaded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91b92936-e70c-50c4-0918-2fe1bb844cde
* Version Independent ID: 23e36a91-085e-21a2-9dbc-a046ea36e430
* Content: [Free/busy lookups stop working - Exchange](https://docs.microsoft.com/en-US/exchange/troubleshoot/calendars/freebusy-lookups-stop-working)
* Content Source: [Exchange/ExchangeHybrid/calendars/freebusy-lookups-stop-working.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/calendars/freebusy-lookups-stop-working.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your feedback and comment. You can check the [TechCenter article](https://social.technet.microsoft.com/Forums/office/en-US/60cb3ed9-94c1-49c0-988b-b6150fcc30c8/runspacespssnapinexception-cannot-load-windows-powershell-snapin-powershelle2010?forum=exchangesvrgeneral) for more information.

**Comment by msbemba** [comment]
@efpob Thank you for your feedback. The reason for the error is: the C# program is targeted for .Net 2.0, while EMS2013 is built by .Net 4.0. Are you still facing any issues with loading the snap-in?

Thanks
Sri

**Comment by efpob** [comment]
Shouldn't this be updated so that the command works with Exchange 2013 and above? Exchange 2010 is no longer supported in hybrid environments

**Comment by nam31** [comment]
Closing via #1683
Thank you
