### ISSUE TITLE
Automate Excel refresh all connections 

### ISSUE THREAD

**Issue by waseemhartak** [MicrosoftDocs/OfficeDocs-Support#1058]
[Enter feedback here]

This way around doesn't support any proper automation through power automate, the only way to automate this process is locally through windows task scheduler which has a lot of limitations and doesn't count as an efficient  way.
I hope a solution will come up soon.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e487-5605-d812-c84c-4fed53011679
* Version Independent ID: 20a863fd-e69e-ae61-5017-ad24a695b660
* Content: [External users cannot refresh data connections from Excel Online - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/excel-online-external-users-cannot-refresh-data-connections)
* Content Source: [Office/OfficeExperts/excel/excel-online-external-users-cannot-refresh-data-connections.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/excel/excel-online-external-users-cannot-refresh-data-connections.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **warrenr**

**Comment by MaryQiu1987** [comment]
You may need to contact [Excel support](https://support.microsoft.com/en-us/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.excel) to check if a solution is ready.
