### ISSUE TITLE
This page contains incorrect syntax

### ISSUE THREAD

**Issue by DemCoders** [MicrosoftDocs/OfficeDocs-Support#1059]
the command used to set-MsolServicePrincipal is incorrect and does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3be1f556-089c-f051-c77c-0d00e2a34e93
* Version Independent ID: c3ad40d2-61bd-d728-f549-aefa0efdc3fa
* Content: [401 Access denied when running Test-OAuthConnectivity - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/401-access-denied-error-when-running-test-oauthconnectivity)
* Content Source: [Exchange/ExchangeOnline/administration/401-access-denied-error-when-running-test-oauthconnectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/administration/401-access-denied-error-when-running-test-oauthconnectivity.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments. You can check the detailed page of the [set-MsolServicePrincipal](https://docs.microsoft.com/powershell/module/msonline/set-msolserviceprincipal?view=azureadps-1.0) cmdlet.

**Comment by DemCoders** [comment]
I got the right syntax. I don’t need help with the issue.  You need to update your page because it’s VERY WRONG.  Not even close to what the solution really is.

Sent from my iPhone

On Jan 28, 2021, at 1:06 AM, Simonx Xu <notifications@github.com> wrote:

﻿

Reopened #1059<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-Support%2Fissues%2F1059&data=04%7C01%7Cd%40barbalios.com%7C145eb9e70dcc49689c1b08d8c352ce29%7C3588b2f638f945d29e2ecc4dcf57d428%7C0%7C0%7C637474107696059614%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ht%2F%2BSHdEp8dVdswvRydsMIaGoaByQEdPcjU0lVOGisM%3D&reserved=0>.

**Comment by msbemba** [comment]
@DemCoders Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1377

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1377
Thank you
