### ISSUE TITLE
Slack, Zoom, and AnyDesk support remote control sessions stating some kind of graphics incompatibility

### ISSUE THREAD

**Issue by tedpenner** [MicrosoftDocs/OfficeDocs-Support#1061]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20956786-4935-bca3-9c57-1f6bb9401da8
* Version Independent ID: 6be80e4f-36bc-6c5d-926c-003132fc4e31
* Content: [Give control doesn't work when you share screen in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-conferencing/give-control-doesn%E2%80%99t-work-sharescreen)
* Content Source: [Teams/teams-conferencing/give-control-doesn’t-work-sharescreen.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-conferencing/give-control-doesn’t-work-sharescreen.md)
* Service: **msteams**
* GitHub Login: @TobyTu
* Microsoft Alias: **sarvdon**

**Comment by msbemba** [comment]
@tedpenner Thank you for your feedback. For the "Give control" feature to work in Teams, hardware acceleration should be supported. We are not aware of any compatibility issues. let us know if you were informed about anything in specific, so we can investigate and document if need be.

Thanks
Sri

**Comment by msbemba** [comment]
@tedpenner Just circling back to check if the issue persists or if you'd like to see an update in the document.

Thanks
Sri

**Comment by nam31** [comment]
@tedpenner We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

**Comment by tedpenner** [comment]
We don't use teams because screen sharing doesn't work right most of the
time, and getting people into teams is frought with all kinds of issues.

The best mix for us is WhatsApp Business because it is incredibly
responsive. It's also much easier to get people in than Microsoft Teams and
it connects directly to Google Contacts. We use it to establish audio and
texting, and we add Zoom for screen sharing as needed.
