### ISSUE TITLE
format PS CMDs wrong

### ISSUE THREAD

**Issue by Joshenou** [MicrosoftDocs/OfficeDocs-Support#1062]
Hello Team,

I found that Method 2 listed on this article has an incorrect format as it shows:
New-RemoteDomaincontoso.com -DomainNamecontoso.comSet-RemoteDomain "contoso.com" -TNEFEnabled $true -AllowedOOFType "InternalLegacy"

The correct format should be:
New-RemoteDomain -DomainName contoso.com Set-RemoteDomain "contoso.com" -TNEFEnabled $true -AllowedOOFType "InternalLegacy"

Thank you,
Jorge

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8aada2c-5bdf-25da-f959-df83bcec96b1
* Version Independent ID: d75554bb-def0-4322-face-db1f13043e64
* Content: [Out-of-office replies and voting options show wrongly - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/send-emails/out-of-office-replies-and-voting-options-appear-incorrectly)
* Content Source: [Exchange/ExchangeHybrid/send-emails/out-of-office-replies-and-voting-options-appear-incorrectly.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/send-emails/out-of-office-replies-and-voting-options-appear-incorrectly.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments, It is fixed.
