### ISSUE TITLE
Link for "Run now" returns 404 file not found in "Fix it for me" section for the page "COM add-ins are not displayed in the COM Add-Ins dialog box in Excel 2013 and Excel 2016"

### ISSUE THREAD

**Issue by paul-barton** [MicrosoftDocs/OfficeDocs-Support#1065]
Link for "[run now](https://go.microsoft.com/fwlink/?linkid=279892)" in the "[Fix it for me](https://docs.microsoft.com/en-us/office/troubleshoot/excel/com-add-ins-not-displayed#fix-it-for-me)" section is broken and end-user receives a [404 file not found error](https://download.microsoft.com/download/5/0/5/505878EB-FFC4-4DF0-A526-B1165BFA6C35/PowerViewAddin.diagcab)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04b68dcc-cad8-ce6d-db63-28bb3bb448ab
* Version Independent ID: 5d41456e-51c0-c4b1-02ad-232f136705e3
* Content: [COM add-ins are not displayed in the COM Add-Ins dialog box - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/com-add-ins-not-displayed)
* Content Source: [Office/Client/excel/com-add-ins-not-displayed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/com-add-ins-not-displayed.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. It is updated.
