### ISSUE TITLE
Why doesn't this article cover Office365 when it is in a folder referring to O365?

### ISSUE THREAD

**Issue by MaV81** [MicrosoftDocs/OfficeDocs-Support#1066]
I don't understand why this article is in a section about Office 365 when it clearly identifies it is relevant for Office 2007 and 2010.
I'm looking for help to disable prompts in Office 365 and keep coming up against brick walls.
This is pretty frustrating.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c90d6f1c-2492-75cc-8e6a-71c9bbdec191
* Version Independent ID: 825ef210-269c-ad98-564b-d5c2eed1560f
* Content: [Enable or disable hyperlink warning messages in Office programs - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/enable-disable-hyperlink-warning)
* Content Source: [Microsoft365/admin/administration/enable-disable-hyperlink-warning.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/enable-disable-hyperlink-warning.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments and feedback. Regarding the prompts in Office 365, You can go to Settings  > Accounts> Access work or school to remove the irrelevant account from your computer. See the [community site](https://answers.microsoft.com/msoffice/forum/msoffice_account-mso_win10-mso_o365b/unwanted-office-365-sign-in-prompts/b1202be2-fa0b-4b2a-b992-902c3487df58?page=0) for more information.

**Comment by MaV81** [comment]
Hi, thanks for your quick response.

I don’t your reply has anything to do with the problem I had.

I was looking for a way to turn off security prompts in Office 365 (ie the ‘this hyperlink might be dangerous, are you sure you want to follow it?’ warning), and looking in the manual for help with Office 365 found your article, however it referred to Office 07 and Office 2010 only (so why is it in the Office 365 section?)

I’m sorry if I didn’t explain the problem properly.  Thanks anyway.

Mark
