### ISSUE TITLE
פיתרון 2 לא פועל

### ISSUE THREAD

**Issue by lionelam12** [MicrosoftDocs/OfficeDocs-Support#1067]
ביצעתי את כל השלבים הREGISTERY וזה לא עזר להחליף מיקום

---
#### פרטי המסמך

⚠ *אין לערוך מקטע זה. פעולה זו נדרשת עבור קישור לנושאים ב- docs.microsoft.com ← GitHub.*

* ID: 9aab602f-f37c-85a1-a063-e2dc70081071
* Version Independent ID: 02bd6670-9886-7ebc-2f2b-048f352d3a37
* Content: [אין אפשרות לשנות את המיקום של קובץ. ost - Outlook](https://docs.microsoft.com/he-il/outlook/troubleshoot/data-files/cannot-change-the-location-of-ost-file)
* Content Source: [Outlook/Client/data-files/cannot-change-the-location-of-ost-file.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/data-files/cannot-change-the-location-of-ost-file.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments. You can change the file location during the first time you set up the profile. You can also contact [Outlook support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.outlook) for more help.
