### ISSUE TITLE
What GPO's can be used to make these settings?

### ISSUE THREAD

**Issue by ShortOrderCookie** [MicrosoftDocs/OfficeDocs-Support#1068]
This KB article seems to be incomplete.
The resolution is to either make manual settings or settings via GPO.
You've provided the manual settings, but not the GPO settings?
For instance, to make the settings in IE's Advanced Privacy Settings, what GPO's would be used to make those settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c17faf2-0e38-0a98-454c-3c2c4387b37f
* Version Independent ID: d9153b98-dc39-fdd1-a798-07da0caaaa64
* Content: [Microsoft Teams is stuck in a login loop in Edge, Internet Explorer or Google Chrome - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#google-chrome)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by dariomws** [comment]
Hi @ShortOrderCookie, thank you for your feedback.

I am working on this issue and will provide you with an update in a few days.
