### ISSUE TITLE
Settings on Edge don't look like on your page

### ISSUE THREAD

**Issue by macosmin** [MicrosoftDocs/OfficeDocs-Support#1069]
I use Microsoft Edge 44.17763.831.0
and the Settings are not opened in a page, but on one side of the browser, 
and all mentioned menus from Edge settings are not visible.
I got to a place where I can see sites, but I can't add more
I followed the path: button '...' from browser menu; Settings; Advanced; Under 'Site settings', under 'Website permissions' on button 'Manage permissions'.
(Note: lots of my workstation's settings are managed by my organization -- maybe this has some involvement of not having the same menu/Settings)

Maybe the section about Edge needs to be updated,
or special cases like mine, when Settings look different needs to be covered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c17faf2-0e38-0a98-454c-3c2c4387b37f
* Version Independent ID: d9153b98-dc39-fdd1-a798-07da0caaaa64
* Content: [Microsoft Teams is stuck in a login loop in Edge, Internet Explorer or Google Chrome - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#resolution)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by sowjanya365** [comment]
Hi @macosmin 

I suggest you to reset Internet explorer settings and then try again! If the problem persists, please contact your local administrator, and if not resolved please contact support team here - https://support.microsoft.com/contactus

Hope this helps! Cheers! 

Thank you!

**Comment by sowjanya365** [comment]
Hi @macosmin 
Please let us know if you still have any question regarding this issue. 

Thanks.

**Comment by macosmin** [comment]
Hello
Thank you for your response.
No more questions from me.
You may close the ticket.

Have a nice day ☀️

**Comment by nam31** [comment]
@macosmin Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
