### ISSUE TITLE
What is the MSO number for?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-Support#107]
I've tried these instructions but Designer still won't log me into O365 SharePoint site.  The only thing that is different with my install of Designer (on current build of Windows 10) is my "About Microsoft SharePoint Designer" listing shows a slightly different MSO (15.0.4569.1506) number than listed here.  I have the latest Designer update per the link listed.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7f9f747-25d0-6471-298b-2a8ca1b74ff6
* Version Independent ID: 65a190ea-2324-7ec8-20a2-f9b98a5d2c60
* Content: [SharePoint Designer 2013 login Issues in a cloud scenario - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/sharing-and-permissions/login-issues-in-a-cloud-scenario)
* Content Source: [SharePoint/SharePointExperts/sharing-and-permissions/login-issues-in-a-cloud-scenario.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointExperts/sharing-and-permissions/login-issues-in-a-cloud-scenario.md)
* Service: **sharepoint-online**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **joergsi**

**Comment by AmandaAZ** [comment]
A solution on this issue has been provided in the "Connection issues" section in this article, so close this issue.
