### ISSUE TITLE
The link is broken to download Dsofile.dll

### ISSUE THREAD

**Issue by kaganova** [MicrosoftDocs/OfficeDocs-Support#1070]
https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/dsofile.dll-allow-edit-document-property
The link to download a package is broken.

**Comment by nam31** [comment]
@kaganova The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content
Thank you.

**Comment by nam31** [comment]
@kaganova We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
