### ISSUE TITLE
Lack of spec and information

### ISSUE THREAD

**Issue by jsandersrocks** [MicrosoftDocs/OfficeDocs-Support#1071]
Office messaging and Office support has no idea how this works.  Can we include a ref or spec on what successful modern auth looks like.  For example.  Azure App Services with Easy Auth does not work.  Why is that?  There is no way to determine what the issue is (and our own products should as the very least work with this).  jsanders   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5d5258-e519-df39-0aa5-57115e0211ab
* Version Independent ID: 01390aa8-7cae-809b-b5e9-567514cc99d8
* Content: [Cannot add an Internet calendar - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/calendaring/cannot-add-an-internet-calendar)
* Content Source: [Outlook/Client/calendaring/cannot-add-an-internet-calendar.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/calendaring/cannot-add-an-internet-calendar.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@jsandersrocks Just circling back to see if you Could you provide more specific information on what you would like to see related to the Internet calendar and outlook?

Thanks
Sri

**Comment by jsandersrocks** [comment]
I'll get with you tomorrow..   jsanders

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by msbemba** [comment]
@jsandersrocks Just circling back to see if you Could provide more specific information on what you would like to see related to the Internet calendar and outlook?

Thanks
Sri

**Comment by nam31** [comment]
@jsandersrocks We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
