### ISSUE TITLE
Doc references outdated Powershell cmdlets

### ISSUE THREAD

**Issue by hmhackmaster** [MicrosoftDocs/OfficeDocs-Support#1072]
This doc has a number of references to outdated or legacy Powershell cmdlets, including the method of connection Exchange Online Powershell (Just using `Connect-ExchangeOnline` seems the more modern method) and it also references `Get-Cloudmailbox`, which I am pretty sure isn't a thing anymore.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1f49302-8af5-dc40-ff24-4d62bc126745
* Version Independent ID: f03ff26f-aca3-6313-f39d-94acca49f150
* Content: [Troubleshoot directory synchronization errors with event 6941 - Office 365](https://docs.microsoft.com/en-US/office365/troubleshoot/active-directory/duplicate-attributes-prevent-dirsync)
* Content Source: [Microsoft365/admin/active-directory/duplicate-attributes-prevent-dirsync.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/active-directory/duplicate-attributes-prevent-dirsync.md)
* Service: **o365-administration**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@hmhackmaster Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1417

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1417
Thank you
