### ISSUE TITLE
Some security issues caused by this behaviour by design

### ISSUE THREAD

**Issue by PeterPesch** [MicrosoftDocs/OfficeDocs-Support#1075]
1. Many Microsoft web services actually tell the User to close all web browser after signing out of that web service.
This often results in the user still being logged in to most of the other services - which is a security problem.

2. Some applications (like Microsoft Azure Devops) use the Single SignOn feature without identifying themselves;
This results in the User getting a 'Microsoft - Pick an account' window which does not tell the user which application they are actually signing in into.
This is especially troublesome for users who start their workday by quickly signing in to their work applications, after having properly signed  out of each of them at the previous workday ...
This would probably urge most users into taking some cutoffs - which is a security problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57691ebf-3011-b41c-3930-64fdbe7a3bc8
* Version Independent ID: afeb5333-1273-e5bd-80cf-061665ed8cbd
* Content: [Problems when signing out of Office 365, Azure, or Intune in a web browser - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/sign-in/cannot-sign-out-cloud-service)
* Content Source: [Microsoft365/admin/sign-in/cannot-sign-out-cloud-service.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/sign-in/cannot-sign-out-cloud-service.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@PeterPesch Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
