### ISSUE TITLE
AutoArchive article sugestion

### ISSUE THREAD

**Issue by a-anchud** [MicrosoftDocs/OfficeDocs-Support#1076]
If an Outlook user has several Exchange Accounts added to a single profile then AutoArchive settings will automatically be applied to all accounts (and hence items from several mailboxes will be moved to .pst). Could this please be added to the article as a note?
Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09a116b-1062-ce85-e849-42acc77bf90b
* Version Independent ID: cf8c17a5-8160-7a6a-6485-645dc5372300
* Content: [Description of the AutoArchive feature - Outlook](https://review.docs.microsoft.com/en-us/outlook/troubleshoot/data-files/description-of-the-autoarchive-feature?source=docs&branch=master)
* Content Source: [Outlook/Client/data-files/description-of-the-autoarchive-feature.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/data-files/description-of-the-autoarchive-feature.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
Closing via #1442 
Thank you
