### ISSUE TITLE
Path is wrong

### ISSUE THREAD

**Issue by campbedj** [MicrosoftDocs/OfficeDocs-Support#1077]
The folder location mentioned in step 2 should be: C:\Users\userprofile\AppData\Local\Microsoft\Windows\INetCache
Then the folder to create in step 3 should be: Content.Word

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f069189a-7af4-d6df-1509-f30af7d3c01d
* Version Independent ID: df260ca7-16dd-d2f8-1de3-91e0b71f67d4
* Content: [Word could not create the work file error message when you save a document - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/word-could-not-create-the-work-file)
* Content Source: [Office/Client/word/word-could-not-create-the-work-file.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/word-could-not-create-the-work-file.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jcrowland** [comment]
This looks right to me too.

**Comment by MaratMussabekov** [comment]
Hello @campbedj ,
please have a look at https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1636
Thank you!

**Comment by nam31** [comment]
Closing via #1636 
Thank you
