### ISSUE TITLE
Trying to remove the annoying Microsoft Anywhere popup

### ISSUE THREAD

**Issue by rolygrit** [MicrosoftDocs/OfficeDocs-Support#1078]
Guess I'm not alone with failing to get rid of the every day "Get Microsoft Anywhere"  popup, even after trying to change two registry keys. Trouble is none of the Mirrosoft methods work. I have Office 365 Home and don't want it on my mobile.
1.The drafts folder has - well drafts and none of the stuff mentioned.
2. The first regedit folder I have edited but the second does not exist
3. The gpedit panel does not have a policies folder
So here I am with irrelevant MS page and a banner I never asked for and cannot remove. All it would take MS is a Never button in the banner, but that's far too simple.
Any help accepted
Phil Duke
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 359383bf-4a8d-a69a-b3d1-1815111f08b3
* Version Independent ID: 180b2b09-cdf7-05ff-e4ef-1bc227a22cfb
* Content: [Remove Get and set up Outlook Mobile app on my phone option - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/installation/how-to-remove-get-and-set-up-outlook-mobile-app-on-my-phone-option)
* Content Source: [Outlook/Client/Installation/how-to-remove-get-and-set-up-outlook-mobile-app-on-my-phone-option.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/Installation/how-to-remove-get-and-set-up-outlook-mobile-app-on-my-phone-option.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. If the article does not work, you can contact [Outlook Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.outlook) for more help.
