### ISSUE TITLE
Update Step 2 to make it easier to Copy and Paste

### ISSUE THREAD

**Issue by benrfairless** [MicrosoftDocs/OfficeDocs-Support#108]
Update Step 2 to say:

Locate the folder location %LOCALAPPDATA%\Microsoft\Windows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93e74201-5f92-5dea-43a7-abc06e04657b
* Version Independent ID: 1425fb4e-4889-8cdc-ef46-d01a31392d73
* Content: [Word could not create the work file error message when you save a document - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/word-could-not-create-the%20work-file#feedback)
* Content Source: [Office/Client/word/word-could-not-create-the%20work-file.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/word-could-not-create-the%20work-file.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@benrfairless , the article has been update here
https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/no-file-previews-file-explorer-switching-to-32-bit
Please let us know if you still want to see this change in the document.
Thank you
