### ISSUE TITLE
Internet Explorer is no longer supported

### ISSUE THREAD

**Issue by aandrew129** [MicrosoftDocs/OfficeDocs-Support#1080]
Internet Explorer is no longer a supported browser. Suggest updating this guide to reflect the supported browsers and remove or update the section instructing users to set Internet Explorer as their default browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 161bf8fc-061e-c244-26a9-d49f2144715f
* Version Independent ID: cf04aa21-cc6c-3c6a-f3ea-ffcf998eb168
* Content: [How to join a Teams meeting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/meetings/how-to-join-a-teams-meeting)
* Content Source: [Teams/meetings/how-to-join-a-teams-meeting.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/meetings/how-to-join-a-teams-meeting.md)
* Service: **msteams**
* GitHub Login: @lucciz01
* Microsoft Alias: **v-zolu**

**Comment by dariomws** [comment]
Hi @aandrew129, thank you for your feedback.

I am working on this issue and will provide you with an update in a few days.
