### ISSUE TITLE
Correct path

### ISSUE THREAD

**Issue by artandrson** [MicrosoftDocs/OfficeDocs-Support#1081]
the path document - %userprofile%\AppData\Local\Microsoft\Teams\stage\squirrel.exe appears to be incorrect. New location is not in the stage folder. Should be %userprofile%\AppData\Local\Microsoft\Teams\squirrel.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23989acb-65f2-d269-66c8-edcdd89c730d
* Version Independent ID: ef65785d-165f-6c91-1e9d-c4e99122c13f
* Content: [How to include or exclude Teams from antivirus or DLP applications - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-administration/include-exclude-teams-from-antivirus-dlp)
* Content Source: [Teams/teams-administration/include-exclude-teams-from-antivirus-dlp.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-administration/include-exclude-teams-from-antivirus-dlp.md)
* Service: **msteams**
* GitHub Login: @McCoyBot
* Microsoft Alias: **v-todmc**

**Comment by VLG17** [comment]
@artandrson I've checked and and path specified in the article appears to be correct (for my Teams client).

![image](https://user-images.githubusercontent.com/41186174/119370650-2fff4a00-bcbe-11eb-8f51-349b4a6d6666.png)

**Comment by nam31** [comment]
@artandrson Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
