### ISSUE TITLE
This is a description, not an explanation

### ISSUE THREAD

**Issue by MichaelBrooks-Version1** [MicrosoftDocs/OfficeDocs-Support#1082]
The author is offering this as an explanation for the behaviour under scrutiny. It is not - it is merely a clarification of the behaviour. An explanation would tell us why someone decided that autocomplete should be disabled in a column with a header. This explanation is needed all the more given that a column with a header will often be an Excel table, and one of the more heavily used features of Excel tables is column filtering. In order for column filtering to work most effectively, users have to stick to standards when entering values into cells. The process of sticking to standards is helped enormously by (you've guessed it) - autocomplete. So logically, the presence of a column header should prompt Excel to enable autocomplete rather than to disable it. The fact that it does the very opposite leaves the poor user wondering what sort of idiot specified this. A proper explanation as to the rationale might (if it's a good explanation) go some way to alleviate the frustration of users and ease their negative impression of Microsoft's product designers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98bb86a0-1e2f-d80a-622c-c0f99fc94c19
* Version Independent ID: 9b9c1944-d206-b1ca-cc28-7e15c0ce1fad
* Content: [Auto-Complete may not work - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/autocomplete-not-work)
* Content Source: [Office/Client/excel/autocomplete-not-work.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/autocomplete-not-work.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by dariomws** [comment]
Hi @MichaelBrooks-Version1, thank you for your feedback and help us to improve docs.microsoft.com.

You're recommending adding a detailed explanation on why Excel behaves this way, isn't it?

**Comment by nam31** [comment]
@MichaelBrooks-Version1 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
