### ISSUE TITLE
office 2010 opération impossible sur les liens

### ISSUE THREAD

**Issue by Chauveau-Georges** [MicrosoftDocs/OfficeDocs-Support#1085]
[Bonjour et merci.
config:  W10, firefox, chrome et edge. pas internet explorer.
options internet de Paramètres ne suit pas les mêmes étapes.
J'ai vérifié par regedit tous les htmfile, c'est complet.
Mais blocage continuel sur les liens dans office 2010 alors que les mêmes liens fonctionnent à partir des autres navigateurs.
J'en suis là !!! 
@ suivre ....
---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 7f736e25-4b81-c26f-ee4d-640519094af6
* Version Independent ID: 9343708d-ccf7-2e46-d377-13564037a5b9
* Content: [Les liens hypertexte ne fonctionnent pas - Outlook](https://docs.microsoft.com/fr-FR/outlook/troubleshoot/message-body/hyperlinks-not-working-in-outlook)
* Content Source: [Outlook/Client/message-body/hyperlinks-not-working-in-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/hyperlinks-not-working-in-outlook.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. If the steps in the article do not work, you can contact [Outlook Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.outlook) for more help.

**Comment by Chauveau-Georges** [comment]
Bonjour,
J'ai installé Internet Explorer 11, j'ai pu alors réinitialiser les options internet grâce à Outil.
J'ai donc résolu le problème des liens qui ne fonctionnaient pas.
Je garde précieusement l'accès à IE 11 qui est plus intéressant que Edge pour ce genre d'intervention.
Cheese !!!
Cordialement.
