### ISSUE TITLE
Correct the PS code in line in article

### ISSUE THREAD

**Issue by j0rt3g4** [MicrosoftDocs/OfficeDocs-Support#1086]
It should be:
```Powershell
Set-User -Identity user@contoso.com -RemotePowerShellEnabled $True
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1919658-c5fb-8538-90bf-244bc481fa87
* Version Independent ID: cabf3111-eaf2-2943-1213-f521638cc391
* Content: [Bad Request when connecting to Exchange Online PowerShell - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/bad-request-error-when-connecting-to-exchange-online-powershell)
* Content Source: [Exchange/ExchangeOnline/administration/bad-request-error-when-connecting-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/administration/bad-request-error-when-connecting-to-exchange-online-powershell.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
PR is merged.
