### ISSUE TITLE
Not always the same behaviour

### ISSUE THREAD

**Issue by Baldgyt** [MicrosoftDocs/OfficeDocs-Support#1088]
The issue I have (aside from the workaround not being acceptable in many cases. Tenan A may not want me to share their data with tenant B, is that the situation is not even reproducible. Most times this works fine between two accounts and just occasionally gets into this state which sounds more like a software fault rather than a design.
Clearly in many cases it would be entirely unacceptable to share files from one tenant with an account in another - especially when the user has been given an account in the tenant with the files and has registered that account for use within the office apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5e0ee51-7cae-be88-5932-f40100e29140
* Version Independent ID: fdd0a8cb-3f97-a9e3-72d3-15a5db334a8e
* Content: [Office 365 (Upload blocked) error when syncing between different tenants in OneDrive - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sync/upload-blocked-error-in-o365)
* Content Source: [SharePoint/OneDrive/sync/upload-blocked-error-in-o365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/OneDrive/sync/upload-blocked-error-in-o365.md)
* Product: **onedrive**
* GitHub Login: @McCoyBot
* Microsoft Alias: **v-todmc**

**Comment by msbemba** [comment]
@Baldgyt Thank you for your feedback. I agree with what you are saying, one way to avoid this error in such a case were there are multiple accounts syncing with onedrive is to uncheck the below option

![image](https://user-images.githubusercontent.com/45987684/123302405-4fe29180-d53a-11eb-9cca-e18f845a2f0e.png)

Thanks
Sri

**Comment by msbemba** [comment]
@Baldgyt Just wanted to circle back and check if the issue persists and if there are any updates needed on the document.

Thanks
Sri

**Comment by nam31** [comment]
@Baldgyt Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
