### ISSUE TITLE
"Spam" is not an acronym; please do not capitalize this term

### ISSUE THREAD

**Issue by fsc-eriker** [MicrosoftDocs/OfficeDocs-Support#1090]
In fact, Hormel spcifically request that email spam should be orthographically stylized differently from their canned ... uh, protein? product.

**Comment by nam31** [comment]
@fsc-eriker The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@fsc-eriker We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.

**Comment by fsc-eriker** [comment]
Sorry, I missed your request for clarifications.

A simple Github search currently brings up 26 results in this repository.

https://github.com/MicrosoftDocs/OfficeDocs-Support/search?q=SPAM
