### ISSUE TITLE
missing info re Outlook 2019 and others

### ISSUE THREAD

**Issue by copenhaus** [MicrosoftDocs/OfficeDocs-Support#1092]
[Enter feedback here]
Although this document claims to apply to Outlook 2019, there's not one mention of Outlook 2019 in the entire article.

For example, what is the number of entries limit for Outlook 2019?

Other sorely missing information:

- How do I examine this list (like open it up and look at individual email addresses, like how NK2 used to be)
- how do I know I am approaching this limit?  For it to *silently* drop the "least used" is not acceptable.
- in RoamCache folder, I have five Stream_Autocomplete_XXXX.dat files, how do I tell which one goes with which profile?  "Look into the registry" is simply not a good answer for an average business owner (who owns multiple small companies or might have different email addresses)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 508859ee-2d96-4d3f-f8ba-0c0b109130b3
* Version Independent ID: 0e7e84e5-62b0-54e8-9cf7-a55ee2897d5d
* Content: [Information about the Outlook AutoComplete list - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/contacts/information-about-the-outlook-autocomplete-list)
* Content Source: [Outlook/Client/contacts/information-about-the-outlook-autocomplete-list.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/contacts/information-about-the-outlook-autocomplete-list.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@copenhaus Thank you for your feedback. We have made changes to the document to include outlook 2019. This can be tracked via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1437

I'll try to answer your questions

How do I examine this list (like open it up and look at individual email addresses, like how NK2 used to be) - {Sri) This option is not available at the moment. There are third-party applications that can do this, but nothing from Microsoft that can be documented.

how do I know I am approaching this limit? For it to silently drop the "least used" is not acceptable.(Sri} This Feature is not available. Outlook uses an internal algorithm to determine the best names to remove from the list. It does this based on a usage weighting.

in RoamCache folder, I have five Stream_Autocomplete_XXXX.dat files {Sri}  The only way to sort and identify is to Arrange the items by name and by date. The AutoComplete file of a new profile has the most recent date. There is no alternate method apart from checking the registry to get the right identity.


Hope this helps!
Thanks
Sri

**Comment by nam31** [comment]
Closing via #1437 
Thank you
