### ISSUE TITLE
Missing instructions to access a single mailbox.

### ISSUE THREAD

**Issue by the-epoch** [MicrosoftDocs/OfficeDocs-Support#1093]
In the section titled "**How do I access the mailbox (Entire Mailbox)**", the article doesn't provide instructions for changing permissions to provide access to a single mailbox; the instructions provided are to access ALL mailboxes! 
e.g. the PowerShell code to access a single mailbox should be something like: 
`Add-MailboxFolderPermission -Identity ayla@contoso.com -User ed@contoso.com -AccessRights FullACcess`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 722948e8-902c-db34-a359-0f3b22200e5d
* Version Independent ID: e4a97de8-7d7f-904f-c611-4f76f48891d1
* Content: [Accessing other people's mailboxes - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/user-and-shared-mailboxes/how-to-access-other-mailboxes#set-up-permissions-to-access-multiple-mailboxes)
* Content Source: [Exchange/ExchangeOnline/user-and-shared-mailboxes/how-to-access-other-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/user-and-shared-mailboxes/how-to-access-other-mailboxes.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@the-epoch Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1378

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1378
Thank you
