### ISSUE TITLE
Preferred Language has no impact on OneDrive region

### ISSUE THREAD

**Issue by jamesw4** [MicrosoftDocs/OfficeDocs-Support#1095]
The article states that changing the preferred language and usage location attributes has an impact on the region of a users OneDrive, however this appears to not be the case (tested with both ad synced and cloud only identity). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca598276-1e7e-4105-81c4-45b2b9f0ba52
* Version Independent ID: e22af2fd-1e50-6c16-2377-fa00a91f68f3
* Content: [Set language and region settings for Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/set-language-and-region)
* Content Source: [Microsoft365/admin/access-management/set-language-and-region.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/access-management/set-language-and-region.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@jamesw4 Thank you for your feedback. I have tested and changing the language in SPO or MS ONLINE does not impact the Region. in fact, both are different attributes -PreferredLanguage and –UsageLocation IT. The document is updated to reflect the same.

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@jamesw4 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
