### ISSUE TITLE
poor

### ISSUE THREAD

**Issue by clubery** [MicrosoftDocs/OfficeDocs-Support#1096]
This is poor, its pathetic and a sad explanation of why you couldn't get a feature to work properly so you provide shabby workarounds, I thought the old microsoft was dead? you still cant nail it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8141a6e6-bec0-7da0-aa4a-d35a02236ebc
* Version Independent ID: e97993f0-1d60-7233-014c-e1506457d175
* Content: [Search results shown without message preview text - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/user-interface/search-results-displayed-without-message-preview-text)
* Content Source: [Outlook/Client/user-interface/search-results-displayed-without-message-preview-text.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/user-interface/search-results-displayed-without-message-preview-text.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. If the resolution in the article does not help, you can contact [Outlook Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.outlook) for more information and support.
