### ISSUE TITLE
The messaging interfaces have returned an unknown error

### ISSUE THREAD

**Issue by mikeykokomo** [MicrosoftDocs/OfficeDocs-Support#1100]
I created the second profile containing the Google account and remover the Google account from the original profile. Problem persists. I deleted the entire Google profile, leaving no Google account in the Outlook 2019 accounts. Problem persists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efa130b-9613-6086-d95a-e6ff8e0ec22c
* Version Independent ID: e5baf249-899e-95c0-e4d0-a4fc2448dad1
* Content: [The operation failed error when you send email messages in Outlook - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/profiles-and-accounts/operation-failed-send-email-outlook)
* Content Source: [Outlook/Client/profiles-and-accounts/operation-failed-send-email-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/profiles-and-accounts/operation-failed-send-email-outlook.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your feedback. If the issue persists, you can contact [Outlook Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.outlook) for more help.

**Comment by mikeykokomo** [comment]
> Thanks for your feedback. If the issue persists, you can contact [Outlook Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.outlook) for more help.

simonxjx,

I believe that issue was resolved. Thanks
