### ISSUE TITLE
Outlook PST Repair Tool

### ISSUE THREAD

**Issue by Chandravat** [MicrosoftDocs/OfficeDocs-Support#1101]
The information here is very helpful, I used Inbox Repair Tool; however, I had a 58 GB PST File hence I had to use a trusted 3rd party PST Repair Tool. I used **[Stellar Repair for Outlook](https://www.stellarinfo.com/outlook-pst-repair.php)** & it helps saves my time & could repair my 58 GB PST file. I also compact my PST file to avoid Corruption in the future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0013ac99-8442-ee88-95d8-c5f459c518e5
* Version Independent ID: 6679377c-f8c6-4e1e-696e-ebf61342e31b
* Content: [Inbox Repair tool (Scanpst.exe) run multiple passes - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/data-files/inbox-repair-tool-scanpst-exe-run-multiple-passes)
* Content Source: [Outlook/Client/data-files/inbox-repair-tool-scanpst-exe-run-multiple-passes.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/data-files/inbox-repair-tool-scanpst-exe-run-multiple-passes.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for sharing your solution and the feedback.
