### ISSUE TITLE
Some spelling mistake

### ISSUE THREAD

**Issue by Roger-Roch** [MicrosoftDocs/OfficeDocs-Support#1110]
Hi there,

Small typos to check please: 

The sentence "Only uses who can approve items" should be replaced by "Only users who can approve items".
To be more clear, the sentence "If you have libraries with Checkout, Required, or" should be replaced by "If you have libraries with Checkout required, or"

Regards,
Roger

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81d1069a-de2b-8466-6db2-ece22060e54c
* Version Independent ID: fff3c0f7-b219-1998-32bb-878780edfe56
* Content: [SharePoint files open as read-only - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/lists-and-libraries/files-open-as-read-only-and-cannot-check-in-or-out)
* Content Source: [SharePoint/SharePointOnline/lists-and-libraries/files-open-as-read-only-and-cannot-check-in-or-out.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/lists-and-libraries/files-open-as-read-only-and-cannot-check-in-or-out.md)
* Product: **sharepoint**
* GitHub Login: @McCoyBot
* Microsoft Alias: **warrenr**

**Comment by RAJU2529** [comment]
@Roger-Roch .   Thanks for pointing out. I am fixing that error.

**Comment by nam31** [comment]
Closing via #1457 
Thank you
