### ISSUE TITLE
Can't find the Media folder 

### ISSUE THREAD

**Issue by neilfrank** [MicrosoftDocs/OfficeDocs-Support#1111]
Working on fixing "The image part with relationship rID8 was not found" error in Microsoft Word

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca27a7a8-589a-70a8-699a-83821633a62b
* Version Independent ID: a275bcf8-bd79-8a99-e12b-9701d4259770
* Content: [The image part with relationship rID8 was not found in Microsoft Word - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/image-part-relationship-rld8-not-found-error-microsoft-word)
* Content Source: [Office/Client/word/image-part-relationship-rld8-not-found-error-microsoft-word.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/image-part-relationship-rld8-not-found-error-microsoft-word.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @McCoyBot
* Microsoft Alias: **v-todmc**

**Comment by sowjanya365** [comment]
Hi @neilfrank 

Have you replaced the target URL with your local folder URL? Please confirm. Thank you!

**Comment by sowjanya365** [comment]
Hi @neilfrank 

Please let us know if you still have any question regarding the issue you have raised initially.
Thanks.

**Comment by nam31** [comment]
@neilfrank We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
