### ISSUE TITLE
Feedback on Outlook continually prompts for password when you try to connect to Office 365

### ISSUE THREAD

**Issue by R3dXIII** [MicrosoftDocs/OfficeDocs-Support#1116]
The security tab is greyed out for all Office 365 users so these instructions are not relevant. 

Page:
Email accounts > Change > More Settings > Security

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8e36de2-8956-ed6f-61b7-2d2ba7b2e7b0
* Version Independent ID: 1e05c7a3-20df-ad99-9fb4-8d3b509f521a
* Content: [Outlook continually prompts for password when you try to connect to Office 365 - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/authentication/continually-prompts-password-office-365)
* Content Source: [Outlook/Client/authentication/continually-prompts-password-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/authentication/continually-prompts-password-office-365.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. You can reference http://answers.microsoft.com/en-us/office/forum/office_2013_release-outlook/microsoft-exchange-mail-profile-security-tab/12c1836b-3c3d-47b8-86b5-336e864dd0ba for more information.

**Comment by MaratMussabekov** [comment]
Hello @R3dXIII,
as you can see in "applies to" section, the article is not applicable to Outlook for Office 365 (or Outlook 2016/2019), it is about older versions connecting to Office 365 (Exchange Online) mailboxes.

Thank you

**Comment by R3dXIII** [comment]
I think the solution to this problem had to do with modern authentication. I had to switch modern authentication on for Office 365 on "Microsoft 365 Admin Center" and then do the same in the registry. For some reason it gets disabled in the registry which was what caused the problem. There is also a workaround where you can add a password into office 365.

1a. To change modern authentication settings go to : Microsoft 365 Admin Center > Settings > Org settings > Modern authentication > Check the box for "Modern authentication".

1b. To edit the registry for this (careful), go to:
Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\Common\Identity
Add a new binary value called "EnableADAL" and set it to "1" (without quotes obviously).

2. To do the workaround with an app password: Go to mysignins.microsoft.com > Security info > Add method > Add an app password if the option is available.

**Comment by MaratMussabekov** [comment]
Hello @R3dXIII ,
are you sure that it didn't work just after step 1a? because outlook newer than 2013 [do not require EnableADAL registry key](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/modern-authentication-configuration).
Thank you

**Comment by nam31** [comment]
@R3dXIII We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

**Comment by R3dXIII** [comment]
@MaratMussabekov no it required either the registry key or the workaround to work.
