### ISSUE TITLE
This does not solve the issue

### ISSUE THREAD

**Issue by zabidin901** [MicrosoftDocs/OfficeDocs-Support#1123]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f069189a-7af4-d6df-1509-f30af7d3c01d
* Version Independent ID: df260ca7-16dd-d2f8-1de3-91e0b71f67d4
* Content: [Word could not create the work file error message when you save a document - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/word-could-not-create-the-work-file)
* Content Source: [Office/Client/word/word-could-not-create-the-work-file.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/word-could-not-create-the-work-file.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. You can try to set the value of the following registry key to **%USERPROFILE%\AppData\Local\Microsoft\Windows\INetCache**:
**HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders\Cache** 
If the issue persists, you can contact [Word Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.word) for more help.
