### ISSUE TITLE
This works

### ISSUE THREAD

**Issue by KdundonMusgrave** [MicrosoftDocs/OfficeDocs-Support#1124]
This worked for me.

/Kieran

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5d5258-e519-df39-0aa5-57115e0211ab
* Version Independent ID: 01390aa8-7cae-809b-b5e9-567514cc99d8
* Content: [Cannot add an Internet calendar - Outlook](https://docs.microsoft.com/en-US/outlook/troubleshoot/calendaring/cannot-add-an-internet-calendar)
* Content Source: [Outlook/Client/calendaring/cannot-add-an-internet-calendar.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/calendaring/cannot-add-an-internet-calendar.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
Thank you @KdundonMusgrave
