### ISSUE TITLE
Clarification on Auto-Mapping

### ISSUE THREAD

**Issue by UnexpectedLemon** [MicrosoftDocs/OfficeDocs-Support#1129]
The article notes: Auto-mapping will not work until all mailboxes are moved to Exchange Online -- but the linked page only discusses cross premises scenarios. Can clarification be added for what "all mailboxes" actually means? And, is there is a better page to link to, or can the linked article be expanded to cover expectations for auto-mapping with all cloud mailboxes tied to an on-premises AD synced identity?

We're setup in a hybrid scenario (with the Modern Full Topology) and auto-mapping is not working between mailboxes with existing FULL ACCESS/Auto-Mapping (that is, permissions assigned on-prem, which are working prior to migration) when those mailboxes are migrated to EXO, UNLESS we manually remove/re-add the Full Access permissions after migration (which seems to create an attribute called "cloudmsExchDelegateLinkList"). Convergys is telling us that auto-mapping is not supported in EXO when migrated. We may or may not end up moving "all mailboxes" to EXO, and for now the identity will be synced from AD via Azure AD Connect because this continues to be a requirement for us and EXO hybrid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 570ac5ae-192f-0775-0ce9-ec491fd3995c
* Version Independent ID: 0e7b3fea-5b00-8ca4-a399-1bd4874edf43
* Content: [Overview of delegation in an Office 365 hybrid environment - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/send-emails/overview-delegation-office-365-hybrid)
* Content Source: [Exchange/ExchangeHybrid/send-emails/overview-delegation-office-365-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/send-emails/overview-delegation-office-365-hybrid.md)
* Service: **exchange-online**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by dariomws** [comment]
Hi @UnexpectedLemon, thank you for your feedback.

I am working on this issue and will provide you with an update in a few days.

**Comment by dariomws** [comment]
@UnexpectedLemon I'm applying the following update to that bullet:
```
Auto-mapping will not work until all related mailboxes are moved to Exchange Online. Any mailboxes that receive these permissions from another mailbox need to be moved simultaneously as the granting mailbox. If a mailbox receives permissions from multiple mailboxes, that mailbox, and all of the mailboxes granting permissions to it, need to be moved at the same time. For more information, see [Auto-mapping doesn't work as expected in an Office 365 hybrid environment](https://support.microsoft.com/help/3080561) and [Permissions in Exchange hybrid deployments](/Exchange/permissions).
```

I tested it on my lab, and auto-mapping worked after both mailboxes were migrated simultaneously. The lab has Exchange 2019 and a full classic hybrid topology. I understand it should also work for modern hybrid as the Mailbox Replication Service Proxy handles the permissions migration.

If it still does not work for you, I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by UnexpectedLemon** [comment]
Thanks @dariomws  -- I apologize for not providing an update sooner. We did resolve our issue, and this specific issue with auto-mapping may have been more of an edge case. Perhaps some additional clarification based on my description below in this article or other Exchange Hybrid documentation would be helpful.

It turns out our AAD Connect (or possibly DirSync?) had been setup many years ago before we upgraded our schema to at least Exchange 2010 when auto-mapping was first introduced and the first three lines of MSFT support did not choose this direction to troubleshoot and could not effectively tell us how to confirm which attributes were actually being synced by AAD Connect. Once we reached the right level of support, and used AAD Connect to "refresh directory schema" the auto-mapping began working as expected (although I thought in our testing it did not seem to matter when we moved mailboxes, existing permissions worked in all permutations).

I don't actually recall this being explicitly called out by other Exchange hybrid documentation despite being a fairly obvious troubleshooting step, and I'm surprised the AAD Connect application did not check or warn me there were un-synced attributes when we enabled Exchange Hybrid Deployment (some of which handle other Exchange features that wont work as expected without being synced).

**Comment by dariomws** [comment]
Thank you @UnexpectedLemon for your answer.

I'm not convinced to add this to the article because it seems a particular scenario. Almost (to not say all) all the articles about Azure AD Connect, Exchange Hybrid and AD FS assume that you are using the latest version of Azure AD Connect and that you are syncing the following attributes:
https://docs.microsoft.com/azure/active-directory/hybrid/reference-connect-sync-attributes-synchronized

**Comment by UnexpectedLemon** [comment]
Thanks @dariomws -- I'll add one final comment/clarification to our overall scenario which is that we already were running the latest version of AAD Connect at the time we setup our Exchange Hybrid. And, I believe we had the correct attributes 'checked' (at least as listed here: https://docs.microsoft.com/en-us/azure/active-directory/hybrid/reference-connect-sync-attributes-synchronized under the text "Then deselect those attributes during installation using Azure AD app and attribute filtering" which links here https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-install-custom#azure-ad-app-and-attribute-filtering) -- if I recall correctly this is what the first three levels of support checked.

But it appears that because we first installed the AAD Connect app before these attributes existed in our directory, that even if these attributes are selected they were not actually synced until we ran the "Refresh Directory Schema" option: https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-installation-wizard#refresh-directory-schema or (as the level 4 support asked us to check) manually select these attributes via Azure AD Sync Services app. This page notes  "This option is used if you have changed the schema in one of your on-premises AD DS forests. For example, you might have installed Exchange" -- in our case we upgraded Exchange years ago. Hope this feedback helps improve the documentation, thanks!

**Comment by dariomws** [comment]
@UnexpectedLemon thank you so much for your explanation. It's is very interesting, but I'm not sure if this article is the correct place to add it.
As you said, it's documented here:
https://docs.microsoft.com/azure/active-directory/hybrid/how-to-connect-installation-wizard#refresh-directory-schema
And maybe another article could be added to a troubleshooting site like:
https://docs.microsoft.com/exchange/troubleshoot/
