### ISSUE TITLE
When Excel is remotely started, what XLSTART is used by the remoted Excel?

### ISSUE THREAD

**Issue by Scheel** [MicrosoftDocs/OfficeDocs-Support#1131]
For example, Machine A starts Excel on Machine B.  I put MyWB.xlsm in C:\ProgramFiles\Microsoft Office\root\Office16\XLSTART\MyWB.xlsm.  If I start Excel on Machine B, the workbook is opened.  But, if I start Excel remotely from Machine A, it is not opened.  The remoted Excel process is showing in Machine A's Task Manager.  If the workbook were opened, code makes the application visible and maximized.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 268953bb-2edc-08a1-2afb-7b00e578cd7a
* Version Independent ID: 1b013dad-688a-251b-b3d1-6e15cde11f85
* Content: [How to use startup folders in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/use-startup-folders)
* Content Source: [Office/Client/excel/use-startup-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/use-startup-folders.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by dariomws** [comment]
Hi @Scheel, thank you for your feedback and help us to improve docs.microsoft.com.

For an updated version of this article please see:
