### ISSUE TITLE
Workaround for this issue

### ISSUE THREAD

**Issue by thanosdoganis** [MicrosoftDocs/OfficeDocs-Support#1132]
I had the same issue in my Laptop. I have 365 office (**32 bit**) running on a Windows 10 Pro 64 bit

Edition	Windows 10 Pro
Version	20H2
Installed on	‎17/‎6/‎2020
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0

The problem occurred when in File Explorer I activated File Preview. When clicking on an office document and Explorer was attempting to Preview it i was getting the message **_Word could not create the work file_** . I disabled Preview in file Explorer and everything works fine. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f069189a-7af4-d6df-1509-f30af7d3c01d
* Version Independent ID: df260ca7-16dd-d2f8-1de3-91e0b71f67d4
* Content: [Word could not create the work file error message when you save a document - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/word-could-not-create-the-work-file)
* Content Source: [Office/Client/word/word-could-not-create-the-work-file.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/word-could-not-create-the-work-file.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by helenclu** [comment]
The original article has been consolidated into https://docs.microsoft.com/office/troubleshoot/office-suite-issues/no-file-previews-file-explorer-switching-to-32-bit. The workaround is added.
