### ISSUE TITLE
Errors in step 2 and 3, and solution does not work

### ISSUE THREAD

**Issue by ahsodex** [MicrosoftDocs/OfficeDocs-Support#114]
It seems there are some errors in steps 2 and 3.

For step 2, there is no space between "Locate" and "the" and the path should have %USERPROFILE% as a variable.

For step 3, I believe the folder should be INetCache\Content.Word, ie:
%USERPROFILE%\AppData\Local\Microsoft\Windows\INetCache

As to the solution itself, the above path exists on my system and I have full permissions on it and I still get the error when previewing .docx files through Windows Explorer. I've seen some other proposed solutions to this with similar errors in paths and folder names that mention editing the registry. I have the correct path already specified in my registry for the cache folder:
```
Key: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders\Cache
Data: %USERPROFILE%\AppData\Local\Microsoft\Windows\INetCache
```

Thanks.

*Update*
Fix found here: https://social.technet.microsoft.com/Forums/en-US/205d7d95-566f-49b0-b23d-9e777bf2eda6/windows-explorer-preview-of-office-2016-files-does-not-work?forum=win10itprogeneral

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93e74201-5f92-5dea-43a7-abc06e04657b
* Version Independent ID: 1425fb4e-4889-8cdc-ef46-d01a31392d73
* Content: [Word could not create the work file error message when you save a document - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/word-could-not-create-the%20work-file#feedback)
* Content Source: [Office/Client/word/word-could-not-create-the%20work-file.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/word-could-not-create-the%20work-file.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
The article has been updated.

**Comment by ahsodex** [comment]
I just checked and the article still has the same errors.
