### ISSUE TITLE
Article is not up to date

### ISSUE THREAD

**Issue by RobertKlohr** [MicrosoftDocs/OfficeDocs-Support#1140]
This article does not cover the past several versions of Outlook and so is of limited use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b1e21ab-f7d9-6c75-c2d8-7d7a38d9b5a6
* Version Independent ID: 72571720-c634-6a03-a239-7d65c4e36e92
* Content: [How to determine Outlook version information - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/user-interface/how-to-determine-outlook-version-information)
* Content Source: [Outlook/Client/user-interface/how-to-determine-outlook-version-information.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/user-interface/how-to-determine-outlook-version-information.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nk-gears** [comment]
@RobertKlohr Do you mean the past outlook version from Outlook 97 to.. Outlook 2002 ?

**Comment by nam31** [comment]
@RobertKlohr We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
