### ISSUE TITLE
Inaccurate Data?

### ISSUE THREAD

**Issue by jpalarchio** [MicrosoftDocs/OfficeDocs-Support#1145]
This article says "you can't do this" and to go check UserVoice and the UserVoice entry is closed out as "complete".

Is this outdated information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1212c318-8633-3692-4873-d1e3127de3fe
* Version Independent ID: c0c7b16a-27ce-1018-5ee4-43702b25012d
* Content: [Teams can't prevent users from changing photos - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/known-issues/cant-prevent-users-from-changing-profile-picture)
* Content Source: [Teams/known-issues/cant-prevent-users-from-changing-profile-picture.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/known-issues/cant-prevent-users-from-changing-profile-picture.md)
* Service: **msteams**
* GitHub Login: @McCoyBot
* Microsoft Alias: **v-todmc**

**Comment by dariomws** [comment]
Hi @jpalarchio, thank you for your feedback.

I am working on this issue and will provide you with an update in a few days.
