### ISSUE TITLE
Edge (Chromium based) can't open Visio files from SharePoint web access in Visio Application 

### ISSUE THREAD

**Issue by GeoSimos** [MicrosoftDocs/OfficeDocs-Support#1147]
I'm facing another issue, while in sharepoint, I can open a visio file via Internet Explorer in the Visio desktop application, but while trying the same from the Edge (Chromium based) this message is displayed:
To open this document, your computer must be running a supported version of Microsoft Visio and a browser that supports opening files directly from Visio Web Access.
Learn more about the requirements.
You can download a copy of this document.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67500af2-e0c3-7d2c-92ad-074a90e49b89
* Version Independent ID: 87d2a160-e8fd-afdd-244b-cdcefd9f69c4
* Content: [Can't open Visio files in Visio Web Access - Office](https://docs.microsoft.com/en-us/office/troubleshoot/visio/open-visio-files-in-visio-web-access)
* Content Source: [Office/Client/visio/open-visio-files-in-visio-web-access.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/visio/open-visio-files-in-visio-web-access.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
CI#145090
