### ISSUE TITLE
Document Update Request - Regarding 30 messages per minute and the corresponding 554 5.2.0

### ISSUE THREAD

**Issue by qaehtesh** [MicrosoftDocs/OfficeDocs-Support#1150]
Following section in this documentation gives an impression that both per day and per minute limit exceed will result in 554 5.2.0 STOREDRV.Submission

-----------------------
Additional throttling limits for the SMTP Authentication protocol are:

30 messages per minute
Recipient rate limit of 10,000 recipients per day
Exceeding these limits causes the following error:

554 5.2.0 STOREDRV.Submission.Exception:SubmissionQuotaExceededException
----------------------

However another documentation and engineering team example shows for 30 messages per minute, when throtled message will be submitted eventually it will just take longer.

-----
https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#message-limits
When outbound message volumes surpass the message rate limit, any excess in message submission will be throttled and successively carried over to the following minutes. This will typically not block the sender's account, but Exchange Online isn't suited to accommodate bulk-mailing scenarios. For this use case, options 2 and 3 here are recommended instead.
--------

So the request is to make this documentation also clear indicating that Exceeding per day only results in 554 5.2.0 STOREDRV error and not per minute limit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54261af2-6912-5d9f-e4db-050a6ea62efd
* Version Independent ID: 014d2473-8c3d-b954-62c6-08dbceab9b74
* Content: [Changes in message store and throttling for concurrent connections - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/send-emails/smtp-submission-improvements)
* Content Source: [Exchange/ExchangeOnline/send-emails/smtp-submission-improvements.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/send-emails/smtp-submission-improvements.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
Closing via #1488 
Thank you
