### ISSUE TITLE
Degrees minutes second conversion in 365

### ISSUE THREAD

**Issue by SkepUser** [MicrosoftDocs/OfficeDocs-Support#1152]
Degrees minutes second conversion in 365 states:
On the Insert menu, click Module.
Where does the option of "Module" appear when the insert tab is clicked?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be969d50-8518-365f-f3ed-5c0e14d55104
* Version Independent ID: 11bad482-781b-bbae-ce60-53f8164d137e
* Content: [Convert degrees/minutes/seconds angles to or from decimal angles - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/convert-degrees-minutes-seconds-angles)
* Content Source: [Office/Client/excel/convert-degrees-minutes-seconds-angles.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/convert-degrees-minutes-seconds-angles.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@SkepUser As the article states in Step.1, you first need to access Visual Basic Editor in Excel (If it's missing, Right-Click the Ribbon -> Customize Ribbon -> Select Developer on the right hand side -> Ok)

> 1. Start Excel and press ALT+F11 to start the Visual Basic editor.


Within Visual Basic Editor in Excel, under Insert tab you have Module:

![image](https://user-images.githubusercontent.com/41186174/118273091-2c084680-b4cc-11eb-954e-f956afa45ad1.png)

**Comment by nam31** [comment]
@SkepUser Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
