### ISSUE TITLE
Wrong german translation for registry key value

### ISSUE THREAD

**Issue by Shadnix-was-taken** [MicrosoftDocs/OfficeDocs-Support#1155]
The referenced registry key in the section "Resolution" for Method 2, Step 3 for the default string value of `HKEY_CLASSES_ROOT\.html` got translated to `HTML-Code` for the german translation. 

The value should be language independent and should be `htmlfile` for the german page as well.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7f736e25-4b81-c26f-ee4d-640519094af6
* Version Independent ID: 9343708d-ccf7-2e46-d377-13564037a5b9
* Content: [Hyperlinks funktionieren nicht - Outlook](https://docs.microsoft.com/de-de/outlook/troubleshoot/message-body/hyperlinks-not-working-in-outlook)
* Content Source: [Outlook/Client/message-body/hyperlinks-not-working-in-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/hyperlinks-not-working-in-outlook.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@Shadnix-was-taken . Thanks for pointing out. the issue is confirmed.

**Comment by helenamasar** [comment]
Article was human translated.
