### ISSUE TITLE
Not an Issue, just a suggestion - Formula to Count the Number of Occurrences of a String in One Cell

### ISSUE THREAD

**Issue by markborges** [MicrosoftDocs/OfficeDocs-Support#1156]
I'd like to suggest a new formula to the document below.

"Formula to Count the Number of Occurrences of a **String** in One Cell"

And the formula would be very similar to the existing one (_Formula to Count the Number of Occurrences of a Single Character in One Cell_):

=**(** LEN(cell_ref)-LEN(SUBSTITUTE(cell_ref,**string_to_be_counted**,"")) **)/ LEN(string_to_be_counted)**

Rgds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d3af8cc-9482-e5e9-f1d5-a64f9ac0c51f
* Version Independent ID: e48dffa1-fccd-8de4-ef83-90f22a420ab1
* Content: [Formulas to count the occurrences of text, characters, and words in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/formulas-to-count-occurrences-in-excel)
* Content Source: [Office/Client/excel/formulas-to-count-occurrences-in-excel.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/formulas-to-count-occurrences-in-excel.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@markborges . Thanks for the new idea. Please write your ideas and suggestions in the Microsoft feedback hub application

**Comment by nam31** [comment]
@markborges Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
