### ISSUE TITLE
Incorrect Registry Keys in Documentation

### ISSUE THREAD

**Issue by cameronkollwitz** [MicrosoftDocs/OfficeDocs-Support#116]
It would appear that the documentation for disabling PST files is referencing the incorrect key in the Windows Registry. In order for this to work you must create the entries under the following locations (NOTE: 'Policies' has been dropped from the path): 

HKEY_CURRENT_USER\Software\Microsoft\Office\\<X.0>\Outlook
HKEY_CURRENT_USER\Software\Microsoft\Office\\<X.0>\Outlook\PST

Creating all associated entries under this location works as-expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a50a221-2351-475b-4b9a-a386b6f5aafd
* Version Independent ID: 4dc840ed-e321-aaf1-bdc1-4030e0163d6a
* Content: [Outlook policy to control PST use and creation in Office 365 Import service - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/outlook-policy/control-pst-use#feedback)
* Content Source: [Exchange/ExchangeHybrid/outlook-policy/control-pst-use.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/outlook-policy/control-pst-use.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by AspenForester** [comment]
Wondering if the .../Policies/... path would be correct as the result of deploying these setting via Group Policy, while setting them manually would use the paths @camxct describes.

**Comment by simonxjx** [comment]
Thanks for your comment. The article is updated with the latest information about registry keys.
