### ISSUE TITLE
This is not accurate and doesn't exist in the settings.

### ISSUE THREAD

**Issue by techlogik** [MicrosoftDocs/OfficeDocs-Support#1161]
This description of what exists in a policy in regards to Unified Messaging is not applicable. MS at some point in the past several months have removed the Unified Messaging option in the User's Exchange Online Phone and Voice Features, it shows in the old admin, but when you click it, the page 400 doesn't exist error. Full admin of the user details the option is no longer there. Thus, this document is also inaccurate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e527c2a7-acc4-6772-88a7-96ea98085afc
* Version Independent ID: 20d5382b-1c89-f18c-3680-92c8d502a689
* Content: [Voice mail settings missing from Options - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/voice-mail-settings-missing-from-options)
* Content Source: [Exchange/ExchangeOnline/administration/voice-mail-settings-missing-from-options.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/administration/voice-mail-settings-missing-from-options.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
Closing via #1410 
Thank you
