### ISSUE TITLE
OSX Screenshots and instructions

### ISSUE THREAD

**Issue by LinealLewis** [MicrosoftDocs/OfficeDocs-Support#1164]
Mac OSX instructions are out of date. Please provide updated advice 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5413e44-74f0-4317-90cc-f4ee40d79cb1
* Version Independent ID: 2146e0ef-8148-3432-44d5-c3d5642dde43
* Content: [Unable to start Excel for Mac - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/fails-starting-excel-mac)
* Content Source: [Office/Client/excel/fails-starting-excel-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/fails-starting-excel-mac.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@LinealLewis this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@LinealLewis We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
