### ISSUE TITLE
Recommended steps do not fix ECP 500 error

### ISSUE THREAD

**Issue by emhouse** [MicrosoftDocs/OfficeDocs-Support#1168]
I have followed the recommended steps for fixing the ECP 500 error to no avail. I tried running the Exchange 2019 CU 8 Security Update from an elevated cmd prompt twice (rebooted after). My BinsearchFolder paths were correct, but ran UpdateCas and UpdateConfigFiles anyway. Any other suggestions to try?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f757dd9-63ac-62bc-514c-f499951cac3d
* Version Independent ID: 9fb3dd48-4074-5127-275e-5f2cf94bdf40
* Content: [OWA or ECP stops working after you install a security update - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/client-connectivity/owa-stops-working-after-update)
* Content Source: [Exchange/ExchangeServer/client-connectivity/owa-stops-working-after-update.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/client-connectivity/owa-stops-working-after-update.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @batre
* Microsoft Alias: **v-matham**

**Comment by msbemba** [comment]
@emhouse Thank you for your feedback. Did you run iisreset after running the scripts: .\UpdateCas.ps1 and .\UpdateConfigFiles.ps1 ? A restart after IISreset is also required. 

Let us know if you still have any issues.

Thanks
Sri

**Comment by msbemba** [comment]
@emhouse Just circling back to check if the issue persists or are we good to close the issue?

Thanks
Sri

**Comment by nam31** [comment]
@emhouse We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
