### ISSUE TITLE
I have exceeded the trials time now encounter problems

### ISSUE THREAD

**Issue by ezidoooo** [MicrosoftDocs/OfficeDocs-Support#1169]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be514288-6578-30c1-233e-ee4781c8045a
* Version Independent ID: d867609b-5ee8-eace-f13c-e440326588bb
* Content: [Listing some issues for Exchange Online - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/exchange-online-welcome)
* Content Source: [Exchange/ExchangeOnline/exchange-online-welcome.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/exchange-online-welcome.md)
* Service: **exchange-online**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by Cloud-Writer** [comment]
@ezidoooo, could you explain your situation more clearly? Which product have you exceeded the trial time for?

**Comment by joinimran** [comment]
Hi @ezidoooo, thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by joinimran** [comment]
@ezidoooo, This document does not explain anything.
![image](https://user-images.githubusercontent.com/47118050/124240289-08f52d00-db34-11eb-9097-8016eb4638dd.png)

**Comment by nam31** [comment]
@ezidoooo We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you
