### ISSUE TITLE
Update the onprem AD group object

### ISSUE THREAD

**Issue by ryanprosser** [MicrosoftDocs/OfficeDocs-Support#117]
I have found this article and intend to test this method
https://blogs.technet.microsoft.com/fasttracktips/2018/10/02/3175/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab981f6a-787d-649f-1e8f-b79bac07f737
* Version Independent ID: a7c9a990-d9db-f143-32d1-df37df20e350
* Content: [On-premises distribution group owner can't manage the group in Exchange Online - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/distribution-groups/cannot-manage-dg)
* Content Source: [Exchange/ExchangeHybrid/distribution-groups/cannot-manage-dg.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/distribution-groups/cannot-manage-dg.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@ryanprosser The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content
Thank you.

**Comment by nam31** [comment]
@ryanprosser We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
