### ISSUE TITLE
Update to include two additional diagnostics

### ISSUE THREAD

**Issue by hdonaldMSFT** [MicrosoftDocs/OfficeDocs-Support#1171]
We should inform customers about these two additional policies in this document:

https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sharing-and-permissions/access-denied-due-to-org-policies
https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sites/compliance-policy-blocking-site-deletion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dad5583-f76b-8542-e7f3-230142b979dc
* Version Independent ID: f70e2083-31ce-c634-304a-a55bb03686c8
* Content: [Use diagnostics to troubleshoot issues in SharePoint Online and OneDrive - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/diagnostics/sharepoint-and-onedrive-diagnostics)
* Content Source: [SharePoint/SharePointOnline/diagnostics/sharepoint-and-onedrive-diagnostics.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/diagnostics/sharepoint-and-onedrive-diagnostics.md)
* Service: **sharepoint-online**
* GitHub Login: @McCoyBot
* Microsoft Alias: **v-todmc**

**Comment by VLG17** [comment]
@hdonaldMSFT These have been added to the article:

![image](https://user-images.githubusercontent.com/41186174/118610970-011c3c00-b7c5-11eb-9cc3-0399c8e4dd7f.png)

**Comment by nam31** [comment]
@hdonaldMSFT Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
