### ISSUE TITLE
Same problems in Word 2102 Build 13801.20266

### ISSUE THREAD

**Issue by eigenvision** [MicrosoftDocs/OfficeDocs-Support#1173]
The same problems described on this page for Word 2007 and Word 2010 also occur in Word 2102 Build 13801.20266.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46468fe2-ff0d-44ae-de1d-f7b411df3d36
* Version Independent ID: b63823d9-b8f7-ca2f-197f-16d1efe8372e
* Content: [A picture or an object may not appear in a Word 2010 or Word 2007 document - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/object-not-appear-in-word-2010)
* Content Source: [Office/Client/word/object-not-appear-in-word-2010.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/object-not-appear-in-word-2010.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@eigenvision , If possible, will you send  2007 and 2010 document file which  contains an image here, so that I can check-in  office 2019  **v2102 build 13801.20294**

**Comment by eigenvision** [comment]
Sorry, I don't understand. I don't have Word 2007 or 2010. I have the 2019
v2012 build. Very recently the problem occurred of pasted-in images not
appearing correctly.

**Comment by RAJU2529** [comment]
@eigenvision , just  now i  added  two  jpg images in word document and saved in .docx format, then i opened the same document, inserted images appeared clearly

**Comment by nam31** [comment]
Closing via #1393 
Thank you
