### ISSUE TITLE
Ambiguous formulation

### ISSUE THREAD

**Issue by hgjd** [MicrosoftDocs/OfficeDocs-Support#1174]
Under "Outlook Search Repair", in the steps for macOS 10.14 and higher, step 4 is formulated in a ambiguous way, which may lead people to delete the "Main Profile" folder, instead of removing it from the list in the Privacy tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a55b51-85d6-f628-581c-5a1c66675933
* Version Independent ID: 9f626f3a-123d-67ca-3aa8-a3443963fe05
* Content: [Outlook for Mac support tools. - Outlook](https://docs.microsoft.com/en-US/outlook/troubleshoot/outlook-for-mac/useful-tools)
* Content Source: [Outlook/OutlookExperts/outlook-for-mac/useful-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/OutlookExperts/outlook-for-mac/useful-tools.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
Closing via #1383 
Thank you
