### ISSUE TITLE
Error windown update in Windows Server 2016

### ISSUE THREAD

**Issue by tuanvip90** [MicrosoftDocs/OfficeDocs-Support#1177]
Dear Support,

I'm getting an error while updating patch in windows. I tried restart, install patch offline on server a few times but it error. Please check with me. 
Many thanks.
![Screenshot_1](https://user-images.githubusercontent.com/56424040/111119810-27dbad80-859d-11eb-9504-66db9746febc.png)

**Comment by nam31** [comment]
@tuanvip90 The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@tuanvip90 We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
