### ISSUE TITLE
Method #1 does not work anymore for o365, only for onPrem.

### ISSUE THREAD

**Issue by DKhrebin** [MicrosoftDocs/OfficeDocs-Support#1178]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6130d9d5-72f1-f6bc-c331-dd3efde61d6f
* Version Independent ID: 55d1fe0c-5327-415c-bf58-3e2cd34a5cb2
* Content: [Collect ActiveSync device logs to troubleshoot sync issues for mobile devices - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/mobile-devices/issues-for-mobile-devices)
* Content Source: [Exchange/ExchangeOnline/mobile-devices/issues-for-mobile-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/mobile-devices/issues-for-mobile-devices.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello, agree,
checked in both old and new interface of OWA, the option **Start Logging** is missing.
Thank you
