### ISSUE TITLE
Christian Mühlbacher

### ISSUE THREAD

**Issue by c3333** [MicrosoftDocs/OfficeDocs-Support#1179]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 795cf34a-71e7-4ce6-3df7-9dc4e2450a76
* Version Independent ID: 927967d1-377a-6f38-85c6-a68c711537ab
* Content: [Error when you use Chrome to manage settings in the EAC in Exchange Server 2013 - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/client-connectivity/cannot-use-chrome-manage-eac-settings?source=docs)
* Content Source: [Exchange/ExchangeServer/client-connectivity/cannot-use-chrome-manage-eac-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/client-connectivity/cannot-use-chrome-manage-eac-settings.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@c3333 The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content ?
Thank you.

**Comment by nam31** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
