### ISSUE TITLE
It's 2021 and your instructions still use IE

### ISSUE THREAD

**Issue by gregory-fonkatz** [MicrosoftDocs/OfficeDocs-Support#1183]
[Enter feedback here]
The obvious thing about the `Sorry, but we're having trouble signing you in - Office 365` page is that you should make the page display details of the problem, instead of asking users to go through the source code in a search of an error. This is called User Friendly Design. It's a new concept for you in MS, I know.
Anyway, IE is dead, why are you using it in examples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6499471f-9237-d5af-9b86-5ffdf3fb2cae
* Version Independent ID: de23bc34-f6ff-d37b-5664-93c6bf1ccb57
* Content: [Sorry, but we're having trouble signing you in - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/sign-in/office-365-azure-intune-sign-in-issue)
* Content Source: [Microsoft365/admin/sign-in/office-365-azure-intune-sign-in-issue.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/sign-in/office-365-azure-intune-sign-in-issue.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nk-gears** [comment]
Hi @gregory-fonkatz,

Thanks for your feedback. 

We are working on to remove IE based Troubleshooting examples in all our documentation.

Will keep you posted once these are updated.
