### ISSUE TITLE
Microsoft Outlook 2013

### ISSUE THREAD

**Issue by adrian-generationtech** [MicrosoftDocs/OfficeDocs-Support#1184]
[Sent email are not being saved in sent folder; tried reinstalling outlook; recreating email account; altering registry settings as advised - STILL NOT WORKING]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1d82c1-752e-e85a-30ca-bba94f138d7c
* Version Independent ID: f92bb03b-c526-7d98-55b4-f3b212666e68
* Content: [Emails are not saved to Sent Items - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/email-management/email-sent-are-not-saved-to-sent-items-folder)
* Content Source: [Outlook/Client/email-management/email-sent-are-not-saved-to-sent-items-folder.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/email-management/email-sent-are-not-saved-to-sent-items-folder.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by AurelianoLobato** [comment]
Boa tarde,
Resolvi o problema reparando o Office, mas apenas para emails novos, emails enviados anteriormente não consegui encontrar.
Office 2016 Plus

**Comment by nam31** [comment]
@adrian-generationtech Thank you for your feedback. The issue was caused by an update and was fixed later in the same day. Please see #1358 
Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
