### ISSUE TITLE
outlook附件被客户端阻止，无法打开

### ISSUE THREAD

**Issue by 1106854713** [MicrosoftDocs/OfficeDocs-Support#1185]
[

你好 OffcieDocs-Support 团队

outlook接收外部邮件的附件会被客户端阻止，在web界面可以看到附件，客户端不行。请问怎么设置才能在客户端查看附件。
报错如下:阻止的附件文件格式是excel文件和PNG图片
### CAUTION: This is an external email that may contain links, attachments and/or embedded images. Proceed only if you recognize the source and know that the content is safe.

]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: eed58735-0119-ca29-71f2-f583d254552b
* Version Independent ID: d9a93396-5498-053d-0360-11dcdd8de68c
* Content: [列出 Outlook 的一些问题 - Outlook](https://docs.microsoft.com/zh-cn/outlook/troubleshoot/outlook-client-welcome)
* Content Source: [Outlook/Client/outlook-client-welcome.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/outlook-client-welcome.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by msbemba** [comment]
@1106854713 Thank you for your feedback. The issue can happen if there are security settings on outlook which have been setup to block certain type of attachments. Does the issue still persist? If yes, do you have a screenshot of the error?

Thanks
Sri

**Comment by msbemba** [comment]
@1106854713 Just circling back to check if you continue to have this problem or are we good to close this issue?

Thanks
Sri

**Comment by nam31** [comment]
@1106854713 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
