### ISSUE TITLE
Command prompt install no longer works

### ISSUE THREAD

**Issue by durrante** [MicrosoftDocs/OfficeDocs-Support#1186]
When using the SaraSetup.exe /? or /q switches it does not reflect the documentation here, /q or /quiet produces prompts and the /? or /help produces a different dialogue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bdf1bb1-b24c-ffb7-3939-dde9dc0a1191
* Version Independent ID: 2e0f5d9e-8c9f-121c-17c0-b1157cebdebb
* Content: [Install and maintain SaRA tool from a network share - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/installation/install-sara-from-network-share)
* Content Source: [Microsoft365/admin/installation/install-sara-from-network-share.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/installation/install-sara-from-network-share.md)
* Product: **office 365**
* GitHub Login: @helenclu
* Microsoft Alias: **v-maqiu**

**Comment by jlriesco** [comment]
This issue has been resolved so no need to update the content.
