### ISSUE TITLE
Additional Test for Cloud User cannot see Free/Busy of On Prem user

### ISSUE THREAD

**Issue by yatesa** [MicrosoftDocs/OfficeDocs-Support#1188]
After having an issue myself where our cloud users could not see free/busy information for our on-prem users and going through all the suggested steps without success, I eventually came across the following article: -
https://docs.microsoft.com/en-us/exchange/troubleshoot/calendars/freebusy-lookups-stop-working

This immediately solve our issue and although the Test-FederationTrust is mentioned in this page, its only listed as a step for opposite issue (On-Prem looking Free/Busy for cloud user). I would suggest you add this link or cmd-let test as a troubleshooting step for Cloud to On-Prem too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33362dda-2259-1ceb-a59e-477fa943fe78
* Version Independent ID: 7fa6b1fe-22d9-40c7-5ad0-26905ee11355
* Content: [Troubleshoot free/busy issues in Exchange hybrid - Exchange](https://docs.microsoft.com/en-US/exchange/troubleshoot/calendars/troubleshoot-freebusy-issues-in-exchange-hybrid)
* Content Source: [Exchange/ExchangeHybrid/calendars/troubleshoot-freebusy-issues-in-exchange-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/calendars/troubleshoot-freebusy-issues-in-exchange-hybrid.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by get-itips** [comment]
Hello @yatesa thanks for your feedback. Will propose through a pr.
