### ISSUE TITLE
Apple article not working

### ISSUE THREAD

**Issue by slowpokezzz** [MicrosoftDocs/OfficeDocs-Support#119]
Since I am using the latest version of Mojave (10.14.6), I was not able to use the Outlook Search Repair Tool.  (Cool.  Got it!)
Being the case, I had to manually rebuild the index using the Apple article provided.  I clearly understand that the article provided has nothing to do with Microsoft.  Well, I just wanted to leave a comment indicating that I had no luck using the provided method.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a55b51-85d6-f628-581c-5a1c66675933
* Version Independent ID: 9f626f3a-123d-67ca-3aa8-a3443963fe05
* Content: [Outlook for Mac support tools. - Outlook](https://docs.microsoft.com/en-in/outlook/troubleshoot/outlook-for-mac/useful-tools#feedback)
* Content Source: [Outlook/OutlookExperts/outlook-for-mac/useful-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/OutlookExperts/outlook-for-mac/useful-tools.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by slowpokezzz** [comment]
SOLUTION: 
I used a solution that (username) "psined1" provided. 
• Close Microsoft Outlook
• Open Finder.  Navigate to your Applications folder.  Find the Microsoft Outlook app (i.e., Microsoft Outlook. app).
• Select/highlight the app (do not open).  Right-click on the app and select "Show Package Contents."  
• Double-click on the "SharedSupport" folder.
• Select/highlight the file named "Outlook Profile Manager.app"
• Press and hold the Command (⌘) and Delete button.  Your Mac will prompt you for your password.  Enter your password and click "OK."
• Navigate to your Trash folder.  Search and locate the file you recently deleted (i.e., Outlook Profile Manager.app).  Select/highlight the file and right-click.  Select the "Put Back" option.  Again, your Mac will prompt you for your password.  Enter your password and click "OK."
• When complete, open Microsoft Outlook and perform a search.

**Comment by lsbthecaretaker** [comment]
I tried to do this but didnt have a "sharedsupport" or a outlook profile manager app in this folder.

**Comment by CVP71** [comment]
@slowpokezzz I have tried your solution but nothing happens. I find it really difficult that Microsoft hasn't better support for this kind of problems. I have done the spotlight solution, that worked in 5 seconds but is an apple tool. I have tried the Outlooksearchrepair tool from microsoft, and then I get the message that Mojave is to new for this tool. Mojave is already more then one year old. Isn't that enough time for microsoft to update this tool.
So that I can use outlook the way I want, sometimes search for an email. I pay 100 dollars a year, then I also expect some kind of support. ;-(

**Comment by Dedcad** [comment]
Catalina not supported!! 
I tried different options, but the search did not work. I even deleted Outlook completely, on the recommendation of Microsoft, with all its folders, but after a clean installation and downloading all the letters from the mailbox, the search did not work!

**Comment by Dedcad** [comment]
Catalina 10.15.2

**Comment by Dedcad** [comment]
Catalina working method:
you can delete your profile by closing out Outlook application; in Finder go to Applications, select MSFT Outlook, right-click Show Package Contents; under Shared Support find Outlook Profile Manager; in the list find your current profile and delete it with "-" button; re-add back your profile by firing up Outlook and following applicable authorization prompts. Once done, check if your Outlook profile is not dangling under the Privacy tab in Spotlight system preferences. Mind you, it may take a while and some CPU hogging on your Mac before your profile syncs fully back and your search yields correct results again. It took my Outlook over 2 hours to sync profile completely after which I was able to successfully search again.

**Comment by CVP71** [comment]
@Dedcad thank you, during the holidays, I will try your solution. And comeback to you.

**Comment by longsincelost** [comment]
Thanks @slowpokezzz - Deleting and putting back the profile mgr. worked.  Cheers.

**Comment by McFcologne** [comment]
It was unfortunately not working for me. Not the deletion and restoring of the "Outlook Profile Manager.app", nor the repair tool which is not running on catalina.
Any suggestions?

**Comment by amicablewings** [comment]
None of this work on MAC OS Catalina 10.15.4. Mac Outlook (16.37) search is completely broken as of May 12, 2020. Microsoft needs to get there acts together and figure our a better solution quickly. This is not acceptable for so long a core search functionality is broken and no support on sight. Official word from Microsoft that its a known issue and MS is working on a fix a year later nothing changed. What is the priority here for MS Product team?

**Comment by joinimran** [comment]
Hi @slowpokezzz , thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by nam31** [comment]
Closing via #1700 
Thank you
