### ISSUE TITLE
Please also consider adding Resolution Step for Azure App Services.

### ISSUE THREAD

**Issue by kenmoritest** [MicrosoftDocs/OfficeDocs-Support#1190]
[Enter feedback here]
Azure App Services does not have registry settings to fix. So we need different approach to address the issue.

1. We can specify ServicePointManager.SecurityProtocol in the initialization code.

  ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

2. We need to upgrade solutions over .NET Framework 4.6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 287a44de-ec68-6dcc-84a3-14344a99b58e
* Version Independent ID: 0f967142-0a0d-b66f-7917-736187716c99
* Content: [Authentication errors when client doesn't have TLS 1.2 support - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/authentication-errors-tls12-support)
* Content Source: [SharePoint/SharePointOnline/administration/authentication-errors-tls12-support.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/administration/authentication-errors-tls12-support.md)
* Service: **o365-solutions**
* GitHub Login: @v-matham
* Microsoft Alias: **v-matham**

**Comment by gabbsmo** [comment]
Our SharePoint Online app in Azure App Service started failing today and this fix worked well for us. Strange that Azure App Service is not automatically configured in a way that works well with Microsoft 365.

**Comment by VLG17** [comment]
@kenmoritest By default App Service uses the latest supported .NET Framework version to run your ASP.NET app and comes with TLS 1.2 enabled by default.  These details are stated [here](https://docs.microsoft.com/en-us/azure/app-service/configure-language-dotnet-framework#set-net-framework-runtime-version) and [here](https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-bindings#enforce-tls-versions).

Nevertheless, I do see your point and I also think it's worth adding it to the article.

**Comment by gabbsmo** [comment]
@VLG17 If I have set .NET version to ASP.NET V4.8 on my app service, should outgoing connection be on TLS 1.2 by default?

**Comment by VLG17** [comment]
@gabbsmo What I'm saying is that "minimum TLS version" for an Azure App Service is (should be) 1.2 by default.

![image](https://user-images.githubusercontent.com/41186174/118506683-34fc5080-b736-11eb-8c92-1958240766cb.png)

**Comment by gabbsmo** [comment]
@VLG17 I just had a support ticket (25251447) with Azure App Service closed that landed in the conclusion that this setting does not affect outgoing connections from App Service to SharePoint Online (for example). Change is needed by Azure product group and thus it was considered out of scope for Azure support. Changing this setting does not help with any of the errors described on this page.

**Comment by nam31** [comment]
Closing via #1395 
Thank you

**Comment by kenmoritest** [comment]
@VLG17  Does that setting affect the inbound settings?

Outbound HTTPS connection for .NET Framework 4.5 does not use latest TLS version. 
.NET Framework should be hardcoded to read ServicePointManager.SecurityProtocol and behave accordingly.

For .NET 4.5 application, it needs to read the following registry key. And if it is not configured, TLS version is set to 1.0.

HKLM\SOFTWARE\Microsoft\.NETFramework\v4.0.30319\UseStrongCrypto = 1

Since Azure App Service does not have registry settings, we can choose to upgrade to .NET 4.6 or later. Otherwise set ServicePointManager.SecurityProtocol.

**Comment by gabbsmo** [comment]
That portal setting only affects inbound connections. I had this confirmed in a support ticket. They also confirmed that the App Service product group has no intention of changing the registry setting. 

So our only option is the two methods you mentioned.
