### ISSUE TITLE
Page Feedback - Teams Loop - Guidance for Firefox is needed

### ISSUE THREAD

**Issue by CD-NBCU** [MicrosoftDocs/OfficeDocs-Support#1194]
Guidance for Firefox is needed.  [This page offers guidance for Edge, Chrome, etc.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c17faf2-0e38-0a98-454c-3c2c4387b37f
* Version Independent ID: d9153b98-dc39-fdd1-a798-07da0caaaa64
* Content: [Microsoft Teams is stuck in a login loop in Edge, Internet Explorer or Google Chrome - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#resolution)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by CD-NBCU** [comment]
Proposed addition for Firefox content attached:

---

![Screen Shot 2021-03-19 at 11 45 14](https://user-images.githubusercontent.com/77810677/111806749-afc8fc80-88a8-11eb-9705-2ef95072bdd4.png)

**Comment by bg-bi** [comment]
Adding those exceptions seemed to work for me, but I also had to sign out of Teams in the browser.

**Comment by davidmarshburn** [comment]
I was able to get by with adding only 

https://microsoftonline.com

**Comment by nam31** [comment]
@CD-NBCU we are going to close this issue as the article has been updated accordingly. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
