### ISSUE TITLE
Request to Update for Outlook 2013, 2016, and 2019

### ISSUE THREAD

**Issue by YipYup** [MicrosoftDocs/OfficeDocs-Support#1198]
Could this be updated with instructions and links for Group Policy Templates for Office 2013, 2016, and 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7af28fd-dfb0-94a2-2227-4a28b19a9887
* Version Independent ID: acf41742-7c7c-a8b4-1cc2-b10edc6e32c9
* Content: [How to control AutoDiscover via Group Policy - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/profiles-and-accounts/how-to-control-autodiscover-via-group-policy)
* Content Source: [Outlook/Client/profiles-and-accounts/how-to-control-autodiscover-via-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/profiles-and-accounts/how-to-control-autodiscover-via-group-policy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@YipYup Thank you for your feedback. I have added information about 2013-2019 via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1634

Once the author reviews and approves, the document will be updated.

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1634 
Thank you
