### ISSUE TITLE
Remove Note: creating cname for msoid

### ISSUE THREAD

**Issue by brainpr** [MicrosoftDocs/OfficeDocs-Support#12]
For GCC High sovereign cloud and all others except for 21Vianet, current guidance for on-boarding is to remove DNS cname records for msoid. Please remove the Note recommending creation of MSOID CNAME record without qualification. The note does not apply to USGov, and following the instructions could cause other issues unintentionally. The note also does not provide enough detail about what values to use as cname alias, even if this did apply to all soverign cloud instances (again, does NOT apply to USGov / DoD). 
--
Remove entire Note that appears immediately before 'Step 1' that contains text starting with:
'If you move from a sovereign cloud to the global cloud....'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccd05f29-a421-2a25-2ce2-25e561331730
* Version Independent ID: 977f14f7-b6be-4ccc-ad9f-8dc3fcef3d8d
* Content: [Reset Office 365 ProPlus activation state](https://docs.microsoft.com/en-us/office365/troubleshoot/activation/reset-office-365-proplus-activation-state#feedback)
* Content Source: [Microsoft365/admin/activation/reset-office-365-proplus-activation-state.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/activation/reset-office-365-proplus-activation-state.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **mattphil**

**Comment by simonxjx** [comment]
The note is removed. https://docs.microsoft.com/en-us/office365/troubleshoot/activation/reset-office-365-proplus-activation-state
