### ISSUE TITLE
Add mention of OneDrive Recycle to step 3

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/OfficeDocs-Support#1200]
With all the pressure MS is exerting on 365 users to "force" them to use OneDrive not mentioning how to recover OneDrive files is a surprising oversight

The article tells how to undelete from the recycle bin. Now you have to ADD instructions on how to recover from OneDrive recycle bin. 

You probably also want to mention the new file recovery tool
http://www.infopackets.com/news/10778/windows-10-gets-file-recovery-tool 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4fca8a9-d513-a44d-462a-bfde11d3b046
* Version Independent ID: ffbc658a-b0cc-2e72-d8f9-5e82dbb2da72
* Content: [How to recover a lost, unsaved, or corrupted Word document - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/recover-lost-unsaved-corrupted-document)
* Content Source: [Office/Client/word/recover-lost-unsaved-corrupted-document.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/recover-lost-unsaved-corrupted-document.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Thanks for the feedback. We've added the information that you suggested.
