### ISSUE TITLE
Automatic removal of junk email is evil

### ISSUE THREAD

**Issue by wiegerw** [MicrosoftDocs/OfficeDocs-Support#1201]
I have been bitten by this 'feature' several times already. The spam filter of Outlook is quite poor, and due to this important emails get lost. It's very poor design. Please make it possible to disable spam filtering altogether, since it only causes problems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea50e9f2-d7a0-cfd9-4a35-9444e8085188
* Version Independent ID: 73189b02-f6df-8a61-c772-41df9cacb609
* Content: [Junk emails are permanently deleted - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/junk-email/junk-emails-are-permanently-deleted)
* Content Source: [Outlook/Client/junk-email/junk-emails-are-permanently-deleted.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/junk-email/junk-emails-are-permanently-deleted.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@wiegerw Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
