### ISSUE TITLE
Additional troubleshooting information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-Support#1204]
Please add a link to this https://support.microsoft.com/en-us/topic/outlook-dlp-policy-tips-not-working-for-certain-conditions-in-email-body-and-attachments-8a32496a-3478-403c-b2eb-04a218f7443c?ui=en-us&rs=en-us&ad=us and any other similar articles. I was under the mistaken impression that this troubleshooting section would be comprehensive. Tech support just informed me about the other article. If it had been here, it would have save me a lot of time and frustration. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3555c8bd-0a31-bff8-73fb-6edd8ea64f3a
* Version Independent ID: bb5a09d8-4b96-4a8d-f327-996ec28c97c7
* Content: [DLP Policy Tip notifications are not displayed in Outlook for Windows - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/security/can't-display-dlp-policytip)
* Content Source: [Outlook/Client/security/can't-display-dlp-policytip.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/security/can't-display-dlp-policytip.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **aruiz**

**Comment by nam31** [comment]
Closing via #1552 
Thank you
