### ISSUE TITLE
workaround not working

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/OfficeDocs-Support#1205]
Hello,

to work around the problem described on this page you recommend the following:

> To avoid this problem, use the user's Simple Mail Transfer Protocol (SMTP) address instead of the display name when you create rules.

However in OWA, you cannot enter SMTP Adresses but only search and select based on the display name.
This is also the only way for a user, that I know of, that has no admin rights to edit a distribution list he owns.
Can you please recommend a working workaround?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfe76582-3547-7d39-3cf1-8492a0ec3d5e
* Version Independent ID: a0fedf91-ab9b-f816-6c4b-6893bdd38323
* Content: [There are multiple recipients matching the identity error - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/outlook-on-the-web-issues/there-are-multiple-recipients-matching-the-identity-error)
* Content Source: [Exchange/ExchangeOnline/outlook-on-the-web-issues/there-are-multiple-recipients-matching-the-identity-error.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/outlook-on-the-web-issues/there-are-multiple-recipients-matching-the-identity-error.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
Closing via #1423 
Thank you
