### ISSUE TITLE
Autovervollständigen auf Outlook Mobile

### ISSUE THREAD

**Issue by kohlfuerst** [MicrosoftDocs/OfficeDocs-Support#1206]
[Hier Feedback eingeben]
Keine Information dazu wie man das Autovervollständigen auch auf Outlook Mobile entfernen kann (wenn da falsche Einträge sind). 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 508859ee-2d96-4d3f-f8ba-0c0b109130b3
* Version Independent ID: 0e7e84e5-62b0-54e8-9cf7-a55ee2897d5d
* Content: [Informationen zur AutoVervollständigen-Liste von Outlook - Outlook](https://docs.microsoft.com/de-DE/outlook/troubleshoot/contacts/information-about-the-outlook-autocomplete-list)
* Content Source: [Outlook/Client/contacts/information-about-the-outlook-autocomplete-list.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/contacts/information-about-the-outlook-autocomplete-list.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@kohlfuerst Thank you for your feedback. The document pertains to deleting autocomplete lists only from desktop outlook applications. There isn’t such related setting for users to delete the email address form the AutoComplete list in Outlook on IOS or Android, However, Start a new email and begin typing the recipients whose emails need removed. When Autocomplete displays the entries you want to remove, click the X at the end of each entry to delete them.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@kohlfuerst Thanks again for the feedback. Just wanted to circle back and check if you still need any assistance or an update on the document.

Thanks
Sri

**Comment by nam31** [comment]
@kohlfuerst We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

**Comment by kohlfuerst** [comment]
Not only me, lots of people do search how to get rid of wrong autocomplete sugesstions on Mobile when using Microsoft Outlook on Android. Also the search function is terribly working wrong. But there is no help or answer anywhere from Microsoft regarding this tasks. 

The solution you describe is not working on AutoComplete list in Outlook Android. The list always stys the same.

**Comment by msbemba** [comment]
@kohlfuerst Thank you for the response. The Suggestions mentioned in the document are typically known fixes for auto-complete issues. If you continue to have problems even after following the suggestions on the document, The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).

Hope this helps!

Thanks
Sri

**Comment by kohlfuerst** [comment]
Thanks Sri, I went through all documentations from Microsoft - there is no better solution. So it will not help to contact Microsoft. They should know by themselfes if they would use their own products :-) THX
