### ISSUE TITLE
Resolution for Separators doesn't address List Separators that aren't commas causing formula 'errors'

### ISSUE THREAD

**Issue by ShaunDave** [MicrosoftDocs/OfficeDocs-Support#1207]
This resolution only addresses issues with _number_ separators. There doesn't seem to be a fix for Named Ranges not being recognised when the system _list_ separator is not a comma.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d45701c5-de5f-e13e-de35-5ea62ec672cf
* Version Independent ID: 2edc6fe2-ab0b-7032-12a2-321e9a3daedc
* Content: [Formula errors when list separator is not set correctly - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/formula-errors)
* Content Source: [Office/Client/excel/formula-errors.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/formula-errors.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@ShaunDave this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@ShaunDave We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
