### ISSUE TITLE
The Instructions are Confusing

### ISSUE THREAD

**Issue by masonabarney** [MicrosoftDocs/OfficeDocs-Support#1209]
Thank you for putting up this page regarding re-indexing the search in Outlook using Spotlight.  HOWEVER, in the last step the instructions say "Once added, remove the folder, and Spotlight will re-index the folder"  It is not clear what you are supposed to remove the folder from because the instructions had just talked about finding the folder in the Finder.  As a result, I deleted the folder from the finder, thereby erasing my preferences in Outlook, which was annoying.  May I suggest a small change to the instructions that would clear this up:

"Once added, remove the folder **from the Spotlight Privacy tab by selecting it and pressing the "minus" symbol in the lower left**, and Spotlight will re-index the folder

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a55b51-85d6-f628-581c-5a1c66675933
* Version Independent ID: 9f626f3a-123d-67ca-3aa8-a3443963fe05
* Content: [Outlook for Mac support tools. - Outlook](https://docs.microsoft.com/en-US/outlook/troubleshoot/outlook-for-mac/useful-tools)
* Content Source: [Outlook/OutlookExperts/outlook-for-mac/useful-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/OutlookExperts/outlook-for-mac/useful-tools.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@masonabarney this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@masonabarney We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
