### ISSUE TITLE
wrong hyperlink

### ISSUE THREAD

**Issue by DutchDarkeh** [MicrosoftDocs/OfficeDocs-Support#121]
The hyper link in the following sentence is wrong and leads to malicious sites : Download and install MFCMapi from the following Microsoft website: MFCMAPI.
the correct one would be https://mfcmapi.codeplex.com , however that leads to a page where there is a notification that its migrated to : https://github.com/stephenegriffin/mfcmapi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de5bfc7-0ef7-fba4-6eb4-eb96f4330aad
* Version Independent ID: e91ab363-95d2-5672-4a82-35097771b77c
* Content: [Outlook SFB Contacts folder doesn't sync with Skype for Business contacts - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/online-contacts/outlook-contacts-folder-not-sync#feedback)
* Content Source: [SkypeforBusiness/SkypeOnline/online-contacts/outlook-contacts-folder-not-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeOnline/online-contacts/outlook-contacts-folder-not-sync.md)
* Service: **skype-for-business-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The link is updated.
