### ISSUE TITLE
Policy configurations are not supported (Outlook 2013 and later clients only)

### ISSUE THREAD

**Issue by tompsmith14** [MicrosoftDocs/OfficeDocs-Support#1210]
there is a section on this page "Policy configurations are not supported (Outlook 2013 and later clients only)"
where the screenshots used are really low/poor resolution, its hard to make out what scenarios aren't supported. 

Also we cant seem to get policy tips to work on any locally installed office applications at all... regardless of what info types we pick or Sensitivity labels.... We have had a call open with MS for 4 weeks and still no progress although a lot of discussions are happening internally apparently.... Within Ms there doesn't seem to be common knowledge whether Policy Tips on local office apps should work not.....  There's a huge amount of wasted effort from IT administrators around the world trying to get this to work...

some definitive clarification on policy tips and locally installed office would be appreciated... 
i cant believe it would actually be released without this working but here we are... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29101071-8828-643f-639a-8cf99731871c
* Version Independent ID: 5a1d7a34-33c4-e596-86b3-c6a88066ed2c
* Content: [Troubleshooting Data Loss Prevention (DLP) policy tips - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/data-loss-prevention/data-loss-prevention-policy-tips)
* Content Source: [Microsoft365/compliance/data-loss-prevention/data-loss-prevention-policy-tips.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/compliance/data-loss-prevention/data-loss-prevention-policy-tips.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by msbemba** [comment]
@tompsmith14 Thank you for your feedback. We will update the screenshots with a better resolution shortly.

Thanks
Sri
