### ISSUE TITLE
Please fix unclear instructions

### ISSUE THREAD

**Issue by amit-nz** [MicrosoftDocs/OfficeDocs-Support#1211]
The part where it says "To create a room list and to add existing rooms to the room list, follow these steps:"

That is not very clear only - steps 1 and 2 are the steps to accomplish this. Step 3 is if you've already got an existing group and want to add members to it. As such it should not be labelled step 3 - it should be in a separate section by itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98329bf6-d177-de21-2083-2efd62e90d14
* Version Independent ID: 12f53470-78ce-07a5-adef-84163da774c5
* Content: [Room Finder doesn't display any conference rooms when a user creates a meeting - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/calendars/conference-rooms-not-displayed)
* Content Source: [Exchange/ExchangeOnline/calendars/conference-rooms-not-displayed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/calendars/conference-rooms-not-displayed.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@amit-nz this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@amit-nz We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
