### ISSUE TITLE
discrepancy on the example

### ISSUE THREAD

**Issue by copenhaus** [MicrosoftDocs/OfficeDocs-Support#1214]
the string went from:
....CN=RECIPIENTS_CN=User6ed4e168-addd-4b03-95f5-b9c9a421957358d\@mgd.domain.com

to

....CN=RECIPIENTS/CN=User-addd-4b03-95f5-b9c9a421957358d

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae3f9ec8-5424-172f-ff80-27baf054bfac
* Version Independent ID: 78efae5e-8b94-2a50-dc65-f559f7a903d6
* Content: [IMCEAEX non-delivery report when you send email messages to an internal user - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/email-delivery/imceaex-ndr)
* Content Source: [Exchange/ExchangeOnline/email-delivery/imceaex-ndr.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/email-delivery/imceaex-ndr.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello, please have a look at #1569 
Thank you

**Comment by nam31** [comment]
Closing via #1569 
Thank you
