### ISSUE TITLE
Format of the date in vCalendar. German website

### ISSUE THREAD

**Issue by ZaUdiaccount** [MicrosoftDocs/OfficeDocs-Support#1215]
Thank You for your support! This side in german language may have a mistake in the Box ' Hinweis' I have insert below. There I marked the ttttt in bold. In my opinion the format has to be yyyymmttthhmmssz  instead of ttttmmttthhmmssz. Because the first four characters stand for the year and not for day. According to ISO 8601 (#https://en.wikipedia.org/wiki/ISO_8601) you may also change to the same format you use in the english version. You may easy use as new text my translation:

New text:
"Die DTSTART -und- DTEND Einträge sind eine Kombination aus Datum und Uhrzeit im Format ,YYYYMMDDThhmmssZ, wobei YYYY=Jahr, MM=Monat, DD=Tag des Monats, T=Zeichen für Beginn der Startuhrzeit, hh=Stunde, mm=Minute, ss=Sekunde, Z=Endzeichen. Diese Zeichenfolge drückt die Zeit als Greenwich Mean Time (GMT) auf eine 24-Stunden-Uhr aus, so wie sie in Deutschland, Österreich und der Schweiz üblicherweise genutzt wird."

Old text:
"_Die DTSTART -und- DTEND Einträge sind eine Kombination aus Datum und Uhrzeit im Format, **_tttt_**mmttthhmmssz, wobei yyyy = year, mm = month, dd = day of the Month, T = Start Time Character, hh = Hour, mm = Minutes, SS = seconds, Z = End Character. Diese Zeichenfolge drückt die Zeit als Greenwich Mean Time (GMT) auf eine 24-Stunden-Uhr aus, sodass Sie an Ihre Zeitzone angepasst werden muss_."
[Hier Feedback eingeben]

![Screenshot 2021-03-26 155441](https://user-images.githubusercontent.com/62600606/112650426-a95bf700-8e4b-11eb-9643-20a5825c20cf.png)
---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: d9ca149b-a507-bfce-b138-23a2876620da
* Version Independent ID: 5562247a-5e50-7318-9b6f-1949822a6452
* Content: [Vorgehensweise verwenden von vCalendar in Outlook - Outlook](https://docs.microsoft.com/de-de/outlook/troubleshoot/calendaring/how-to-use-vcalendar-in-outlook)
* Content Source: [Outlook/Client/calendaring/how-to-use-vcalendar-in-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/calendaring/how-to-use-vcalendar-in-outlook.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by helenamasar** [comment]
This article was human translated into German.
