### ISSUE TITLE
Visio 2019 Default Font

### ISSUE THREAD

**Issue by RichCleaver** [MicrosoftDocs/OfficeDocs-Support#1218]
how do you change the Default font in Visio 2019 like you can in word and excel?

**Comment by nam31** [comment]
@RichCleaver The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@RichCleaver We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
