### ISSUE TITLE
There is no Login network security list in Outlook 365 ProPl;us Version 1908 

### ISSUE THREAD

**Issue by LeslieMurphy** [MicrosoftDocs/OfficeDocs-Support#122]
I am getting repeated prompts to log into an Exchange server.  The O365 account works fine.   If I click "Need Password" in Outlook it logs in (temporarily).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8e36de2-8956-ed6f-61b7-2d2ba7b2e7b0
* Version Independent ID: 1e05c7a3-20df-ad99-9fb4-8d3b509f521a
* Content: [Outlook continually prompts for password when you try to connect to Office 365 - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/sign-in/continually-prompts-password-office-365#feedback)
* Content Source: [Outlook/Client/sign-in/continually-prompts-password-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/sign-in/continually-prompts-password-office-365.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Beej126** [comment]
Same frustrating issue. Regularly recurring prompts for password. Entering password never "sticks". I now continually avoid it by hitting cancel on password prompt and clicking "Needs Password" in the far lower right corner of Outlook status bar which works for a while but always nags again.

This version of outlook doesn't even have the anonymous login dropdown box at all on that settings page... nor in the registry so I assume this outlook is hard coded to work only in this anonymous mode anyway.

Outlook 365 1902 (11328.20438) from Office ProPlus

Somebody please help

**Comment by cloudtechfreak** [comment]
the same issue for me and it's frustrating. no solution till now and my service desk team asking for re-image the laptop.  If anyone has solution. please post.

**Comment by aaroneccles** [comment]
Same problem here.  Same Office version as Beej.  Not all users are having this problem though... very sporadic.

**Comment by RichieRoxx** [comment]
+1

**Comment by aaroneccles** [comment]
Here is the fix that worked for me: adding a regkey for the ExcludeExplicitO365Endpoint value and setting it to 1.   Note that for some of our systems I had to remove credentials from windows credential manager... delete anything related to Microsoft, outlook, or your own exchange server URLs.

Details can be found here:  (I only did steps 1 and 2)
https://kb.intermedia.net/Article/39713

hope it helps

**Comment by Beej126** [comment]
nice to see others plugging away at this... recreating outlook profile might have actually put me in a positive new behavior... will need to give it a few days to be sure and will report back... the registry key by itself didn't seem to improve things

**Comment by msbemba** [comment]
@LeslieMurphy Thank you for your feedback. The Login network security list is not available on newer versions of outlook. It is available in outlook 2007 and outlook 2010. We have added that to the document so there are two sections, One for the newer versions of outlook and the other for older versions. Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@LeslieMurphy Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
