### ISSUE TITLE
EWS script - issues with MFA

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/OfficeDocs-Support#1220]
This document is missing the details for an Admin account that uses MFA.
The console opened by the application isn't in a PowerShell windows with Admin control.
So, there are steps missing. Please have someone to test and then provide updated steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5438283-95e8-9a36-a211-1cc104349217
* Version Independent ID: c6c42db1-7942-629c-de07-ecf2513d6f1f
* Content: [Outlook Search Folders show unexpected mail items with empty subject lines - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/user-interface/personmetadata-items)
* Content Source: [Outlook/Client/user-interface/personmetadata-items.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/user-interface/personmetadata-items.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **gbratton**

**Comment by MaratMussabekov** [comment]
Hello @Jmartinez589 ,
as authentication is performed within the script, I believe the script need to be updated, there is no need for updates in the article.
Also, the script has hardcoded path to the DLL (line 639):
`
Import-Module "C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.3\Microsoft.IdentityModel.Clients.ActiveDirectory.dll" -force
`
Current version of Exchange Online Module is 2.0.5, and the correct path to the DLL is C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.5\netFramework\Microsoft.IdentityModel.Clients.ActiveDirectory.dll

Thank you

**Comment by nam31** [comment]
@Jmartinez589 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
