### ISSUE TITLE
by adding the member/user to an administrator role?

### ISSUE THREAD

**Issue by Candelit** [MicrosoftDocs/OfficeDocs-Support#1221]
[Enter feedback here]
'can be resolved by adding the member/user to an administrator role within Azure'
Hi.
This is unfortunately a really weak answer...to add the user to 'an admin role'...asks for going against least privilege. My guess is that 99% of all who sees this adds the user to Global Admin. The link supplied offers no more advice.
What exact role is required for the respective connections? From other posts in forums, I'm not the only one asking.
Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ba7ce18-5db2-8f74-3d63-63f23373d2f0
* Version Independent ID: 590ca207-7b23-58b6-7ac8-c097448e76f5
* Content: [Access Denied when you connect to Office 365, Azure, or Intune - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/o365-security/access-denied-office-365-azure)
* Content Source: [Microsoft365/security/o365-security/access-denied-office-365-azure.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/security/o365-security/access-denied-office-365-azure.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@Candelit Looks like "Company Administrator" is indeed "Global Administrator". More details in this thread: https://docs.microsoft.com/en-us/answers/questions/233909/get-azureaddirectoryrole-and-34global-administrato.html

Also, if you check [the list of Azure AD built-in roles](https://docs.microsoft.com/en-us/azure/active-directory/roles/permissions-reference), there is no Company Administrator (anymore).

**Comment by VLG17** [comment]
@Candelit any updates?

**Comment by nam31** [comment]
@Candelit We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
