### ISSUE TITLE
Administering the Room Finder through Group Policy does not use Group Policy

### ISSUE THREAD

**Issue by Ghostmokey582** [MicrosoftDocs/OfficeDocs-Support#1222]
The section on Administering the Room Finder through Group Policy misses the mark. It provides the registry keys which are set through GPO, but does not identify the actual Group Policy settings and the source for the ADMX and ADML files used to administer the group policy. 
What is in this document is instructions on how to manipulate the Group Policy registry keys without actually using Group Policy. This could be helpful in a Dev or non-AD joined computer situation. However, as an AD Administrator, when I need to set a Group Policy, I need to know which group policy object needs to be set, what options are available for the group policy, the effects of each possible setting, and the source for getting the group policy object (i.e. the gpmx and gpml files that allow policy setting to be visible in the Group Policy Management editor for any non-native group policy objects).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1b9c380-0116-3400-1d54-3ee50c924cba
* Version Independent ID: f1ad1b10-c320-61fa-2818-8dfc8b63271c
* Content: [How to control the Room Finder in Outlook - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/calendaring/room-finder)
* Content Source: [Outlook/Client/calendaring/room-finder.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/calendaring/room-finder.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **gabesl**

**Comment by nam31** [comment]
Closing via #1601 
Thank you
