### ISSUE TITLE
Who should be posting the SPF record?

### ISSUE THREAD

**Issue by brettfinchhotmailca** [MicrosoftDocs/OfficeDocs-Support#1225]
If an enterprise's email cloud provider is an enterprise instance on Google, should they not have these records already?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef6fd529-a369-9afd-ce21-4cb8b415f6c4
* Version Independent ID: 9e7c3225-ddba-1af5-c2f0-ab3da394f02f
* Content: [Voicemail messages are not delivered in Teams or Skype for Business client - Skype for Business](https://docs.microsoft.com/en-us/SkypeForBusiness/troubleshoot/hybrid-phone-system/voicemails-not-delivered)
* Content Source: [SkypeforBusiness/SkypeHybrid/hybrid-phone-system/voicemails-not-delivered.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeHybrid/hybrid-phone-system/voicemails-not-delivered.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@brettfinchhotmailca As stated in the article, third-party email systems aren't supported.

> The primary issue that affects third-party email systems is that the FROM address is formatted for PSTN calls in a non–RFC-compliant manner. However, the Skype for Business or Teams client filters messages depending on the formatting of the FROM field. To fix this issue, you can change the mail protection filter of the third-party email system to use the "P1 sender address" instead (which is formatted correctly), and then enable these kinds of email messages to pass through.

Are you using Google as your mail system and have this issue described in the article?

**Comment by brettfinchhotmailca** [comment]
yes & there has been a change within past few months, we now get the voice mail from Teams with a VoIP skype domain name so I'll just resign to having this work itself out eventually as now we can at least have people enter a manual trust for delivery as it at least arrives now, in the SPAM folder.
