### ISSUE TITLE
Someone has already set up Teams for your organization

### ISSUE THREAD

**Issue by vladaman** [MicrosoftDocs/OfficeDocs-Support#1226]
[Enter feedback here]
I am unable to solve this issue. I am trying to login to Teams and I get "Someone has already set up Teams for your organization"

This page does not properly describe issue and does not offer solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab509e31-52d3-be39-501a-aef6c701201c
* Version Independent ID: 4c2f3f40-91ca-7bb2-3090-6fd38ba82f40
* Content: [Someone has already set up Teams for your organization error in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/someone-has-already-setup-teams)
* Content Source: [Teams/teams-sign-in/someone-has-already-setup-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/someone-has-already-setup-teams.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **billkau**

**Comment by helenclu** [comment]
Please post your specific issue on [Microsoft Community](https://answers.microsoft.com/).
