### ISSUE TITLE
Leap Year logic is not completely correct

### ISSUE THREAD

**Issue by kesavarajan23** [MicrosoftDocs/OfficeDocs-Support#1227]
Hi Team,

You have mentioned that 2000 is a leap year. I completely agree that 2000 is the leap year. However, based on the steps that you have provided, 2000 is not evenly divisible by 400. 2000/400 = 5; Hence, it is not a leap year as per your logic, which is not true. I would request you to update the logic. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6f92333-a9f0-7616-64e8-5aaceb1e3f40
* Version Independent ID: c8136395-44ec-6eb6-3153-53527baf19b3
* Content: [Method to determine whether a year is a leap year - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/determine-a-leap-year)
* Content Source: [Office/Client/excel/determine-a-leap-year.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/determine-a-leap-year.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
@kesavarajan23 I don't understand your comment. 2000 is obviously divisible by 400 since it gives you a perfect 5 with no reminder (reminder=0)
