### ISSUE TITLE
IOS or Android quarantined on exchange

### ISSUE THREAD

**Issue by corinnemec** [MicrosoftDocs/OfficeDocs-Support#1228]
When setting up the exchange email account on IOS, using IOS email app, if 2FA is used on exchange (in my case authenticator), you need to use autodiscover ('sign in') to set up the account and NOT manual configure. If you use manual configure, then 2FA will not get instigated and the account will automatically be quarantined. 

Use Autodiscover (the 'sign in' option) when setting up the account and the device will not be quarantined.

Jeffrey was very helpful in Microsoft support in getting this resolved for me :)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 000fd45f-f079-b7cf-288d-025708f31d2e
* Version Independent ID: d90b16a4-6181-bb09-28b6-2eeccb0f00ef
* Content: [Outlook for iOS and Android with ABQ rules are quarantined - Outlook](https://docs.microsoft.com/en-US/outlook/troubleshoot/exchange-connectivity/outlook-for-ios-and-android-with-abq-rules-are-quarantined)
* Content Source: [Outlook/Mobile/exchange-connectivity/outlook-for-ios-and-android-with-abq-rules-are-quarantined.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Mobile/exchange-connectivity/outlook-for-ios-and-android-with-abq-rules-are-quarantined.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by joinimran** [comment]
I am taking care of this.

**Comment by nam31** [comment]
@corinnemec we are going to close this issue as the article has been updated accordingly. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
