### ISSUE TITLE
Typo: remove speech mark from command

### ISSUE THREAD

**Issue by gazelle-24** [MicrosoftDocs/OfficeDocs-Support#1230]
There is a typo; the command is written as:
`cscript OSPP.VBS” /dstatus`
Command prompt returns:
`Input Error: There is no file extension in "c:\Program Files (x86)\Microsoft Office\Office16\OSPP.VBS \dstatus".`
However, removing speech mark from command so it is:
`cscript OSPP.VBS /dstatus`
Command runs correctly.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b21845-29d6-e3d7-df04-ddcb81f7aaf6
* Version Independent ID: dcebc19d-d197-56a2-900c-749c29e00db6
* Content: [Determine the license type of your Microsoft Office product - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/licensing/determine-office-license-type?tabs=windows)
* Content Source: [Microsoft365/admin/licensing/determine-office-license-type.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/licensing/determine-office-license-type.md)
* Product: **office-365**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by helenclu** [comment]
Thank you for your feedback! The article was updated.
