### ISSUE TITLE
Add "resetfoldernames" to the first things to try when troubleshooting outlook folder names

### ISSUE THREAD

**Issue by provet1** [MicrosoftDocs/OfficeDocs-Support#1231]
Going through the troubleshooting a combination of method 2 and "**Run Outlook.exe /resetfoldernames**" solved the issue.
I tried method 1-2, 4 without success until I skipped all the way down in step 4 to the mentioned command.

You should add "**Run Outlook.exe /resetfoldernames**" to method 1 possibly method 2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e382bcde-4ad2-c781-e2be-ab5d4f5781e6
* Version Independent ID: 71740043-eab5-b2d6-ecce-07aa59fe107a
* Content: [Folder names are incorrect or displayed in an incorrect language in Outlook - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/user-interface/incorrect-folder-names)
* Content Source: [Outlook/Client/user-interface/incorrect-folder-names.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/user-interface/incorrect-folder-names.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by joinimran** [comment]
I am taking care of this.

**Comment by nam31** [comment]
@provet1 we are going to close this issue as the article has been updated accordingly. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
