### ISSUE TITLE
Missing Outlook Version in "Applies to:"

### ISSUE THREAD

**Issue by Neomaxer** [MicrosoftDocs/OfficeDocs-Support#1233]
Hi,

In the ticket "Case #:24954572" it was confirmed to me that these limits/restrictions are also valid for Outlook 365 (Apps for Enterprise Outlook). Please add this version under "Applies to".

Also I would like to see these limit information somehow linked on this service description page:

https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41bf0ec4-8320-414b-a936-a77e91139531
* Version Independent ID: e82f817d-05bd-95fd-8172-89ec6d7162c6
* Content: [Performance issues for too many items or folders - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/performance/performance-issues-if-too-many-items-or-folders)
* Content Source: [Outlook/Client/performance/performance-issues-if-too-many-items-or-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/performance/performance-issues-if-too-many-items-or-folders.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello
**Please add this version under "Applies to"** - PR created
**Also I would like to see these limit information somehow linked on this service description page** - the information is out of the scope of that article. It is Outlook limitation, not Exchange Online limitation

Thank you

**Comment by nam31** [comment]
Closing via #1384 
Thank you
