### ISSUE TITLE
Unclear, where is minRequiredVersion

### ISSUE THREAD

**Issue by cvmike** [MicrosoftDocs/OfficeDocs-Support#1236]
What is the Policy Nudge Rule? Where do we define minRequiredVersion?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3555c8bd-0a31-bff8-73fb-6edd8ea64f3a
* Version Independent ID: bb5a09d8-4b96-4a8d-f327-996ec28c97c7
* Content: [DLP Policy Tip notifications are not displayed in Outlook for Windows - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/security/can't-display-dlp-policytip)
* Content Source: [Outlook/Client/security/can't-display-dlp-policytip.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/security/can't-display-dlp-policytip.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **aruiz**

**Comment by helenclu** [comment]
It's defined in the Users\<user>\AppData\Local\Microsoft\Outlook\PolicyNudgeRules<GUID>.XML file.
