### ISSUE TITLE
Update article to reflect that Version "16.0" in registry applies to 2016/2019/(2021)/365

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/OfficeDocs-Support#1237]
Please update the article to reflect that it applies to Office 365/2021/2019 as well as 2016.  All of those versions share the version "16.0" is shared by all of those versions (stupid design decision by MS, breaking software development standards).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da1a40ba-1c68-4517-a018-c2e2a4ad3a5d
* Version Independent ID: 8898311b-38f3-a1e0-533f-652b72fcc1a1
* Content: [How to reset user options and registry settings in Word - Office](https://docs.microsoft.com/en-US/office/troubleshoot/word/reset-options-and-settings-in-word)
* Content Source: [Office/Client/word/reset-options-and-settings-in-word.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/reset-options-and-settings-in-word.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Checking into this.
