### ISSUE TITLE
Falsche Informationen: User/PWD: juliet@contoso.com/bla

### ISSUE THREAD

**Issue by ukr966** [MicrosoftDocs/OfficeDocs-Support#1239]
Folgende Informationen sind (zumindest zeitweise) falsch:

- "Wenn Sie zurück drücken, um Ihre Anmeldeinformationen erneut einzugeben, und Sie denselben Fehler sehen, wählen Sie Back again aus, und verwenden Sie dann die folgenden Beispiel Anmeldeinformationen, um ein nicht Office 365es Konto nachzuahmen: 
E-Mail-Adresse: juliet@contoso.com 
Kennwort: <any password that you want to `use>"`

Das Konto ist aufgrund falscher Passworteingaben gesperrt und kann für das Tool nicht genutzt werden.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e8d636cc-bc81-84ad-0e05-ffcb60ba8224
* Version Independent ID: 82cda844-eb2e-4a1a-60ec-c017fe189638
* Content: [Überprüfen mithilfe des Microsoft-Support-und Wiederherstellungs-Assistenten - Outlook](https://docs.microsoft.com/de-DE/outlook/troubleshoot/performance/how-to-scan-outlook-by-using-microsoft-support-and-recovery-assistant)
* Content Source: [Outlook/Client/performance/how-to-scan-outlook-by-using-microsoft-support-and-recovery-assistant.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/performance/how-to-scan-outlook-by-using-microsoft-support-and-recovery-assistant.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello @ukr966 ,
i am trying to reproduce the issue, but I cannot. Could you please advise, how you got this "this solution isn't supported by your office environment" issue?
Thank you

**Comment by ukr966** [comment]
I reported the problem on 04.04.2021. Do you think I will get back into the problem now?

Very bad service.
Maybe the Accound juliet@contoso.com has been reseted in the last 2.5 months. Then it's no wonder that you can't reproduce the error.
