### ISSUE TITLE
why does this impact free/busy?

### ISSUE THREAD

**Issue by gnerd** [MicrosoftDocs/OfficeDocs-Support#124]
Why would not writing back these have any affect on free/busy?
None of these (maybe proxy..) have anything to do with free/busy..

msExchSafeSendersHash
msExchBlockedSendersHash
msExchSafeRecipientHash
msExchArchiveStatus
msExchUCVoiceMailSettings
ProxyAddresses

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee01f9a2-888c-58d9-ab2e-6381a0c43e60
* Version Independent ID: d91b824b-e8d3-3c5b-e57a-8802180f2c7e
* Content: [Exchange Online attributes aren't written back to on-premises AD directory service - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/federation/attribute-not-written-to-azure-ad)
* Content Source: [Exchange/ExchangeHybrid/federation/attribute-not-written-to-azure-ad.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/federation/attribute-not-written-to-azure-ad.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello @gnerd,
free/busy information relies on federation trust. ProxyAddresses attribute defines addresses, so it helps to identify whether SMTP addresses are federated.
Thank you

**Comment by nam31** [comment]
@gnerd Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
