### ISSUE TITLE
IP ranges up to date?

### ISSUE THREAD

**Issue by bballpaul4work** [MicrosoftDocs/OfficeDocs-Support#1241]
I'm trying to identify Azure voicemails coming in as emails but there seems to be too many non-consistent variables. noreply@skype.voicemail.microsoft.com is the reply-to and cannot be used to setup a rule. Is this an exhaustive list of IPs that Microsoft would be sending VMs from? Because I've identified at least one other: 52.114.128.99.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef6fd529-a369-9afd-ce21-4cb8b415f6c4
* Version Independent ID: 9e7c3225-ddba-1af5-c2f0-ab3da394f02f
* Content: [Voicemail messages are not delivered in Teams or Skype for Business client - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/hybrid-phone-system/voicemails-not-delivered)
* Content Source: [SkypeforBusiness/SkypeHybrid/hybrid-phone-system/voicemails-not-delivered.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeHybrid/hybrid-phone-system/voicemails-not-delivered.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by dariomws** [comment]
Hi @bballpaul4work, thank you for your feedback.

I am working on this issue and will provide you with an update in a few days.

**Comment by dariomws** [comment]
Hi @bballpaul4work, thank you for your feedback.

This article was updated 16 hours ago, and the list of IPs was removed in favour of https://docs.microsoft.com/microsoft-365/enterprise/urls-and-ip-address-ranges.

**Comment by nam31** [comment]
@bballpaul4work Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
