### ISSUE TITLE
[LOC]Fixed inappropriate japanese "端末"→"ターミナル"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-Support#1244]
ja-jp:"https://docs.microsoft.com/ja-jp/outlook/troubleshoot/files-and-folders/outlook-2016-for-mac-freezes-on-email-folders"
![outlook-2016-for-mac-freezes-on-email-folders_j](https://user-images.githubusercontent.com/40815708/113896259-bb9f4300-9804-11eb-9df3-6ae5b151b20e.png)

en-us:"https://docs.microsoft.com/en-us/outlook/troubleshoot/files-and-folders/outlook-2016-for-mac-freezes-on-email-folders"
![outlook-2016-for-mac-freezes-on-email-folders_e](https://user-images.githubusercontent.com/40815708/113896287-c2c65100-9804-11eb-9e47-47e9096ac0c0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43ad1294-2529-2817-5a48-2127ddab0bad
* Version Independent ID: eaa8d426-2ce5-b095-870f-9867cbf849bc
* Content: [Outlook 2016 for Mac freezes on email folders - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/files-and-folders/outlook-2016-for-mac-freezes-on-email-folders)
* Content Source: [Outlook/Mac/files-and-folders/outlook-2016-for-mac-freezes-on-email-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Mac/files-and-folders/outlook-2016-for-mac-freezes-on-email-folders.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by TakaKinjo** [comment]
Just checked the JA live version and this is already fixed:

![Issue_1224_AlreadyFixed](https://user-images.githubusercontent.com/67296345/126723876-24fbfd6e-5111-4b54-ae24-d80d1cb2eab9.jpg)

**Comment by hyoshioka0128** [comment]
@nam31  @TakaKinjo - Fixed. Thanks!
Closed #1244 .
