### ISSUE TITLE
Offline client settings no longer available

### ISSUE THREAD

**Issue by tlourey** [MicrosoftDocs/OfficeDocs-Support#1245]
The steps in _'If you are a site administrator, use the following steps to confirm the site is available for syncing.'_ under ['Is the library configured to be available offline'](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sync/troubleshoot-sync-issues#is-the-library-configured-to-be-available-offline) are no longer accurate. 

There is no link 'Search and Offline Availability' (Step 3) so Step 4 & 5 can't be followed. 

Not sure where these settings have moved too. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81263839-b5c0-3024-8d33-43bbf6dc8170
* Version Independent ID: ed15d83f-a2c2-e808-309d-496483772ae0
* Content: [Troubleshoot OneDrive for Business sync issues - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sync/troubleshoot-sync-issues)
* Content Source: [SharePoint/OneDrive/sync/troubleshoot-sync-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/OneDrive/sync/troubleshoot-sync-issues.md)
* Product: **onedrive**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@tlourey Are you still seeing this issue? I see this option in my tenant:

As a workaround, you could use the URL: https://[tenant].sharepoint.com/sites/[site]/_layouts/15/srchvis.aspx

![image](https://user-images.githubusercontent.com/41186174/118480194-97475800-b71a-11eb-9985-c7da10629bf4.png)

**Comment by tlourey** [comment]
The option is their now. It wasn't when I logged this, and I looked everywhere. 

This can be closed.
