### ISSUE TITLE
Azure Active Directory Sync or Azure AD Connect?

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/OfficeDocs-Support#1246]
This article refers to Azure AD Sync...  is that correct or did it mean to refer to our newest sync tool, 'Azure AD Connect'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0638257c-2829-38a7-6bd7-799b96ca8761
* Version Independent ID: 051d257b-e558-7dce-3714-c70fd56eecaa
* Content: [Office 365 email address contains underscore character - Office 365](https://docs.microsoft.com/en-US/office365/troubleshoot/active-directory/email-address-contain-underscore)
* Content Source: [Microsoft365/admin/active-directory/email-address-contain-underscore.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/active-directory/email-address-contain-underscore.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by nam31** [comment]
Closing via #1382 
Thank you
