### ISSUE TITLE
Changing 3rd party cookie settings is not an acceptable solution for Team redirect loops

### ISSUE THREAD

**Issue by dnaod** [MicrosoftDocs/OfficeDocs-Support#1249]
Changing 3rd party cookie settings is not an acceptable solution for Team redirect loops.  This needs to be modernized to match current standards for security and privacy and not rely on 3rd party cookies anymore.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c17faf2-0e38-0a98-454c-3c2c4387b37f
* Version Independent ID: d9153b98-dc39-fdd1-a798-07da0caaaa64
* Content: [Microsoft Teams is stuck in a login loop in Edge, Internet Explorer or Google Chrome - Microsoft Teams](https://docs.microsoft.com/en-ca/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#resolution)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by patricktokeeffe** [comment]
This wouldn't be quite so bad if the exclusion was for a single domain. 

But the current implementation specifies *six* different top-level domains (which isn't even a complete list; see #1026) and an *infinite* number of subdomains. No user serious enough to enable third-party cookie blocking would approve of adding wildcard domains to their exclusion list. The current "solution" is completely unacceptable.

**Comment by nam31** [comment]
@dnaod Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
