### ISSUE TITLE
Potential Fix for "Sorry, something went wrong" when you click an InfoPath form in mobile view in SharePoint Online

### ISSUE THREAD

**Issue by RCFTech** [MicrosoftDocs/OfficeDocs-Support#125]
In my personal testing appending &DefaultItemOpen=1 appears to fix the link provided by the "new form" button in a form library and also when appended to workflow item links of the format [%Workflow Context:Current Site URL%]/_layouts/15/formserver.aspx?XmlLocation=[%Current Item:Encoded Absolute URL%]&DefaultItemOpen=1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92a596c7-3b00-63cf-7a16-36b4e2e7ee0e
* Version Independent ID: f038b9d5-3d4b-ce36-0212-2b74d60cef8f
* Content: [Sorry, something went wrong when you click an InfoPath form in mobile view - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/infopath/click-infopath-form-mobile-view#feedback)
* Content Source: [SharePoint/SharePointOnline/infopath/click-infopath-form-mobile-view.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/infopath/click-infopath-form-mobile-view.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by claudialake** [comment]
RCTTech, Yes, this can be used as an alternate method to open an InfoPath form in a mobile device in additional to the Full Screen (PC view).
