### ISSUE TITLE
how to stop this problem constantly reoccurring?

### ISSUE THREAD

**Issue by nutmix** [MicrosoftDocs/OfficeDocs-Support#1250]
[Enter feedback here]
Adding and removing the main profile to spotlight privacy solves the issue temporarily, but after a few days or weeks outlook cant find any new emails once again.  How do we fix this issue permanently? It has been an ongoing bug for several years, and is now appearing on brand new M1 macs with a clean install.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a55b51-85d6-f628-581c-5a1c66675933
* Version Independent ID: 9f626f3a-123d-67ca-3aa8-a3443963fe05
* Content: [Outlook for Mac support tools. - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/outlook-for-mac/useful-tools)
* Content Source: [Outlook/OutlookExperts/outlook-for-mac/useful-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/OutlookExperts/outlook-for-mac/useful-tools.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by helenclu** [comment]
In this case, we'd recommend that you post your specific issue on [Microsoft Community](https://answers.microsoft.com/).
