### ISSUE TITLE
solution provided in the article is not proper

### ISSUE THREAD

**Issue by shrikantbhere** [MicrosoftDocs/OfficeDocs-Support#1251]
If we enable either <ReportToManagerEnabled> or <ReportToOriginatorEnabled> option then the sender's mailbox will receive all the non delivery emails from the members of DL.

Most of the time DLs are used by CEOs or higher management of an organization to communicate with their employees, partners. In case their mailboxes are bombarded with these non delivery messages, it wouldn't be a good picture. 

Microsoft should think of adding a generic address in return-path<noreply@microsoft.com> of messages sent out through DL, so that these emails are not dropped by recipients mail system.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f28c510-85d2-c149-dfff-7b3bd02bc0eb
* Version Independent ID: f8c27dc1-ffb3-7d94-53de-19965c8989a5
* Content: [External recipients don't get distribution group email - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/email-delivery/external-recipients-not-receiving-distribution-group-emails)
* Content Source: [Exchange/ExchangeOnline/email-delivery/external-recipients-not-receiving-distribution-group-emails.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/email-delivery/external-recipients-not-receiving-distribution-group-emails.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @Norman-sun
* Microsoft Alias: **v-swei**

**Comment by msbemba** [comment]
@shrikantbhere Thank you for your feedback. I'll test the report to manager attribute and update you.

Thanks
Sri

**Comment by msbemba** [comment]
@shrikantbhere Thank you for your feedback. I was able to test this in our lab. When you Set [-ReportToManagerEnabled $true] and  [-ReportToOriginatorEnabled $false] the NDR's don't reach the sender instead reaches only the owners of the group as described in the document. 

Hope this helps!

Thanks
Sri

**Comment by shrikantbhere** [comment]
Hello Sri,

Thank you for getting back to me.

Regards,
Shrikant

________________________________

**Comment by nam31** [comment]
@shrikantbhere  Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
