### ISSUE TITLE
Clarification of 554 5.4.14 Hop count exceeded

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [MicrosoftDocs/OfficeDocs-Support#1252]
"This issue occurs because the Exchange Edge server cannot associate the SMTP address space for the application as a subdomain to the accepted domain. This is true even though the accepted domain is configured as a parent domain."

I have difficulty understand the above sentence. What is "the SMTP address space"? What is "the application"? What "subdomain" it refers to? What is "the accepted domain"? What is a parent domain? This sentence is quite confusing. Could you please clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 696bb95d-070c-6ca5-3a1a-cac33ab19722
* Version Independent ID: f5d2d655-934b-67c3-ca0c-7c92483874a6
* Content: [554 5.4.14 Hop count exceeded - possible mail loop NDR for outgoing email - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/mailflow/hop-count-exceeded-possible-mail-loop)
* Content Source: [Exchange/ExchangeServer/mailflow/hop-count-exceeded-possible-mail-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/mailflow/hop-count-exceeded-possible-mail-loop.md)
* Service: **exchange-powershell**
* GitHub Login: @Norman-sun
* Microsoft Alias: **v-swei**

**Comment by MaratMussabekov** [comment]
Hello, 
to make it simpler:
you have some internal domain, but exchange doesn't know that this domain is internal. It thinks that this domain is external, and tries to send email addressed to that domain outside. However, as the domain is internal, the email is being routed back to your company. And as Exchange doesn't know that this domain is internal, it tries to send it outside again, etc, until the hop count exceeded.
The resolution is to let the exchange know that the domain is internal.

Thank you

**Comment by nam31** [comment]
@prRZ5F4LXZ Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
