### ISSUE TITLE
Seems like typos in the SRV record info.

### ISSUE THREAD

**Issue by Chris8top8he8r** [MicrosoftDocs/OfficeDocs-Support#1253]
I just used this page to fix my Skype for Business and I figure that fixes Teams also.  Just intending to mention what seems like an error in this URL.  The table for SRV records info says use the service "_sip" and the second one says use "_sipfederationtls" and it failed.  When running the Lync Connectivity Analyzer it says it couldn't find the SRV records "_sip._tls.wigglemylegs.com." and "_sipfederationtls._tcp.wigglemylegs.com." so I learned from the error message what text should be entered.  Maybe I'm supposed to be able to interpret intended actual text to enter from this URL's shorthand, but I don't know that much and it looks like a typo, while I may be incorrect.  No response needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963f4e4e-860f-6b95-82a4-907e687403cd
* Version Independent ID: 25913310-1269-a95d-19c4-929f07571bdf
* Content: [Troubleshoot Skype for Business Online DNS configuration issues in Office 365 - Skype for Business](https://docs.microsoft.com/en-US/SkypeForBusiness/troubleshoot/online-configuration/dns-configuration-issue)
* Content Source: [SkypeforBusiness/SkypeOnline/online-configuration/dns-configuration-issue.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeOnline/online-configuration/dns-configuration-issue.md)
* Service: **skype-for-business-online**
* GitHub Login: @Norman-sun
* Microsoft Alias: **v-swei**

**Comment by Norman-sun** [comment]
If also have the same type problems behind, please contact us, thank you!
