### ISSUE TITLE
Links to old instructions for installed AADmodule

### ISSUE THREAD

**Issue by jjl109** [MicrosoftDocs/OfficeDocs-Support#1254]
This page (https://docs.microsoft.com/en-us/exchange/troubleshoot/hybrid-configuration-wizard-errors/unable-to-determine-the-routing-domain-for-the-cloud-org) links to https://docs.microsoft.com/en-us/previous-versions/azure/jj151815(v=azure.100) which states "We're no longer updating this content regularly. Check the Microsoft Product Lifecycle for information about how this product, service, technology, or API is supported.."
The  links on that page don't seem to be correct anymore for installing this AAD module, as they link to Microsoft download Centre that has been retired.
Ultimately, it's **not** possible - by following those links - to get a working shell that allows running `Set-MsolDirSyncEnabled -EnableDirsync $true` as instructed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcf09886-36ac-0acd-c827-7e1be8ce4b0f
* Version Independent ID: f4a3d32a-a442-a069-d140-45f2d17dc7c4
* Content: [Unable to determine routing domain for cloud organization - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/hybrid-configuration-wizard-errors/unable-to-determine-the-routing-domain-for-the-cloud-org)
* Content Source: [Exchange/ExchangeHybrid/hybrid-configuration-wizard-errors/unable-to-determine-the-routing-domain-for-the-cloud-org.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/hybrid-configuration-wizard-errors/unable-to-determine-the-routing-domain-for-the-cloud-org.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @Norman-sun
* Microsoft Alias: **v-swei**

**Comment by nam31** [comment]
Closing via #1371 
Thank you
