### ISSUE TITLE
Alternate Word-Counter

### ISSUE THREAD

**Issue by johnaweiss** [MicrosoftDocs/OfficeDocs-Support#1255]
use your character-counter to count spaces " ", then add 1. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d3af8cc-9482-e5e9-f1d5-a64f9ac0c51f
* Version Independent ID: e48dffa1-fccd-8de4-ef83-90f22a420ab1
* Content: [Formulas to count the occurrences of text, characters, and words in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/formulas-to-count-occurrences-in-excel)
* Content Source: [Office/Client/excel/formulas-to-count-occurrences-in-excel.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/formulas-to-count-occurrences-in-excel.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by nam31** [comment]
@johnaweiss The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content ?
Thank you.

**Comment by nam31** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
