### ISSUE TITLE
return receipt from Monrovia Reykjavik

### ISSUE THREAD

**Issue by ChiefHart** [MicrosoftDocs/OfficeDocs-Support#1257]
[Enter feedback here]?////Why am I getting this return receipt?  I have read it is a Microsoft problem, except I am running a Linux laptop, and using Thunderbird as my mail client.  No microsoft junk on my computer, so what gives?  I also read it is a microsoft problem that microsoft is not fixing even though it is a known problem with their software.
I do not think my emails should be going to other than the addressee.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39593e7f-4aa7-57d9-3602-275e1ef0e189
* Version Independent ID: b7ee86f2-983f-6652-078e-1791706eb785
* Content: [Read receipt from Office 365 recipient displays incorrect time zone - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/outlook-on-the-web-issues/read-receipt-incorrect-timezone)
* Content Source: [Exchange/ExchangeOnline/outlook-on-the-web-issues/read-receipt-incorrect-timezone.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/outlook-on-the-web-issues/read-receipt-incorrect-timezone.md)
* Service: **exchange-online**
* GitHub Login: @Norman-sun
* Microsoft Alias: **v-swei**

**Comment by msbemba** [comment]
@ChiefHart Thank you for your feedback. This could happen if they have an automatic forwarding set on the recipient's end. This is by design that Microsoft lets the sender know about a return receipt if there is an auto-forward in place.

Hope this helps!
Thanks
Sri

**Comment by msbemba** [comment]
@ChiefHart Just circling back to confirm the question was answered. Let us know if you have more questions or if there are any changes required to the document.

Thanks
Sri

**Comment by nam31** [comment]
@ChiefHart  Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
