### ISSUE TITLE
Still doesn't work

### ISSUE THREAD

**Issue by stallter4** [MicrosoftDocs/OfficeDocs-Support#126]
Microsoft, just received a wonderful new Windows update, after which your out of the box tutorial on how to create an excel javascript add-in is now broken.  So.  I doubt youll fix it, but it sure would be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 236f9838-fd32-0154-122e-77725824160a
* Version Independent ID: 76d757f8-a4b1-3bb2-a186-a21b385c6b7e
* Content: [We can't open this add-in from localhost - Office](https://docs.microsoft.com/en-us/office/troubleshoot/error-messages/cannot-open-add-in-from-localhost#feedback)
* Content Source: [Office/Client/error-messages/cannot-open-add-in-from-localhost.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/error-messages/cannot-open-add-in-from-localhost.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by stallter4** [comment]
Fixed my issue by getting latest yo office-generator, latest npm, latest node, and creating a new yo office project, running it. Then my old add-in magically worked.  no clue why.

**Comment by hengchengfei** [comment]
still doesn't work.
