### ISSUE TITLE
In-place-archive doesn't appear enabled

### ISSUE THREAD

**Issue by LarsGottlieb** [MicrosoftDocs/OfficeDocs-Support#1265]
Its nice to know that in-place-archive, is attached an functioning, but the GUI doesnt show that the archive is in place, and when you try to enabled in-place archive, an error is shown.
So how do I change the ArchiveStatus to Active and thereby hopefully having the GUI to reflect the attached in-place-archive.
br Lars

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c23533c-37b7-ed9c-a5d7-a1e25117fd68
* Version Independent ID: 149e15df-70a5-35d1-ec81-9434f9474785
* Content: [ArchiveStatus is set to None for an active archive mailbox - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/archive-mailboxes/archivestatus-set-none)
* Content Source: [Microsoft365/compliance/archive-mailboxes/archivestatus-set-none.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/compliance/archive-mailboxes/archivestatus-set-none.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by msbemba** [comment]
@LarsGottlieb Thank you for your feedback. Do you have the exact error that shows up when enabling archiving in GUI? Also, do you have a Cross-premises scenario where the primary mailbox is on-prem and the archive mailbox is in M365?

Thanks
Sri

**Comment by LarsGottlieb** [comment]
Sorry, no i dont have the exact error and no onprem. mailbox

Mvh Lars Gottlieb
________________________________
Fra: Sriraman M S ***@***.***>
Sendt: Monday, June 21, 2021 10:12:36 PM
Til: MicrosoftDocs/OfficeDocs-Support ***@***.***>
Cc: Lars Gottlieb ***@***.***>; Mention ***@***.***>
Emne: Re: [MicrosoftDocs/OfficeDocs-Support] In-place-archive doesn't appear enabled (#1265)


@LarsGottlieb<https://github.com/LarsGottlieb> Thank you for your feedback. Do you have the exact error that shows up when enabling archiving in GUI? Also, do you have a Cross-premises scenario where the primary mailbox is on-prem and the archive mailbox is in M365?

Thanks
Sri

**Comment by msbemba** [comment]
@LarsGottlieb Thank you for the quick response. The way to enable archive mailbox is outlined in this document -https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-archive-mailboxes?view=o365-worldwide

If you still have any issues, let us know.

Thanks
Sri

**Comment by LarsGottlieb** [comment]
Hi again

The error is here in the GUI it show that an archive is in place, but it is not.
***@***.***D76741.82FDB840]
But I tried to disable and the reenable and now it shows up fine, so it has been fixed.
