### ISSUE TITLE
(at least) ProPlus2019Retail is missing from the list

### ISSUE THREAD

**Issue by DeltaBlast** [MicrosoftDocs/OfficeDocs-Support#1266]
(at least) ProPlus2019Retail is missing from the list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b0e3f06-bd25-2d92-228b-9b5e1cf47ff3
* Version Independent ID: c8a6ff08-5acf-adcb-855f-5eadce72f7ba
* Content: [Product IDs that are supported by the Office Deployment Tool for Click-to-Run - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/installation/product-ids-supported-office-deployment-click-to-run)
* Content Source: [Microsoft365/admin/installation/product-ids-supported-office-deployment-click-to-run.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/installation/product-ids-supported-office-deployment-click-to-run.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by RAJU2529** [comment]
@MaryQiu1987 . Thanks for pointing out . i already downloaded proplus2019retail using  latest deployment tool. 
So I conformed product ID is supported.

**Comment by helenclu** [comment]
[PR1287](https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1287) is merged, close this PR.

@MaryQiu1987 , please update the CI status.
