### ISSUE TITLE
Method 4 only applies for an environment with Exchange Server

### ISSUE THREAD

**Issue by alnad1** [MicrosoftDocs/OfficeDocs-Support#127]
Hello,

The commands that are asked to run for Method 4 cannot be run in a pure "AD synchronized to O365" environment without an Exchange Server. They also mention remoteRoutingAddress / TargetAddress, which would only apply in a hybrid environment for mailflow / autodiscover redirect purposes (would apply if they have an internal DNS with records not pointing to O365 though). If there could be a method listed that uses the attribute editor or Set-ADUser commands to edit directly in AD, that would be great, as method 4 does not mention Exchange / EXO hybrid anywhere. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de7f5ee-fe29-1cbc-fdf1-a29dce272aae
* Version Independent ID: f54cbcf4-bd8a-58ba-9c36-88d7864dbaf4
* Content: [Can't set up a new profile by using Exchange Autodiscover for Online mailbox - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/outlook-profiles/cannot-set-up-profile-autodiscover#feedback)
* Content Source: [Exchange/ExchangeOnline/outlook-profiles/cannot-set-up-profile-autodiscover.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/outlook-profiles/cannot-set-up-profile-autodiscover.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
Closing via #1451 
Thank you
