### ISSUE TITLE
Not Applicable

### ISSUE THREAD

**Issue by szachnoa** [MicrosoftDocs/OfficeDocs-Support#1270]
In relation to lat (current update ) Office Version
does not work
There is no key **9.0**\Common\Internet

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6621f77-f212-d653-6a1f-b53377122299
* Version Independent ID: 00180269-ac22-7154-fe4a-38b9f0a4ecbf
* Content: [Cannot locate the Internet or proxy server when selecting hyperlink in Office - Office](https://docs.microsoft.com/en-US/office/troubleshoot/office-suite-issues/cannot-locate-server-when-click-hyperlink)
* Content Source: [Office/Client/office-suite-issues/cannot-locate-server-when-click-hyperlink.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/cannot-locate-server-when-click-hyperlink.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by helenclu** [comment]
Replace 9.0 with the number based on your Office version:
16.0 = Office 2016/Office 2019
15.0 = Office 2013
14.0 = Office 2010
