### ISSUE TITLE
Mistake in New-Mailbox command in step 2

### ISSUE THREAD

**Issue by Tasty69** [MicrosoftDocs/OfficeDocs-Support#1274]
[Enter feedback here]
New-Mailbox command in step 2 has a space in-between the hyphen and Password parameter.

Currently:
- Password

Needs to be:
-Password

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bdb9e4e-58bb-0b83-2b67-666aca01b889
* Version Independent ID: af966098-3448-53a7-e18a-0116ae61fc24
* Content: [Reconnect inactive or soft-deleted mailboxes to AD - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/reconnect-inactive-or-soft-deleted-mailboxes-to-ad)
* Content Source: [Exchange/ExchangeOnline/administration/reconnect-inactive-or-soft-deleted-mailboxes-to-ad.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/administration/reconnect-inactive-or-soft-deleted-mailboxes-to-ad.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @Norman-sun
* Microsoft Alias: **v-swei**

**Comment by MaryQiu1987** [comment]
Removed the space
