### ISSUE TITLE
64 bits jet ODBC driver

### ISSUE THREAD

**Issue by magla42** [MicrosoftDocs/OfficeDocs-Support#1275]
I am a bit confused here, but perhaps I am only missing some context. We are converting old jet db databases in a 64-bit application and use the 64-bit version of [Microsoft Access Database Engine 2010 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=13255) to get the jet odbc driver. 
So there is a 64-bit version of it currently?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b07d713b-970d-6d44-e69a-3adcc6810ca3
* Version Independent ID: 40bc4a76-f053-e10f-17f4-37a0430ea589
* Content: [OLE DB Provider for Jet and ODBC driver are 32-bit versions only - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/jet-odbc-driver-available-32-bit-version)
* Content Source: [Office/Client/access/jet-odbc-driver-available-32-bit-version.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/jet-odbc-driver-available-32-bit-version.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by jlriesco** [comment]
“The Jet Database Engine was designed to be a general purpose database engine supplied with Windows and was only available in 32 bit before it was deprecated. The Access Database Engine aka Access Connectivity Engine (ACE) is Office’s private engine built from the foundations of Jet. Although both engines provide similar functionality, ACE follows the design principles of Office and is not suited for some of the previous scenarios supported by Jet. However, ACE is provided in both 32bit and 64bit but only one bitness is allowed on a machine and that bitness must be the same as the Office bitness if Office is installed. Please read through all of the intended use scenarios provided on the download page Download Microsoft Access Database Engine 2016 Redistributable from Official Microsoft Download Center. Additionally, ACE is provided within the Office installation, please review this article to understand if ACE is already available or what installation is recommended Unable to use the Access ODBC, OLEDB or DAO interfaces outside Office Click-to-Run applications.”

I will get the article updated with this sentence.

**Comment by jlriesco** [comment]
created PUBLIC CONTENT REQUEST 147944 to get this article updated.
