### ISSUE TITLE
This policy doesn't work on Outlook 2019

### ISSUE THREAD

**Issue by mchibams** [MicrosoftDocs/OfficeDocs-Support#1279]
The AuthenticationService is not referred by Outlook 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cdfd10f-31f7-d3d6-08a6-82896adfbc46
* Version Independent ID: d8a9e3ac-0409-eec1-d0a6-bd004801336f
* Content: [Outlook asks for password repeatedly when it uses MAPI over HTTP - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/authentication/outlook-prompt-password-when-use-mapi-over-http)
* Content Source: [Outlook/Client/authentication/outlook-prompt-password-when-use-mapi-over-http.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/authentication/outlook-prompt-password-when-use-mapi-over-http.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by nam31** [comment]
Closing via #1513
Thank you
