### ISSUE TITLE
Incorrect URLs in Japanese page should be correct as English page.

### ISSUE THREAD

**Issue by mitanabe** [MicrosoftDocs/OfficeDocs-Support#128]
Incorrect URLs in Japanese page should be correct as English page.
Following URLs are shown in Japanese page (https://docs.microsoft.com/ja-jp/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop).

--- in ja-jp page ---
https://*. .com
https://* microsoft online .com
https://* teams.
https://* teams. .com
https://* sfbassets
https://* skypeforbusiness .com
--- in ja-jp page ---

--- in en-us page ---
https://*.microsoft.com
https://*.microsoftonline.com
https://*.teams.skype.com
https://*.teams.microsoft.com
https://*.sfbassets.com
https://*.skypeforbusiness.com
--- in en-us page ---

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c060df7-e881-f6b9-29bb-8ee6ba3cb43a
* Version Independent ID: e614dbf0-9542-9f60-e430-d1aa2471f42c
* Content: [Microsoft Teams is stuck in a login loop in Edge or Internet Explorer - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#feedback)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Cloud-Writer** [comment]
Fixed
