### ISSUE TITLE
It worked

### ISSUE THREAD

**Issue by silviopst** [MicrosoftDocs/OfficeDocs-Support#1282]
Thank you, your vba script worked fine. Why don't you (microsoft) allow the configuration of the output csv format?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92765388-a22b-7311-8764-e8b065a0569e
* Version Independent ID: d02626a0-1eb2-1e62-efa5-519676f527a7
* Content: [Export a text file with both comma and quote delimiters in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/export-text-file-with-comma-quote)
* Content Source: [Office/Client/excel/export-text-file-with-comma-quote.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/export-text-file-with-comma-quote.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by nam31** [comment]
@silviopst The issues section of this repository is intended for product documentation issues only.
Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
