### ISSUE TITLE
what kind of BS is this?

### ISSUE THREAD

**Issue by walterramjet** [MicrosoftDocs/OfficeDocs-Support#1283]
[The burning question is, "why".  If I go to outlook live OPTIONS to the COMPOSE EMAIL, I am given the option to include email signature AUTOMATICALLY when I compose an email, but it doesn't work.  Your WORK-AROUND is also BS because if I select INCLUDE SIGNATURE from the ribbon above my email while composing an email, NOTHING HAPPENS!!!!!!   News Flash, no one in their right mind would call this progress and you say there are no plans to fix it.  What kind of an outfit are you?  Answer:  a waste of space.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beddb76f-6c9b-a26f-0db7-39b08b2b6cdd
* Version Independent ID: 769e6bf2-217c-e914-a20e-a1062f4b8f37
* Content: [Messages do not include default email signature - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/message-body/outside-messages-not-include-email-signature)
* Content Source: [Outlook/Client/message-body/outside-messages-not-include-email-signature.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/outside-messages-not-include-email-signature.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by nam31** [comment]
@walterramjet Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
