### ISSUE TITLE
Typo in Powershell command for On Premise to Cloud Free/Busy

### ISSUE THREAD

**Issue by Reithy28** [MicrosoftDocs/OfficeDocs-Support#1284]
Hello.

Just wanted to report that there is a type in the powershell command to look up the Org Relationship.

Current Powershell command on page is "Get-OrganizationReationship -Identity "On Premises to Exchange Online Organization Relationship"    -  As you can see Relationship is spelt incorrectly.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33362dda-2259-1ceb-a59e-477fa943fe78
* Version Independent ID: 7fa6b1fe-22d9-40c7-5ad0-26905ee11355
* Content: [Troubleshoot free/busy issues in Exchange hybrid - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/calendars/troubleshoot-freebusy-issues-in-exchange-hybrid)
* Content Source: [Exchange/ExchangeHybrid/calendars/troubleshoot-freebusy-issues-in-exchange-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/calendars/troubleshoot-freebusy-issues-in-exchange-hybrid.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @Norman-sun
* Microsoft Alias: **v-swei**

**Comment by Reithy28** [comment]
Sorry page is - https://docs.microsoft.com/en-us/exchange/troubleshoot/calendars/troubleshoot-freebusy-issues-in-exchange-hybrid

**Comment by Reithy28** [comment]
I have created the following pull req for this issue - https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1285

**Comment by helenclu** [comment]
PR 1285 was merged, close this issue.
