### ISSUE TITLE
Can't access Teams Admin Center despite explicitly allowing third party cookies

### ISSUE THREAD

**Issue by seiwaldm** [MicrosoftDocs/OfficeDocs-Support#1291]
the suggested solution ist not working for me. have the option to block 3rd party cookies disabled. tried to reinstall edge with the suggested script under https://answers.microsoft.com/en-us/edge/forum/all/how-to-reinstall-edge/b8339332-ef53-45d5-ad68-406cfb19929e.

still not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3f23881-693f-f82e-7fc2-7b9f73b29090
* Version Independent ID: 5ea1b8c7-f978-bcca-1d92-01df10f747ae
* Content: [Error (We can't get the activity log) when accessing the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-administration/cannot-access-admin-center)
* Content Source: [Teams/teams-administration/cannot-access-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-administration/cannot-access-admin-center.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **scapero**

**Comment by msbemba** [comment]
@seiwaldm Just circling back to see if you were able to contact Microsoft support to get this resolved.

Thanks
Sri

**Comment by seiwaldm** [comment]
Thx for coming back to me about this. tbh, i forgot about the issue in the meantime. Just tried to log in with Edge and everything worked fine. Thx again for your effort. Have a nice day
