### ISSUE TITLE
links to download  enable-remotearchive.ps1 and disable-remotearchive.ps1 are not working

### ISSUE THREAD

**Issue by Rmca81** [MicrosoftDocs/OfficeDocs-Support#1292]
Hi,

I am writing in regards to an issue with links to download the scripts.
https://download.microsoft.com/download/4/9/7/497B7DB5-16C6-40D1-A3F6-AF332E797644/Enable-RemoteArchive.ps1.txt
https://download.microsoft.com/download/1/D/F/1DF27D3D-78FF-4B75-BF01-305DDB0742FA/Disable-RemoteArchive.ps1.txt

Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a449846-e325-24ba-ea5e-48d6f9c49b22
* Version Independent ID: 200173f7-9779-bd93-2272-4494da6f642d
* Content: [Archive mailbox can't be provisioned or deprovisioned after a mailbox is migrated to Office 365 Dedicated/ITAR vNext - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/archive-mailboxes/cannot-provision-deprovision)
* Content Source: [Microsoft365/compliance/archive-mailboxes/cannot-provision-deprovision.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/compliance/archive-mailboxes/cannot-provision-deprovision.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by simonxjx** [comment]
Links are updated.
