### ISSUE TITLE
KB5001779 for Exchange 2016

### ISSUE THREAD

**Issue by eduzav** [MicrosoftDocs/OfficeDocs-Support#1293]
I do not know if it is the right place, I need to know if the KB5001779 affects exchange server 2016 (on premise) CU11?
I only see patch released for CU19 and CU20.
Thanks

**Comment by eduzav** [comment]
I search here -> https://www.catalog.update.microsoft.com/Search.aspx?q=KB5001779

**Comment by nam31** [comment]
The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@eduzav We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
