### ISSUE TITLE
SharePoint 2010 User Profile Service Synchronization start

### ISSUE THREAD

**Issue by malazess** [MicrosoftDocs/OfficeDocs-Support#1294]
In my SharePoint server I selected option RC3_HMAC_MD5 too. Only after that my User Profile Service Synchronization started. 
I found solution in another Article ( https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/sccm-quot-the-encryption-type-requested-is-not-supported-by-the/ba-p/570914 ).

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 8e1c2159-4985-32ba-bbf5-88c922bc899d
* Version Independent ID: ed385bf7-1e6a-efd2-fa38-0c850ebf7237
* Content: [Запрашиваемая типа шифрования не поддерживается KDC - SharePoint](https://docs.microsoft.com/ru-ru/sharepoint/troubleshoot/security/configuration-to-support-kerberos-aes-encryption)
* Content Source: [SharePoint/SharePointServer/security/configuration-to-support-kerberos-aes-encryption.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointServer/security/configuration-to-support-kerberos-aes-encryption.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by nam31** [comment]
Closing via #1388 
Thank you
