### ISSUE TITLE
(Get-Mailbox <user>).primarysmtpaddress.domain Does Not Return the Domain.

### ISSUE THREAD

**Issue by Arbar1** [MicrosoftDocs/OfficeDocs-Support#1296]
The first line of code provided under "More Information" cannot work.  "Domain" is not a value returned by (Get-Mailbox <user>).PrimarySmtpAddress

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afbaaec1-fe8b-d838-2f60-5868b4f9823b
* Version Independent ID: 3d0f136c-3549-d33d-71af-16e0917e050a
* Content: [Cannot view free/busy information for a remote user - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/calendars/cannot-view-freebusy-information-for-remote-user)
* Content Source: [Exchange/ExchangeHybrid/calendars/cannot-view-freebusy-information-for-remote-user.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/calendars/cannot-view-freebusy-information-for-remote-user.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @Norman-sun
* Microsoft Alias: **v-swei**

**Comment by nam31** [comment]
Closing via #1362 
Thank you
