### ISSUE TITLE
Why does wrap text not adjust row height in Excel?

### ISSUE THREAD

**Issue by naitsirch** [MicrosoftDocs/OfficeDocs-Support#1297]
This behavior is extremely annoying, if you want to add some explanation text to the document. At the docs it is said "This behavior is by design". I'd like to know why this is the desired behavior.

Is there an alternative way to work with a little bit more text in Excel?

Btw. in LibreOffice the row height is adjusted automatically even for wrapped text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 637418b9-c486-0de0-7f52-c79b4b3dc542
* Version Independent ID: a357675b-ee15-92a3-9c82-9abcd9d261c4
* Content: [Wrap text not adjust row height - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/wrap-text-not-adjust-row-height)
* Content Source: [Office/Client/excel/wrap-text-not-adjust-row-height.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/wrap-text-not-adjust-row-height.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by joinimran** [comment]
Hi @naitsirch, thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by joinimran** [comment]
Hi Wrap text is working fine for me. I tried some other features as well.

![image](https://user-images.githubusercontent.com/47118050/124253373-6348ba80-db41-11eb-8bce-47501cb9c330.png)

Please let me know if any of these works for you.

**Comment by nam31** [comment]
@naitsirch Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
