### ISSUE TITLE
IP table not updated in Workaround Symptom 1

### ISSUE THREAD

**Issue by jshaole** [MicrosoftDocs/OfficeDocs-Support#1298]
The Workaround Symptom 1 IP list looks to be not updated. We implemented this workaround months ago and determined there are now new IP addresses not on this list sending voicemail messages to user mailboxes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef6fd529-a369-9afd-ce21-4cb8b415f6c4
* Version Independent ID: 9e7c3225-ddba-1af5-c2f0-ab3da394f02f
* Content: [Voicemail messages are not delivered in Teams or Skype for Business client - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/hybrid-phone-system/voicemails-not-delivered)
* Content Source: [SkypeforBusiness/SkypeHybrid/hybrid-phone-system/voicemails-not-delivered.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeHybrid/hybrid-phone-system/voicemails-not-delivered.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @Norman-sun
* Microsoft Alias: **v-swei**

**Comment by dariomws** [comment]
Hi @jshaole, thank you for your feedback and help us to improve docs.microsoft.com.

That section in this article was updated 1 month ago, and now it redirects you to the article which lists all the IP addresses for Office 365.

**Comment by nam31** [comment]
@jshaole Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Comment by jshaole** [comment]
No additional questions. Thank you.

Thank you,
Jeff Schroeder
________________________________
