### ISSUE TITLE
Office should not bypass the 302 portion of redirects and assume that this part of an application is not important.

### ISSUE THREAD

**Issue by EklipZgit** [MicrosoftDocs/OfficeDocs-Support#1299]
You have a huge page here filled with words attempting to justify the fact that when you click on a link in Microsoft Word, Microsoft Word DOES NOT ACTUALLY TAKE YOU TO THE LINK YOU CLICKED ON.

This is not ok. It is not up to you to decide whether people should use cookie based sessions for authentication. It is up to you to put clickable links in word documents that take the user -- in their own browser -- to the hyperlink in the original URL. Not where it 302'd to, but to the location that returns the 302. 

It is that simple. This is a bug. Please fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb4e2409-fde8-8b1b-4dca-01bb6759b006
* Version Independent ID: fd463b22-33c1-a726-6a63-62ee892c5df3
* Content: [Issues when you click a hyperlink to SSO Web site - Office](https://docs.microsoft.com/en-US/office/troubleshoot/office-suite-issues/click-hyperlink-to-sso-website)
* Content Source: [Office/Client/office-suite-issues/click-hyperlink-to-sso-website.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/click-hyperlink-to-sso-website.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by nam31** [comment]
@EklipZgit Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
