### ISSUE TITLE
Issue importing termset with 774 terms

### ISSUE THREAD

**Issue by distinctapp** [MicrosoftDocs/OfficeDocs-Support#13]
Today while trying to import a termset to my managed metadata service, I got the error "Not all terms were imported successfully. Please see the server log for more information."
This is totally unexpected because the termset contains 774 terms which is far less than the 5000 terms limit.
Happy to provide more details if needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d9e717c-b657-e988-6bb7-ada6ae92c24d
* Version Independent ID: 42f12397-4486-230b-05db-49c7ea86a769
* Content: [Error when you try to import a term set into SharePoint Online - Troubleshooting | SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/online-admin/troubleshoot-error-when-importing-a-term-set#feedback)
* Content Source: [SharePoint/SharePointOnline/online-admin/troubleshoot-error-when-importing-a-term-set.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/online-admin/troubleshoot-error-when-importing-a-term-set.md)
* Service: **sharepoint-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by spowriter** [comment]
distinctapp,

I'm sorry you encountered this issue. One question: were you using the term store tool to do the import?

**Comment by nam31** [comment]
@distinctapp, this article has been retired. 
You can find more information regarding the issue that you raised on the updated page https://docs.microsoft.com/en-us/sharepoint/troubleshoot/search/troubleshoot-error-when-importing-a-term-set
Please feel free to raise a ticket using the Feedback section of the article if you still face any issue regarding the article.
Thanks

**Comment by eheidrich** [comment]
I am getting the same error message "Not all terms were imported successfully. Please see the server log for more information." when trying to import into the SharePoint Online Term Store. I cannot figure out where the server log is to get more information. My term set CSV file has about 800 terms, so it's not the 5,000 terms issue.
