### ISSUE TITLE
When this feature can be supported?

### ISSUE THREAD

**Issue by ismeleo** [MicrosoftDocs/OfficeDocs-Support#130]
May I know when this feature can be supported in SharePoint Online?

Before that, if any workaround to add the outlook calendar to the SharePoint Online?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f739dde2-469a-c061-3d82-06d4580903c1
* Version Independent ID: 67a424b8-a866-dbbb-2a3a-974fa1588cd5
* Content: [Exchange Online calendar isn't displayed in SharePoint Online - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/Sites/calendar-overlay-unsupported#feedback)
* Content Source: [SharePoint/SharePointOnline/sites/calendar-overlay-unsupported.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sites/calendar-overlay-unsupported.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by claudialake** [comment]
I don't have details on when or if this will be supported in SharePoint Online, but you can add a Group calendar to your site by using the Calendar web part. See this article for details: https://support.office.com/en-us/article/use-the-group-calendar-web-part-eaf3c04d-5699-48cb-8b5e-3caa887d51ce
