### ISSUE TITLE
OWA search returns up to 1028 results, not 250

### ISSUE THREAD

**Issue by ZugBug** [MicrosoftDocs/OfficeDocs-Support#1300]
This article states that the OWA search result limit is 250 but it is actually 1028.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa9a41d-09b0-f435-c33c-bb187e12d760
* Version Independent ID: 4bb37e8e-3ad9-a701-7ed0-69ab7fa0646f
* Content: [Items are missing from search results when Office 365 users search their mailbox in Outlook on the web - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/outlook-on-the-web-issues/items-missing-search-results)
* Content Source: [Exchange/ExchangeOnline/outlook-on-the-web-issues/items-missing-search-results.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/outlook-on-the-web-issues/items-missing-search-results.md)
* Product: **office 365**
* GitHub Login: @Norman-sun
* Microsoft Alias: **v-swei**

**Comment by MaratMussabekov** [comment]
Hello @ZugBug ,
can you please provide the source of this information?
I just checked in OWA, and got 250 results.
Thank you

**Comment by ZugBug** [comment]
Hi Marat,

Thanks for reaching out. I first noticed this in a customers environment and then I reproduced it in a few test environments. I've selected 1027 items in these screenshots because if I select all 1028 it just says "All conversations selected".
***@***.***D74717.99A6E2F0]

Here is a screenshot of the same behavior in another mailbox:
***@***.***D74717.CD57C420]

Please let me know if I have misunderstood anything or if I can provide any further evidence.

Kind regards,

Sam

**Comment by MaratMussabekov** [comment]
Hello, confirmed, you are correct.
in exchange server limit is 250, in exchange online - 1028
Thank you

**Comment by nam31** [comment]
Closing via #1487 
Thank you
