### ISSUE TITLE
Issue with WPJCleanUp script (Doesn't work)

### ISSUE THREAD

**Issue by sigfusvi227** [MicrosoftDocs/OfficeDocs-Support#1301]
Hello. I am trying to make the WPJCleanUp script to work but it doesn't seem to do anything. I've tried most of the things I know like run command as administrator and such but I can still see the Work account in the "Work or School" section. I am trying things out first on a Win10 Virtual Machine to see if the script work so I don't really know if it is the case, I highly doubt it. 

Basically what I get step by step is that I download the zip and unzip to desktop. Then I run the WPJCleanUp script and it opens up command prompt for a split second like it's doing something and then automatically closes it self like it worked. Then I go back to the "Work or school" but I still see the account there unremoved.

Win10 version is 20H2 (OS build 19042.867)

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1375a9d-fa30-75a2-5aea-daca0e74f142
* Version Independent ID: c9510807-f261-5a24-0039-d6bf5ad630e5
* Content: [Reset Microsoft 365 Apps for enterprise activation state - Office](https://docs.microsoft.com/en-us/office/troubleshoot/activation/reset-office-365-proplus-activation-state)
* Content Source: [Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md)
* Service: **o365-solutions**
* GitHub Login: @MJP-MSFT
* Microsoft Alias: **mattphil**

**Comment by MJP-MSFT** [comment]
+ @Eric ***@***.***> he wrote the latter part of the article and more familiar with WPJCleanup.

Matt Philipenko
Sr. Customer Engineer – Microsoft 365 Apps Ranger
Microsoft 365 Apps <Deployment/Servicing/Activation/>
10 Habits to create accessible content<https://blogs.microsoft.com/accessibility/10-habits-to-create-accessible-content/>



From: Sigfús Már Viðarsson ***@***.***>
Sent: Monday, April 26, 2021 8:10 AM
To: MicrosoftDocs/OfficeDocs-Support ***@***.***>
Cc: Matt Philipenko (OFFICE RANGER) ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/OfficeDocs-Support] Issue with WPJCleanUp script (Doesn't work) (#1301)


Hello. I am trying to make the WPJCleanUp script to work but it doesn't seem to do anything. I've tried most of the things I know like run command as administrator and such but I can still see the Work account in the "Work or School" section. I am trying things out first on a Win10 Virtual Machine to see if the script work so I don't really know if it is the case, I highly doubt it.

Basically what I get step by step is that I download the zip and unzip to desktop. Then I run the WPJCleanUp script and it opens up command prompt for a split second like it's doing something and then automatically closes it self like it worked. Then I go back to the "Work or school" but I still see the account there unremoved.

Win10 version is 20H2 (OS build 19042.867)

Thanks in advance!

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: e1375a9d-fa30-75a2-5aea-daca0e74f142
  *   Version Independent ID: c9510807-f261-5a24-0039-d6bf5ad630e5
  *   Content: Reset Microsoft 365 Apps for enterprise activation state - Office<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Foffice%2Ftroubleshoot%2Factivation%2Freset-office-365-proplus-activation-state&data=04%7C01%7Cmattphil%40microsoft.com%7C9ff5a2c5d174488a81b908d908b499b8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637550394031464448%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VoCjrf2p%2BZfXYW5SgaiEYlHafVnLvcx4FrsAkKoWgWI%3D&reserved=0>
  *   Content Source: Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-Support%2Fblob%2Fpublic%2FOffice%2FOfficeExperts%2Factivation%2Freset-office-365-proplus-activation-state.md&data=04%7C01%7Cmattphil%40microsoft.com%7C9ff5a2c5d174488a81b908d908b499b8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637550394031464448%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=G0Ef4%2BasDoYBJt9W7jBZ%2F6JfQdMCIXu9c%2BKm90S6PZI%3D&reserved=0>
  *   Service: o365-solutions
  *   GitHub Login: @MJP-MSFT<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMJP-MSFT&data=04%7C01%7Cmattphil%40microsoft.com%7C9ff5a2c5d174488a81b908d908b499b8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637550394031474442%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jqMRdGbVl0%2FLAtbndNll9xPYHNl0igpd7ornMD8BTj4%3D&reserved=0>
  *   Microsoft Alias: mattphil

**Comment by sigfusvi227** [comment]
Want to also note that I didn't get any error or anything inside the output.txt file

**Comment by MJP-MSFT** [comment]
The script was designed prior to 20H2. We are working to include this windows build.

Eric Splichal
Support Escalation Engineer
Office Deployment
701-281-7634
Working Hours: M-F 8:00am – 5:00pm CST

Need help outside of my working hours?
Manager: Lisa Bernhardson, ***@***.******@***.***>

[Image result for microsoft logo]

From: Matt Philipenko (OFFICE RANGER) ***@***.***>
Sent: Monday, April 26, 2021 8:15 AM
To: MicrosoftDocs/OfficeDocs-Support ***@***.***>; MicrosoftDocs/OfficeDocs-Support ***@***.***>; Eric Splichal ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/OfficeDocs-Support] Issue with WPJCleanUp script (Doesn't work) (#1301)

+ @Eric ***@***.***> he wrote the latter part of the article and more familiar with WPJCleanup.

Matt Philipenko
Sr. Customer Engineer – Microsoft 365 Apps Ranger
Microsoft 365 Apps <Deployment/Servicing/Activation/>
10 Habits to create accessible content<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fblogs.microsoft.com%2Faccessibility%2F10-habits-to-create-accessible-content%2F&data=04%7C01%7Cericspli%40microsoft.com%7C02b33a66b2a24a338bac08d908b5598a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637550397246109176%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1RYvirL4v5dkjjBaPD5m3eNIrs6tBvDIPcqCyNQTzYM%3D&reserved=0>



From: Sigfús Már Viðarsson ***@***.******@***.***>>
Sent: Monday, April 26, 2021 8:10 AM
To: MicrosoftDocs/OfficeDocs-Support ***@***.******@***.***>>
Cc: Matt Philipenko (OFFICE RANGER) ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: [MicrosoftDocs/OfficeDocs-Support] Issue with WPJCleanUp script (Doesn't work) (#1301)


Hello. I am trying to make the WPJCleanUp script to work but it doesn't seem to do anything. I've tried most of the things I know like run command as administrator and such but I can still see the Work account in the "Work or School" section. I am trying things out first on a Win10 Virtual Machine to see if the script work so I don't really know if it is the case, I highly doubt it.

Basically what I get step by step is that I download the zip and unzip to desktop. Then I run the WPJCleanUp script and it opens up command prompt for a split second like it's doing something and then automatically closes it self like it worked. Then I go back to the "Work or school" but I still see the account there unremoved.

Win10 version is 20H2 (OS build 19042.867)

Thanks in advance!

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: e1375a9d-fa30-75a2-5aea-daca0e74f142
  *   Version Independent ID: c9510807-f261-5a24-0039-d6bf5ad630e5
  *   Content: Reset Microsoft 365 Apps for enterprise activation state - Office<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Foffice%2Ftroubleshoot%2Factivation%2Freset-office-365-proplus-activation-state&data=04%7C01%7Cericspli%40microsoft.com%7C02b33a66b2a24a338bac08d908b5598a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637550397246119136%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Kt0G9pK1SUnGvxiFX0ucoUd0Msss6%2B6IfIANUrPtiKs%3D&reserved=0>
  *   Content Source: Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-Support%2Fblob%2Fpublic%2FOffice%2FOfficeExperts%2Factivation%2Freset-office-365-proplus-activation-state.md&data=04%7C01%7Cericspli%40microsoft.com%7C02b33a66b2a24a338bac08d908b5598a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637550397246129090%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hSGzkTNXHVYO%2Bamr3M9MJjrqtRmjA4%2FRs7AkUkLiCHI%3D&reserved=0>
  *   Service: o365-solutions
  *   GitHub Login: @MJP-MSFT<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMJP-MSFT&data=04%7C01%7Cericspli%40microsoft.com%7C02b33a66b2a24a338bac08d908b5598a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637550397246139043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2B2muWAGiXufEINXZVCAsg50vw4YUgTUXLf5P0kWVKZo%3D&reserved=0>
  *   Microsoft Alias: mattphil

**Comment by sigfusvi227** [comment]
> The script was designed prior to 20H2. We are working to include this windows build. Eric Splichal Support Escalation Engineer Office Deployment 701-281-7634 Working Hours: M-F 8:00am – 5:00pm CST Need help outside of my working hours? Manager: Lisa Bernhardson, ***@***.******@***.***> [Image result for microsoft logo] From: Matt Philipenko (OFFICE RANGER) ***@***.***> Sent: Monday, April 26, 2021 8:15 AM To: MicrosoftDocs/OfficeDocs-Support ***@***.***>; MicrosoftDocs/OfficeDocs-Support ***@***.***>; Eric Splichal ***@***.***> Cc: Mention ***@***.***> Subject: RE: [MicrosoftDocs/OfficeDocs-Support] Issue with WPJCleanUp script (Doesn't work) (#1301) + @eric ***@***.***> he wrote the latter part of the article and more familiar with WPJCleanup. Matt Philipenko Sr. Customer Engineer – Microsoft 365 Apps Ranger Microsoft 365 Apps <Deployment/Servicing/Activation/> 10 Habits to create accessible content<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fblogs.microsoft.com%2Faccessibility%2F10-habits-to-create-accessible-content%2F&data=04%7C01%7Cericspli%40microsoft.com%7C02b33a66b2a24a338bac08d908b5598a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637550397246109176%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1RYvirL4v5dkjjBaPD5m3eNIrs6tBvDIPcqCyNQTzYM%3D&reserved=0> From: Sigfús Már Viðarsson ***@***.******@***.***>> Sent: Monday, April 26, 2021 8:10 AM To: MicrosoftDocs/OfficeDocs-Support ***@***.******@***.***>> Cc: Matt Philipenko (OFFICE RANGER) ***@***.******@***.***>>; Mention ***@***.******@***.***>> Subject: [MicrosoftDocs/OfficeDocs-Support] Issue with WPJCleanUp script (Doesn't work) (#1301) Hello. I am trying to make the WPJCleanUp script to work but it doesn't seem to do anything. I've tried most of the things I know like run command as administrator and such but I can still see the Work account in the "Work or School" section. I am trying things out first on a Win10 Virtual Machine to see if the script work so I don't really know if it is the case, I highly doubt it. Basically what I get step by step is that I download the zip and unzip to desktop. Then I run the WPJCleanUp script and it opens up command prompt for a split second like it's doing something and then automatically closes it self like it worked. Then I go back to the "Work or school" but I still see the account there unremoved. Win10 version is 20H2 (OS build 19042.867) Thanks in advance!
> […](#)
> ________________________________ Document Details ⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking. * ID: e1375a9d-fa30-75a2-5aea-daca0e74f142 * Version Independent ID: c9510807-f261-5a24-0039-d6bf5ad630e5 * Content: Reset Microsoft 365 Apps for enterprise activation state - Office<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Foffice%2Ftroubleshoot%2Factivation%2Freset-office-365-proplus-activation-state&data=04%7C01%7Cericspli%40microsoft.com%7C02b33a66b2a24a338bac08d908b5598a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637550397246119136%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Kt0G9pK1SUnGvxiFX0ucoUd0Msss6%2B6IfIANUrPtiKs%3D&reserved=0> * Content Source: Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-Support%2Fblob%2Fpublic%2FOffice%2FOfficeExperts%2Factivation%2Freset-office-365-proplus-activation-state.md&data=04%7C01%7Cericspli%40microsoft.com%7C02b33a66b2a24a338bac08d908b5598a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637550397246129090%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hSGzkTNXHVYO%2Bamr3M9MJjrqtRmjA4%2FRs7AkUkLiCHI%3D&reserved=0> * Service: o365-solutions * GitHub Login: @MJP-MSFT<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMJP-MSFT&data=04%7C01%7Cericspli%40microsoft.com%7C02b33a66b2a24a338bac08d908b5598a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637550397246139043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2B2muWAGiXufEINXZVCAsg50vw4YUgTUXLf5P0kWVKZo%3D&reserved=0> * Microsoft Alias: mattphil — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-Support%2Fissues%2F1301&data=04%7C01%7Cericspli%40microsoft.com%7C02b33a66b2a24a338bac08d908b5598a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637550397246139043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zfcIkXO4Lgcak5L6Iyo5Yfinqtjcyb%2BUbdulIKMNcPo%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALV2LTXMIQLAJBQXZNUO6G3TKVQ2TANCNFSM43S3LVCQ&data=04%7C01%7Cericspli%40microsoft.com%7C02b33a66b2a24a338bac08d908b5598a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637550397246148999%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qRDG0fTsBbovyBzoJ84YsHkA3TI%2F8fwjYhAKArY83M4%3D&reserved=0>.

Thank you!
