### ISSUE TITLE
What is [*.]sfbassets.com ?

### ISSUE THREAD

**Issue by mgenelins** [MicrosoftDocs/OfficeDocs-Support#1302]
On this page we are asked to accept all cookies from a list of domains. While microsoft.com and others are clearly recognizable domains, what in the world is [*.]sfbassets.com ?

...And why would I need to allow cookies to access an Office 365 document that was shared with me, internal to my large corporation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c17faf2-0e38-0a98-454c-3c2c4387b37f
* Version Independent ID: d9153b98-dc39-fdd1-a798-07da0caaaa64
* Content: [Microsoft Teams is stuck in a login loop in Edge, Internet Explorer or Google Chrome - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#resolution)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by VLG17** [comment]
@mgenelins It's part of the [Global Endpoints / Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide) that are required for Skype for Business and Teams to work properly.

![image](https://user-images.githubusercontent.com/41186174/118131959-d36f7580-b407-11eb-8cb6-950fb3959b02.png)

**Comment by nam31** [comment]
@mgenelins Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
