### ISSUE TITLE
Script download links are broken

### ISSUE THREAD

**Issue by jeffkizn** [MicrosoftDocs/OfficeDocs-Support#1304]
The links to the PS1 scripts in this article return 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a449846-e325-24ba-ea5e-48d6f9c49b22
* Version Independent ID: 200173f7-9779-bd93-2272-4494da6f642d
* Content: [Archive mailbox can't be provisioned or deprovisioned after a mailbox is migrated to Office 365 Dedicated/ITAR vNext - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/archive-mailboxes/cannot-provision-deprovision)
* Content Source: [Microsoft365/compliance/archive-mailboxes/cannot-provision-deprovision.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/compliance/archive-mailboxes/cannot-provision-deprovision.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by simonxjx** [comment]
Links are updated.
