### ISSUE TITLE
I have this issue but there is no onsite exchange but it is a hybrid setup with local AD so how does that relate to this document?

### ISSUE THREAD

**Issue by webstaff** [MicrosoftDocs/OfficeDocs-Support#1306]
See title, no onsite exchange but yes to hybrid so should there be additional info to cover that scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a3774b7-97a1-78b9-2ffb-d7c718d0ad81
* Version Independent ID: e1c226c8-231c-d50a-6912-6360f7815c18
* Content: [550 5.1.10 RESOLVER.ADR.RecipientNotFound in Office 365. - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/email-delivery/recipientnotfound-ndr)
* Content Source: [Exchange/ExchangeOnline/email-delivery/recipientnotfound-ndr.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/email-delivery/recipientnotfound-ndr.md)
* Product: **office 365**
* GitHub Login: @Norman-sun
* Microsoft Alias: **v-swei**

**Comment by MaratMussabekov** [comment]
Hello,
**no onsite exchange but yes to hybrid** - how is that possible? hybrid Exchange deployment is a deployment where you have components described [here](https://docs.microsoft.com/en-us/exchange/exchange-hybrid#exchange-hybrid-deployment-components). May be you have Hybrid Azure AD, not hybrid Exchange?

**should there be additional info to cover that scenario** - 550 5.1.10 RESOLVER.ADR.RecipientNotFound error could be returned in any scenario where Exchange cannot find the recipient. This article is only dedicated to the case where on-prem exchange cannot find a mailbox that was created on cloud. Any other scenario is out of its scope.

For other scenarios, I would recommend to have a look at this article - https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-10-in-exchange-online

Thank you

**Comment by nam31** [comment]
@webstaff Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Comment by webstaff** [comment]
Sorry just to clarify, So yes its hybrid in terms of AD sync from on prem AD to office 365.
We had one mailbox sync from onsite AD to 365 and one mailbox 365 cloud only and the message we got was the one listed.
Cloud mailbox is the one who can't email the onsite sync'd to 365 user.
So the issue was almost exactly as listed in the document.

Very long story short though, was a weird forwarding issue causing that NDR for some reason.

**Comment by MaratMussabekov** [comment]
Hello @webstaff ,
**was a weird forwarding issue causing that NDR for some reason** - yes, this message could be returned in any scenario when recipient couldn't be found. Usually message trace parsing is required to find out the root cause.
Thank you!
