### ISSUE TITLE
Suggested changes to Article body text

### ISSUE THREAD

**Issue by wcorkill** [MicrosoftDocs/OfficeDocs-Support#1307]
This article should be expanded to better explain that this issue affects more products than the body text implies.  This problem exists with Outlook (v16 2019/O365) and document links from Office 365 (Sharepoint and OneDrive for Business)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ac3767-b57b-b9e0-b8e0-9a65d2ac21dc
* Version Independent ID: 61a1f6e1-4809-84b5-6f22-f133e5fb567b
* Content: [Document inserted as icon with hyperlink in message - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/message-body/document-inserted-as-icon-with-hyperlink)
* Content Source: [Outlook/Client/message-body/document-inserted-as-icon-with-hyperlink.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/document-inserted-as-icon-with-hyperlink.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by MaratMussabekov** [comment]
Hello @wcorkill ,
please have a look at https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1641
Thank you

**Comment by wcorkill** [comment]
@MaratMussabekov thanks for tagging me. #1641 looks like a good improvement to the description.

**Comment by nam31** [comment]
Closing via #1641 
Thank you
