### ISSUE TITLE
Forgot to add windows update as cause of graphical-/display issues in Office

### ISSUE THREAD

**Issue by chrisoutwright** [MicrosoftDocs/OfficeDocs-Support#1310]
You forgot to add that the latest windows update cause hardware acceleration bugs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d43aa283-d5e9-9b92-a7c9-f6bacede1b19
* Version Independent ID: 44cfded9-2ef6-751a-6558-b3bb21e35534
* Content: [Display issues in Office client applications. - Office](https://docs.microsoft.com/en-us/office/troubleshoot/settings/office-display-issues)
* Content Source: [Office/Client/settings/office-display-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/settings/office-display-issues.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@chrisoutwright Thank you for your feedback. Do you know which particular windows update causes issues with the display? 

Video card manufacturers frequently release updates to their drivers to improve performance or to fix compatibility issues with new programs. If you do not find an updated video driver for your computer through Windows Update and must have the latest driver for your video card, go to the support or download section of your video card manufacturer's website for information about how to download and install the newest driver.

Thanks
Sri

**Comment by nam31** [comment]
@chrisoutwright Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
