### ISSUE TITLE
Second normalization example explanation seems off

### ISSUE THREAD

**Issue by gtrimis** [MicrosoftDocs/OfficeDocs-Support#1314]
[Enter feedback here]
It seems that the explanation of the application of the second normal form is not right. It might be better to say that the advisor name and office number repeats, and applies to multiple records.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cd6dedf-a161-f49c-3a9f-f5a7bafafb41
* Version Independent ID: 180356f6-6484-19bd-3efe-79682a1152c1
* Content: [Database normalization description - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/database-normalization-description)
* Content Source: [Office/Client/access/database-normalization-description.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/database-normalization-description.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by dariomws** [comment]
Hi @gtrimis, thank you for your feedback.

I understand, but the advisor and adv-room are being used in the tried normalization room example. I modified the data to clearly show that you can have several students in the same class.

Please let me know if it looks good. Thanks!
