### ISSUE TITLE
Request update version of this issue for "Machine Wide" installs

### ISSUE THREAD

**Issue by jdehart-ca1** [MicrosoftDocs/OfficeDocs-Support#1316]
[Enter feedback here]
This document is geared towards the standard USER install,  however it appears that if you use the machine-wide install this article is completely wrong, and you shouldn't have any information in the reg keys for users, or this actually breaks things.  I would like to see an updated version of this document for a system-wide install

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 850ed2b6-a710-60b7-268b-7938ae86eb47
* Version Independent ID: f7017e61-de53-5e9b-6046-5f720a85d63c
* Content: [User presence status issues in Outlook - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-im-presence/issues-with-presence-in-outlook?tabs=32#resolution)
* Content Source: [Teams/teams-im-presence/issues-with-presence-in-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-im-presence/issues-with-presence-in-outlook.md)
* Service: **msteams**
* GitHub Login: @helenclu
* Microsoft Alias: **premgan**

**Comment by dariomws** [comment]
Hi @jdehart-ca1, thank you for your feedback.

To fix the issue in that case, please use the [Microsoft Support and Recovery Assistant](https://aka.ms/SaRA-TeamsPresenceScenario).

**Comment by nam31** [comment]
@jdehart-ca1 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
