### ISSUE TITLE
Link to architecture: landing page incorrect

### ISSUE THREAD

**Issue by marisolALDI** [MicrosoftDocs/OfficeDocs-Support#1318]
Link on text "Overview of Click-to-Run for Office 365 setup architecture" is:
https://docs.microsoft.com/en-us/previous-versions/office/jj219420(v=office.15)?redirectedfrom=MSDN
which lands on a page that states:
" This content is no longer available".

Could not find architecture in Deployment Guide linked on the landing page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdf4f7db-9b53-0da7-41ab-17a57c6a1481
* Version Independent ID: 6d01c403-6542-083b-5087-a8d8fb4d33b5
* Content: [Can't use the Access ODBC driver or OLEDB provider outside Office Click-to-Run - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/cannot-use-odbc-or-oledb)
* Content Source: [Office/Client/access/cannot-use-odbc-or-oledb.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/cannot-use-odbc-or-oledb.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by RAJU2529** [comment]
@marisolALDI , Thanks  for pointing out, i will remove the incorrect link and I will add a new link which is related to this article

**Comment by nam31** [comment]
Closing via #1337 
Thank you
