### ISSUE TITLE
Page needs updating

### ISSUE THREAD

**Issue by wolfenden** [MicrosoftDocs/OfficeDocs-Support#1319]
Page: 
https://docs.microsoft.com/en-us/outlook/troubleshoot/calendaring/delegate-receives-multiple-or-duplicate-meeting-requests

This page has a hyper link to : 
https://archive.codeplex.com/?p=mfcmapi

The page it links to states: 
CodePlex Archive will be shut down after July 1st, 2021.
CodePlex was Microsoft's free, open source project hosting site, which ran from 2006 through 2017. The site has been in archive mode for 3 years.

I think you need to update the link on this page to a new one within GitHub.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d97c0b6-c02d-0ddc-e46e-a42d37f2adcc
* Version Independent ID: aafd0e53-4238-9bdb-4993-8e8b7c6eaef3
* Content: [Delegate gets multiple or duplicate meeting requests - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/calendaring/delegate-receives-multiple-or-duplicate-meeting-requests)
* Content Source: [Outlook/Client/calendaring/delegate-receives-multiple-or-duplicate-meeting-requests.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/calendaring/delegate-receives-multiple-or-duplicate-meeting-requests.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by RAJU2529** [comment]
@wolfenden , Thanks for pointingout. I  will remove old link and i add new link now.

**Comment by nam31** [comment]
Closing via #1338
Thank you
