### ISSUE TITLE
Resolution uses wrong path

### ISSUE THREAD

**Issue by kwbskf** [MicrosoftDocs/OfficeDocs-Support#132]
INetCacheContent.Word  should really be INetCache\Content.Word

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93e74201-5f92-5dea-43a7-abc06e04657b
* Version Independent ID: 1425fb4e-4889-8cdc-ef46-d01a31392d73
* Content: [Word could not create the work file error message when you save a document - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/word-could-not-create-the%20work-file)
* Content Source: [Office/Client/word/word-could-not-create-the-work-file.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/word-could-not-create-the%20work-file.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@kwbskf this article has been retired.
You can find more information regarding the issue that you raised on the updated page https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/no-file-previews-file-explorer-switching-to-32-bit
Please feel free to raise a ticket using the Feedback section of the article if you still face any issue regarding the article.
Thanks
