### ISSUE TITLE
Any plans to remove this limitation?

### ISSUE THREAD

**Issue by toxarisswe** [MicrosoftDocs/OfficeDocs-Support#1320]
Hello.

This is an issue when running Teams in an VDI environment for example. Are there any plans to remove this limitation in order to be able to Give/Take Control in an environment where the client do not have access to hardware graphics acceleration? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20956786-4935-bca3-9c57-1f6bb9401da8
* Version Independent ID: 6be80e4f-36bc-6c5d-926c-003132fc4e31
* Content: [Give control doesn't work when you share screen in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-conferencing/give-control-doesn%E2%80%99t-work-sharescreen?source=docs)
* Content Source: [Teams/teams-conferencing/give-control-doesn’t-work-sharescreen.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-conferencing/give-control-doesn’t-work-sharescreen.md)
* Service: **msteams**
* GitHub Login: @helenclu
* Microsoft Alias: **sarvdon**

**Comment by dariomws** [comment]
Hi @toxarisswe, thank you for your feedback.

I'm not aware of any plan to remove this limitation. I know the product teams are always looking for user feedback and how to make Teams better. They keep a close tab on user feedback, and it would be awesome to add your voice in User Voice https://microsoftteams.uservoice.com/.

You might find others have made a similar request that you can add to, or you can open a new one. For example:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/42285130-allow-control-of-gpu-acceleration-by-gpo-or-regist

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by nam31** [comment]
@toxarisswe Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
