### ISSUE TITLE
looking for answers 

### ISSUE THREAD

**Issue by loodini** [MicrosoftDocs/OfficeDocs-Support#1321]
Hi, 

This is exactly the issue I am having at work and looking to fix. The workaround says turn AutoSave off to open the current file on the server, but autosave is off and I am still having this issue. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a2f88c1-3f35-2433-0639-401888ed6792
* Version Independent ID: cbc52b66-404b-c7cc-c8d8-cf2477d5822b
* Content: [Microsoft 365 apps open files from SharePoint on-premises that aren’t the current version - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/office-opens-outdated-files)
* Content Source: [Office/Client/office-suite-issues/office-opens-outdated-files.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/office-opens-outdated-files.md)
* Product: **sharepoint**
* GitHub Login: @v-matham
* Microsoft Alias: **v-matham**

**Comment by dariomws** [comment]
Hi @loodini, thank you for your feedback.

Could you kindly double-check that you are following all the requirements/steps in the article?

You are using Microsoft 365 Apps to open a file located in SharePoint Server (on-premises version). You also turned off Autosave by adding the DWORD value "autosavebydefaultadminchoice" with "2" under the HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\word or HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\powerpoint subkey.

**Comment by nam31** [comment]
@loodini We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
