### ISSUE TITLE
Typo, missed a space before the word directory

### ISSUE THREAD

**Issue by TalkingToes** [MicrosoftDocs/OfficeDocs-Support#1322]
[Enter feedback here]

Near the bottom of the page is "_C:\Program Files\Microsoft\Exchange Server\v15\Bin\directory_"  in italics.

The example path is incorrect. It does not include the "\directory"  but, it could be _C:\Program Files\Microsoft\Exchange Server\v15\Bin\_ directory. (The word directory fits the sentence, but not as part of the path).  The example folder does not exist on Exchange 2019.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f757dd9-63ac-62bc-514c-f499951cac3d
* Version Independent ID: 9fb3dd48-4074-5127-275e-5f2cf94bdf40
* Content: [OWA or ECP stops working after you install a security update - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/client-connectivity/owa-stops-working-after-update)
* Content Source: [Exchange/ExchangeServer/client-connectivity/owa-stops-working-after-update.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/client-connectivity/owa-stops-working-after-update.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @batre
* Microsoft Alias: **v-matham**

**Comment by nam31** [comment]
Closing via #1363 
Thank you
