### ISSUE TITLE
Method 2 instruction for Dutch Windows10 

### ISSUE THREAD

**Issue by nvhv** [MicrosoftDocs/OfficeDocs-Support#1324]
[Voer hier feedback in]
HKEY_LOCAL_MACHINE\Software\Classes\htmlfile\shell\open\command
In Dutch Windows10 _html_ could be found, but not _htmlfile_
---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 7f736e25-4b81-c26f-ee4d-640519094af6
* Version Independent ID: 9343708d-ccf7-2e46-d377-13564037a5b9
* Content: [Hyperlinks werken niet - Outlook](https://docs.microsoft.com/nl-nl/outlook/troubleshoot/message-body/hyperlinks-not-working-in-outlook)
* Content Source: [Outlook/Client/message-body/hyperlinks-not-working-in-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/hyperlinks-not-working-in-outlook.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by MaratMussabekov** [comment]
Hello,
Classes are not locale-sensitive, and they are the same for any version of Windows 10.
Can you please check again? may be on another computer with Dutch version of Windows 10

thank you

**Comment by MaratMussabekov** [comment]
Hello @nvhv ,
did you have time to check it?
Thank you

**Comment by nam31** [comment]
@nvhv We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
