### ISSUE TITLE
If you do not see a value of 49 for this property, go on to step d.  should be "on to step l."

### ISSUE THREAD

**Issue by stevecharon** [MicrosoftDocs/OfficeDocs-Support#1325]
In step k. it is mentioned that if you not see the default value 49 (0x31) you should go on to step d which would be leading back to starting mfcmapi what you would be anyway since this is already done.
To get the correct statement step k should mention step l:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81b9e548-8b47-8450-b43f-03c235d2345d
* Version Independent ID: bb938e2f-aa98-70b3-a046-97d1427df045
* Content: [You are over Junk E-mail list limit - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/junk-email/outlook-error-over-junk-emial-list-limit)
* Content Source: [Outlook/Client/junk-email/outlook-error-over-junk-emial-list-limit.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/junk-email/outlook-error-over-junk-emial-list-limit.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by nam31** [comment]
Closing via #1364
Thank you
