### ISSUE TITLE
Unclear instructions at points 10 & 11

### ISSUE THREAD

**Issue by SpaceCivilization** [MicrosoftDocs/OfficeDocs-Support#1329]
Unable to find an ‘Edit’ menu in the most recent version of Excel. Also unable to find a ‘Links’ button that goes to a dialog box like the one described. Is this in the most recent version of Excel and Visio? Pictures would definitely be helpful here. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0978476-f804-5686-d24b-99c854db57dd
* Version Independent ID: 68059573-0170-14d3-1876-3e07124f687b
* Content: [How to link a Visio drawing to a specific region in an Excel worksheet - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/link-visio-drawing-to-a-specific-region)
* Content Source: [Office/Client/excel/link-visio-drawing-to-a-specific-region.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/link-visio-drawing-to-a-specific-region.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by dariomws** [comment]
Hi @SpaceCivilization, thank you for your feedback.

I'm updating the steps, and they'll be live in the next couple of days.

Please try:

1. Open your worksheet in Microsoft Excel.
2. Select the range of cells that you want to link to.
3. On the Formulas menu, click Define Name.
4. In the Define Name dialog box, type a unique name and then click OK.
5. Save the Microsoft Excel Workbook.
6. Start Microsoft Visio and open your drawing.
7. On the Insert menu, click Object.
8. In the Insert Object dialog box, click **Create from file** and then click Browse. Navigate to your Excel workbook, select it, and click Open.
9. Click to select the **Link to file** check box, and then click OK.
10. In the **Tell me what you want to do** box, type and click Links.
11. In the Links dialog box, select the link to the Excel worksheet, click **Automatic** under Update, and then click **Change Source**.
12. In the Item Name box, type the name defined in step 4, and then click Open.
13. Click **Update Now**, and then click Close.
