### ISSUE TITLE
AllowConsecutiveSlashesInUrlPathComponent registry subkey is wrong

### ISSUE THREAD

**Issue by Diesel1017** [MicrosoftDocs/OfficeDocs-Support#1330]
**The Registry subkey is wrong!**
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\x.0\Common

**With Office 2019 when i create the key nothing is changed! (AllowConsecutiveSlashesInUrlPathComponent)**
HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common

**The good path:**
HKEY_CURRENT_USER\Software\Microsoft\Office\Common

**Source:**
https://stackoverflow.com/questions/2101555/double-slashes-in-urls-in-outlook

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8a246ba-7c5d-75af-8dc5-4a83e8269a0e
* Version Independent ID: 7f8a969f-324c-74ec-7fa1-05fdc5e567ae
* Content: [URL multiple slashes are changed to a single slash - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/message-body/url-multiple-slashes-become-single-slash)
* Content Source: [Outlook/Client/message-body/url-multiple-slashes-become-single-slash.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/url-multiple-slashes-become-single-slash.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by nam31** [comment]
Closing via #1409 
Thank you
