### ISSUE TITLE
Should also include the requirement that the user must be in TeamsOnly mode.

### ISSUE THREAD

**Issue by jpalarchio** [MicrosoftDocs/OfficeDocs-Support#1332]
If the user is in Islands mode, the dial pad will also fail to appear as it is not a supported mode.  We should add this to the list.

_Phone System isn't supported in Teams in Islands mode. Islands mode doesn't support Enterprise Voice client is Skype for Business._

https://docs.microsoft.com/en-us/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e700b86-b8ed-2056-063b-df5eb6117743
* Version Independent ID: 08018f7e-651b-6991-95d3-52e1748d8505
* Content: [Dial pad in missing in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-conferencing/no-dial-pad)
* Content Source: [Teams/teams-conferencing/no-dial-pad.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-conferencing/no-dial-pad.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **kellybos**

**Comment by nam31** [comment]
Closing via #1368 
Thank you
