### ISSUE TITLE
Internet Explorer should be replaced by Edge ASAP!

### ISSUE THREAD

**Issue by lalazarescou** [MicrosoftDocs/OfficeDocs-Support#1333]
This is the third request to update this page (2 from another user) - customers have a multitude of problems using IE and it's being discontinued in August 2021 so please change documentation to encourage them to make Edge their default browser.  This is time critical since we are also discontinuing Skype for Business and more users are using Teams every day.  Thank you

**Comment by nam31** [comment]
@lalazarescou The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@lalazarescou We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
