### ISSUE TITLE
MS Recording became tmp prefix and became not accessible even after 13hrs.

### ISSUE THREAD

**Issue by harshithsk** [MicrosoftDocs/OfficeDocs-Support#1334]
Hi,

My meeting recording became inaccessible. 
A screenshot of the same is below
![image](https://user-images.githubusercontent.com/3191811/117105452-ab469d80-ad9b-11eb-94b5-7538125275a9.png)

Any help is appreciated.

Regards,
Harshit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 257d97c1-20b6-143b-d6a8-f061f206b113
* Version Independent ID: ed549113-a90f-d5a2-3294-52d86f29bde9
* Content: [Issues with meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/meetings/troubleshoot-meeting-recording-issues)
* Content Source: [Teams/meetings/troubleshoot-meeting-recording-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/meetings/troubleshoot-meeting-recording-issues.md)
* Service: **msteams**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by dariomws** [comment]
Hi @harshithsk, thank you for your feedback and help us to improve docs.microsoft.com.

I think you need to free up space in your OneDrive storage. If you still have the issue, the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by harshithsk** [comment]
I contacted. still nothing they can help out. 
Strangely I have freely Business support, support team couldn't help me as I am not paid.

**Comment by dariomws** [comment]
Hi @harshithsk, my apologies but we cannot help here as we are limited to documentation issues and improvements.
