### ISSUE TITLE
Contradicting messages

### ISSUE THREAD

**Issue by mikalar** [MicrosoftDocs/OfficeDocs-Support#1336]
The resolution says to enable third-party cookies but the instructions points say to disable third-party cookies and the picture also shows to disable rather than enable.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3f23881-693f-f82e-7fc2-7b9f73b29090
* Version Independent ID: 5ea1b8c7-f978-bcca-1d92-01df10f747ae
* Content: [Error (We can't get the activity log) when accessing the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-administration/cannot-access-admin-center)
* Content Source: [Teams/teams-administration/cannot-access-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-administration/cannot-access-admin-center.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **scapero**

**Comment by VLG17** [comment]
@mikalar In order to enable 3rd party cookies, as the resolution states, you will need to disable the feature "Block third-party cookies". Both article and picture are correct.

It's like a double negation. You set to disabled a feature which is blocking cookies, meaning you allow cookies.

**Comment by nam31** [comment]
@mikalar Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
