### ISSUE TITLE
Login Loop

### ISSUE THREAD

**Issue by BobSarfo** [MicrosoftDocs/OfficeDocs-Support#1339]
If the system date and time is wrong, It can also cause sign-in loop. Kindly correct the date and time and check the daylight savings. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c17faf2-0e38-0a98-454c-3c2c4387b37f
* Version Independent ID: d9153b98-dc39-fdd1-a798-07da0caaaa64
* Content: [Microsoft Teams is stuck in a login loop in Edge, Internet Explorer or Google Chrome - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by nk-gears** [comment]
Hello @BobSarfo,

Thanks for your suggestion. We will update the docs with that suggestion and get back you in few days.

**Comment by nam31** [comment]
Closing via #1616 
Thank you
