### ISSUE TITLE
What about Office 2019?

### ISSUE THREAD

**Issue by the-epoch** [MicrosoftDocs/OfficeDocs-Support#134]
The registry key path (Method 1, Step 2) has a note for the versions of Office that the key relates to, but Office 2019 is not mentioned on the note. Does Office 2019 require the same registry key addition?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63db99b0-97d7-f1a4-b3b2-ec80a6a6b43c
* Version Independent ID: d74dbce7-c3d4-353e-a990-ad6447597b66
* Content: [Messages sent from a shared mailbox aren't saved to the Sent Items folder - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/shared-mailboxes/sent-mail-is-not-saved#feedback)
* Content Source: [Exchange/ExchangeOnline/shared-mailboxes/sent-mail-is-not-saved.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/shared-mailboxes/sent-mail-is-not-saved.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Rich-The-Tech** [comment]
We have just been looking into this and it seems to stop at 16.0

I have office 2019 and still see 16.0 and when I edit registry keys in there it effects office 2019 with the desired results.

Hope this helps.

**Comment by sys-kutzner** [comment]
We can confirm that 16.0 is also the right "version" for Office 2019.

We brought out method 2 via GPO and it worked well with Office 2016. Only on Office 2019 the sent messages from a shared mailbox are still only in the main mailbox, although the GPO/registry settings are rightly deployed. Also Outlook is in cached mode. Any ideas?

**Comment by nam31** [comment]
Closing via #1452 
Thank you
