### ISSUE TITLE
Excel's 1900-02-29 bug

### ISSUE THREAD

**Issue by PaulMargus** [MicrosoftDocs/OfficeDocs-Support#1342]
I think that Excel's 1900-02-29 should be fixed.  To prevent any disruption, "Thu, 1900-03-01" should retain its "day 61" serial number, so that all later dates remain similarly unchanged.   "Wed, 1900-02-28" (not Tue!) should get a new "day 60" serial, and so on down to "serial 1" for "Sun, 1899-12-31".   It may even make sense to extend the serial number into negative territory, to cover the 19th century.   That would help professional historians.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e28dce76-cc6a-3af7-b51b-48ea6ba8b3ef
* Version Independent ID: c691ecbb-6184-a73b-2f25-2d72eccd8a14
* Content: [Excel incorrectly assumes that the year 1900 is a leap year - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/wrongly-assumes-1900-is-leap-year)
* Content Source: [Office/Client/excel/wrongly-assumes-1900-is-leap-year.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/wrongly-assumes-1900-is-leap-year.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by nam31** [comment]
@PaulMargus Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
