### ISSUE TITLE
Teams update process when the App is not signed-in [for guest meeting attendees]

### ISSUE THREAD

**Issue by na1D** [MicrosoftDocs/OfficeDocs-Support#1345]
Great to improve the wording on this page and explain how the Teams App updates itself for Meeting Guest attendee users - for users that are typically not signed in to Teams and running the full Teams App experience.

This para. - "Users can also manually download updates by selecting Check for updates on the Profile drop-down menu on the top right of the app. If an update is available, it will be downloaded and silently installed when the computer is idle." won't be relevant to such users.

Let's explain the specific update process for the scenario where Teams is running, but not signed-in - if the client is still updating in the background, when a meeting is not active, let's state that specifically.

Thx

Ian...
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03680c46-ebfc-9d54-168b-214f8c8e9de9
* Version Independent ID: 929c0e47-28df-c61a-2359-93ae53d75031
* Content: [Automatic update not working in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/known-issues/teams-doesnt-automatically-update)
* Content Source: [Teams/known-issues/teams-doesnt-automatically-update.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/known-issues/teams-doesnt-automatically-update.md)
* Service: **msteams**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@na1D Thank you for your feedback. Per design, Users need to be signed in for updates to be downloaded. I have added that to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1416

Thanks
Sri

**Comment by na1D** [comment]
Personally, I still think the article could be clearer - sorry.

Your update "_Users need to be signed in for updates to be downloaded._" would read better as _"Users need to be signed in for updates to be manually downloaded using Check for updates on the Profile drop-down menu._".

...But, the change doesn't really address my original clarification query - namely; "Let's explain the specific update process for the scenario where Teams is running, _but not signed-in_.". That's what I was looking to understand.

**Comment by nam31** [comment]
Closing via #1416 
Thank you
