### ISSUE TITLE
Degree symbol cannot display properly

### ISSUE THREAD

**Issue by futandrew** [MicrosoftDocs/OfficeDocs-Support#1346]
After implementing this VBA in my excel, the degree symbol (°) cannot display properly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be969d50-8518-365f-f3ed-5c0e14d55104
* Version Independent ID: 11bad482-781b-bbae-ce60-53f8164d137e
* Content: [Convert degrees/minutes/seconds angles to or from decimal angles - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/convert-degrees-minutes-seconds-angles)
* Content Source: [Office/Client/excel/convert-degrees-minutes-seconds-angles.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/convert-degrees-minutes-seconds-angles.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by dariomws** [comment]
Hi @futandrew, thank you for your feedback.

I've tested it and seems to works as it's documented:
![image](https://user-images.githubusercontent.com/33589238/118259346-54cf1280-b4b1-11eb-80f9-0ccc96244405.png)

If you have any problem with this function please read the following sentences included in the article:

Microsoft provides programming examples for illustration only, without warranty either expressed or implied, including, but not limited to, the implied warranties of merchantability and/or fitness for a particular purpose. This article assumes that you are familiar with the programming language being demonstrated and the tools used to create and debug procedures. Microsoft support professionals can help explain the functionality of a particular procedure, but they will not modify these examples to provide added functionality or construct procedures to meet your specific needs.

 If you have limited programming experience, you may want to contact Microsoft Advisory Services. For more information, visit the Microsoft Web site:

Microsoft Advisory Services - [https://support.microsoft.com/gp/advisoryservice](https://support.microsoft.com/gp/advisoryservice)

For more information about the support options that are available and about how to contact Microsoft, see [https://support.microsoft.com](https://support.microsoft.com).

**Comment by nam31** [comment]
@futandrew Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
