### ISSUE TITLE
Additional Location for signinoptions key

### ISSUE THREAD

**Issue by tadakk** [MicrosoftDocs/OfficeDocs-Support#1347]
[Enter feedback here]
We found other locations where the signinoptions key is stored.
This was causing Exchange online sign in issues for Outlook.
We found the setting under HKEY_USERS\<sid>\Software\Office\16.0\Common\Signin
SignInOptions was set to 3.

This was not in HKEY_CURRENT_USER but still affected the logged in user.
Thanks,
Tommy Paulk

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab3b3b72-87a5-8b6f-f049-0500b0cbee6e
* Version Independent ID: b8a259e9-cb59-936d-f38f-e157772ca311
* Content: [This feature has been disabled by your administrator error in Microsoft Office - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/office-feature-disabled?source=docs)
* Content Source: [Microsoft365/admin/access-management/office-feature-disabled.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/access-management/office-feature-disabled.md)
* Service: **sharepoint-powershell**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by joinimran** [comment]
@tadakk - Can you please confirm, 
1. If the <SID> is the current user's SID, then the key is the same as the one under HKCU. Otherwise, it won't affect the current user's sign-in.
2. If it's HKEY_USERS\.DEFAULT, it may affect the current user.

This information will help to add up the exact and correct information in the article. 

Thanks,
Imran.

**Comment by joinimran** [comment]
@tadakk - We are looking for your input? Can you please update?

**Comment by joinimran** [comment]
@tadakk - Any input from your side will be highly appreciated.

**Comment by nam31** [comment]
@tadakk We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
