### ISSUE TITLE
More details on supposed dependency.

### ISSUE THREAD

**Issue by AdrianRaduMS** [MicrosoftDocs/OfficeDocs-Support#1348]
Hello. Could you kindly give more info in regards to the note that says _"You may have previously enabled this feature, or it may have been enabled because it's required for other features that you're using, such as Publishing sites."_  Is there any actual dependency with Publishing infrastructure that customers would need to be aware of, when they disable  Limited-access user permission lockdown mode? If there is none, could you please modify the note to fit the criteria and if there are dependencies, would you be so kind as to list them so people can better understand what disabling that feature which gets automatically enabled with Publishing Infrastructure does? 

Thank you! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4d624d5-6ac4-16ff-f212-0c16d0291e2c
* Version Independent ID: 26a3bff8-8ce5-f2d5-df72-d10176a86657
* Content: [Users cannot access a shared folder in SharePoint Online - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sharing-and-permissions/cannot-access-shared-folder)
* Content Source: [SharePoint/SharePointOnline/sharing-and-permissions/cannot-access-shared-folder.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sharing-and-permissions/cannot-access-shared-folder.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by Reeced40** [comment]
@AdrianRaduMS thank you for reaching out. Please have a look at these two articles that show the implications of this feature being on or off. https://techcommunity.microsoft.com/t5/sharepoint/publishing-infrastructure-turn-off-implications/m-p/59288
and https://social.technet.microsoft.com/Forums/office/d37eadbc-5671-48d3-addf-55ad92de0971/what-happens-when-you-disable-sharepoint-publishing. Please let me know if it helps at all and if you think I should add these links to the article to help other users.

**Comment by AdrianRaduMS** [comment]
Hello @Reeced40 . Thanks a lot for the reply. If you could kindly include some of the info in the note, I believe people would find it greatly useful. I had a case with a customer who raised these exact questions.

Best regards!

**Comment by Reeced40** [comment]
@nam31  this can be closed thank you.

**Comment by nam31** [comment]
Closing via #1402 
Thank you
