### ISSUE TITLE
What Edit Menu?

### ISSUE THREAD

**Issue by keith2237** [MicrosoftDocs/OfficeDocs-Support#1349]
The portion from step 10 on down makes no sense. What Edit menu? Excel? Visio? Neither has an Edit menu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0978476-f804-5686-d24b-99c854db57dd
* Version Independent ID: 68059573-0170-14d3-1876-3e07124f687b
* Content: [How to link a Visio drawing to a specific region in an Excel worksheet - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/link-visio-drawing-to-a-specific-region)
* Content Source: [Office/Client/excel/link-visio-drawing-to-a-specific-region.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/link-visio-drawing-to-a-specific-region.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by dariomws** [comment]
Hi @keith2237, thank you for your feedback.

It's the same issue as https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1329. I'm updating the article and also added some information in my comment.

Steps 1 to 5 in Excel, since step 6 Visio.

**Comment by nam31** [comment]
Closing via #1369 
Thank you
