### ISSUE TITLE
How to fix on Mac?

### ISSUE THREAD

**Issue by TorQueMoD** [MicrosoftDocs/OfficeDocs-Support#135]
All of the solutions to this error are for windows. How do you fix this on a Mac?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93e74201-5f92-5dea-43a7-abc06e04657b
* Version Independent ID: 1425fb4e-4889-8cdc-ef46-d01a31392d73
* Content: [Word could not create the work file error message when you save a document - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/word-could-not-create-the%20work-file#feedback)
* Content Source: [Office/Client/word/word-could-not-create-the%20work-file.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/word-could-not-create-the%20work-file.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@TorQueMoD Are you still seeing this issue? The article you linked do not exist anymore (404 - Page not found).

[This article](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/no-file-previews-file-explorer-switching-to-32-bit) describes what needs to be done to fix this issue.

For Mac specifically I would always start with checking for updates and installing what's missing : https://support.microsoft.com/en-us/office/update-office-for-mac-automatically-bfd1e497-c24d-4754-92ab-910a4074d7c1

**Comment by VLG17** [comment]
@TorQueMoD could you check the info above and share an update?

**Comment by nam31** [comment]
@TorQueMoD We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
