### ISSUE TITLE
Agenda/feestdagen

### ISSUE THREAD

**Issue by WimHekken** [MicrosoftDocs/OfficeDocs-Support#1350]
Helaas is de helpfile voor problemen met Outlook niet volledig; elk spoor voor het oplossen van de fouten in het "feestdagen" bestand ontbreken. Veel feestdagen zijn niet meer te zien in de agenda, als voorbeeld pasen en pinksteren.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: eed58735-0119-ca29-71f2-f583d254552b
* Version Independent ID: d9a93396-5498-053d-0360-11dcdd8de68c
* Content: [Enkele problemen voor Outlook op een lijst - Outlook](https://docs.microsoft.com/nl-nl/outlook/troubleshoot/outlook-client-welcome)
* Content Source: [Outlook/Client/outlook-client-welcome.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/outlook-client-welcome.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by dariomws** [comment]
Hi @WimHekken, thank you for your feedback and help us to improve docs.microsoft.com.

My apologies, but I think I don't understand. Are you suggesting that a new article should be added to the Outlook errors section?

**Comment by WimHekken** [comment]
Wow, that was a loooong time ago, I almost forgot what it was about, but that might be my age….

 

The (Dutch?) holydays in Outlook are wrong on many occasions.

It’s not the first time that Microsoft messes this up, but on previous occasions the faults where quickly repaired.

This time there is no correction from MS.

I deleted the holydays and imported them from Google, but I don’t think that is a Microsoft worthy solution…….

 

 

Bye, Jan

 

 

Van: Dario Woitasen ***@***.*** 
Verzonden: zaterdag 10 juli 2021 10:05
Aan: MicrosoftDocs/OfficeDocs-Support
CC: WimHekken; Mention
Onderwerp: Re: [MicrosoftDocs/OfficeDocs-Support] Agenda/feestdagen (#1350)

 

Hi @WimHekken <https://github.com/WimHekken> , thank you for your feedback and help us to improve docs.microsoft.com.

My apologies, but I think I don't understand. Are you suggesting that a new article should be added to the Outlook errors section?

**Comment by dariomws** [comment]
Hi @WimHekken, thank you so much for your explanation.

The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information provided at [Get support](https://docs.microsoft.com/microsoft-365/business-video/get-help-support). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).

They will be able to help you as here we are limited to documentation issues and improvements.
