### ISSUE TITLE
feestdagen fout

### ISSUE THREAD

**Issue by WimHekken** [MicrosoftDocs/OfficeDocs-Support#1351]
Het is een schande dat er hier aangegeven wordt hoe je handmatig de blunders van Microsoft moet oplossen. Dat moet Microsoft zelf doen!!!!!

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 4c927cdc-ee29-cbbb-6966-d0f5a1d58f93
* Version Independent ID: 46387189-6555-f299-6092-06e9df727da6
* Content: [Onjuiste feestdagen in .hol-bestanden - Outlook](https://docs.microsoft.com/nl-nl/outlook/troubleshoot/calendaring/incorrect-holidays-in-hol-files)
* Content Source: [Outlook/Client/calendaring/incorrect-holidays-in-hol-files.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/calendaring/incorrect-holidays-in-hol-files.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by nam31** [comment]
@WimHekken Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
