### ISSUE TITLE
Other IPs than the ones listed in the page are used

### ISSUE THREAD

**Issue by okand** [MicrosoftDocs/OfficeDocs-Support#1352]
Just got a voice mail email delivered from 104.47.12.56 instead of the IPs listed on this page and thus it failed SPF and got stuck.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef6fd529-a369-9afd-ce21-4cb8b415f6c4
* Version Independent ID: 9e7c3225-ddba-1af5-c2f0-ab3da394f02f
* Content: [Voicemail messages are not delivered in Teams or Skype for Business client - Skype for Business](https://docs.microsoft.com/en-us/SkypeForBusiness/troubleshoot/hybrid-phone-system/voicemails-not-delivered)
* Content Source: [SkypeforBusiness/SkypeHybrid/hybrid-phone-system/voicemails-not-delivered.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeHybrid/hybrid-phone-system/voicemails-not-delivered.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @Norman-sun
* Microsoft Alias: **v-swei**

**Comment by dariomws** [comment]
Hi @okand, thank you for your feedback and help us to improve docs.microsoft.com.

That section in this article was updated 1 month ago, and now it redirects you to the article which lists all the IP addresses for Office 365.

**Comment by nam31** [comment]
@okand Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
