### ISSUE TITLE
Mails stuck in Outlook (New UI) on macOS – Solutions for devices non macOS

### ISSUE THREAD

**Issue by asseeger** [MicrosoftDocs/OfficeDocs-Support#1353]
I would argue that this is pretty bad – I do have an issue with the new Outlook on __macOS__, where a message from an IMAP account (yes, this still is and will be a thing for quite some more time...) remains in the Outbox folder and all proposed solutions do not mention macOS/a means of fixing this on macOS __at all__.

I switched back to the old Outlook – I guess there is still some way to go for the new Outlook...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 255b5732-ef8a-f040-4cde-d9fc40486764
* Version Independent ID: 053a2e2a-d7a1-2562-8d83-b65263c6ec92
* Content: [Email messages are stuck in Outbox in Outlook 2016 for Mac - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/send-receive-emails/email-stuck-in-outbox-outlook-2016-mac)
* Content Source: [Outlook/Mac/send-receive-emails/email-stuck-in-outbox-outlook-2016-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Mac/send-receive-emails/email-stuck-in-outbox-outlook-2016-mac.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@asseeger Thank you for your feedback. The document is specifically for an issue wherein the sent items folder gets renamed and causes emails to be stuck in the outbox. So the steps provided might not be able to resolve the issue with IMAP accounts.

We recommend you update outlook to Version 16.49 (Build 21050901) released on May 11 to see if that helps.

Thanks
Sri

**Comment by nam31** [comment]
@asseeger Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
