### ISSUE TITLE
Atualização no modo de visualização do contatos auto completar

### ISSUE THREAD

**Issue by ma4celo** [MicrosoftDocs/OfficeDocs-Support#1354]
Recentemente teve uma atualização na visualização dos contatos rapidos do auto completar e com isso dificultou a visualização pois quando voce começa a digitar o endereço de e-mail o historico ficou muito grande e não tem mais a caixa de rolagem para selecionar o endereço impossibilitanto selecionar o endereço de e-mail.

Alguem de voces ja deve essa atualização? Saberiam como alterar para visualização antiga?

https://i.ibb.co/99QrT0g/contatos.jpg

Estamos usando o Office home and bussiness 2016

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: ba9d1611-1eab-6734-c76a-9d42ef563c60
* Version Independent ID: e97f1158-d35c-f6a7-125a-577df5a9e9b5
* Content: [AutoComplete não está funcionando corretamente - Outlook](https://docs.microsoft.com/pt-br/outlook/troubleshoot/contacts/autocomplete-not-working-correctly-in-outlook-2010)
* Content Source: [Outlook/Client/contacts/autocomplete-not-working-correctly-in-outlook-2010.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/contacts/autocomplete-not-working-correctly-in-outlook-2010.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@ma4celo Thank you for your feedback. This document pertains only to outlook 2010. I'd suggest you check for the latest update for the home and business suite and let us know if you continue to have problems.

Thanks
Sri

**Comment by msbemba** [comment]
@ma4celo Just circling back to check if you continue to have problems or are we good to close this issue.

Thanks
Sri
