### ISSUE TITLE
Recommended fix does not work.

### ISSUE THREAD

**Issue by BROnstott** [MicrosoftDocs/OfficeDocs-Support#1355]
Hi.  The body of my outlook email messages started showing up blank today.  I tried looking for avgoutlook in the registry, and can't find it.  
---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6235ea9-d8df-c7c8-5540-402bbf2bf459
* Version Independent ID: 887b3e23-dd0b-caa8-0a20-3f754fc9bb86
* Content: [Email message body is blank in Outlook - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/message-body/email-message-body-is-blank-in-outlook)
* Content Source: [Outlook/Client/message-body/email-message-body-is-blank-in-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/email-message-body-is-blank-in-outlook.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by osensnolf** [comment]
Same for me.  Some text emails show 1 or 2 lines of text and some emails flash the content but quickly it disappears.  It works on the phone and if I forward it to someone else then the content is correct.  It happens with all of my email accounts in Outlook 365 desktop.

**Comment by ChixyChux** [comment]
Exactly the same as osensnolf described - emails blank, or just showing first line, and a brief flash of the contents when clicking an email. Just started this evening. I don't have AVG installed, so not that.

**Comment by osensnolf** [comment]
If any of you find a solution, please post it here.  I've updated, rebooted, tried safemode and everything else I can find.

**Comment by DanVrt** [comment]
I have the same problem and I don't have AVG installed.
Yesterday everything was fine

**Comment by DWG1234** [comment]
Same with me, everything was fine until about 3 hours ago.  Using Outlook 2019.

**Comment by osensnolf** [comment]
This is the experience I am having.  I assume others are having the same? https://youtu.be/tdo4G_Hrpt8

**Comment by osensnolf** [comment]
UPDATE: Many have reported that this solution takes care of it.  I am running the update now. https://stackoverflow.com/questions/67493919/microsoft-outlook-2019-and-2016-reading-pane-blank/67494438#67494438

**Comment by DanVrt** [comment]
Apparently it has been resolved spontaneously, do not perform any process, however, the solution accepted by most is in the next link.

 vasif75:
https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1358

**Comment by nam31** [comment]
@BROnstott Thank you for your feedback. The issue was caused by an update and was fixed later in the same day. Please see #1358
Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
