### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by Vylda** [MicrosoftDocs/OfficeDocs-Support#1356]
I have no AVG

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6235ea9-d8df-c7c8-5540-402bbf2bf459
* Version Independent ID: 887b3e23-dd0b-caa8-0a20-3f754fc9bb86
* Content: [Email message body is blank in Outlook - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/message-body/email-message-body-is-blank-in-outlook)
* Content Source: [Outlook/Client/message-body/email-message-body-is-blank-in-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/email-message-body-is-blank-in-outlook.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by Vylda** [comment]
![obrazek](https://user-images.githubusercontent.com/47244408/117885419-23d2c000-b2ae-11eb-9cbd-d94e6dcf8437.png)
Copy pasted text to e-mail
![obrazek](https://user-images.githubusercontent.com/47244408/117885540-41078e80-b2ae-11eb-9e47-32c001d51bfa.png)
message in browser
![obrazek](https://user-images.githubusercontent.com/47244408/117885766-875ced80-b2ae-11eb-9dd7-2e68be7532eb.png)
recieved message in Outlook

**Comment by Vylda** [comment]
outlook v 2104

**Comment by Vylda** [comment]
> 
> 
> the problem is when giving enter maybe it is a problem with some update that was released today

Yes, you right.
roll back to latest working version:
```
C:\Program Files\Common Files\microsoft shared\ClickToRun\OfficeC2RClient.exe" /update user updatetoversion=16.0.13901.20462
```

**Comment by Vylda** [comment]
> 
> 
> How can I go back to the last stable version?
Latest working (rollback):
`Win + R` then run command
```
"C:\Program Files\Common Files\microsoft shared\ClickToRun\OfficeC2RClient.exe" /update user updatetoversion=16.0.13901.20462
```

**Comment by vasif75** [comment]
here is the fix in this thread.
https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1358

**Comment by nam31** [comment]
@Vylda Thank you for your feedback. The issue was caused by an update and was fixed later in the same day. Please see #1358
Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
