### ISSUE TITLE
AVGOutlook 

### ISSUE THREAD

**Issue by Ashton01Prestonmag** [MicrosoftDocs/OfficeDocs-Support#1359]
Page is no use whatsoever. I do not have AVGOutlook.addin installed. 

I still have emails which do not display the email body however

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6235ea9-d8df-c7c8-5540-402bbf2bf459
* Version Independent ID: 887b3e23-dd0b-caa8-0a20-3f754fc9bb86
* Content: [Email message body is blank in Outlook - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/message-body/email-message-body-is-blank-in-outlook)
* Content Source: [Outlook/Client/message-body/email-message-body-is-blank-in-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/email-message-body-is-blank-in-outlook.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by nam31** [comment]
@Ashton01Prestonmag Thank you for your feedback. The issue was caused by an update and was fixed later in the same day. Please see #1358
Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
