### ISSUE TITLE
Stesso problema (Outlook 2016) ma non c'è AVG installato

### ISSUE THREAD

**Issue by FrancescoRizzone** [MicrosoftDocs/OfficeDocs-Support#1360]
Premetto che utilizzo per lavoro Outlook e da ieri 11 Maggio 2021 sono impossibilitato ad utilizzare questo fondamentale strumento. Qualsiasi email apra, il corpo del messaggio è vuoto non si legge più il contenuto (anche email di testo semplice e non html), sia nel corpo del messaggio che nell'anteprima.

Non utilizzo AVG ma ho fatto comunque una verifica sul regedit se vi fosse un Addin simile (allo stesso percorso) ma nulla. Come antivirus è installato Avira Free Antivirus. Utilizzo Windows 10 Pro Versione 2004 Build sistema operativo 19041.928, Windows Feature Experience Pack 120.2212.551.0 ed Outlook 2016 (parte del pacchetto Office Professional Plus 2016).

Riesco a leggere vostre eventuali risposte soltanto dallo smarthphone. Grazie per un aiuto tempestivo (che potrebbe riguardare anche altri utenti).

[Immetti qui i commenti]

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: d6235ea9-d8df-c7c8-5540-402bbf2bf459
* Version Independent ID: 887b3e23-dd0b-caa8-0a20-3f754fc9bb86
* Content: [Il corpo del messaggio di posta elettronica è vuoto in Outlook - Outlook](https://docs.microsoft.com/it-it/outlook/troubleshoot/message-body/email-message-body-is-blank-in-outlook)
* Content Source: [Outlook/Client/message-body/email-message-body-is-blank-in-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/email-message-body-is-blank-in-outlook.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by vasif75** [comment]
Hi, sorry I do not speak your language, but I think you have blank email body.
here is the fix:
go to command prompt and run it as administrator

cd  C:\Program files\Common Files\Microsoft shared\Clicktorun

then type this
OfficeC2RClient.exe /update user updatetoversion=16.0.13901.20462

**Comment by FrancescoRizzone** [comment]
Thank you so much vasif75, the suggested update worked! Now I see the body of the emails.
I thought Office did automatic updates ... anyway the issue is now fixed!
Thanks again

**Comment by nam31** [comment]
@FrancescoRizzone Thank you for your feedback. The issue was caused by an update and was fixed later in the same day. Please see #1358
Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
