### ISSUE TITLE
Spell mistake

### ISSUE THREAD

**Issue by venreddy77** [MicrosoftDocs/OfficeDocs-Support#1365]
We have a word spell mistake here, if you could update that would be great. 

Resolution
To view unified DLP policy tips, use one of the following options in Exchange Online:

Disable all Transport rules that include the Notify the sender with a Policy Ti action.
Remove the action Notify the sender with a **Policy Ti**  from all Transport rules.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9add86ae-f5b1-8009-8ee1-0216a9982c90
* Version Independent ID: 26183475-5f53-c6c9-2baf-270c683c9361
* Content: [Office 365 DLP policy tips are not showing in Outlook or OWA - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/data-loss-prevention/dlp-tips-not-work)
* Content Source: [Microsoft365/compliance/data-loss-prevention/dlp-tips-not-work.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/compliance/data-loss-prevention/dlp-tips-not-work.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by nam31** [comment]
Closing via #1394 
Thank you
