### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by bbhulsey** [MicrosoftDocs/OfficeDocs-Support#137]
Why are there links to Microsoft Access 2013 Runtime and Microsoft Access Database Engine 2010 Redistributable here?  In what situations if any would these be better choices than the Microsoft Access Database Engine 2016 which should be backwards compatible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdf4f7db-9b53-0da7-41ab-17a57c6a1481
* Version Independent ID: 6d01c403-6542-083b-5087-a8d8fb4d33b5
* Content: [Can't use the Access ODBC driver or OLEDB provider outside Office Click-to-Run - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/cannot-use-odbc-or-oledb#feedback)
* Content Source: [Office/Client/access/cannot-use-odbc-or-oledb.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/cannot-use-odbc-or-oledb.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
You cannot install mixed install methods (click to run and msi) of the same version of Office on the same machine. It is not supported. This is why we have those other products listed in this article.

All of the following products are MSI versions:

Microsoft Access 2013 Runtime 
Microsoft Access Database Engine 2010 Redistributable
Microsoft Access Database Engine 2016 Redistributable

If customer has O365 installed (click to run), they cannot install 2016 MSI products on the same machine (in this case the Microsoft Access Database Engine 2016 Redistributable) . They would need to install either of the MSI products listed in the article: Microsoft Access 2013 Runtime Or Microsoft Access Database Engine 2010 Redistributable.
