### ISSUE TITLE
Typo in source code

### ISSUE THREAD

**Issue by sravenscroft** [MicrosoftDocs/OfficeDocs-Support#138]
Currently:
$SessionExO = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $Cred -Authentication Basic - AllowRedirection

There is a space between "-" and "AllowRedirection"

Should be:
$SessionExO = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $Cred -Authentication Basic -AllowRedirection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1f49302-8af5-dc40-ff24-4d62bc126745
* Version Independent ID: f03ff26f-aca3-6313-f39d-94acca49f150
* Content: [Troubleshoot directory synchronization errors with event 6941 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/duplicate-attributes-prevent-dirsync#feedback)
* Content Source: [Microsoft365/admin/administration/duplicate-attributes-prevent-dirsync.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/duplicate-attributes-prevent-dirsync.md)
* Service: **o365-administration**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
It is fixed. Thanks.
