### ISSUE TITLE
Public group calendar missing in navigation pane

### ISSUE THREAD

**Issue by mortentanggaardnielsen** [MicrosoftDocs/OfficeDocs-Support#1385]
I can't add to Favorites since the calendar does not become visible in navigation pane. It only shows in the main window on MS Outlook 365 MSO (16.0.13929.20222) 64-bit 

![Capture](https://user-images.githubusercontent.com/6685863/118262914-da54c180-b4b5-11eb-9667-36474b34c27d.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d4c5396-5562-5f30-a7b6-c2fc045e553f
* Version Independent ID: 7efbc0ce-55fc-3e06-24df-a8f7a1f47afc
* Content: [All members' free/busy data of a group is displayed - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/outlook-issues/group-calendar-shows-all-user-free-busy-info)
* Content Source: [Exchange/ExchangeOnline/outlook-issues/group-calendar-shows-all-user-free-busy-info.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/outlook-issues/group-calendar-shows-all-user-free-busy-info.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @Norman-sun
* Microsoft Alias: **v-swei**

**Comment by msbemba** [comment]
@mortentanggaardnielsen Thank you for your feedback. Are you referring to Favorites on the Main tab or the calendar? There is no Favorites option in the calendar. The group calendar that you are part of should show up in All group calendars.

Hope this helps!
Thanks
Sri

**Comment by nam31** [comment]
@mortentanggaardnielsen Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
