### ISSUE TITLE
„Microsoft Teams is stuck in a login loop in Edge, Internet Explorer or Google Chrome” - I get the error on Firefox, but it's not mentioned.

### ISSUE THREAD

**Issue by RobertCezaryKujawa-TomTom** [MicrosoftDocs/OfficeDocs-Support#1386]
I get the error on Firefox, however it's not mentioned on the website.
Could you help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c17faf2-0e38-0a98-454c-3c2c4387b37f
* Version Independent ID: d9153b98-dc39-fdd1-a798-07da0caaaa64
* Content: [Microsoft Teams is stuck in a login loop in Edge, Internet Explorer or Google Chrome - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#resolution)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@RobertCezaryKujawa-TomTom Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1614

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1614 
Thank you
