### ISSUE TITLE
Script download link 404 error : enable-remotearchive.ps1 and disable-remotearchive.ps1

### ISSUE THREAD

**Issue by Shuyzhou666** [MicrosoftDocs/OfficeDocs-Support#1392]
[Enter feedback here]
Script download link 404 error : enable-remotearchive.ps1 and disable-remotearchive.ps1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a449846-e325-24ba-ea5e-48d6f9c49b22
* Version Independent ID: 200173f7-9779-bd93-2272-4494da6f642d
* Content: [Archive mailbox can't be provisioned or deprovisioned after a mailbox is migrated to Office 365 Dedicated/ITAR vNext - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/archive-mailboxes/cannot-provision-deprovision)
* Content Source: [Microsoft365/compliance/archive-mailboxes/cannot-provision-deprovision.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/compliance/archive-mailboxes/cannot-provision-deprovision.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by obadiola** [comment]
I need this files too.
I need activate archive in Shared MailBox with hybrid configuration and without old Exchange.

**Comment by sowjanya365** [comment]
Hi @Shuyzhou666 

This is strange. We verified, and it's working on our end. Could you please try again and let us know if the issue still persists. And also please let us know the browser that you are using. Thank you!

**Comment by sowjanya365** [comment]
Hi @Shuyzhou666 

Please let us know if you still have any question regarding the issue you have raised initially.
Thanks.

**Comment by Shuyzhou666** [comment]
Hello

Problem resolved , Thanks a lot !




Best regards,
Shuyin Zhou

**Comment by nam31** [comment]
@Shuyzhou666 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
