### ISSUE TITLE
Unhelpful help

### ISSUE THREAD

**Issue by HelmZalee** [MicrosoftDocs/OfficeDocs-Support#1397]
Poor phrasing; remove the full stop after "...with the object", and make this one sentence:
This problem occurs if you are using a Wrapping style option other than the In line with text option with the picture or with the object. And, one of the following conditions is true:

Beyond that, the "wrapping style" is already "in line with text", so I'm left to guess which of the other problems may be manifested.  Is it not possible for the error message to provide a hint?

And beyond _that_, as an Office 365 subscriber, I'm left to guess which of the various options applies.  Apparently some renaming is going on: "Office 365 ProPlus is being renamed...", but neither "Office 365..." nor "Microsoft 365..." appears in the remainder of the page, so to what does it refer, and which alternative (Word 10? None?) actually applies in this case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46468fe2-ff0d-44ae-de1d-f7b411df3d36
* Version Independent ID: b63823d9-b8f7-ca2f-197f-16d1efe8372e
* Content: [A picture or an object may not appear in a Word 2010 or Word 2007 document - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/object-not-appear-in-word-2010)
* Content Source: [Office/Client/word/object-not-appear-in-word-2010.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/object-not-appear-in-word-2010.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by sowjanya365** [comment]
Hi @HelmZalee 

Thank you for reaching out and let us know your views!

We appreciate your time, but we didn't find any phrasing issue with this sentence. It looks good! 

"This problem occurs if you are using a Wrapping style option other than the In line with text option with the picture or with the object. And, one of the following conditions is true:"

And, with reference to your Office 365/Microsoft 365 note, we have added it as a knowledge reference to all the articles present in the repository. 

Hope this helps! Thank you!

**Comment by HelmZalee** [comment]
This is clearer to me.  It has fewer words and says the same thing.
“The problem occurs if you’re using a wrapping style option other than _In line with Text_ and one of the following conditions is true:"

In the original, "...the In Line with text option" is clear only after some consideration.  Italicizing the option name helps.

"with the picture or with the object" adds a new word, "object".  "Object" serves only to confuse.  The word is undefined in this context; it does not appear in the Insert menu.  Including one specific object (picture) while omitting all the others only makes the user wonder if it applies to, for example, Icon.  Using only "object" is potentially confusing because it is unmentioned in the menu.  Just leave them all out; its clear we're talking about whatever is being wrapped.

**Comment by sowjanya365** [comment]
Thank you for your contribution @HelmZalee!

**Comment by sowjanya365** [comment]
Hi @HelmZalee 

In the following sentence "Picture & Object" refer to the relative positioning. So, we do not see any need for modifying the sentence at the moment. But, we highly appreciate your support and contribution. Thank you so much!

**Comment by nam31** [comment]
@HelmZalee Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
