### ISSUE TITLE
Should be renamed - chock-ful-o-errors-and-typos

### ISSUE THREAD

**Issue by soupman98** [MicrosoftDocs/OfficeDocs-Support#14]
This document is chock full of errors... 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b5852d3-9d75-1c0a-792f-783b4c10d9dc
* Version Independent ID: 09bfccc0-29fe-68a4-d172-3db14c38a30f
* Content: [Count The Number of Cells With Specific Cell Color By Using VBA - Troubleshooting | Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-developer/count-cells-number-with-color-using-vba)
* Content Source: [Office/Client/office-developer/count-cells-number-with-color-using-vba.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-developer/count-cells-number-with-color-using-vba.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Sending this article to editing.

**Comment by todmccoy** [comment]
Content Idea Request 103330 created to address this issue.

**Comment by jlriesco** [comment]
Thank you Tod,
Jose

**Comment by jlriesco** [comment]
Edited. Closing the case.
