### ISSUE TITLE
Need exclusions for Mac client as well

### ISSUE THREAD

**Issue by schumatt-msft** [MicrosoftDocs/OfficeDocs-Support#1401]
This page contains great information for the Teams client on Windows, but we need the same details for the client on Mac. Can you please update with the necessary paths to exclude from scanning for MacOS as well? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23989acb-65f2-d269-66c8-edcdd89c730d
* Version Independent ID: ef65785d-165f-6c91-1e9d-c4e99122c13f
* Content: [How to include or exclude Teams from antivirus or DLP applications - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-administration/include-exclude-teams-from-antivirus-dlp)
* Content Source: [Teams/teams-administration/include-exclude-teams-from-antivirus-dlp.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-administration/include-exclude-teams-from-antivirus-dlp.md)
* Service: **msteams**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by schumatt-msft** [comment]
@nam31 Checking in to see if you have any more info here to share. Thanks!

**Comment by dariomws** [comment]
Hi @schumatt-msft, thank you for your feedback.

I am working on this issue and will provide you with an update in a few days.

**Comment by schumatt-msft** [comment]
> I am working on this issue and will provide you with an update in a few days.

Hi @dariomws - Any updates here? Thanks!

**Comment by dariomws** [comment]
Hi @schumatt-msft, I don't have this information and had to contact another team to get it. I'll let you know immediately once I get it.

Thank you!

**Comment by schumatt-msft** [comment]
> Hi @schumatt-msft, I don't have this information and had to contact another team to get it. I'll let you know immediately once I get it.
> 
> Thank you!

@dariomws Any updates?

**Comment by dariomws** [comment]
Hi @schumatt-msft, my apologies, but I still don't have updates.

Do you think you can try to push this information from your side? Thanks!

**Comment by dariomws** [comment]
Hi @schumatt-msft, 

Do you think you can try to push this information from your side? Thanks!

**Comment by tiburd** [comment]
@schumatt-msft
Hi,

Our team no longer supports this repo, so I'm closing this issue.

cc: @dariomws
