### ISSUE TITLE
The script to change the registry setrings is not in Powershell, but in legacay prompt (cmd.exe)

### ISSUE THREAD

**Issue by JuGhithub** [MicrosoftDocs/OfficeDocs-Support#141]
Please provide a script in PowerShell or change the type of script in this page

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 95d45540-ec98-57d5-7ef3-0190c64d164e
* Version Independent ID: 1b33de41-c3b6-35bc-840f-085007fc3b71
* Content: [Procédure de basculement du canal semi-annuel au canal mensuel pour Office 365](https://docs.microsoft.com/fr-fr/office365/troubleshoot/administration/switch-channel-for-office-365#feedback)
* Content Source: [Microsoft365/admin/administration/switch-channel-for-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/switch-channel-for-office-365.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@JuGhithub Which script are you referring to? The [page you linked](https://docs.microsoft.com/en-us/deployoffice/change-update-channels) does not contain a script. It talks about the two ways of doing this, either using a group policy or via the Office Deployment Tool.

**Comment by JuGhithub** [comment]
I'm sorry, i had provide a bad link
you can close the issue
