### ISSUE TITLE
Exchange server

### ISSUE THREAD

**Issue by stefanojj** [MicrosoftDocs/OfficeDocs-Support#1419]
After long time searching for a solution the one that worked for me was to completely deleting the CN=discovery folder from your domain controller in ADSI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7e2de27-485e-1265-06b3-08d12e2883f1
* Version Independent ID: 4cd64135-d888-72e3-44a4-fe5aca3c2c2d
* Content: [Installation of Edge Transport role fails - Exchange](https://docs.microsoft.com/en-US/exchange/troubleshoot/setup/process-execution-failed-with-exit-code-3)
* Content Source: [Exchange/ExchangeServer/setup/process-execution-failed-with-exit-code-3.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/setup/process-execution-failed-with-exit-code-3.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @Norman-sun
* Microsoft Alias: **v-swei**

**Comment by MaratMussabekov** [comment]
Hello @stefanojj ,
can you please provide more details?
did you get the same error as described in the article?
**was to completely deleting the CN=discovery folder from your domain controller in ADSI** - in DMZ domain?
Thank you

**Comment by MaratMussabekov** [comment]
Hello @stefanojj ,
did you have time to check the error? is it the same as in the article?
Thank you

**Comment by stefanojj** [comment]
hi @MaratMussabekov i ended up doing a brand new exchange server install

**Comment by MaratMussabekov** [comment]
hello @stefanojj , so it is not within the scope of the article I assume? wouldn't you mind if @nam31 close this issue?
Thank you

**Comment by stefanojj** [comment]
No I do not mind

Thanks,

Stefano Jean Joseph
CEO/CTO
JeanComputech Corporation
Main: (888) 585 5326
Direct:(617) 294-9797
Cell:  (857) 869 2283
Skype id: stefano.jean.joseph
***@***.******@***.***>
www.jeancomputech.com<http://www.jeancomputech.com/>

***@***.***D76765.90E4A3A0]
