### ISSUE TITLE
C2R Product Id for Office Professional Plus 2019 (MAPS core)?

### ISSUE THREAD

**Issue by sherpya** [MicrosoftDocs/OfficeDocs-Support#142]
I have a maps subscription, on premise download provides an iso for Italian version of Office Professional Plus 2019.
As the iso filename suggests `SW_DVD5_Office_Professional_Plus_2019_32_BIT_X64_Italian_C2R_X21-84636.ISO` I suppose I can customize it using c2r deploy tool.

Unfortunately I've not found a suitable product id, as far I known maps on premise office are retail multilicenses but not volume (Volume products ids are not working in fact).

I've tried with `ProPlusRetail` `ProPlus2019Retail` without success.
The only way to make it work is install using provided iso (so all products), activate then reinstall using the deploy tool (but I'm not even sure that it works always).

By looking a the iso can I extract the product id(s) the C2R installer (there are 4 different setups) picks by defaults?
Thanks

**Comment by sherpya** [comment]
by looking at an installed version looks like the product id the iso install is `ProPlusRetail`, latest updated version `16.0.12026.20264`, but I've tested downloading it from scratch and it says "This key if for Office Professional Plus 2019" (that indeed is)

**Comment by sherpya** [comment]
update: `ProPlus2019Retail` worked (hope not because of multipe installs), but please add the info to the documentation

**Comment by nam31** [comment]
@sherpya The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@sherpya We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
