### ISSUE TITLE
Seems to have done the trick!

### ISSUE THREAD

**Issue by calmaniac** [MicrosoftDocs/OfficeDocs-Support#143]
I used Reindex Spotlight for Outlook for Mac for my 2019 MacBook Air running Mojave with Office 365 and the Outlook email searches are now working. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a55b51-85d6-f628-581c-5a1c66675933
* Version Independent ID: 9f626f3a-123d-67ca-3aa8-a3443963fe05
* Content: [Outlook for Mac support tools. - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/outlook-for-mac/useful-tools#feedback)
* Content Source: [Outlook/OutlookExperts/outlook-for-mac/useful-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/OutlookExperts/outlook-for-mac/useful-tools.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Cloud-Writer** [comment]
Glad to know your issue is resolved.

**Comment by jasermd** [comment]
Can you explain to me in detail how you did this reindexing? Thanks, JAS

**Comment by calmaniac** [comment]
I apologize, I don't recall the details. Here are the Microsoft info pages I used to figure it out. Hope that helps. 
•  https://docs.microsoft.com/en-us/outlook/troubleshoot/outlook-for-mac/useful-tools
•  https://support.microsoft.com/en-us/help/2741535/outlook-for-mac-search-returns-no-results-and-task-items-are-not-displ
