### ISSUE TITLE
Method 2 doesn't work

### ISSUE THREAD

**Issue by mikenri** [MicrosoftDocs/OfficeDocs-Support#1432]
Method 2 seems to not work. 
Get-CsOnlineSipDomain shows the impacted domain status is disabled, but Grant-CSTeamsUpgradePolicy still throws the error. 

Support Case #25742549 has some artifacts showing this. 

It seems it would be better to have a -force switch added to the Grant-CSteamsUpgradePolicy to get around this. 
The "sanity check" process for lyncdiscover.domain.com seems flawed.
The cmdlet only validates if DNS is pointed at Skype For Business online. 
It doesn't try to connect to the FQDN to confirm if it's actually an on-premises Skype server. 
It's problematic for domains that use wildcard DNS. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 397653ec-e60a-ee24-8794-97ef38d611af
* Version Independent ID: 00cbbdff-7b3a-f466-b165-239082bb3d9e
* Content: [Unable to switch a tenant to Teams Only mode - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-administration/cannot-switch-to-teams-only-mode)
* Content Source: [Teams/teams-administration/cannot-switch-to-teams-only-mode.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-administration/cannot-switch-to-teams-only-mode.md)
* Service: **msteams**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by dariomws** [comment]
Hi @mikenri, thank you for your feedback.

If method 2 doesn't work for you, I think you can try method 1. I understand that the -Force switch must be used only as a last resort.

@MaryQiu1987 maybe you can add something here. Thanks!

**Comment by mikenri** [comment]
In our case, we had a domain that we no longer owned in our tenant, DNS was no longer under our control. 
Whoever bought the domain set up a wildcard DNS entry for the root of the domain, so even though the lyncdiscover DNS record didn't really exist, it was resolving due to the wildcard DNS entry.

We did clean up any objects that were associated with the problematic domain and removing it from our tenant in order to proceed. 

It seems a DNS check alone isn't really a valid way to determine if a domain is using on-premises Skype in this scenario.

**Comment by dariomws** [comment]
Hi @mikenri,

If you removed the domain from your tenant, it's not listed when you run Get-CsOnlineSipDomain, and you still have the same error, I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.
