### ISSUE TITLE
 Outlook Search Repair tool not supported

### ISSUE THREAD

**Issue by jkeponen** [MicrosoftDocs/OfficeDocs-Support#1433]
Outlook Search Repair Utility throws "The Outlook Search Repair tool is not supported on this version of macOS. Please see the following article for more information." And then link back to this page https://docs.microsoft.com/en-us/outlook/troubleshoot/outlook-for-mac/useful-tools But there are now information regarding that error. My Outlook search is broken, my macOS is Big Sur 11.1, Outlook 16.49 (21050901)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a55b51-85d6-f628-581c-5a1c66675933
* Version Independent ID: 9f626f3a-123d-67ca-3aa8-a3443963fe05
* Content: [Outlook for Mac support tools. - Outlook](https://docs.microsoft.com/en-US/outlook/troubleshoot/outlook-for-mac/useful-tools)
* Content Source: [Outlook/OutlookExperts/outlook-for-mac/useful-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/OutlookExperts/outlook-for-mac/useful-tools.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@jkeponen Thank you for your feedback. 

This tool no longer works in 10.14 and higher. If you are on macOS Big Sur 11.1,, you can follow the steps below to reindex Spotlight for Outlook for Mac.  This has been added to the important section of the document

Choose Apple menu, then System Preferences, and then Spotlight.

Select the Privacy tab.

In Finder:

On the Go menu, select Go to Folder...

Copy and paste the following location into the "Go to the folder:" dialog box and select Go:

~/Library/Group Containers/UBF8T346G9.Office/Outlook/Outlook 15 Profiles/

Drag the "Main Profile" folder to the Privacy tab. Once added, remove the folder from the Privacy tab, and Spotlight will re-index the folder.

You must perform this step for any additional profile folders you have.

Hope this helps!
Thanks
Sri

**Comment by leslieligori** [comment]
Sri - did exactly as suggested above (3 times) and still not searching.  I'm using BigSur 11.2.3.        Any other suggestions as this has caused a huge interruption in daily operations.

**Comment by msbemba** [comment]
@leslieligori The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).

Thanks
Sri
