### ISSUE TITLE
The Note under Method 2 should only appear for Step 2

### ISSUE THREAD

**Issue by VShrubowich** [MicrosoftDocs/OfficeDocs-Support#1434]
Under [Method 2](https://docs.microsoft.com/en-us/office/troubleshoot/word/damaged-documents-in-word#method-2-insert-the-document-as-a-file-in-a-new-document), the Note that says 

> You might have to reapply some formatting to the last section of the new document.

 appears under both Step 1 and Step 2.  It should appear only under Step 2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b95df2f-e3de-e2d1-b48a-3fcd4183463f
* Version Independent ID: 397150eb-b8e0-62c0-55b9-c5277aacb5dd
* Content: [How to troubleshoot damaged documents in Word - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/damaged-documents-in-word)
* Content Source: [Office/Client/word/damaged-documents-in-word.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/damaged-documents-in-word.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by RAJU2529** [comment]
@VShrubowich Thanks for pointing out

**Comment by nam31** [comment]
Closing via #1445 
Thank you
