### ISSUE TITLE
How about Outlook v16?

### ISSUE THREAD

**Issue by Gitchiel** [MicrosoftDocs/OfficeDocs-Support#1435]
Hello,

what would the registry key be for Outlook v16? I'd prefer to know, instead of simply testing, since it's configured on a Citrix environment and I'd have to send the input to a colleague, who takes care of this, etc.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f23df0e5-abb2-4d2b-75eb-e70a542a4f7a
* Version Independent ID: 9b10bdfe-b18f-9c24-d395-a3acfa6d0486
* Content: [No buttons to sign or encrypt emails - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/security/no-buttons-to-sign-or-encrypt-emails)
* Content Source: [Outlook/Client/security/no-buttons-to-sign-or-encrypt-emails.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/security/no-buttons-to-sign-or-encrypt-emails.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@Gitchiel Thank you for your feedback. This document applies to outlook 2007 and 2010, that is why you don't see the registry information for Office 15 or 16.

If you are using outlook version 16, the registry key would be HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Outlook\Preferences

Hope this helps!
Thanks
Sri

**Comment by nam31** [comment]
@Gitchiel Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Comment by Gitchiel** [comment]
Many thanks! Can be / remain closed :-)

Best
Michiel
