### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by JamesEdmonds89** [MicrosoftDocs/OfficeDocs-Support#144]
I don't understand why this behaviour occurs?
If the workaround is to basically create a new group that replicates what the default group does, what is the point of carrying out this action on the default group?

You will still end up in the exact same place with the exact same permissions, just with one extra group to worry about.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a93f5a-6e89-4811-9c34-41932077e4eb
* Version Independent ID: 7598878f-e9b4-2fc7-f20a-37438e010dc1
* Content: [Everyone except external users group is removed on Office 365 - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/sharing-and-permissions/everyone-except-external-user-removed#feedback)
* Content Source: [SharePoint/SharePointOnline/sharing-and-permissions/everyone-except-external-user-removed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sharing-and-permissions/everyone-except-external-user-removed.md)
* Service: **sharepoint-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by claudialake** [comment]
The article has been updated to clarify.
