### ISSUE TITLE
ASCII link is broken

### ISSUE THREAD

**Issue by pa12ag** [MicrosoftDocs/OfficeDocs-Support#1444]
[Enter feedback here]
The ASCII link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae3f9ec8-5424-172f-ff80-27baf054bfac
* Version Independent ID: 78efae5e-8b94-2a50-dc65-f559f7a903d6
* Content: [IMCEAEX non-delivery report when you send email messages to an internal user - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/email-delivery/imceaex-ndr)
* Content Source: [Exchange/ExchangeOnline/email-delivery/imceaex-ndr.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/email-delivery/imceaex-ndr.md)
* Service: **exchange-online**
* GitHub Login: @Norman-sun
* Microsoft Alias: **v-swei**

**Comment by RAJU2529** [comment]
@pa12ag . Thanks for pointing out. This issue is confirmed from my side.

**Comment by RAJU2529** [comment]
@e0i , i found correct link from intel official website

**Comment by RAJU2529** [comment]
@nam31. please close this issue

**Comment by nam31** [comment]
Closing via #1448
Thank you
