### ISSUE TITLE
This article should clarify in step 3 this needs to be 9.0 for all versions of office

### ISSUE THREAD

**Issue by pizzaazzip** [MicrosoftDocs/OfficeDocs-Support#1449]
Regardless of the fact the top says it applies to many versions of Office from 2007 to 365/2019 this looks like a typo or someone forgetting to update the article from an older version of Office.  It would be best to clarify in step 3 by adding some sort of wording like _Note:  This is not the current version of Office installed (e.g. 15.0 or 16.0), it does need to be 9.0 for this to apply correctly_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6621f77-f212-d653-6a1f-b53377122299
* Version Independent ID: 00180269-ac22-7154-fe4a-38b9f0a4ecbf
* Content: [Cannot locate the Internet or proxy server when selecting hyperlink in Office - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/cannot-locate-server-when-click-hyperlink)
* Content Source: [Office/Client/office-suite-issues/cannot-locate-server-when-click-hyperlink.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/cannot-locate-server-when-click-hyperlink.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by RAJU2529** [comment]
@pizzaazzip . thanks for pointing it out. I am going to fixing now.

**Comment by RAJU2529** [comment]
@nam31 . I created this PR#1454 carefully by gettings sufficient details and then i edited this article.

**Comment by RAJU2529** [comment]
this issue has been resolved so I am closing issue.

**Comment by RAJU2529** [comment]
I don't have option to this issue

**Comment by pizzaazzip** [comment]
> this issue has been resolved so I am closing issue.

I'm sorry, I might not have been super clear in my earlier note, the original article was actually correct, it just _looked_ wrong with it saying 9.0 and it actually won't work with how you've edited it.  I was suggesting it might be an idea to clarify **yo dawg, 9.0 isn't a typo, don't put 16.0 or 15.0 or 12.0 because it needs to be 9.0 there, it won't work any other way**.  Hopefully that makes sense, sorry for the confusion.

**Comment by helenclu** [comment]
Corrected.

**Comment by pizzaazzip** [comment]
> Corrected.

Awesome!  That should work well!
