### ISSUE TITLE
How we can reset office365 activation for Mac OSx ?

### ISSUE THREAD

**Issue by ferhotguy** [MicrosoftDocs/OfficeDocs-Support#145]
How we can reset office365 activation for Mac OSx ?

**Comment by nam31** [comment]
@ferhotguy The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@ferhotguy We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
