### ISSUE TITLE
Additional Solution - tested, repeatable and proven

### ISSUE THREAD

**Issue by JamesCarlyleClarke** [MicrosoftDocs/OfficeDocs-Support#1450]
Another solution - should be tried after all settings have been checked, but before updating the Video Driver:

Find the images that are not printing; select them (one, or several at a time), and copy them and paste them in to an empty Word document; and then select them in the new document, and copy and paste them back in to the original document, either overwriting or manually deleting the original ones.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46468fe2-ff0d-44ae-de1d-f7b411df3d36
* Version Independent ID: b63823d9-b8f7-ca2f-197f-16d1efe8372e
* Content: [A picture or an object may not appear in a Word 2010 or Word 2007 document - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/object-not-appear-in-word-2010#)
* Content Source: [Office/Client/word/object-not-appear-in-word-2010.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/object-not-appear-in-word-2010.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@JamesCarlyleClarke Thank you for your feedback. The option to copy and paste would be a temporary workaround and don't think that can be added as a workaround. I will check with the author and update you.

CC: @helenclu 

Thanks
Sri

**Comment by JamesCarlyleClarke** [comment]
Dear Sri,

Yes it would most definitely be a temporary workaround - but it is one that
works. Unlike the other solutions. Unlike Microsoft Office support
technicians.
If you do not formalise it on this document then there will continue to be
lost documents, bad advice, bad solutions, and upset with Office and MS.

All the best,

James

**Comment by msbemba** [comment]
@JamesCarlyleClarke I have added the steps to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1571

The author will review this first and once this is approved the document will be updated.

Thanks
Sri

**Comment by JamesCarlyleClarke** [comment]
Dear Sri,
That's great news, thanks.

James

**Comment by nam31** [comment]
Closing via #1571 
Thank you
