### ISSUE TITLE
Explain how to save individual objects as high resolution

### ISSUE THREAD

**Issue by creidieki** [MicrosoftDocs/OfficeDocs-Support#1456]
This is great for exporting whole slides, but it doesn't seem to change the resolution of the "save as picture" function. It's still blurry when I save as as a picture and then import into Word. This document should also explain how to save individual powerpoint objects/drawings as high resolution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e390c4c9-9cdf-beb1-43dc-6ec45ae5fe77
* Version Independent ID: bb31c9ea-7186-22fb-195f-f481eb5137e4
* Content: [How to export high-resolution (high-dpi) slides from PowerPoint - Office](https://docs.microsoft.com/en-us/office/troubleshoot/powerpoint/change-export-slide-resolution)
* Content Source: [Office/Client/powerpoint/change-export-slide-resolution.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/powerpoint/change-export-slide-resolution.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by RAJU2529** [comment]
@creidieki . Just now i inserted high-end wallpaper with dimension 10929x5553 and another size 1920x1080   in single PowerPoint file as two slides.
also, i added 1092 dpi in the Registry key., then i exported PowerPoint file  .jpg format.
Both inserted wallpapers are exported separately in single folder.
so i conformed article is correct 
, when exporting image you may get below warning 
![Capture](https://user-images.githubusercontent.com/3296790/119505841-fcd6bc80-bd8a-11eb-8791-e327acc3164a.JPG)

click on **all slides**

**Comment by creidieki** [comment]
The article is correct, it's just incomplete. If you right-click on an individual object on the slide, and click "save as picture", then it's still exported as low resolution, ignoring your registry settings.

**Comment by RAJU2529** [comment]
@creidieki . i exported a single image and then verified , image resolution is not decreased, instead image resolution is  increased 

inserted image 
[Waterfalls_USA_10929x5553.zip](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/6539712/Waterfalls_USA_10929x5553.zip)

exported image
[single.zip](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/6539730/single.zip)

**Comment by nam31** [comment]
Closing via #1463 
Thank you
