### ISSUE TITLE
Workaround did not work for me

### ISSUE THREAD

**Issue by brickb** [MicrosoftDocs/OfficeDocs-Support#1458]
The workaround did not work for me.  I was able to successfully add an Internet calendar use the Outlook web app, but the calendar never appeared as a calendar in the  "Other Calendar" section of my Outlook desktop app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5d5258-e519-df39-0aa5-57115e0211ab
* Version Independent ID: 01390aa8-7cae-809b-b5e9-567514cc99d8
* Content: [Cannot add an Internet calendar - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/calendaring/cannot-add-an-internet-calendar)
* Content Source: [Outlook/Client/calendaring/cannot-add-an-internet-calendar.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/calendaring/cannot-add-an-internet-calendar.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@brickb Thank you for your feedback. I'm testing this currently and will update the document If need be.

Thanks
Sri
