### ISSUE TITLE
Alternative Solution

### ISSUE THREAD

**Issue by yatesa** [MicrosoftDocs/OfficeDocs-Support#1462]
There is actually an alternative solution to this.
You can use "Controlled Connections to Public Folders" to prevent the password prompts.
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-support-for-controlled-connections-to-public-folders/ba-p/608591

Before enabling at org level, first make sure you set all your user accounts to be allowed access to Public Folders, using the Set-CASMailbox “John" -PublicFolderClientAccess $true.
The set the shared mailboxes to not be allowed Public folder access, Set-CASMailbox “Accounts" -PublicFolderClientAccess $false.
And finally enable the controlled connection feature at org level, Set-OrganizationConfig -PublicFolderShowClientControl $true.

Give it a couple of hours for changes to propagate. Users with shared mailboxes will then no longer get constant password prompts as the shared mailbox will no longer be attempting to access the public folders.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f07a8040-1fca-5ace-d65d-130ea81dab33
* Version Independent ID: 5fed2b8c-ffb8-bf49-8cac-56be6b2f81f2
* Content: [Users prompted for credentials after adding a shared mailbox - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/user-and-shared-mailboxes/users-prompted-credentials-after-adding-shared-mailbox)
* Content Source: [Exchange/ExchangeHybrid/user-and-shared-mailboxes/users-prompted-credentials-after-adding-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/user-and-shared-mailboxes/users-prompted-credentials-after-adding-shared-mailbox.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @Norman-sun
* Microsoft Alias: **v-swei**

**Comment by msbemba** [comment]
@yatesa Thank you for your feedback. We have added the solution to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1507

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1507 
Thank you
