### ISSUE TITLE
Trust That Your Users Aren't Stupid

### ISSUE THREAD

**Issue by Dick95518** [MicrosoftDocs/OfficeDocs-Support#1467]
The reasoning for not allowing users to easily block domains is ridiculous. Could I inadvertently block a domain? Could happen, but I would accept that slim possibility to make Outlook more productive for me. 
Spam is a huge time suck - the fact that you make me jump through hoops to block a domain wastes even more of my time. Please fix this.
Thank you,
D. Johnson

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60595511-c869-95d3-4140-00b0626149a3
* Version Independent ID: 5e9f8265-b259-114b-532c-5b2ac5442625
* Content: [Cannot add sender's domain to Blocked Senders list - Outlook](https://docs.microsoft.com/en-US/outlook/troubleshoot/security/no-shortcut-menu-command-to-add-senders-domain-to-blocked)
* Content Source: [Outlook/Client/security/no-shortcut-menu-command-to-add-senders-domain-to-blocked.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/security/no-shortcut-menu-command-to-add-senders-domain-to-blocked.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@Dick95518 Thank you for your feedback. By design, there is no shortcut menu command to add a sender's domain to the Blocked Senders list in Outlook. I don't see it in the roadmap either, I'll check internally and confirm.

Thanks
Sri

**Comment by msbemba** [comment]
@Dick95518 Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).

Thanks
Sri
