### ISSUE TITLE
Error creating a profile of Exchange in Outlook (desktop)

### ISSUE THREAD

**Issue by SaedMartinez** [MicrosoftDocs/OfficeDocs-Support#1468]
Hi there, first of all, I´m learning english i understand slowly, well now i got a problem in the process of create a profile in the Outlook app (desktop) specificly when i try to sync or log in the server of my company with the account, (i make this mannually with the ("Control panel>outlook (mail)") i read mosething about the intermediate server with name autodiscover.xml that produce  this error, pleeeease help!,
 thanks

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 77d2afb6-f8d8-8423-42d4-185856a9b39d
* Version Independent ID: 2bad43bf-3690-fc3a-91aa-aab674cf2662
* Content: [Los buzones no se automapped to Outlook profile - Outlook](https://docs.microsoft.com/es-es/outlook/troubleshoot/profiles-and-accounts/full-access-mailbox-not-automapped-outlook-profile)
* Content Source: [Outlook/Client/profiles-and-accounts/full-access-mailbox-not-automapped-outlook-profile.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/profiles-and-accounts/full-access-mailbox-not-automapped-outlook-profile.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@SaedMartinez Thank you for your feedback. This document pertains to mailboxes that are not automatically mapped to an outlook profile when you have full access. Could you please elaborate on the error you receive, so we can point you to the correct document?

Thanks
Sri

**Comment by msbemba** [comment]
@SaedMartinez Thank you for your feedback. As mentioned earlier, this document pertains to mailboxes that are not automatically mapped and this does not cover the scenario or issue that you are facing currently. For instructions to create a  new profile you can visit - https://support.microsoft.com/en-us/office/create-an-outlook-profile-f544c1ba-3352-4b3b-be0b-8d42a540459d

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@SaedMartinez Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
