### ISSUE TITLE
this does not work it is not updated

### ISSUE THREAD

**Issue by jaaronanderson** [MicrosoftDocs/OfficeDocs-Support#147]
I do not have a gear beside members to click on step 5 it is an elipses i click to get to group settings ...

AND when I click save to update the instructed changes.. I get a subtle block error way at the bottom of the frame that states "This item might not exist or is no longer available. X " I never get group notices from the form owned by the group that there is new Responses to see ... this is so frustrating...  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 275b5403-3896-cf97-ee66-786dab0b4d61
* Version Independent ID: d51b179c-13f4-24c9-ae6b-e3f04b23e6c0
* Content: [No email notifications for responses to Group Forms - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/no-email-notifications-for-responses-to-group-forms#feedback)
* Content Source: [Microsoft365/enterprise/no-email-notifications-for-responses-to-group-forms.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/enterprise/no-email-notifications-for-responses-to-group-forms.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **zakirh**

**Comment by nam31** [comment]
@jaaronanderson , this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@jaaronanderson We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
