### ISSUE TITLE
references to Internet Explorer

### ISSUE THREAD

**Issue by catknabb** [MicrosoftDocs/OfficeDocs-Support#1470]
I would like to share this page, but it refers to Internet Explorer. I don't want to encourage people to make IE their default browser. Can this page be edited to point people to Edge?
Thanks, Cath

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 161bf8fc-061e-c244-26a9-d49f2144715f
* Version Independent ID: cf04aa21-cc6c-3c6a-f3ea-ffcf998eb168
* Content: [How to join a Teams meeting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/meetings/how-to-join-a-teams-meeting)
* Content Source: [Teams/meetings/how-to-join-a-teams-meeting.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/meetings/how-to-join-a-teams-meeting.md)
* Service: **msteams**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by dariomws** [comment]
Hi @catknabb, thank you for your feedback.

I am working on this issue and will provide you with an update in a few days.

**Comment by dariomws** [comment]
@catknabb, it's being updated here:
https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1537

Thank you again for your feedback.

**Comment by nam31** [comment]
Closing via #1537 
Thank you
