### ISSUE TITLE
KB missing information

### ISSUE THREAD

**Issue by lmoore101** [MicrosoftDocs/OfficeDocs-Support#1478]
A new prompt in Outlook is occurring, very similar to the one mentioned in this article and the setting in this article should also apply and hide the "IOS OR ANDROID? Take your Outlook on the go.  Download" prompt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 359383bf-4a8d-a69a-b3d1-1815111f08b3
* Version Independent ID: 180b2b09-cdf7-05ff-e4ef-1bc227a22cfb
* Content: [Remove Get and set up Outlook Mobile app on my phone option - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/installation/how-to-remove-get-and-set-up-outlook-mobile-app-on-my-phone-option)
* Content Source: [Outlook/Client/Installation/how-to-remove-get-and-set-up-outlook-mobile-app-on-my-phone-option.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/Installation/how-to-remove-get-and-set-up-outlook-mobile-app-on-my-phone-option.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@lmoore101 Thank you for your feedback. I'll have the image added to the document shortly.

**Comment by msbemba** [comment]
@lmoore101 Thank you for your feedback. We have added the new prompt to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1542

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1542 
Thank you
