### ISSUE TITLE
Where are the instructions for how to set up the rule?

### ISSUE THREAD

**Issue by 6StringJazzer** [MicrosoftDocs/OfficeDocs-Support#148]
I am using Outlook 2019 and can't find an Outlook Rules Wizard or an option for "run a script." Is this feature deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e06b4935-24d7-124a-5f6c-ebaed4e679d2
* Version Independent ID: b2c14660-e8ed-ca53-13f4-8b423a748af9
* Content: [How to create a script for the Rules Wizard in Outlook - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-developer/create-script-for-rule-wizard-in-outlook)
* Content Source: [Office/Client/office-developer/create-script-for-rule-wizard-in-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-developer/create-script-for-rule-wizard-in-outlook.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@6StringJazzer The article you linked applies to Outlook 2010, and is also no longer being updated.

For Outlook 2019, you need to enable the "run a script" option with the help of a registry key first. The steps are described [in this article.](https://support.microsoft.com/en-us/topic/how-to-control-the-rule-actions-to-start-an-application-or-run-a-macro-in-outlook-2016-and-outlook-2013-e4964b72-173c-959d-5d7b-ead562979048)

Keep in mind the article is for Outlook 2013 and 2016, so you need to adapt for Office 2019 in terms of path.

**Comment by nam31** [comment]
@6StringJazzer Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
