### ISSUE TITLE
IM Client?

### ISSUE THREAD

**Issue by wroze** [MicrosoftDocs/OfficeDocs-Support#1480]
How do I know what my IM client is? I can follow all the other steps but I do not understand what my client is or how I can fix this part. I'm trying to get IM working on my companies Outlook apps so we can improve comms.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d8ad0d6-f08c-61af-c9d9-c4c7bcd74315
* Version Independent ID: 0833835a-0a52-112c-d819-a6a247a47cdb
* Content: [Instant messaging client features not available - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/user-interface/some-instant-messaging-client-features-not-available)
* Content Source: [Outlook/Client/user-interface/some-instant-messaging-client-features-not-available.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/user-interface/some-instant-messaging-client-features-not-available.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@wroze Thank you for your feedback. What Instant message client are you trying to incorporate into your companies Outlook Apps? Do you use Microsoft teams or any third-party client like Cisco Jabber? What is the current behavior when you try to IM a colleague currently?

Thanks
Sri

**Comment by msbemba** [comment]
@wroze Hope you were able to find the IM client. let us know if you still feel a document update is needed.

Thanks
Sri

**Comment by nam31** [comment]
@wroze We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
