### ISSUE TITLE
Method 2 Does Nothing

### ISSUE THREAD

**Issue by hrussd** [MicrosoftDocs/OfficeDocs-Support#1481]
Method 2: This did not help. The RegEdit file for
HKEY_LOCAL_MACHINE\Software\Classes\htmlfile\shell\open\command
was identical for the PC on which Outlook 2019 could not open a message in browser as a PC which could.
This is the content for both:
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile\shell\open\command]
@="\"C:\\Program Files\\Internet Explorer\\IEXPLORE.EXE\" %1"
"DelegateExecute"="{17FE9752-0B5A-4665-84CD-569794602F5C}"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f736e25-4b81-c26f-ee4d-640519094af6
* Version Independent ID: 9343708d-ccf7-2e46-d377-13564037a5b9
* Content: [Hyperlinks are not working - Outlook](https://docs.microsoft.com/en-US/outlook/troubleshoot/message-body/hyperlinks-not-working-in-outlook)
* Content Source: [Outlook/Client/message-body/hyperlinks-not-working-in-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/hyperlinks-not-working-in-outlook.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@hrussd Thank you for your feedback. Did you also try Step3 to check the default value is  "htmlfile"

![image](https://user-images.githubusercontent.com/45987684/120407051-f5ef1180-c369-11eb-8a4a-b9fe413b8c99.png)

Thanks
Sri

**Comment by hrussd** [comment]
Yes, I did , and it is htmlfile.

 

Regards,

H. Russell Donovan

***@***.***

**Comment by msbemba** [comment]
@hrussd   The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).

Thanks
Sri

**Comment by vinyar** [comment]
@msbemba  - how about home users? I don't have paid support, but my computer is just as broken.
