### ISSUE TITLE
So what is the process to notify everyone

### ISSUE THREAD

**Issue by gman57783** [MicrosoftDocs/OfficeDocs-Support#1484]
It wonderful to now know that Everyone Except Externals won't get the normal invitation email, and it great to know that this is the 'expected behavior', but this page should also tell me what the process is to notify those who are added to a site.  I'm sure there is some valid reason why the expected behavior is different from when some other group is added to a site, but if I now have to go back and generate a separate email telling everyone with the company domain email address that they now have access to Site X, then your Everyone Except Externals group is absolutely no value to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80d1153b-8536-65d0-e095-14e0ab035c1f
* Version Independent ID: cd07b425-0820-0122-f53c-1fdeb84b00d1
* Content: [Everyone or Everyone except external users group don't receive invitation - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sharing-and-permissions/everyone-group-not-receive-email-invitation)
* Content Source: [SharePoint/SharePointOnline/sharing-and-permissions/everyone-group-not-receive-email-invitation.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sharing-and-permissions/everyone-group-not-receive-email-invitation.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@gman57783 Thank you for your feedback. SharePoint does not email the Everyone or Everyone except external users. This is by design. When you use the everyone group or the everyone except external users you will just be assigning security, SharePoint does not provide an email when these are used.

Unfortunately, there is no workaround apart from sending an email manually to an All users distribution group(if it exists).

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@gman57783 Hopefully I answered your question. In case you feel a document update is needed, let us know.

Thanks
Sri

**Comment by gman57783** [comment]
No further action is required.

**Comment by nam31** [comment]
@gman57783 The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
