### ISSUE TITLE
needs a space after preparead before the next / 

### ISSUE THREAD

**Issue by nickjxyz** [MicrosoftDocs/OfficeDocs-Support#1489]
setup /preparead/IAcceptExchangeServerLicenseTerms  - needs a space after preparead in the document

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5dc1f9c-7ebd-d4fe-dc82-b8405899bd46
* Version Independent ID: 3e9b4bb9-1aa2-81f2-7a12-28a2f21ea3c6
* Content: [Moving migration mailbox fails - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/migration/moving-migration-mailbox-fails)
* Content Source: [Exchange/ExchangeServer/migration/moving-migration-mailbox-fails.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/migration/moving-migration-mailbox-fails.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@nickjxyz . Thanks for pointing out.

**Comment by nam31** [comment]
Closing via #1494 
Thank you
