### ISSUE TITLE
OutlookResetRecentAddresses Not Working

### ISSUE THREAD

**Issue by SWCarson** [MicrosoftDocs/OfficeDocs-Support#149]
I am trying this tool with Outlook v16.29 (Office 365) on the Mac and it is not working.

Old recent addresses (that have an X next to them) are still there when I type in the To line of a new email.

Outlook: 16.29
MacOS: 10.14.5

**Comment by nam31** [comment]
@SWCarson The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@SWCarson We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
