### ISSUE TITLE
Pre-formatting the field as Text before Pasting value does not work in Mac OS version

### ISSUE THREAD

**Issue by mbazzelle** [MicrosoftDocs/OfficeDocs-Support#1490]
[Enter feedback here]I have attempted to pre-format the field by selecting the column and changing the column type from the header menu.  It still is automatically re-formatting long numbers as scientific notation when I paste in the values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa826a3-4a58-3877-2d60-a8883a291c71
* Version Independent ID: baabb01c-cf19-eef9-afac-f1fecc41d205
* Content: [Long numbers are displayed incorrectly in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/long-numbers-incorrectly-in-excel)
* Content Source: [Office/Client/excel/long-numbers-incorrectly-in-excel.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/long-numbers-incorrectly-in-excel.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@mbazzelle Thank you for your feedback. Usually, when you copy a number from another excel file, it carries the format.  You can also select empty cells, and then enter numbers after you format the cells as text. Those numbers will be formatted as text.

For more information, please refer to https://support.microsoft.com/en-us/office/format-numbers-as-text-in-excel-for-mac-dfbe20dc-e7b1-44b2-80fe-2072d074e2a3

I have also added this reference document to the related articles section via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1506

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1506 
Thank you
