### ISSUE TITLE
Publish Date is incorrect

### ISSUE THREAD

**Issue by rohillakr** [MicrosoftDocs/OfficeDocs-Support#1492]
hi Team,

i have doubt about the the publishing/modification date on this article.
date mentioned is 02/05/2019 and in summary paragraph some information mentioned dated March 24, 2020.

requesting you to review the same to provide correct information to users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b0b2e1-5bf4-c802-871b-7577ba317fb1
* Version Independent ID: 1c23c3cc-15c7-85f1-9890-326878e33be8
* Content: [SharePoint Online service process schedule temporary change - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/temporary-adjustments-in-sharepoint-online)
* Content Source: [SharePoint/SharePointOnline/administration/temporary-adjustments-in-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/administration/temporary-adjustments-in-sharepoint-online.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by nam31** [comment]
Closing via #1493 
Thank you
