### ISSUE TITLE
Merging DOCX.

### ISSUE THREAD

**Issue by WAM1956** [MicrosoftDocs/OfficeDocs-Support#1500]
Trying to merge 70+ pages of DOCX. to submit for publication. Photos and text do not stay on separate pages. They are running into the next page. Help!

**Comment by RAJU2529** [comment]
try to change orientation or  text size or  layout paper size.

**Comment by nam31** [comment]
@WAM1956 The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you

**Comment by nam31** [comment]
@WAM1956 We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
