### ISSUE TITLE
Update-PublicFolderPermissions.ps1 no longer exists gives 404.

### ISSUE THREAD

**Issue by j0rt3g4** [MicrosoftDocs/OfficeDocs-Support#1502]
.\Update-PublicFolderPermissions.ps1 no longer exists.

Please correct the link to the addecuate script.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b937cc-c35f-948b-e6f9-3484782ac54a
* Version Independent ID: 00a7a93c-d282-b514-ffb4-6c38a7cf2e8d
* Content: [Can't apply permissions to public folder subfolders in EAC - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/public-folders/can%E2%80%99t-apply-permissions-public-folder-subfolders)
* Content Source: [Exchange/ExchangeOnline/public-folders/can’t-apply-permissions-public-folder-subfolders.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/public-folders/can’t-apply-permissions-public-folder-subfolders.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **batre**

**Comment by RAJU2529** [comment]
issue is conformed from my side
