### ISSUE TITLE
ActiveSync Sync and Ping behavior

### ISSUE THREAD

**Issue by mukunda-** [MicrosoftDocs/OfficeDocs-Support#1505]
Is this article accurate? Why would the Ping command affect the Sync command's output? From what I understand, the Ping command monitors folder(s) for changes. If the client misses the Sync response, it will not get a new Sync Key. Shouldn't the Sync Key be used to determine what state is current on the client? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f5f00d8-ca59-3731-5f43-10519d074e60
* Version Independent ID: 421a9031-b493-d7f2-c700-211d9133a6db
* Content: [Items missing on Exchange ActiveSync client - Exchange](https://docs.microsoft.com/en-US/exchange/troubleshoot/administration/items-missing-on-exchange-activesync-client)
* Content Source: [Exchange/ExchangeOnline/administration/items-missing-on-exchange-activesync-client.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/administration/items-missing-on-exchange-activesync-client.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@mukunda- As the article states, the Ping command is an acknowledgment of the Sync response. So if the client sends a Ping command (because of the heartbeat interval setting), this implies that a succesful sync took place (which it didn't), thus causing the behavior described.

**Comment by mukunda-** [comment]
I think we could avoid errors in current implementations if we were more clear on cases like this. The Ping command is not described as an acknowledgement. It's described as a changes monitor. Technically, Sync should always return data from the point of the recorded sync key given.

MS-ASCMD does not quite describe Ping as a Sync confirmation. However, it does describe that Ping should be based off of the last SyncKey sent, using a "MUST" condition when describing semantics of the workflow.

![image](https://user-images.githubusercontent.com/7541831/121187764-056ccf80-c82e-11eb-8ed0-466109a925f6.png)

So, I think this is sufficient evidence that the flow should always be:
- Sync (check for changes)
- Ping (wait for changes)
- ...repeat...

With the Ping command being optional.
