### ISSUE TITLE
I don't have the folder "options"

### ISSUE THREAD

**Issue by burnindisaster** [MicrosoftDocs/OfficeDocs-Support#1508]
everything ok until it says i have to go to PowerPoint/Options 
![Captura](https://user-images.githubusercontent.com/85144607/120258888-db7d4100-c260-11eb-9667-0ab4dd089801.JPG)
there's only a folder called installroot what do i have to do????

**Comment by nam31** [comment]
@burnindisaster The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you

**Comment by RAJU2529** [comment]
@burnindisaster . Options will be created automatically only after you should adjust settings  under options menu In PowerPoint application.
So open the PowerPoint application, go to file, choose options ,  modify any settings as you like and then click ok, close PowerPoint application. now to go registry editor, now you will find options key is created.

**Comment by nam31** [comment]
@burnindisaster We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
