### ISSUE TITLE
Search Parameter Incorrect

### ISSUE THREAD

**Issue by John471** [MicrosoftDocs/OfficeDocs-Support#151]
Under the heading:-
[ Make sure that the Owners group has permissions to the Access Requests list ]
Step 7. In the search box, type pagelistid:, and then press Enter.

The search term as shown in the instruction (pagelistid:) does *not* locate the GUID.  The search term should be updated to:-
pageListId":
(i.e. upper/lower case is optional, however a double quote character is required immediately before the colon, or the search, as presently detailed, will fail to find any results). (Using Internet Explorer v11.1387.16299.0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fcbe622-fa9d-15c0-038b-259418a6c0ec
* Version Independent ID: 123ff403-baaa-d4e6-f7a5-defbebe827b4
* Content: [Request approval failed when you process a pending request - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/sharing-and-permissions/request-approval-failed?redirectSourcePath=%252fen-us%252farticle%252f-access-denied-to-access-requests-list-or-request-approval-failed-when-you-process-a-pending-request-in-sharepoint-online-3ec71fe1-9111-4a4c-84a5-bdfe05c2e558#feedback)
* Content Source: [SharePoint/SharePointOnline/sharing-and-permissions/request-approval-failed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sharing-and-permissions/request-approval-failed.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by claudialake** [comment]
The article has been updated to clarify.
