### ISSUE TITLE
Developer Tools Window Instructions Improvement Suggestions (for IE11)

### ISSUE THREAD

**Issue by John471** [MicrosoftDocs/OfficeDocs-Support#152]
Under the heading:-
[ Make sure that the Owners group has permissions to the Access Requests list ]
Step 5. In the Developer Tools window, double-click the *first result* in the URL list. This URL ends in "pendingreq.aspx."
- note : the required item is not the *first result* in the URL list in my case, it is preceded by an item for https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true....

Step 6. In the Developer Tools window, click Response body.
- note : the panel may not open with the 'Body' tab active, in which case there is no visible 'Response body' to click on. This instruction may be better expressed as:-
In the Developer Tools window, whilst on the Network tab, in the right-hand side panel, navigate to Body &gt; Response body

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fcbe622-fa9d-15c0-038b-259418a6c0ec
* Version Independent ID: 123ff403-baaa-d4e6-f7a5-defbebe827b4
* Content: [Request approval failed when you process a pending request - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/sharing-and-permissions/request-approval-failed?redirectSourcePath=%252fen-us%252farticle%252f-access-denied-to-access-requests-list-or-request-approval-failed-when-you-process-a-pending-request-in-sharepoint-online-3ec71fe1-9111-4a4c-84a5-bdfe05c2e558#feedback)
* Content Source: [SharePoint/SharePointOnline/sharing-and-permissions/request-approval-failed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sharing-and-permissions/request-approval-failed.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The article is updated. Thanks.
