### ISSUE TITLE
Line breaks are removed in posts with rich format

### ISSUE THREAD

**Issue by FWW410552** [MicrosoftDocs/OfficeDocs-Support#1520]
A recent topic from Microsoft states that the removal of line breaks only occurs in plain text formatted messages. That's simply not true. Also in rich text formatted messages the line breaks are removed, even though the option is switched off.
Any one who can help?
Freek Weeda, the Netherlands

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99035eb-0df0-4ecf-f126-c9602805cbb1
* Version Independent ID: 814cd737-87d4-eea4-7cb4-3be6c3bf6ec2
* Content: [Line breaks are removed in posts made in plain text format - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/message-body/line-breaks-are-removed-in-posts-made-in-plain-text)
* Content Source: [Outlook/Client/message-body/line-breaks-are-removed-in-posts-made-in-plain-text.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/line-breaks-are-removed-in-posts-made-in-plain-text.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by joinimran** [comment]
Hi @FWW410552, thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by joinimran** [comment]
Hi @FWW410552,  can you tell me which version of Outlook are you using?

**Comment by nam31** [comment]
@FWW410552 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you
