### ISSUE TITLE
Seems to be applicable to on-premise servers as well

### ISSUE THREAD

**Issue by vherrlein** [MicrosoftDocs/OfficeDocs-Support#1521]
1. Seems to be applicable to on-premise servers as well.
2. Absolute URL not supported too

**SharePoint Server 2013**
Relying on the method "Microsoft.SharePoint.ApplicationPages.CreateNewDocument.CreateDocument(string, SPFolder, string)"
**SharePoint Server 2019**
Relying on the method "Microsoft.SharePoint.SPList.CreateDocumentInternal(SPResourcePath, SPFolder, SPResourcePath)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a947b38a-3bc9-3c93-bed5-85534afbda11
* Version Independent ID: 41889edb-0ae5-db2f-56d6-57a997926e64
* Content: [Relative URLs for content types across site collections is not supported - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/lists-and-libraries/relative-url-across-site-collection-not-supported)
* Content Source: [SharePoint/SharePointOnline/lists-and-libraries/relative-url-across-site-collection-not-supported.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/lists-and-libraries/relative-url-across-site-collection-not-supported.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by simonxjx** [comment]
Checking.

**Comment by nam31** [comment]
Closing via #1624 
Thank you
