### ISSUE TITLE
Incorrect summary of low/no CPU usage.

### ISSUE THREAD

**Issue by mntorq** [MicrosoftDocs/OfficeDocs-Support#1523]
Statement of: "It doesn't cause any Office performance issues during startup."
Is false. 

It consumes 50-60% CPU for at least 30 minutes

![image](https://user-images.githubusercontent.com/66257685/120681817-c6bfc980-c469-11eb-8567-d6c9b063c63c.png)

There are also numerous Forum posts regarding this. 
https://answers.microsoft.com/en-us/windows/forum/all/microsoft-office-sdx-helper-high-cpu-in-background/cc5c9682-1bc6-409f-8882-33be61039e8f
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8e0141a-1e1e-ed87-beac-13b1ac0dba53
* Version Independent ID: e8c1ef21-1a8b-051a-8e86-276df2ae1308
* Content: [Office Feature Updates task description and FAQ - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/updates/office-feature-updates-task-faq)
* Content Source: [Microsoft365/admin/updates/office-feature-updates-task-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/updates/office-feature-updates-task-faq.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by joinimran** [comment]
I am taking care of this.

**Comment by nam31** [comment]
@mntorq we are going to close this issue as the article has been updated accordingly. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
