### ISSUE TITLE
Changing JPG save resolution in Office 365

### ISSUE THREAD

**Issue by skibum42** [MicrosoftDocs/OfficeDocs-Support#154]
The information on this page worked on Office 2013, but for Office 365, I am not finding the registry values mentioned.  There is nothing under the HKCU\Software\Microsoft\Office, but a Common folder.   Are the 365 registry values somewhere else or is high-resolution saving not supported in PowerPoint 365?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e390c4c9-9cdf-beb1-43dc-6ec45ae5fe77
* Version Independent ID: bb31c9ea-7186-22fb-195f-f481eb5137e4
* Content: [How to change the export resolution of a PowerPoint slide - Office](https://docs.microsoft.com/en-us/office/troubleshoot/powerpoint/change-export-slide-resolution#feedback)
* Content Source: [Office/Client/powerpoint/change-export-slide-resolution.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/powerpoint/change-export-slide-resolution.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jzohsuh** [comment]
If you have the Office 365 licence, as of November 2019, you should find it here:
HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\PowerPoint\Options

(This appeared to work for me- I have Office 365.)

**Comment by riteshporwal** [comment]
You first see if office 365 or Office 2019  is appearing on your installed program list. Sometime office works correctly but still its is not in your installed program list. You can see your installed program list from control panel. 
Now if Office doesn't show in installed program list then go to your office app from start menu and install office 2019. It will take around half-n-hour. Now you will see office in installed program list. 
Now you can go edit registry. it is there.

**Comment by skibum42** [comment]
Thanks.  I finally solved it with help from a MS support rep.  I had installed Office 365 from the App Store and it didn't support the registry entry.  I re-installed via the normal route and was able to make the registry change.

**Comment by nam31** [comment]
@skibum42 The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content
Thank you.

**Comment by nam31** [comment]
@skibum42 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
