### ISSUE TITLE
Назначение категорий задач в outlook при почте с протоколом imap

### ISSUE THREAD

**Issue by vri229it** [MicrosoftDocs/OfficeDocs-Support#1549]
Решение следующее:
1. Заходим в раздел Задачи. Создаём новую папку со следующими настройками:
Содержимое папки: элементы типа Задача, поместить в папку: Задачи (только этот компьютер)
2. Заходим в новую папку и назначаем задаче необходимую категорию. Доступно переименование категорий, группировка, перенос.
3. В представлении Задач в области Списка дел (где почта) - категории отображаются, но менять их и переносить там недоступно.

[Введите отзыв здесь]

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: af419cb4-8534-71c5-2717-df7df7d4d465
* Version Independent ID: b3c245ef-01ed-9579-d87c-357efdec40b7
* Content: [Невозможно назначить цветовые категории для учетных записей IMAP - Outlook](https://docs.microsoft.com/ru-ru/outlook/troubleshoot/user-interface/cannot-assign-color-categories-for-imap-accounts)
* Content Source: [Outlook/Client/user-interface/cannot-assign-color-categories-for-imap-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/user-interface/cannot-assign-color-categories-for-imap-accounts.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@vri229it Thank you for your feedback. I was able to test this and it works. However, this is not the exact color category feature that outlook provides, instead, it uses the task/color categories. This is a nice way of adding email to the tasks/to list with color categories but does not let you view the color categories in the email reading pane. So I don't think this can be added to the document as a workaround.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@nam31 There are no changes required in this document. Please close the issue.

**Comment by nam31** [comment]
@vri229it Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
