### ISSUE TITLE
AutoFit feature for rows or columns that contain merged cells

### ISSUE THREAD

**Issue by Levelup1P** [MicrosoftDocs/OfficeDocs-Support#1557]
"You cannot use the AutoFit feature for rows or columns that contain merged cells in Excel"
Well, that s**ks, It was ON by default in google docs. I think I'll stick to that then. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 637418b9-c486-0de0-7f52-c79b4b3dc542
* Version Independent ID: a357675b-ee15-92a3-9c82-9abcd9d261c4
* Content: [Wrap text not adjust row height - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/wrap-text-not-adjust-row-height)
* Content Source: [Office/Client/excel/wrap-text-not-adjust-row-height.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/wrap-text-not-adjust-row-height.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by dariomws** [comment]
@billwolfhub - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make Excel better. They keep a close tab on user feedback, and it would be awesome if you could add your feedback in:
https://support.microsoft.com/office/how-do-i-give-feedback-on-microsoft-office-2b102d44-b43f-4dd2-9ff4-23cf144cfb11
https://techcommunity.microsoft.com/t5/microsoft-excel/ct-p/Excel_Cat
Here we are limited to documentation issues and improvements.

You might find others have made a similar request that you can add to, or you can open a new one.

Thank you for your contribution to make the docs better! Much appreciated!
