### ISSUE TITLE
Fix for those still struggling

### ISSUE THREAD

**Issue by MarvinNorway** [MicrosoftDocs/OfficeDocs-Support#156]
Visual Studio creates two projects, one for the add-in "website" that will be displayed in the side panel in Excel, and another project for just the manifest. I have found that running the manifest project will launch Excel, but sometimes (always?) the local webserver isn't started. Just run the local web project first (F5) and then right-click the manifest project and start a separate instance. That solved it for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 236f9838-fd32-0154-122e-77725824160a
* Version Independent ID: 76d757f8-a4b1-3bb2-a186-a21b385c6b7e
* Content: [We can't open this add-in from localhost - Office](https://docs.microsoft.com/en-us/office/troubleshoot/error-messages/cannot-open-add-in-from-localhost#feedback)
* Content Source: [Office/Client/error-messages/cannot-open-add-in-from-localhost.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/error-messages/cannot-open-add-in-from-localhost.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@MarvinNorway The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content ?
Thank you.

**Comment by MarvinNorway** [comment]
@nam31 Well, this issue is 1.5 years old. To be honest, I don't remember the details. Would have helped if someone had looked into this a bit earlier...
