### ISSUE TITLE
Service Reboot Required

### ISSUE THREAD

**Issue by aurentzt** [MicrosoftDocs/OfficeDocs-Support#1563]
An import step seems to be missing from this article.  Please ensure it is clear that the Exchange Services must be restarted for changes to take effect.  We went through the guide and updated all values and confirmed they were showing the correct values.  However, only after the Exchange service was restarted did the 10MB message stop being displayed and attachments larger than 10MB were allowed to be sent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d62d97d-7750-3bb3-330c-3fd77f9223c6
* Version Independent ID: a8c266b1-e570-5b51-d3bb-4aa5e74fa2a7
* Content: [Can't add an attachment in Outlook on the web - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/mailflow/cannot-add-attachment-outlook-web)
* Content Source: [Exchange/ExchangeServer/mailflow/cannot-add-attachment-outlook-web.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/mailflow/cannot-add-attachment-outlook-web.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@aurentzt Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1592

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1592 
Thank you
