### ISSUE TITLE
No instructions for Firefox

### ISSUE THREAD

**Issue by chrisrapson** [MicrosoftDocs/OfficeDocs-Support#1567]
This page has instructions for Edge, Internet Explorer and Chrome. It would be good to include instructions for Firefox. If Teams supports Mac, then Safari would also be worthwhile. Both have higher market share than Internet Explorer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c17faf2-0e38-0a98-454c-3c2c4387b37f
* Version Independent ID: d9153b98-dc39-fdd1-a798-07da0caaaa64
* Content: [Microsoft Teams is stuck in a login loop in Edge, Internet Explorer or Google Chrome - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#resolution)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by chrisrapson** [comment]
I now see that the page I sent this is only intended to reference Edge, Internet Explorer or Chrome.

I reached that page when trying to load MicroSoft Teams in Firefox, and reached this error:
"To open the web app, change your browser settings to allow third-party cookies or allow certain trusted domains."

When I clicked the hyperlink for "change your browser settings" it took me to the "stuck in a login loop" page.

**Comment by nam31** [comment]
@chrisrapson we are going to close this issue as the article has been updated accordingly. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
