### ISSUE TITLE
This is really disapointing.  There shsould be a warning before you mark a lot of msgs as read.

### ISSUE THREAD

**Issue by billwolfhub** [MicrosoftDocs/OfficeDocs-Support#1573]
SUPER DISAPPOINTING.  This is such a common mistake and a simple "Are you Sure?" would prevent it.    

Honestly this is the most I've wanted to curse Microsoft in a long long time.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cafe1e33-42e4-3963-3cc8-5933e641c598
* Version Independent ID: 3494acea-0387-76d6-238a-c9266ea999ee
* Content: [Cannot undo changes if all messages marked as read - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/user-interface/cannot-undo-changes-if-marking-all-messages-as-read)
* Content Source: [Outlook/Client/user-interface/cannot-undo-changes-if-marking-all-messages-as-read.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/user-interface/cannot-undo-changes-if-marking-all-messages-as-read.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by dariomws** [comment]
@billwolfhub - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make Outlook better. They keep a close tab on user feedback, and it would be awesome if you could add your feedback in:
https://support.microsoft.com/office/how-do-i-give-feedback-on-microsoft-office-2b102d44-b43f-4dd2-9ff4-23cf144cfb11
https://techcommunity.microsoft.com/t5/outlook/ct-p/Outlook
Here we are limited to documentation issues and improvements.

You might find others have made a similar request that you can add to, or you can open a new one.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by nam31** [comment]
@billwolfhub Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
