### ISSUE TITLE
Excel Text column setting is defective for numbers

### ISSUE THREAD

**Issue by cvhorie** [MicrosoftDocs/OfficeDocs-Support#1586]
This method does not work

I am copying registration numbers, like 1866,1114.70   from a text into my spreadsheet.
I have already formatted the column as Text.
But any new copy and pasted reg. nos. are pasted as numbers, eg. 18661114.7

How do I force Excel to to recognise the column setting when pasting or other manipulation?  
For instance after changing the column from general to text, I had to correct a large number of mispasted reg.nos.  These had been displayed as
18661114.7 
It was not possible to do a find and replace to change multiple instances of 1866 to 1866,
I did them all by hand, and had to correct the .70 
When manipulating important data that is in the form of a number, e.g. passport or health number, it can be vitally important that the data element is not changed in any way.  Excel is widely used for managing this kind of data. This error in parsing data needs to be fixed.
Thank you
I am using Excel 2109 and Win10
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa826a3-4a58-3877-2d60-a8883a291c71
* Version Independent ID: baabb01c-cf19-eef9-afac-f1fecc41d205
* Content: [Long numbers are displayed incorrectly in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/long-numbers-incorrectly-in-excel)
* Content Source: [Office/Client/excel/long-numbers-incorrectly-in-excel.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/long-numbers-incorrectly-in-excel.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by joinimran** [comment]
Hi @cvhorie, thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by joinimran** [comment]
Hi @cvhorie, I followed the following method it worked for me.
1.Right-click target cell and then click Format Cells
2.On the Number tab, select Text and then click OK.
3.Then type a long number. (Be sure to set the cell format before you type the number).
4.If you do not want to see the warning arrows, click the small arrow, and then click Ignore Error.
![image](https://user-images.githubusercontent.com/47118050/123417065-c205b580-d5d0-11eb-8649-43a4375dbb74.png)

**Comment by nam31** [comment]
@cvhorie Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
