### ISSUE TITLE
Microsoft Office Visio isn't free

### ISSUE THREAD

**Issue by ITJoe29** [MicrosoftDocs/OfficeDocs-Support#1590]
At the end of this article (https://docs.microsoft.com/en-us/office/troubleshoot/visio/open-visio-files-in-visio-web-access) it suggests to go to https://products.office.com/en-US/Visio as a means to resolve issues where Visio Viewer isn't working. 

The suggested work around/solution to the problem requires a purchase of Visio. This isn't a solution to the problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67500af2-e0c3-7d2c-92ad-074a90e49b89
* Version Independent ID: 87d2a160-e8fd-afdd-244b-cdcefd9f69c4
* Content: [Can't open Visio files in Visio Web Access - Office](https://docs.microsoft.com/en-us/office/troubleshoot/visio/open-visio-files-in-visio-web-access)
* Content Source: [Office/Client/visio/open-visio-files-in-visio-web-access.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/visio/open-visio-files-in-visio-web-access.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by MaratMussabekov** [comment]
Hello @ITJoe29 ,
I agree that is not a resolution, but it still be considered as a workaround.
Thank you

**Comment by nam31** [comment]
Closing via #1602 
Thank you
