### ISSUE TITLE
needs update

### ISSUE THREAD

**Issue by lukasmehringer** [MicrosoftDocs/OfficeDocs-Support#1594]
Servus ich arbeite auf einem Windows 10 Rechner. Leider war es mir nicht möglich den Punkt "UseOnlineContent" zu finden. 
---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: ab3b3b72-87a5-8b6f-f049-0500b0cbee6e
* Version Independent ID: b8a259e9-cb59-936d-f38f-e157772ca311
* Content: [Fehlermeldung „Dieses Feature wurde von Ihrem Administrator deaktiviert“ in Microsoft Office - Office 365](https://docs.microsoft.com/de-de/office365/troubleshoot/access-management/office-feature-disabled)
* Content Source: [Microsoft365/admin/access-management/office-feature-disabled.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/access-management/office-feature-disabled.md)
* Service: **sharepoint-powershell**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by msbemba** [comment]
@lukasmehringer Thank you for your feedback. If you don't have the registry either the issue could be different from what is described in the document or you can continue creating the key mentioned in the document. Let us know if the issue persists even after creating the key.

Thanks
Sri

**Comment by msbemba** [comment]
@lukasmehringer Just wanted to circle back and check if you still have any questions or if there are any updates required in the document.

Thanks
Sri

**Comment by nam31** [comment]
@lukasmehringer Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
