### ISSUE TITLE
There is a wrong char in the signoutofwamaccounts.ps1 file

### ISSUE THREAD

**Issue by FullStackEngN** [MicrosoftDocs/OfficeDocs-Support#1596]
I download the signoutofwamaccounts.ps1, but it failed to run.
Then I open the file using notepad, and I found last line contains unexpected char.
Please help update the script content.

$accounts.Accounts | % { AwaitAction ($_.SignOutAsync(**揹**3590ed6-52b3-4102-aeff-aad2292ab01c**?**) }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1375a9d-fa30-75a2-5aea-daca0e74f142
* Version Independent ID: c9510807-f261-5a24-0039-d6bf5ad630e5
* Content: [Reset Microsoft 365 Apps for enterprise activation state - Office](https://docs.microsoft.com/en-us/office/troubleshoot/activation/reset-office-365-proplus-activation-state)
* Content Source: [Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md)
* Service: **o365-solutions**
* GitHub Login: @MJP-MSFT
* Microsoft Alias: **mattphil**

**Comment by RAJU2529** [comment]
@FullStackEngN . i have removed invalid char, i added two scripts, one of the script will work for you.
[signoutofwamaccounts.zip](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/6660233/signoutofwamaccounts.zip)

**Comment by FullStackEngN** [comment]
Hi expert,

Thanks for your feedback, the second one scripts run successfully.

$accounts.Accounts | % { AwaitAction ($_.SignOutAsync({d3590ed6-52b3-4102-aeff-aad2292ab01c})) }


The first one still encountered problem.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by RAJU2529** [comment]
@MJP-MSFT . I have corrected an invalid character in **signoutofwamaccounts.ps1**  and i uploaded it here, so, please upload this ZIP   
[signoutofwamaccounts.zip](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/6660615/signoutofwamaccounts.zip)
 file in the Microsoft download center server.

**Comment by MJP-MSFT** [comment]
+ @Eric ***@***.***> who has been driving the scripts upload process.

Matt Philipenko
Sr. Customer Engineer - Microsoft 365 Apps Ranger
Microsoft 365 Apps <Deployment/Servicing/Activation/>
10 Habits to create accessible content<https://blogs.microsoft.com/accessibility/10-habits-to-create-accessible-content/>

**Comment by MJP-MSFT** [comment]
Follow up:

We cannot update the script our engineers will need to address this issue if any.  Can you open a support case through your organization to properly track this issue you're seeing?

Matt Philipenko
Sr. Customer Engineer - Microsoft 365 Apps Ranger
Microsoft 365 Apps <Deployment/Servicing/Activation/>
10 Habits to create accessible content<https://blogs.microsoft.com/accessibility/10-habits-to-create-accessible-content/>



From: Matt Philipenko (OFFICE RANGER)
Sent: Wednesday, June 16, 2021 8:29 AM
To: MicrosoftDocs/OfficeDocs-Support ***@***.***>; MicrosoftDocs/OfficeDocs-Support ***@***.***>; Eric Splichal ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/OfficeDocs-Support] There is a wrong char in the signoutofwamaccounts.ps1 file (#1596)

+ @Eric ***@***.***> who has been driving the scripts upload process.

Matt Philipenko
Sr. Customer Engineer - Microsoft 365 Apps Ranger
Microsoft 365 Apps <Deployment/Servicing/Activation/>
10 Habits to create accessible content<https://blogs.microsoft.com/accessibility/10-habits-to-create-accessible-content/>

**Comment by RAJU2529** [comment]
@MJP-MSFT 
in this script   **signoutofwamaccounts.ps1**  below  line must be replaced 
**�d3590ed6-52b3-4102-aeff-aad2292ab01c�**    

by

 **{d3590ed6-52b3-4102-aeff-aad2292ab01c}**

so please  @MJP-MSFT  verify the script with notepad.

**Comment by msbemba** [comment]
@FullStackEngN Thank you for your feedback. I see the updated script without the wrong character.

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@FullStackEngN Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
