### ISSUE TITLE
Inaccurate/out of date instructions?

### ISSUE THREAD

**Issue by jimvernon** [MicrosoftDocs/OfficeDocs-Support#1597]
It does not appear that "double clicking" a domain does anything, nor does there appear to be an option for "shared" in the side panel that flies out with clicking a domain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce99bf5-25b2-a3bb-8205-d61cdf13826e
* Version Independent ID: 2355d132-1c5f-751c-df3d-e3a801c6ce96
* Content: [On-premises users not getting emails from Microsoft 365 - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/email-delivery/on-premises-users-not-getting-emails-from-microsoft-365)
* Content Source: [Exchange/ExchangeHybrid/email-delivery/on-premises-users-not-getting-emails-from-microsoft-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/email-delivery/on-premises-users-not-getting-emails-from-microsoft-365.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello @jimvernon ,
yes, the instruction is outdated.
I created a PR to update it.
Thank you

**Comment by nam31** [comment]
Closing via #1637 
Thank you
