### ISSUE TITLE
Limitation information incorrect

### ISSUE THREAD

**Issue by bazzilic** [MicrosoftDocs/OfficeDocs-Support#16]
Seems like the info on max possible dpi being 307 is incorrect, I set dpi to 900 decimal through regedit and it exports my slides correctly with dimensions much higher than 3072 × 2304.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e72bcb0-3d1d-c5f4-5caf-facd2a089622
* Version Independent ID: 40ad10e2-0a95-7609-cf99-496a98e5a871
* Content: [How to change the export resolution of a PowerPoint slide - Troubleshooting | Office](https://docs.microsoft.com/en-us/office/troubleshoot/powerpoint/change-export-resolution-of-powerpoint-slide#feedback)
* Content Source: [Office/Client/powerpoint/change-export-resolution-of-powerpoint-slide.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/powerpoint/change-export-resolution-of-powerpoint-slide.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Checking to see if we can recommend a higher resolution.

**Comment by jlriesco** [comment]
Michael Maxey will be editing the article to reflect the new resolution.

**Comment by jlriesco** [comment]
The update has been made so I am closing
