### ISSUE TITLE
HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\MSExchangeIS\ParametersSystem

### ISSUE THREAD

**Issue by robert-krause** [MicrosoftDocs/OfficeDocs-Support#1603]
Thank you for the details.  However, I have Exchange Server for Office 365 with all updates, and therefore the latest version.
You state to go to HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\MSExchangeIS\ParametersSystem
However, this is as far as I can go:  Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services
There is no MSExchangeIS folder.
What should I do now?
Thanks!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81b9e548-8b47-8450-b43f-03c235d2345d
* Version Independent ID: bb938e2f-aa98-70b3-a046-97d1427df045
* Content: [You are over Junk E-mail list limit - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/junk-email/outlook-error-over-junk-emial-list-limit)
* Content Source: [Outlook/Client/junk-email/outlook-error-over-junk-emial-list-limit.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/junk-email/outlook-error-over-junk-emial-list-limit.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by RAJU2529** [comment]
@robert-krause . You need to create required registry key manually and tehn to add correct value with data.

**Comment by MaratMussabekov** [comment]
Hello, @robert-krause ,
you should try other options, since the described registry key is not presented in newer Exchange Server versions.
Thank you

**Comment by nam31** [comment]
Closing via #1610 
Thank you
