### ISSUE TITLE
Guidance for removing this from OWA as well

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Support#1604]
This article seems like a good place to also document how you can turn this feature off for Outlook on the Web.  It is via `Set-OrganizationConfig -MobileAppEducationEnabled:$false`.

Source: https://docs.microsoft.com/en-us/powershell/module/exchange/set-organizationconfig?view=exchange-ps#:~:text=The%20MobileAppEducationEnabled

I get a error 404 page not found when I click the Edit/pencil button on the page, so couldn't just submit a PR myself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 359383bf-4a8d-a69a-b3d1-1815111f08b3
* Version Independent ID: 180b2b09-cdf7-05ff-e4ef-1bc227a22cfb
* Content: [Remove Get and set up Outlook Mobile app on my phone option - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/installation/how-to-remove-get-and-set-up-outlook-mobile-app-on-my-phone-option)
* Content Source: [Outlook/Client/Installation/how-to-remove-get-and-set-up-outlook-mobile-app-on-my-phone-option.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/Installation/how-to-remove-get-and-set-up-outlook-mobile-app-on-my-phone-option.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by MaratMussabekov** [comment]
hello @JeremyTBradshaw ,
I also got error 404, it looks like github is case sensetive:
https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/Installation/how-to-remove-get-and-set-up-outlook-mobile-app-on-my-phone-option.md - returns error 404 (it has "I" in "Installation")
https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/installation/how-to-remove-get-and-set-up-outlook-mobile-app-on-my-phone-option.md - opens the editing page (it has "i" in "installation")

Thank you

**Comment by MaratMussabekov** [comment]
Hello @JeremyTBradshaw ,
please have a look at #1660 
I am not sure this PR will be applied by Microsoft since the article is about MS Office Outlook, and OWA is a part of Exchange, not MS Office, however, let's give it a shot )
Thank you

**Comment by JeremyTBradshaw** [comment]
@MaratMussabekov thanks very much for taking care of this and figuring out the link issue.  The PR looks perfect to me!

**Comment by nam31** [comment]
Closing via #1660 
Thank you
