### ISSUE TITLE
Microsoft 365 Apps

### ISSUE THREAD

**Issue by aka-cardz** [MicrosoftDocs/OfficeDocs-Support#1605]
"Shared Computer Activation is only available for Microsoft 365 Apps."

It's not clear if "Microsoft 365 Apps" refers to both Microsoft 365 Apps for business and Microsoft 365 Apps for enterprise, as only Microsoft 365 Apps for enterprise is explicitly mentioned. Other documents mention that Shared computer activation is supported with Microsoft 365 Apps for business as long as the users have Microsoft 365 Business Premium licenses, but since this document specifically deals with the issue on RDS hosts and only mentions Microsoft 365 Apps for enterprise, it would be helpful if it explicitly stated whether or not Microsoft 365 Apps for business is also supported on an RDS host.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a74a612a-33c1-e216-ec12-85f4c974436a
* Version Independent ID: 783bc271-e638-7c8c-1273-1c6ef5177ffb
* Content: [Open Click-to-Run version of Office on a terminal server - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/click-to-run-office-on-terminal-server)
* Content Source: [Office/Client/office-suite-issues/click-to-run-office-on-terminal-server.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/click-to-run-office-on-terminal-server.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@aka-cardz Thank you for your feedback. You are correct, The Microsoft 365 Business Premium plan is the only business plan that includes support for shared computer activation. I have added a note to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1619

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1619 
Thank you
