### ISSUE TITLE
Problème lié au registre avec 16.0 au lieu de 15.0

### ISSUE THREAD

**Issue by ProfesseurXpro** [MicrosoftDocs/OfficeDocs-Support#1608]
[Bonjour, j'ai suivi le plan de depannage a la lettre mais a la dernière étape j'ai vu un sous dossier du registre nommé 16.0 au lieu de 15.0 comme dit sur le site.  Je pense que c'est cette étape qui a fait a ce que je retrouve pas le sous registre de la fin apres "common". il y'aurait il un moyen de regler ce probleme de Drive avec 16.0.]

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9d6e3ca1-7649-7b00-d45c-fc62b6374098
* Version Independent ID: 484304ce-60cd-fec8-c2e8-e13c81a3aba3
* Content: [Nous ne pouvons pas nous connecter au site SharePoint spécifié - SharePoint](https://docs.microsoft.com/fr-fr/sharepoint/troubleshoot/sync/onedrive-for-business-sync-returns-error#resolution)
* Content Source: [SharePoint/OneDrive/sync/onedrive-for-business-sync-returns-error.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/OneDrive/sync/onedrive-for-business-sync-returns-error.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@ProfesseurXpro Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1620

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1620 
Thank you
