### ISSUE TITLE
Wrong information: Minor version is searchable

### ISSUE THREAD

**Issue by PerJarlemark** [MicrosoftDocs/OfficeDocs-Support#1609]
**Minor version is searchable**
the text on the page claims minor versions is not searchable but they are, if this has not been changed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 347f3fed-01c7-a1c1-ef4b-206aefea5056
* Version Independent ID: 5d46bf6e-72e0-798c-957a-a16440c436f6
* Content: [Search results missing in SharePoint Online - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/search/search-results-missing)
* Content Source: [SharePoint/SharePointOnline/search/search-results-missing.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/search/search-results-missing.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@PerJarlemark Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1663

Thanks
Sri

**Comment by nam31** [comment]
Closing via @1663
Thank you
