### ISSUE TITLE
Please add another registy entry to this list

### ISSUE THREAD

**Issue by DocUpdate** [MicrosoftDocs/OfficeDocs-Support#1611]
[Enter feedback here]

There are times when users need to use the emailaddress and not the UPN for Autodiscover logons.  Can the following be added, (taken from https://support.microsoft.com/en-us/topic/november-5-2019-update-for-outlook-2016-kb4484139-9f986a96-8075-7ded-ccf4-d4ba69e8efeb) so we have all the autodiscover registry keys in one place,

When a user wants to user their email address for autodiscover instead of their UPN.

Add the registry PreferProvidedEmailInAutoDiscoverAuthPrompts that enables users to be authenticated using the configured account email or the user principal name (UPN) during AutoDiscover scenarios.

Registry key
Location: HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Outlook\AutoDiscover
Value Type: DWORD
Value name: PreferProvidedEmailInAutoDiscoverAuthPrompts

Value data:
0: It's the default value. Outlook will use the UPN when it's available.
1: If the value is set to 1, Outlook will ignore the UPN and just use the provided account email.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5128fe3-c5d0-be69-afc4-bbb644c3a303
* Version Independent ID: a5b9870b-4d90-b98a-8fa0-85ce84334eb3
* Content: [Unexpected Autodiscover behavior if settings under the \Autodiscover key - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/profiles-and-accounts/unexpected-autodiscover-behavior)
* Content Source: [Outlook/Client/profiles-and-accounts/unexpected-autodiscover-behavior.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/profiles-and-accounts/unexpected-autodiscover-behavior.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@DocUpdate Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1627

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1627 
Thank you
