### ISSUE TITLE
Could not authenticate

### ISSUE THREAD

**Issue by alexfreu69** [MicrosoftDocs/OfficeDocs-Support#162]
If you receive an error message like

Connect-SPOService : Could not authenticate to SharePoint Online http://contoso-admin.sharepoint.com/ using OAuth 2.0

just try:

Connect-SPOService -URL https://contoso-admin.sharepoint.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10cbe7f0-b53e-b339-6177-d11228cfb15a
* Version Independent ID: a98ade74-a921-f149-689c-dd4e21e58df2
* Content: [Your session has expired in Office Online - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/your-session-has-expired-error#feedback)
* Content Source: [Microsoft365/admin/administration/your-session-has-expired-error.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/your-session-has-expired-error.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Update the command to use "HTTPS" to connect to the admin site.
