### ISSUE TITLE
Missing backslash in file path

### ISSUE THREAD

**Issue by MitchJaehrlich** [MicrosoftDocs/OfficeDocs-Support#1631]
In step 2 of the "[Create a Temporary Internet Files folder](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/no-file-previews-file-explorer-switching-to-32-bit#create-a-temporary-internet-files-folder)" section, the file path should be:
"C:\Users\<XXXX>\AppData\Local\Microsoft\Windows"
instead of "C:\Users<XXXX>\AppData\Local\Microsoft\Windows"

The current line implies that there is a folder called "UsersMitch", in the case of my username.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 301c2efc-2856-4ba4-365d-66ddcf6b7e35
* Version Independent ID: 8d6b913c-061c-4aa1-f81f-2c84e5965cfe
* Content: [Office error “could not create the work file” - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/no-file-previews-file-explorer-switching-to-32-bit)
* Content Source: [Office/Client/office-suite-issues/no-file-previews-file-explorer-switching-to-32-bit.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/no-file-previews-file-explorer-switching-to-32-bit.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by RAJU2529** [comment]
@MitchJaehrlich . Thanks for pointing out.

**Comment by nam31** [comment]
Closing via #1639 
Thank you
