### ISSUE TITLE
Solution doesn't fit cause

### ISSUE THREAD

**Issue by mauld-louie** [MicrosoftDocs/OfficeDocs-Support#1638]
[Enter feedback here]
This article doesn't make sense because it says the cause is that the text/html MIME type was removed or changed. But the solution is to remove the text/html MIME type. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b95f13c4-bcf9-5c41-784d-18ec336e2559
* Version Independent ID: 4dec44a0-03d4-42c7-6dfc-71ce099bd995
* Content: [We can't display your message right now error in Outlook Web App - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/office-message-encryption/cannot-display-message)
* Content Source: [Microsoft365/compliance/office-message-encryption/cannot-display-message.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/compliance/office-message-encryption/cannot-display-message.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by MaratMussabekov** [comment]
Hello @mauld-louie ,
please have a look at https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1656
Thank you

**Comment by nam31** [comment]
Closing via #1656 
Thank you
