### ISSUE TITLE
Error on this page

### ISSUE THREAD

**Issue by sanga549** [MicrosoftDocs/OfficeDocs-Support#164]
Need to disable Automatic updates in Office 2013 while used from Citrix because all users are getting prompted to update office when launched from Citrix.

This document says:
Office 2013
HKEY_LOCAL_MACHINE\software\policies\microsoft\office\15.0\common\OfficeUpdate

However there is no "office" key in that path. The actual path is as follows: 
HKEY_LOCAL_MACHINE\software\Wow6432Node\microsoft\office\15.0\common\MicrosoftUpdate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49136300-9a11-ce51-3830-cf8bba44f881
* Version Independent ID: 8a0dd569-5d49-cdc7-c903-38ff685261c5
* Content: [Automatic updating for Office 2016 and 2013 Click-to-Run is not enabled - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/automatic-updates#feedback)
* Content Source: [Microsoft365/admin/administration/automatic-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/automatic-updates.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by simonxjx** [comment]
It is updated.
