### ISSUE TITLE
Page documenting how to change profile picture - update to links and instructions

### ISSUE THREAD

**Issue by robertafreese** [MicrosoftDocs/OfficeDocs-Support#1645]
This page seems out of date.

The links are called:

View Account
https://myaccount.microsoft.com/?ref=MeControl&login_hint=[myinfohinthere]

and

My Office Profile
https://[mytenant]-my.sharepoint.com/person.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11a2fd28-32c0-0d80-312a-7f35ff186812
* Version Independent ID: a7870de6-9246-a1f9-7190-cbadbe6bdffa
* Content: [How to change your user photo - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/how-to-change-your-user-photo)
* Content Source: [Exchange/ExchangeOnline/administration/how-to-change-your-user-photo.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/administration/how-to-change-your-user-photo.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello @robertafreese ,
please have a look at https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1655
Thank you

**Comment by nam31** [comment]
Closing via #1655 
Thank you
