### ISSUE TITLE
Number of attendees that can join a meeting has changed - please update this article?

### ISSUE THREAD

**Issue by scapero** [MicrosoftDocs/OfficeDocs-Support#1649]
[Enter feedback here]

**Attendee maximum for meetings capped at 250** [This is no longer what our official documentation states]
https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams

Number of people in a meeting (can chat and call in) | 1000, includes GCC but not yet for GCCH, DoD, or A1 (300). View-only allows for up to 20,000 listen-only participants to join a meeting

I would suggest linking out to that doc as well

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d83b7f29-f947-5df5-0c9c-c23ce2d886ac
* Version Independent ID: 32583d94-5a60-687f-e68e-9383afebfa8d
* Content: [Teams meetings are limited to 250 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/known-issues/teams-meetings-capped-at-250)
* Content Source: [Teams/known-issues/teams-meetings-capped-at-250.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/known-issues/teams-meetings-capped-at-250.md)
* Service: **msteams**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by MaratMussabekov** [comment]
Dear @scapero ,
please have a look at #1665.
Thank you

**Comment by nam31** [comment]
Closing via #1665 
Thank you
