### ISSUE TITLE
After upgrade Exchange 2016 RTM to CU21 the IMAP service start and stopped

### ISSUE THREAD

**Issue by Schottkey21** [MicrosoftDocs/OfficeDocs-Support#1654]
After upgrade Exchange 2016 RTM to CU21 the IMAP service started and stopped after IMAP client connects to port 143.

**Before I give the solution I would like to have some feedback about this issue, namely because I don't understand and I don't know what I'm doing it. So Please Microsft explain it.**  
Thanks in advance.

After travelling in the **WorId Wide Web** I found the following site that help me resolve this issue:
`https://nchrissos.wordpress.com/2017/01/10/reactivate-a-broken-imap-service-on-microsoft-exchange-20132016/`

**The solution is:**

**1.  List the "Offline" Healths**
```
[PS] C:\> Get-ServerHealth -Id srv01 | where { $_.CurrentHealthSetState -eq "Offline"}
Server          State           Name                 TargetResource       HealthSetName   AlertValue ServerComponent
srv01      Offline    1     ImapProxyTestMonitor MSExchangeImap4      IMAP.Proxy      Healthy    ImapProxy
srv01      Offline         PopProxyTestMonitor  MSExchangePop3       POP.Proxy       Healthy    PopProxy
```
**2. Turn OnLine the "Offline" Healths**
```
[PS] C:\> Set-ServerComponentState -id enco-srv01 -Component imapproxy -state active -Requester HealthAPI
[PS] C:\> Set-ServerComponentState -id enco-srv01 -Component popproxy -state active -Requester HealthAPI
```
**3. Wait some time**

**4. Confirm if the "Offline" Healths turned "Online"**
```
[PS] C:\> Get-ServerHealth -Id srv01 | where { $_.CurrentHealthSetState -eq "Offline"}
[PS] C:\>
<The result above should be empty>
```

**5. Restart Exchange Imap and Pop services**
```
[PS] C:\> Restart-Service MSExchangeIMAP4; Restart-Service MSExchangeIMAP4BE
[PS] C:\> Restart-Service MSExchangePOP3; Restart-Service MSExchangePOP3BE
```

**Search Keywords**
imap not working exchange 2016

**Comment by nam31** [comment]
@Schottkey21 Here we are limited to documentation issues and improvements.
The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@Schottkey21 We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
