### ISSUE TITLE
Leave a copy of the message on the server is missing in Outlook

### ISSUE THREAD

**Issue by Pravin666** [MicrosoftDocs/OfficeDocs-Support#1657]
[Microsoft mentioned that we can disable the outlook settings "leave a copy of the message on the server".But actually, This option is only available in office 2016 and it's older versions. Not for office 2019. If there any settings related to this in offfice 2019, please share the way. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e2c9702-92b1-2b20-6e27-87105570fb21
* Version Independent ID: af86d85b-f67c-ae79-6d48-f9976f69f2c1
* Content: [Leave a copy of the message on the server is missing in Outlook - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/installation/enable-leave-a-copy-of-the-message-on-the-server-outlook)
* Content Source: [Outlook/Client/Installation/enable-leave-a-copy-of-the-message-on-the-server-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/Installation/enable-leave-a-copy-of-the-message-on-the-server-outlook.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**[
![OUTLOOK LEAVE A COPY IN WEB SERVER ISSUE](https://user-images.githubusercontent.com/86899665/124371103-31983680-dc9c-11eb-99be-51c1d1ea774f.PNG)
](url)

**Comment by MaratMussabekov** [comment]
Hello @Pravin666 ,
this option is available for Pop3 accounts only, the account on your screenshot is IMAP
Thank you

**Comment by Pravin666** [comment]
> Hello @Pravin666 ,
> this option is available for Pop3 accounts only, the account on your screenshot is IMAP
> Thank you

Thanks for your clarification.
