### ISSUE TITLE
missing space in Powershell snippet

### ISSUE THREAD

**Issue by mattwaab** [MicrosoftDocs/OfficeDocs-Support#166]
Procedure item number 3's powershell snippet is missing a space between '&lt;Mailbox ID2&gt;' and '-AccessRights'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aacc4cd-e080-bbcf-5e67-6a5658114252
* Version Independent ID: a48721b6-2300-d0bf-3541-d3f29ea1d37e
* Content: [Remove automapping for a shared mailbox - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/remove-automapping-for-shared-mailbox)
* Content Source: [Microsoft365/admin/administration/remove-automapping-for-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/remove-automapping-for-shared-mailbox.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The article is updated. Thanks.
