### ISSUE TITLE
Access Error: Data on the Clipboard is damaged, so Microsoft Access can't paste it

### ISSUE THREAD

**Issue by mdoehnert** [MicrosoftDocs/OfficeDocs-Support#1669]
I get problem with Access in Office 365 too

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85483394-0194-dbb2-3261-63bdba0d0e6d
* Version Independent ID: 9770a875-4f9f-46f3-a601-5bbfa5a759da
* Content: [Unable to copy and paste from Excel into Access - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/clipboard-data-damaged?source=docs)
* Content Source: [Office/Client/access/clipboard-data-damaged.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/clipboard-data-damaged.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by MaratMussabekov** [comment]
Hello @mdoehnert ,
yes, you are correct, version newer than 2016 also have this issue.
I created a PR to update the article.
Thank you

**Comment by nam31** [comment]
Closing via #1682 
Thank you
