### ISSUE TITLE
Step 7 Cmdlet Concern

### ISSUE THREAD

**Issue by PaulRNewell** [MicrosoftDocs/OfficeDocs-Support#167]
Hi there,
I read over the document noted below (for quick reference: https://docs.microsoft.com/en-us/exchange/troubleshoot/move-mailboxes/mailbox-exists-exo-onpremises) and have a concern about the cmdlet on step 7. It notes using the parameters "RemoteHostName", "RemoteCredential", "RemoteDatabaseGuid", and "RemoteRestoreType", all of which are marked as "This parameter is reserved for internal Microsoft use." in the cmdlet documentation, which is here: https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/new-mailboxrestorerequest?view=exchange-ps

I wanted to bring it up for clarification, be it on the page I opened this issue on, or the cmdlet documentation. 

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b0eef03-98f2-0630-f331-6eedf8a98085
* Version Independent ID: 2302b229-aff5-d18d-dcb9-844a29e28728
* Content: [How to recover when a mailbox exists in both Exchange Online and on-premises - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/move-mailboxes/mailbox-exists-exo-onpremises)
* Content Source: [Exchange/ExchangeHybrid/move-mailboxes/mailbox-exists-exo-onpremises.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/move-mailboxes/mailbox-exists-exo-onpremises.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @TobyTu
* Microsoft Alias: **benwinz**

**Comment by JeremyTBradshaw** [comment]
Subscribing to this one.  I'm interested in the answer.

**Comment by bwinzenz** [comment]
Hi guys - thanks for the comment here and sorry for the delayed response. "Reserved for Microsoft Internal Use" in many cases means you should only use those cmdlet parameters under the direct supervision of someone from Microsoft Support. In this particular case our Engineering/Development team was part of the conversation. I can check whether it would be appropriate to update the Help topics for that cmdlet, but rest assured the process was tested.

**Comment by TobyTu** [comment]
@bwinzenz thanks for your sharing, you can click the **Edit** in the upper right of the article to update this article. I notice that the article was written by chrisda.  Maybe you can contact him directly.
