### ISSUE TITLE
Should mention debug log time limit

### ISSUE THREAD

**Issue by dsolodow** [MicrosoftDocs/OfficeDocs-Support#1671]
The article should probably mention that enabling ActiveSyncDebugLogging auto-disables after 48 hours for Exchange Online and 72 for on-premise. We ran afoul of this trying to run down a sporadic issue. :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6130d9d5-72f1-f6bc-c331-dd3efde61d6f
* Version Independent ID: 55d1fe0c-5327-415c-bf58-3e2cd34a5cb2
* Content: [Collect ActiveSync device logs to troubleshoot sync issues for mobile devices - Exchange](https://docs.microsoft.com/en-US/exchange/troubleshoot/mobile-devices/issues-for-mobile-devices)
* Content Source: [Exchange/ExchangeOnline/mobile-devices/issues-for-mobile-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/mobile-devices/issues-for-mobile-devices.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@dsolodow Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1674

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1674 
Thank you
