### ISSUE TITLE
Why are newer versions not included?

### ISSUE THREAD

**Issue by drichard1** [MicrosoftDocs/OfficeDocs-Support#1672]
[Enter feedback here]
This article was written in 2021 and seems to cover Excel 2013, 2021, 2007, and earlier. Are 2016 and 2019 versions not included? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14b7ee83-38f7-b9b9-5fd9-3039447e5353
* Version Independent ID: 933b6c89-ee19-ba9e-5aea-c5716fdb3584
* Content: [Use defined names to automatically update a chart range - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/defined-names-to-update-chart-range)
* Content Source: [Office/Client/excel/defined-names-to-update-chart-range.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/defined-names-to-update-chart-range.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by MaratMussabekov** [comment]
Hello @drichard1 ,
you are right, newer versions are applicable too.
I created a PR to update the article.
Thank you!

**Comment by nam31** [comment]
Closing via #1681 
Thank you
