### ISSUE TITLE
Unused variables

### ISSUE THREAD

**Issue by DiskCrasher** [MicrosoftDocs/OfficeDocs-Support#1673]
What is the purpose of this line in the sample code:

`Dim i, j As Long`

Also, on my system, some fields returned extra spaces that I had to trim off.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb5e490e-e0a5-3470-cb10-9a3e75f4a6ae
* Version Independent ID: 77e4f016-946b-82cf-d4ff-def1d6fcc6ac
* Content: [Determine who is logged on to a database - Office](https://docs.microsoft.com/en-US/office/troubleshoot/access/determine-who-is-logged-on-to-database)
* Content Source: [Office/Client/access/determine-who-is-logged-on-to-database.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/determine-who-is-logged-on-to-database.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by MaratMussabekov** [comment]
Hello @DiskCrasher ,
you are right, these variables are not used, please have a look at #1689 
Thank you

**Comment by nam31** [comment]
Closing via #1689 
Thank you
