### ISSUE TITLE
inaccurate information for finding the room finder button

### ISSUE THREAD

**Issue by DPFlint** [MicrosoftDocs/OfficeDocs-Support#1684]
Document says room finder is visible in a couple of places but does not say, to make it visible, you have to click "invite Attendees"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1b9c380-0116-3400-1d54-3ee50c924cba
* Version Independent ID: f1ad1b10-c320-61fa-2818-8dfc8b63271c
* Content: [How to control the Room Finder in Outlook - Outlook](https://docs.microsoft.com/en-US/outlook/troubleshoot/calendaring/room-finder)
* Content Source: [Outlook/Client/calendaring/room-finder.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/calendaring/room-finder.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **gabesl**

**Comment by joinimran** [comment]
Hi @DPFlint , thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by nam31** [comment]
@DPFlint we are going to close this issue as the article has been updated accordingly. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
