### ISSUE TITLE
Is the information from that page outdated?

### ISSUE THREAD

**Issue by TobiasAT** [MicrosoftDocs/OfficeDocs-Support#1686]
Hello, it's a strange question but I have to ask. Is this support page really true or just a nice post?
Recently I opened a Microsoft support case why the function described in the help is not available in my tenant. 

A summarization about my tenant: 

- The affected OneDrive has 4.7 TB = more than 90%.
- My tenant has 25 Microsoft E5 licenses. 
- Based on the previous points my tenant should be qualified to follow the description in the help. 

I start the diagnostic (point 4) and get no option like in point 5. I get the information "Your tenant is not configured to increase a user's OneDrive quota beyond 5TB" and to open a support case. I did it and my question to the support was is this function not enabled for all tenants, or what should I do so that I can also use this function? The answer from the support agent is "This is by design since it acquires space at the server end. And hence the threshold is kept 5TB once reached the admins need to raise support request."

Either the information from this page is outdated or the support agent has wrong information. Please give me some advise what is true, how this option can be configured and why this option is not available in all qualified tenants? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcd9e2ca-403b-989a-e38c-27b81a03a32c
* Version Independent ID: 6c03204c-9e52-4f92-e33b-adf7a394a6bb
* Content: [Check OneDrive site eligibility for increased storage - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/storage/check-storage-increase-eligibility)
* Content Source: [SharePoint/OneDrive/storage/check-storage-increase-eligibility.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/OneDrive/storage/check-storage-increase-eligibility.md)
* Service: **one-drive**
* GitHub Login: @v-matham
* Microsoft Alias: **v-matham**

**Comment by joinimran** [comment]
Hi @TobiasAT, thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by TobiasAT** [comment]
Hello @joinimran, unfortunately your support still has no clue about step 5. Is step 5 currently a general bug in your system?

**Comment by TobiasAT** [comment]
Hello @joinimran, still waiting for an update, and still the same topic with support.

**Comment by joinimran** [comment]
@TobiasAT - Did you get a chance to manually open a support case with Microsoft for the increase of storage?

**Comment by TobiasAT** [comment]
@joinimran Yes, the question is why a case is required if your step 5 has different information? My support case is primary to solve why step 5 is not working, but your support team has still no clue about this help article. Is the way with step 5 not working for all tenants, and why not?

**Comment by joinimran** [comment]
@TobiasAT - I have also tried this and I was also having the same issue. Keeping this in mind, I will suggest a change in the document author to see how it goes. 

Thanks.

**Comment by helenclu** [comment]
@TobiasAT , could you send me an email?

**Comment by TobiasAT** [comment]
@helenclu As mentioned in my email the cause is step 5 is not available in developer or MSDN tenants. The documentation should be updated with the information.
