### ISSUE TITLE
Sync/publish time longer then 1 hour

### ISSUE THREAD

**Issue by PerplexMarc** [MicrosoftDocs/OfficeDocs-Support#1688]
the article contains the following text
_In some environments, it may take an hour for the OAuth certificate to be published. If you have a hybrid setup, you have to run the Hybrid Configuration Wizard again to update the changes to Azure Active Directory (Azure AD)._

But it can take several hours to sync. It might be useful to adjust this. This is confirmed on various forums.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18a6f2e-2e68-51d2-b1e7-1e3a15073238
* Version Independent ID: 0b637e4f-aaac-9ea1-4e17-2b1ac500a868
* Content: [Can't access OWA/EAC with expired OAuth certificate - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/cannot-access-owa-or-ecp-if-oauth-expired#resolution)
* Content Source: [Exchange/ExchangeServer/administration/cannot-access-owa-or-ecp-if-oauth-expired.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/administration/cannot-access-owa-or-ecp-if-oauth-expired.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello @PerplexMarc ,
yes, it seems to be related to timezone issue https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1693
Set-AuthConfig accepts time in local timezone, and then processes it in UTC timezone, so everyone to the east from UTC will have a time gap.
Thank you

**Comment by nam31** [comment]
@PerplexMarc @ Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
