### ISSUE TITLE
NPAPI not supported by Chrome

### ISSUE THREAD

**Issue by EvaGilszki** [MicrosoftDocs/OfficeDocs-Support#169]
NPAPI is not supported by Chrome at all anymore, so please update this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62e22224-64c1-ea10-101b-c6ba96c9c1fd
* Version Independent ID: 4bc021f0-7050-4c66-16d9-0f11961e3284
* Content: [Client does not start when click a meeting link if default browser is Chrome - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/server-sign-in/client-not-start-click-meeting-link#feedback)
* Content Source: [SkypeforBusiness/SkypeServer/server-sign-in/client-not-start-click-meeting-link.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeServer/server-sign-in/client-not-start-click-meeting-link.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Article is updated as NPAPI is not supported by Chrome.
