### ISSUE TITLE
Additional information

### ISSUE THREAD

**Issue by DanGuzman450** [MicrosoftDocs/OfficeDocs-Support#1690]
When including the changing of the setting in the "Current Database", you should mention that the option is only available in new MS Access databases.  Once tables have been added, this option is no longer available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c4635a6-1d2b-3155-a2a7-625958332caa
* Version Independent ID: 1f689b25-968f-8e6f-3eb7-e6b05d295340
* Content: [Access linked table to SQL Server database returns Deleted - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/access-linked-table-deleted)
* Content Source: [Office/Client/access/access-linked-table-deleted.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/access-linked-table-deleted.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by MaratMussabekov** [comment]
Hello @DanGuzman450 ,
could you please provide the source of this information?
I tried on version 2106, and I am able to change this setting after adding the table.
Thank you

**Comment by DanGuzman450** [comment]
Personal experience, in both MS Access 2016 and 365. Long integer type option is there, higher precision dates is not.  This screenshot is 365:
![image](https://user-images.githubusercontent.com/47125539/126961459-a67b15cf-3ed9-4f74-aaf4-940d68cb363d.png)
Here is the same db in 2016:
![image](https://user-images.githubusercontent.com/47125539/126964453-2cb9eebc-a176-4f5a-b4ae-2232335674a0.png)

**Comment by MaratMussabekov** [comment]
Hello @DanGuzman450 ,
article says about DateTime2 data type, not about BigInt. It was added in the latest versions of MS Office. Try to update your office to the latest version, and this option will appear. Here what I see in version 2106:
![изображение](https://user-images.githubusercontent.com/48041687/127104806-b6a43825-a590-4d18-b3ba-1c8566e2bd26.png)

Thank you

**Comment by DanGuzman450** [comment]
My second image is from 2016, with latest updates.  I only see your highlighted box on brand new databases, no tables.  Once I've added one linked table, that option goes away, thus my comment.

**Comment by MaratMussabekov** [comment]
Hello,
**My second image is from 2016, with latest updates. I only see your highlighted box on brand new databases, no tables.** - not sure how it is possible. DateTime2 data type is not supported by Access 2016 at all.
![image](https://user-images.githubusercontent.com/48041687/127610707-58dd9ab9-ae93-43f1-9d50-54a8c55eca62.png)
Tried on Access 2016 and 2019, do not see this option, as it is described in the article.
I see it only in Access for Microsoft 365 and do not experience any issue with changing this option after adding the table.
**Once I've added one linked table, that option goes away** - May be the linked table is incompatible with DateTime2 format?
Thank you

**Comment by nam31** [comment]
@

**Comment by nam31** [comment]
@DanGuzman450  Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
