### ISSUE TITLE
Format of CSV file isn't correct error when an Office 365 user tries to import contacts

### ISSUE THREAD

**Issue by tainium** [MicrosoftDocs/OfficeDocs-Support#1692]
Solution doesn't work for me.  No diagnostic data is provided by the Microsoft interface to troubleshoot the issue.

https://docs.microsoft.com/en-us/office365/troubleshoot/administration/format-of-the-csv-file-not-correct-error-when-importing-contacts
"The format of the CSV file isn't correct. Be sure that the file was exported in the Outlook CSV Format"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8563627-80ef-0f18-79c5-2e4dd9fd00c3
* Version Independent ID: 4492ed2b-0bd7-3271-69b9-612fb01684c2
* Content: [Format of the CSV file isn't correct error - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/format-of-the-csv-file-not-correct-error-when-importing-contacts)
* Content Source: [Microsoft365/enterprise/administration/format-of-the-csv-file-not-correct-error-when-importing-contacts.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/enterprise/administration/format-of-the-csv-file-not-correct-error-when-importing-contacts.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by msbemba** [comment]
@tainium Thank you for your feedback. There are no diagnostics data provided as it only accepts without trailing spaces. Could you please test again with just one row(without trailing spaces) and verify if the problem persists.

Thanks
Sri

**Comment by msbemba** [comment]
@tainium Just circling back to see if you were able to upload the file now or does the issue still persists.

Thanks
Sri

**Comment by tainium** [comment]
Hi, I went a different route.  Used a Windows machine to manually import the data and then re-exported it.  The re-exported data was then compatible.

**Comment by nam31** [comment]
@tainium Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
