### ISSUE TITLE
-NewCertificateEffectiveDate (Get-Date) does not take time zone into account

### ISSUE THREAD

**Issue by Gindi4711** [MicrosoftDocs/OfficeDocs-Support#1693]
The following command does not take time zone into account:
Set-AuthConfig -NewCertificateThumbprint <ThumbprintFromStep1> -NewCertificateEffectiveDate (Get-Date)

The solution still works, but it needs additional up to 12 hours (depending on time zone) of downtime

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18a6f2e-2e68-51d2-b1e7-1e3a15073238
* Version Independent ID: 0b637e4f-aaac-9ea1-4e17-2b1ac500a868
* Content: [Can't access OWA/EAC with expired OAuth certificate - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/cannot-access-owa-or-ecp-if-oauth-expired)
* Content Source: [Exchange/ExchangeServer/administration/cannot-access-owa-or-ecp-if-oauth-expired.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/administration/cannot-access-owa-or-ecp-if-oauth-expired.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello @Gindi4711 ,
yes, you are correct.
no matter what you try, it always use UTC.
I even tried to use `(Get-Date).AddHours(-[String](Get-TimeZone).BaseUTCOffset.Hours)` to remove the gap between my timezone and UTC, and I got the error the effective date must be greater than the current time.
![image](https://user-images.githubusercontent.com/48041687/127115226-a32268bc-a641-4629-9e11-f4cefd9a8e80.png)

So I assume that Set-AuthConfig accepts time in local timezone, while processes it in UTC timezone. The only working workaround is to change local timezone to UTC and then turn it back.

Thank you

**Comment by nam31** [comment]
@Gindi4711 @ Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
