### ISSUE TITLE
Clicking on Notifications from Chat messages sent by Bots do not open in Chat Tab on Teams Desktop client

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/OfficeDocs-Support#1697]
There appears to have been a recent breaking change (last few weeks ~possibly April/May 2021) where when a desktop teams client user clicks on a notification sent by a Teams chat bot (built using Microsoft Bot Framework), it does not open the actual chat pane with the sending bot contact.  Teams client instead opens in the "Feed"/Activity Pane of the Teams client and the use must manually navigate to the Chat pane in the left navigation rail to find the message that triggered the notification.

(This used to work fine earlier for several years as our chat bot has been in use that long)

Expected behaviour is that  if there is a notification of a text message sent from a chatbot, when a user clicks on the notification, it should take the user directly to the chat pane of the bot , retaining the focus on the chat pane in the navigation rail (and not switch focus to Feed/Activity Tab and lose the context)

(Have not tested on non-Windows Desktop clients as Windows Desktop is the main use case)

**Comment by nam31** [comment]
@GauravES The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
