### ISSUE TITLE
Office 365 does not appear in the list of programs, so it can't be selected to repair it.

### ISSUE THREAD

**Issue by BROnstott** [MicrosoftDocs/OfficeDocs-Support#1698]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00046333-d516-67e3-ad57-abc0c37b2b35
* Version Independent ID: a48d6248-4a5a-4b38-f358-b35de1a8ee1c
* Content: [Repair process does not start for Office Click-to-Run application - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/click-to-run-app-repair-process)
* Content Source: [Office/Client/office-suite-issues/click-to-run-app-repair-process.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/click-to-run-app-repair-process.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by RAJU2529** [comment]
@BROnstott. To repair Microsoft   365 suite  , you can use the SARA tool from the Microsoft site, you can download it from below site
**https://outlookdiagnostics.azureedge.net/sarasetup/SetupProd_ExpExp.exe**

**Comment by msbemba** [comment]
@BROnstott Thank you for your feedback. If the application is not listed, then you can use the Microsoft SARA tool to repair as it is most likely corrupted or access Portal.office.com and install the suite again.

Hope this helps!
Thanks
Sri

**Comment by msbemba** [comment]
@BROnstott Just circling back to check if you still have any issues repairing office.

Thanks
Sri

**Comment by nam31** [comment]
@BROnstott We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
