### ISSUE TITLE
Onedrive hangs during signin for 1 hour after changing the tlsciphersuite

### ISSUE THREAD

**Issue by L0nnny** [MicrosoftDocs/OfficeDocs-Support#1703]
[Enter feedback here]
Preface:
All machines are managed by Intune and run W10 21h1 Enterprise.
I could not perform Solution 3 because this is a remote worker.
The settings of Solution 2 were already configured correctly.

Affected laptop is unable to sign in to Onedrive 
I noticed that the affected laptop had very outdated TLScipersuites  compared to my working machine.
So I tried Solution 1: Check cipher suites settings and added the recommended tlsciphersuites to the affected laptop.
After reboot the machine still hangs during onedrive login for 1 hour. After that the the user is logged in.
But after rebooting you have the same issue of Onedrive hanging during logon
The user does experience any other problems with other applications

Also after that change I saw a lot of event logs messages.
A fatal error occurred while creating a TLS client credential. The internal error state is 10013
So i compared my tlsciphersuites  on my machine with the affected device. and I noticed they were very old and different.

Affected machine
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384_P384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P256
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384_P384
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA_P384
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA_P256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P384
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P256
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256_P256
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA_P384
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA_P256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA_P384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA_P256
TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
TLS_DHE_DSS_WITH_AES_256_CBC_SHA
TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
TLS_DHE_DSS_WITH_AES_128_CBC_SHA
TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA
TLS_RSA_WITH_AES_256_CBC_SHA256
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_AES_128_CBC_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_RC4_128_SHA
TLS_RSA_WITH_3DES_EDE_CBC_SHA
TLS_RSA_WITH_RC4_128_MD5
SSL_CK_RC4_128_WITH_MD5
SSL_CK_DES_192_EDE3_CBC_WITH_MD

Not affected machine
(Get-TlsCipherSuite ).name
TLS_AES_256_GCM_SHA384
TLS_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_256_GCM_SHA384
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_256_CBC_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA256
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_3DES_EDE_CBC_SHA
TLS_RSA_WITH_NULL_SHA256
TLS_RSA_WITH_NULL_SHA
TLS_PSK_WITH_AES_256_GCM_SHA384
TLS_PSK_WITH_AES_128_GCM_SHA256
TLS_PSK_WITH_AES_256_CBC_SHA384
TLS_PSK_WITH_AES_128_CBC_SHA256
TLS_PSK_WITH_NULL_SHA384
TLS_PSK_WITH_NULL_SHA256

Is there a way to get onedrive working on the affected device without reinstalling W10
Reseting, Removing, Reinstalling Onedrive did not solve the issue

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c329eb0b-4792-e585-f387-a77ae3786e0d
* Version Independent ID: 043ae1c6-00ff-a67b-7605-86c74bd2df45
* Content: [Error Code 0x8004de40 when signing in to OneDrive - SharePoint](https://docs.microsoft.com/en-sg/sharepoint/troubleshoot/administration/error-0x8004de40-in-onedrive)
* Content Source: [SharePoint/OneDrive/administration/error-0x8004de40-in-onedrive.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/OneDrive/administration/error-0x8004de40-in-onedrive.md)
* Service: **one-drive**
* GitHub Login: @salarson
* Microsoft Alias: **v-matham**

**Comment by nam31** [comment]
@L0nnny The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content ?
Thank you.

**Comment by L0nnny** [comment]
@nam31 
If you're asking if there are factual errors in the article listed then I would probably say NO.
However my feedback is that the steps in the article did not resolve the issue that we have on multiple devices.
Thank you.

**Comment by L0nnny** [comment]
@salarson  
I did not, but I will raise a support ticket as suggested
Thanks

**Comment by nam31** [comment]
@L0nnny The best way to get your issue resolved is to contact Microsoft Support. 
If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 
Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
