### ISSUE TITLE
Missed link

### ISSUE THREAD

**Issue by Alex-Glebov** [MicrosoftDocs/OfficeDocs-Support#1704]
There is missed reference to the article "...to open database in Enabled mode" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d4dd9b0-5e6c-b2f3-fa62-7a204c0832eb
* Version Independent ID: 654489ba-fe5f-73f9-54fe-3fc42a57e747
* Content: [Database's user-defined function isn't displayed - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/user-defined-function-fail-displayed)
* Content Source: [Office/Client/access/user-defined-function-fail-displayed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/user-defined-function-fail-displayed.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by MaratMussabekov** [comment]
Hello @Alex-Glebov ,
please have a look at #1722
Thank you

**Comment by nam31** [comment]
Closing via #1722 
Thank you
