### ISSUE TITLE
WHY DOESN'T WORD GIVE GOOD ERROR MESSAGES?

### ISSUE THREAD

**Issue by pfc-akorda** [MicrosoftDocs/OfficeDocs-Support#1705]
[Enter feedback here]
When a word document opens with errors it should give detailed errors so that the creating application can have a proper report filed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b95df2f-e3de-e2d1-b48a-3fcd4183463f
* Version Independent ID: 397150eb-b8e0-62c0-55b9-c5277aacb5dd
* Content: [How to troubleshoot damaged documents in Word - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/damaged-documents-in-word)
* Content Source: [Office/Client/word/damaged-documents-in-word.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/damaged-documents-in-word.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by RAJU2529** [comment]
@pfc-akorda , Pease write feedback about suggestions in this case through feedback hub application.

**Comment by nam31** [comment]
@pfc-akorda Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
