### ISSUE TITLE
Cannot move a meeting between calendars: a solution

### ISSUE THREAD

**Issue by AlexisEspinosaGayosso** [MicrosoftDocs/OfficeDocs-Support#1707]
[Enter feedback here]
I found a good solution: right click the meeting and forward it to the account that manages the calendar on which you want to move the meeting. Then, the meeting entry will appear in the preferred calendar. Finally, re-accept the meeting within the preferred calendar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0225229b-5cc7-b648-817e-3c63a790cfaf
* Version Independent ID: e08f89d6-faa9-f89c-b5d2-32eae843bd11
* Content: [Cannot move a meeting between calendars - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/calendars/cannot-move-meetings-between-calendars)
* Content Source: [Outlook/Mac/calendars/cannot-move-meetings-between-calendars.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Mac/calendars/cannot-move-meetings-between-calendars.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@AlexisEspinosaGayosso Thank you for your feedback. I have added this workaround to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1723

Once the author approves the PR, the document will be live.

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1723 
Thank you
