### ISSUE TITLE
Really Microsoft?!? have you read your own 'workarounds'? Do you understand where people use Teams for?

### ISSUE THREAD

**Issue by raymondwigmore** [MicrosoftDocs/OfficeDocs-Support#1708]
[Enter feedback here]

The workarounds in this document make me cry and laugh at the same time.....
turn of your video; disconnect your monitor, switch everything else of, kill all other programs.... It seems like Microsoft doesn't even understand it's own application, or what it is used for.... A tragic joke, that's what this is....
I have another workaround; don't use teams :-) when you have a laptop and an external monitor.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df6fe49-939e-8330-07a1-49ff0a2c4ab7
* Version Independent ID: f7cc79e9-6e2a-17a4-36ec-743acc0d679a
* Content: [Teams is slow during video meetings on laptops docked to 4K/UHD monitors - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/known-issues/teams-slow-video-meetings-laptops-4k)
* Content Source: [Teams/known-issues/teams-slow-video-meetings-laptops-4k.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/known-issues/teams-slow-video-meetings-laptops-4k.md)
* Service: **msteams**
* GitHub Login: @helenclu
* Microsoft Alias: **sgorantl**

**Comment by nam31** [comment]
@raymondwigmore Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
