### ISSUE TITLE
Office365 - Outlook - Current time zone - not dynamic tracking with local-browser TZ

### ISSUE THREAD

**Issue by smallscript** [MicrosoftDocs/OfficeDocs-Support#171]
The `https://outlook.office.com/calendar/view/day` PWA/App uses "Settings/Current time zone" as a hard-coded value no matter where I am, or what device I am using (including laptop).

This has caused me no-end of troubles when traveling to/from locations like Seattle to Salt Lake City.

Unless I remember to switch while traveling I get dates/times for meetings confused and wrong because of the CST to PST 1 hour difference. This has also bitten many of my co-workers.

Why is there not an option in "Settings/Current time zone" to use "local-browser" time?

**Comment by nam31** [comment]
@smallscript The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content
Thank you.

**Comment by nam31** [comment]
@smallscript We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.

**Comment by smallscript** [comment]
Where is the CORRECT place to FILE the above BUG?
