### ISSUE TITLE
Changing the path does not work

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/OfficeDocs-Support#1716]
As of today, neither of these options work. I've just tried it with Microsoft® Outlook® for Microsoft 365 MSO (16.0.14228.20200) 32-bit .

If you can confirm, then set this article to archive if this feature is being deprecated. No use in having a published article with incorrect information.
I tried method 1 and the option to browse is disabled.
I tried method 2 and the new profile attempted to load but then failed because the folders we inaccessible.

Again, neither option works which makes the article ineffective and inaccurate.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aab602f-f37c-85a1-a063-e2dc70081071
* Version Independent ID: 02bd6670-9886-7ebc-2f2b-048f352d3a37
* Content: [Cannot change the location of .ost file - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/data-files/cannot-change-the-location-of-ost-file)
* Content Source: [Outlook/Client/data-files/cannot-change-the-location-of-ost-file.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/data-files/cannot-change-the-location-of-ost-file.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@Jmartinez589 Thank you for your feedback. I was able to test both the methods on Outlook 2016 and 2019 C2R versions. We are here to take your feedback and improve docs.microsoft.com, but we cannot provide you support. If you still have problems I have to suggest you that open a support ticket.
If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in the future .

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@Jmartinez589 Just circling back to check if you were able to open a service ticket.

Thanks
Sri

**Comment by nam31** [comment]
@Jmartinez589 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
