### ISSUE TITLE
Additional fix for <Unknown> in nested contact group preventing expanding group

### ISSUE THREAD

**Issue by molsen222** [MicrosoftDocs/OfficeDocs-Support#1718]
The issue provided on the article shows marking "Show this folder as an email address book" as the resolution. However, this will not resolve all occurrences of the problem. 

I have found that if you open the group in question and select 'update now' option it will show that there are members that cannot be found. If you select 'Try to repair the lost members and remove only those that cannot be resolved' it will fix the issue. I have also noticed this has not actually removed any members in the 10+ times I have used this fix. Likely there is a bug that removes members of this group but somewhere there is reference to them which is causing the problem. 

Picture of options for reference
![image](https://user-images.githubusercontent.com/16551983/128080492-eee35b81-48bd-433d-8498-389749808330.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cf41b3d-1f09-0dfd-7a66-f7c9dbf3ed9a
* Version Independent ID: b465a742-8eae-c58c-e92d-22d0864641c1
* Content: [Unknown is shown in group name when expanding - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/contacts/cannot-expand-nested-contact-groups-unknown-shown)
* Content Source: [Outlook/Client/contacts/cannot-expand-nested-contact-groups-unknown-shown.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/contacts/cannot-expand-nested-contact-groups-unknown-shown.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@molsen222 Thank you for your feedback. The document has been updated via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1726

Once the author approves the PR, the document will be live.
Thanks
Sri

**Comment by nam31** [comment]
Closing via #1726 
Thank you
