### ISSUE TITLE
ensure-that-the-required-attribute-synchronized - information missing step 2

### ISSUE THREAD

**Issue by robin-martin** [MicrosoftDocs/OfficeDocs-Support#1719]
https://docs.microsoft.com/en-us/exchange/troubleshoot/move-or-migrate-mailboxes/troubleshoot-migration-issues-in-exchange-hybrid#ensure-that-the-required-attribute-synchronized-properly-this-is-not-a-common-problem

Under this heading, step 2 says to run a cmdlet but nothing is listed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2177a0d-960e-912e-5020-6e5e62543029
* Version Independent ID: 789e584d-7e81-f5ca-a175-e727875dc665
* Content: [Troubleshoot migration issues in Exchange hybrid - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/move-or-migrate-mailboxes/troubleshoot-migration-issues-in-exchange-hybrid)
* Content Source: [Exchange/ExchangeOnline/move-or-migrate-mailboxes/troubleshoot-migration-issues-in-exchange-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/move-or-migrate-mailboxes/troubleshoot-migration-issues-in-exchange-hybrid.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello @robin-martin ,
please have a look at #1721
Thank you

**Comment by nam31** [comment]
Closing via #1721 
Thank you
