### ISSUE TITLE
Skype for Business 2016 Product ID not listed

### ISSUE THREAD

**Issue by scabrera-aeroterra** [MicrosoftDocs/OfficeDocs-Support#172]
The product ID for Skype for Business 2016 is not listed for the ODT. I need this to create an xml to remove SFB2016. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b0e3f06-bd25-2d92-228b-9b5e1cf47ff3
* Version Independent ID: c8a6ff08-5acf-adcb-855f-5eadce72f7ba
* Content: [Product IDs that are supported by the Office Deployment Tool for Click-to-Run - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/product-ids-supported-office-deployment-click-to-run#feedback)
* Content Source: [Microsoft365/admin/administration/product-ids-supported-office-deployment-click-to-run.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/product-ids-supported-office-deployment-click-to-run.md)
* Service: **o365-solutions**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **stevhord**

**Comment by stdin82** [comment]
SkypeforBusinessRetail = Skype for Business 2016

**Comment by nam31** [comment]
@scabrera-aeroterra we are going to close this issue as the article has been updated accordingly. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
