### ISSUE TITLE
Update Outlook 2016 implementation of Autodiscover

### ISSUE THREAD

**Issue by Raymoncorrea** [MicrosoftDocs/OfficeDocs-Support#1720]
[Enter feedback here]

The Outlook 2016 implementation of Autodiscover document, can this be updated with the details mentioned in this article? 

"It is recommended that users force Outlook to use Modern Authentication by setting the DWORD value of the following registry key to 1:
HKEY_CURRENT_USER\Software\Microsoft\Exchange\AlwaysUseMSOAuthForAutoDiscover"

https://support.microsoft.com/en-us/topic/outlook-2016-implementation-of-autodiscover-0d7b2709-958a-7249-1c87-434d257b9087

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cf82aad-5a93-fa3c-4be9-3481fd55c4a3
* Version Independent ID: 996a07a7-6c2c-2719-9363-6a1cdc94d80d
* Content: [Outlook prompts for password when Modern Authentication is enabled - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/authentication/outlook-prompt-password-modern-authentication-enabled)
* Content Source: [Outlook/Client/authentication/outlook-prompt-password-modern-authentication-enabled.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/authentication/outlook-prompt-password-modern-authentication-enabled.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@Raymoncorrea Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1725

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1725 
Thank you
