### ISSUE TITLE
Disable GPU acceleration should be "checked" not "unchecked"

### ISSUE THREAD

**Issue by dtriana** [MicrosoftDocs/OfficeDocs-Support#1728]
For the "disable GPU acceleration" workaround, the article says make sure ... option is unchecked. Should be the opposite, checked

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df6fe49-939e-8330-07a1-49ff0a2c4ab7
* Version Independent ID: f7cc79e9-6e2a-17a4-36ec-743acc0d679a
* Content: [Teams is slow during video meetings on laptops docked to 4K/UHD monitors - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/known-issues/teams-slow-video-meetings-laptops-4k)
* Content Source: [Teams/known-issues/teams-slow-video-meetings-laptops-4k.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/known-issues/teams-slow-video-meetings-laptops-4k.md)
* Service: **msteams**
* GitHub Login: @helenclu
* Microsoft Alias: **sgorantl**

**Comment by nam31** [comment]
Closing via #1729 
Thank you
