### ISSUE TITLE
Outlook 2019 for Mac (iMac Outbox issue)

### ISSUE THREAD

**Issue by tribbletron** [MicrosoftDocs/OfficeDocs-Support#1731]
Hi Microsoft, please investigate the impact of a user with a 45GB Mail Usage on a 50GB size limit that's using Outlook 2019 for Mac. In our case, we noticed Outlook 2019 for Mac has difficulty syncing with the inbox of our Marketing VP. And after checking that the Outlook program was up-to-date, network connectivity is OK, and iMac has lots of storage space... the other possibilities are the mailbox size or the amount of SharedInboxes she has access to.

- Jenny Ng (jng@mcny.org)
- Technical Support Analyst at the Museum of the City of New York

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 255b5732-ef8a-f040-4cde-d9fc40486764
* Version Independent ID: 053a2e2a-d7a1-2562-8d83-b65263c6ec92
* Content: [Email messages are stuck in Outbox in Outlook 2016 for Mac - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/send-receive-emails/email-stuck-in-outbox-outlook-2016-mac)
* Content Source: [Outlook/Mac/send-receive-emails/email-stuck-in-outbox-outlook-2016-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Mac/send-receive-emails/email-stuck-in-outbox-outlook-2016-mac.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@tribbletron Just circling back to see if you were able to contact Microsoft support for this issue.

Thanks
Sri

**Comment by nam31** [comment]
@tribbletron We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
