### ISSUE TITLE
group form guide issue.

### ISSUE THREAD

**Issue by jrummer** [MicrosoftDocs/OfficeDocs-Support#1733]
[Enter feedback here]
i think this guide makes some assumptions about the type of group used to create the form.  i used a Teams created group to create a form and there's no email box created for that group, from what i can tell.  please update this guide specifying exactly the type of group this is geared for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae5837d9-04a2-ffb7-19f4-1b6538cd7630
* Version Independent ID: 97de6157-49d3-99e6-91a5-6d669b95cd90
* Content: [No email notifications for responses to Group Forms - Office](https://docs.microsoft.com/en-us/office/troubleshoot/microsoft-forms/no-email-notifications-for-responses-to-group-forms)
* Content Source: [Office/OfficeExperts/microsoft-forms/no-email-notifications-for-responses-to-group-forms.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/microsoft-forms/no-email-notifications-for-responses-to-group-forms.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **zakirh**

**Comment by MaratMussabekov** [comment]
Hello @jrummer ,
**i think this guide makes some assumptions about the type of group used to create the form** - the only type of groups that could be used for forms is Microsoft 365 Groups
**i used a Teams created group to create a form and there's no email box created for that group** - it doesn't matter how group was created, it always has a mailbox.
If you see some message like "We couldn't find a mailbox for this account. Either they don't have a mailbox or don't have a license assigned." it means that account of the user that tries to edit Form doesn't have Exchange Online mailbox.
Thank you

**Comment by nam31** [comment]
@jrummer We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
