### ISSUE TITLE
Mysterious Parameter

### ISSUE THREAD

**Issue by BeginTry** [MicrosoftDocs/OfficeDocs-Support#1734]
In the code for [Method 1](https://docs.microsoft.com/en-us/office/troubleshoot/access/create-dsn-less-connection-linkted-table#method-1-use-the-createtabledef-method), the second parameter to the CreateTableDef method (_dbAttachSavePWD_) is not explained. There is nothing in the VBA code to demonstrate how its value is set or what the value is. Omitting that parameter from the method results in the following error:

> Run-time error '3264'
> 
> No field defined--cannot append TableDef or Index.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c40ffdb2-b91d-d76a-3a27-ffb4846cfc24
* Version Independent ID: 1ea977c8-eabd-9cd3-5514-cc6b3752a432
* Content: [Create DSN-less connection to SQL for linked table - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/create-dsn-less-connection-linkted-table)
* Content Source: [Office/Client/access/create-dsn-less-connection-linkted-table.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/create-dsn-less-connection-linkted-table.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by MaratMussabekov** [comment]
Hello @BeginTry ,
please have a look at https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1741
Thank you

**Comment by nam31** [comment]
Closing via #1741 
Thank you
