### ISSUE TITLE
Single quote used in email addresses

### ISSUE THREAD

**Issue by yvesst-cyr** [MicrosoftDocs/OfficeDocs-Support#1736]
After testing using single quotes in email addresses, AD Connect did not interfere at all. The data synchronized as per expectations.  I am somewhat surprised that your article is saying that single quotes are considered special characters in an email address when this article says otherwise.

https://docs.microsoft.com/en-gb/microsoft-365/enterprise/prepare-for-directory-synchronization?redirectSourcePath=%252farticle%252fPrepare-to-provision-users-through-directory-synchronization-to-Office-365-01920974-9e6f-4331-a370-13aea4e82b3e&view=o365-worldwide

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0638257c-2829-38a7-6bd7-799b96ca8761
* Version Independent ID: 051d257b-e558-7dce-3714-c70fd56eecaa
* Content: [Office 365 email address contains underscore character - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/active-directory/email-address-contain-underscore)
* Content Source: [Microsoft365/admin/active-directory/email-address-contain-underscore.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/active-directory/email-address-contain-underscore.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by MaratMussabekov** [comment]
the same is for "&" symbol.
Synchronized without any problem.

**Comment by MaratMussabekov** [comment]
Hello @yvesst-cyr ,
have a look at #1750 
Thank you

**Comment by nam31** [comment]
Closing via #1750 
Thank you
