### ISSUE TITLE
Adding new step to Troubleshoot the Teams presence issue section

### ISSUE THREAD

**Issue by joaolloureiro** [MicrosoftDocs/OfficeDocs-Support#1738]
Please add step below (as step 2) into 'Troubleshoot the Teams presence issue' section.

Please ping me (joaol@microsoft.com) so i can provide image contents referenced below:

#### Step 2: Verify that the Teams Presence Based on Calendar Events test is successful

1. Ask the user to go to the [Microsoft Remote Connectivity Analyzer](https://testconnectivity.microsoft.com/tests/TeamsCalendarPresence/input).
2. Input the requested information.
3. Select the **Perform Test** button to start the Teams Presence Based on Calendar Events test.

If the test fails, you should attempt to resolve the issue and rerun the test.

:::image type="content" source="media/teams-exchange-interaction-issue/presence-test.png" alt-text="Screenshot of testing calendar":::

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b88a6c5-1b3e-88df-c08d-046f69974039
* Version Independent ID: 531fedcc-8032-fbb2-e41a-9fdaa00b1cde
* Content: [Troubleshoot Microsoft Teams and Exchange Server interaction issues - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/exchange-integration/teams-exchange-interaction-issue)
* Content Source: [Teams/exchange-integration/teams-exchange-interaction-issue.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/exchange-integration/teams-exchange-interaction-issue.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @helenclu
* Microsoft Alias: **chunlli**

**Comment by MaratMussabekov** [comment]
Hello @joaolloureiro ,
could you please provide the mentioned screenshot?
I want to create a PR to fix this issue.
Thank you

**Comment by joaolloureiro** [comment]
![image](https://user-images.githubusercontent.com/41290695/129972823-724fb22e-0580-4ed4-a9e3-58e175d04898.JPG)
Hello @MaratMussabekov 

Image attached. This is a print screen of https://testconnectivity.microsoft.com/tests/teams

Thank you

**Comment by MaratMussabekov** [comment]
Hello @joaolloureiro ,
please have a look at #1759
I changed the screenshot and added some minor changes to the text.
Thank you

**Comment by nam31** [comment]
Closing via #1759 
Thank you
