### ISSUE TITLE
Missleading with scenarios

### ISSUE THREAD

**Issue by voutit** [MicrosoftDocs/OfficeDocs-Support#174]
Your O365 Support has told me that the scenario "Your organization has to send messages from the email server in your on-premises environment from domains that your organization hasn't added to Office 365" is not doable even with the mentioned resolution; configuring certificate-based connector. Only the forwarding scenario works.
If this is correct information you should mention it on this article before your customers go ahead and buy expenseive SAN certificates for nothing really.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e7a3118-66aa-6e42-43fa-e7af0abb087a
* Version Independent ID: 6c48ff6f-c50f-4a02-faf0-0278e71bcc3d
* Content: [Important notice for Office 365 email customers who have configured connectors - Exchange](https://docs.microsoft.com/en-gb/exchange/troubleshoot/connectors/office-365-notice#feedback)
* Content Source: [Exchange/ExchangeOnline/connectors/office-365-notice.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/connectors/office-365-notice.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello @voutit ,
it is already stated in the article that the scenario is not supported. It never says that if you use certificate-based connector you will be able to send emails from domain which ownership you cannot prove.
Thank you

**Comment by nam31** [comment]
@voutit Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
