### ISSUE TITLE
Another reason for this error message

### ISSUE THREAD

**Issue by tknaller** [MicrosoftDocs/OfficeDocs-Support#1743]
I've been biting my teeth out on that exact error message for 3 days at a customer and the solution explained in this article was not applicable. Attempts to solve this with Office 365 Support were also unsuccessful.

Today the solution came: the UserPrincipalName of the Remote Credentials (entered as DOMAIN\sAMAccountName) was invalid, it was something along the lines of "HTTP/servername@domain", probably because of an unsuccessful attempt to configure a Service Principal Name for Kerberos Delegation for some service long in the past.

As soon as the UserPrincipalName was changed to sAMAccountName@domain it immediately started working like a charm.

Please revise this document and add this as a second possible solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc9b67a4-0837-5c70-0ca5-da21f9275dd2
* Version Independent ID: 5f270ddb-9395-6c3c-14f1-a7d5f5a82c23
* Content: [Access is denied error when moving mailboxes - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/move-mailboxes/access-is-denied-error-when-moving-mailboxes)
* Content Source: [Exchange/ExchangeHybrid/move-mailboxes/access-is-denied-error-when-moving-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/move-mailboxes/access-is-denied-error-when-moving-mailboxes.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@nam31 looking into it.
