### ISSUE TITLE
Problems with Internet-Calendar in Outlook

### ISSUE THREAD

**Issue by gent99** [MicrosoftDocs/OfficeDocs-Support#1746]
[Enter feedback here]
It is absolutely not user friendly to do such a change in a core-functionality, without providing a solution for customers that rely on this functionality. Please change it to the previous version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5d5258-e519-df39-0aa5-57115e0211ab
* Version Independent ID: 01390aa8-7cae-809b-b5e9-567514cc99d8
* Content: [Cannot add an Internet calendar - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/calendaring/cannot-add-an-internet-calendar)
* Content Source: [Outlook/Client/calendaring/cannot-add-an-internet-calendar.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/calendaring/cannot-add-an-internet-calendar.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by VLG17** [comment]
@nam31  looking into it.

**Comment by VLG17** [comment]
@gent99 Did you try the workaround presented in the article - using OWA?

You can use the [Microsoft Tech Community](https://techcommunity.microsoft.com/) to raise this point and provide feedback, that you want the functionality added back. 

We can only help with documentation changes, so if the functionality does come back, we will be able to update the article to reflect it.

**Comment by gent99** [comment]
We're not using OWA here, so that's not a workaround for us.
Kind regards
