### ISSUE TITLE
The PS1 script needs updating to v15 for Exchange 2019

### ISSUE THREAD

**Issue by GLComputing** [MicrosoftDocs/OfficeDocs-Support#1747]
Returns this error:
`Checking the Exchange Install Path variable...

get-itemproperty : Cannot find path 'HKLM:\SOFTWARE\Microsoft\ExchangeServer\v14\Setup' because it does not exist.
At L:\certs\Ex2019\EMTshooter\EMTshooter.ps1:61 char:22
+ ... xinstall = (get-itemproperty HKLM:\SOFTWARE\Microsoft\ExchangeServer\ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\...erver\v14\Setup:String) [Get-ItemProperty], ItemNotFo
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand

The ExchangeInstallPath Environment Variable does not match the Exchange Install Path found in the registry.

Registry Entry:

vs

ExchangeInstallPath Environment Variable:
C:\Program Files\Microsoft\Exchange Server\V15\

Please ensure that both reflect the proper path to the Exchange binary files.

The MsinstallPath registry key can be found at
HKLM:\SOFTWARE\Microsoft\ExchangeServer\v14\Setup\MsiInstallPath`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9478ec16-b866-03ae-edf7-d1076c0163e7
* Version Independent ID: 1abb2287-645a-5ddf-695f-2e066cf60031
* Content: [Connecting to the remote server failed when start Management Shell or Console - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/connecting-remote-server-failed)
* Content Source: [Exchange/ExchangeServer/administration/connecting-remote-server-failed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/administration/connecting-remote-server-failed.md)
* Service: **exchange-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@nam31 looking into it.

**Comment by VLG17** [comment]
@GLComputing The EMTShooter.ps1 applies only to Exchange 2010. It's not constructed to run on newer Exchange versions. Also, many of the things that it checks don't even exist in Exchange 2019 anymore, so it wouldn't make sense to run it as it is on an Exchange 2019 server.

**Comment by nam31** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
