### ISSUE TITLE
Documentation inaccurate

### ISSUE THREAD

**Issue by intrepidtech** [MicrosoftDocs/OfficeDocs-Support#1748]
SharePoint Online list item attachments are not affected by the site collection feature _Open Documents in Client Applications by Default_.  If there is some other way to enable that functionality for list item attachments, please specify, otherwise change the documentation to reflect **SharePoint Online library files** as opposed to list item attachments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d2410e2-6e38-59a3-c528-e5ba3becd1ff
* Version Independent ID: 0f3d3418-944b-1f96-7047-e453acf687b0
* Content: [A SharePoint Online list item attachment doesn't open in the Office client app - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/lists-and-libraries/office-app-fails-opening-list-item-attachment)
* Content Source: [SharePoint/SharePointOnline/lists-and-libraries/office-app-fails-opening-list-item-attachment.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/lists-and-libraries/office-app-fails-opening-list-item-attachment.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by Reeced40** [comment]
@intrepidtech thank you for reaching out. The Open in the client application function works for Office related applications and this document gives a workaround for that. Not sure if I'm misunderstanding the issue, but please clarify if you still need assistance.

**Comment by intrepidtech** [comment]
1. This sentence "You removed the Office Online license from the affected user account." is unlikely to happen.  People  need their Office license, and I don't see that as a valid fix.
2. This sentence "You changed the list's Opening Documents in the Browser setting in Advanced Settings to Open in the client application." is inaccurate.  There is no such advanced setting in a default SharePoint Online _list_, whereas it is present in a document library.
3. This section, "activate the Open Documents in Client Applications by Default site collection feature in Site settings.", does not work for me with the current instructions.  The only way I was able to get files to get files to open in the client app by default is in a document library, and activating this feature helped.

**Comment by Reeced40** [comment]
@tiburd please can you assist here? It seems these are valid points. Can I change the title to the suggestion above - SharePoint Online library files?

**Comment by tiburd** [comment]
@intrepidtech @Reeced40 - Thank you for bringing this issue to our attention. I've passed on the information - this article will be archived, so I'm closing this issue.
