### ISSUE TITLE
this tip helped, but should be in an error message in the application itself

### ISSUE THREAD

**Issue by ahcyip** [MicrosoftDocs/OfficeDocs-Support#1751]
I was able to add an external calendar via OWA, but this workaround should be suggested/advised in the Outlook application itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5d5258-e519-df39-0aa5-57115e0211ab
* Version Independent ID: 01390aa8-7cae-809b-b5e9-567514cc99d8
* Content: [Cannot add an Internet calendar - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/calendaring/cannot-add-an-internet-calendar)
* Content Source: [Outlook/Client/calendaring/cannot-add-an-internet-calendar.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/calendaring/cannot-add-an-internet-calendar.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by nam31** [comment]
Thank you for providing feedback to help improve a Microsoft product!

@ahcyip The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The issues section of this repository is intended for product documentation issues only.

 To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
