### ISSUE TITLE
Please add TABL as the most recommended method to block/allow messages

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/OfficeDocs-Support#1754]
Please add TABL as the top method to block/allow messages. The others are relevant/possible but TABL is recommended. 
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/tenant-allow-block-list?view=o365-worldwide

Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d39c3f-93c5-f920-5148-8069f5021c83
* Version Independent ID: d1e51705-dec0-baee-80f2-71499fd31b52
* Content: [Cautions against bypassing Office 365 spam filters. - Exchange](https://review.docs.microsoft.com/en-us/exchange/troubleshoot/antispam-and-protection/cautions-against-bypassing-spam-filters?branch=main#feedback)
* Content Source: [Exchange/ExchangeOnline/antispam-and-protection/cautions-against-bypassing-spam-filters.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/antispam-and-protection/cautions-against-bypassing-spam-filters.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@nam31 looking into it.
