### ISSUE TITLE
Correction Done in Excel.Sheet.12 in Regedit and finally it worked!

### ISSUE THREAD

**Issue by hassan-usman229** [MicrosoftDocs/OfficeDocs-Support#1765]
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Excel.Sheet.12]
@="Microsoft Excel Worksheet"
"FriendlyTypeName"="@C:\\Program Files\\Microsoft Office\\Root\\VFS\\ProgramFilesCommonX86\\Microsoft Shared\\Office16\\oregres.dll,-101"
"EditFlags"=dword:00000000
"BrowserFlags"=dword:00000008

[HKEY_CLASSES_ROOT\Excel.Sheet.12\CLSID]
@="{00020830-0000-0000-C000-000000000046}"

[HKEY_CLASSES_ROOT\Excel.Sheet.12\DefaultIcon]
@="C:\\Program Files\\Microsoft Office\\Root\\VFS\\Windows\\Installer\\{90160000-000F-0000-1000-0000000FF1CE}\\xlicons.exe,1"

[HKEY_CLASSES_ROOT\Excel.Sheet.12\Insertable]
@=""

[HKEY_CLASSES_ROOT\Excel.Sheet.12\Protocol]

[HKEY_CLASSES_ROOT\Excel.Sheet.12\Protocol\StdFileEditing]

[HKEY_CLASSES_ROOT\Excel.Sheet.12\Protocol\StdFileEditing\Server]
@="C:\\Program Files\\Microsoft Office\\Root\\Office16\\EXCEL.EXE"

[HKEY_CLASSES_ROOT\Excel.Sheet.12\Protocol\StdFileEditing\Verb]

[HKEY_CLASSES_ROOT\Excel.Sheet.12\Protocol\StdFileEditing\Verb\0]
@="@C:\\Program Files\\Microsoft Office\\Root\\VFS\\ProgramFilesCommonX86\\Microsoft Shared\\Office16\\oregres.dll,-1"

[HKEY_CLASSES_ROOT\Excel.Sheet.12\Protocol\StdFileEditing\Verb\1]
@="@C:\\Program Files\\Microsoft Office\\Root\\VFS\\ProgramFilesCommonX86\\Microsoft Shared\\Office16\\oregres.dll,-3"

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell]
@="Open"

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\Edit]
@="@C:\\Program Files\\Microsoft Office\\Root\\VFS\\ProgramFilesCommonX64\\Microsoft Shared\\Office16\\oregres.dll,-1"
"Extended"=""

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\Edit\command]
@="\"C:\\Program Files\\Microsoft Office\\Root\\Office16\\EXCEL.EXE\" /vu \"%1\""

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\Edit\ddeexec]
@=""

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\New]
@="@C:\\Program Files\\Microsoft Office\\Root\\VFS\\ProgramFilesCommonX64\\Microsoft Shared\\Office16\\oregres.dll,-2"

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\New\command]
@="\"C:\\Program Files\\Microsoft Office\\Root\\Office16\\EXCEL.EXE\" /n \"%1\""

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\New\ddeexec]
@=""

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\Open]
@="@C:\\Program Files\\Microsoft Office\\Root\\VFS\\ProgramFilesCommonX64\\Microsoft Shared\\Office16\\oregres.dll,-3"

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\Open\command]
@="\"C:\\Program Files\\Microsoft Office\\Root\\Office16\\EXCEL.EXE\" \"%1\""

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\Open\ddeexec]
@=""

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\OpenAsReadOnly]
@="@C:\\Program Files\\Microsoft Office\\Root\\VFS\\ProgramFilesCommonX64\\Microsoft Shared\\Office16\\oregres.dll,-4"
"Extended"=""

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\OpenAsReadOnly\command]
@="\"C:\\Program Files\\Microsoft Office\\Root\\Office16\\EXCEL.EXE\" /h \"%1\""

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\OpenAsReadOnly\ddeexec]
@=""

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\Print]
@="@C:\\Program Files\\Microsoft Office\\Root\\VFS\\ProgramFilesCommonX64\\Microsoft Shared\\Office16\\oregres.dll,-5"

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\Print\command]
@="\"C:\\Program Files\\Microsoft Office\\Root\\Office16\\EXCEL.EXE\" /q \"%1\""

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\Print\ddeexec]
@=""

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\Printto]

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\Printto\command]
@="\"C:\\Program Files\\Microsoft Office\\Root\\Office16\\EXCEL.EXE\" /q \"%1\" /j \"%2\""

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\Printto\ddeexec]
@=""

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\ViewProtected]
@="@C:\\Program Files\\Microsoft Office\\Root\\VFS\\ProgramFilesCommonX64\\Microsoft Shared\\Office16\\oregres.dll,-11"
"Extended"=""

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\ViewProtected\command]
@="\"C:\\Program Files\\Microsoft Office\\Root\\Office16\\EXCEL.EXE\" /vp \"%1\""

[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\ViewProtected\ddeexec]
@=""

[HKEY_CLASSES_ROOT\Excel.Sheet.12\XML Handler]

[HKEY_CLASSES_ROOT\Excel.Sheet.12\XML Handler\Icon]
@=".xlxml"
".xml"=".xlxml"

**Comment by nam31** [comment]
@hassan-usman229 The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by hassan-usman229** [comment]
This pertains to the issue that Excel opens blank workbooks when clicked on any excel file in your pc.

**Comment by nam31** [comment]
@hassan-usman229 The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The best way to get your issue resolved is to contact Microsoft Support. 
If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 
Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
