### ISSUE TITLE
Forms Documentation - Correction on UI Navigation

### ISSUE THREAD

**Issue by bungard** [MicrosoftDocs/OfficeDocs-Support#1766]
Step5, instructs the user to select the ellipsis button next to Send Email (within Outlook Web Access). This button is longer present. Rather, it seems the user will need to click the "Edit" button above the group name. 
After this change, the rest of the documentation appears to remain correct. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae5837d9-04a2-ffb7-19f4-1b6538cd7630
* Version Independent ID: 97de6157-49d3-99e6-91a5-6d669b95cd90
* Content: [No email notifications for responses to Group Forms - Office](https://docs.microsoft.com/en-us/office/troubleshoot/microsoft-forms/no-email-notifications-for-responses-to-group-forms)
* Content Source: [Office/OfficeExperts/microsoft-forms/no-email-notifications-for-responses-to-group-forms.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/microsoft-forms/no-email-notifications-for-responses-to-group-forms.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **zakirh**

**Comment by MaratMussabekov** [comment]
Hello @bungard ,
please have a look at https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1781
Thank you

**Comment by nam31** [comment]
Closing via #1781 
Thank you
