### ISSUE TITLE
First Table on Page - Outlook 2016 "AlwaysUseMSOAuthForAutodiscover reg key required" should have a value of "No" (not "Yes") now.

### ISSUE THREAD

**Issue by toddalbers** [MicrosoftDocs/OfficeDocs-Support#1770]
According to a Microsoft Support rep that I spoke with today, the very first table on this page needs to be updated for the latest version of Outlook 2016.  For (row) "Outlook 2016", the (column) "AlwaysUseMSOAuthForAutodiscover reg key required" should have a value of "No" (not "Yes") now.  There was a new release of Outlook 2016 today - Version 2108 (Build 14326.20238).  I think it changed in this release.  (not positive if it was this release or an earlier one).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 890d8b0d-530d-7bb1-e437-19f26086fa59
* Version Independent ID: 3f2e2e82-85f9-7339-8a4b-d2de2c016bfb
* Content: [Modern Authentication configuration requirements for transition - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/modern-authentication-configuration)
* Content Source: [Exchange/ExchangeOnline/administration/modern-authentication-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/administration/modern-authentication-configuration.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@toddalbers We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
