### ISSUE TITLE
Hash and Time Stamp

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/OfficeDocs-Support#1772]
Can you help to clarify what values to add to the <Hash> and <Time Stamp> fields. The example has a reference of.

<Hash>=<Timestamp>
44ldt=IX

But, how can we properly approach what values we add.
Also, it would be great to have the complete command example with the filled in fields and a means to validate it.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 230f187a-8786-947f-29b1-b28283f15872
* Version Independent ID: 6662debb-5bef-d33f-0f14-62e32ec65f84
* Content: [Sender Rewriting Scheme (SRS) in Office 365 - Office 365](https://docs.microsoft.com/en-AU/office365/troubleshoot/antispam/sender-rewriting-scheme)
* Content Source: [Microsoft365/security/antispam/sender-rewriting-scheme.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/security/antispam/sender-rewriting-scheme.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by MaratMussabekov** [comment]
Hello @Jmartinez589 ,
**Can you help to clarify what values to add to the and fields** - you don't need to add anything there, it is generated automatically by Exchange Online.
Thank you

**Comment by nam31** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
