### ISSUE TITLE
Microsoft 365 Apps for business - not listed

### ISSUE THREAD

**Issue by davidslight** [MicrosoftDocs/OfficeDocs-Support#1773]
Microsoft 365 Apps for business - not listed
![image](https://user-images.githubusercontent.com/25210376/131174665-aaf541eb-5910-4106-8f34-385ddefdea4c.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b0e3f06-bd25-2d92-228b-9b5e1cf47ff3
* Version Independent ID: c8a6ff08-5acf-adcb-855f-5eadce72f7ba
* Content: [Product IDs that are supported by the Office Deployment Tool for Click-to-Run - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/installation/product-ids-supported-office-deployment-click-to-run)
* Content Source: [Microsoft365/admin/installation/product-ids-supported-office-deployment-click-to-run.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/installation/product-ids-supported-office-deployment-click-to-run.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by nam31** [comment]
Closing via #1792
Thank you
