### ISSUE TITLE
How to enable or disable hyperlink warnings per protocol

### ISSUE THREAD

**Issue by johnbeardy** [MicrosoftDocs/OfficeDocs-Support#1774]
[Enter feedback here]
how does the section "How to enable or disable hyperlink warnings per protocol" work in Office 16.0 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c90d6f1c-2492-75cc-8e6a-71c9bbdec191
* Version Independent ID: 825ef210-269c-ad98-564b-d5c2eed1560f
* Content: [Enable or disable hyperlink warning messages in Office programs - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/enable-disable-hyperlink-warning)
* Content Source: [Microsoft365/admin/administration/enable-disable-hyperlink-warning.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/enable-disable-hyperlink-warning.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by MaratMussabekov** [comment]
Hello @johnbeardy, 
it works, for example it is mentioned here - https://docs.microsoft.com/en-us/office/troubleshoot/word/force-word-document-to-open-in-edit-mode#add-a-ms-word-registry-key-to-suppress-microsoft-outlook-security-notice
Thank you

**Comment by nam31** [comment]
Closing via #1795 
Thank you
