### ISSUE TITLE
Misspelling of Alternatively

### ISSUE THREAD

**Issue by lightchipster** [MicrosoftDocs/OfficeDocs-Support#1775]
Half way down, there is this paragraph:

"Alternativley, you can use the Enable-TlsCipherSuite cmdlet to enable the TLS cipher suites. For example, run the following command to enable a cipher suite as the highest priority"

I believe this should be spelt Alternatively

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c329eb0b-4792-e585-f387-a77ae3786e0d
* Version Independent ID: 043ae1c6-00ff-a67b-7605-86c74bd2df45
* Content: [Error Code 0x8004de40 when signing in to OneDrive - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/error-0x8004de40-in-onedrive)
* Content Source: [SharePoint/OneDrive/administration/error-0x8004de40-in-onedrive.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/OneDrive/administration/error-0x8004de40-in-onedrive.md)
* Service: **one-drive**
* GitHub Login: @salarson
* Microsoft Alias: **v-matham**

**Comment by salarson** [comment]
Thanks for the catch - Fixing it!

**Comment by Reeced40** [comment]
@lightchipster thank you for pointing this out. The typo has been fixed. Please let me know if you need further assistance.
