### ISSUE TITLE
Which roles give permission?

### ISSUE THREAD

**Issue by FlorH** [MicrosoftDocs/OfficeDocs-Support#178]
Can you please include the admin role which provides the permissions to use the command. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ba7ce18-5db2-8f74-3d63-63f23373d2f0
* Version Independent ID: 590ca207-7b23-58b6-7ac8-c097448e76f5
* Content: [Access Denied when you connect to Office 365, Azure, or Intune - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/security/access-denied-office-365-azure#feedback)
* Content Source: [Microsoft365/admin/security/access-denied-office-365-azure.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/security/access-denied-office-365-azure.md)
* Service: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by todmccoy** [comment]
Article updated.
