### ISSUE TITLE
Cause 2 Review and or Correction

### ISSUE THREAD

**Issue by jmaiher** [MicrosoftDocs/OfficeDocs-Support#1780]
Cause 2 may need to be updated or removed.
Cmdlet Set-DistributedGroup allows for the ManagedBy property to utilize either a mailbox, mail user or mail-enabled security group. This is outlined here: https://docs.microsoft.com/en-us/powershell/module/exchange/set-distributiongroup?view=exchange-ps

I have not tested on all versions listed - but it does say its applicable to on-prem Exchange & in the cloud based service. 
The Applies To section shows: Exch 2010, 2013, 2016, 2019 and EXO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eec0f440-01f4-ec27-7db7-b697ed6c075f
* Version Independent ID: 338b692c-7e9d-67aa-0425-3b23eb8bb1c6
* Content: [Can't manage distribution group from Outlook - Outlook](https://docs.microsoft.com/en-US/outlook/troubleshoot/contacts/cannot-manage-distribution-group-exchange-mailbox)
* Content Source: [Outlook/Client/contacts/cannot-manage-distribution-group-exchange-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/contacts/cannot-manage-distribution-group-exchange-mailbox.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by MaratMussabekov** [comment]
Hello @jmaiher ,
please have a look at https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1803
Thank you

**Comment by nam31** [comment]
Closing via #1803 
Thank you
