### ISSUE TITLE
What if email are not reflecting on message trace from maccount@microsoft.com? 

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/OfficeDocs-Support#1789]
Please give more insight. 
Like email is trigerred from maccount@microsoft.com which will be external. 
How email is trigerred from maccount@microsoft.com
If email is not reflecting in message trace then issue is with form submission and not at group level

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae5837d9-04a2-ffb7-19f4-1b6538cd7630
* Version Independent ID: 97de6157-49d3-99e6-91a5-6d669b95cd90
* Content: [No email notifications for responses to Group Forms - Office](https://docs.microsoft.com/en-us/office/troubleshoot/microsoft-forms/no-email-notifications-for-responses-to-group-forms)
* Content Source: [Office/OfficeExperts/microsoft-forms/no-email-notifications-for-responses-to-group-forms.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/microsoft-forms/no-email-notifications-for-responses-to-group-forms.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **zakirh**

**Comment by MaratMussabekov** [comment]
Hello @robinpoulose1 ,
do I understand your scenario correctly: email is sent from external address to a group, you do not see this email in message trace and no email notification is received  by group members?
If yes, can this external sent messages to other recipients? or they only has problem with group?
If I misunderstand it, please correct me.

Thank you

**Comment by robinpoulose1** [comment]
it is resolved.  
actual query was No email notifications for responses to Group Forms..
isolated the issue and found responses were generated from external account maccount@microsoft.com 
we did troubleshooting 
https://docs.microsoft.com/en-us/office/troubleshoot/microsoft-forms/no-email-notifications-for-responses-to-group-forms

however we came to know that client have MX with third party and it pointless to troubleshoot at  o365 end.
