### ISSUE TITLE
Found the exact issue and.... thanks for not providing the fix

### ISSUE THREAD

**Issue by Axilla-the-HUN** [MicrosoftDocs/OfficeDocs-Support#1791]
Once again I find myself frustrated with Microsoft documentation that I feel compelled to post. This is the exact issue I'm having, trying to remove a database from Exchange 2016 that is being decommissioned and the Mailbox database has this audit log, systemmailbox, hidden inside it. After using Get-Mailbox -AuditLog -Database "MailboxDB" I found the audit log is there preventing me from deleting the database. What I need to know from this document is, is it safe to delete, or is it recommended to move to the new server's database. And also how to delete or move, where are the PowerShell examples, don't just link to the PowerShell command page with it's ridiculous amount of switches, provide the last steps in this beautiful support journey we call DOCs. This article just leaves it hanging. You need to take it all the way to the finish line and not just link some semi related topics and the end. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab7f15d5-0399-cd7f-365d-ff7a5414f7e3
* Version Independent ID: bdb2a134-364a-4dc0-1577-8950b0a93c4b
* Content: [Error when you remove a mailbox database - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/error-remove-a-mailbox-database)
* Content Source: [Exchange/ExchangeServer/administration/error-remove-a-mailbox-database.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/administration/error-remove-a-mailbox-database.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
Thank you @dariomws
