### ISSUE TITLE
Get-EXORecipient command might require "-ResultSize unlimited"

### ISSUE THREAD

**Issue by helpcomputer19** [MicrosoftDocs/OfficeDocs-Support#1794]
In my case I needed to add "-ResultSize unlimited" for Step 2 of the solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2473020-afb3-5811-8119-1b102c342a20
* Version Independent ID: 8f5ea090-348a-04ea-90fd-da478d27d8a2
* Content: [Proxy address is already being used error message in Exchange Online - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/proxy-address-being-used)
* Content Source: [Exchange/ExchangeOnline/administration/proxy-address-being-used.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/administration/proxy-address-being-used.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by get-itips** [comment]
Thanks for your feedback!
