### ISSUE TITLE
Invalid Link to https://portal.office.com/DirSync/DirectorySynchronization.aspx

### ISSUE THREAD

**Issue by FrankCarius** [MicrosoftDocs/OfficeDocs-Support#1796]
The first part "Symptoms" has three Links all pointing to "https://portal.office.com/DirSync/DirectorySynchronization.aspx", which is invalid

I think https://admin.microsoft.com/#/dirsyncmanagement or https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/AzureADConnect are better targets

Frank

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc339f75-4ab4-db88-f12d-a8cc238e2050
* Version Independent ID: dc88d81a-0a86-de4d-b021-431ac853463e
* Content: [Fix pending state issue with Directory synchronization for Office 365, Azure, or Intune - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/active-directory/pending-state-issue-with-directory-synchronization)
* Content Source: [Microsoft365/admin/active-directory/pending-state-issue-with-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/active-directory/pending-state-issue-with-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by get-itips** [comment]
Thanks for your feedback @FrankCarius
