### ISSUE TITLE
Example PowerShell script doesn't match scenario

### ISSUE THREAD

**Issue by knightcott-paul** [MicrosoftDocs/OfficeDocs-Support#1797]
The scenario is for private items in a shared mailbox but the example PowerShell script is for Calendar.  Would be more useful if the script showed how to add permissions for an Inbox

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ef4a314-fa73-52f1-fc93-f044451b2118
* Version Independent ID: 5a10809a-5baf-74ac-7613-d35842920252
* Content: [Private items aren't displayed in a shared mailbox in Outlook - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/user-and-shared-mailboxes/private-items-not-display)
* Content Source: [Exchange/ExchangeOnline/user-and-shared-mailboxes/private-items-not-display.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/user-and-shared-mailboxes/private-items-not-display.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **shmcdani**

**Comment by knightcott-paul** [comment]
Actually, I'm wrong.  The Powershell script referencing the Calendar does work for Inbox items, but the article should be improved to explain that.

**Comment by get-itips** [comment]
Thanks for your feedback @knightcott-paul
