### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by stmatw** [MicrosoftDocs/OfficeDocs-Support#18]
Typo in step 2 of How to set up safe senders and blocked senders for a single user
-TrustSendersAndDomains should read -TrustedSendersAndDomains

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abe7d1ac-3629-627e-0f80-77fc4a2d926f
* Version Independent ID: 9ab1df0b-79ff-bfc0-5aff-eaae52277fe1
* Content: [How to set up safe senders and blocked senders in Office 365 - Troubleshooting | Office 365](https://docs.microsoft.com/en-au/office365/troubleshoot/set-up-safe-blocked-senders#feedback)
* Content Source: [Microsoft365/admin/set-up-safe-blocked-senders.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/set-up-safe-blocked-senders.md)
* Service: **o365-administration**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
I've fixed the typo. Closing the case.
