### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by GeorgeKOrr** [MicrosoftDocs/OfficeDocs-Support#180]
I have no F4 key on my mobile device. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35690fa7-49d0-9a1d-7fda-3d91d3b4d301
* Version Independent ID: 05574ffa-cb85-df47-eb86-b7ae2726d927
* Content: [Change from absolute to relative or mixed references in a formula - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/change-formular-reference-type-#feedback)
* Content Source: [Office/Client/excel/change-formular-reference-type-.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/change-formular-reference-type-.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
If there is no F4 Key, it would be better to install a third-party keyboard app or use a bluetooth keyboard.
