### ISSUE TITLE
1024 KB/s does not equal 1Megabit/s

### ISSUE THREAD

**Issue by ktkintner** [MicrosoftDocs/OfficeDocs-Support#1804]
7.5 MB/(60 seconds) = 131,072 bytes/second (for reference, 1,024 KB/s = 1 Megabit/s)

1024 KB/s (Kilobytes per second) in the above reference does not equal 1 Megabit/s, 1024 Kb/s (Kilobits) is equal to 1 Megabit/s. Somehow you switched from bytes to bits and didn't do the conversion, if wanting to reference KB/s then it needs to show 1024 KB/s = 8.192 Mb/s, or for simplification, 1 MB/s = 8 Mb/s

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3fe4dd8-c44f-dc40-e2e7-f6a96e1dd8e2
* Version Independent ID: afb978bc-0d61-e90c-b702-207faea59f30
* Content: [Large mailbox migrations are slow due to network latency - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/move-mailboxes/large-mailbox-migrations-are-slow-due-to-network-latency)
* Content Source: [Exchange/ExchangeHybrid/move-mailboxes/large-mailbox-migrations-are-slow-due-to-network-latency.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/move-mailboxes/large-mailbox-migrations-are-slow-due-to-network-latency.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello,
it looks like a mistake, and the author meant 1,024 KB/s = 1 MB/s, I created a PR to fix it.
Thank you

**Comment by nam31** [comment]
Closing via #1808 
Thank you
