### ISSUE TITLE
Broken download link: Msvbvm50.exe (deprecated?)

### ISSUE THREAD

**Issue by illfated** [MicrosoftDocs/OfficeDocs-Support#181]
Broken link:
- https://download.microsoft.com/download/vb50pro/utility/1/win98/msvbvm50.exe

Not sure if the link should be removed, maybe if it is 100% deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1f7b31c-71ee-442f-1a8f-dec1e5a6f9b5
* Version Independent ID: 04085b6c-1185-26c3-2ba4-97a508ebe022
* Content: [Msvbvm50.exe Installs VB 5.0 Run-Time Files - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office/msvbvm50-installs-vb-5-0-run-time#feedback)
* Content Source: [Office/Client/office/msvbvm50-installs-vb-5-0-run-time.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office/msvbvm50-installs-vb-5-0-run-time.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The link is removed. Thanks.

**Comment by jwalter-io** [comment]
So, there isn't a link left to actually download msvbvm50.dll for those who need it.

**Comment by illfated** [comment]
Good point. I will take a look around and see if there are any pages on support.microsoft.com containing that file.

**Comment by SrBeowulf** [comment]
I downloaded the file when it was available for download and left it saved. I uploaded it to google drive for anyone who wants to download: https: //drive.google.com/file/d/1sRBVzTqRPtS71RDz-FCBczXnvUJLsOV7/view
