### ISSUE TITLE
Group Header vs Group Footer

### ISSUE THREAD

**Issue by FrontierSteve** [MicrosoftDocs/OfficeDocs-Support#1810]
Setting Force New Page to "After Section" on a Group Footer produces a blank page at the end of my Access report, while setting "Force New Page to "Before Section on the Group Header produces a blank page at the beginning of the report.  Either way, I always end up with Page 1 of 6 for my 5-page report.  I want the darn report to be 5-pages and I want the footer to say Page 1 of 5.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62624122-207e-c593-14ad-5f5633821ac7
* Version Independent ID: 10962e0d-8be0-6a4e-ebba-5e06ce2436a4
* Content: [Extra Access report page prints - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/extra-access-report-page-prints)
* Content Source: [Office/Client/access/extra-access-report-page-prints.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/extra-access-report-page-prints.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by MaratMussabekov** [comment]
Hello @FrontierSteve ,
According to [this article](https://support.microsoft.com/en-us/office/insert-a-page-break-control-in-an-access-report-7ce16f0a-7e13-4d39-a197-846ae155cf9a), **Before Section** option doesn't insert a blank page at the beginning of the document. Are you sure there is no other page breaks beside the **Force New Page** setting?
Thank you
