### ISSUE TITLE
Outlook Templates size too large 

### ISSUE THREAD

**Issue by Kirstyx** [MicrosoftDocs/OfficeDocs-Support#1811]
Hi!

i work with outlook many hours a day for work, and what takes up the most time at the end of the day is the recap mails. 
I have to copy and paste so many things it takes up a lot more time and feels like monkeywork. 

I can only use the web version of outlook and cannot import templates due to computer restrictions. It would be AMAZING if I could save my emails as templates, however right now the size is ALWAYS “too large”. Even though it does not have any files in it whatsoever. It would be great to have more advanced options with this that could help me be much more efficient. 

Please help me out and many thanks!

**Comment by nam31** [comment]
@Kirstyx The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@Kirstyx We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
