### ISSUE TITLE
Method 2 - Hyperlinks are not working in Outlook

### ISSUE THREAD

**Issue by francisco-lafe** [MicrosoftDocs/OfficeDocs-Support#1813]
Please, for the love of god, provide a more logical solution for windows 10. 
The method 2 even states "The registry file can be saved directly to the hard disk or **floppy disk**"  
How can I trust a method that considers technology that's 20 years old? 

Is there a better way?

Also, the document navigation tree does not consider the "methods" as part of the hierarchy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f736e25-4b81-c26f-ee4d-640519094af6
* Version Independent ID: 9343708d-ccf7-2e46-d377-13564037a5b9
* Content: [Hyperlinks are not working - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/message-body/hyperlinks-not-working-in-outlook#resolution)
* Content Source: [Outlook/Client/message-body/hyperlinks-not-working-in-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/hyperlinks-not-working-in-outlook.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by RAJU2529** [comment]
@francisco-lafe , the article tells methods of saving registry in examples. You can save to one drive or in write-protected USB pen drive or any other medias

**Comment by francisco-lafe** [comment]
Hello RAJU, I understand what it's saying, the method of course doesn't work and my argument was that the method written there is old as mud. 
Regards,

**Comment by RAJU2529** [comment]
@francisco-lafe . According to you which new method should be included. Could you please suggest here.

**Comment by francisco-lafe** [comment]
These: https://www.timeatlas.com/outlook-hyperlinks-fail-to-work/
I am not certain which one's are "legit" but I'm not the person in charge of knowing that. 
Regards,

**Comment by MaratMussabekov** [comment]
Hello @francisco-lafe ,
**Please, for the love of god, provide a more logical solution for windows 10** - the provided solution would work for Windows 10.
**The method 2 even states "The registry file can be saved directly to the hard disk or floppy disk"** - yes, this could be confusing, I added PR to remove this part.
**Also, the document navigation tree does not consider the "methods" as part of the hierarchy.** - in Microsoft Docs platform, only level 2 headers are shown in the content hierarchy on the right side.

Thank you

**Comment by francisco-lafe** [comment]
It is not a logical solution, you're saying that if your outlook doesn't work, what you should do? 
"welp, good luck if you only have one computer with outlook, out of luck kiddo".  
It basically asks for two computers to fix one.

**Comment by vinyar** [comment]
The SOLUTION should actually provide a solution. I for one do not have "Another" computer to export from. And what if ALL of my computers are experiencing the same issue.

The solution article should provide an export as PART of the solution, not telling users to 'go fetch'. What will happen is users will google up some article, import some registry they find, and end up with a virus or an even bigger issue.

**Solution:** In the registry section, provide a registry export with functional values for all of the impact registry keys. (HKLM, HKCR, etc.)

**Comment by francisco-lafe** [comment]
Yeah I would feel much safer if the registry was provided on the microsoft official troubleshooting guide instead of some randowebsite
