### ISSUE TITLE
Folders with a different language from Cpanel's webmail

### ISSUE THREAD

**Issue by vitorliduario** [MicrosoftDocs/OfficeDocs-Support#1814]
I've tried all the methods and none work.

**Comment by nam31** [comment]
@vitorliduario The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@vitorliduario We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.

**Comment by vitorliduario** [comment]
In Documentos https://docs.microsoft.com/en-us/outlook/troubleshoot/user-interface/incorrect-folder-names, presents some methods to leave the internal folders of an imap account @nameofthesite.com.br in Brazilian Portuguese. I've checked it on the server and it's already in pt_BR, the outloook is also there, and only the internal folders that are in English. Method 1 had no effect, and method 3 with the following line of code after it gives an error message, following code and error:

Code: Set-MailboxRegionalConfiguration -Id "contato.unica@pronam.com.br" -LocalizeDefaultFolderName:$true -Language pt-br -DateFormat "d/m/yyyy"

Error: Set-MailboxRegionalConfiguration : O termo 'Set-MailboxRegionalConfiguration' não é reconhecido como nome de cmdlet,
função, arquivo de script ou programa operável. Verifique a grafia do nome ou, se um caminho tiver sido incluído, veja
se o caminho está correto e tente novamente.
No linha:1 caractere:1
+ Set-MailboxRegionalConfiguration -Id "contato.unica@pronam.com.br" -L ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-MailboxRegionalConfiguration:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
