### ISSUE TITLE
Correction for negative degree convertion

### ISSUE THREAD

**Issue by Orignal74** [MicrosoftDocs/OfficeDocs-Support#1836]
I am submitting to you an improved version of the Convert_Degree function to fix some bugs with negative values.

Using the Fix function instead of the Int function prevents negative values from being rounded down. Adding a condition fixes another bug for numbers between 0 and -1.

Function Convert_Degree(Decimal_Deg) As Variant
    With Application
        'To keep the negative sign if the value is between 0 and -1
        if Decimal_Deg < 0 And Fix(Decimal_Deg) = 0 then Degree_sign = "-"
        'Set degree to Integer of Argument Passed
        Degrees = Fix(Decimal_Deg)
        'Set minutes to 60 times the number to the right
        'of the decimal for the variable Decimal_Deg
        Minutes = (ABS(Decimal_Deg - Degrees) * 60)
        'Set seconds to 60 times the number to the right of the
        'decimal for the variable Minute
        Seconds = Format(((Minutes - Int(Minutes)) * 60), "0")
        'Returns the Result of degree conversion
        '(for example, 10.46 = 10~ 27  ' 36")
        Convert_Degree = " " &Degree_sign & Degrees & "° " & Int(Minutes) & " ' " & Seconds + Chr(34)
    End With
End Function

**Comment by nam31** [comment]
@Orignal74 The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by Orignal74** [comment]
https://docs.microsoft.com/en-us/office/troubleshoot/excel/convert-degrees-minutes-seconds-angles

**Comment by Orignal74** [comment]
I saw the problem by converting negative angles between 0 and -1, only to see that the problem was also present for the other negative values.

-0.000161099999985481 decimal degree gave me -1 ° 59 '59 "in degree minute second, instead of -0 ° 0' 1".
