### ISSUE TITLE
This help article is missing a critical detail in the Shell subkeys.  I have Outlook 2003 and Windows 10 Pro.

### ISSUE THREAD

**Issue by 0salex0** [MicrosoftDocs/OfficeDocs-Support#1849]
This is to important not to share and so I joined the GitHub for this one thing.

When you don't have another computer to get a regkey from or the win versions are a little different that can make things difficult and I have fought with this on and off for weeks.  I did a lot of online searching and a lot of the different online sources all said pretty much the same thing as how it is laid out in this Microsoft document.  But that did not work for me.

What I finally ended up doing all afternoon today was a removal of IE 11 from within the Windows features function of Control Panel - Apps.  Unselect the checkbox in the Installed Features dialog.  Do the reboot.

Then I went back to Apps and re-installed the Feature for Internet Explorer 11 and let Windows installer do its thing.  And did the reboot.

Then I looked at the reg keys again in Classes \ HTMLfile.  Oh my.  There were two additional subkeys present that were not there before, and not mentioned in any of the online help articles that I spent weeks reviewing.  Now my hyperlinks are functional again.

I exported the htmlfile reg key to my hard disk so that now I have a good regkey file and notepad text file to document it in case it gets deleted again and links stop launching.

The two missing key folders are shell\open\ddeexec and then ddeexec\Application.  Do a manual edit to add or repair those two subkeys in the Shell\open section or use the text below to make a key file to repair the HTMLFile tree and all the subkeys in it.

Data entries are String Value entries regSZ.  Right click and select Add String Value.  Double click the new string value to add text Data.

ddeexec is empty with (Default) and no data.  That is the Dynamic Data Exchange Execution key.  That ddeexec is the key that actually does the work to open the web browser.

The ddeexec\Application subkey contains (Default) and the data IExplore.  Without the application folder under ddeexec  nothing will ever happen even though IExplore.exe is properly defined in all the other subkeys.  So frustrating.

Classes htmlfile is the same in both Classes \ Root and Local Machine \ Software so changing it in one place changes it in both places.  This is the text of the Complete HTMLFile regkey file and can be pasted into a Notepad and renamed to htmlfile.reg

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile]
@="HTML Document"
"AppUserModelID"="Microsoft.InternetExplorer.Default"
"EditFlags"=dword:00200000
"FriendlyTypeName"="@C:\\WINDOWS\\system32\\ieframe.dll,-912"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile\CLSID]
@="{25336920-03F9-11cf-8FD0-00AA00686F13}"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile\DefaultIcon]
@=hex(2):25,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,46,00,69,00,6c,00,65,\
  00,73,00,25,00,5c,00,49,00,6e,00,74,00,65,00,72,00,6e,00,65,00,74,00,20,00,\
  45,00,78,00,70,00,6c,00,6f,00,72,00,65,00,72,00,5c,00,69,00,65,00,78,00,70,\
  00,6c,00,6f,00,72,00,65,00,2e,00,65,00,78,00,65,00,2c,00,2d,00,31,00,37,00,\
  00,00

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile\ScriptHostEncode]
@="{0CF774D0-F077-11D1-B1BC-00C04F86C324}"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile\shell]
@="open"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile\shell\Edit]
@="&Edit"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile\shell\Edit\command]
@="\"C:\\Program Files (x86)\\Microsoft Office\\OFFICE11\\msohtmed.exe\" %1"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile\shell\open]
@="Open in S&ame Window"
"CommandId"="IE.File"
"MUIVerb"="@C:\\WINDOWS\\System32\\ieframe.dll,-5732"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile\shell\open\command]
@="\"C:\\Program Files\\Internet Explorer\\iexplore.exe\" %1"
"DelegateExecute"="{17FE9752-0B5A-4665-84CD-569794602F5C}"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile\shell\open\ddeexec]

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile\shell\open\ddeexec\Application]
@="IExplore"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile\shell\Print]
@="&Print"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile\shell\Print\command]
@="\"C:\\Program Files (x86)\\Microsoft Office\\OFFICE11\\msohtmed.exe\" /p %1"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile\shell\printto]

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile\shell\printto\command]
@="\"C:\\WINDOWS\\system32\\rundll32.exe\" \"C:\\WINDOWS\\system32\\mshtml.dll\",PrintHTML \"%1\" \"%2\" \"%3\" \"%4\""

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile\shellex]

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile\shellex\IconHandler]
@="{42042206-2D85-11D3-8CFF-005004838597}"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\htmlfile\shellex\{8895B1C6-B41F-4C1C-A562-0D564250836F}]
@="{f8b8412b-dea3-4130-b36c-5e8be73106ac}"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f736e25-4b81-c26f-ee4d-640519094af6
* Version Independent ID: 9343708d-ccf7-2e46-d377-13564037a5b9
* Content: [Hyperlinks are not working - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/message-body/hyperlinks-not-working-in-outlook)
* Content Source: [Outlook/Client/message-body/hyperlinks-not-working-in-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/hyperlinks-not-working-in-outlook.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by vinyar** [comment]
@0salex0 - hey man. Thanks for the report. I am fighting the same thing, and about to reboot now after installing IE11 which wasn't on my system for the last 5+ years. I really appreciate your post, and will try your registry in a sec and report back.

Trying to be productive, and instead fighting microsoft again. No wonder no one wants to update.. This is infuriating, and I feel you very much.

**Comment by vinyar** [comment]
Another issue provides a solution that's not captured by the document or registry manipulations - 
https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/875

This solution has not been added to the document despite someone from Microsoft Shanghai acknowledging it.

**Comment by vinyar** [comment]
validated that the following worked for me on a system w/o any IE installed:
* install IE from optional features
* reboot
* restore defaults inside IE settings

Notes:
* IE options are available without browser, but restoring defaults did not help
* my HKCR & HKLM settings were correct as per article
* I had a number of child nodes under (HKCR) .html & .hml nodes, which I removed prior to reboot. OpenWithProgIds got regreated.

**Comment by 0salex0** [comment]
I just found something else out the hard way.  Something changed recently (past 6 months) in the Win 10 security model, and you have to be signed into the computer as an administrator level user in order for hyperlinks to trigger.  I tried to open the email links to your reply above relative to the other case so I could see what you were talking about and the links would not open.  I use standard user local sign on to desktop for added protection and the links errored (not allowed - see your administrator).

So I signed out of the local standard user and back in as the administrator.  Opened Outlook and the links worked again.

So it is a combination of needing admin rights and having all of the proper registry keys.

I have been also wondering if you could specify a different browser name and location in the htmlfile keys to trigger a different web application, but I am not going to try to set up and learn another browser application.  So that thought is just a what if for those who use other web interface browsers.

The solution for me will be to just manually open Outlook with the Run as Administrator option when I want to use Outlook hyperlinks.

Glad I was able to help with this riddle.
