### ISSUE TITLE
Another possible solution: Unhide Window

### ISSUE THREAD

**Issue by druggedhippo** [MicrosoftDocs/OfficeDocs-Support#185]
Had the exact symptoms as detailed here, user had blank screen on opening document.

In our case it was due the document being hidden and then saved (as per the notes here https://support.office.com/en-us/article/hide-or-show-worksheets-or-workbooks-69f2701a-21f5-4186-87d7-341a8cf53344 )

"When you exit Excel, you will be asked if you want to save changes to the hidden workbook window. Click Yes if you want the workbook window to be hidden the next time that you open the workbook."

So, the simple solution is to unhide the window:

- Click View tab
- Click Unhide
- Choose the workbook in the list
- Click "OK"

I know it seems silly, but this troubleshooting page was the first I found when I was looking into why a workbook wasn't opening for one of my users since I had assumed corruption or other issues. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62a88c46-43bb-92cf-c409-c8b3071b3865
* Version Independent ID: 19f5e98e-36a5-e2e9-39b1-5fc5ae349b50
* Content: [Troubleshoot Excel opening blank when double-click a file icon or file name - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/excel-opens-blank#feedback)
* Content Source: [Office/Client/excel/excel-opens-blank.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/excel-opens-blank.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by ryanAltobello** [comment]
I'm so grateful you took the time to respond to this thread. I have no idea how the hell I hid my view, but I thought I lost 2 weeks of work. Thank you so much for your solution.
