### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by dscam** [MicrosoftDocs/OfficeDocs-Support#1854]
The link to 'Why does Outlook keep prompting for password' is broken (https://social.technet.microsoft.com/Forums/en-US/bcd2d9c2-1a1b-4446-bf32-69fee8cdf11b/why-does-outlook-keep-prompting-for-password?forum=outlook)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8e36de2-8956-ed6f-61b7-2d2ba7b2e7b0
* Version Independent ID: 1e05c7a3-20df-ad99-9fb4-8d3b509f521a
* Content: [Outlook continually prompts for password when you try to connect to Office 365 - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/authentication/continually-prompts-password-office-365)
* Content Source: [Outlook/Client/authentication/continually-prompts-password-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/authentication/continually-prompts-password-office-365.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by RAJU2529** [comment]
@dscam , the link is perfectly working 
![Uploading Web capture_29-9-2021_192640_social.technet.microsoft.com.jpeg…]()
