### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by UWillC** [MicrosoftDocs/OfficeDocs-Support#186]
I have tried all the methods on my environment which is Windows 10 1803 with the latest patches installed and MS Office 2016 Professional Plus version 16.0.4266.1001 and still has the same issue that when I am trying to open the documment from Network/Local drive all I get is MS Excel opened without the spreadsheet... frustrating for the moment but I will keep look for possible solution on this problem.

**Comment by nam31** [comment]
@UWillC, can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you

**Comment by nam31** [comment]
@UWillC We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
