### ISSUE TITLE
Should say the Group policy object to modify if its set by an admin..

### ISSUE THREAD

**Issue by RescueWhale** [MicrosoftDocs/OfficeDocs-Support#187]
Should say the Group policy object to modify if its set by an admin..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab3b3b72-87a5-8b6f-f049-0500b0cbee6e
* Version Independent ID: b8a259e9-cb59-936d-f38f-e157772ca311
* Content: [This feature has been disabled by your administrator error in Office - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/office-feature-disabled)
* Content Source: [Microsoft365/admin/administration/office-feature-disabled.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/office-feature-disabled.md)
* Service: **sharepoint-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by todmccoy** [comment]
Article updated.
