### ISSUE TITLE
Set-MSOLUser Command Parameter -PreferredDataLocation no longer supported

### ISSUE THREAD

**Issue by DaytonaXBoxGuy** [MicrosoftDocs/OfficeDocs-Support#188]
[This command no longer works. I tried it on several of our users and got the following error.....

PS C:\ Set-MsolUser -UserPrincipalName "hidden@xxx.com" -PreferredDataLocation "NAM"
Set-MsolUser : A parameter cannot be found that matches parameter name 'PreferredDataLocation'.
At line:1 char:51
+ ... ser -UserPrincipalName "hidden@xxx.com" -PreferredDataLocation "NAM"
+                                              ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-MsolUser], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Online.Administration.Automation.SetUser
---]

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11b3d069-49f1-30d1-7a51-ca4fdb91ae8d
* Version Independent ID: efb1f3e7-9f48-96dc-6654-cccd3c7afae7
* Content: [Cannot create a meeting on behalf of delegate in Skype for Business - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/online-meetings/cannot-create-meeting-delegate)
* Content Source: [SkypeforBusiness/SkypeOnline/online-meetings/cannot-create-meeting-delegate.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeOnline/online-meetings/cannot-create-meeting-delegate.md)
* Service: **skype-for-business-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-zht**

**Comment by claudialake** [comment]
Hi @DaytonaXBoxGuy,

Sorry you've encountered this issue. It looks like this Cmdlet still exists. If you haven't already and are still encountering this issue, please open a support ticket. Thanks!

**Comment by DaytonaXBoxGuy** [comment]
I confirmed I have the latest version of the MSONLINE cmdlets and only the parameter "-PreferredDataLocation" throws the error. None of the other Set-MSOLUser cmdlets error out as long as that parameter is not included. It must be one of those reserved parameters that only O365 backend staff can use.

**Comment by claudialake** [comment]
@DaytonaXBoxGuy, thanks for verifying you have the latest version of MSONLINE. Go ahead and open a support ticket to further debug this issue. Thanks!

**Comment by alexlushsevernunival** [comment]
@DaytonaXBoxGuy - are you syncing users from on premise AD using Azure AD Connect? Its not supported to update this property on on-premise authored accounts.

**Comment by nam31** [comment]
@DaytonaXBoxGuy this article has been updated recently. 
Also as @claudialake suggested if the issue persists, the best way to get your issue resolved is to contact Microsoft Support. 
If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 
Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
