### ISSUE TITLE
Outlook Crashing After a Few Seconds

### ISSUE THREAD

**Issue by dothedewonline** [MicrosoftDocs/OfficeDocs-Support#189]
I tried Safe mode and unchecked all add-ins and I still get the error.  Then I tried to run SetupProd_OlkStart.exe and I get an error that states that my admin has blocked running this program.  I am the admin; I own the computer that I built and it is not part of a domain for the corporation that I work for.  This started after upgrade to Windows 1903.
![Blocked Application Install Error Screen](https://user-images.githubusercontent.com/51028916/68041652-09725c00-fc9f-11e9-924c-cd3c298128ee.jpg)

**Comment by nam31** [comment]
@dothedewonline, can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you

**Comment by nam31** [comment]
@dothedewonline We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
