### ISSUE TITLE
Wrong link in outlook-issues

### ISSUE THREAD

**Issue by flpelletier** [MicrosoftDocs/OfficeDocs-Support#1899]
Good morning,

The link in resolution Section of this page is broken :
https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/outlook-issues/show-a-room-list-option-not-displayed-in-room-finder.md#resolution
It redirects to : https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/recipients/room-mailboxes, which not exist

Thanks

**Comment by RAJU2529** [comment]
@simonxjx  so please verify and merge it, if added link is correct

**Comment by simonxjx** [comment]
@RAJU2529, the link is working in https://docs.microsoft.com/exchange/troubleshoot/outlook-issues/show-a-room-list-option-not-displayed-in-room-finder.

**Comment by RAJU2529** [comment]
@simonxjx , below link is mentioned 
Which is not working so j changed it. Under the GitHub page
https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/outlook-issues/show-a-room-list-option-not-displayed-in-room-finder.md#resolution


Wrong link is mentioned
    Exchange/recipients/room-mailboxes

**Comment by aisgbnok** [comment]
@flpelletier If you are viewing the docs through GitHub, the links won't always work. The links are pathed/written to work on [docs.microsoft.com](https://docs.microsoft.com/), not on Github.

As @simonxjx stated, the best place to view that page is at [https://docs.microsoft.com/exchange/troubleshoot/outlook-issues/show-a-room-list-option-not-displayed-in-room-finder](https://docs.microsoft.com/exchange/troubleshoot/outlook-issues/show-a-room-list-option-not-displayed-in-room-finder), where the link will work correctly.

I hope this helps? This issue and respective PR can be closed?
