### ISSUE TITLE
Step 8 "If the address is incorrect" proceed to the next section

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/OfficeDocs-Support#19]
What if the address is in fact correct, but the user still gets the 'not in directory' message?
For things like this, each If needs a corresponding Else, no?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147ff236-2d1b-b9e2-ba17-f79c734ca30f
* Version Independent ID: 430e1980-6757-8290-788d-350fe4a57662
* Content: [Error message when an external user accepts a SharePoint Online invitation by using another account - Troubleshooting | SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/online-admin/error-when-external-user-accepts-an-invitation-by-using-another-account)
* Content Source: [SharePoint/SharePointOnline/online-admin/error-when-external-user-accepts-an-invitation-by-using-another-account.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/online-admin/error-when-external-user-accepts-an-invitation-by-using-another-account.md)
* Service: **sharepoint-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The article is updated that the incorrect and correct account should be removed as there may be SID mismatches.
