### ISSUE TITLE
INCORRECT CODE , below works . Also using names in place of cell numbers is not explained or example

### ISSUE THREAD

**Issue by Mikelaplaya** [MicrosoftDocs/OfficeDocs-Support#190]
Application.Goto Sheets("Sheet1").Range(Sheets("Sheet1").Cells(2, 3), _
      Sheets("Sheet1").Cells(4, 5))
You need an example also of how to use a name range as a variable in this , very mixed up.
Eg if i want to use a named cell that has a value of 346 in place of the 2 in the first part of the range . Name LOWRANGE = 346  THEN CELLS(LOWRANGE,3) ,doesnot work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74bbe6e6-cb2a-50ae-7c2c-cef5c64e6559
* Version Independent ID: 9a187fc7-3fc1-effa-a440-46dc2c8838b6
* Content: [How to select cells or ranges by using Visual Basic procedures in Excel. - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-developer/select-cells-rangs-with-visual-basic#feedback)
* Content Source: [Office/Client/office-developer/select-cells-rangs-with-visual-basic.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-developer/select-cells-rangs-with-visual-basic.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by todmccoy** [comment]
Article updated and published.
