### ISSUE TITLE
issues 

### ISSUE THREAD

**Issue by Oliviavazle** [MicrosoftDocs/OfficeDocs-Support#1909]
how can i get my hp after i buy the 365 Microsoft 
[Getting started with OneDrive.pdf](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/8848728/Getting.started.with.OneDrive.pdf)

**Comment by RAJU2529** [comment]
@Oliviavazle ,  First you need to install office 365 using office 365 key and install on your HP.
viit below official sites for more information

https://support.microsoft.com/en-us/office/download-and-install-or-reinstall-microsoft-365-or-office-2021-on-a-pc-or-mac-4414eaaf-0478-48be-9c42-23adc4716658

https://support.microsoft.com/en-us/office/activate-office-5bd38f38-db92-448b-a982-ad170b1e187e
