### ISSUE TITLE
Worksheet_SelectionChange event kills Paste Special

### ISSUE THREAD

**Issue by RonWHarding** [MicrosoftDocs/OfficeDocs-Support#192]
I had this issue and  I found that it was caused by a Sub Worksheet_SelectionChange  event.
I had selected some cells that I wanted to use with Paste Special. As soon as I clicked (or right-clicked) on the destination cells to Past Special, the paste options were gone. the Selection change event took the option away.

To fix this, I toggle Application.EnableEvents off in the immediate box in the VBA environment. After I finish my copy and special pasting, I turn Application.EnableEvents back to True so my macros run again.

I eventually wrote some code to toggle this on and off with a macro button on the Quick Access Toolbar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fc5c286-b567-411a-7f3a-231067bc9bbf
* Version Independent ID: 767b8433-efdc-47a8-4a71-030a65fe548c
* Content: [Paste Special option is missing or not working in Microsoft Office - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/paste-special-missing-or-not-working)
* Content Source: [Office/Client/excel/paste-special-missing-or-not-working.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/paste-special-missing-or-not-working.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by nam31** [comment]
Closing via #1687 
Thank you
