### ISSUE TITLE
Awkward design

### ISSUE THREAD

**Issue by SjoerdV** [MicrosoftDocs/OfficeDocs-Support#195]
Although this apparently is 'by design' it is not how normal people would want this column to work. We need this column to accurately display the people or groups that this file/folder is shared with, whether it is through direct access or a sharing link. 

Please vote for the uservoice here: https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration/suggestions/17840410-the-shared-with-column-displays-users-who-no-lon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70a92366-f8a4-0261-d508-a5f9db54b2a3
* Version Independent ID: 42cd3349-a3a8-8d9f-85be-85801014053b
* Content: [Shared With column displays users who no longer have access to a document - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/sharing-and-permissions/shared-with-column-users-no-access?redirectSourcePath=%252fen-us%252farticle%252fthe-shared-with-column-displays-users-who-no-longer-have-access-to-a-document-in-sharepoint-online-c6b76219-8551-4e56-ae02-f7dbae827b61&source=docs#problem)
* Content Source: [SharePoint/SharePointOnline/sharing-and-permissions/shared-with-column-users-no-access.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sharing-and-permissions/shared-with-column-users-no-access.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by JakeDWarren** [comment]
This design almost has not purpose but to track the history of access. We need a column that show who its actively shared with.

**Comment by nam31** [comment]
@SjoerdV Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
