### ISSUE TITLE
Version index does not exists

### ISSUE THREAD

**Issue by Leif-Frederiksen** [MicrosoftDocs/OfficeDocs-Support#197]
I have this exact problem, but I do NOT see a "Version" index to delete. 
What can I do to resolve the issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8a8160-6b6e-7d8c-4ce8-4b91de15239e
* Version Independent ID: 84d69666-3c35-03e1-be70-eea2d5d3e33d
* Content: [The URL is invalid error when you upload a file to a SharePoint list - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/lists-and-libraries/url-invalid-upload-file-to-list)
* Content Source: [SharePoint/SharePointOnline/lists-and-libraries/url-invalid-upload-file-to-list.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/lists-and-libraries/url-invalid-upload-file-to-list.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
You can check the step 4 of https://support.office.com/en-us/article/f3f00554-b7dc-44d1-a2ed-d477eac463b0. Thanks.

**Comment by Leif-Frederiksen** [comment]
That is the recipe for adding an index. I do not see how this would help me with this issue where the resolution should be to delete an index?/Leif
-------- Oprindelig besked --------Fra: Simonx Xu <notifications@github.com> Dato: 06/11/2019  03.14  (GMT+01:00) Til: MicrosoftDocs/OfficeDocs-Support <OfficeDocs-Support@noreply.github.com> Cc: Leif Frederiksen <leif.frederiksen@gmail.com>, Author <author@noreply.github.com> Emne: Re: [MicrosoftDocs/OfficeDocs-Support] Version index does not exists (#197) You can check the step 4 of https://support.office.com/en-us/article/f3f00554-b7dc-44d1-a2ed-d477eac463b0. Thanks.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/197?email_source=notifications\u0026email_token=AGABXNJHCJDOK3E34BML2L3QSIR7BA5CNFSM4JJCD6F2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDFAHJA#issuecomment-550110116",
"url": "https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/197?email_source=notifications\u0026email_token=AGABXNJHCJDOK3E34BML2L3QSIR7BA5CNFSM4JJCD6F2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDFAHJA#issuecomment-550110116",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by zeusvillanueva** [comment]
Any resolution? I have the same issue but no version index. I can't delete or do anything with the document. I need to update the new document.

**Comment by danniborg** [comment]
Any fix to this problem yet?
