### ISSUE TITLE
KB224351 Link is Broken

### ISSUE THREAD

**Issue by mikebinz** [MicrosoftDocs/OfficeDocs-Support#198]
Can anyone direct me to an archive of this Package please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28438126-9e76-2fe6-45db-b3209cf447bf
* Version Independent ID: 908778fc-c9a5-1012-2b26-d3d781f8e9c3
* Content: [Dsofile.dll lets you edit OLE document property - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office/dsofile.dll-allow-edit-document-property#feedback)
* Content Source: [Office/Client/office/dsofile.dll-allow-edit-document-property.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office/dsofile.dll-allow-edit-document-property.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The package can be downloaded now.

**Comment by mikebinz** [comment]
Great service thanks Simon
