### ISSUE TITLE
Go into effect 

### ISSUE THREAD

**Issue by Thommykatz** [MicrosoftDocs/OfficeDocs-Support#199]
Hi, 
could you please verify with which build it goes into effect ? Monthly September was 11929.xxxxx and this should be SAC in January 2020. Build 12130 was released in October and therefore should not go into SAC in January.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3317dae2-eec1-fbf0-d7a4-eca880046043
* Version Independent ID: abce7354-b1e1-d9b3-edb0-19e863d82e1c
* Content: [Enable co-authoring for OneDrive-synced files - Office](https://docs.microsoft.com/en-us/office/troubleshoot/reference/enable-co-authoring-for-onedrive-synced-file#feedback)
* Content Source: [Office/Client/reference/enable-co-authoring-for-onedrive-synced-file.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/reference/enable-co-authoring-for-onedrive-synced-file.md)
* Product: **office 365**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by claudialake** [comment]
Thommykatz, we are targeting this change to go into effect starting in the September 2019 monthly update (build 16.0.12129.xxxxx) Additionally, this change will be rolled into the next semi-annual channel release in the January 2020 update.
