### ISSUE TITLE
scripts in one line

### ISSUE THREAD

**Issue by andresan21** [MicrosoftDocs/OfficeDocs-Support#2]
[Enter feedback here]
If you copy and paste everything in one line as the example in resolution one it will not work.
You have to break the script apart line by line in order for it to work. You also have to add the "-identity" for the Get-SPWebApplication. 

Example:

Add-PsSnapin Microsoft.SharePoint.PowerShell
$webApp = Get-SPWebApplication -identity "webapplication" 
foreach($site in $webApp.Sites){ 
    foreach($web in $site.AllWebs) {
         $appInstance = Get-SPAppInstance -Web $web.Url | ? {$_.LaunchUrl -notlike "~appWebUrl*"} | select Title, AppPrincipalId 
         if($appInstance -ne $null) { 
            foreach ($instance in $appInstance) { 
                $tmp = $instance.AppPrincipalId.Split('|@',[System.StringSplitOptions]::RemoveEmptyEntries) 
                $appInfo = $instance.Title + " - " + $tmp[$tmp.Count - 2] + " - " + $web.Url 
                Write-Output $appInfo } } }}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8f9c9cc-3c05-5d14-5f48-45928f21e738
* Version Independent ID: 3eaa6276-2210-b9f5-9522-e912c179efc9
* Content: [Provider-hosted add-ins stop working and HTTP 401 error after you configure SharePoint farm hybrid features](https://docs.microsoft.com/en-us/sharepoint/support/server-admin/provider-hosted-add-ins-stop-working-and-http-401-error-after-configure-farm-hybrid-features#feedback)
* Content Source: [SharePoint/SharePointServer/server-admin/provider-hosted-add-ins-stop-working-and-http-401-error-after-configure-farm-hybrid-features.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointServer/server-admin/provider-hosted-add-ins-stop-working-and-http-401-error-after-configure-farm-hybrid-features.md)
* Service: **sharepoint-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Fixed.
