### ISSUE TITLE
"1,462 days is equal to four years and one day (including one leap day)" is incorrect

### ISSUE THREAD

**Issue by sean-rose** [MicrosoftDocs/OfficeDocs-Support#202]
Four years and one day would be 1,461.  The difference is 1,462 instead of 1,461 because the 1900 date system starts with serial number 1 (one) while the 1904 date system starts with serial number 0 (zero).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8462f7c-3fcb-c891-cca9-8c1ff894d4b0
* Version Independent ID: 78b5d0d6-6de5-e495-20a6-c5b9c34046f7
* Content: [Differences between the 1900 and the 1904 date system - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/1900-and-1904-date-system#feedback)
* Content Source: [Office/Client/excel/1900-and-1904-date-system.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/1900-and-1904-date-system.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
This article has been updated.
