### ISSUE TITLE
Helpful

### ISSUE THREAD

**Issue by bady2bro** [MicrosoftDocs/OfficeDocs-Support#203]
It helped with my count errors and my light-undiagnosed-and-probably-not-a-thing OCD of having no unread emails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b64aa0cd-7717-992d-6960-c4c5acec8e21
* Version Independent ID: 065defa3-391b-c629-ccff-316e906f0ad2
* Content: [Only a subset of your Exchange mailbox items are synchronized in Outlook - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/mailboxes/only-subset-items-synchronized#feedback)
* Content Source: [Outlook/Client/mailboxes/only-subset-items-synchronized.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/mailboxes/only-subset-items-synchronized.md)
* Service: **exchange-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments.
