### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by Dra-Knight** [MicrosoftDocs/OfficeDocs-Support#205]
I'm using the latest release of Outlook for Mac and I'll still be asked for passwords constantly during the day.

Have uninstalled every key, and re-installed Outlook. 

It still doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdfab92b-6018-8f71-8eb8-e31d3371dbd4
* Version Independent ID: 9e60f423-e7fa-8ce0-17c4-7cdd37bd6083
* Content: [Outlook 2016 for Mac repeatedly prompts for authentication - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/sign-in/repeated-prompts-authentication#feedback)
* Content Source: [Outlook/Mac/sign-in/repeated-prompts-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Mac/sign-in/repeated-prompts-authentication.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments. I think you can try to reach https://support.office.com/en-us/outlook for the issue.
