### ISSUE TITLE
Bad links to KB Articles

### ISSUE THREAD

**Issue by lesterw1** [MicrosoftDocs/OfficeDocs-Support#206]
Under the *Outlook 2016* section, the links to *KB 3126599* and *KB 2937684* simply point back to the current page. The correct links are as follows:

* *KB 3126599* - https://support.microsoft.com/en-us/help/3126599/outlook-prompts-for-password-when-modern-authentication-is-enabled
* *KB 2937684* - https://support.microsoft.com/en-us/help/2937684/outlook-may-not-connect-using-mapi-over-https-as-expected

Please correct the embedded links in the page under the *Outlook 2016* section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 890d8b0d-530d-7bb1-e437-19f26086fa59
* Version Independent ID: 3f2e2e82-85f9-7339-8a4b-d2de2c016bfb
* Content: [Modern Authentication configuration requirements for transition - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/modern-authentication/modern-authentication-configuration)
* Content Source: [Exchange/ExchangeOnline/modern-authentication/modern-authentication-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/modern-authentication/modern-authentication-configuration.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The links are updated. Thanks.
