### ISSUE TITLE
"Parent site and sub site-specific search issues" does not match the GUI

### ISSUE THREAD

**Issue by gabbsmo** [MicrosoftDocs/OfficeDocs-Support#207]
The docs mentions that under the "Search and Offline availability" page in Site settings there should be an option to "Do not index ASPX pages". This does not exist on the page but there is an option to "Do not index Web Parts".

Is it the docs or Site settings that is correct here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03fc1c37-d042-bcc4-5d3e-31ac9f4dc500
* Version Independent ID: 0375882c-42a3-b271-cfa2-51029d6bfb93
* Content: [Search results missing in SharePoint Online - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/search/search-results-missing#parent-site-and-sub-site-specific-search-issues)
* Content Source: [SharePoint/SharePointOnline/search/search-results-missing.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/search/search-results-missing.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by get-itips** [comment]
Thanks for raising, will update the article @gabbsmo
