### ISSUE TITLE
Line breaks missing from sample output

### ISSUE THREAD

**Issue by browlry** [MicrosoftDocs/OfficeDocs-Support#208]
The sample output of steps 5a through 5c has been formatted without line breaks for some reason.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4016371-ddf1-433d-ab2e-3c0730a15a46
* Version Independent ID: 07c31443-9837-7f86-a729-ad57befa0d82
* Content: [Cannot connect to your account when activate Office from Office 365 - Office](https://docs.microsoft.com/en-us/office/troubleshoot/activation-installation/issue-when-activate-office-from-office-365#feedback)
* Content Source: [Office/Client/activation-installation/issue-when-activate-office-from-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/activation-installation/issue-when-activate-office-from-office-365.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your feedback. The output sample is fixed.
