### ISSUE TITLE
Having Syntax Problems (Coordinates Long/Lat Decimal conversion to DMS)

### ISSUE THREAD

**Issue by zpModus** [MicrosoftDocs/OfficeDocs-Support#209]
Hello, 

I am receiving a SYNTAX error when trying to convert from decimal to DMS in coordinates using this function. I am learning to code and am confused as to why the Microsoft guide on conversion is not working appropriately. Any help would be much appreciated.

Thank You!

-ZPMODUS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be969d50-8518-365f-f3ed-5c0e14d55104
* Version Independent ID: 11bad482-781b-bbae-ce60-53f8164d137e
* Content: [Convert degrees/minutes/seconds angles to or from decimal angles - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/convert-degrees-minutes-seconds-angles)
* Content Source: [Office/Client/excel/convert-degrees-minutes-seconds-angles.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/convert-degrees-minutes-seconds-angles.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments. I think you can try to reach https://support.office.com/en-us/excel for help.

**Comment by bladecell** [comment]
Function Convert_Degree(Decimal_Deg) As Variant
With Application
  'Set degree to Integer of Argument Passed
   Degrees = Int(Decimal_Deg)
   'Set minutes to 60 times the number to the right
   'of the decimal for the variable Decimal_Deg
   Minutes = (Decimal_Deg - Degrees) * 60
   'Set seconds to 60 times the number to the right of the
   'decimal for the variable Minute
   Seconds = Format(((Minutes - Int(Minutes)) * 60), "0")
   'Returns the Result of degree conversion
   '(for example, 10.46 = 10~ 27  ' 36")
   Convert_Degree = Int(Degrees) & "°" & Int(Minutes) & "'" & Int(Seconds) & "''"
  End With
End Function

**Comment by hkmiller14** [comment]
This question wasn't answered and I'm having the same problem. There is a syntax error for going from DMS to DD. If that Macro could be updated to solve the problem that would be great. Thanks!
