### ISSUE TITLE
MS Excel Cell Alignment Justify not working while printing.

### ISSUE THREAD

**Issue by prdpspkt** [MicrosoftDocs/OfficeDocs-Support#210]
[Enter feedback here]

Im using Microsoft Excel 2019, I justified a long text-wrapped cell in excel it looks fine in working and print preview but when I print document printing text is left align and leaves gaps in right margin.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5d586e4-c434-c16c-c72b-a09f38f394c1
* Version Independent ID: 84efcca4-1707-22c2-bf71-58755cbb57ea
* Content: [Control settings in the Format Cells dialog box - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/format-cells-settings)
* Content Source: [Office/Client/excel/format-cells-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/format-cells-settings.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments. I think you can reach https://support.office.com/en-us/excel for help.
