### ISSUE TITLE
new project online design

### ISSUE THREAD

**Issue by funzel1** [MicrosoftDocs/OfficeDocs-Support#212]
Is this  article  up to date with the new design  ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25ff84f5-c9c9-5093-a5c6-639a03c0ed75
* Version Independent ID: 883a3113-c0cf-fec2-fb36-04fbff905356
* Content: [Access Project Online Tenant - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/access-project-online-tenant)
* Content Source: [Microsoft365/admin/administration/access-project-online-tenant.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/access-project-online-tenant.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by joinimran** [comment]
Hi @funzel1, thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by joinimran** [comment]
Hi @funzel1, yes it is up to date but if you see any ambiguity please let us know.

**Comment by nam31** [comment]
@funzel1 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
