### ISSUE TITLE
How does/can this work with MFA?

### ISSUE THREAD

**Issue by TKardinal** [MicrosoftDocs/OfficeDocs-Support#213]
Since we have to load the special powershell modules indicated in this document for MFA, https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps, how would we use this process, specifically Step 7, since we cannot cache $cred with MFA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b0eef03-98f2-0630-f331-6eedf8a98085
* Version Independent ID: 2302b229-aff5-d18d-dcb9-844a29e28728
* Content: [How to recover when a mailbox exists in both Exchange Online and on-premises - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/move-mailboxes/mailbox-exists-exo-onpremises?source=docs#feedback)
* Content Source: [Exchange/ExchangeHybrid/move-mailboxes/mailbox-exists-exo-onpremises.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/move-mailboxes/mailbox-exists-exo-onpremises.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @TobyTu
* Microsoft Alias: **benwinz**

**Comment by ChrisAtMAF** [comment]
I suspect it should be as easy as replacing
$cred = Get-Credential
with
Connect-EXOPSSession

**Comment by JeremyTBradshaw** [comment]
That answer (Connect-EXOPSSession) is incorrect.  Regarding MFA, the RemoteCredential parameter is there to catch credentials for use against on-premises Exchange.  I don't believe MFA is going to be a factor in this case, whereas the connection is going to be from Exchange Online to Exchange on-premises.  If you have Hybrid Modern Authentication setup, then maybe MFA could be a factor, but I'm not familiar enough on that topic to know for sure.  My suspicion is that Hybrid Modern Auth. may not apply to on-premises Exchange's remote PowerShell authentication.

**Comment by bwinzenz** [comment]
Jeremy is correct. These are the creds needed to connect to On-Premises Exchange, so MFA should not be a concern here. The steps assume you are already connected to Exchange Online PowerShell before running any commands, and if MFA is required, it would be during the initial connection phase. HMA also is not available for PowerShell, so should further not be a factor. If you think additional steps are needed to add PowerShell connection steps, we can review if that would be helpful to add.

**Comment by MaratMussabekov** [comment]
Hello @TKardinal ,
yes, there is no need for MFA, as it is about credentials of on-premises exchange.
Also, added some details in #1568 
Thank you

**Comment by nam31** [comment]
Closing via #1568 
Thank you
