### ISSUE TITLE
Code 404

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/OfficeDocs-Support#214]
First 2 links give 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 850e6d40-20b8-85c9-2c19-7bf1ff1e7206
* Version Independent ID: 2959843b-b0e7-17b5-ece2-c0bd2bb3bc59
* Content: [Win32API_PtrSafe with 64-bit Support - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office/win32api_ptrsafe-with-64-bit-support#feedback)
* Content Source: [Office/Client/office/win32api_ptrsafe-with-64-bit-support.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office/win32api_ptrsafe-with-64-bit-support.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The links are updated. Thanks.
