### ISSUE TITLE
Resolution doesn't apply to Mac

### ISSUE THREAD

**Issue by memsim1010** [MicrosoftDocs/OfficeDocs-Support#215]
So, this page is specifically for Office for Mac but, your resolution is for a PC. Mac doesn't have a start menu and typing services.msc isn't going to do a Mac much good, either...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 145563a8-813d-f479-7a73-29a6705ea5cc
* Version Independent ID: 74ec5975-f3b0-15c4-7699-491b544232aa
* Content: [Office files in SharePoint fail to open from an Office 2016 client - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-for-mac/files-fail-to-open#feedback)
* Content Source: [Office/Client/office-for-mac/files-fail-to-open.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-for-mac/files-fail-to-open.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by joinimran** [comment]
Hi @memsim1010, thank you for your feedback.
I am working on this issue and will provide you with an update soon

**Comment by nam31** [comment]
@memsim1010 we are going to close this issue as the article has been updated accordingly. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
