### ISSUE TITLE
Incorrect process name listed for Google Chrome on page

### ISSUE THREAD

**Issue by wesmacdonald** [MicrosoftDocs/OfficeDocs-Support#218]
The following text 

If you're using Google Chrome, find and right-click **iexplore.exe** in the list, and then click End task.

Should read

If you're using Google Chrome, find and right-click **chrome.exe** in the list, and then click End task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57691ebf-3011-b41c-3930-64fdbe7a3bc8
* Version Independent ID: afeb5333-1273-e5bd-80cf-061665ed8cbd
* Content: [Problems when signing out of Office 365, Azure, or Intune in a web browser - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/active-directory/cannot-sign-out-cloud-service?source=docs#feedback)
* Content Source: [Microsoft365/admin/active-directory/cannot-sign-out-cloud-service.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/active-directory/cannot-sign-out-cloud-service.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments, The article is updated.
