### ISSUE TITLE
Unable to create 2 shared emails with same address but different domains

### ISSUE THREAD

**Issue by abirtley** [MicrosoftDocs/OfficeDocs-Support#22]
If I have a shared email support@domain.com.au, I cannot create a second shared email support@domain.co.uk (despite owning both domain.com.au and domain.co.uk, and having regular (mailbox) emails working just fine on both domains).

I receive the following error:

```
The proxy address "SMTP:support@domain.com.au" is already being used by the proxy addresses or LegacyExchangeDN. Please choose another proxy address.
```

Of course, I'm not trying to create support@domain.com.au, I'm trying to create support@domain.co.uk

I don't want to have to delete the existing support email address.

Any ideas?

**Comment by abirtley** [comment]
Workaround - I *can* create a *distribution list* for support@domain.co.uk (rather than a second shared email).  This workaround is sufficient for my purposes, so I'm personally happy for the issue to be closed, but it may not be appropriate for other use cases.

**Comment by Cloud-Writer** [comment]
@abirtley, glad that you found a workaround you can use.
