### ISSUE TITLE
Information still correct about which Endpoint will be asked first?

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/OfficeDocs-Support#220]
As this article has a complete other order how Autodiscover is done: https://support.microsoft.com/en-us/help/3211279/outlook-2016-implementation-of-autodiscover

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4758d9-52a3-67e9-8e60-b7e503605f38
* Version Independent ID: 57c2f2b7-bceb-c884-495a-39d77d49b6bb
* Content: [Unexpected Autodiscover behavior if settings under the \Autodiscover key - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/unexpected-autodiscover-behavior#feedback)
* Content Source: [Microsoft365/admin/administration/unexpected-autodiscover-behavior.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/unexpected-autodiscover-behavior.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@myfope Thank you for your feedback. The document talks only about the autodiscoverbehaviour when you have the registry settings under the \Autodiscover key.

Whereas the support document talks about implementation-https://support.microsoft.com/en-us/help/3211279/outlook-2016-implementation-of-autodiscover

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@nam31 There are no changes required in the document.

Thanks
Sri
