### ISSUE TITLE
Reducing the spam classification value

### ISSUE THREAD

**Issue by aneubau** [MicrosoftDocs/OfficeDocs-Support#226]
I would recommend to change content and/or design of the e-mail for sending the verification code. Almost 100% of the receiver get it into their spam folder
---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c22f02e6-000b-ca44-2e72-78baeb7378cb
* Version Independent ID: 8e32d30e-05b0-df7d-af4f-fe4c0887c3c1
* Content: [Kein Verifizierungscode, wenn externe Empfänger auf freigegebene sichere Links zugreifen](https://docs.microsoft.com/de-DE/sharepoint/support/sharing-and-permissions/no-verification-code-to-access-shared-secure-link#feedback)
* Content Source: [SharePoint/SharePointOnline/sharing-and-permissions/no-verification-code-to-access-shared-secure-link.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sharing-and-permissions/no-verification-code-to-access-shared-secure-link.md)
* Service: **sharepoint-online**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by astera-cmorrison** [comment]
Some users report that they do not receive the email even in their spam or junk folders.

**Comment by dariomws** [comment]
Hello @aneubau,

Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/answers/products/m365).
