### ISSUE TITLE
Solution incomplète

### ISSUE THREAD

**Issue by dglecoq** [MicrosoftDocs/OfficeDocs-Support#229]
Bonjour,
J'ai le même problème à l'ouverture de Word dans un dossier OneDrive.
J'ai testé la solution indiquée dans cet article. La nouvelle clé de registre est bien enregistrée, mais il n'y aucune amélioration. J'ai redémarré le poste, aucune amélioration. J'ai Office 365 ProPlus, Windows 10, et une version Word pour Office 365 MSO 64 bits. 
Courage, ne lâchez rien :)
Daniel

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour docs.microsoft.com ➟ problème de liaison GitHub.*

* ID: ac9e4a61-582e-a7dd-18dd-2ec4aa752c04
* Version Independent ID: be69fff1-2970-dc24-7256-77c41cd0efa0
* Content: [Les applications Office demandent périodiquement les informations d’identification](https://docs.microsoft.com/fr-ca/office365/troubleshoot/authentication/office-prompt-for-credentials#feedback)
* Content Source: [Microsoft365/admin/authentication/office-prompt-for-credentials.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/authentication/office-prompt-for-credentials.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@dglecoq Thank you for your feedback. This document pertains to federated user accounts.  If that is the case, does it still happen In onedrive?

Thanks
Sri

**Comment by msbemba** [comment]
@dglecoq Wanted to circle back and check if the issue persists.

Thanks
Sri

**Comment by nam31** [comment]
@dglecoq We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
