### ISSUE TITLE
Backslash Character Labeled as "Pipe"

### ISSUE THREAD

**Issue by AutoGlass** [MicrosoftDocs/OfficeDocs-Support#23]
In the list of special characters it shows a backslash (\) character, but calls it the Pipe character.  I suspect neither special character would be an allowed character.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0638257c-2829-38a7-6bd7-799b96ca8761
* Version Independent ID: 051d257b-e558-7dce-3714-c70fd56eecaa
* Content: [Office 365 email address contains underscore character - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/active-directory/email-address-contain-underscore)
* Content Source: [Microsoft365/admin/active-directory/email-address-contain-underscore.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/active-directory/email-address-contain-underscore.md)
* Service: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Checking this problem.

**Comment by simonxjx** [comment]
The article is updated.
