### ISSUE TITLE
Showing "**Click Run" (extra asterisks appears) 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-Support#231]
![cannot-set-up-profile-autodiscover](https://user-images.githubusercontent.com/40815708/69472404-16d9bc80-0ded-11ea-8bb1-0a85aa1dc91b.png)

https://docs.microsoft.com/en-us/exchange/troubleshoot/outlook-profiles/cannot-set-up-profile-autodiscover

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de7f5ee-fe29-1cbc-fdf1-a29dce272aae
* Version Independent ID: f54cbcf4-bd8a-58ba-9c36-88d7864dbaf4
* Content: [Can't set up a new profile by using Exchange Autodiscover for Online mailbox - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/outlook-profiles/cannot-set-up-profile-autodiscover)
* Content Source: [Exchange/ExchangeOnline/outlook-profiles/cannot-set-up-profile-autodiscover.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/outlook-profiles/cannot-set-up-profile-autodiscover.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by hyoshioka0128** [comment]
@TinaMcN - Could you please explain a bit more about the reason of PR not being built? 
Thanks.

**Comment by simonxjx** [comment]
Updated.
