### ISSUE TITLE
Missing <Mailbox ID1> and <Mailbox ID2> within "In this command..." note

### ISSUE THREAD

**Issue by pwnflakes** [MicrosoftDocs/OfficeDocs-Support#233]
In this command, ??? represents the mailbox to which the user is granted permission and ??? is the mailbox of the user to whom you want to add full access permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aacc4cd-e080-bbcf-5e67-6a5658114252
* Version Independent ID: a48721b6-2300-d0bf-3541-d3f29ea1d37e
* Content: [Remove automapping for a shared mailbox - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/remove-automapping-for-shared-mailbox#feedback)
* Content Source: [Microsoft365/admin/administration/remove-automapping-for-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/remove-automapping-for-shared-mailbox.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Updated.
