### ISSUE TITLE
Creation of an ODBC 64 bit Access driver on top of Office 365 32 bit

### ISSUE THREAD

**Issue by castorfou** [MicrosoftDocs/OfficeDocs-Support#235]
Hello

Is there possible to install a 64-bit ODBC MS Access driver with 32-bit Office 365?
I have installed AccessDatabaseEngine_X64.exe and then I can use the 64-bit ODBC driver. But it creates some warning message each time I open office365 apps (outlook, excel, ...)
I have just switch AccessDatabaseEngine from 64-bit to 32-bit, the warning message has now gone but I don't have anymore the 64-bit ODBC driver.

Is there a way to do it properly?

**Comment by nam31** [comment]
@castorfou, can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you

**Comment by nam31** [comment]
@castorfou We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
