### ISSUE TITLE
Updated references for latest Visual Studio

### ISSUE THREAD

**Issue by EoMcDonald** [MicrosoftDocs/OfficeDocs-Support#236]
Would be good to have this page updated for Visual Studio 2019. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d97d229-5826-ef83-f3f2-b84056d5770f
* Version Independent ID: c6c9c555-3f49-c3da-3814-6a06f1bb293c
* Content: [How to automate Microsoft Word to create a new document by using Visual C# - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-developer/automate-word-create-file-using-visual-c#feedback)
* Content Source: [Office/Client/office-developer/automate-word-create-file-using-visual-c.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-developer/automate-word-create-file-using-visual-c.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by joinimran** [comment]
Hi @EoMcDonald, thank you for your feedback.
I am working on this issue and will provide you with an update soon

**Comment by joinimran** [comment]
Hello @EoMcDonald - I have checked and the whole document and it's fully compatible with Visual Studio 2019. All of the steps mentioned in the document are working fine. Please see the screenshot below

![image](https://user-images.githubusercontent.com/47118050/123774399-cd195800-d8e6-11eb-8b44-6cab741b89a6.png)

Also, as requested, we cannot update the document as Microsoft is not regularly updating this document. Please see the screenshot of the notification below.

![image](https://user-images.githubusercontent.com/47118050/123774549-f33ef800-d8e6-11eb-9d07-6dc07d8c63a7.png)

Thanks

@nam31 - FYI&A please.

**Comment by nam31** [comment]
@EoMcDonald Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
