### ISSUE TITLE
Does this include connectivity from smart host and other on-prem servers connecting to O365?

### ISSUE THREAD

**Issue by RaviD-Git** [MicrosoftDocs/OfficeDocs-Support#238]
Does this TLS depreciation include connectivity from smart host and other on-prem servers connecting to O365?
Am talking about Exchange admin center -&gt; Mail flow -&gt; Connectors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 753400c8-a0d3-4fdb-e819-e1eb8d2c9e58
* Version Independent ID: d13e562e-7cb8-8ee2-ba1e-66072e70f687
* Content: [Preparing for TLS 1.2 in Office 365 and Office 365 GCC - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/security/prepare-tls-1.2-in-office-365)
* Content Source: [Microsoft365/admin/security/prepare-tls-1.2-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/security/prepare-tls-1.2-in-office-365.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@RaviD-Git, this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@RaviD-Git We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
