### ISSUE TITLE
Another trick

### ISSUE THREAD

**Issue by s-sols** [MicrosoftDocs/OfficeDocs-Support#239]
It applies to PowerPoint 365 (2019) too :(

So, another trick is to create invisible object (e.g. rectangle with no line and fill) with "Appear" animation and delay equals to slide duration and put needed sound with "After Previous" animation after that object. Note that "Play Across Slides" should be checked in the sound's settings to play it in parallel with transition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c48ef92-0783-aed5-93d9-0ee2c2407844
* Version Independent ID: 77db357d-bde5-19e0-0b8c-69885ee059b4
* Content: [Slide transition sounds missing - Office](https://docs.microsoft.com/en-us/office/troubleshoot/powerpoint/slide-transition-sounds-missing)
* Content Source: [Office/Client/powerpoint/slide-transition-sounds-missing.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/powerpoint/slide-transition-sounds-missing.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Luke-Robinett** [comment]
Thank you but we shouldn't have to resort to these clumsy workarounds. It's especially impractical when you have a large slideshow.

**Comment by s-sols** [comment]
It's the one way to get the right result if you need a video. So, as you say "clumsy workarounds" are converted to working solutions until you fix the standard way in Office.

**Comment by nam31** [comment]
@s-sols Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
