### ISSUE TITLE
Solution to hide blank emails from PersonMetadata folder

### ISSUE THREAD

**Issue by servicesenthydro** [MicrosoftDocs/OfficeDocs-Support#24]
If you right-click on the Search Folder, click Customize This Search Folder, click Browse, and deselect the option to Search Subfolders (and manually select the folders you wish to include), it will avoid listing the 'blank emails' from the hidden subfolder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5438283-95e8-9a36-a211-1cc104349217
* Version Independent ID: c6c42db1-7942-629c-de07-ecf2513d6f1f
* Content: [Outlook search folders show unexpected mail items with an empty subject - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/search-folders/personmetadata-items#feedback)
* Content Source: [Outlook/Client/search-folders/personmetadata-items.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/search-folders/personmetadata-items.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Cloud-Writer** [comment]
@servicesenthydro, thank you so much for helping us improve the article. Your suggestion has been added to the article.

**Comment by patchwolf** [comment]
Better: If you right-click the Search Folder, click Customize This Search Folder, click Criteria, then the Advanced tab.  Click the Fields button, and select "In Folder" from the "All mail fields" flyout.  Set the criteria to "doesn't contain" and enter `PersonMetadata` in the value field.  This will retain your search folders will avoid listing the 'blank emails'.

**Comment by PReinie** [comment]
Patchwolf, I was wondering how to do that. Instead I was using "in folder" "does not contain" "PersonMetadata" but  that didn't seem to work right.

I think your method will eliminate emails about PersonMetadata too, correct? (Such as if you and I were discussing PersonMetadata via email.)

Instead, I used criteria "From" "is not empty", as all PersonMetadata message have an empty from field. (Messages can be sent or received with other address fields or the subject empty, but they always have a From field.)

My criteria will also eliminate messages in folders listing (logging) errors or about sync issues, but they probably aren't needed for the searches most people would do.
