### ISSUE TITLE
No DataFetch timeout option for 64-bit Access on 64 Bit Windows?

### ISSUE THREAD

**Issue by djroller1** [MicrosoftDocs/OfficeDocs-Support#240]
Would be helpful if page included references for 64-bit Access on 64-bit windows.   Even if there is no regedit option for 64-Bit Access, it would be helpful to at least acknowledge that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 595c6435-a58f-b2bf-d2c8-46aecf9eaac3
* Version Independent ID: 69bc2d69-b171-6a33-3771-9a5845a7c134
* Content: [Issues when you retrieve SharePoint list data - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/retrieve-sharepoint-list-in-access#feedback)
* Content Source: [Office/Client/access/retrieve-sharepoint-list-in-access.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/retrieve-sharepoint-list-in-access.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@djroller1, this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@djroller1 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
