### ISSUE TITLE
Also can happen when there is a corrupt value in a field or change to list schema

### ISSUE THREAD

**Issue by djroller1** [MicrosoftDocs/OfficeDocs-Support#242]
When there is a change to list schema - especially a change to field type or field size where an pre-change value exists in the list that isn't compatible with the newest setting.   For example a change to field size or  change from plain text to choice can sometime cause this if an existing list value isn't compatible.  Seems to go away if I relink or drop and recreate connection to list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35517558-5b9a-6a86-ea69-afee68a7abe5
* Version Independent ID: 960971db-75f3-0733-1db1-1a1b8667e913
* Content: [Access linked table to a SharePoint list returns Deleted - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/access-linked-table-return-deleted)
* Content Source: [Office/Client/access/access-linked-table-return-deleted.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/access-linked-table-return-deleted.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@djroller1, this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@djroller1 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
