### ISSUE TITLE
Steps for outlook web interface are wrong, (old version?)

### ISSUE THREAD

**Issue by frankhaugen** [MicrosoftDocs/OfficeDocs-Support#244]
The steps outlined in this article does not match the current user interface:
![image](https://user-images.githubusercontent.com/13543585/70236553-6e6d1600-1765-11ea-8e1e-243e74dc211b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 227c2f2b-6bda-f2e9-4b6e-afafe81e4527
* Version Independent ID: 8bbf5f26-e6c2-460b-dadd-bed855c0d77d
* Content: [STOREDRV.Deliver.Exception:ObjectNotFoundException.MapiExceptionNotFound - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/mail-delivery/mapiexceptionnotfound-ndr)
* Content Source: [Exchange/ExchangeOnline/mail-delivery/mapiexceptionnotfound-ndr.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/mail-delivery/mapiexceptionnotfound-ndr.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MurtazK** [comment]
I approve. The option is only available in Classic view.
Here is the link to open outlook 365 in classic mode and test > https://outlook.office365.com/owa/?path=/classic
***Please revisit the information provided on this page.
Thank you!

**Comment by nam31** [comment]
@frankhaugen, this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@frankhaugen We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
