### ISSUE TITLE
Where is the actual workaround.

### ISSUE THREAD

**Issue by davidpietz** [MicrosoftDocs/OfficeDocs-Support#245]
You describe a scenario where some columns in a spreadsheet have been merged causing a malfunction when trying to sort the spreadsheet.  You spend the rest of the article under the heading of "Workaround".  2 problems:  1.  The workaround shows only how to reproduce the problem, not how to fix or workaround it.  2. The scenario is incomplete for my situation is not included:  My merging ocurred during a download so I have no confidence that your workaround, which you dont provide, will help me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0ef33ee-f9d1-a2fc-d747-dd134f7a7b38
* Version Independent ID: 159ba786-e8c2-a963-894e-7acb09cb7d65
* Content: [An error message when you sort a range that contains merged cells in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/error-sort-a-range-merged-cell#feedback)
* Content Source: [Office/Client/excel/error-sort-a-range-merged-cell.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/error-sort-a-range-merged-cell.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
The article has been updated with more information.
