### ISSUE TITLE
Riddled with errors

### ISSUE THREAD

**Issue by BicycleBuck** [MicrosoftDocs/OfficeDocs-Support#246]
Thank you for the informative article, but you should be aware that it is filled with spelling and punctuation errors. Corrections would go a long way toward establishing credibility.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d36769ab-395f-261a-4cf8-8c0645cf40c7
* Version Independent ID: 2866abcb-42db-d58f-4f81-97f9070ea94e
* Content: [Tasks are not scheduled as expected in Microsoft Project - Office](https://docs.microsoft.com/en-us/office/troubleshoot/project/tasks-not-scheduled#feedback)
* Content Source: [Office/Client/project/tasks-not-scheduled.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/project/tasks-not-scheduled.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@BicycleBuck, this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@BicycleBuck We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
