### ISSUE TITLE
Can you open in app PBIX files

### ISSUE THREAD

**Issue by microsoftsearch** [MicrosoftDocs/OfficeDocs-Support#247]
I have powerbi files stored in sharepoint and when I click to open in app, instead of opening the file in the powerbi desktop application, it downloads the pbix file. Is this supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d2410e2-6e38-59a3-c528-e5ba3becd1ff
* Version Independent ID: 0f3d3418-944b-1f96-7047-e453acf687b0
* Content: [A SharePoint Online list item attachment doesn't open in the Office client app - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/lists-and-libraries/office-app-fails-opening-list-item-attachment)
* Content Source: [SharePoint/SharePointOnline/lists-and-libraries/office-app-fails-opening-list-item-attachment.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/lists-and-libraries/office-app-fails-opening-list-item-attachment.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. The **Open in the client application** function works for Office related applications.
