### ISSUE TITLE
Microsoft Access from C#: wrong displayed code language

### ISSUE THREAD

**Issue by SunSerega** [MicrosoftDocs/OfficeDocs-Support#248]
Language of code samples is displayed as `SQL`, while it's clearly `C#`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 700a9caf-6faf-2ebe-6f94-7221c574dbe1
* Version Independent ID: f0c6c288-4623-f26b-70a5-a4caa267dbd2
* Content: [How to automate Microsoft Access by using Visual C# - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-developer/automate-access-using-visual-c)
* Content Source: [Office/Client/office-developer/automate-access-using-visual-c.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-developer/automate-access-using-visual-c.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The language type is updated. Thanks for your comment.
