### ISSUE TITLE
Outlook Reset Preferences tool.

### ISSUE THREAD

**Issue by jnandakumar** [MicrosoftDocs/OfficeDocs-Support#249]
Running this tool displays "Recent addresses cleared".
It did not solve my Spell check not functioning problem

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a55b51-85d6-f628-581c-5a1c66675933
* Version Independent ID: 9f626f3a-123d-67ca-3aa8-a3443963fe05
* Content: [Outlook for Mac support tools. - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/outlook-for-mac/useful-tools#feedback)
* Content Source: [Outlook/OutlookExperts/outlook-for-mac/useful-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/OutlookExperts/outlook-for-mac/useful-tools.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your feedback. I think you can reach https://support.office.com/outlook for help.
