### ISSUE TITLE
The bat file cannot be executed

### ISSUE THREAD

**Issue by zzjjbb** [MicrosoftDocs/OfficeDocs-Support#25]
All the CRLF is lost and all the code is in one line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95d45540-ec98-57d5-7ef3-0190c64d164e
* Version Independent ID: 1b33de41-c3b6-35bc-840f-085007fc3b71
* Content: [How to switch from Semi-Annual Channel to Monthly Channel for the Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/switch-channel-for-office-365#feedback)
* Content Source: [Microsoft365/admin/administration/switch-channel-for-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/switch-channel-for-office-365.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by TroutZhang** [comment]
Yes, I just need to switch channels and tried, it only worked after I added line breaks myself.
When I tried to file a PR, I found there is one already addressing this issue:
https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/20/commits

**Comment by maazirfan007** [comment]
can you share the correct script with line breaks added?

**Comment by zzjjbb** [comment]
setlocal

reg query HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration\ /v CDNBaseUrl
if %errorlevel%==0 (goto SwitchChannel) else (goto End)

:SwitchChannel
reg add HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration /v CDNBaseUrl /t REG_SZ /d "https://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60" /f
reg delete HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration /v UpdateUrl /f
reg delete HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration /v UpdateToVersion /f
reg delete HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Updates /v UpdateToVersion /f
reg delete HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Office\16.0\Common\OfficeUpdate\ /f

:End
Endlocal

**Comment by zzjjbb** [comment]
> can you share the correct script with line breaks added?

I think it should be like this, and the script seems more like a cmd .bat file rather than a powershell code

**Comment by maazirfan007** [comment]
Thank you very much

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jlriesco** [comment]
The comment is correct and the correct script is in the comments. The script that is in the section for Powershell does not have any line breaks and they are needed. The Copy button should return this:

setlocal

reg query HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration\ /v CDNBaseUrl
if %errorlevel%==0 (goto SwitchChannel) else (goto End)

:SwitchChannel
reg add HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration /v CDNBaseUrl /t REG_SZ /d "https://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60" /f
reg delete HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration /v UpdateUrl /f
reg delete HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration /v UpdateToVersion /f
reg delete HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Updates /v UpdateToVersion /f
reg delete HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Office\16.0\Common\OfficeUpdate\ /f

:End
Endlocal

I will get this article updated and republished. 
Thank you,
Jose
