### ISSUE TITLE
These instrux dont work for Mac Catalina 10.15.1 and Outlook 16.31

### ISSUE THREAD

**Issue by jgemmill** [MicrosoftDocs/OfficeDocs-Support#250]
I have tried each/all of these as well as many other suggestions found online and am still having exactly the same problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a55b51-85d6-f628-581c-5a1c66675933
* Version Independent ID: 9f626f3a-123d-67ca-3aa8-a3443963fe05
* Content: [Outlook for Mac support tools. - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/outlook-for-mac/useful-tools#feedback)
* Content Source: [Outlook/OutlookExperts/outlook-for-mac/useful-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/OutlookExperts/outlook-for-mac/useful-tools.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your feedback. I think you can reach https://support.office.com/outlook for help.
