### ISSUE TITLE
But, but, this is not the desired behavior..

### ISSUE THREAD

**Issue by cheezewhizze** [MicrosoftDocs/OfficeDocs-Support#252]
Intention is to have the user be prompted for credentials in the normal AAD way. Is what is described here a "resolution" or a "workaround"? Or is there a different, better way to do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50267c3e-8463-7640-3ba6-4c2f99aaa1a8
* Version Independent ID: c89aab7f-cc76-5689-2d79-757b1daa06c7
* Content: [Linked table connection failed when using Azure AD interactive authentication - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/linked-table-connection-failed#feedback)
* Content Source: [Office/Client/access/linked-table-connection-failed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/linked-table-connection-failed.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by JChivallOBT** [comment]
I've been able to work around this issue by adding "UID=;" to the end of the ODBC connection string in Linked Table Manager. Forcing a null UID in this way seems to placate the ODBC driver and allow the desired behaviour of prompting for user sign in through ADAL

**Comment by nam31** [comment]
@cheezewhizze, this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@cheezewhizze We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you
