### ISSUE TITLE
Old article

### ISSUE THREAD

**Issue by kellybos** [MicrosoftDocs/OfficeDocs-Support#254]
Network traces are not very helpful for Outlook. There's also a reference to Dedicated/ITAR in the subject line. My recommendation would be to archive this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bde6ec33-50b7-e519-e639-d4ffd2e629ce
* Version Independent ID: 0e070d41-860d-73d0-ed0f-4ddea3ccb4ea
* Content: [Collect Network Monitor trace in O365 Dedicated/ITAR - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/support/collect-network-monitor-trace#feedback)
* Content Source: [Microsoft365/admin/support/collect-network-monitor-trace.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/support/collect-network-monitor-trace.md)
* Service: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@kellybos, this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by kellybos** [comment]
Office Dedicated/ITAR is no longer a valid offering. This article should be archived.
