### ISSUE TITLE
How to match blank cells in common matching and lookup formulas?

### ISSUE THREAD

**Issue by clarpaul** [MicrosoftDocs/OfficeDocs-Support#256]
How to match blank cells in these formulas?
∙ SUMIF() / COUNTIF()
∙ HLOOKUP / VLOOKUP()
∙ MATCH()
∙ DCOUNT()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d37aacf0-7de2-a24f-2314-c798bc580b77
* Version Independent ID: 587eb6d2-f47f-fec7-c8e5-2db05cd1a291
* Content: [Create a formula to correctly evaluate blank cells - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/use-formula-evaluate-blank-cell?source=docs#feedback)
* Content Source: [Office/Client/excel/use-formula-evaluate-blank-cell.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/use-formula-evaluate-blank-cell.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by joinimran** [comment]
Hi @clarpaul, thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by joinimran** [comment]
Hi @clarpaul, Following details how to use these formulas
SUMIF(): Select a blank cell, copy and paste the formula =SUMIF(B2:B7,"<>"&"",A2:A7) ( B2:B7 is the data range which contains the text cells, and A2:A7 is the data you want to sum) into the Formula Bar, then press Ctrl + Shift + Enter keys.

COUNTIF(): Type =COUNTIF(range,""), replacing range with your chosen cell range.

HSLOOKUP(): = To lookup and retrieve the first text value across a range of columns, you can use the HLOOKUP function with a wildcard. In the example shown, the formula in F5 is HLOOKUP("*",C5:E5,1,0)

DCOUNT(): DCOUNT(B7:E14,4,B4:E5) // field by index

**Comment by nam31** [comment]
@clarpaul Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
