### ISSUE TITLE
Great article. One correction. One suggestion.

### ISSUE THREAD

**Issue by 6StringJazzer** [MicrosoftDocs/OfficeDocs-Support#257]
This is one of the best treatments of this topic I have seen, and the best one specific to Excel. I wish more users would read this. 

I do have one correction to suggest:
"Infinities occur when you divide by 0." This is not true mathematically. The operation of division is not defined for a zero divisor. The claim that the result is infinity is a popular misconception.

"Bias is the bias value used to avoid having to store negative exponents." This is a circular definition; I still don't know what bias is. A bit more explanation is warranted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164a5098-e3e4-7666-b6bc-53072113ded3
* Version Independent ID: 85d54834-d3b8-7428-dc92-92db3973577a
* Content: [Floating-point arithmetic may give inaccurate result in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/floating-point-arithmetic-inaccurate-result)
* Content Source: [Office/Client/excel/floating-point-arithmetic-inaccurate-result.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/floating-point-arithmetic-inaccurate-result.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by joinimran** [comment]
Hi @65Stringjazzer, thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by joinimran** [comment]
Hi @6StringJazzer, thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by helenclu** [comment]
More information about bias can be found at [https://en.wikipedia.org/wiki/Exponent_bias](https://en.wikipedia.org/wiki/Exponent_bias).

About division by zero, see [https://stackoverflow.com/questions/14682005/why-does-division-by-zero-in-ieee754-standard-results-in-infinite-value](https://stackoverflow.com/questions/14682005/why-does-division-by-zero-in-ieee754-standard-results-in-infinite-value).

**Comment by 6StringJazzer** [comment]
Thank you, but I was not asking for a personal explanation. I was suggesting the article be improved with a better explanation. For example, instead of this circular definition:

 

Bias is the bias value used to avoid having to store negative exponents. 

 

Say this

 

Bias is the an offset from the actual exponent value used to store the exponent as an unsigned value. 

 

And instead of this

 

*         Positive/Negative Infinities: Infinities occur when you divide by 0. Excel does not support infinities, rather, it gives a #DIV/0! error in these cases.

 

Say this

 

*         Positive/Negative Infinities: When you divide by 0, IEEE 754 requires the result to be stored as infinity (although mathematical convention considers this result to be undefined). Excel does not support infinities, rather, it gives a #DIV/0! error in these cases.

 

 

 

Jeff Seigle
