### ISSUE TITLE
Wow, really?

### ISSUE THREAD

**Issue by jim88888** [MicrosoftDocs/OfficeDocs-Support#258]
I have to write a script to do something that Microsoft was too lazy to do? Really?  

*eyerolls* 

This should be a native option.  It's not that hard guys.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92765388-a22b-7311-8764-e8b065a0569e
* Version Independent ID: d02626a0-1eb2-1e62-efa5-519676f527a7
* Content: [Export a text file with both comma and quote delimiters in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/export-text-file-with-comma-quote#feedback)
* Content Source: [Office/Client/excel/export-text-file-with-comma-quote.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/export-text-file-with-comma-quote.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by linhartr22** [comment]
How do I upvote this?
