### ISSUE TITLE
Needs to be updated

### ISSUE THREAD

**Issue by deshyde** [MicrosoftDocs/OfficeDocs-Support#26]
Using objApp = New Excel.Application() within the office "365proplus" environment does not work
The below error is shown
System.Runtime.InteropServices.COMException (0x80070490): Retrieving the COM class factory for component with CLSID {00024500-0000-0000-C000-000000000046} failed due to the following error: 80070490 Element not found. (Exception from HRESULT: 0x80070490).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4d1788-af80-29f4-838d-4f7e92a28b89
* Version Independent ID: 2edbb4f4-3201-086d-3f04-b63e6941bb43
* Content: [Automate Excel from Visual Basic .NET to fill or obtain data by using arrays - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-developer/automate-excel-from-visual-basic-net#feedback)
* Content Source: [Office/Client/office-developer/automate-excel-from-visual-basic-net.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-developer/automate-excel-from-visual-basic-net.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Checking this.

**Comment by jlriesco** [comment]
(objApp = New Excel.Application() within the office "365proplus" environment) should work. Looks like some previous Office installs or something has left the registry in a bad state at the user’s machine.
