### ISSUE TITLE
Report generated from MSProject

### ISSUE THREAD

**Issue by silvaniaalmeida** [MicrosoftDocs/OfficeDocs-Support#260]
Missing to describe how to share reports generated in MSProject into to Sharepoint

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6c31962-c894-f081-9f1a-3e73a4333ebc
* Version Independent ID: c35a6c06-91ee-32d1-f2b3-01d1e64beed8
* Content: [Sync with SharePoint tasks list from Project Professional - Office](https://docs.microsoft.com/en-us/office/troubleshoot/project/sync-with-tasks-from-project#feedback)
* Content Source: [Office/Client/project/sync-with-tasks-from-project.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/project/sync-with-tasks-from-project.md)
* Product: **project-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@silvaniaalmeida That info is described in [this article](https://support.microsoft.com/en-us/office/sync-with-a-sharepoint-tasks-list-fb956d2c-723d-4d5a-b7e5-710ef82aa27a), which is contained by the article you linked. 

Do you feel like extra information is needed? If yes, which exactly?

**Comment by VLG17** [comment]
@silvaniaalmeida Any update?

**Comment by nam31** [comment]
@silvaniaalmeida We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
