### ISSUE TITLE
So what is the new method for deselecting a cell?

### ISSUE THREAD

**Issue by misterleif** [MicrosoftDocs/OfficeDocs-Support#262]
Why would you replace a working and useful method with something as esoteric as you describe? You need to restore the original function and come up with a new way to trigger this new functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ebdf7f7-c355-5815-5682-499e3d0ee0a8
* Version Independent ID: 9ebfbf70-4ab4-1bee-d17b-f7e256c60851
* Content: [Cell shading continually darkens - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/cell-shading-continually-darkens#feedback)
* Content Source: [Office/Client/excel/cell-shading-continually-darkens.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/cell-shading-continually-darkens.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@misterleif The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content ?
Thank you.

**Comment by nam31** [comment]
@misterleif We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
