### ISSUE TITLE
Odd reference..

### ISSUE THREAD

**Issue by trlinde** [MicrosoftDocs/OfficeDocs-Support#263]
Found it odd I was sent by Details to a page referencing Office 2013 when it regards office 2016.
Still relevant. Although never mentions later office versions directly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a8969a-2a7b-f254-4f64-ecd44ac6e8e3
* Version Independent ID: b1f12577-2c6f-5abd-ba52-22acd348e25b
* Content: [Apps for Office don't start if you disable protected mode for  Restricted Sites zone - Office](https://docs.microsoft.com/en-us/office/troubleshoot/error-messages/apps-for-office-not-start#feedback)
* Content Source: [Office/Client/error-messages/apps-for-office-not-start.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/error-messages/apps-for-office-not-start.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by vtzimpl** [comment]
I cannot see how this is relevant with IE. I use O365 and this error is without solution for almost a year.

ADD-IN ERROR

Add-ins are currently blocked to help protect the
security of your computer. Click "See Details" to
learn how to fix this issue.

**Comment by stephenboothuk** [comment]
My thought as well, the article isn't about the message I'm getting.  I'm also getting the Add-In error that vtzimpk is reporting above.  I have protected mode enabled for restricted zone.

**Comment by nam31** [comment]
@trlinde We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you
