### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by kaiznet** [MicrosoftDocs/OfficeDocs-Support#264]
New message window doesn't appear after marking task as completed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c5e49c3-1e2d-d7d1-6108-4b0cff21833c
* Version Independent ID: faf28500-6177-d906-86cd-0fc1ef6e71f4
* Content: [How to create a recurring e-mail message in Outlook - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/email-messages/create-recurring-email#feedback)
* Content Source: [Outlook/Client/email-messages/create-recurring-email.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/email-messages/create-recurring-email.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@kaiznet This article has been retired because the content was very old and didn’t apply to the versions of Outlook still in Support.
Thank you
