### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by AshrafAlam** [MicrosoftDocs/OfficeDocs-Support#266]
The following link is broken:
2829747 Android smartphone devices that are supported for use with Skype for Business for Android.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 061c6c9a-3f11-0730-770f-b36fbc932d5e
* Version Independent ID: b2159344-8d61-db66-b626-f2988c730622
* Content: [Troubleshooting issues with Microsoft Skype for Business for Android - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/server-mobile-devices/issues-for-android)
* Content Source: [SkypeforBusiness/SkypeServer/server-mobile-devices/issues-for-android.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeServer/server-mobile-devices/issues-for-android.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The link is removed. Thanks.
