### ISSUE TITLE
Backslash () is missing the Backslash!!

### ISSUE THREAD

**Issue by walvisam** [MicrosoftDocs/OfficeDocs-Support#267]
Hello team, I was working on a case where admin can't create UPN with certain characters, so searching in this article, we notices the Backslash (\)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77f5b607-30cb-0c3c-d099-d41567e29773
* Version Independent ID: 55c37b8d-0cea-0b7e-4a31-da0968f1be87
* Content: [Error when you create a user name that contains a special character - Office](https://docs.microsoft.com/en-us/office/troubleshoot/error-messages/username-contains-special-character)
* Content Source: [Office/Client/error-messages/username-contains-special-character.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/error-messages/username-contains-special-character.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
As you can see, backslash is not permitted in user names. Thanks for your comment.

**Comment by LegoSCCMGuy** [comment]
simonxjx there is a commit request to update the issue mentioned above.
