### ISSUE TITLE
Needs to run ad Administrator

### ISSUE THREAD

**Issue by kerbos** [MicrosoftDocs/OfficeDocs-Support#268]
Can you add a similar Note about running with Admin privileges that exists on this page for ospp.vbs? Thanks!
https://docs.microsoft.com/en-us/deployoffice/vlactivation/tools-to-manage-volume-activation-of-office

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccd05f29-a421-2a25-2ce2-25e561331730
* Version Independent ID: 977f14f7-b6be-4ccc-ad9f-8dc3fcef3d8d
* Content: [Reset Office 365 ProPlus activation state - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/activation/reset-office-365-proplus-activation-state#feedback)
* Content Source: [Microsoft365/admin/activation/reset-office-365-proplus-activation-state.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/activation/reset-office-365-proplus-activation-state.md)
* Service: **o365-solutions**
* GitHub Login: @MJP-MSFT
* Microsoft Alias: **mattphil**

**Comment by msbemba** [comment]
@kerbos Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1615

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1615 
Thank you
