### ISSUE TITLE
Method 8 steps make no sense

### ISSUE THREAD

**Issue by JulietteLaurier** [MicrosoftDocs/OfficeDocs-Support#269]
Please review - the steps make no sense. https://docs.microsoft.com/en-us/office/troubleshoot/word/issues-when-start-or-use-word#method-8-change-the-default-printer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be46645d-dbd2-f1f8-089d-de61c678807f
* Version Independent ID: 5945f781-2560-84f0-494e-2473b9537939
* Content: [How to troubleshoot problems that occur when you start or use Word - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/issues-when-start-or-use-word#method-8-change-the-default-printer)
* Content Source: [Office/Client/word/issues-when-start-or-use-word.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/issues-when-start-or-use-word.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Ronsss** [comment]
Word is very dependent on printer drivers. So I can see how a problem in the printer drivers could cause problems in Word. 

My question is, why would these instructions suggest using a reg hack instead of the Windows GUI to set the default printer?

**Comment by MaratMussabekov** [comment]
Hello @JulietteLaurier , @Ronsss ,
it seems like the issue was that it was copy pasted from another step and then wasn't edited properly.
I created a PR to fix it.
Thank you

**Comment by nam31** [comment]
Closing via #1531 
Thank you
