### ISSUE TITLE
Wrong url for this page

### ISSUE THREAD

**Issue by Chaz6** [MicrosoftDocs/OfficeDocs-Support#271]
This page should have the url https://docs.microsoft.com/en-gb/office/troubleshoot/excel/laa-capability-change because the title is "Large Address Aware [..]".

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 128b1af9-4024-a3f9-2e91-053afacd5d45
* Version Independent ID: 3c6de6c1-4e87-fd32-fbe0-bd663ebe939c
* Content: [Large Address Aware capability change for Excel - Office](https://docs.microsoft.com/en-gb/office/troubleshoot/excel/lla-capability-change#feedback)
* Content Source: [Office/Client/excel/lla-capability-change.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/lla-capability-change.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The URL is updated. Thanks.
