### ISSUE TITLE
Step 1 link no longer references CDNBaseURL list

### ISSUE THREAD

**Issue by microsoftsearch** [MicrosoftDocs/OfficeDocs-Support#272]
The link in step 1 used to link to an article with the CDNBaseURL's in a list for all four and now the article it links to no longer contains the CDNBaseURL's. Am I missing the location of the CDNBaseURL's in the other link or can this be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95d45540-ec98-57d5-7ef3-0190c64d164e
* Version Independent ID: 1b33de41-c3b6-35bc-840f-085007fc3b71
* Content: [How to switch from Semi-Annual Channel to Monthly Channel for the Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/switch-channel-for-office-365#feedback)
* Content Source: [Microsoft365/admin/administration/switch-channel-for-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/switch-channel-for-office-365.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The article is moved to https://docs.microsoft.com/en-nz/deployoffice/change-update-channels. Please check.
