### ISSUE TITLE
Excel Day Zero (1900 system)

### ISSUE THREAD

**Issue by HelmZalee** [MicrosoftDocs/OfficeDocs-Support#273]
From the docs: "In the 1900 date system, the first day that is supported is January 1, 1900. When you enter a date, the date is converted into a serial number that represents the number of elapsed days since January 1, 1900." But: 
  Dim yada as Single
  yada = cdate("1/1/1900 0:30:00AM")
  ?yada => 2.020833

Didn't Knuth say Counting Starts at Zero?  Or was it two?
BTW, what is the difference between a "serial number" and a plain old number?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8462f7c-3fcb-c891-cca9-8c1ff894d4b0
* Version Independent ID: 78b5d0d6-6de5-e495-20a6-c5b9c34046f7
* Content: [Differences between the 1900 and the 1904 date system - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/1900-and-1904-date-system)
* Content Source: [Office/Client/excel/1900-and-1904-date-system.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/1900-and-1904-date-system.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments. For this case, I think you can contact https://support.office.com/excel for help.
