### ISSUE TITLE
TLS 1.0 seems to be deprecated for some service already - Status?

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/OfficeDocs-Support#274]
The information available around when Ms are to deprecating TLS 1.0 and 1.1 are... inconsistant.

This docs says that forced TLS 1.2 will happen in June 2020:

* https://docs.microsoft.com/en-us/office365/troubleshoot/security/prepare-tls-1.2-in-office-365#more-information

Yet a customer reports that one of their addons to Office 365 named "Evoko Room Manager" has stopped working due to TLS 1.0 not being supported anymore. Evoko has a support article about this:

* https://support.evoko.se/hc/en-us/articles/360036551491-Office-365-connection-issues

While a different addon, "Templafy" is still working over older TLS versions.

Whats the actual correct information here?

* Have you started deprecating TLS 1.0 and 1.1 for some services or some tenants?
* Is it a staged rollout per tenant? Where can we see this status?
* Is it a staged rollout per service (Exchange, Teams, Skype for Business etc.)? Whats the dates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 753400c8-a0d3-4fdb-e819-e1eb8d2c9e58
* Version Independent ID: d13e562e-7cb8-8ee2-ba1e-66072e70f687
* Content: [Preparing for TLS 1.2 in Office 365 and Office 365 GCC - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/security/prepare-tls-1.2-in-office-365#more-information)
* Content Source: [Microsoft365/admin/security/prepare-tls-1.2-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/security/prepare-tls-1.2-in-office-365.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by claudialake** [comment]
Office 365 will be starting the retirement of TLS 1.0 and 1.1 on January 15th, 2020 in GCC-High and DoD environments.As previously communicated (MC126199 in Dec 2017, MC128929 in Feb 2018 and MC186827 in July 2019), we are moving all of our online services to Transport Layer Security (TLS) 1.2+ to provide best-in-class encryption, and to ensure our service is more secure by default.Keeping on track with this promise – Office 365 will be retiring TLS 1.0 and 1.1 starting January 15, 2020 in GCC-High and DoD environments[How does this impact me?]Starting January 15, 2020, Office 365 will begin retiring TLS 1.0 and 1.1. This means that all connections to Office 365 using the protocols TLS 1.0 and TLS 1.1 will not work. [What should I do to prepare for this change?] Update or replace clients and devices that rely on TLS 1.0 and 1.1 to connect to Office 365, prior to January 15, 2020. More info [here](https://support.microsoft.com/help/4341731/deprecating-tls-1-0-and-1-1-in-o365-gcc-high-and-dod-for-tls-1-2).
