### ISSUE TITLE
Open with Explorer - only valid for Internet Explorer

### ISSUE THREAD

**Issue by evandimsby** [MicrosoftDocs/OfficeDocs-Support#275]
The option for "Open with Explorer" is only available when using Internet Explorer. Other browsers like Chrome, Edge, or Firefox do not show this as an option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41b7e3ce-33fc-5070-367b-4ff58f39d8a6
* Version Independent ID: deb49775-aa8a-1069-42ce-ee0b6dc91b49
* Content: [Using Open with Explorer command to troubleshoot issues in SharePoint Online - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/Lists-and-libraries/troubleshoot-issues-using-open-with-explorer)
* Content Source: [SharePoint/SharePointOnline/lists-and-libraries/troubleshoot-issues-using-open-with-explorer.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/lists-and-libraries/troubleshoot-issues-using-open-with-explorer.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The "Open with Explorer" is only available in IE. If you want to use other web browsers, such as Chrome. You can use a Google Extension called [IE Tab](https://chrome.google.com/webstore/detail/ie-tab/hehijbfgiekmjfkfjpbkbammjbdenadd/related?hl=en).
