### ISSUE TITLE
Excel - Year 1900 Leap Year Bug

### ISSUE THREAD

**Issue by PaulMargus** [MicrosoftDocs/OfficeDocs-Support#276]
Since its earliest versions, Microsoft Excel has incorrectly considered 1900 to be a leap year.  It erroneously inserts February 29, 1900 between February 28 and March 1.  Microsoft did this deliberately for backward compatibility with Lotus 1-2-3.  There were good business reasons to do this.   Microsoft lists valid reasons for perpetuating this bug.

However, I believe that most of these reasons disappear if Excel were switched to the convention used in Microsoft Access:
•	For Thu, 1900-03-01 (day number 61) through Fri, 9999-12-31 (day number 2,958,465), the Access convention is compatible with existing Excel.   For these dates, Excel would remain unchanged.
•	Wed, 1900-02-29 (no day number) would no longer exist. 
•	Mon, 1900-01-01 (day number 2) through Wed, 1900-02-28 (day number 60) would be incompatible with existing Excel.
•	Note the dates Sat, 1899-12-30 (day number 0) and Sun, 1899-12-31 (day number 1).
•	Fri, 0100-01-01 (day number -657,434) through Fri, 1899-12-29 (day number -1) would be a great bonus.

Applying the "Access" proposal to Excel, ...
•	Thu, 1900-03-01 and all subsequent dates would be unaffected.  
•	Although dates in January and February 1900 would be broken, it is doubtful that very many users would care.  Under the existing scheme, this interval is already defective and probably useless.   For example, consider Wed, 1900-02-28.   Using "ddd, yyyy-mm-dd" format, Excel now erroneously indicates Tuesday ("Tue, 1900-02-28").

This would be a useful change for various historical studies.  Besides listing the births and deaths of 19th century poets, consider http://www.nber.org/papers/w13567, in which Confederate war bond prices are analyzed.   Because Excel allows totally useless dates such as Thu, 7654-12-31, it should at least allow potentially useful 19th Century dates.   

Of course, Access blithely extrapolates the Gregorian Calendar back to the year 100.   Obviously, the Julian and other calendars have been used.   But this would still be a great improvement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e28dce76-cc6a-3af7-b51b-48ea6ba8b3ef
* Version Independent ID: c691ecbb-6184-a73b-2f25-2d72eccd8a14
* Content: [Excel incorrectly assumes that the year 1900 is a leap year - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/wrongly-assumes-1900-is-leap-year#feedback)
* Content Source: [Office/Client/excel/wrongly-assumes-1900-is-leap-year.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/wrongly-assumes-1900-is-leap-year.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by nam31** [comment]
@PaulMargus Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
