### ISSUE TITLE
Proxy not running

### ISSUE THREAD

**Issue by kdreally** [MicrosoftDocs/OfficeDocs-Support#277]
#Cause

Proxy has been configured but proxy is not running.

#Solution

1. Take the steps to start the proxy and try again.  OR
2. Determine current proxy by executing (in powershell run as administrator)

        netsh winhttp show proxy

3. From here, you can reset the proxy settings

        netsh winhttp reset proxy

4. OR you can change the proxy to something else (in the example 127.0.0.1:8888)

        netsh winhttp set proxy "127.0.0.1:8888"

5. OR you can import the proxy settings from internet explorer (assuming you are able to access the internet from Internet Explorer)

        netsh winhttp import proxy source=ie

#References

1. http://woshub.com/using-powershell-behind-a-proxy/
2. https://support.microsoft.com/en-us/help/900935/how-the-windows-update-client-determines-which-proxy-server-to-use-to

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143b3381-4f04-ca4f-0b97-fa5e9b2db255
* Version Independent ID: 09a088d4-b421-f597-26ee-1ab3aaa489f3
* Content: [WinRM client cannot process the request when connect to Exchange Online - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/connecting-to-the-service/winrm-cannot-process-request#feedback)
* Content Source: [Exchange/ExchangeOnline/connecting-to-the-service/winrm-cannot-process-request.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/connecting-to-the-service/winrm-cannot-process-request.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by joinimran** [comment]
I am looking into this.

**Comment by nam31** [comment]
@kdreally we are going to close this issue as the article has been updated accordingly. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
