### ISSUE TITLE
Status of Check Out / Check In 

### ISSUE THREAD

**Issue by pbadams** [MicrosoftDocs/OfficeDocs-Support#278]
Is there an estimate of when Check In / Check Out will work with OneDrive for Business? Specifically the macOS version. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: L2VuLXVzL3NoYXJlcG9pbnQvc3VwcG9ydC9saXN0cy1hbmQtbGlicmFyaWVzL2ZpbGVzLW9wZW4tYXMtcmVhZC1vbmx5LWFuZC1jYW5ub3QtY2hlY2staW4tb3Itb3V0
* Version Independent ID: L2VuLXVzL3NoYXJlcG9pbnQvc3VwcG9ydC9saXN0cy1hbmQtbGlicmFyaWVzL2ZpbGVzLW9wZW4tYXMtcmVhZC1vbmx5LWFuZC1jYW5ub3QtY2hlY2staW4tb3Itb3V0
* Content: [SharePoint files open as read-only and can't check in or out - SharePoint | Microsoft Docs](https://docs.microsoft.com/en-us/sharepoint/support/lists-and-libraries/files-open-as-read-only-and-cannot-check-in-or-out#feedback)
* Content Source: [SharePoint/SharePointExperts/lists-and-libraries/files-open-as-read-only-and-cannot-check-in-or-out.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointExperts/lists-and-libraries/files-open-as-read-only-and-cannot-check-in-or-out.md)

**Comment by joinimran** [comment]
Hello @pbadams - Thank you for posting your query, but I am sorry to say that there is no ETA for this feature release. But there is a request for a feature open in the UserVoice channel. I would suggest you vote that request. Here is the link for your reference. https://onedrive.uservoice.com/forums/262982-onedrive-archive/suggestions/7094810-check-in-check-out-by-onedrive-for-business-clie

Thanks
Imran.

**Comment by joinimran** [comment]
@pbadams - Can you please elaborate in more detail what exactly the issue you are facing? Any screenshot will be helpful.

**Comment by nam31** [comment]
@pbadams We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
