### ISSUE TITLE
not seeing in list of apps

### ISSUE THREAD

**Issue by ganlbarone** [MicrosoftDocs/OfficeDocs-Support#279]
Ran the new- cmdlet to add the app principal which completed successfully. If I do a get command with the appid listed in this article I can see the app via PS. However the application never shows in the app list on the azure portal. I also get an error when trying to test fluid out that it isnt enabled for my tenant. Please advise. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aba8a7c4-dfd6-f2fc-5b2b-0ea5e9516bc5
* Version Independent ID: c7abd315-d5d5-48cc-d50d-b7986d0a3576
* Content: [How to manage access to Microsoft Fluid Framework preview - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/manage-fluid-framework-preview-access)
* Content Source: [Microsoft365/admin/access-management/manage-fluid-framework-preview-access.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/access-management/manage-fluid-framework-preview-access.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by nam31** [comment]
@ganlbarone We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you
