### ISSUE TITLE
Formatting problem

### ISSUE THREAD

**Issue by smittypro** [MicrosoftDocs/OfficeDocs-Support#280]
Under the Precision section, this text with pipes (|) and hyphens (-) seems like it's not properly formatted: 

A floating-point number is stored in binary in three parts within a 65-bit range: the sign, the exponent, and the mantissa. ||||| |---|---|---|---| |1 Sign Bit|11 Bit Exponent|1 Implied Bit|52 Bit Mantissa|

This was reported by an Excel MVP: 

"I think the dashes and pipes are supposed to produce a tabular layout in pages written using a markup language."

Thanks,

Smitty

**Comment by nam31** [comment]
@smittypro The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@smittypro We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
