### ISSUE TITLE
Incorrect usage of ADAL term.

### ISSUE THREAD

**Issue by alextok** [MicrosoftDocs/OfficeDocs-Support#281]
ADAL is using WAM, but not always, and Office not always uses ADAL, when it uses WAM.

>to reinstall the packages for ADAL
 - it should be "to reinstall WAM packages"

>you have to fix the ADAL package
- you have to fix the AAD package

Thank you,
Sasha Tokarev
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 231e7041-4e8f-aa66-ec94-d6d6937ee80e
* Version Independent ID: f565fa3e-a0b9-4069-b296-c2cacd2f1af9
* Content: [Authentication automatically fails in Office 365 services - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/authentication/automatic-authentication-fails)
* Content Source: [Microsoft365/admin/authentication/automatic-authentication-fails.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/authentication/automatic-authentication-fails.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by nam31** [comment]
Closing via #1510 
Thank you
