### ISSUE TITLE
32-bit vs 64-bit

### ISSUE THREAD

**Issue by JakeFemm** [MicrosoftDocs/OfficeDocs-Support#282]
When I select the "Edit" menu, I have the option to add a DWORD (32-bit) Value, or a QWORD (64-bit) Value. If I am running 64-bit Office, do I still add the DWORD key, or do I use the 64-bit QWORD key?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a702ef95-1c85-b6a8-98d2-fad219a723f7
* Version Independent ID: e4fdc47e-19ac-f442-38c6-ab705856d55c
* Content: [This feature has been disabled by your Administrator - Office](https://docs.microsoft.com/en-us/office/troubleshoot/error-messages/office-365-activates-skype#feedback)
* Content Source: [Office/Client/error-messages/office-365-activates-skype.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/error-messages/office-365-activates-skype.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. DWORD (32-bit) Value is enough for this case.
