### ISSUE TITLE
Method 1 is not valid to retrieve the logs anymore

### ISSUE THREAD

**Issue by a-anchud** [MicrosoftDocs/OfficeDocs-Support#284]
It's not possible to retrieve ActiveSync device logs through OWA anymore, instead ECP could be used: https://outlook.office365.com/ecp/ &gt; options &gt; phone &gt; mobile devices &gt; highlight necessary device &gt; retrieve log on top.​

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6130d9d5-72f1-f6bc-c331-dd3efde61d6f
* Version Independent ID: 55d1fe0c-5327-415c-bf58-3e2cd34a5cb2
* Content: [Collect ActiveSync device logs to troubleshoot sync issues for mobile devices - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/active-sync/issues-for-mobile-devices#feedback)
* Content Source: [Exchange/ExchangeOnline/active-sync/issues-for-mobile-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/active-sync/issues-for-mobile-devices.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by joinimran** [comment]
I am looking into this issue.

**Comment by joinimran** [comment]
Hello, @a-anchud there is only one procedure mentioned in the document, are you sure that you are referring to the correct document?
Thanks.

**Comment by joinimran** [comment]
Hello @a-anchud - Can you please confirm if you are asking for the correct document. I have checked the whole document and it looks good.

@nam31 FYI&A please.

**Comment by a-anchud** [comment]
Hi,

It looks good to me now.
No need to change anything, seems like it was done already by someone else.

Thanks!

**Comment by nam31** [comment]
@a-anchud Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
