### ISSUE TITLE
Error: Length of Year

### ISSUE THREAD

**Issue by KingHorton** [MicrosoftDocs/OfficeDocs-Support#285]
The established length of a Gregorian calendar year is 365.2425 days. Otherwise, there would be a need for more leap years.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6f92333-a9f0-7616-64e8-5aaceb1e3f40
* Version Independent ID: c8136395-44ec-6eb6-3153-53527baf19b3
* Content: [Method to determine whether a year is a leap year - Office](https://docs.microsoft.com/en-in/office/troubleshoot/excel/determine-a-leap-year#feedback)
* Content Source: [Office/Client/excel/determine-a-leap-year.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/determine-a-leap-year.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by madhavsankar** [comment]
Yes your statement makes total sense. The slight lesser than 0.25 is the reason why we don't have leap years when the year is a multiple of 100 but not 400.

**Comment by simonxjx** [comment]
The article is updated.
