### ISSUE TITLE
Version compatibility info should be lower priority

### ISSUE THREAD

**Issue by rexwave** [MicrosoftDocs/OfficeDocs-Support#286]
Wading through language about older versions is confusing. I suggest putting the current version info at the top with a note "For older versions (list), see below", maybe with links in the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa01da04-38bb-0536-bb87-ae209b21bdb1
* Version Independent ID: 6ded95ed-ccaa-9d1c-3ac3-95d4705546e5
* Content: [Use the INDIRECT function to create reference in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/indirect-function-to-create-reference#feedback)
* Content Source: [Office/Client/excel/indirect-function-to-create-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/indirect-function-to-create-reference.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@rexwave we are going to close this issue as the article has been updated accordingly. 
The updated article is available at [INDIRECT function - Office Support (microsoft.com)](https://support.microsoft.com/en-us/office/indirect-function-474b3a3a-8a26-4f44-b491-92b6306fa261?ui=en-US&rs=en-US&ad=US#feedback).
