### ISSUE TITLE
14 or 15 digits of precision?

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/OfficeDocs-Support#287]
You show 15 digits of precision for the positive number, but only 14 for the negative:
2.2250738585072E-308. 
Could you explain why in the document?
.
Could you make it even more explicitly clear how many digits of precision are used in calculations vs display.  The example 15 digit vs 19 digit precision is good, but I think it needs additional re-enforcement.

I am in the middle of a "heated" discussion on the level of precision used in Excel calculations. I say 15 (decimal) while the "opposition says 58 digits decimal and gives the following examples:
&lt;snip https://answers.microsoft.com/en-us/msoffice/forum/msoffice_excel-mso_win10-mso_o365b/addition-error-in-excel/fdd8b24d-9300-4cc9-ac2e-20940b75e890?messageId=8064a168-d13a-4729-8d15-3528f3cee125&gt;
The following shows the exact decimal representation on the right for the internal binary values.

10.01      10.0099999999999,997868371792719699442386627197265625

10.01-10    0.00999999999999978,68371792719699442386627197265625

0.01        0.0100000000000000,0020816681711721685132943093776702880859375
&lt;/snip &gt;
If you could jump in on that question it would be great. 

Thanks.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164a5098-e3e4-7666-b6bc-53072113ded3
* Version Independent ID: 85d54834-d3b8-7428-dc92-92db3973577a
* Content: [Floating-point arithmetic may give inaccurate result in Excel - Office](https://docs.microsoft.com/en-gb/office/troubleshoot/excel/floating-point-arithmetic-inaccurate-result#feedback)
* Content Source: [Office/Client/excel/floating-point-arithmetic-inaccurate-result.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/floating-point-arithmetic-inaccurate-result.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by joinimran** [comment]
Hi @Ronsss, thank you for your feedback.
I am working on this issue and will provide you with an update soon.
