### ISSUE TITLE
Wrong regional setting in example

### ISSUE THREAD

**Issue by simone-gasparini** [MicrosoftDocs/OfficeDocs-Support#289]
The example below have incorrect time format

```
Get-Mailbox user1@contoso.com | Get-MailboxRegionalConfiguration | Set-MailboxRegionalConfiguration -Language it-it -DateFormat "dd/MM/yyyy" -TimeFormat "HH.mm" -TimeZone "W. Europe Standard Time"
```

"HH.mm" must be changed to "HH:mm"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c5d2597-6e11-7c74-1af1-50dd21364593
* Version Independent ID: 4bdf974e-3408-1408-6272-96323b0ad7b6
* Content: [Set language and region settings for Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/set-language-and-region)
* Content Source: [Microsoft365/admin/access-management/set-language-and-region.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/access-management/set-language-and-region.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The article is updated. Thanks.
