### ISSUE TITLE
SpacesGotRemoved

### ISSUE THREAD

**Issue by bwilsonms** [MicrosoftDocs/OfficeDocs-Support#29]
becausethe and Todetermine  under the Cause section looks like the space got removed. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb2abd8e-a09d-1c56-d513-2afae80c9698
* Version Independent ID: 0a2aeabc-3c52-aef7-44f6-69522c313389
* Content: [Windows Fabric, Front-end services won't start on system with 4K native disk - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/server-configuration/windows-fabric-front-end-services-not-start#feedback)
* Content Source: [SkypeforBusiness/SkypeServer/server-configuration/windows-fabric-front-end-services-not-start.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeServer/server-configuration/windows-fabric-front-end-services-not-start.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Cloud-Writer** [comment]
Fixed
