### ISSUE TITLE
Mail drop:-Reason: [{LED=250 2.1.5 RESOLVER.GRP.Expanded; distribution list expanded};{MSG=};{FQDN=}

### ISSUE THREAD

**Issue by prontohostau** [MicrosoftDocs/OfficeDocs-Support#291]
Got the error code from Message trace when sending to 3 different distribution group. Did saw that Email Sender receives NDR from some of the deleted/non-existent user who are listed as group member. Can you investigate on this and add the reason on article? Thanks for reading the feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8ea6148-7a9e-fc28-b6aa-1c4792d9f0cf
* Version Independent ID: c57934fc-54ed-49a1-9ff3-393f22243145
* Content: [Distribution group issues - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/groups/distribution-list-issues?source=docs)
* Content Source: [Microsoft365/admin/groups/distribution-list-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/groups/distribution-list-issues.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by prontohostau** [comment]
@scanum Please help in this matter. thanks

**Comment by msbemba** [comment]
@prontohostau Thank you for your feedback. I have verified in the lab and this does not happen anymore. There have been a few changes with m365 from the time you had created this issue and most importantly the users who are deleted or non Existent are automatically removed from the group as well. Let us know if this issue still persists.

Thanks
Sri

**Comment by msbemba** [comment]
@prontohostau Just circling back to check if the issue persists.

Thanks
Sri

**Comment by nam31** [comment]
@prontohostau Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
