### ISSUE TITLE
What feature are these limits specific for?

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/OfficeDocs-Support#292]
&lt;snip&gt;
Maximum number of moves 	
(Range Permission) maximum number allowed
&lt;snip&gt; 
What features are affected by these 2 limits. I don't recall seeing the terms used in context of MS Word.
Can you add a brief description or links to relevant descriptions.
Can you add RAM limits specific to 32 and 64bit Word?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d78d3ef8-de77-365b-2f50-1777a119a301
* Version Independent ID: 60ee27a7-a6a8-2452-fa37-5c531fac4b95
* Content: [Operating parameter limitations and specifications in Word - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/operating-parameter-limitation#feedback)
* Content Source: [Office/Client/word/operating-parameter-limitation.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/operating-parameter-limitation.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Reeced40** [comment]
@Ronsss thank you for reaching out. The article was updated since the issue was raised. I see the table has the compatibility versions above each one. Please let me know if you think there is anything else missing from the article.

**Comment by Reeced40** [comment]
@Ronsss I haven't been able to find a document that defines the list, but all of the paremeters refers to the limits in a Word Document eg. I'm sure these limits will be hard to exceed, but it's always good to know. Here are some links to other articles regarding the limits https://answers.microsoft.com/msoffice/forum/msoffice_word-mso_other-mso_2007/microsoft-word-limit/fbbb1f64-ddcb-46bc-9b35-3361b7018810 and https://answers.microsoft.com/msoffice/forum/msoffice_word-msoffice_custom-mso_2016/what-is-the-maximum-number-of-merge-fields-in-word/254cc398-2934-4745-8a4e-3216efadd67c
Would you suggest adding a note to elaborate on the limit of 512MB for images?

**Comment by Ronsss** [comment]
Yes, adding a note about the 32MB vs 512MB limits would help.

Adding a note based on the link you provided would also help
https://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-msoffice_custom-mso_2016/what-is-the-maximum-number-of-merge-fields-in-word/254cc398-2934-4745-8a4e-3216efadd67c
.
Looking at the point made in the other link, I would suggest a change in
the layout of the page in question.  Since most/all of the rows are the
same, it would make more sense to me to add a column for "compatibility
mode". That makes it easier to compare the values.
.
Thanks.

**Comment by nam31** [comment]
Closing via #1589 
Thank you

**Comment by Ronsss** [comment]
Nice for you to close, but.
You didn't address most of the points I made.
Adding a link to "merge fields" description is "nice". But referring to
some random non-ms source does not give it the credibility of including the
information directly in the article.
.
The 512MB limit is for the whole document, including graphical elements. No
mention of graphics.
.
There still is no mention of the 32MB limit for the body text (including
some formatting HTML) only.  There is a huge difference between 32MB and
512MB. People are disconcerted when they get a message that the file is
"too big" when file size is below the documented 512MB size limit. They
look at this article and and don't see an explanation.

**Comment by Reeced40** [comment]
@Ronsss thank you for clearing that up, but I see in the document there is a note stipulating the 32MB is for text only and does not include graphics. Please have a look under Note 1, under Word Limits at the top. Please let me know if you think anything else is missing.

**Comment by Ronsss** [comment]
Yes, Note 1 is exactly what I was suggesting.
.
You can close the request on that basis.

However, I still wish you would consider making the limits table a 3 column
table like this:
[image: zzz.jpg]
I bolded the numbers that are different in Compatibility mode
Minor additional issue, the order of items is not the same in the 2 lists.
Master documents is in different positions in the 2 tables.

Minor additional issue 2: numbers are traditionally right aligned to make
them easier to understand

Thanks.

**Comment by Reeced40** [comment]
@Ronsss thank you for clearing that up. I'm glad it is reflecting as you suggested. We will keep the issue closed for now. The table limit setup will remain as is for now but will definitely be considered for future updates to the documents. PS. We are not able to see your jpg's you have inserted here. Maybe try adding a screenshot and we can forward it to the team for future updates. Thanks again for your valuable input.

**Comment by Ronsss** [comment]
Thanks.
Getting images through various "email" systems can be an adventure. Here is
a share link to a doc with and alternate version of the table in it
OfficeDocs-Support What feature are these limits specific for ^N292.docx
<https://1drv.ms/w/s!Am8lVyUzjKfppmK7ie4rv7DWruT8?e=BUXilA>
Let me know when you have it so I can delete it to free up space.

**Comment by Reeced40** [comment]
@Ronsss thanks again for your valuable input! You can delete it now, I've got it thank you.
