### ISSUE TITLE
This page is wrong. Its complex. And what it suggests doesn't work.  MS Help however had the answer.

### ISSUE THREAD

**Issue by pythologist** [MicrosoftDocs/OfficeDocs-Support#293]
1. It claims that on the "View" menu for MS Word there are entries there are these two entries: "Click to select the Horizontal scroll bar and the Vertical scroll bar check boxes in the Window section, and then click OK." But those two entries simply do not exist.  My MS Word Preferences/View menu has "Show in document" ]/"Show Non-Printing Characters/Show Windows Elements/Ribbon and on none of those is "Horizontal scroll bar and Vertical scroll bar. They just do not exist. However the Mac has these.  Original problem: For reasons that can not be explained the "Vertical scroll bar" which is what I want, so I can navigate fast up and down simply disappeared and does not come back and these instructions do not show what I see on the screen.  Solution: For Mac Go to Apple/Preferences/General and turn scroll bars to always on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04a174f0-107a-caf2-09b0-003c90fa1d2f
* Version Independent ID: 91df925f-965a-b706-384e-11e1b66c0e65
* Content: [Scroll bars are missing in Word for Mac - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/word-scroll-bars-missing#feedback)
* Content Source: [Office/Client/word/word-scroll-bars-missing.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/word-scroll-bars-missing.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Close this one as the article is already redirected.
