### ISSUE TITLE
url error

### ISSUE THREAD

**Issue by jeasonzhou** [MicrosoftDocs/OfficeDocs-Support#294]
The url ‘/FederationMetadat/2007-06/FederationMetadata.xml’  is short of ‘a’

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 91594f16-0dfd-7f42-29c6-3211805aef61
* Version Independent ID: 8cbdbc8b-4497-59ad-36dd-d8b1358ec8c0
* Content: [更改联合身份验证服务终结点后，登录到 Office 365、Azure 或 Intune 失败](https://docs.microsoft.com/zh-cn/office365/troubleshoot/active-directory/sign-in-fails-if-federation-endpoint-changes#feedback)
* Content Source: [Microsoft365/admin/active-directory/sign-in-fails-if-federation-endpoint-changes.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/active-directory/sign-in-fails-if-federation-endpoint-changes.md)
* Product: **office 365**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by Lucciz** [comment]
Updated.
