### ISSUE TITLE
D'oh!

### ISSUE THREAD

**Issue by webmaestro** [MicrosoftDocs/OfficeDocs-Support#295]
Excel used to quote strings, but they don't know. Thanks for providing instructions on how to fix Excel so it has an option to quote strings. Excel should support this without any shenanigans.

IIRC, when Microsoft upgraded Mac Office, it broke Visual Basic Macros throughout (later coming back). LibreOffice, NeoOffice & OpenOffice.org continued to support Visual Basic during this time. I downloaded one of those, and it happily quoted all my strings.

Problem solved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92765388-a22b-7311-8764-e8b065a0569e
* Version Independent ID: d02626a0-1eb2-1e62-efa5-519676f527a7
* Content: [Export a text file with both comma and quote delimiters in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/export-text-file-with-comma-quote#feedback)
* Content Source: [Office/Client/excel/export-text-file-with-comma-quote.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/export-text-file-with-comma-quote.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment and feedback.
