### ISSUE TITLE
stopped at step 1

### ISSUE THREAD

**Issue by Trish15** [MicrosoftDocs/OfficeDocs-Support#296]
"On the View menu, point to Toolbars, and then click Customize."

I see no 'Toolbars' on the View menu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c394586c-ceee-d004-ef45-a6bff9c12aaf
* Version Independent ID: 8383bd6d-1054-c0a8-a469-114ad0a14e88
* Content: [How to work with toolbars and toolbar buttons in Word - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/toolbars-and-toolbar-buttons-in-word#feedback)
* Content Source: [Office/Client/word/toolbars-and-toolbar-buttons-in-word.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/toolbars-and-toolbar-buttons-in-word.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@Trish15 
we are going to close this issue as the article has been updated accordingly. 
The updated article is available at [Customize the ribbon in Office (microsoft.com)](https://support.microsoft.com/en-us/topic/customize-the-ribbon-in-office-00f24ca7-6021-48d3-9514-a31a460ecb31?ui=en-us&rs=en-us&ad=us#feedback).
