### ISSUE TITLE
Typo in Method 1

### ISSUE THREAD

**Issue by jaapwess** [MicrosoftDocs/OfficeDocs-Support#297]
Method 1, for the Send on behalf of option, it should read Set-Mailbox &lt;mailbox name&gt; -MessageCopyForSendOnBehalfEnabled $TRUE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63db99b0-97d7-f1a4-b3b2-ec80a6a6b43c
* Version Independent ID: d74dbce7-c3d4-353e-a990-ad6447597b66
* Content: [Messages sent from a shared mailbox aren't saved to the Sent Items folder - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/shared-mailboxes/sent-mail-is-not-saved#feedback)
* Content Source: [Exchange/ExchangeOnline/shared-mailboxes/sent-mail-is-not-saved.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/shared-mailboxes/sent-mail-is-not-saved.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
It is updated. Thanks for the comments.
