### ISSUE TITLE
How to identify old TLS in office 365

### ISSUE THREAD

**Issue by deanmresource** [MicrosoftDocs/OfficeDocs-Support#298]
The one piece of information i need is how to identify Office 365 users of TLS1.0 and 1.1 however this link 

https://blogs.technet.microsoft.com/exchange/2018/04/02/exchange-server-tls-guidance-part-2-enabling-tls-1-2-and-identifying-clients-not-using-it/

Tells you everything BUT office 365 :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 753400c8-a0d3-4fdb-e819-e1eb8d2c9e58
* Version Independent ID: d13e562e-7cb8-8ee2-ba1e-66072e70f687
* Content: [Preparing for TLS 1.2 in Office 365 and Office 365 GCC - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/security/prepare-tls-1.2-in-office-365)
* Content Source: [Microsoft365/admin/security/prepare-tls-1.2-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/security/prepare-tls-1.2-in-office-365.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by c016smith** [comment]
Plus 1 for this, would be great to identify a workbook or other methods of tracking/reporting on the transport layer security (versions etc.) used by different clients and sessions, so we can see that getting removed over time. Thanks!

**Comment by deanmresource** [comment]
I have found out how to do this, the page itself doesn't tell you.
Log into the Office 365 Admin portal.

Go into SECURITY & COMPLIANCE

Then go to MAIL FLOW

Then go to DASHBOARD

Then go to SMTP CLIENTS

then in the middle of the page you can click SMTP AUTH CLIENTS REPORT 

Quick link: https://protection.office.com/reportv2?id=SmtpClientSubmissionReport&pivot=SenderDomain

This gives you the number of SMTP AUTH requests. Change the VIEW DATA BY drop down from Sending Volume to TLS Usage, then once that has loaded click on VIEW DETAILS TABLE 

You will now be able to see the email address that uses TLS and what tls version they are using to authenticate. Took me quite some time to find this but i got there in the end.

Would be nice if the "help page" actually told us this important information.

**Comment by MaratMussabekov** [comment]
Hello @deanmresource , @c016smith ,
I created a PR to add link to this information.
Thank you

**Comment by nam31** [comment]
Closing via https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5216
Thank you
