### ISSUE TITLE
Correct the SendOnBehalf section

### ISSUE THREAD

**Issue by victorlamb** [MicrosoftDocs/OfficeDocs-Support#299]
Using Exchange PowerShell, for emails Sent On Behalf of the shared mailbox, run the following cmdlet:
PowerShell
set-mailbox &lt;mailbox name&gt; -MessageCopyForSentAsEnabled $True

Should be
set-mailbox &lt;mailbox name&gt; -MessageCopyForSendOnBehalfEnabled $True

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63db99b0-97d7-f1a4-b3b2-ec80a6a6b43c
* Version Independent ID: d74dbce7-c3d4-353e-a990-ad6447597b66
* Content: [Messages sent from a shared mailbox aren't saved to the Sent Items folder - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/shared-mailboxes/sent-mail-is-not-saved#feedback)
* Content Source: [Exchange/ExchangeOnline/shared-mailboxes/sent-mail-is-not-saved.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/shared-mailboxes/sent-mail-is-not-saved.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
It is updated. Thanks for the comments.
