### ISSUE TITLE
Office 365 Pro Plus with Device Based Activation - Predecessor to Device Based Subscription

### ISSUE THREAD

**Issue by rtate78** [MicrosoftDocs/OfficeDocs-Support#300]
My Office install is activated using the device in the form of an Azure Active Directory device object.  When making the proposed changes to the registry, my licensing is broken.  I am being asked to license my software in order to create new documents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb87ad1f-6d70-d314-1e86-390d21c6f29c
* Version Independent ID: e89f736a-4bf3-407c-cd77-723c998c72e8
* Content: [How to switch from Semi-Annual Channel to Monthly Channel for the Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/updates/switch-channel-for-office-365#feedback)
* Content Source: [Microsoft365/admin/updates/switch-channel-for-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/updates/switch-channel-for-office-365.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@rtate78 Thank you for your feedback. I was able to test it by changing the channel using ODT and it did not prompt for credentials (Device-based licensing). This might have been a bug at the time the issue was created. Could you confirm if the issue persists?

Thanks
Sri

**Comment by msbemba** [comment]
@rtate78 Just circling back to check if the issue persists.

Thanks
Sri

**Comment by nam31** [comment]
@rtate78 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
