### ISSUE TITLE
Hard Matching using Immutable ID Technet gone

### ISSUE THREAD

**Issue by pstasik** [MicrosoftDocs/OfficeDocs-Support#302]
Where did the article go for hard matching account when Cloud Anchor is missing?  It used to reside at the link below but is no longer there.  Where did it go?
http://blogs.technet.com/b/praveenkumar/archive/2014/08/10/how-to-do-hard-match-part-2.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10fe7667-5c74-325b-7f55-123bde0add23
* Version Independent ID: 353543ec-d9e0-5166-1ec4-1b68c388f431
* Content: [Troubleshoot directory synchronization errors with event 6941 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/active-directory/duplicate-attributes-prevent-dirsync#feedback)
* Content Source: [Microsoft365/admin/active-directory/duplicate-attributes-prevent-dirsync.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/active-directory/duplicate-attributes-prevent-dirsync.md)
* Service: **o365-administration**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. The blog is moved to https://docs.microsoft.com/en-nz/archive/blogs/praveenkumar/how-to-do-hard-match-part-2. You can get the article by searching **how-to-do-hard-match-part-2** on Bing.
