### ISSUE TITLE
D Wall

### ISSUE THREAD

**Issue by Nad42** [MicrosoftDocs/OfficeDocs-Support#303]
Hi, 

This is all well and good but all my users connected just show as 'Admin'; is there anyway to find  their windows user account name?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb5e490e-e0a5-3470-cb10-9a3e75f4a6ae
* Version Independent ID: 77e4f016-946b-82cf-d4ff-def1d6fcc6ac
* Content: [Determine who is logged on to a database - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/determine-who-is-logged-on-to-database)
* Content Source: [Office/Client/access/determine-who-is-logged-on-to-database.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/determine-who-is-logged-on-to-database.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by Rogoflap** [comment]
When I try this same code, I am getting an error:
on this line: 

Set rs = cn.OpenSchema(adSchemaProviderSpecific, _
    , "{947bb102-5d43-11d1-bdbf-00c04fb92675}")

Object or Provider is not capable of performing requested operation.

MS Access 2016 32 bit

**Comment by VLG17** [comment]
@Nad42 You won't be able to find their windows user account name by using the Microsoft Jet UserRoster, although you can see the computer name.

Although not a Microsoft article, you could use the steps [in this article](https://www.devhut.net/2013/03/19/ms-access-who-is-logged-in/) to create a LoggedIn table and get/store that info.

**Comment by VLG17** [comment]
@Nad42 any updates?

**Comment by nam31** [comment]
@Nad42 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
