### ISSUE TITLE
VBA code writes to cells slowly when many Shape Objects are in Excel 2016 workbook

### ISSUE THREAD

**Issue by Grosner300** [MicrosoftDocs/OfficeDocs-Support#304]
The VBA code in this article is also slow to write to worksheet when many Shape Objects exist. After removing the shape objects (i.e. Textboxs, Charts, etc.) or deleting the worksheet containing several hundred shapes, the write speed is significantly faster.  There was no apparent difference in write speed even after all ActiveX objects were made visible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c452ff16-544a-dbdf-b35b-b446c7094511
* Version Independent ID: 28df3285-d7bc-c71e-0807-26562b77873b
* Content: [VBA writes to cells slowly when ActiveX controls are invisible - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/vba-writes-to-cells-slowly#feedback)
* Content Source: [Office/Client/excel/vba-writes-to-cells-slowly.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/vba-writes-to-cells-slowly.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
Closing via #1547 
Thank you
