### ISSUE TITLE
Update "Applies to"

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/OfficeDocs-Support#305]
The Applies to list ends at Office 2013 and Windows 8.1, yet the article was recently updated. Add 2016, 2019, 365 and Windoze 10.
.
The steps include Office 2016, but not 365 or 2019.  Personally, I know that MS got lazy when they created 365 and lumped it in with 2016, same with 2019. But the "average" user would not.  Please make that clear in the article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be46645d-dbd2-f1f8-089d-de61c678807f
* Version Independent ID: 5945f781-2560-84f0-494e-2473b9537939
* Content: [How to troubleshoot problems that occur when you start or use Word - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/issues-when-start-or-use-word#feedback)
* Content Source: [Office/Client/word/issues-when-start-or-use-word.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/issues-when-start-or-use-word.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
Closing via #1501 
Thank you
