### ISSUE TITLE
Paper Size

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/OfficeDocs-Support#306]
I thought Word had a max paper size of 22 inches
PRINTING VERY LARGE PAPER SIZES
http://wordribbon.tips.net/T009992_Printing_Very_Large_Paper_Sizes.html 
Summary: Need to print on large pieces of paper? Word has a limit on the size of the paper it can use, but that might not be the only limiting factor. You also need to worry about your printer and printer driver. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d78d3ef8-de77-365b-2f50-1777a119a301
* Version Independent ID: 60ee27a7-a6a8-2452-fa37-5c531fac4b95
* Content: [Operating parameter limitations and specifications in Word - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/operating-parameter-limitation#feedback)
* Content Source: [Office/Client/word/operating-parameter-limitation.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/operating-parameter-limitation.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@Ronsss You are right:

![image](https://user-images.githubusercontent.com/41186174/121010810-88dee000-c79e-11eb-890b-246197232948.png)

**Comment by nam31** [comment]
Closing via #1546 
Thank you
