### ISSUE TITLE
Maximum rows referenced by a literal count (64k, no less). Best would be "rows.count" or "columns.count".

### ISSUE THREAD

**Issue by wornhall** [MicrosoftDocs/OfficeDocs-Support#308]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74bbe6e6-cb2a-50ae-7c2c-cef5c64e6559
* Version Independent ID: 9a187fc7-3fc1-effa-a440-46dc2c8838b6
* Content: [How to select cells or ranges by using Visual Basic procedures in Excel. - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-developer/select-cells-rangs-with-visual-basic#feedback)
* Content Source: [Office/Client/office-developer/select-cells-rangs-with-visual-basic.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-developer/select-cells-rangs-with-visual-basic.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@wornhall I see the article now contains both rows.count and columns.count.

Also, I don't see anything related to the 64k limit.

**Comment by VLG17** [comment]
@wornhall Any updates?

**Comment by nam31** [comment]
@wornhall We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
