### ISSUE TITLE
Cannot find "Office 2011 AutoRecovery" folder 

### ISSUE THREAD

**Issue by yvonneqiao** [MicrosoftDocs/OfficeDocs-Support#31]
No such folder under Library&gt;Application Support&gt;Microsoft&gt;Office

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 381e2038-d0be-539f-a6fa-69f103827909
* Version Independent ID: 78b0f11d-6504-1e6e-8111-dbd5a2d718a5
* Content: [Opening Excel for Mac stops responding with spinning wheel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/open-excel-for-mac-stop-responding#feedback)
* Content Source: [Office/Client/excel/open-excel-for-mac-stop-responding.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/open-excel-for-mac-stop-responding.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Following up on the feedback.

**Comment by jlriesco** [comment]
The comment is correct. This article has info on locating the recovery files for 2011 and newer versions. I’m not sure we even need the DOCs article. Here is the SOC content: https://support.office.com/en-us/article/recover-files-in-office-for-mac-6c6425b1-6559-4bbf-8f80-4f038402ff02#ID0EAACAAA=Newer_versions 

I will redirect this DOCs article to the SOC article.
