### ISSUE TITLE
Error is also caused when 2FA is enabled on user's account

### ISSUE THREAD

**Issue by apawsey** [MicrosoftDocs/OfficeDocs-Support#310]
If 2FA (MFA?) is enabled on the account trying to do this, you also get access denied.  For that scenario, I believe you need to generate an app password, or use an existing one - at least that worked for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a7466a6-9557-8c01-02c2-516732c3c17f
* Version Independent ID: 7d82a28b-6229-7d2b-dc4e-b7a793f4c649
* Content: [Access is denied when you connect to Exchange Online with Windows PowerShell - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/connecting-to-the-service/access-denied-connect-powershell#feedback)
* Content Source: [Exchange/ExchangeOnline/connecting-to-the-service/access-denied-connect-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/connecting-to-the-service/access-denied-connect-powershell.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Pyrobolser** [comment]
Thanks a lot for your comment, it saved me some time!

**Comment by ArrowRaider** [comment]
I have 2FA enabled and generated an app password.  It did not help here.

**Comment by DanTheRed** [comment]
Thanks Pyrobolser, set me on the right path. 
App Password didn't work for me either. 
Found out you need to install a Power Shell module that works with 2FA. 
Instructions below on link from MS. 
https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps

**Comment by HandyAndyOnGitHub** [comment]
Yup many thanks - excellent comment.  Documentation needs updating for MFA users please :)

**Comment by VLG17** [comment]
@apawsey The article has been update to reflect this - security defaults and what needs to be done (for both MFA and non-MFA).

**Comment by VLG17** [comment]
@apawsey Can you check the article and let us know if you feel we need to add anything else?

**Comment by nam31** [comment]
@apawsey We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
