### ISSUE TITLE
Skype for Business 2019 Basic

### ISSUE THREAD

**Issue by brianshiers** [MicrosoftDocs/OfficeDocs-Support#312]
The documented product id for Skype for Business 2019 Basic seems to be incorrect as the current documented value of Skypeforbusiness2019retail doesn't result in the product installation. Should the value be SkypeforbusinessEntry2019retail

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 358c3fd4-27aa-fc10-e23e-43b3f801b739
* Version Independent ID: 3d322857-f041-5b22-d91b-458427e45fb1
* Content: [Product IDs that are supported by the Office Deployment Tool for Click-to-Run - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/installation/product-ids-supported-office-deployment-click-to-run)
* Content Source: [Microsoft365/admin/installation/product-ids-supported-office-deployment-click-to-run.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/installation/product-ids-supported-office-deployment-click-to-run.md)
* Service: **o365-solutions**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **stevhord**

**Comment by VLG17** [comment]
@brianshiers The article has been updated to reflect this change. SkypeforBusinessEntry2019Retail corresponds to Skype for Business Basic 2019

**Comment by VLG17** [comment]
@brianshiers Could you check and see if you are ok with the update or need something else added?

**Comment by nam31** [comment]
@brianshiers We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
