### ISSUE TITLE
The commands should be performed in Terminal

### ISSUE THREAD

**Issue by ShawnTeng** [MicrosoftDocs/OfficeDocs-Support#313]
"In the Finder menu, click Go, and click Go to Folder. Run the following commands: "

Shouldn't these command be run in Terminal? How to run them in Folder path?

**Comment by nam31** [comment]
@ShawnTeng The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@ShawnTeng We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
