### ISSUE TITLE
Voice message notifications not appearing in Teams

### ISSUE THREAD

**Issue by AlexanderSaad** [MicrosoftDocs/OfficeDocs-Support#314]
Could you please provide more details about the message headers that do not have to be modified in order for messages to appear in Teams and Skype for Business, and also an example of identifying a similar issue. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef6fd529-a369-9afd-ce21-4cb8b415f6c4
* Version Independent ID: 9e7c3225-ddba-1af5-c2f0-ab3da394f02f
* Content: [Voicemail messages are not delivered in Teams or Skype for Business client - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/hybrid-phone-system/voicemails-not-delivered#feedback)
* Content Source: [SkypeforBusiness/SkypeHybrid/hybrid-phone-system/voicemails-not-delivered.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeHybrid/hybrid-phone-system/voicemails-not-delivered.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@AlexanderSaad this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@AlexanderSaad We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
