### ISSUE TITLE
The quality of writing

### ISSUE THREAD

**Issue by AlanOlrog** [MicrosoftDocs/OfficeDocs-Support#316]
I arrived at this page after a Google search for a Word topic.
It looks similar to many Microsoft information pages that I've visited, but I was puzzled by the last paragraph: you introduce something called EeeKB without elaboration or explanation. A Google search was unenlightening.

I'm very much in favour of feeding back to Microsoft, but I don't understand what EeeKB is. However, for what seems to be an official Microsoft page, the standard of writing is poor. Generally, I find Microsoft's technical documentation to be well written, if often lacking detail, but this text is stylistically odd. There's nothing wrong with informal English, but the explanation of technical subjects should be clear, above all, and this aim is best served by using Standard English.

There are errors in the grammar, syntax and punctuation. The style is odd in places too, e.g. "info", and the use of the text-speak "pls" for "please".

Three examples:
The title "How to merge multiple Word documents into one?" is not a question but has a question mark.

"By pressing and holding Ctrl to select more than one documents." is not a sentence and is also ungrammatical.

"Formats will not be necessarily remained when you merging the documents." is ungrammatical.

I clicked the feedback button "This product" and was taken to a page called Office 365 UserVoice Forums. The text here appeared to have been typed in haste, as there was missing punctuation and at least six examples of a missing space between word pairs. Is this the work of Microsoft? It's very sloppy.
The "Give feedback" links take me to a page that asks for ideas and suggestions, not feedback. Where should my feedback go, for example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d25557df-12d9-2b76-eba2-a3c8134d294a
* Version Independent ID: c8a4f4fd-dbbe-0c41-5c4a-0dd10f7caa93
* Content: [How to merge multiple Word documents into one? - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/merge-word-documents)
* Content Source: [Office/Client/word/merge-word-documents.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/merge-word-documents.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment to this article. The article is an old article that is moved from an old platform. Currently, the article is updated with your comment. Very appreciate for your comment and feedback to the article. As this is an old article, the feedback link is not working. Thanks again for your comment.

**Comment by rmanjoney** [comment]
I agree with @AlanOlrog, but I am not seeing where his concerns or suggestions have been incorporated into the article, despite the fact that this issue is "Closed".

**Comment by Urbs3w** [comment]
> I agree with @AlanOlrog, but I am not seeing where his concerns or suggestions have been incorporated into the article, despite the fact that this issue is "Closed".

I also agree. I am still seeing the same style, syntax and grammar issues in that article that make it difficult for me to understand the article as an American English user.
