### ISSUE TITLE
Where is the option?

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/OfficeDocs-Support#317]
Where is the fiddler option?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a7194fa-a20c-433c-a928-9035dfa48c84
* Version Independent ID: 54452f7c-d2af-234b-c830-dab49d3a0864
* Content: [How to run the Fiddler Trace after installing SaRA - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/diagnostic-logs/run-fiddler-trace)
* Content Source: [Microsoft365/admin/diagnostic-logs/run-fiddler-trace.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/diagnostic-logs/run-fiddler-trace.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by jlriesco** [comment]
We've updated the article to make it clearer.
