### ISSUE TITLE
Skype for Business comes back

### ISSUE THREAD

**Issue by rsmith013** [MicrosoftDocs/OfficeDocs-Support#318]
I have followed all the steps on this page but Skype for business is back! It seems to "Update" and download itself again. Is there a way to prevent this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5738299a-feb3-740e-aa42-5814f797a607
* Version Independent ID: e5373833-2a2e-0c3b-03fb-933de37c0d42
* Content: [How to do a clean uninstallation of Skype for Business on Mac - Skype for Business](https://docs.microsoft.com/en-us/SkypeForBusiness/troubleshoot/server-install-or-uninstall/clean-uninstallation#feedback)
* Content Source: [SkypeforBusiness/SkypeServer/server-install-or-uninstall/clean-uninstallation.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeServer/server-install-or-uninstall/clean-uninstallation.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. For the issue you experience, You can get the support via https://support.office.com/en-us/skype-for-business.
