### ISSUE TITLE
Server 2012 R2 ADFS Patch?

### ISSUE THREAD

**Issue by cklouda** [MicrosoftDocs/OfficeDocs-Support#319]
The article mentions Server 2019 and Server 2016 ADFS.  What about 2012 R2?  Is this not considered a break/fix that falls under extended support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b6e323a-6fb2-c1a6-3afa-b88ed1ad419c
* Version Independent ID: ca05aa94-6799-3961-d83b-8fab9cf83be1
* Content: [Chrome SameSite cookie behavior effect on customer applications - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/miscellaneous/chrome-behavior-affects-applications#feedback)
* Content Source: [Microsoft365/admin/miscellaneous/chrome-behavior-affects-applications.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/miscellaneous/chrome-behavior-affects-applications.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by lightupdifire** [comment]
Hello,
Agree with @cklouda, but interesting not only for ADFS 2012R2 patch, also need for Web Application Proxy, hope no difference.

**Comment by TobieFysh** [comment]
The 2012r2 patches have the same text ("addresses an issue to support new SameSite cookie policies by default for release 80 of Google Chrome") as the 2016/2019 patches. Would be good to have confirmation from Microsoft that these have the same fixes included.

https://support.microsoft.com/en-us/help/4534309/windows-8-1-kb4534309
https://support.microsoft.com/en-us/help/4534297/windows-8-1-kb4534297

**Comment by jpoindexter9** [comment]
Also what about just plain Windows Server 2012? Which is also under extended support to the same date as 2012 R2?

**Comment by Kofl** [comment]
Yes, they are included in kb4534309, mentioned here:

Addresses a potential AD FS chrome failure due to support of new SameSite cookie policies by default for release 80 of Google Chrome. For more information, please refer here ==> January 2020
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/updates-for-active-directory-federation-services-ad-fs?redirectedfrom=MSDN

The teams dont talk to each other?

**Comment by TobieFysh** [comment]
@jpoindexter9 

Looking at the link that @kofl provided and also at the 2012 update page 

(https://support.microsoft.com/en-gb/help/4534283 - also click through on the left hand bar)

There does not appear to be this update included in 2012 (which is ADFS 2.x) but is included in 2012r2 (ADFS 3.0)

**Comment by jpoindexter9** [comment]
> 
> 
> @jpoindexter9
> 
> Looking at the link that @Kofl provided and also at the 2012 update page
> 
> (https://support.microsoft.com/en-gb/help/4534283 - also click through on the left hand bar)
> 
> There does not appear to be this update included in 2012 (which is ADFS 2.x) but is included in 2012r2 (ADFS 3.0)

@TobieFysh now that you say that you are right... that is for 2012r2 (KB4534309) @Kofl

**Comment by Kofl** [comment]
Yes, its 2012 R2, now also linked in that article. My answer referred to original question about 2012 R2.

**Comment by cklouda** [comment]
Excellent... thanks
