### ISSUE TITLE
Please remove this content. It is inaccurate

### ISSUE THREAD

**Issue by denniwil** [MicrosoftDocs/OfficeDocs-Support#32]
Please pull this content as the Access Database Engine is not supported for connections to ASP pages as the use of unattended/service accounts is not supported as stated on the engine's download page. https://www.microsoft.com/en-us/download/details.aspx?id=54920

The Access Database Engine 2016 Redistributable is not intended: 
4.To be used by a system service or server-side program where the code will run under a system account, or will deal with multiple users identities concurrently, or is highly reentrant and expects stateless behavior. Examples would include a program that is run from task scheduler when no user is logged in, or a program called from server-side web application such as ASP.NET, or a distributed component running under COM+ services.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d17bf6f4-78fe-62a0-eda2-fdbb23e50c7c
* Version Independent ID: cba1f8c3-2df5-caa2-7ad1-a513ad40a630
* Content: [Connect to a remote Access database from Active Server Pages - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/connect-access-from-active-server#feedback)
* Content Source: [Office/Client/access/connect-access-from-active-server.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/connect-access-from-active-server.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Checking this feedback.

**Comment by simonxjx** [comment]
Article is removed.
