### ISSUE TITLE
This solution didn't work for me, but my problem *may* be unrelated.

### ISSUE THREAD

**Issue by sydbarrett74** [MicrosoftDocs/OfficeDocs-Support#320]
I was directed to this page to help resolve a problem I'm having, which I'll detail below.

I have Office 365 16.0.12325.20344 on a Windows 10 Home 1909 machine. I'm using it in conjunction with the Automation Anywhere Enterprise 11.3.3 Client. When I access a specific Excel spreadsheet, I get the following error:

'retrieving the com class factory for component with clsid {00024500-0000-0000-c000-000000000046} failed due to the following error: 80070490 element not found. (exception from hresult: 0x80070490).'

When I did the steps on this page, I found that ShownFirstRunOptin was set to '2'. I changed it to '1' as per the steps. After rebooting the machine and trying my AA bot out, I got the same error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3e1325-8447-d157-729e-f668bef41db0
* Version Independent ID: f411b63a-8be9-9ac4-3f1c-8746216d243d
* Content: [Office Applications crash or cannot start - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/office-crash-or-cannot-start#feedback)
* Content Source: [Microsoft365/enterprise/administration/office-crash-or-cannot-start.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/enterprise/administration/office-crash-or-cannot-start.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by todmccoy** [comment]
Article updated with new information. Thanks for pointing this out.
