### ISSUE TITLE
What Update to install

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-Support#321]
The link above points to a general purpose page about Windows Updates. What is the specific update that needs to be installed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc923ec5-ba8f-ce73-147c-974f704c4d97
* Version Independent ID: 03f97d04-a393-d80d-91f1-fac4a397b75e
* Content: [An update for supporting migration from AD RMS to Azure RMS - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/active-directory/migration-from-ad-rms-to-azure-rms?source=docs#feedback)
* Content Source: [Microsoft365/admin/active-directory/migration-from-ad-rms-to-azure-rms.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/active-directory/migration-from-ad-rms-to-azure-rms.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by DeanGross** [comment]
Follow up, I cannot find any information about Office 2017 16.0.7407.1000, is this a valid edition?

**Comment by simonxjx** [comment]
Thanks for your comment. It is updated.
