### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Lou240** [MicrosoftDocs/OfficeDocs-Support#322]
in your Set-MsolUser commands , you have an extra space.  Should be -UsageLocation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c5d2597-6e11-7c74-1af1-50dd21364593
* Version Independent ID: 4bdf974e-3408-1408-6272-96323b0ad7b6
* Content: [Set language and region settings for Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/set-language-and-region#feedback)
* Content Source: [Microsoft365/admin/access-management/set-language-and-region.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/access-management/set-language-and-region.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. It is updated.
