### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by gaelicWizard** [MicrosoftDocs/OfficeDocs-Support#324]
Does this work on Windows 10? Is the XML file export/import not required to set email client? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce321185-d005-bcfb-74bf-a23bd31850a6
* Version Independent ID: f96194ef-a823-7f29-fda3-4dc6e84f6831
* Content: [How to configure the default e-mail client using Group Policy - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/group-policy/configure-email-client-using-policy#feedback)
* Content Source: [Microsoft365/admin/group-policy/configure-email-client-using-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/group-policy/configure-email-client-using-policy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by brunofelipens** [comment]
Does this work on Windows 10 1909....

**Comment by simonxjx** [comment]
The articles have been updated. Closing this now.
