### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/OfficeDocs-Support#325]
Hello,
FYI. while testing, found that those not work:
https://security.microsoft.com/
https://compliance.microsoft.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b6e323a-6fb2-c1a6-3afa-b88ed1ad419c
* Version Independent ID: ca05aa94-6799-3961-d83b-8fab9cf83be1
* Content: [Chrome SameSite cookie behavior effect on customer applications - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/miscellaneous/chrome-behavior-affects-applications#recommendations)
* Content Source: [Microsoft365/admin/miscellaneous/chrome-behavior-affects-applications.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/miscellaneous/chrome-behavior-affects-applications.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by hpsin** [comment]
Thank you! I've reached out to those teams.

**Comment by hpsin** [comment]
#please-close - we've found the teams in question and they've committed to a fix.
