### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-Support#326]
Do we need to install a separate patch if we already have deployed Office versions that are higher than those listed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc923ec5-ba8f-ce73-147c-974f704c4d97
* Version Independent ID: 03f97d04-a393-d80d-91f1-fac4a397b75e
* Content: [An update for supporting migration from AD RMS to Azure RMS - Office 365](https://docs.microsoft.com/en-in/office365/troubleshoot/active-directory/migration-from-ad-rms-to-azure-rms)
* Content Source: [Microsoft365/admin/active-directory/migration-from-ad-rms-to-azure-rms.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/active-directory/migration-from-ad-rms-to-azure-rms.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
There is no need to install a separate patch as the fix is included in the listed version and later versions.
