### ISSUE TITLE
What about new Edge?

### ISSUE THREAD

**Issue by PiKappZ746** [MicrosoftDocs/OfficeDocs-Support#327]
Is this change in Chromium also going to affect the behavior in the new Edge browser?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b6e323a-6fb2-c1a6-3afa-b88ed1ad419c
* Version Independent ID: ca05aa94-6799-3961-d83b-8fab9cf83be1
* Content: [Chrome SameSite cookie behavior effect on customer applications - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/miscellaneous/chrome-behavior-affects-applications#feedback)
* Content Source: [Microsoft365/admin/miscellaneous/chrome-behavior-affects-applications.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/miscellaneous/chrome-behavior-affects-applications.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by hpsin** [comment]
https://docs.microsoft.com/en-us/microsoft-edge/web-platform/site-impacting-changes

Edge is not picking up this change in this timeframe.

**Comment by hpsin** [comment]
#please-close as this has been added to the article. Thank you PiKappZ746 for pointing it out.

**Comment by ShadowSharmon** [comment]
The linked page now says it WILL be adopting the change at the same time???

**Comment by hpsin** [comment]
To clarify, it says it will adopt around 82, and at the same or later time.
