### ISSUE TITLE
Link to Exchange Blog broken.

### ISSUE THREAD

**Issue by Dottn** [MicrosoftDocs/OfficeDocs-Support#328]
The link to the exchange blog (under method 1) is redirected to the archive of all technet blogs, making it incredibly difficult to find the actual blogpost you are linking to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63db99b0-97d7-f1a4-b3b2-ec80a6a6b43c
* Version Independent ID: d74dbce7-c3d4-353e-a990-ad6447597b66
* Content: [Messages sent from a shared mailbox aren't saved to the Sent Items folder - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/shared-mailboxes/sent-mail-is-not-saved#feedback)
* Content Source: [Exchange/ExchangeOnline/shared-mailboxes/sent-mail-is-not-saved.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/shared-mailboxes/sent-mail-is-not-saved.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The link is updated. Thanks. https://techcommunity.microsoft.com/t5/exchange-team-blog/want-more-control-over-sent-items-when-using-shared-mailboxes/ba-p/611106
