### ISSUE TITLE
How to do Step 2 under Testing Guidelines : Start at the experimental feature flag --enable-features=SameSiteDefaultChecksMethodRigorously

### ISSUE THREAD

**Issue by rohitiscancerian** [MicrosoftDocs/OfficeDocs-Support#329]
How to do Step 2 under Testing Guidelines : Start at the experimental feature flag --enable-features=SameSiteDefaultChecksMethodRigorously

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b6e323a-6fb2-c1a6-3afa-b88ed1ad419c
* Version Independent ID: ca05aa94-6799-3961-d83b-8fab9cf83be1
* Content: [Chrome SameSite cookie behavior effect on customer applications - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/miscellaneous/chrome-behavior-affects-applications)
* Content Source: [Microsoft365/admin/miscellaneous/chrome-behavior-affects-applications.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/miscellaneous/chrome-behavior-affects-applications.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by ianc911** [comment]
Yes, what's the deal on this one? Can't test properly without it?

**Comment by ianc911** [comment]
Actually, after a little more looking, I think "Start at the experimental feature flag" really means "Start Chrome with the experimental feature flag", as in "chrome.exe --enable-features=SameSiteDefaultChecksMethodRigorously".

Someone needs some proofreading skills... ;)

**Comment by hpsin** [comment]
This is correct - we're updating it now, thanks.

**Comment by tarekd** [comment]
Thanks for the feedback, folks. Also you can just enable the settings from the UI.
