### ISSUE TITLE
Please pull article. It's outdated.

### ISSUE THREAD

**Issue by denniwil** [MicrosoftDocs/OfficeDocs-Support#33]
Data Access pages were deprecated in Access 2010. https://support.office.com/en-us/article/discontinued-features-and-modified-functionality-in-access-2010-9714e5e4-4bbc-490f-97b6-29a7730381cb

Please pull this article as this functionality no longer works as expected in recent browsers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be0cc41a-a1f6-130e-22cf-b50cd061e37b
* Version Independent ID: ea2886ff-15d7-b2d8-63e5-cb3e7c97e357
* Content: [How To Connect an HTML Page to a Microsoft Access Database - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/html-page-connects-access-database#feedback)
* Content Source: [Office/Client/access/html-page-connects-access-database.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/html-page-connects-access-database.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Following up on this feedback.

**Comment by simonxjx** [comment]
Article is removed.
