### ISSUE TITLE
Explain difference between "User Logon" task and Time scheduled task

### ISSUE THREAD

**Issue by weigh2tall** [MicrosoftDocs/OfficeDocs-Support#333]
These two tasks seem to be redundant and we are having issues with the "non-logon' version of the task locking up the CPU because it "sees the same task is already running".  
If SDXHelper is being called on user logon or unlock, why does it also need to be called at a timed interval?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c3b7888-83d6-8d09-c293-af0a55f5d05b
* Version Independent ID: 4cc2574d-f4e8-d727-c6c1-59bf17aa153b
* Content: [Office Feature Updates task description and FAQ - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/updates/office-feature-updates-task-faq#feedback)
* Content Source: [Microsoft365/admin/updates/office-feature-updates-task-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/updates/office-feature-updates-task-faq.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by awalman** [comment]
I'm seeing this problem on WVD installs with Office ProPlus - multiple uses logging in at the same time are causing multiple instances of SDXHelper to run, and bring the session hosts to an unusable state. Changing the task, to disabled for example, is then undone by any Office repairs or updates. SDXhelper either needs fixing or changes to the tasks need to be allowed to remain.

**Comment by nam31** [comment]
@weigh2tall The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content ?
Thank you.

**Comment by nam31** [comment]
@weigh2tall We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
