### ISSUE TITLE
Alerts not sent immediately

### ISSUE THREAD

**Issue by kevintaber** [MicrosoftDocs/OfficeDocs-Support#334]
What about instances where alerts ARE received but not immediately as selected? We are seeing alerts delayed hours and days in some cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bab7a81a-6c24-4dab-0fb3-69d0170576c6
* Version Independent ID: 92c808f7-2e1f-8cad-c0d4-56ca93739e3a
* Content: [Users don't receive SharePoint Online alert notifications - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sites/no-alert-notifications)
* Content Source: [SharePoint/SharePointOnline/sites/no-alert-notifications.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sites/no-alert-notifications.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @v-miegge
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@kevintaber The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content ?
Thank you.

**Comment by nam31** [comment]
@kevintaber We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
