### ISSUE TITLE
Behavior still seems to exist

### ISSUE THREAD

**Issue by jeff-bryant** [MicrosoftDocs/OfficeDocs-Support#336]
I've attempted to do what is outlined using SharePoint Online in Modern Mode and still do not see this working properly.  I thought perhaps it was something that I did not have configured correctly, however when I switch to Classic mode, everything works as expected.
I'd really like to see this working and will continue to search for a solution that will work with SPO in Modern Mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93b7fa94-4918-3789-1392-6c88a4abff1f
* Version Independent ID: 8ed491fb-d6bd-47b7-06d1-d01ba7b94e1b
* Content: [Per-location view settings don't work at the folder level - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/lists-and-libraries/per-location-view-settings-fail-working#feedback)
* Content Source: [SharePoint/SharePointOnline/lists-and-libraries/per-location-view-settings-fail-working.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/lists-and-libraries/per-location-view-settings-fail-working.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments and feedback.
