### ISSUE TITLE
Update Firmware Version

### ISSUE THREAD

**Issue by Brownmattc** [MicrosoftDocs/OfficeDocs-Support#338]
Is the firmware version on this page still accurate?  "The new firmware release version is 5.5.1.11526"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92da332f-edb9-e81c-dd55-da248110c5c3
* Version Independent ID: 5d1a3ecb-1f3a-75b9-1a8b-0fe7689ca83d
* Content: [New features in the firmware update for Polycom VVX IP phones - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/server-phone-system/new-features-in-firmware-update#feedback)
* Content Source: [SkypeforBusiness/SkypeServer/server-phone-system/new-features-in-firmware-update.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeServer/server-phone-system/new-features-in-firmware-update.md)
* Service: **skype-for-business-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@Brownmattc this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@Brownmattc We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
