### ISSUE TITLE
Needs updates for Skype for Business 2015/2019

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Support#339]
Should include 2015 and 2019 as well as any changes given those versions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd32f2c0-4cd9-e181-40cd-aa6aa95220c2
* Version Independent ID: 0726178a-ed69-80d5-278d-914162bcf7dc
* Content: [Integrate Exchange Online with Skype for Business hybrid deployment - Skype for Business](https://docs.microsoft.com/en-us/SkypeForBusiness/troubleshoot/online-exchange-integration/integrate-exchange-online-skype-for-business#feedback)
* Content Source: [SkypeforBusiness/SkypeOnline/online-exchange-integration/integrate-exchange-online-skype-for-business.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeOnline/online-exchange-integration/integrate-exchange-online-skype-for-business.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by TobyTu** [comment]
Retire and Redirect these two articles:
https://docs.microsoft.com/en-us/SkypeForBusiness/troubleshoot/online-exchange-integration/integrate-exchange-online-skype-for-business

https://docs.microsoft.com/en-us/SkypeForBusiness/troubleshoot/online-exchange-integration/exchange-server-lync-server-hybrid

To:
https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-configuring-hybrid-deployments
