### ISSUE TITLE
Deprecated feature. Please pull article

### ISSUE THREAD

**Issue by denniwil** [MicrosoftDocs/OfficeDocs-Support#34]
Data Access pages were deprecated in Access 2010. https://support.office.com/en-us/article/discontinued-features-and-modified-functionality-in-access-2010-9714e5e4-4bbc-490f-97b6-29a7730381cb

Please pull article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0378a981-8e7c-81cc-1091-0df1c268eac4
* Version Independent ID: de46bdc8-d4be-f034-3561-67964034d652
* Content: [An error when you create a data access page in Access - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/create-data-access-page)
* Content Source: [Office/Client/access/create-data-access-page.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/create-data-access-page.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Checking this issue.

**Comment by simonxjx** [comment]
Article is removed.
