### ISSUE TITLE
This workaround is not working

### ISSUE THREAD

**Issue by RameshSeervi** [MicrosoftDocs/OfficeDocs-Support#343]
I've tried this workaround on multiple machines and the issue does not get resolved. I've seen this issue occur on many Office builds and with various Windows 10 build combinations. 
Please try to find the root cause and help with a final fix. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3e1325-8447-d157-729e-f668bef41db0
* Version Independent ID: f411b63a-8be9-9ac4-3f1c-8746216d243d
* Content: [Office Applications crash or cannot start - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/office-crash-or-cannot-start#feedback)
* Content Source: [Microsoft365/enterprise/administration/office-crash-or-cannot-start.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/enterprise/administration/office-crash-or-cannot-start.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by todmccoy** [comment]
Article updated.

**Comment by Jay-NI** [comment]
The same problem with me. The value was already '1'. I keep getting the error, "element not found" for my word documents. The ppts and excel files open for me, however.  Please help
