### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by potatoqualitee** [MicrosoftDocs/OfficeDocs-Support#344]
All not found: Description of the numbering scheme for product code GUIDs in Office 2016
Description of the numbering scheme for product code GUIDs in Office 2013
Description of the numbering scheme for product code GUIDs in Office 2010

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7b83c15-5559-e4b2-c66d-a45003378637
* Version Independent ID: 035c45d0-631d-41e4-2a62-2a2ad3dd709c
* Content: [How to automate the uninstallation of an Office update programmatically - Office](https://docs.microsoft.com/en-us/office/troubleshoot/installation/automate-uninstall-office-update)
* Content Source: [Office/OfficeExperts/installation/automate-uninstall-office-update.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/installation/automate-uninstall-office-update.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **ericspli**

**Comment by jlriesco** [comment]
All the redirects (links) have been fixed.
