### ISSUE TITLE
These options are selected but greyed out

### ISSUE THREAD

**Issue by jedilowe** [MicrosoftDocs/OfficeDocs-Support#345]
The instructions are valid, but they don't seem to make sense.  Both options are checked but greyed out, so does that mean they are active (they are not) and cannot be inactive, or they are inactive because they are grey?  I don't love the mac, but here I feel this is not their problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04a174f0-107a-caf2-09b0-003c90fa1d2f
* Version Independent ID: 91df925f-965a-b706-384e-11e1b66c0e65
* Content: [Scroll bars are missing in Word for Mac - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/word-scroll-bars-missing#feedback)
* Content Source: [Office/Client/word/word-scroll-bars-missing.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/word-scroll-bars-missing.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Close this one as the article is already redirected.
