### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by petegaist** [MicrosoftDocs/OfficeDocs-Support#346]
"If enterprise customers learn that most of their apps are affected, or if they have enough time to test their apps before the Chrome Stable version release date."

The second part should be: 

...or if they do not have enough time to test their apps ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b6e323a-6fb2-c1a6-3afa-b88ed1ad419c
* Version Independent ID: ca05aa94-6799-3961-d83b-8fab9cf83be1
* Content: [Chrome SameSite cookie behavior effect on customer applications - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/miscellaneous/chrome-behavior-affects-applications#feedback)
* Content Source: [Microsoft365/admin/miscellaneous/chrome-behavior-affects-applications.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/miscellaneous/chrome-behavior-affects-applications.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by jlriesco** [comment]
Fixed. Closing this issue.
