### ISSUE TITLE
Regarding the symptom: An Office program is either mostly all white or all black.

### ISSUE THREAD

**Issue by jacksondk** [MicrosoftDocs/OfficeDocs-Support#348]
I had the opposite experience with my Office install. After an upgrade of Windows 7 to Windows 10 99% of the UI of all Office applications was black or white depending on the theme - the elements "was" there as an inspection of the application using "inspect.exe" showed that e.g. the ribbon "was there". Upgrading all drivers, reinstall etc did not work. However, enabling HW acceleration via the registry brought back the UI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8d561d1-d212-5808-25f5-965cb97e83ea
* Version Independent ID: f94c75c6-b141-691a-49d2-c885cc3ffa1e
* Content: [Display issues in Office client applications. - Office](https://docs.microsoft.com/en-us/office/troubleshoot/settings/office-display-issues#feedback)
* Content Source: [Office/Client/settings/office-display-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/settings/office-display-issues.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment.
