### ISSUE TITLE
Wrong info....

### ISSUE THREAD

**Issue by koumouts** [MicrosoftDocs/OfficeDocs-Support#35]
1. Options Menu
2. Formulas
3. Uncheck "working with formulas"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d300911-341a-ea5e-e35c-192b36351da0
* Version Independent ID: 1b2b5e86-4e2e-ab3f-7513-db547695e831
* Content: [Columns and rows are labeled numerically - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/numeric-columns-and-rows%20labels#feedback)
* Content Source: [Office/Client/excel/numeric-columns-and-rows%20labels.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/numeric-columns-and-rows%20labels.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Checking this issue.

**Comment by jlriesco** [comment]
I think the info in the article dates back to 2003 or before (before we had the ribbon). The comment is correct.
File -> Options -> Formulas and under Working with formulas, uncheck R1C1 reference style

We will update and republish the article.

**Comment by simonxjx** [comment]
Updated https://docs.microsoft.com/en-us/office/troubleshoot/excel/numeric-columns-and-rows
