### ISSUE TITLE
Solved in 2020 on macOS Catalina

### ISSUE THREAD

**Issue by deang** [MicrosoftDocs/OfficeDocs-Support#351]
Appears to be a permissions problem.
Go to System Preferences -&gt; Security & Privacy -&gt; Camera -&gt; Privacy.
Grant Skype for Business access to the camera.  You'll be prompted to restart Skype for Business.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68ba9eec-d9df-c870-d637-0f0037a3ecf0
* Version Independent ID: 9cbe8c21-b84b-5525-800f-9f575259fd07
* Content: [Black screen during desktop sharing in Skype for Business on macOS High Sierra - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/server-meetings/desktop-sharing-black-screen-macos-high-sierra#feedback)
* Content Source: [SkypeforBusiness/SkypeServer/server-meetings/desktop-sharing-black-screen-macos-high-sierra.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeServer/server-meetings/desktop-sharing-black-screen-macos-high-sierra.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by TobyTu** [comment]
@deang thanks for sharing, this method has been added in this article,
