### ISSUE TITLE
This helped!

### ISSUE THREAD

**Issue by Keleion** [MicrosoftDocs/OfficeDocs-Support#354]
Thank you for helping me resolve our issue! For my scenario, we use modern auth with FMA. I am trying to create a script that will run on a schedule and needs to run with: 
"Connect-SPOService -Url $adminSiteUrl -Credential $cred" 
This wasn't working because it would force legacy authentication and I would get the error:
"Cannot contact web site 'https://TENANT-admin.sharepoint.com/' or the web site does not support SharePoint Online credentials. The response 
status code is 'Unauthorized'. The response headers are 'X-SharePointHealthScore=4, X-MSDAVEXT_Error=917656;"
This was due to our Azure AD conditional access policy "Default Cloud Access Policy", which was blocking "Other clients" in the Client Apps. After making an exclusion for the service user this worked correctly. But I was getting another error simply saying it could not use OAuth 2.0. For this I followed these steps in this article, but noticed I only needed to make the two keys and not the DWORD. The script now connects to SPO without error.

Thanks so much!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f722b3d-7060-827c-357d-e3acbb5b1eb5
* Version Independent ID: eb0898ea-d02a-31cb-3b8c-e690824a7f92
* Content: [Can't force Modern Authentication when using Connect-SPOService cmdlet in SharePoint Online Management Shell - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/security/cannot-force-modern-authentication#feedback)
* Content Source: [SharePoint/SharePointOnline/security/cannot-force-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/security/cannot-force-modern-authentication.md)
* Service: **sharepoint-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment and feedback. It is happy to hear that your issue is fixed.
