### ISSUE TITLE
Outdated link to Exchange 2010 page, which is if no use to Office 365

### ISSUE THREAD

**Issue by adamlavery** [MicrosoftDocs/OfficeDocs-Support#355]
As said

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd6c33b6-24fb-447d-e9de-c5f11f0aaaae
* Version Independent ID: f5fd953d-bcbf-9315-8336-e43c20ef8022
* Content: [Remove automapping for a shared mailbox - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/domain-management/remove-automapping-for-shared-mailbox#feedback)
* Content Source: [Outlook/Client/domain-management/remove-automapping-for-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/domain-management/remove-automapping-for-shared-mailbox.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@adamlavery this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@adamlavery We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
