### ISSUE TITLE
No stay signed-in option

### ISSUE THREAD

**Issue by ryanturcotte** [MicrosoftDocs/OfficeDocs-Support#358]
If my organization doesn't provide me with the "Stay signed-in option" , like it redirects to an ADFS sign-in, is this possible to allow IE to cache the credentials needed to always connect to the network drive? Shouldn't there be something able to be saved in Credential Manager? I'm not sure the steps above are 100% accurate for the way office 365/sharepoint currently process logins at least for my organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8928ed26-fda0-0e68-a4e1-cc287a5e5699
* Version Independent ID: c6ff303c-a5b4-4890-6d00-82246b92ea45
* Content: [Troubleshoot mapped network drives that connect to SharePoint Online - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/troubleshoot-mapped-network-drives)
* Content Source: [SharePoint/SharePointOnline/administration/troubleshoot-mapped-network-drives.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/administration/troubleshoot-mapped-network-drives.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by ryanturcotte** [comment]
Or if my organization has two-factor enabled?

**Comment by claudialake** [comment]
@ryanturcotte, the only way to "persist a cookie" is only availble for Explorer View. The data in this article under "Establishing the Claim", however may help.
https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/troubleshoot-mapped-network-drives

**Comment by ryanturcotte** [comment]
Did you link me the right page? I’m not seeing that part of the article.
  

  
  

  
  
>

**Comment by jmuehlenbein** [comment]
@claudialake, I'm also not finding the info about establishing a claim in the linked article. Can you please clarify? Thanks!

**Comment by jmuehlenbein** [comment]
I think this is the correct article: https://techcommunity.microsoft.com/t5/sharepoint-support-blog/cookie-persistence-in-sharepoint-online/ba-p/847724

**Comment by claudialake** [comment]
@ryanturcotte and @jmuehlenbein, sorry wrong link. updated.
