### ISSUE TITLE
Step 5's 'get-recipient' is incorrect

### ISSUE THREAD

**Issue by netresults-scott** [MicrosoftDocs/OfficeDocs-Support#359]
When run as documented via steps in this article, produces error: 
Get-Recipient : The term 'Get-Recipient' is not recognized as the name of a cmdlet, function, script file, or operable program. 

I beleive the correct command is 'get-cloudmailbox' per the nearly identical instructions in https://support.microsoft.com/en-ca/help/2643629/one-or-more-objects-don-t-sync-when-the-azure-active-directory-sync-to

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10fe7667-5c74-325b-7f55-123bde0add23
* Version Independent ID: 353543ec-d9e0-5166-1ec4-1b68c388f431
* Content: [Troubleshoot directory synchronization errors with event 6941 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/active-directory/duplicate-attributes-prevent-dirsync)
* Content Source: [Microsoft365/admin/active-directory/duplicate-attributes-prevent-dirsync.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/active-directory/duplicate-attributes-prevent-dirsync.md)
* Service: **o365-administration**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The article is updated. Thanks for the comment.
