### ISSUE TITLE
Errors in the paths for files to be deleted

### ISSUE THREAD

**Issue by sdagley** [MicrosoftDocs/OfficeDocs-Support#36]
All of the paths in Step 4b are incorrect. They are missing the 2nd node of the path which should be the short name for the user account (e.g. the current path /Users//Library/Containers/com.microsoft.SkypeForBusiness should be /Users/shortname/Library/Containers/com.microsoft.SkypeForBusiness). You could also use the a leading ~ in the path to indicate the user's home directory which would be simpler: ~/Library/Containers/com.microsoft.SkypeForBusiness

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5738299a-feb3-740e-aa42-5814f797a607
* Version Independent ID: e5373833-2a2e-0c3b-03fb-933de37c0d42
* Content: [How to do a clean uninstallation of Skype for Business on Mac - Skype for Business](https://docs.microsoft.com/en-us/SkypeForBusiness/troubleshoot/server-install-or-uninstall/clean-uninstallation#feedback)
* Content Source: [SkypeforBusiness/SkypeServer/server-install-or-uninstall/clean-uninstallation.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeServer/server-install-or-uninstall/clean-uninstallation.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Cloud-Writer** [comment]
Contacted the SME to confirm.

**Comment by Cloud-Writer** [comment]
The procedure has been updated with the correct commands that need to be run.
