### ISSUE TITLE
Exact same problem, but there is no "Workflow Settings" page to browse to

### ISSUE THREAD

**Issue by ShamelessCamper** [MicrosoftDocs/OfficeDocs-Support#360]
I downloaded DharePoint Designer 2013 like the article says, and when I open my workflow in it, I see a page that has a settings box in it, but not a settings page.  The settings box only contains a dropdown for language and "show workflow visualization on status page".   There is no settings page to browse to as far as I can tell, and the "automatically update" line mentioned in this article doesn't appear anywhere on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7f06f80-4426-24f8-23a2-eb473c04d8df
* Version Independent ID: 1012e3f8-c790-886d-fc1f-3151dfcff196
* Content: [SharePoint item that requires content approval reverts to Pending status - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/workflows/item-pending-status#feedback)
* Content Source: [SharePoint/SharePointOnline/workflows/item-pending-status.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/workflows/item-pending-status.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by claudialake** [comment]
Hi @ShamelessCamper, to access the Workflow page, do one of the following:

1. click on the Workflow then click Workflow Settings,
2. right-click the Workflow then click Workflow Settings,
3, or select the workflow and click  the Workflow tab to go to Workflow settings page
