### ISSUE TITLE
"Run gpupdate/force to make the policy take effect immediately."

### ISSUE THREAD

**Issue by evilensky** [MicrosoftDocs/OfficeDocs-Support#363]
Why is the `/force` flag needed here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3174785-7824-784b-692d-d9ace42a3fee
* Version Independent ID: 3a4a952d-7776-2f87-2f2b-4214e959d7d8
* Content: [Site slowness because of SharePoint STS certificate CRL checking - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sites/site-slowness-because-of-sts-certificate-crl-checking#feedback)
* Content Source: [SharePoint/SharePointServer/sites/site-slowness-because-of-sts-certificate-crl-checking.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointServer/sites/site-slowness-because-of-sts-certificate-crl-checking.md)
* Service: **sharepoint-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by claudialake** [comment]
@evilensy, the /force parameter reapplies all policy settings. By default, gpupdate only applies policy settings that have changed.
