### ISSUE TITLE
Utterly useless

### ISSUE THREAD

**Issue by NeilGazz** [MicrosoftDocs/OfficeDocs-Support#364]
As far as I can see the information relating W10 on this page with the specified error is out of date and misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8e36de2-8956-ed6f-61b7-2d2ba7b2e7b0
* Version Independent ID: 1e05c7a3-20df-ad99-9fb4-8d3b509f521a
* Content: [Outlook continually prompts for password when you try to connect to Office 365 - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/sign-in/continually-prompts-password-office-365#feedback)
* Content Source: [Outlook/Client/sign-in/continually-prompts-password-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/sign-in/continually-prompts-password-office-365.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Cloud-Writer** [comment]
The steps for Win 10 have been verified to be correct.
