### ISSUE TITLE
SharePoint 2013

### ISSUE THREAD

**Issue by oswin-e1** [MicrosoftDocs/OfficeDocs-Support#365]
Is there a patch planned for SharePoint Server 2013 too?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b6e323a-6fb2-c1a6-3afa-b88ed1ad419c
* Version Independent ID: ca05aa94-6799-3961-d83b-8fab9cf83be1
* Content: [Chrome SameSite cookie behavior effect on customer applications - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/miscellaneous/chrome-behavior-affects-applications#feedback)
* Content Source: [Microsoft365/admin/miscellaneous/chrome-behavior-affects-applications.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/miscellaneous/chrome-behavior-affects-applications.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by TobieFysh** [comment]
I doubt it based on SharePoint 2013 being out of mainstream support, if they do it for SharePoint then they will have to do it for Lync Server 2013 too:

https://support.microsoft.com/en-gb/lifecycle/search?alpha=SharePoint%20Server%202013%20Service%20Pack%201

**Comment by TobieFysh** [comment]
@oswin-e1 WOW, I was wrong, based on the table there are going to be fixing in SharePoint 2010 and up.

**Comment by MaryQiu1987** [comment]
Close the issue.
