### ISSUE TITLE
A SharePoint file is downloaded instead of opening the Office application with a direct connection to it

### ISSUE THREAD

**Issue by Madhu-Vana** [MicrosoftDocs/OfficeDocs-Support#367]
As per the given remedy, we can add the suggested texting(?web=1) in the browser url. It's fine, if user just need one file to open. Let's assume, if user needs to work on multiple files from different libraries then how can he add suggested texting each time to the URL. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc277ba5-3c58-12d9-e817-a9cece03c5dc
* Version Independent ID: cade746d-2a43-7ee1-6ab6-9cd378e5efc2
* Content: [A SharePoint file is downloaded instead of opening the Office application with a direct connection to it - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/lists-and-libraries/files-downloaded-instead-of-opening-office-application#feedback)
* Content Source: [SharePoint/SharePointExperts/lists-and-libraries/files-downloaded-instead-of-opening-office-application.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointExperts/lists-and-libraries/files-downloaded-instead-of-opening-office-application.md)
* Service: **sharepoint-online**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **warrenr**

**Comment by VLG17** [comment]
@Madhu-Vana You could test a URL rewrite extension in Chrome, and think of a rule that would rewrite the URL to add ?web=1 at the end of the URL.

As far as I know, there is no way of doing this from SharePoint side. Keeping in mind you see this only when using Chrome, it would make sense to implement a "fix" on the Chrome side.

**Comment by VLG17** [comment]
@Madhu-Vana any updates? What do you think of the previous suggestion?

**Comment by nam31** [comment]
@Madhu-Vana We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
