### ISSUE TITLE
PowerShell not optimal

### ISSUE THREAD

**Issue by PChipVIA** [MicrosoftDocs/OfficeDocs-Support#369]
Since PowerShell is a Microsoft product, the codes on the MS pages should present the best features of the tool.  In this case, the pipeline is not used when it should have been.
The following line is not optimal:
Get-ADUser -SearchBase "OU=Italy,OU=Countries,DC=contoso,DC=com" -Filter * -Properties PreferredLanguage | ForEach-Object {Set-ADUser $_.SAMAccountName –replace @{PreferredLanguage="it-it"}}

There is no reason to use a ForEach as the Pipeline will correctly pipe the information.  Also, there is no reason to Get the PreferredLanguage attribute as it is not used further down the road.  Thus it should read:
Get-ADUser -SearchBase "OU=Italy,OU=Countries,DC=contoso,DC=com" -Filter * | Set-ADUser –replace @{PreferredLanguage="it-it"}}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c5d2597-6e11-7c74-1af1-50dd21364593
* Version Independent ID: 4bdf974e-3408-1408-6272-96323b0ad7b6
* Content: [Set language and region settings for Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/set-language-and-region)
* Content Source: [Microsoft365/admin/access-management/set-language-and-region.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/access-management/set-language-and-region.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
Closing via #1535 
Thank you
