### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Mugen593** [MicrosoftDocs/OfficeDocs-Support#37]
This doesn't even work at all. I've seen a few posts on technet that refer to these instructions and every single one ended up having to use the XML import with the existing template. This custom template doesn't work.
I tested with multiple different versions of Windows 10 from 1607 to 1903.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85707799-bb03-361a-9542-e2b4bd9cfefe
* Version Independent ID: 299e2b5c-bdab-c9ee-6c2e-a20f334ed02b
* Content: [How to configure the default e-mail client using Group Policy - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/configure-email-client-using-policy#feedback)
* Content Source: [Microsoft365/admin/administration/configure-email-client-using-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/configure-email-client-using-policy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Checking on this issue.

**Comment by Mugen593** [comment]
We ended up using the XML way with the default app association policy. Couldn't get the policy in this article to overwrite it even after signing out and signing in.
I saw the policy and enabled it. Machine was getting the policy 100 percent. I used the same policy to do the default app gpo with the XML file and that took. Has anyone had success with this policy or able to replicate?

**Comment by bkell904** [comment]
Like what was stated in July. DO NOT WORK! Tested on 1803 by importing into the local policy store. Seems odd to go to the trouble of creating a classic policy template when the same thing can be done with a policy preference for the same registry value.

**Comment by msbemba** [comment]
@Mugen593 Thank you for your feedback. I was able to test it on windows 10 and we have added steps for windows 10 to the document - https://docs.microsoft.com/en-us/office365/troubleshoot/group-policy/configure-email-client-using-policy#windows-10-and-windows-8

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@Mugen593 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
