### ISSUE TITLE
Need Mac instructions

### ISSUE THREAD

**Issue by 2sylbl** [MicrosoftDocs/OfficeDocs-Support#370]
Having the same problem with Mac but there are no instructions for that platform

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 003b3cba-164f-4443-ad85-9509a54a125b
* Version Independent ID: c237b7a5-7b05-900d-adab-df43daed3d8a
* Content: [You can't successfully dismiss calendar reminders in Outlook - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/calendar-reminders/cannot-dismiss-outlook-calendar-reminders#feedback)
* Content Source: [Exchange/ExchangeHybrid/calendar-reminders/cannot-dismiss-outlook-calendar-reminders.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/calendar-reminders/cannot-dismiss-outlook-calendar-reminders.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by florianmutter** [comment]
You could try this in the terminal:
```
cd /Applications/Microsoft Outlook.app/Contents/MacOS
./Microsoft\ Outlook /cleanreminders
```

Found here: https://superuser.com/a/690724/289519

**Comment by dariomws** [comment]
Hi @2sylbl, thank you for your feedback.

As @florianmutter commented, you should use that command in Mac. Thank you for that.

**Comment by nam31** [comment]
@2sylbl Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks
