### ISSUE TITLE
Need a little clarification, please.

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-Support#371]
Is the Hide OneDrive Personal option only for the OneDrive Personal icon?  That is, it seems users can still right click on the OneDrive for Business icon in their system tray, choose Settings, then Add an Account from the Account tab to add their own OneDrive account.  How can you prevent users from adding any other account other than the business's tenant OneDrive service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6c2afc6-5df6-43c4-c3f8-29649089d075
* Version Independent ID: 3b2b8534-4ca1-30d1-6acb-9db590f3577a
* Content: [How to block OneDrive use from within Office 365 ProPlus and Office 2016 applications - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/group-policy/block-onedrive-use-from-office#use-a-group-policy-object)
* Content Source: [Microsoft365/admin/group-policy/block-onedrive-use-from-office.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/group-policy/block-onedrive-use-from-office.md)
* Service: **one-drive**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@Canis-Lupis You are right, you could still add your personal account via the OneDrive for Business. You could use the "DisablePersonalSync" regkey to achieve your goal.

Mode details [here](https://docs.microsoft.com/en-us/onedrive/use-group-policy#prevent-users-from-syncing-personal-onedrive-accounts)

**Comment by nam31** [comment]
@Canis-Lupis Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
