### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/OfficeDocs-Support#372]
There's a typo on the new CsHostingProvider command, should be AlwaysVerifiable instead of AlwayVerifiable

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6de9348b-8010-0dc4-3ca2-42ad3511a9c2
* Version Independent ID: 3773c897-157b-5103-0ec5-ef5d5f8af009
* Content: [You are operating in a split-domain (hybrid) topology when set call queue - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/hybrid-phone-system/issue-configure-call-queue?source=docs)
* Content Source: [SkypeforBusiness/SkypeHybrid/hybrid-phone-system/issue-configure-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeHybrid/hybrid-phone-system/issue-configure-call-queue.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The command is updated.
