### ISSUE TITLE
False

### ISSUE THREAD

**Issue by Alan-Langer** [MicrosoftDocs/OfficeDocs-Support#376]
The information posted here is false. It does not prevent a user from creating new distribution groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba33f5bf-7fd8-5833-4390-322ca80d0bf9
* Version Independent ID: bfaf769f-98f9-0d26-043a-96b8fd6b68bd
* Content: [Prevent users from creating and managing distribution groups in Office 365 - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/distribution-groups/prevent-users-create-manage-dg#feedback)
* Content Source: [Exchange/ExchangeOnline/distribution-groups/prevent-users-create-manage-dg.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/distribution-groups/prevent-users-create-manage-dg.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello @Alan-Langer ,
are you sure you assigned policy correctly? the provided instruction is correct and it is expected that user will not be able to create groups.
Thank you

**Comment by MaratMussabekov** [comment]
Hello @Alan-Langer ,
Did you have a chance to check it?
Thank you

**Comment by nam31** [comment]
@Alan-Langer We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
