### ISSUE TITLE
link to Set-MailboxAutoReplyConfiguration wrong 

### ISSUE THREAD

**Issue by BlackJebus** [MicrosoftDocs/OfficeDocs-Support#378]
Link at the bottom of the page https://docs.microsoft.com/en-us/exchange/troubleshoot/configure-mailboxes/set-automatic-replies
the link to -> Set-MailboxAutoReplyConfiguration sends to wrong address, 
Sends them to this address 
https://support.office.com/en-us/article/Automatic-replies-formerly-Out-of-office-assistant-48D40166-0129-4653-98F1-EB85F9BD8C20

should be 
https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-mailboxautoreplyconfiguration?view=exchange-ps

**Comment by nam31** [comment]
@BlackJebus, we are going to close this issue as the article has been updated accordingly. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
