### ISSUE TITLE
Incorrect Keys for O365

### ISSUE THREAD

**Issue by tokenwill** [MicrosoftDocs/OfficeDocs-Support#381]
In our environment we have to run the registry as admin. In order to make this work, we created a script to edit the key under the users SID.

HKEY_USERS\$($Item.SID)\Software\Policies\Microsoft\office\16.0\outlook\
HKEY_USERS\$($Item.SID)\Software\Policies\Microsoft\office\16.0\outlook\PST

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a50a221-2351-475b-4b9a-a386b6f5aafd
* Version Independent ID: 4dc840ed-e321-aaf1-bdc1-4030e0163d6a
* Content: [Outlook policy to control PST use and creation in Office 365 Import service - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/outlook-policy/control-pst-use#feedback)
* Content Source: [Exchange/ExchangeHybrid/outlook-policy/control-pst-use.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/outlook-policy/control-pst-use.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The article is updated with the latest information about registry keys.
