### ISSUE TITLE
That's exactly what I needed

### ISSUE THREAD

**Issue by Sir4o** [MicrosoftDocs/OfficeDocs-Support#382]
Helped me fix the O365 Onedrive visibility

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6c2afc6-5df6-43c4-c3f8-29649089d075
* Version Independent ID: 3b2b8534-4ca1-30d1-6acb-9db590f3577a
* Content: [How to block OneDrive use from within Office 365 ProPlus and Office 2016 applications - Office 365](https://docs.microsoft.com/en-gb/office365/troubleshoot/group-policy/block-onedrive-use-from-office#feedback)
* Content Source: [Microsoft365/admin/group-policy/block-onedrive-use-from-office.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/group-policy/block-onedrive-use-from-office.md)
* Service: **one-drive**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. You can download OneDrive via https://products.office.com/en-us/onedrive/download. You can also visit https://support.office.com/en-us/onedrive for further support.
