### ISSUE TITLE
The last link on controlling Outlook AutoDiscover by Group policy doesn't include 2013, 2016, 2019

### ISSUE THREAD

**Issue by GLComputing** [MicrosoftDocs/OfficeDocs-Support#383]
Isn't it about time to update this ... New Template links and new controls (eg ExcludeExplicitO365Endpoint)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5128fe3-c5d0-be69-afc4-bbb644c3a303
* Version Independent ID: a5b9870b-4d90-b98a-8fa0-85ce84334eb3
* Content: [Unexpected Autodiscover behavior if settings under the \Autodiscover key - Outlook](https://docs.microsoft.com/en-au/outlook/troubleshoot/domain-management/unexpected-autodiscover-behavior)
* Content Source: [Outlook/Client/domain-management/unexpected-autodiscover-behavior.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/domain-management/unexpected-autodiscover-behavior.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by GLComputing** [comment]
In fact, might add a link to the new details on the AutoDiscover service in the "White Paper" section in this page, also

**Comment by nam31** [comment]
@GLComputing this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@GLComputing We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
