### ISSUE TITLE
Another Workaround

### ISSUE THREAD

**Issue by MrcACrl** [MicrosoftDocs/OfficeDocs-Support#384]
Went through everything there. None of the above helped, but I did find a quick workaround, though the issue itself persists. Read on...

Just to explain the issue I've been having, as precisely as I can: the worksheet appears blank (like there are no cell contents and Gridlines have been turned off in the View menu) but the Formula Bar shows the entries in individual cells of the workbook. So it is more precise to say that the cells aren't being displayed (in their entirety - no formatting no contents, no Gridlines) on the worksheet. However if the workbook was last closed with a range of cells selected, the selection box remains visible after re-opening (but, as above, no cells, cell contents or cell formatting) in accordance with standard Excel behavior to save the selected range upon closing a workbook and re-displaying said range open re-opening a given workbook.

A simple resolution for me has been to use the "restore/maximize" window control button (viz. minimize, restore / maximize, close) in the upper right of the window to restore the application window from a maximized view, and the full contents of the cells suddenly appear. I note that Excel doesn't seem to allow me to open a workbook with the window unmaximized, so the bug may be lurking somewhere in that behavior.

Anyway, until this is resolved, I'll just be "restoring" the window if a workbook opens blank. Another workaround is to open a blank workbook, which doesn't seem to have the issue, and then open your desired workbook after opening the blank one and having the cells dsiplayed on the worksheet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62a88c46-43bb-92cf-c409-c8b3071b3865
* Version Independent ID: 19f5e98e-36a5-e2e9-39b1-5fc5ae349b50
* Content: [Troubleshoot Excel opening blank when double-click a file icon or file name - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/excel-opens-blank#feedback)
* Content Source: [Office/Client/excel/excel-opens-blank.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/excel-opens-blank.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MrcACrl** [comment]
And by blank workbook above, I mean a new workbook.

**Comment by todmccoy** [comment]
Thank you! We have added this to the document.
