### ISSUE TITLE
There is a workaround for this.

### ISSUE THREAD

**Issue by jameslear** [MicrosoftDocs/OfficeDocs-Support#387]
One can edit the range in the Select Data popup.  When the range is selected, place a comma between the ordinary data table rows and the total row.  E.g. ='Balance Sheet Summary'!$C$3:$C$4,'Balance Sheet Summary'!$C$5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d456799-7b50-f2f8-a25d-7ca6ade39dba
* Version Independent ID: e1897375-a875-ac9f-f05f-2f2235c4bc40
* Content: [Total row of a table isn't displayed in waterfall charts - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/table-total-row-not-shown-in-waterfall)
* Content Source: [Office/Client/excel/table-total-row-not-shown-in-waterfall.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/table-total-row-not-shown-in-waterfall.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by jlriesco** [comment]
I reproduced as best as I could from the article and the workaround proposed did not seem to work for me with O365. Excel seems to know that it is a total row and it doesn't make sense to include the total in the chart.

In Excel 2016 perpetual (msi) the chart just includes the Total row when you create it.

**Comment by jameslear** [comment]
It may be a little tricky.  Here's the exact sequence I use.
Create the waterfall chart.
![image](https://user-images.githubusercontent.com/20506085/76000837-e3b5c780-5ec9-11ea-9ce0-8e35d2f21b56.png)
Edit the series
![image](https://user-images.githubusercontent.com/20506085/76000872-ee705c80-5ec9-11ea-969b-87f8541e039b.png)
![image](https://user-images.githubusercontent.com/20506085/76000927-0051ff80-5eca-11ea-8021-4a5a26d010bc.png)
The total is now included in the series.
![image](https://user-images.githubusercontent.com/20506085/76000983-1069df00-5eca-11ea-9df6-f4b2d6a263de.png)
Select the last data point, and mark it as the total.
![image](https://user-images.githubusercontent.com/20506085/76001067-29729000-5eca-11ea-9f8e-9d2067148719.png)
![image](https://user-images.githubusercontent.com/20506085/76001074-2bd4ea00-5eca-11ea-9624-5b5c6f14871b.png)
