### ISSUE TITLE
COM add-ins are not displayed in Office 365 pro plu

### ISSUE THREAD

**Issue by SajiSam** [MicrosoftDocs/OfficeDocs-Support#388]
COM add-ins are not displayed in Office 365 pro plus? please help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04b68dcc-cad8-ce6d-db63-28bb3bb448ab
* Version Independent ID: 5d41456e-51c0-c4b1-02ad-232f136705e3
* Content: [COM add-ins are not displayed in the COM Add-Ins dialog box - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/com-add-ins-not-displayed#feedback)
* Content Source: [Office/Client/excel/com-add-ins-not-displayed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/com-add-ins-not-displayed.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. Please make sure you have the latest update installed according to https://support.office.com/en-us/article/install-office-updates-2ab296f3-7f03-43a2-8e50-46de917611c5. If the issue persists, you can contact Office 365 support via https://support.office.com/home/contact.
