### ISSUE TITLE
Typo in title

### ISSUE THREAD

**Issue by jmillerFLND** [MicrosoftDocs/OfficeDocs-Support#389]
Title of this site in the left nav has a typo.
"Issue when creating an onilne ste". FYI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2ee4188-775b-b108-604a-257595dfab6f
* Version Independent ID: 833002d5-8187-0ee1-9bb1-4ad631a66132
* Content: [Site names cannot contain certain reserved words when you create a new subsite - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sites/site-names-cant-contain-reserved-word)
* Content Source: [SharePoint/SharePointOnline/sites/site-names-cant-contain-reserved-word.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sites/site-names-cant-contain-reserved-word.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The TOC is updated.
