### ISSUE TITLE
Workaround is on the data entry side. What about on formula

### ISSUE THREAD

**Issue by FrankKooijman** [MicrosoftDocs/OfficeDocs-Support#39]
ISBlank() is one of those formula that is in itself a workaround. Likely a workaround for a rather large number of cell. So suggesting a workaround to go and 'fix; a large number of cells is not a real workaround, or maybe just a terrible one.
What about a workaround on formula side. Can it be OR( Len()=0, Isblank() )? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 833fe32e-a4c2-a70c-3755-34914666577b
* Version Independent ID: 7a1c3712-4d0b-1fd7-4ce9-c8bade7f5b9b
* Content: [The result is false when you use the ISBLANK function - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/isblank-function-return-false#feedback)
* Content Source: [Office/Client/excel/isblank-function-return-false.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/isblank-function-return-false.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Checking on this issue. I will post an update next week.

**Comment by jlriesco** [comment]
The comment is accurate. The workaround in the article talks about clearing out the cells, but the commenter has a good point. I think we would add the suggestion as a second, alternate solution. This formula will return the results you are expecting even if the cells contain info described in the 4 bullets under More Information.
OR( Len()=0, Isblank() ) Example, if the cell you are checking is A1, the formula would be OR( Len(A1)=0, Isblank(A1) )
