### ISSUE TITLE
Connection to Access database crashes using OLEDB provider (since O365 Build 12430.20184)

### ISSUE THREAD

**Issue by rainan16** [MicrosoftDocs/OfficeDocs-Support#390]
**Environment:** 
- Office 365 Version 2001 (Build 12430.20184) and later
- .NET 4.6 using OLEDB provider
- COM-Interop component (32bit)
- Access 2007 databases

**Connection String:**
`Provider=Microsoft.ACE.OLEDB.12.0; Data Source=C:\temp\dat.mdb`

**Incidence:**
- more than 300 identical crashes reported in Feb. 2020 (different PCs / configurations)
- Windows 7 to latest Win10

**Symptoms**:
- app crash when invoking `conn.Open()`

> Keine Fehlermeldung verfügbar, Fehlercode: E_UNEXPECTED(0x8000FFFF).
>    bei System.Data.OleDb.OleDbConnectionInternal..ctor(OleDbConnectionString constr, OleDbConnection connection)
>    bei System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject)
>    bei System.Data.ProviderBase.DbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
>    bei System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
>    bei System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
>    bei System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
>    bei System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
>    bei System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
>    bei System.Data.OleDb.OleDbConnection.Open()

- no crashes when using direct DAO access
- no crashes when using ODBC driver instead of OLEDB provider
- no crashes after rolling back to an older Office 365 Build

**Workaround reported by many clients (not persistent)**
Installing Office 2007 Database Engine or Office 2010 Database Engine fixes it, until a new O365 update is deployed.

**Additional notice**
Weird: a sample app to reproduce the error crashes after der third consecutive `conn.Open()` attempt.
No problems have been reported for office installations other than O365 (monthly update). So far.

**Comment by nam31** [comment]
@rainan16 The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@rainan16 We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
