### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by uido123** [MicrosoftDocs/OfficeDocs-Support#392]
This link is not helpful:
"View and customize settings in Outlook Web App mailbox policies"[https://help.outlook.com/140/gg192742.aspx]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42e6bb9b-9940-e036-eab9-372576e5b4a0
* Version Independent ID: 465cae18-753a-008e-6298-ff4f4dff9126
* Content: [Office 365 users can't open or view attachments in Outlook Web App - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/owa-attachments/cannot-open-attachments#feedback)
* Content Source: [Exchange/ExchangeOnline/owa-attachments/cannot-open-attachments.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/owa-attachments/cannot-open-attachments.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. As the link is referenced from an old article that is not existed now. We have updated the article with the link removed. Thanks.
