### ISSUE TITLE
URL for main "Excel Help & Training" heading is invalid across ENTIRE Excel Help site

### ISSUE THREAD

**Issue by yukon-cornelius** [MicrosoftDocs/OfficeDocs-Support#393]
Unsure how this gets past Office Support editors ... :-)

The URL for the main "Excel Help & Training" heading across ALL Excel help topics on the Support site is currently invalid.  If you go to a sample page, such as the "IF function" located at ...
https://support.office.com/en-us/article/if-function-69aed7c9-4e8a-4755-a9bc-aa8bbff73be2

And then hover over the "Excel Help & Training" link, like in my attached screenshot, you'll see the URL is pointing to ...
https://support.office.com/en-us/https://support.office.com/en-us/excel

![SupportOfficeCom%en-us%excel](https://user-images.githubusercontent.com/6321786/75623782-96042c80-5b62-11ea-9cfa-675c24d85288.jpg)

**Comment by nam31** [comment]
@yukon-cornelius both of the articles mentioned have been updated. 
Thank you
