### ISSUE TITLE
Several issues with copy and running powershell cmdlets

### ISSUE THREAD

**Issue by surinderv** [MicrosoftDocs/OfficeDocs-Support#394]
There are script formatting issues with carriage returns and missing spaces. Please try copy and paste and you will see issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c80eda87-604d-e321-9754-c9f0447513c4
* Version Independent ID: 96f8b7ae-aceb-4b53-cccd-4a994081fdad
* Content: [Provider-hosted add-ins stop working and HTTP 401 error after you configure SharePoint farm hybrid features - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/provider-hosted-add-ins-stop-working-and-http-401-error-after-configure-farm-hybrid-features#feedback)
* Content Source: [SharePoint/SharePointServer/administration/provider-hosted-add-ins-stop-working-and-http-401-error-after-configure-farm-hybrid-features.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointServer/administration/provider-hosted-add-ins-stop-working-and-http-401-error-after-configure-farm-hybrid-features.md)
* Service: **sharepoint-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The cmdlets are updated.
