### ISSUE TITLE
Read-only issue

### ISSUE THREAD

**Issue by mub-arak** [MicrosoftDocs/OfficeDocs-Support#395]
I did everything, but in the last step it told me that I cannot access a read-only document
How can I resolve the issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29cfe041-911f-a366-832f-3f735555b499
* Version Independent ID: dcc01b3c-60e8-eadd-99ca-3aef750a0083
* Content: [The first sheet name is in a language different from the Office display language - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/first-sheet-name-displays-different-language#feedback)
* Content Source: [Office/Client/excel/first-sheet-name-displays-different-language.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/first-sheet-name-displays-different-language.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by jlriesco** [comment]
@mub-arak Did you try to just create a new document from within Excel (File/New) instead of using the right--clicking in a folder method?

**Comment by Reeced40** [comment]
@mub-arak thank you for reaching out. Has this issue been resolved? If you're still having issues, try signing in with your subscription and make sure there are no other users that could have locked the doc (read-only permissions)

**Comment by Reeced40** [comment]
@mub-arak please can you let me know if this issue is resolved and if we can close it. Thanks again for your valuable input.

**Comment by nam31** [comment]
@mub-arak We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
