### ISSUE TITLE
Sharing options Greyed out

### ISSUE THREAD

**Issue by TausifJam** [MicrosoftDocs/OfficeDocs-Support#396]
If your Tenant and Site collection Level sharing allows Anonymous Access
But if you have "Limited Access Lockdown Mode is enabled" on the site collection.
From Modern UI sharing console "Anyone" and "People in your Organization" Sharing option (Links )will be Greyed out, except Specific People and People with Existing Access.

It will be great if you include this scenario as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59668480-ba24-0bea-bb82-9f7d368a655a
* Version Independent ID: d7f8a814-31ce-cd4f-304e-57382be26310
* Content: [Sharing options are grayed out when sharing from SharePoint Online or OneDrive - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/sharing-options-grayed-out-when-sharing-from-sharepoint-online-or-onedrive#feedback)
* Content Source: [SharePoint/SharePointOnline/administration/sharing-options-grayed-out-when-sharing-from-SharePoint-Online-or-OneDrive.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/administration/sharing-options-grayed-out-when-sharing-from-SharePoint-Online-or-OneDrive.md)
* Service: **sharepoint-online**
* GitHub Login: @todmccoy
* Microsoft Alias: **v-todmc**

**Comment by msbemba** [comment]
@TausifJam Thank you for your feedback. I understand that there could be multiple causes for this feature greyed out. The resolution in both these cases is common where you will have to Deactivate limited-access user permission lockdown mode.

@nam31 There are no additional changes required in the document. 

Thanks
Sri

**Comment by nam31** [comment]
@TausifJam Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
