### ISSUE TITLE
OLicenseCleanup.vbs not working

### ISSUE THREAD

**Issue by brucesa85** [MicrosoftDocs/OfficeDocs-Support#398]
Hello team, we are in the process of changing tenants and was hoping to use this OLicenseCleanup.vbs script. It has worked till a couple months ago but now it does not seem to be resetting the activation anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1375a9d-fa30-75a2-5aea-daca0e74f142
* Version Independent ID: c9510807-f261-5a24-0039-d6bf5ad630e5
* Content: [Reset Office 365 ProPlus activation state - Office](https://docs.microsoft.com/en-us/office/troubleshoot/activation/reset-office-365-proplus-activation-state#feedback)
* Content Source: [Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md)
* Service: **o365-solutions**
* GitHub Login: @MJP-MSFT
* Microsoft Alias: **mattphil**

**Comment by MJP-MSFT** [comment]
What Windows versions are you running the script in?  Are clients using AAD?  We are working on a few updates for the script to include some more locations but I want to make sure you’re scenario is scoped first.

Can you share Windows versions, Office versions, and the authentication flow you’re using. AADJ, HAADJ, ADJ and so on?

Matt Philipenko
Sr. Premier Field Engineer – ProPlus Ranger
Microsoft Office <Deployment/Servicing/Activation/>
Direct:(813) 868-8108| E-Mail: mattphil@microsoft.com<mailto:mattphil@microsoft.com> | Office Hours: M-F, 7AM-4PM EST
Feedback Contact my Manager Palance Harris - palanceh@microsoft.com<mailto:palanceh@microsoft.com>
Want the inside scoop on Office Deployment? Videos<https://aka.ms/ODInsidersVideos> | UserVoice<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fodinsiders.uservoice.com%2F&data=02%7C01%7Cmattphil%40microsoft.com%7C5ff59ea895af49d1f4cb08d71fd2103b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637012859399918154&sdata=Z08QXEqnjt2t3JczrBKLGmVX4ktKVZzr2NHxJB8Id2U%3D&reserved=0> | TechCommunity<https://aka.ms/ODInsiderTechCommunity>

**Comment by ericspli** [comment]
The new tools should resolve the additional locations that cache credentials.

**Comment by nam31** [comment]
@brucesa85 this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by msbemba** [comment]
@brucesa85 Thank you for your feedback. I was able to test this and resets the Office activation state.

@nam31 There are no changes needed to the script or document.

Thanks
Sri

**Comment by msbemba** [comment]
@brucesa85 Thank you for your feedback. I was able to test this and resets the Office activation state. Let us know if you still have this issue or if any update is required in this document.

Thanks
Sri

**Comment by nam31** [comment]
@brucesa85 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
