### ISSUE TITLE
Remove the folder

### ISSUE THREAD

**Issue by techdivision-mark** [MicrosoftDocs/OfficeDocs-Support#399]
'Once added, remove the folder'.  From where?  Finder, or Spotlight?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a55b51-85d6-f628-581c-5a1c66675933
* Version Independent ID: 9f626f3a-123d-67ca-3aa8-a3443963fe05
* Content: [Outlook for Mac support tools. - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/outlook-for-mac/useful-tools#feedback)
* Content Source: [Outlook/OutlookExperts/outlook-for-mac/useful-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/OutlookExperts/outlook-for-mac/useful-tools.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. Please try to remove the "Main Profile" folder from the **Privacy** tab after you drag it to the **Privacy** tab.
