### ISSUE TITLE
Seperate sessions still crash and burn other open sessions during unstoppable file recovery reopen.

### ISSUE THREAD

**Issue by sekerob** [MicrosoftDocs/OfficeDocs-Support#400]
No Idea what HKCU means when staring at the RegEdit trunk, so went to search for the rest of the path which came up with HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Excel\Options

Then the instruction of creating the key. Hmmm. Anyway, closed all sessions. Opened several, STILL requiring to hold the Alt key to get to open in a separate session, and when crashing it still tries recovering in another open Excel session, resulting in crashing that too if the workbook got damaged during last save.

Big thumbs down a Humongous irritant in developing in Excel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 970cf317-aa45-6f08-5edc-f40825391dca
* Version Independent ID: bc3709a7-0210-c17b-b130-79aa14a956d8
* Content: [Force Excel to open in a new instance by default - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/force-excel-to-open-new-instance#feedback)
* Content Source: [Office/Client/excel/force-excel-to-open-new-instance.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/force-excel-to-open-new-instance.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by todmccoy** [comment]
We've updated the article to indicate that "HKCU" stands for "HKEY_CURRENT_USER". If you have any other issues, please contact Microsoft Support (http://support.microsoft.com/contactus).
