### ISSUE TITLE
Which Voicemail???

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/OfficeDocs-Support#401]
is the workaround some weird way of fixing the online voicemail routing, or is the intent to use the Voicemail of the mobile phone in your example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6b6fca-a76a-7d9e-47de-8cda874541f5
* Version Independent ID: 7d664094-5c39-25ab-006b-7035ea64fc6c
* Content: [Skype for Business Online users can't manage voice mail or customize greeting - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/online-phone-system/cannot-manage-voice-mail-or-greeting)
* Content Source: [SkypeforBusiness/SkypeOnline/online-phone-system/cannot-manage-voice-mail-or-greeting.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeOnline/online-phone-system/cannot-manage-voice-mail-or-greeting.md)
* Service: **skype-for-business-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by claudialake** [comment]
@korbyn72, the workaround for not having a license for Exchange Online (Plan 2 or higher) is to use the voicemail of the mobile phone, in this example.
