### ISSUE TITLE
Agreed, this didn't work for me.  Needs updating

### ISSUE THREAD

**Issue by RandomDave1** [MicrosoftDocs/OfficeDocs-Support#402]
Here's a page that actually did work for me through.  The power of Google compels you!

https://www.cloudfronts.com/room-list-not-showing-in-room-finder-outlook-client/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1e6278-ea7f-4eea-fbb1-f2de033ee400
* Version Independent ID: a90193e5-6ed9-8f29-d342-008e6cc904e9
* Content: [Room Finder doesn't display any conference rooms when a user creates a meeting - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/meetings/conference-rooms-not-dispalyed#feedback)
* Content Source: [Exchange/ExchangeOnline/meetings/conference-rooms-not-dispalyed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/meetings/conference-rooms-not-dispalyed.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by B3J** [comment]
I followed the link and have the room available on OWA but the list is empty in outlook (Office 365) ...
I lost 2 days on this it is annoying...

**Comment by B3J** [comment]
Update : works perfectly on Teams and OWA but not on outlook...

**Comment by marcussaunders** [comment]
I'm the same as above-  works everywhere except outlook

**Comment by nam31** [comment]
@RandomDave1, this article has been updated and moved to https://docs.microsoft.com/en-us/exchange/troubleshoot/calendars/conference-rooms-not-displayed
Please let us know if you are still facing the issue you raised initially.
Thanks

**Comment by nam31** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
