### ISSUE TITLE
"We are unable to connect right now" error can also caused by Windows NCSI settings

### ISSUE THREAD

**Issue by koolhand** [MicrosoftDocs/OfficeDocs-Support#403]
This same error can also be caused by Windows NCSI settings. Under some conditions, if only passive probing is allowed, it doesn't work correctly, and prevents Office from registering. Active probing is required for it to be reliable.

So in group policy, this will cause the error: _Administrative Templates &gt; System &gt; Internet Communication Management &gt; Turn off Windows Network Connectivity Status active tests_

Which is this in the registry:
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\NetworkConnectivityStatusIndicator]
"NoActiveProbe"=dword:00000001
```

Setting this parameter in Network Location Awareness service probably has the same effect:
```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet]
"EnableActiveProbing"=dword:00000000
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45650bf5-ff8a-4331-baf6-24438f21ffce
* Version Independent ID: 0d39f51c-4ff4-98ac-c77f-e3af486004f2
* Content: [We are unable to connect right now when try to activate Office 365 ProPlus - Office](https://docs.microsoft.com/en-us/office/troubleshoot/activation/issue-when-activate-office-365-proplus)
* Content Source: [Office/Client/activation/issue-when-activate-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/activation/issue-when-activate-office-365-proplus.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by misaka00251** [comment]
When I disable it still wont work after a reboot...

**Comment by msbemba** [comment]
@koolhand  Thank you for your feedback. Microsoft does not recommend disabling the NCSI probes. Several operating system components and applications rely on NCSI. For example, if NCSI does not function correctly, Microsoft Outlook may not be able to connect to a mail server, or Windows may not be able to download updates even if the computer is connected to the internet.

Hope this helps!

@nam31 There are no changes required in the document.

Thanks
Sri

**Comment by koolhand** [comment]
@msbemba Thanks, but for clarity: I'm not recommending that anyone disable NCSI probes. I'm recommending the opposite.

This article describes an error message, and is intended to explain the possible causes. But one of the standard causes of the error is not listed. So I'm just trying to point customers to both of the things ghat might cause the error.

If a customer has - _incorrectly_ - disabled the NCSI probes, they will see the error. Even if they have firewall correctly configured.

I have seen a team struggle with this error, because they focused on the firewall rule suggested in this article, which was already in place - when it was really caused by the Windows setting.

**Comment by msbemba** [comment]
@koolhand Thank you for the update. I have updated the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1486. Once the author reviews and approves the PR, the changes will be live.

CC: @simonxjx 

Thanks
Sri

**Comment by koolhand** [comment]
Thanks @msbemba.

Can I recommend that the cause explain both the registry keys, and the Group Policy that can disable the NCSI probes. They can be disabled by registry, or group policy. And in the scenario I saw, the policy was the cause.

I included in my my original issue description, but got the detail slightly wrong. There are two policies which disable NCSI probes. The precise setting is:

> _Administrative Templates &gt; System &gt; Internet Communication Management &gt; Internet Communication Settings &gt; Turn off Windows Network Connectivity Status active tests_

but there is also the broader umbrella setting, which disables _all_ of the Windows components that send data back to Microsoft servers by default, including NCSI probes:

> _Administrative Templates &gt; System &gt; Internet Communication Management &gt; Restrict Internet communication_

**Comment by msbemba** [comment]
@koolhand Thank you for the feedback. I have updated the PR with the following

To use Group Policy to Enable NCSI active probes, configure the following GPO:

- **Computer Configuration**\\**Administrative Templates**\\**System**\\**Internet Communication Management**\\**Internet Communication settings**\\**Turn off Windows Network Connectivity Status Indicator active tests**  
  - Value: Disabled

**Comment by nam31** [comment]
Closing via #1486 
Thank you
