### ISSUE TITLE
Opening the Corrupt File in WordPad Works Sometimes as Well

### ISSUE THREAD

**Issue by socrtwo** [MicrosoftDocs/OfficeDocs-Support#404]
Sometimes opening a corrupt Word file with WordPad will help you recover part of a corrupt Word DOCX file as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b95df2f-e3de-e2d1-b48a-3fcd4183463f
* Version Independent ID: 397150eb-b8e0-62c0-55b9-c5277aacb5dd
* Content: [How to troubleshoot damaged documents in Word - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/damaged-documents-in-word#feedback)
* Content Source: [Office/Client/word/damaged-documents-in-word.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/damaged-documents-in-word.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your suggestion.
