### ISSUE TITLE
Pound sign

### ISSUE THREAD

**Issue by O365scripts** [MicrosoftDocs/OfficeDocs-Support#405]
It is not possible to put a # sign in an email address when creating a user or a group from either the old or the new admin center. However, it is possible to create a distribution group (shared mailbox as well I presume) with an email address containing the # sign. When an alias with # in it is set as primary, the new admin center is unable to pull the distribution group's properties while the old is able to. It should not be possible to start with to be able to put a # in an alias, on either side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77f5b607-30cb-0c3c-d099-d41567e29773
* Version Independent ID: 55c37b8d-0cea-0b7e-4a31-da0968f1be87
* Content: [Error when you create a user name that contains a special character - Office](https://docs.microsoft.com/en-us/office/troubleshoot/error-messages/username-contains-special-character#feedback)
* Content Source: [Office/Client/error-messages/username-contains-special-character.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/error-messages/username-contains-special-character.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by todmccoy** [comment]
Article updated.
