### ISSUE TITLE
not working !

### ISSUE THREAD

**Issue by Macadoshis** [MicrosoftDocs/OfficeDocs-Support#409]
not working !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5f0ba42-c4ad-3179-91e2-fcddc957c319
* Version Independent ID: e4b3b41e-f71a-27da-7837-6d305e709f5c
* Content: [Office applications periodically prompt for credentials - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/office-prompt-for-credentials#feedback)
* Content Source: [Microsoft365/admin/access-management/office-prompt-for-credentials.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/access-management/office-prompt-for-credentials.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. If the issue persists, you can contact [Office Support](https://support.office.com/home/contact?contactUsExperienceEntryPointAssetId=S.HP.Main).
