### ISSUE TITLE
It's not under 'Policies' (Key is wrong)

### ISSUE THREAD

**Issue by thisisfutile** [MicrosoftDocs/OfficeDocs-Support#411]
You have two articles now, this one and "https://support.microsoft.com/en-us/help/832925/how-to-configure-the-size-limit-for-both-pst-and-ost-files-in-outlook".
BOTH are showing the wrong key.  They should remove 'Policies' from the key and then they would be correct.  Our business is using Outlook 2010 and our PST key is located in:
HKEY_CURRENT_USER\Software\Microsoft\Office14.0\Outlook\PST.  The 'Policies' entry has a Microsoft key but no Office key

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a50a221-2351-475b-4b9a-a386b6f5aafd
* Version Independent ID: 4dc840ed-e321-aaf1-bdc1-4030e0163d6a
* Content: [Outlook policy to control PST use and creation in Office 365 Import service - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/outlook-policy/control-pst-use#feedback)
* Content Source: [Exchange/ExchangeHybrid/outlook-policy/control-pst-use.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/outlook-policy/control-pst-use.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The article is updated with the latest information about registry keys.
