### ISSUE TITLE
I still have this issue

### ISSUE THREAD

**Issue by WeeBeasties** [MicrosoftDocs/OfficeDocs-Support#412]
I continue to have this issue with Outlook 16.36. I cannot figure out how to downgrade, and the suggested workaround does not solve the issue for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdfab92b-6018-8f71-8eb8-e31d3371dbd4
* Version Independent ID: 9e60f423-e7fa-8ce0-17c4-7cdd37bd6083
* Content: [Outlook 2016 for Mac repeatedly prompts for authentication - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/sign-in/repeated-prompts-authentication#feedback)
* Content Source: [Outlook/Mac/sign-in/repeated-prompts-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Mac/sign-in/repeated-prompts-authentication.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. Could you please try to install the update via https://docs.microsoft.com/en-us/officeupdates/update-history-office-for-mac?

**Comment by WeeBeasties** [comment]
I have installed the Outlook package update package (catchy name, there) to no avail. When restarting Outlook, it continues to complain about improper passwords – which I need to repeatedly enter to continue receiving email. The other suggested workaround with keychain also had no effect on this behavior.

Cheers,
Cliff
---
[A close up of a logo  Description automatically generated]
Dr. Clifton Franklund | Professor of Microbiology
General Education Assessment Coordinator |  Gen. Ed. website<https://www.ferris.edu/HTMLS/academics/general-education/index.htm>
Ferris State University | Department of Biological Sciences
820 Campus Drive | Big Rapids, MI 49307
CliftonFranklund@ferris.edu<mailto:%20cliftonfranklund@ferris.edu> | (231) 591-2552
Website<https://cliftonfranklund.com> |  LinkedIn<https://www.linkedin.com/in/cliftonfranklund/> |  Twitter<https://twitter.com/Dr_Franklund> |  Instagram<https://www.instagram.com/dr_franklund/>


Ferris State University - Small enough to know your dreams; big enough to make them happen
Learner - Input - Ideation - Intellection - Adaptability
