### ISSUE TITLE
Wrong cause and resolution

### ISSUE THREAD

**Issue by niderost** [MicrosoftDocs/OfficeDocs-Support#415]
This page states that the "Give Control" doesn’t work because of lack of hardware acceleration and that a resolution is to ensure the system supports hardware acceleration. In my specific situation, "Give Control" is also not working and the cause is not a lack of hardware acceleration. I know this because:
* chrome://gpu/ shows that hardware acceleration ís enabled in Chrome
* The Teams client logs don't show info messages "info -- [screenSharing][control] appSharingToolbar: AppSharingToolbar created with hardware acceleration: false". Instead, error messages are shown: "-- error -- [screenSharing][control] appSharingToolbar: "this" does not bind to AppSharingToolbar object in closeWindow" (however, it's not clear if these messages are related to the issue).
This page should inform readers that there might be other causes and would ideally link the users to additional information about those other causes / ways to debug those messages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20956786-4935-bca3-9c57-1f6bb9401da8
* Version Independent ID: 6be80e4f-36bc-6c5d-926c-003132fc4e31
* Content: [Give control doesn’t work when you share screen in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-conferencing/give-control-doesn%E2%80%99t-work-sharescreen)
* Content Source: [Teams/teams-conferencing/give-control-doesn%E2%80%99t-work-sharescreen.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-conferencing/give-control-doesn%E2%80%99t-work-sharescreen.md)
* Service: **msteams**
* GitHub Login: @TobyTu
* Microsoft Alias: **sarvdon**

**Comment by msbemba** [comment]
@niderost Thank you for your feedback. In general, the issue is caused because it does not have a GPU installed or if the hardware acceleration is disabled. We have not seen any other notable causes, Were you able to find out the cause and resolve the issue, If yes, Please do provide and we can add to the document after testing.

Thanks
Sri

**Comment by msbemba** [comment]
@niderost Just following up to see in case you would like to add more information to the document. 

Thanks
Sri

**Comment by niderost** [comment]
Hello Sri,
Thank you for your message and reminder. I haven't been able to find the root cause for the issue. I assume it was a bug in the software, as it disappeared after an update to a newer version of Teams. I didn't have any issues with this since then.
Regards, Beat

**Comment by nam31** [comment]
@niderost The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
