### ISSUE TITLE
Missing information on Teams client log location

### ISSUE THREAD

**Issue by niderost** [MicrosoftDocs/OfficeDocs-Support#416]
This page states "... you can see the following information in Teams client logs:". It is left to the reader to find out where those logs are located. It would be great if information on where the logs are located is added to the page. Or - at least - a link to relevant information is provided. I found the logs on my system in %appdata%\Microsoft\Teams\logs.txt. Background on using log files in troubleshooting Microsoft Teams is found here: https://docs.microsoft.com/en-us/microsoftteams/log-files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20956786-4935-bca3-9c57-1f6bb9401da8
* Version Independent ID: 6be80e4f-36bc-6c5d-926c-003132fc4e31
* Content: [Give control doesn’t work when you share screen in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-conferencing/give-control-doesn%E2%80%99t-work-sharescreen)
* Content Source: [Teams/teams-conferencing/give-control-doesn%E2%80%99t-work-sharescreen.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-conferencing/give-control-doesn%E2%80%99t-work-sharescreen.md)
* Service: **msteams**
* GitHub Login: @TobyTu
* Microsoft Alias: **sarvdon**

**Comment by unreinCoding** [comment]
Where are the logs on Linux? On the site (`https://docs.microsoft.com/en-us/microsoftteams/log-files`) is no description about it. What Graphics Feature Status do I need when I call chrome://gpu/ in Chromium?

**Comment by TobyTu** [comment]
Thanks for sharing, the article has been updated.
