### ISSUE TITLE
Some missing information, and some is simply wrong

### ISSUE THREAD

**Issue by buckleys78** [MicrosoftDocs/OfficeDocs-Support#419]
Incomplete:
When you press F9 or click Calc Sheet on the Calculation tab on the Tools/Options menu. Calculation also occurs every time that you save the file...  [ unless you turn this off by unchecking the "Recalculate workbook before saving" checkbox in the File/Options/Formulas menu. ]

Incorrect:
Summary: In Microsoft Excel, all currently open documents use the same mode of calculation, regardless of the mode in which they were saved. 

This is true only in Excel 2016, Office 365, and so.

In prior versions (Excel 2010, Excel 2007, and perhaps Excel 2013(?), this is only true if the documents are all opened in the same instance of Excel. If additional instances of Excel are launched (for example, by right-clicking on the Excel icon in the Task bar and clicking on the Excel icon with no file name), any workbooks within each new instance will have a Calculation mode independent of other instances.

This change was bitterly lamented and protested by users, as forcing all instances of Excel to the same mode caused much harm. Microsoft's reasoning was that they wanted Word and Excel to operate the same way so users wouldn't be confused. IMHO, dumb reasoning, but there it is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f225e12-9b7e-cd6e-34a6-9afccc2fa281
* Version Independent ID: 3a931302-8254-de43-4331-dc5e8a9384ad
* Content: [How Excel determines the current mode of calculation - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/current-mode-of-calculation#feedback)
* Content Source: [Office/Client/excel/current-mode-of-calculation.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/current-mode-of-calculation.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
I understand what you are saying, but don't know how we force that into this article. Possibly we could say this refers to a single instance of Excel.exe, but that could confuse others who would never do that. I also am not sure trying to get an exhaustive list of calc triggers makes this article any better. It isn't what the article is trying to articulate, so we will leave the article as it is for now.

**Comment by jlriesco** [comment]
We've updated the article to make it clearer.
