### ISSUE TITLE
Page needs to be updated with new product versions and an example

### ISSUE THREAD

**Issue by jasgreen-msft** [MicrosoftDocs/OfficeDocs-Support#421]
The article as written is for SharePoint 2013.  But this same guidance also applies to SharePoint 2016 and SharePoint 2019.  So they should be added.

Next this article needs to provide an actual example for enabling a 3rd party pdf ifilter.  The linked TechNet article does not actually contain an example although it is implied it does in this article.  This leads to customer confusion and subsequently a lot of erroneous blog articles being written on how to enable it.

Enabling 3rd party pdf iflters is done very simply via SharePoint PowerShell (once the ifilter has been installed on the search servers) as in the following example:

$ssa = Get-SPEnterpriseSearchServiceApplication -Identity "Search Service Application"
Set-SPEnterpriseSearchFileFormatState -SearchApplication $ssa -Identity PDF -Enable $true -UseIFilter $true

An example of how our customers are suggesting enabling it can be found in blogs like this example:
https://sharepoint2020.blogspot.com/2013/10/sharepoint-2013-installing-adobe.html

A method like this was used for SharePoint 2010, but it isn't needed for SharePoint 2013/2016/2019.  Updating our docs should help prevent customer confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 933ac227-798e-5e04-f93e-97532d6b02e2
* Version Independent ID: 24226e1b-7601-c57f-7cde-3e5ca153fa3f
* Content: [IFilter alternative to the native SharePoint 2013 PDF parser - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/lists-and-libraries/ifilter-alternative-to-the-native-pdf-parser#feedback)
* Content Source: [SharePoint/SharePointServer/lists-and-libraries/ifilter-alternative-to-the-native-pdf-parser.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointServer/lists-and-libraries/ifilter-alternative-to-the-native-pdf-parser.md)
* Service: **sharepoint-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by todmccoy** [comment]
Article updated.

**Comment by jasgreen-msft** [comment]
There is a line which should be removed in the updated article:

Installation example
Enabling third-party PDF iFilter tools can be done via SharePoint PowerShell once the iFilter has been installed on the search servers.
For example:
Copy
$ssa = Get-SPEnterpriseSearchServiceApplication -Identity "Search Service Application"
Set-SPEnterpriseSearchFileFormatState -SearchApplication $ssa -Identity PDF -Enable $true -UseIFilter $true
Another example on how to install a PDF iFilter can be found in the blogpost SharePoint 2013 - Installing Adobe iFilter and the 'real' PDF icon.
The highlighted line should be removed.

I would also change the title of the section from “Installation example” to something like “Enable support for installed pdf ifilter”.  Since the sample code provided really is showing you how to enable support in SharePoint for a 3rd party pdf ifilter which you installed.

Regards,
Jason Greene

**Comment by todmccoy** [comment]
Hi Jason –

The highlighting didn’t come through in the email. Can you try again?

Thanks,

Tod
