### ISSUE TITLE
problem with This page

### ISSUE THREAD

**Issue by MKelly63** [MicrosoftDocs/OfficeDocs-Support#423]
I have Excel 2016 MSO; the table only lists Excel MSI. Is this important?
build info is out of date:
"Excel 2016 (MSI) 	June 7, 2016 	Build 16.0.4393.1000"
I have build 16.0.12527.20260
Is there an updated page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 970cf317-aa45-6f08-5edc-f40825391dca
* Version Independent ID: bc3709a7-0210-c17b-b130-79aa14a956d8
* Content: [Force Excel to open in a new instance by default - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/force-excel-to-open-new-instance#feedback)
* Content Source: [Office/Client/excel/force-excel-to-open-new-instance.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/force-excel-to-open-new-instance.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
We've updated the article.
