### ISSUE TITLE
Cmdlet link seems wrong!

### ISSUE THREAD

**Issue by wormscoffer** [MicrosoftDocs/OfficeDocs-Support#425]
The link for more information on Set-MailboxAutoReplyConfiguration seems to go to a page about configuring in OWA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65d28096-bc2d-7c6f-f3cd-5c18e08a6c92
* Version Independent ID: 3f2cb43c-a0e7-2937-ae4c-7c19b08662ad
* Content: [How to set automatic replies on a user's mailbox in Office 365 - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/configure-mailboxes/set-automatic-replies#feedback)
* Content Source: [Exchange/ExchangeOnline/configure-mailboxes/set-automatic-replies.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/configure-mailboxes/set-automatic-replies.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The link is updated. Thanks for your comment.
