### ISSUE TITLE
Excel links still do not automatically update values after following this advice

### ISSUE THREAD

**Issue by TraderMikeS** [MicrosoftDocs/OfficeDocs-Support#426]
This advice does not work. MS Office 365. Links between two excel spreadsheets in the same folder created by the same excel application will not automatically update values. I have to manually update links or open the source spreadsheet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8675d7c-0870-b2c1-f442-867164e2949d
* Version Independent ID: 3cc6eaf5-37fa-b835-4d81-d3a83e9922bc
* Content: [Control the startup message about updating linked workbooks - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/control-startup-message#feedback)
* Content Source: [Office/Client/excel/control-startup-message.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/control-startup-message.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaryQiu1987** [comment]
Updated the article so close the issue
