### ISSUE TITLE
Newer tenants do not have the option to enable SfB Online

### ISSUE THREAD

**Issue by Pher0ah** [MicrosoftDocs/OfficeDocs-Support#427]
Hi, this page says QUOTE: "The domain should have at least one user licensed for Skype for Business or Teams. A global admin or company tenant has to assign a Skype for Business license to a user account that has either a Teams Admin role or a Global Admin role."

How do you assign a Skype for Business license to a user when the newer tenants come without a Skype for Business option

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c21105bc-e201-7743-2664-aaa067d8f97d
* Version Independent ID: 806f8a1b-9288-25a6-0965-e450a198ad84
* Content: [Microsoft Teams admin center error FAILED_TO_AUTO_DISCOVER_DOMAIN - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-administration/failed-to-auto-discover-domain-error-teams-admin-center#feedback)
* Content Source: [Teams/teams-administration/failed-to-auto-discover-domain-error-teams-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-administration/failed-to-auto-discover-domain-error-teams-admin-center.md)
* Product: **teams**
* GitHub Login: @todmccoy
* Microsoft Alias: **v-todmc**

**Comment by MaratMussabekov** [comment]
Hello @Pher0ah , please have a look at #1539 
Thank you

**Comment by nam31** [comment]
Closing via #1539 
Thank you
