### ISSUE TITLE
HR= not found

### ISSUE THREAD

**Issue by Gante82** [MicrosoftDocs/OfficeDocs-Support#428]
I tried looking for the text "HR=" in the source code of the error's page but it's nowhere to be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b636c2af-532f-0d70-be16-047a69c830b9
* Version Independent ID: 95022478-e764-1fd3-d0f3-77babec8e56c
* Content: [Sorry, but we're having trouble signing you in - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/sign-in/office-365-azure-intune-sign-in-issue#feedback)
* Content Source: [Microsoft365/admin/sign-in/office-365-azure-intune-sign-in-issue.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/sign-in/office-365-azure-intune-sign-in-issue.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. Can you also try to find 800 on the page?
