### ISSUE TITLE
Microsoft Teams is stuck in a login

### ISSUE THREAD

**Issue by e404r** [MicrosoftDocs/OfficeDocs-Support#429]
not working 
https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop
video: https://youtu.be/Qpfjal8qtM4

**Comment by e404r** [comment]
[https://youtu.be/Qpfjal8qtM4](url)

**Comment by RAJU2529** [comment]
@e404r . Try to contact to your college or university campus system administrator, he might solve it.
In meanwhile use recommended browser from  system admin

**Comment by e404r** [comment]
Sorry but I'm a system administrator. 
And we've already solved this problem!
They basically had such a problem Win  10  Home  And Win 7
