### ISSUE TITLE
Typo on the Add-MailboxPermission PowerShell

### ISSUE THREAD

**Issue by cregkly** [MicrosoftDocs/OfficeDocs-Support#433]
The line should not have a colon and it does not work as written:
Add-MailboxPermission -Identity johnsmith@contoso.onmicrosoft.com -User admin@contoso.onmicrosoft.com -AccessRights FullAccess -AutoMapping $false

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd6c33b6-24fb-447d-e9de-c5f11f0aaaae
* Version Independent ID: f5fd953d-bcbf-9315-8336-e43c20ef8022
* Content: [Remove automapping for a shared mailbox - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/domain-management/remove-automapping-for-shared-mailbox#feedback)
* Content Source: [Outlook/Client/domain-management/remove-automapping-for-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/domain-management/remove-automapping-for-shared-mailbox.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello @cregkly ,
**The line should not have a colon** - in powershell, parameter accepts value with or without colon the same way, it affects nothing.
**and it does not work as written** - worked as expected for me. Which error did you see in output?
Thank you

**Comment by MaratMussabekov** [comment]
Hello @cregkly ,
Did you have a chance to check it?
Thank you

**Comment by cregkly** [comment]
Looks like is is working with the colon. I suspect the delay in the change taking effect might be why I thought it was the incorrect syntax. Thanks for looking into this.

**Comment by nam31** [comment]
@cregkly Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
