### ISSUE TITLE
Priority and Weight Are Reversed

### ISSUE THREAD

**Issue by Avianographer** [MicrosoftDocs/OfficeDocs-Support#434]
In SRV records, the priority determines the order in which records will be processed, with lower numbers having higher priority than higher numbers. This is identical to how other DNS records work, such as MX records.

The weight determines which record should be processed if there are two records with identical priority, which is useful for primitive DNS load balancing. If any other record has the same priority, the highest-numbered record will always be preferred.

Your priority should be a low number, maybe "0" to be the lowest, and your weight should always be a high number. The range of values for these integers is 0-65535.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963f4e4e-860f-6b95-82a4-907e687403cd
* Version Independent ID: 25913310-1269-a95d-19c4-929f07571bdf
* Content: [Troubleshoot Skype for Business Online DNS configuration issues in Office 365 - Skype for Business](https://docs.microsoft.com/en-us/SkypeForBusiness/troubleshoot/online-configuration/dns-configuration-issue#feedback)
* Content Source: [SkypeforBusiness/SkypeOnline/online-configuration/dns-configuration-issue.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeOnline/online-configuration/dns-configuration-issue.md)
* Service: **skype-for-business-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by TobyTu** [comment]
@Avianographer thanks for your sharing, the article has been updated now.
