### ISSUE TITLE
Cant find the setting

### ISSUE THREAD

**Issue by damnSD** [MicrosoftDocs/OfficeDocs-Support#435]
I dont seem to finde the "Computer Configuration\Administrative Templates\Google\Google Chrome\Content Settings\Allow plugins on these sites" setting after importing the new policy tempkates???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62e22224-64c1-ea10-101b-c6ba96c9c1fd
* Version Independent ID: 4bc021f0-7050-4c66-16d9-0f11961e3284
* Content: [Client does not start when click a meeting link if default browser is Chrome - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/server-sign-in/client-not-start-click-meeting-link#feedback)
* Content Source: [SkypeforBusiness/SkypeServer/server-sign-in/client-not-start-click-meeting-link.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeServer/server-sign-in/client-not-start-click-meeting-link.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. To complete the steps, please make sure we have the following prerequisites and complete these steps on a Windows Server Domain Controller.

Prerequisites for Administering Domain-Based GPOs with ADMX Files
- A Windows Server 2008, Windows Server 2003, or Windows 2000 domain that uses a DNS name server.
- A Windows Vista–based computer to use as an administrative workstation.

**Comment by damnSD** [comment]
> Thanks for your comment. To complete the steps, please make sure we have the following prerequisites and complete these steps on a Windows Server Domain Controller.
> 
> Prerequisites for Administering Domain-Based GPOs with ADMX Files
> 
> * A Windows Server 2008, Windows Server 2003, or Windows 2000 domain that uses a DNS name server.
> * A Windows Vista–based computer to use as an administrative workstation.

I know how ADMX files work, but it don't help if the setting isn't there to use...

**Comment by vogash** [comment]
I agree with damnSD, plugin is not there

**Comment by vogash** [comment]
I can't find mentioned policy in google site
https://cloud.google.com/docs/chrome-enterprise/policies/

**Comment by hkystar35** [comment]
Also agreeing with @damnSD 
I have the ADMX templates from January 2020 which do not have this setting, nor does the latest release have it.
Google Chrome's policy site only has references to _Flash Player_ plugins, not app calls like Teams. Ultimately, trying to get rid of this pop-up in Chrome:
https://techcommunity.microsoft.com/t5/microsoft-teams/teams-join-online-button-opens-browser-in-stead-of-desktop/m-p/1169997#

**Comment by MaratMussabekov** [comment]
Hello everyone, 
please have a look at #1540.
thank you

**Comment by nam31** [comment]
Closing via #1540 
Thank you
