### ISSUE TITLE
I think Microsoft Learning's Azure Sandboxes broke because of this

### ISSUE THREAD

**Issue by Camios** [MicrosoftDocs/OfficeDocs-Support#437]
Problem with Chrome with v80 can't review permissions when trying to activate the sandbox. The fix is to clear browser cache. I suggest someone advises the team that looks after the Azure Sandboxes / learning content to either fix the problem and/or update the troubleshooting page with the tip to clear browser cache.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b6e323a-6fb2-c1a6-3afa-b88ed1ad419c
* Version Independent ID: ca05aa94-6799-3961-d83b-8fab9cf83be1
* Content: [Chrome SameSite cookie behavior effect on customer applications - Office 365](https://docs.microsoft.com/en-au/office365/troubleshoot/miscellaneous/chrome-behavior-affects-applications)
* Content Source: [Microsoft365/admin/miscellaneous/chrome-behavior-affects-applications.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/miscellaneous/chrome-behavior-affects-applications.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by joinimran** [comment]
Hi @Camios, thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by nam31** [comment]
@Camios we are going to close this issue as the article has been updated accordingly. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
