### ISSUE TITLE
Worked for me

### ISSUE THREAD

**Issue by kartarsingh** [MicrosoftDocs/OfficeDocs-Support#438]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8e36de2-8956-ed6f-61b7-2d2ba7b2e7b0
* Version Independent ID: 1e05c7a3-20df-ad99-9fb4-8d3b509f521a
* Content: [Outlook continually prompts for password when you try to connect to Office 365 - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/sign-in/continually-prompts-password-office-365)
* Content Source: [Outlook/Client/sign-in/continually-prompts-password-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/sign-in/continually-prompts-password-office-365.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment.
