### ISSUE TITLE
PowerPoint output resolution

### ISSUE THREAD

**Issue by GerardTromp** [MicrosoftDocs/OfficeDocs-Support#44]
Has anybody thought about the obvious manner of changing resolution such as a simple menu interface that allows one to type in / select the output resolution? 

Mucking about in the registry to change the resolution in a half dozen places and then again resetting it, is both arcane and tedious.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e390c4c9-9cdf-beb1-43dc-6ec45ae5fe77
* Version Independent ID: bb31c9ea-7186-22fb-195f-f481eb5137e4
* Content: [How to change the export resolution of a PowerPoint slide - Office](https://docs.microsoft.com/en-us/office/troubleshoot/powerpoint/change-export-slide-resolution)
* Content Source: [Office/Client/powerpoint/change-export-slide-resolution.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/powerpoint/change-export-slide-resolution.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Please file a feature request through UserVoice, which is where engineering looks at feedback around feature requests.

Here's the link: [https://powerpoint.uservoice.com/](https://powerpoint.uservoice.com/)
