### ISSUE TITLE
List of Product IDs which are supported by the Office Deployment Tool for Click-to-Run

### ISSUE THREAD

**Issue by HeatherAllemang** [MicrosoftDocs/OfficeDocs-Support#441]
It would be most helpful to us folks in support if you added the Product ID's for Visio and Project 2016.  It seems that when 2019 came to many of our docs the info for 2016 disappeared and we still need it.  thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 358c3fd4-27aa-fc10-e23e-43b3f801b739
* Version Independent ID: 3d322857-f041-5b22-d91b-458427e45fb1
* Content: [Product IDs that are supported by the Office Deployment Tool for Click-to-Run - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/installation/product-ids-supported-office-deployment-click-to-run#feedback)
* Content Source: [Microsoft365/admin/installation/product-ids-supported-office-deployment-click-to-run.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/installation/product-ids-supported-office-deployment-click-to-run.md)
* Service: **o365-solutions**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-todmc**

**Comment by msbemba** [comment]
@HeatherAllemang Thank you for your feedback. I was able to get the Product ids for Visio and Project 2016. they are called VisioStdRetail and ProjectStdRetail etc.

This was always available in the document, I think the 2019 product IDs might have created a bit of confusion.

Hope this helps!

@nam31 There are no changes in the document and the issue can be closed.

Thanks
Sri

**Comment by nam31** [comment]
@HeatherAllemang Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
