### ISSUE TITLE
User self update of contact info documentation does not work nor does it match what users see on screen

### ISSUE THREAD

**Issue by mariajavier1** [MicrosoftDocs/OfficeDocs-Support#442]
What old version of Outlook is "How to update contact information" referencing? The steps are not matching what our users see in O365 outlook web. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b9d03b7-62fa-21cf-6bad-7474e643ce27
* Version Independent ID: 837d0aec-c3dc-df94-643c-31bffbd72a01
* Content: [How to update contact information in Exchange Online in Office 365 - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/configure-contacts/update-contact-information#feedback)
* Content Source: [Exchange/ExchangeOnline/configure-contacts/update-contact-information.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/configure-contacts/update-contact-information.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello @mariajavier1,
please have a look at #1541
Thank you

**Comment by nam31** [comment]
Closing via #1541
Thank you
