### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MattFromPhilly** [MicrosoftDocs/OfficeDocs-Support#443]
Is there some reason why hyperlinks set up in Word have to ALWAYS use the Microsoft Hyperlink Library and the URLMON API?? Could there be an option in Word in the hyperlink dialog when you set up with something like "Simple URL Link" or whatever? One that simply passes the URL to the default browser and that's it? It's kind of a lot to ask that organizations completely re-work their company-wide SSO system just so links in Word will work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb4e2409-fde8-8b1b-4dca-01bb6759b006
* Version Independent ID: fd463b22-33c1-a726-6a63-62ee892c5df3
* Content: [Issues when you click a hyperlink to SSO Web site - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office/click-hyperlink-to-sso-website#feedback)
* Content Source: [Office/Client/office/click-hyperlink-to-sso-website.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office/click-hyperlink-to-sso-website.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@MattFromPhilly Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
