### ISSUE TITLE
I have this problem.

### ISSUE THREAD

**Issue by JungWonYong** [MicrosoftDocs/OfficeDocs-Support#444]
My outlook prompt password dialog every 5 seconds. (I'm WIndows 10 on VDI. Symptom 4 may be.)
I decided to use thunderbird with DavMail and I happy now. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb91ee9-4509-b01f-6260-18114bc44f52
* Version Independent ID: 67fbeacf-d523-df48-fbd8-e35135960727
* Content: [Connection issues in sign-in after update to Office 2016 build 16.0.7967 - Office 365](https://docs.microsoft.com/en-my/office365/troubleshoot/authentication/connection-issue-when-sign-in-office-2016#feedback)
* Content Source: [Microsoft365/admin/authentication/connection-issue-when-sign-in-office-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/authentication/connection-issue-when-sign-in-office-2016.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. Here is another article you can reference. https://docs.microsoft.com/outlook/troubleshoot/sign-in/continually-prompts-password-office-365
