### ISSUE TITLE
Neat scavenger hunt, but didn't work for me

### ISSUE THREAD

**Issue by blackft** [MicrosoftDocs/OfficeDocs-Support#445]
I chased the registry entries as described but when I arrived at the last entry in the chain in step 9, there was no Binary: 00036619 and so while I was tempted to edit the one that was closest, I've been burned before by taking guesses within the registry.  Either the directions fit exactly or don't and these don't.  Maybe 003661c is the droid I was looking for with a data value of 22 00 00 00 or maybe it wasn't but I'll never know because I'm not messing with it.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8e36de2-8956-ed6f-61b7-2d2ba7b2e7b0
* Version Independent ID: 1e05c7a3-20df-ad99-9fb4-8d3b509f521a
* Content: [Outlook continually prompts for password when you try to connect to Office 365 - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/sign-in/continually-prompts-password-office-365#feedback)
* Content Source: [Outlook/Client/sign-in/continually-prompts-password-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/sign-in/continually-prompts-password-office-365.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@blackft Thank you for your feedback. This document pertains to outlook 2007, 2010, and 2013 where you have the Logon network security option under security.  I'm able to find this option using outlook 2010. Another thing to note is that all builds of outlook 2016 and later are not affected by this issue. If you are using a newer version and face this problem, we highly recommend that you use SATA diagnostic to troubleshoot repeated credential prompts.

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@blackft Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
