### ISSUE TITLE
Map a Network Drive cookie doesnt stay after sign-out Server 2012 R2

### ISSUE THREAD

**Issue by ryanturcotte** [MicrosoftDocs/OfficeDocs-Support#446]
Any suggestions for when trying this and you can get it to work once, but after sign-out of user account and log back-in it does not work until you manually go to the Sharepoint page you are trying to connect to? Do we know where the cookie is being stored that enables this auto login?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8928ed26-fda0-0e68-a4e1-cc287a5e5699
* Version Independent ID: c6ff303c-a5b4-4890-6d00-82246b92ea45
* Content: [Troubleshoot mapped network drives that connect to SharePoint Online - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/troubleshoot-mapped-network-drives#feedback)
* Content Source: [SharePoint/SharePointOnline/administration/troubleshoot-mapped-network-drives.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/administration/troubleshoot-mapped-network-drives.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. By default, all SharePoint Online cookies are session cookies. These cookies are not saved to the browser's cookie cache and instead are deleted whenever the browser is closed. You can see https://docs.microsoft.com/en-us/sharepoint/authentication for details.

**Comment by nam31** [comment]
@ryanturcotte It seems that the question has been answered.
Are you still facing this issue ?

**Comment by nam31** [comment]
@ryanturcotte We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
