### ISSUE TITLE
This is old firmware for the VVXs

### ISSUE THREAD

**Issue by sdleslie** [MicrosoftDocs/OfficeDocs-Support#447]
Current firmware from PolyCom is now at 6.2, 5.5 is very old.  Yet this article is date Mar 17 2020.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92da332f-edb9-e81c-dd55-da248110c5c3
* Version Independent ID: 5d1a3ecb-1f3a-75b9-1a8b-0fe7689ca83d
* Content: [New features in the firmware update for Polycom VVX IP phones - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/server-phone-system/new-features-in-firmware-update#feedback)
* Content Source: [SkypeforBusiness/SkypeServer/server-phone-system/new-features-in-firmware-update.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeServer/server-phone-system/new-features-in-firmware-update.md)
* Service: **skype-for-business-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by rufioIK708** [comment]
It currently lists no version number.  Although this page: https://docs.microsoft.com/en-us/skypeforbusiness/certification/devices-ip-phones, appears to be the current list, the latest update for the phones is from 01/22/2019.  Also, the Polycomm site mentions "Customers in Skype for Business deployments should only use software releases that have been qualified by Microsoft or the maintenance releases built on a qualified release." This sentiment is not mirrored in any Microsoft documentation that I can find.  And what is a maintenance release is it 5.9.X or 5.9.0.XXXX.  Does this count for phones used in Teams deployments?  These inconsistencies make it very difficult to support customers with theses phones.

**Comment by dariomws** [comment]
Hi @sdleslie and @rufioIK708, thank you for your feedback.

As you clearly noticed, there are no version numbers anymore in this article except for a minimum to auto-update it. Also, this article applies to Skype for Business Online and it's being retired.
Please check the following articles for devices supported with Teams:
https://docs.microsoft.com/microsoftteams/devices/teams-ip-phones
