### ISSUE TITLE
Running `npm start` works with cmd not bash from VS Code Terminal

### ISSUE THREAD

**Issue by mbalex99** [MicrosoftDocs/OfficeDocs-Support#448]
I am using the yeoman generator to create a react and typescript project on windows 10 machine using VSCode

![image](https://user-images.githubusercontent.com/2183729/79043559-a32a2780-7bb4-11ea-8514-75e4318b0aac.png)

1. If I run `npm start` from bash, the taskpane will fail to load
2. If I switch to cmd, it will properly start

Not sure why it's causing the discrepancy...

**Comment by nam31** [comment]
@mbalex99 The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@mbalex99 We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
