### ISSUE TITLE
Poorly written article

### ISSUE THREAD

**Issue by vreddy-m** [MicrosoftDocs/OfficeDocs-Support#449]
Must have been written by an intern. Most of the REG paths in the article are invalid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70dfdda1-e80e-5707-3ecb-38b689633075
* Version Independent ID: 4e53296e-25e1-7120-a563-6a008abb42fc
* Content: [No Add-ins loaded due to group policy settings - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/group-policy/office-add-in-not-loaded#feedback)
* Content Source: [Microsoft365/admin/group-policy/office-add-in-not-loaded.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/group-policy/office-add-in-not-loaded.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@vreddy-m this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@vreddy-m We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
