### ISSUE TITLE
General availability of O365 CDN link broken

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/OfficeDocs-Support#451]
The link points to https://dev.office.com/blogs/general-availability-of-office-365-cdn but is invalid.
The correct link seems to be https://developer.microsoft.com/en-us/office/blogs/general-availability-of-office-365-cdn/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bef914e3-cdd6-c422-98b6-9a9513863b5e
* Version Independent ID: 63e1f699-f8f0-d278-d7a8-7576684787c7
* Content: [Non-CDN-enabled SharePoint Picture Library Slideshow web part no longer switches automatically to new images - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/web-parts/non-cdn-enabled-picture-library-slideshow-web-part-no-longer-switches-automatically-to-new-images#feedback)
* Content Source: [SharePoint/SharePointOnline/web-parts/non-cdn-enabled-picture-library-slideshow-web-part-no-longer-switches-automatically-to-new-images.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/web-parts/non-cdn-enabled-picture-library-slideshow-web-part-no-longer-switches-automatically-to-new-images.md)
* Service: **sharepoint-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. As the platform is updated, the link is updated in the article.
