### ISSUE TITLE
Would be great to mention the -ClearAutoMapping parameter too

### ISSUE THREAD

**Issue by jettan92** [MicrosoftDocs/OfficeDocs-Support#452]
I recently discovered that the Remove-MailboxPermission command has this new parameter called -ClearAutoMapping. It would be great if this article could mention that as well.

Thank you and best regards!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd6c33b6-24fb-447d-e9de-c5f11f0aaaae
* Version Independent ID: f5fd953d-bcbf-9315-8336-e43c20ef8022
* Content: [Remove automapping for a shared mailbox - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/domain-management/remove-automapping-for-shared-mailbox#feedback)
* Content Source: [Outlook/Client/domain-management/remove-automapping-for-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/domain-management/remove-automapping-for-shared-mailbox.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by marconipoveda** [comment]
Hi @jettan92.

Very interesting option. 

I'd like to add that aparently `ClearAutoMapping` can only be used to remove permission to all users, not a specific ones.

`C:\Users\MarconiPoveda> Remove-MailboxPermission -Identity jreyes@example.com -ClearAutoMapping

Confirm
Are you sure you want to perform this action?
Clear automatic mapping delegation entries for mailbox "jreyes@example.com". Users granted FullAccess permission to this mailbox will no longer have the mailbox mapped
automatically.
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [?] Help (default is "Y"):
C:\Users\MarconiPoveda> Remove-MailboxPermission -Identity jreyes@example.com -ClearAutoMapping -User mpoveda@example.com
Parameter set cannot be resolved using the specified named parameters.
    + CategoryInfo          : InvalidArgument: (:) [Remove-MailboxPermission], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Remove-MailboxPermission
    + PSComputerName        : outlook.office365.com`

Regards.

**Comment by jettan92** [comment]
@marconipoveda Thanks for chipping in! I can see that this option is useful for customers who are not comfortable with removing permissions for a mailbox, then adding them back.

With this option, the permissions stay in place, just that the mailbox does not get auto-mapped, which is less of a disruption.

**Comment by sowjanya365** [comment]
Hi @jettan92 

Thank you for your feedback. -ClearAutoMapping parameter can only be used to remove permission for all the users, not for an individual ones.

Hope this clarifies your query. For more details, please read this article. 

https://docs.microsoft.com/powershell/module/exchange/remove-mailboxpermission?view=exchange-ps

Thank you!

**Comment by nam31** [comment]
@jettan92 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
