### ISSUE TITLE
Wrong endpoints

### ISSUE THREAD

**Issue by gallama1** [MicrosoftDocs/OfficeDocs-Support#453]
The list of the endpoints is not perfectly accurate.
Same mistakes of another URL https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/best-practices-securing-ad-fs

1) end slash =&gt; /adfs/services/trust/2005/windowstransport/
2) Space  =&gt; adfs/services/trust/13/ issuedtokenmixedasymmetricbasic256
3) Space =&gt; /adfs/services/trust/13/ issuedtokenmixedsymmetricbasic256
4) Typo =&gt; /adfs/services/trsuttcp/windows

here is the list of the correct list:
EndpointPath,Enabled,Proxy
/adfs/ls/,TRUE,TRUE
/adfs/services/trust/2005/windowstransport,TRUE,FALSE
/adfs/services/trust/2005/certificatemixed,TRUE,TRUE
/adfs/services/trust/2005/certificatetransport,TRUE,TRUE
/adfs/services/trust/2005/usernamemixed,TRUE,TRUE
/adfs/services/trust/2005/kerberosmixed,TRUE,FALSE
/adfs/services/trust/2005/issuedtokenmixedasymmetricbasic256,TRUE,TRUE
/adfs/services/trust/2005/issuedtokenmixedsymmetricbasic256,TRUE,TRUE
/adfs/services/trust/13/kerberosmixed,TRUE,FALSE
/adfs/services/trust/13/certificatemixed,TRUE,TRUE
/adfs/services/trust/13/usernamemixed,TRUE,TRUE
/adfs/services/trust/13/issuedtokenmixedasymmetricbasic256,TRUE,TRUE
/adfs/services/trust/13/issuedtokenmixedsymmetricbasic256,TRUE,TRUE
/adfs/services/trusttcp/windows,TRUE,FALSE
/adfs/services/trust/mex,TRUE,TRUE
/FederationMetadata/2007-06/FederationMetadata.xml,TRUE,TRUE
/adfs/ls/federationserverservice.asmx,TRUE,FALSE

it is not clear to me why the path /adfs/services/trust/mex has been included in the list. ADFS 2012 R2 and above doen not let you disable it \ manipulate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91594f16-0dfd-7f42-29c6-3211805aef61
* Version Independent ID: 8cbdbc8b-4497-59ad-36dd-d8b1358ec8c0
* Content: [Sign in to Office 365, Azure, or Intune fails after you change the federation service endpoint - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/active-directory/sign-in-fails-if-federation-endpoint-changes#feedback)
* Content Source: [Microsoft365/admin/active-directory/sign-in-fails-if-federation-endpoint-changes.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/active-directory/sign-in-fails-if-federation-endpoint-changes.md)
* Product: **office 365**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by nam31** [comment]
@gallama1 this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@gallama1 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
