### ISSUE TITLE
Method 8?  (and BTW none of these worked for me...)

### ISSUE THREAD

**Issue by BCB57** [MicrosoftDocs/OfficeDocs-Support#458]
This is wrong:
"Method 8: Change the default printer
To change the default printer, follow these steps:
Exit all Office programs.
Type regedit in the Search box (in Windows 10, Windows 8.1, or Windows 8) or in the Start Search box on the Start menu (in earlier versions of Windows), and then press Enter.
Right-click Microsoft XPS Document Writer, and then click Set as default printer."

I see the issue was already pointed out by  JulietteLaurier last December ... anyone reading this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be46645d-dbd2-f1f8-089d-de61c678807f
* Version Independent ID: 5945f781-2560-84f0-494e-2473b9537939
* Content: [How to troubleshoot problems that occur when you start or use Word - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/issues-when-start-or-use-word#feedback)
* Content Source: [Office/Client/word/issues-when-start-or-use-word.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/issues-when-start-or-use-word.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@BCB57 this article has been updated. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@BCB57 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
