### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by isumit19** [MicrosoftDocs/OfficeDocs-Support#460]
I don't know who the admin is? Can you please clarify it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b670b40-1e7b-7491-d4d6-d2d1368539a8
* Version Independent ID: 345d7ba0-6bdc-4fb8-6a91-6dcd0ac96630
* Content: [A user or an administrator forgot their password - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/sign-in/forgot-sign-in-password#feedback)
* Content Source: [Microsoft365/admin/sign-in/forgot-sign-in-password.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/sign-in/forgot-sign-in-password.md)
* Service: **o365-administration**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. In this case, you can [contact support](https://support.office.com/en-us/home/contact?contactUsExperienceEntryPointAssetId=S.HP.Main) for help.

**Comment by sowjanya365** [comment]
Hi @isumit19 

In this article admin refers to user administrator, or password administrator. 

For more details please read this article. 

https://docs.microsoft.com/azure/active-directory/fundamentals/active-directory-users-reset-password-azure-portal

Hope this clarifies your query. Thank you!

**Comment by nam31** [comment]
@isumit19 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
