### ISSUE TITLE
Voicemail delivered to junk mail

### ISSUE THREAD

**Issue by smudgecat** [MicrosoftDocs/OfficeDocs-Support#462]
Another reason that your voicemail does not arrive as you would expect it is that Microsoft have not configured SPF correctly. Voicemails go to junk in my email. Within teams, it says "No voicemails yet, but when you get some, you’ll get transcripts, too".
The SPF record spf.protection.outlook.com should include the IP/range of the server sending the emails. This was EUR03B.map.protection.outlook.com 52.114.76.82 yesterday. 
There is a uservoice that raises the bug, however I've reluctant to put the workaround in place as Microsoft may change the IP without notice.
https://microsoftteams.uservoice.com/forums/908686-bug-reports/suggestions/38791981-microsoft-teams-sends-voice-email-messages-which-f

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef6fd529-a369-9afd-ce21-4cb8b415f6c4
* Version Independent ID: 9e7c3225-ddba-1af5-c2f0-ab3da394f02f
* Content: [Voicemail messages are not delivered in Teams or Skype for Business client - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/hybrid-phone-system/voicemails-not-delivered#feedback)
* Content Source: [SkypeforBusiness/SkypeHybrid/hybrid-phone-system/voicemails-not-delivered.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeHybrid/hybrid-phone-system/voicemails-not-delivered.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@smudgecat Are you still seeing this issue? I don't have an easy way to test this, but my research leads me to believe it was fixed.

**Comment by smudgecat** [comment]
@VLG17 Thank you for the reply. Yes, I've tested and received my first Teams voicemail! Will update the Uservoice as that is still open.
