### ISSUE TITLE
Method 5 helps

### ISSUE THREAD

**Issue by nortagem-de** [MicrosoftDocs/OfficeDocs-Support#463]
Add-in from Foxit-Reader created problems for me. I disabled it and problem was soolved. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62a88c46-43bb-92cf-c409-c8b3071b3865
* Version Independent ID: 19f5e98e-36a5-e2e9-39b1-5fc5ae349b50
* Content: [Troubleshoot Excel opening blank when double-click a file icon or file name - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/excel-opens-blank#feedback)
* Content Source: [Office/Client/excel/excel-opens-blank.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/excel-opens-blank.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment.
