### ISSUE TITLE
Use double quotes instead of single quotes for $OutFileName = 'AuditLogResults$Date.csv'

### ISSUE THREAD

**Issue by sysadmin-scs** [MicrosoftDocs/OfficeDocs-Support#464]
Using single quotes results in a file called AuditLogResults$Date.csv
If double quotes are used, the file is appended with the day's date which is the intended behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a93c78d-ed18-2fda-d8bb-9f60f64fbc0f
* Version Independent ID: a79b1742-f841-c8a5-71f6-1c1dda533d6a
* Content: [How to use mailbox audit logs in Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/audit-logs/mailbox-audit-logs)
* Content Source: [Microsoft365/Compliance/audit-logs/mailbox-audit-logs.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/Compliance/audit-logs/mailbox-audit-logs.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by sysadmin-scs** [comment]
I think there are other issues with the script. See these items I received in PowerShell while processing:

Searching Mailbox Audit Logs...
$($SearchREsults.Count) Total entries Found
Removing FolderBind operations.
Filtered to $($SearchREsults.Count) Entries

Posting results to file: $OutfileName

**Comment by mesum9** [comment]
Just change below lines with "double quotes" and it will be perfect.
$OutFileName = "AuditLogResults$Date.csv"
write-host -fore green "Posting results to file: $OutfileName"
write-host -fore green "$($SearchREsults.Count) Total entries Found"

**Comment by nam31** [comment]
@sysadmin-scs this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@sysadmin-scs We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
