### ISSUE TITLE
Not resolved

### ISSUE THREAD

**Issue by rgsbouma** [MicrosoftDocs/OfficeDocs-Support#466]
I have found the ShownFirstRunOptin in my Registry with the value 1, nevertheless opening a document from OneDrive or SharePoint makes every Office App crash (PP, Word, Excel etc).

I am running Windows 10 build 19041.207 and having the problem since build 173).
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3e1325-8447-d157-729e-f668bef41db0
* Version Independent ID: f411b63a-8be9-9ac4-3f1c-8746216d243d
* Content: [Office Applications crash or cannot start - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/office-crash-or-cannot-start#feedback)
* Content Source: [Microsoft365/enterprise/administration/office-crash-or-cannot-start.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/enterprise/administration/office-crash-or-cannot-start.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@rgsbouma . You are using windows 10 insider preview 19041, and is not officially released as a stable version to the public , so we cant give a guarantee existing OfficeSuite will in the insider preview version .  i am using windows 10 18363.815 and office is  working with registry key

**Comment by sowjanya365** [comment]
Hi @rgsbouma 

Could you please confirm if you are still facing this issue. I tried, and it's working for me. 

Thank you!

**Comment by sowjanya365** [comment]
Hi @rgsbouma 

Please let us know if you still have any questions regarding the issue you have raised initially.

Thanks.

**Comment by nam31** [comment]
@rgsbouma We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
