### ISSUE TITLE
Solution roadmap

### ISSUE THREAD

**Issue by Janus-Unit-IT** [MicrosoftDocs/OfficeDocs-Support#467]
Is this an issue, that has a solution in the pipeline?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ac0b77-ce59-4464-abbb-987b6ace1000
* Version Independent ID: 4e50e53f-04ee-a522-b47a-2b50556bb81b
* Content: [“Something went wrong and your search couldn’t be completed” error message when searching from an additional mailbox in Outlook - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/search/can%27t-search-additional-mailbox#feedback)
* Content Source: [Outlook/Client/search/can't-search-additional-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/search/can't-search-additional-mailbox.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @TobyTu
* Microsoft Alias: **aruiz**

**Comment by TobyTu** [comment]
This is a known limitation, we'll post more information when it becomes available.

**Comment by andrewclark55** [comment]
Starting yesterday (12 May 2020) I am getting this exact issue and I only have ONE Exchange account.

**Comment by TobyTu** [comment]
@andrewclark55 does the workaround works for you? If you still need help to fix this issue, you may go to [Microsoft Community](https://answers.microsoft.com/) or submit a service request

**Comment by andrewclark55** [comment]
>@andrewclark55<https://github.com/andrewclark55> does the workaround work for you?

The workaround to search Main computer seems to work for now.  I have not tried the suggested registry edits to disable searches, as I prefer not to do that.

Does this issue need to be reported separately to Microsoft?  It is clearly a bug that needs fixing.

Regards
Andrew
