### ISSUE TITLE
This does not work

### ISSUE THREAD

**Issue by cnherrick** [MicrosoftDocs/OfficeDocs-Support#469]
2020/04 :: The regedit does not present the check box.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c55d1be5-45a5-00fb-9116-e92b0be83db0
* Version Independent ID: 99af8069-ecf4-3b11-05da-2869e1922208
* Content: [How to disable Automatic Gain Control in Skype for Business on Windows - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/server-configuration/disable-automatic-gain-control#feedback)
* Content Source: [SkypeforBusiness/SkypeServer/server-configuration/disable-automatic-gain-control.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeServer/server-configuration/disable-automatic-gain-control.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by PedroKirwan** [comment]
has also failed to work for me

**Comment by nam31** [comment]
@cnherrick this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@cnherrick We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
