### ISSUE TITLE
Change the deadline

### ISSUE THREAD

**Issue by kintz** [MicrosoftDocs/OfficeDocs-Support#47]
Since the published deadline is 2 years in the past, this creates the false impression that the information is now irrelevant.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e7a3118-66aa-6e42-43fa-e7af0abb087a
* Version Independent ID: 6c48ff6f-c50f-4a02-faf0-0278e71bcc3d
* Content: [Important notice for Office 365 email customers who have configured connectors - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/connectors/office-365-notice#feedback)
* Content Source: [Exchange/ExchangeOnline/connectors/office-365-notice.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/connectors/office-365-notice.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by irufus** [comment]
No follow-up to this? Need to know since we have a sendmail --> O365 connection.

**Comment by nam31** [comment]
@kintz We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
