### ISSUE TITLE
Less useful for dynamically created sheets

### ISSUE THREAD

**Issue by Dawood-ibn-Kareem** [MicrosoftDocs/OfficeDocs-Support#470]
I need to capture change events on a worksheet that was inserted by VBA code.  This page doesn't describe how to do that.  

This page would be far more useful if it also mentioned the Workbook.SheetChange event, or alternatively some other mechanism for capturing change events on dynamically inserted worksheets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8cfc787-adcf-0d91-3562-a613ef0b2496
* Version Independent ID: e7e093bf-f79e-21fe-1309-a2dfbad9f120
* Content: [Run a macro when certain cells change in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/run-macro-cells-change#feedback)
* Content Source: [Office/Client/excel/run-macro-cells-change.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/run-macro-cells-change.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by joinimran** [comment]
Hi @Dawood-ibn-Kareem, thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by joinimran** [comment]
Hi @Dawood-ibn-Kareem, Following is how to capture change events. For example, if you have a named range called “DataRange” and you want to show a prompt in case the user makes a change in this named range, you can use the code below:

Private Sub Worksheet_Change(ByVal Target As Range)
Dim DRange As Range
Set DRange = Range("DataRange")
If Not Intersect(Target, DRange) Is Nothing Then
MsgBox "You just made a change to the Data Range"
End If
End Sub

**Comment by nam31** [comment]
@Dawood-ibn-Kareem Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
