### ISSUE TITLE
Had to change -Authentication from Basic to Default

### ISSUE THREAD

**Issue by dialedin2014** [MicrosoftDocs/OfficeDocs-Support#471]
This got it working on a brand new tenant.  Maybe basic authentication isn't supported by default anymore?

Another problem can be if the user has a pending password change requirement.

**Comment by nam31** [comment]
@dialedin2014 The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@dialedin2014 We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
