### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by HenrikBernhard** [MicrosoftDocs/OfficeDocs-Support#474]
doesn't seem like "explaiwhat" is a real word :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a45df92-9913-0633-a06b-e996602e1708
* Version Independent ID: ddb7596e-7d36-36aa-8283-1b061f798891
* Content: [What the UserAgent property value refers to in the unified audit log - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/audit-logs/useragent-property#feedback)
* Content Source: [Microsoft365/Compliance/audit-logs/useragent-property.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/Compliance/audit-logs/useragent-property.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The article is updated.
