### ISSUE TITLE
Error: How to determine whether a year is a leap year

### ISSUE THREAD

**Issue by sangramnavale** [MicrosoftDocs/OfficeDocs-Support#475]
On Step 2, it is written : 
If the year is evenly divisible by 100, go to step 3. Otherwise, go to step 4. 
It should be step 5 and not step 4 . Kindly correct it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6f92333-a9f0-7616-64e8-5aaceb1e3f40
* Version Independent ID: c8136395-44ec-6eb6-3153-53527baf19b3
* Content: [Method to determine whether a year is a leap year - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/determine-a-leap-year#feedback)
* Content Source: [Office/Client/excel/determine-a-leap-year.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/determine-a-leap-year.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The article is updated.

**Comment by Vukain** [comment]
The change wa incorrect and now the script is invalid. It should just to step 4.
