### ISSUE TITLE
Please post an updated Message Centre post reflecting the delay due to COVID19

### ISSUE THREAD

**Issue by ma261065** [MicrosoftDocs/OfficeDocs-Support#476]
Please post an updated Message Centre post reflecting the delay due to COVID19

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02c6141e-02b7-7ee1-5b00-5ff9cf5b3fe4
* Version Independent ID: 6fd90401-551d-ee7a-cb0f-199a99d97af9
* Content: [Preparing for TLS 1.2 in Office 365 and Office 365 GCC - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/o365-security/prepare-tls-1.2-in-office-365#feedback)
* Content Source: [Microsoft365/security/o365-security/prepare-tls-1.2-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/security/o365-security/prepare-tls-1.2-in-office-365.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Reeced40** [comment]
@ma261065 thank you for reaching out. Apologies for the delayed response. Please see related issue and let me know if this helps -  https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2758

**Comment by Reeced40** [comment]
@ma261065 please can you let me know if this issue has been resolved and can be closed, as the article mentions the date October 2020.  Thanks again for your valuable input.

**Comment by nam31** [comment]
@ma261065 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
