### ISSUE TITLE
Unclear

### ISSUE THREAD

**Issue by heikoludwig** [MicrosoftDocs/OfficeDocs-Support#477]
Doesn't work for me. I don't have a Microsoft folder in Library, use a few microsoft plist files. None for PPT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9ec3586-e95e-26d8-caa1-f4baee90275a
* Version Independent ID: e7c1e698-fe8e-b67b-425f-799277c0f071
* Content: [Unable to start PowerPoint for Mac - Office](https://docs.microsoft.com/en-us/office/troubleshoot/powerpoint/fails-starting-powerpoint-mac#feedback)
* Content Source: [Office/Client/powerpoint/fails-starting-powerpoint-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/powerpoint/fails-starting-powerpoint-mac.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@heikoludwig this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@heikoludwig We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
