### ISSUE TITLE
is this solution still working?

### ISSUE THREAD

**Issue by alneven** [MicrosoftDocs/OfficeDocs-Support#478]
hi there,
I have outlook 2016 and I can change the subfolders (for example "only for Inbox") and for a few seconds the number of emails is also changed, but after that it includes the PersonMetadata entries again.
Any suggestion?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5d228b-c88c-f396-0680-1974ee3836a9
* Version Independent ID: 5d4feafb-42dd-edce-4caa-06226cbd9e12
* Content: [Outlook search folders show unexpected mail items with an empty subject - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/search/personmetadata-items#feedback)
* Content Source: [Outlook/Client/search/personmetadata-items.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/search/personmetadata-items.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by alneven** [comment]
humm, this is a bit confusing...
you have to remove the first/on the top checkbox for the whole email:
<img width="60" alt="ooo" src="https://user-images.githubusercontent.com/16620485/79838648-9d51f480-83b3-11ea-84a3-bb7045a8816a.png">

after this it will work...

**Comment by superdale007** [comment]
Why would this all of a sudden (after using Outlook for 10+ years) be a "Thing"!?!
