### ISSUE TITLE
Method 2

### ISSUE THREAD

**Issue by douglasac10** [MicrosoftDocs/OfficeDocs-Support#48]
Under Method 2 it says "The following knowledge base articles...", however, there are no knowledge base articles linked there. 

Additionally, the info box has the grammatically incorrect "These article require you to install and add a registry key" - this should either be "These articles" or "This article". 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90a8b996-c44c-02fc-746a-5747f2b40cc8
* Version Independent ID: bfff6e2d-4ab8-ad6c-01a5-262151f18412
* Content: [You receive a Too many different cell formats error message in Excel - Office](https://docs.microsoft.com/en-au/office/troubleshoot/excel/too-many-different-cell-formats-in-excel)
* Content Source: [Office/Client/excel/too-many-different-cell-formats-in-excel.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/too-many-different-cell-formats-in-excel.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Working on a fix for these issues.

**Comment by simonxjx** [comment]
https://docs.microsoft.com/en-us/office/troubleshoot/excel/too-many-different-cell-formats-in-excel is fixed.
