### ISSUE TITLE
Link to Office ULS Logs redirects to 404

### ISSUE THREAD

**Issue by isuckatscripting** [MicrosoftDocs/OfficeDocs-Support#480]
The link in Symptom 4 for Office ULS logs redirects to 404 error.
Might be trying to redirect:
https://docs.microsoft.com/en-us/office/troubleshoot/diagnostic-logs/how-to-enable-office-365-proplus-uls-logging

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb91ee9-4509-b01f-6260-18114bc44f52
* Version Independent ID: 67fbeacf-d523-df48-fbd8-e35135960727
* Content: [Connection issues in sign-in after update to Office 2016 build 16.0.7967 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/authentication/connection-issue-when-sign-in-office-2016)
* Content Source: [Microsoft365/admin/authentication/connection-issue-when-sign-in-office-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/authentication/connection-issue-when-sign-in-office-2016.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. Yes, the article is moved to a new location. The link is updated.
