### ISSUE TITLE
Unread email

### ISSUE THREAD

**Issue by dnsss90** [MicrosoftDocs/OfficeDocs-Support#481]
The built in search folder for unread emails suddenly has almost a thousand emails in it and I can't change the criteria for that specific search folder by following your instructions. Do you have any way to modify the built in search folders? This particular search folder is the only one I can't live without.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5d228b-c88c-f396-0680-1974ee3836a9
* Version Independent ID: 5d4feafb-42dd-edce-4caa-06226cbd9e12
* Content: [Outlook search folders show unexpected mail items with an empty subject - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/search/personmetadata-items#feedback)
* Content Source: [Outlook/Client/search/personmetadata-items.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/search/personmetadata-items.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. You can visit https://support.office.com/en-us/outlook for more support.

**Comment by DCEagle01** [comment]
I did what @alneven recommended below and it worked perfectly for my Win 7 user on Outlook 2013. Right click the folder, click Customize, then click Browse, then uncheck the very top account xxxxxx@.com or whatever yours is, then just check the inbox and it got rid of the 1,000 unread personmetadata folder for me.
