### ISSUE TITLE
duo mobile

### ISSUE THREAD

**Issue by fahadsul** [MicrosoftDocs/OfficeDocs-Support#484]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62828759-47a9-6685-0c2d-ab141c75d0c5
* Version Independent ID: 8a85abdf-33f1-bb10-ac7d-f00b11f73a8c
* Content: [Office doesn't render a custom DUO API multi-factor authentication login page - Office](https://docs.microsoft.com/en-us/office/troubleshoot/authentication/not-render-a-custom-duo-api-multi-factor-authentication-login-page#feedback)
* Content Source: [Office/OfficeExperts/authentication/not-render-a-custom-duo-api-multi-factor-authentication-login-page.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/authentication/not-render-a-custom-duo-api-multi-factor-authentication-login-page.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **warrenr**

**Comment by fahadsul** [comment]
do

**Comment by fahadsul** [comment]
-

**Comment by nam31** [comment]
@fahadsul The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content
Thank you.

**Comment by nam31** [comment]
@fahadsul We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
