### ISSUE TITLE
Yes, it is always Office 9.0

### ISSUE THREAD

**Issue by MrM40** [MicrosoftDocs/OfficeDocs-Support#487]
It is actually "..\Office\9.0\.." even though you use a newer Office version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6621f77-f212-d653-6a1f-b53377122299
* Version Independent ID: 00180269-ac22-7154-fe4a-38b9f0a4ecbf
* Content: [Cannot locate the Internet or proxy server when selecting hyperlink in Office - Office](https://docs.microsoft.com/en-us/office/troubleshoot/error-messages/cannot-locate-server-when-click-hyperlink)
* Content Source: [Office/Client/error-messages/cannot-locate-server-when-click-hyperlink.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/error-messages/cannot-locate-server-when-click-hyperlink.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment.
