### ISSUE TITLE
中国电信网络环境下的onedrive无法登陆。

### ISSUE THREAD

**Issue by onlyscv** [MicrosoftDocs/OfficeDocs-Support#489]
中国电信网络环境下的onedrive无法登陆。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7f440093-321f-47f7-e893-ffead3e70c88
* Version Independent ID: 6fc68489-3b0e-a6dd-df77-42ab2e128757
* Content: [列出 OneDrive for business 的一些问题](https://docs.microsoft.com/zh-cn/sharepoint/troubleshoot/onedrive#feedback)
* Content Source: [SharePoint/OneDrive/onedrive.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/OneDrive/onedrive.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by simonxjx** [comment]
Thanks for your comment. This issue occurs because of the local Internet settings. You can try to use the One Drive client instead.
