### ISSUE TITLE
Download link?

### ISSUE THREAD

**Issue by kingzettbb** [MicrosoftDocs/OfficeDocs-Support#49]
I'm not able to find this tool in WSUS or the update catalog. Would you be able to add it or provide a download link?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4699da98-06e2-c03c-9cbb-a82f7c44ebe6
* Version Independent ID: 82b53e22-fd8a-9f84-f0f7-0bc0282027f7
* Content: [Click-to-Run Update Support Tool for Office - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/licensing/click-to-run-update-support-tool#feedback)
* Content Source: [Microsoft365/admin/licensing/click-to-run-update-support-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/licensing/click-to-run-update-support-tool.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
This tool is not longer available. Removing this article.

**Comment by kingzettbb** [comment]
Is there a comparable tool available?
