### ISSUE TITLE
Fix dosn‘t work for me

### ISSUE THREAD

**Issue by Rampdisli** [MicrosoftDocs/OfficeDocs-Support#491]
Set up the sideload project for Excel following the tutorial on the microsoft site.
It works well on mac, online and on windows where the „old“ edge is installed. But on windows with the new edge I get the error „we can not open the add-in from localhost“.
I tried the fix as discribed but it changed nothing. I although move the webpart on a server, but even then I get the same error on windows with the new edge all other platforms works fine. What can I do else ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 236f9838-fd32-0154-122e-77725824160a
* Version Independent ID: 76d757f8-a4b1-3bb2-a186-a21b385c6b7e
* Content: [We can't open this add-in from localhost - Office](https://docs.microsoft.com/en-us/office/troubleshoot/error-messages/cannot-open-add-in-from-localhost#feedback)
* Content Source: [Office/Client/error-messages/cannot-open-add-in-from-localhost.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/error-messages/cannot-open-add-in-from-localhost.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@Rampdisli . Might be some windows office related files are corrupted or installed office suite might be corrupted.

**Comment by nam31** [comment]
@Rampdisli this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@Rampdisli We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
