### ISSUE TITLE
Workaround does not work on Forms Pro

### ISSUE THREAD

**Issue by Ian-H2006** [MicrosoftDocs/OfficeDocs-Support#494]
This is a serious bug which makes Forms Pro unworkable for my intended use of the  application. This bug needs fixing as a matter of priority. The workaround provided does not work with Forms Pro which has a different interface for responses. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3f3199-69e9-2514-70e3-effbbb679bcd
* Version Independent ID: 370dbbaf-035c-2f57-7ecd-1d7a4412c051
* Content: [Forms response columns are out of order - Office](https://docs.microsoft.com/en-us/office/troubleshoot/microsoft-forms/forms-response-columns-out-of-order#feedback)
* Content Source: [Office/OfficeExperts/microsoft-forms/forms-response-columns-out-of-order.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/microsoft-forms/forms-response-columns-out-of-order.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **zakirh**

**Comment by davereinhardt** [comment]
+1 for @Ian-H2006 's comment. In my client we'd also like to use Forms Pro but cannot do so because of this bug.

**Comment by jalcerreca77** [comment]
All you have to do is select the header column and cut it and use the insert cut cells option to move the columns in the order you want and works like a charm.  Tried it and was able to maintain the integrity of the form responses.

**Comment by Ian-H2006** [comment]
Thank you the response - but that is not really a workaround. Manually repairing the broken excel file was always an option - but what is needed is a workaround similar to the Forms one where you prevent the production of the broken file in the first place by using "Sync all responses to a new workbook". Also, the problem is that the mis-ordering of the response columns is not predictable and can vary if the survey is edited, so you proposed solution requires some detective work to align columns with headers.

**Comment by joinimran** [comment]
Hi @Ian-H2006, thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by joinimran** [comment]
@lan-H2006 / @jalcerreca77 - Can you please both see if you guys are still facing this issue. I have checked and found that this is working as expected. Even I have changed/shuffled the questions. The response column remained the same.

Thanks.

**Comment by nam31** [comment]
@Ian-H2006 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
