### ISSUE TITLE
Details are out of date

### ISSUE THREAD

**Issue by TheRealStriff** [MicrosoftDocs/OfficeDocs-Support#495]
1. Sign in to Outlook Web App, click Settings &gt; View All Outlook settings
2. In the left navigation pane, click General
3. In the current "Language and time" box, click the arrow, and then click the correct time zone setting
4. Click Save

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 570a7ee0-fb80-2542-0418-9e5742eb047b
* Version Independent ID: 3897aabd-6c7f-81f4-db76-8288dbb6df7b
* Content: [The time zone setting is set incorrectly to (UTC) Monrovia, Reykjavik - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/owa-time-zones/incorrect-setting#feedback)
* Content Source: [Exchange/ExchangeOnline/owa-time-zones/incorrect-setting.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/owa-time-zones/incorrect-setting.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@TheRealStriff This article has been retired as the product was updated last year and the problem documented in the article doesn’t exist anymore.
Thank you
