### ISSUE TITLE
The function of picture displaying thumbnail in document library

### ISSUE THREAD

**Issue by LeeNoon** [MicrosoftDocs/OfficeDocs-Support#496]
We have learned the following information. Do you have an update plan for this function?
By looking at the international version of office365, it is found that when thumbnails are loaded, an interface named storagegetthumbnail will be called. This interface is used to show the association between thumbnails and system resources. After the association, thumbnails can be displayed normally.
But the way of onedrive request in China is different from that in the global version and the personal version. It sends out the post request directly and does not request the thumbnail, so the default icon of the system will be displayed.
This problem is a feature gap, which is consistent with the previous onedrive service in China given by the product group. The behavior generated is inconsistent with other versions of office 365.

**Comment by RAJU2529** [comment]
@LeeNoon. Which article are you referring?

**Comment by nam31** [comment]
@LeeNoon The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@LeeNoon We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
