### ISSUE TITLE
Mac Outlook 2016 Search Issue - Workaround suggestion for Mojave 10.14 doesn't work

### ISSUE THREAD

**Issue by mac471** [MicrosoftDocs/OfficeDocs-Support#50]
Upgraded from Macbook Pro (late 2016) running High Sierra to Macbook Pro (2019) running Mojave 10.14.5 using Migration Assistant and Target Disk Mode (on old Mac). 

Running Mac Outlook 2016 (version 16.16.12) and "No Results" is shown when trying to search for emails.  Curiously, macOS Spotlight will show email search results but not Mac Outlook.

- Tried workaround suggested above (dragging profile to Privacy tab and then removing it...and waiting for indexing to complete). This did not work.
- Tried "mdimport -L" to confirm that there is only 1 Outlook importer
- Used "Outlook Profile Manager" to create a "new" profile and re-created email accounts from scratch (imap accounts, if that matters)
- Tried using "Rebuild" on a folder in Outlook as suggested in a forum post - waiting for indexing to completed. This did not work
- Reluctant to try uninstalling Mac Office 2016 and re-installing because Microsoft does not provide an uninstaller tool.  Deleting individual files/folders in ~/Library feels risky - what if this causes the Mac not to boot?

Question: has Microsoft tested this workaround with Mac Outlook 2016 or only with Mac Outlook 2019?  I thought about upgrading to Office 2019 but don't want to deal with a new list of incompatibilities between 2019 and Mojave.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a55b51-85d6-f628-581c-5a1c66675933
* Version Independent ID: 9f626f3a-123d-67ca-3aa8-a3443963fe05
* Content: [Outlook for Mac support tools. - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/outlook-for-mac/useful-tools#feedback)
* Content Source: [Outlook/OutlookExperts/outlook-for-mac/useful-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/OutlookExperts/outlook-for-mac/useful-tools.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by takhozu10** [comment]
Same here. I can't get the work around for Mojave to work. The tool works great on High Sierra. It works every time for me.

**Comment by mac471** [comment]
Here is a link for a more detailed accounting of what I've found: [https://answers.microsoft.com/en-us/msoffice/forum/all/mac-outlook-2016-search-returns-no-results-after/1accb0e2-56eb-4293-acb9-238051644428](url)

Basically, I've tracked the problem down to a Spotlight meta-data attribute that is being set incorrectly: kMDItemKind is being set to "Document" in Mojave and "olk15_message" in High Sierra.

This is why Spotlight will still see the email file but Mac Outlook 2016 (which must be looking for "olk15_message") does not.  

I've confirmed this by using the bash commands mdls and mdfind.

On High Sierra, open Terminal and type:

`mdfind -count "kMDItemKind" == "olk15_message"`

After a few seconds, you'll see the number of matching items.

On Mojave, open Terminal and type the same thing and you will receive "0"

However, if you type:

`mdfind -count "kMDItemKind" == "Document"`

you'll see a non-zero value (this includes items other than emails).

I compared the Outlook spotlight mdimporter on the Mojave machine with the High Sierra machine and they appear to be the same. I'm wondering if Migration Assistant just copied the High Sierra mdimporter as-is (how would it know that a new one is required) if the Microsoft Office updating tool just figures that if we're running on Mojave, the mdimporter must be current.

Current Microsoft Outlook suggested solution is to un-install and re-install Office 2016.  They haven't confirmed that this will indeed fix the problem.  Just something to try because it has worked for others in the past.

Not particularly happy with this solution but will post updates if it works.

**Comment by ntaylor-nanigans** [comment]
@mac471, did un-install and re-install resolve your search issues?  I am facing the same problem.

**Comment by mac471** [comment]
Yes, un-install/re-install resolved the search issue. I have several imap email accounts with a lot of messages so it took several hours to rebuild my Outlook inboxes (was the third time I had to do this because the other methods also required rebuilding) but search started to work correctly right away.  

This link has the full results of my investigation: [https://answers.microsoft.com/en-us/msoffice/forum/all/mac-outlook-2016-search-returns-no-results-after/1accb0e2-56eb-4293-acb9-238051644428](https://answers.microsoft.com/en-us/msoffice/forum/all/mac-outlook-2016-search-returns-no-results-after/1accb0e2-56eb-4293-acb9-238051644428)

Seems like this is a problem that Apple and Microsoft could jointly solve if they worked together to save their customers hours of frustration.  Start with any Mac that is running High Sierra and Outlook and then use the Migration Assistant to initialize a new Mac running Mojave. Then figure out what didn't migrate correctly and fix the Migration Assistant.

**Comment by dfuentes03** [comment]
For step #4 in the instructions for macOS Mojave - should we be removing the folder from the Spotlight 'Privacy' window or removing the folder from the directory completely?

**Comment by mac471** [comment]
If you are referencing the list of things that were tried (and failed), then the answer is to remove the folder from the Spotlight "Privacy" window only. Removing the folder causes Spotlight to start indexing it again.

**Comment by AlexTelly** [comment]
I am having this search issue. I've tried the Spotlight Privacy fix but can see no evidence of the re-indexing happening when I remover the profile. Psined1 - please could you tell me how to delete and re-register a profile? Many thanks.

**Comment by Flower7C3** [comment]
No of this solutions work for me. I am still unable to search emails in Outlook app (not via Spotlight).

**Comment by AlexTelly** [comment]
Thank you so much for taking the time to explain. I'll try this today and feedback.

**Comment by Flower7C3** [comment]
@psined1 I did this steps and finally it works 🎉

**Comment by AlexTelly** [comment]
@psined1 - Thanks a million for the walk through. I've just followed your route and can now search again. I can't tell you how grateful I am for this solution - the search function is absolutely indispensable in my work. SO grateful for your time and generosity.

**Comment by jwidenerga** [comment]
@psined1 - THANK YOU! Solved my problems as well. @microsoft - please update your info for this issue to reflect the steps offered by @psined1.

**Comment by jasermd** [comment]
I need some help here. I am having the same problem. Apple Support no help as of now. Microsoft Outlook support said to do the following: 

Thanks for contacting Outlook for Mac Support, my name is Saleem and I will be assisting you today.

Can you please perform these steps to reindex your search and let us know if it helps:

1. Choose Apple menu > System Preferences, then click Spotlight.
2. Click the Privacy tab.
3. Drag your Macintosh HD to the Privacy tab. Once added, remove the drive immediately and Spotlight will re-index the drive.
4. Wait at least an hour before searching in Outlook for Mac.

I tried this but when I dragged the MacIntosh HD icon over to Privacy it would not stick.

In the instructions above from @psined1, I do not understand all of the instructions listed. I can find the Outlook Profile Manager under Shared Support. I do not see a list however that identifies my current profile and I do not know what is meant by "delete it with ""-" button? Help would be appreciated here. Thanks

**Comment by simonbuerger** [comment]
tried the listed steps AND tried @psined1 solution on MacOS Catalina and still no indexing even after removing the profile entirely and re-opening Outlook

**Comment by mac471** [comment]
I can't speak for MacOS Catalina (my issue was upgrading to Mojave) but I tried all of the various "re-indexing" approaches (e.g. deleting/rebuilding profiles, changing privacy options for Spotlight, etc.) and nothing worked until I un-installed Mac Outlook (I am using 2016 version) and re-installing it again. 

Note: My email services (Google and Comcast) are using IMAP - which means that my Mac is keeping a **copy** of all my messages on the respective email servers. So when I re-installed Outlook, it just took awhile to "resync" (make a copy on my local Mac) all of my messages.

If you are using POP email (you can tell by going into Outlook/Preferences/Accounts), you should save a copy of your email before you un-install (just in case) since the messages are no longer on the server - they are on your Mac.

As a precaution, do a full backup before you start the un-install/re-install process just to be safe.

**Comment by jasermd** [comment]
Here is what worked for me. Also, in outlook click on Help at the top menu, then Outlook Support – MFST support responded by messaging within the Outlook program (the responsive shows up in the lower right corner of Outlook when they respond.

 

1) Download the latest Production Release by following the instructions in this link: https://support.office.com/en-us/article/download-and-install-or-reinstall-office-365-or-office-2016-on-a-pc-or-mac-4414eaaf-0478-48be-9c42-23adc4716658

2) Quit all Office apps (Word, Excel, PowerPoint, OneNote, & Outlook)

3) Go into Applications folder and drag each of these apps to the trash

4) Empty Trash

5) Open Keychain app and search for ADAL and delete all MicrosoftOffice15 keys

6) Install the Office version that your downloaded in step 1

7) Open Outlook first and input password(s) for email account(s)

 

 

Please note once you have completed steps 1-7, right click on Outlook on the dock to quit and relaunch then reindex Outlook by doing the following:

 

1. Choose Apple menu > System Preferences, then click Spotlight.

2. Click the Privacy tab.

3. Drag your Macintosh HD to the Privacy tab. Once added, remove the drive immediately and Spotlight will re-index the drive.

4. Wait at least an hour before searching in Outlook for Mac.

 

 

NOTE- I using Mojave

**Comment by msulwa** [comment]
Thank you @psined1 - I did the steps you advised and this is the only solution that worked for me!

**Comment by jessicaandrey012** [comment]
Hello, I am Jessica Andrey and I am working with [outlook search not working](https://comofficesetup.com/blog/outlook-search-not-working-on-mac/). Our Company gives the total answer for all the outlook related issues. You can get moment specialized help from our specialists for issues like outlook search function not working issues, secret word recuperation, availability issues, and so forth. You can call our specialists whenever to get moment help.

**Comment by adam-ludgate** [comment]
I have tried the spotlight tool fix, wiping Outlook 2016 completely from my mac, along with the profile data, etc. None of these solutions seem to work. There are keywords I search for when I use my account in Gmail which produce results, but come up empty in Outlook. Is there just a poor keyword search function in outlook? It's really affecting my ability to do work, when I search for a term which I know exists in an email but it does not appear in search results in Outlook.

Help!

**Comment by nam31** [comment]
@mac471 The best way to get your issue resolved is to contact Microsoft Support. 
If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 
Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
