### ISSUE TITLE
PFP changing not recorded properly

### ISSUE THREAD

**Issue by Bk49** [MicrosoftDocs/OfficeDocs-Support#504]
Although on my site, the profile picture has changed, but the profile picture still displays the same one when viewed from my friend's site

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f57501e-bafa-eeeb-ea6c-7126182f1e0a
* Version Independent ID: eb9112dd-3ce2-23dd-fad4-4caa2d85ad47
* Content: [Listing some issues for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/troubleshoot/teams#feedback)
* Content Source: [Teams/teams.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams.md)
* Service: **msteams**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by AmandaAZ** [comment]
Thank you for contacting Microsoft, For this issue, you can contact [Teams Support](https://support.office.com/teams).
