### ISSUE TITLE
Another Potential Fix - This Worked for Me

### ISSUE THREAD

**Issue by tillyny** [MicrosoftDocs/OfficeDocs-Support#505]
I had this issue because I had a tab name in my Excel file that contained apostrophes, as well as a column with data that also contained apostrophes. When I deleted the apostrophes from the tab name and saved the Excel file, the paste error went away. My suggestion is to check for potential invalid characters in a spreadsheet name in your Excel file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85483394-0194-dbb2-3261-63bdba0d0e6d
* Version Independent ID: 9770a875-4f9f-46f3-a601-5bbfa5a759da
* Content: [Unable to copy and paste from Excel into Access - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/clipboard-data-damaged#feedback)
* Content Source: [Office/Client/access/clipboard-data-damaged.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/clipboard-data-damaged.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by joinimran** [comment]
Hi @tillyny, thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by nam31** [comment]
@tillyny we are going to close this issue as the article has been updated accordingly. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
