### ISSUE TITLE
Error: Invalid change in step 2.

### ISSUE THREAD

**Issue by Vukain** [MicrosoftDocs/OfficeDocs-Support#509]
The previous version was proper, in step 2 it should jump to step 4 (not 5) - if a year is divisible by 4 and not divisible by 100 - it IS a leap year.
Now the script is invalid, not working properly for leap years like 2004.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6f92333-a9f0-7616-64e8-5aaceb1e3f40
* Version Independent ID: c8136395-44ec-6eb6-3153-53527baf19b3
* Content: [Method to determine whether a year is a leap year - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/determine-a-leap-year#feedback)
* Content Source: [Office/Client/excel/determine-a-leap-year.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/determine-a-leap-year.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
Any four-digit number is divisible by 4 then its automatically called LEAP Year. the  following steps is enough 

1. If the year is divisible by 4, go to step 2. Otherwise, go to step 3.
2. The year is a leap year (it has 366 days).
3. The year is not a leap year (it has 365 days).

**Comment by Vukain** [comment]
Nope, that's a primary school definition of a leap year, which isn't true.
There are more conditions.


pon., 4 maj 2020 o 08:50 VARADHARAJAN K <notifications@github.com>
napisał(a):

**Comment by simonxjx** [comment]
The article is updated.
