### ISSUE TITLE
Using WorksheetFunctions within a VBA written Excel Function

### ISSUE THREAD

**Issue by DWMULLARD** [MicrosoftDocs/OfficeDocs-Support#51]
You cannot use a WorksheetFunction within function written in VBA and called from a spreadsheet, a user written Excel function.
You get a "Application-defined or object-defined error" message. Error 50290.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b873508-4f19-a23b-2d3c-c559d18df1ff
* Version Independent ID: 247bf64e-be19-05b0-da6e-fca2b9058be1
* Content: [Use a worksheet function in a Visual Basic macro - Office](https://docs.microsoft.com/en-gb/office/troubleshoot/excel/worksheet-function-in-vb-macro)
* Content Source: [Office/Client/excel/worksheet-function-in-vb-macro.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/worksheet-function-in-vb-macro.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Checking on this issue.

**Comment by jlriesco** [comment]
(objApp = New Excel.Application() within the office "365proplus" environment) should work. Looks like some previous Office installs or something has left the registry in a bad state at your machine.

**Comment by jlriesco** [comment]
It works for me so I am not sure what you are referring to. Note that there is no UI for run-time errors for User Defined Functions, they just return an error to the cell, so possibly you are doing something different than we understand?

**Comment by nam31** [comment]
@DWMULLARD, this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@DWMULLARD We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
