### ISSUE TITLE
Windows 10 1909

### ISSUE THREAD

**Issue by brunofelipens** [MicrosoftDocs/OfficeDocs-Support#510]
Does this work on Windows 10

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: ce321185-d005-bcfb-74bf-a23bd31850a6
* Version Independent ID: f96194ef-a823-7f29-fda3-4dc6e84f6831
* Content: [Como configurar o cliente de email padrão usando a política de grupo](https://docs.microsoft.com/pt-br/office365/troubleshoot/group-policy/configure-email-client-using-policy#feedback)
* Content Source: [Microsoft365/admin/group-policy/configure-email-client-using-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/group-policy/configure-email-client-using-policy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments. The article has been updated and it works in Windows 10.
