### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by JeffArch59** [MicrosoftDocs/OfficeDocs-Support#515]
The link in the Note at the bottom of this article is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d45701c5-de5f-e13e-de35-5ea62ec672cf
* Version Independent ID: 2edc6fe2-ab0b-7032-12a2-321e9a3daedc
* Content: [Formula errors when list separater is not set correctly - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/formula-errors#feedback)
* Content Source: [Office/Client/excel/formula-errors.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/formula-errors.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The link in the article is updated.
