### ISSUE TITLE
Applies to more than Excel Online

### ISSUE THREAD

**Issue by erictreelight** [MicrosoftDocs/OfficeDocs-Support#516]
This problem appears to apply to Excel 2010, and I've seen at least one web report of user having a problem in Excel 2007. A query for a connection to a CSV file or other data source can be created, and can be edited. But manual refresh does not seem to work. There is an "auto-refresh after opening" option, and a "refresh after N minutes" option. One of those may work, although neither is appropriate for my application. In any case "Refresh All" does not appear to do anything. (My test: Delete the data, leaving the query intact. Then choose Refresh All. The data is not changed. Nor doe it change the data if the underlying CSV file is modified before choosing Refresh All.) In short, either the manual refresh operation does not work, and has not worked for quite a while, or the documentation that tells how to use it is (somehow) misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e487-5605-d812-c84c-4fed53011679
* Version Independent ID: 20a863fd-e69e-ae61-5017-ad24a695b660
* Content: [External users cannot refresh data connections from Excel Online - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/excel-online-external-users-cannot-refresh-data-connections#feedback)
* Content Source: [Office/OfficeExperts/excel/excel-online-external-users-cannot-refresh-data-connections.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/excel/excel-online-external-users-cannot-refresh-data-connections.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **warrenr**

**Comment by erictreelight** [comment]
Something I forgot to mention: I enabled "Prompt for filename on refresh".
(I tried my test with that property disabled, however, with no effect.)

**Comment by erictreelight** [comment]
One more thing: After CLOSING the spreadsheet and RE-OPENING it. The connection appears in the list. The Refresh operation then does something. This is a bug in the docs, imho. It should be noted that the connection only "exists" as something that can be refreshed after the file is closed.

**Comment by Reeced40** [comment]
@erictreelight thank you for pointing this out and helping to improve MS Docs. I'm looking into it.

**Comment by Reeced40** [comment]
@erictreelight thank you for clearing this up. Just to be sure, are you suggesting adding a note to the article saying that the refresh does work, but only after the file is closed?  Also, are you an internal user of the tenant or external?

**Comment by erictreelight** [comment]
Sorry. It was more than a month ago. Yes. Oddly enough. If you read what I wrote, I am suggesting that you must close the file and re-open it for refresh to work. And I have no idea what "tenant" you are referring to. I'm not using Excel in the cloud. I don't buy such things.

**Comment by Reeced40** [comment]
@erictreelight thanks again for your input. This article is related to Excel Online, so the change/additional info workaround will not be applicable here. Please let me know if you have any further queries.

**Comment by nam31** [comment]
@erictreelight Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
