### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by aytimothy** [MicrosoftDocs/OfficeDocs-Support#517]
The link to the knowledgebase page (https://docs.microsoft.com/en-us/help/214019) is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e28dce76-cc6a-3af7-b51b-48ea6ba8b3ef
* Version Independent ID: c691ecbb-6184-a73b-2f25-2d72eccd8a14
* Content: [Excel incorrectly assumes that the year 1900 is a leap year - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/wrongly-assumes-1900-is-leap-year#feedback)
* Content Source: [Office/Client/excel/wrongly-assumes-1900-is-leap-year.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/wrongly-assumes-1900-is-leap-year.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by nam31** [comment]
Closing via https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/518
Thank you
