### ISSUE TITLE
32 and 64 bit drivers

### ISSUE THREAD

**Issue by PietDeBooser** [MicrosoftDocs/OfficeDocs-Support#519]
I need to install the 2016 engine for access so I am able to work with 64 bit ODBC drivers outside of access, so far so good. But the 32 bit driver for Access only supports *.mdb and not *.accdb. To solve this I installed the 32 bit 2016 engine after the 64 bit engine and the 32 bit problem is solved. If I try to create a 64 bit access odbc driver I get 'unable to load odbcji32.dll. I like to have a fix not only for the invisible  ACEODBC divers but also for the 32 bit accdb problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdf4f7db-9b53-0da7-41ab-17a57c6a1481
* Version Independent ID: 6d01c403-6542-083b-5087-a8d8fb4d33b5
* Content: [Can't use the Access ODBC driver or OLEDB provider outside Office Click-to-Run - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/cannot-use-odbc-or-oledb#feedback)
* Content Source: [Office/Client/access/cannot-use-odbc-or-oledb.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/cannot-use-odbc-or-oledb.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@PietDeBooser. Your issue is different, only experienced users with practical knowledge are able to give ideas. in meanwhile, you can post your query in technet.microsoft.com to get expert answers.

**Comment by msbemba** [comment]
@PietDeBooser  Thank you for your feedback. This document pertains to only a specific issue. You can follow the below instructions To check whether the 32-bit Microsoft Access Database Engine drivers are installed

1)Go to C:\Windows\SysWOW64\odbcad32.exe.
 If on a 32-bit machine, go to C:\Windows\System32\odbcad32.exe to access the utility. Navigate to the drivers tab. If the Microsoft Access Driver lists .mdb and .accdb, then the correct drivers are installed. If not, 

2)Expand Database Connections in the Catalog tree.
3)Double-click Add OLE DB Connection. The Data Link Properties dialog box appears in which you can create an OLE DB connection.

![image](https://user-images.githubusercontent.com/45987684/120403203-5d549380-c361-11eb-875e-1b8adcc165f3.png)

4)Click the OLE DB provider you want to use to access data.
5)Click Next or click the Connection tab.
6)Provide the required connection information. The Connection tab is different for each provider. Most require that you identify the database to which you want to connect along with your user name and password.
7)Click Test Connection to validate that you have entered connection information correctly.
8)Click OK once your test is successful.
9)Name your OLE DB connection.
10)Any table data sources in the connection format you added are displayed in the OLE DB connection node. You can expand this new OLE DB node to view and work with its table contents.

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@PietDeBooser Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
