### ISSUE TITLE
priviledges is misspelled

### ISSUE THREAD

**Issue by magowemogithub** [MicrosoftDocs/OfficeDocs-Support#520]
There is no 'd' in privileges

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1375a9d-fa30-75a2-5aea-daca0e74f142
* Version Independent ID: c9510807-f261-5a24-0039-d6bf5ad630e5
* Content: [Reset Microsoft 365 Apps for enterprise activation state - Office](https://docs.microsoft.com/en-us/office/troubleshoot/activation/reset-office-365-proplus-activation-state#feedback)
* Content Source: [Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md)
* Service: **o365-solutions**
* GitHub Login: @MJP-MSFT
* Microsoft Alias: **mattphil**

**Comment by MJP-MSFT** [comment]
Thanks for the help!  I have submitted a request to change this.

**Comment by MaryQiu1987** [comment]
Resolved the typo. So close the issue.
