### ISSUE TITLE
problem in converting into docs

### ISSUE THREAD

**Issue by Manasjain19** [MicrosoftDocs/OfficeDocs-Support#522]
I have the following file which is originally in doc format and is encrypted, and I am unable to reconvert back into doc.
Please help.

[Uploading Ch_1-4 - Copy.docx…]()

**Comment by RAJU2529** [comment]
@Manasjain19 . At first  decrypt the file , then open with office 2016 or 2019 , then save as .doc  format

**Comment by Manasjain19** [comment]
but if you can please guide me decrypting that, would be a great help.

**Comment by RAJU2529** [comment]
@Manasjain19 . Ask the sender , who sends the file to you. 
If the file owned by you means, if you used encryption software to encrypt, use same software to decrypt

**Comment by nam31** [comment]
@Manasjain19 The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@Manasjain19 We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
