### ISSUE TITLE
Question - why is mapping a drive to SharePoint no longer recommended?

### ISSUE THREAD

**Issue by SarahSue8** [MicrosoftDocs/OfficeDocs-Support#523]
Question - why is mapping a drive to SharePoint no longer recommended? This has been a supported functionality for all previous versions of SharePoint.  Why has this functionality been removed? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8928ed26-fda0-0e68-a4e1-cc287a5e5699
* Version Independent ID: c6ff303c-a5b4-4890-6d00-82246b92ea45
* Content: [Troubleshoot mapped network drives that connect to SharePoint Online - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/troubleshoot-mapped-network-drives#feedback)
* Content Source: [SharePoint/SharePointOnline/administration/troubleshoot-mapped-network-drives.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/administration/troubleshoot-mapped-network-drives.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by todmccoy** [comment]
Hi -- thank you for the comment. This article has been updated with new information to clarify mapping.
