### ISSUE TITLE
Step 6 needs to include adding teams.microsoft.com to trusted sites

### ISSUE THREAD

**Issue by SarahSue8** [MicrosoftDocs/OfficeDocs-Support#524]
Please update step 6 to include adding not only the SharePoint site but also teams.microsoft.com to the trusted sites in IE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8928ed26-fda0-0e68-a4e1-cc287a5e5699
* Version Independent ID: c6ff303c-a5b4-4890-6d00-82246b92ea45
* Content: [Troubleshoot mapped network drives that connect to SharePoint Online - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/troubleshoot-mapped-network-drives#feedback)
* Content Source: [SharePoint/SharePointOnline/administration/troubleshoot-mapped-network-drives.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/administration/troubleshoot-mapped-network-drives.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@SarahSue8 Thank you for your feedback. The Note in the document talks about adding the below Office 365 URLs to the Trusted sites zone:

https://*.sharepoint.com
https://*.microsoftonline.com
https://*.microsoft.com

https://*.microsoft.com would cover all hosts in the domain microsoft.com

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@SarahSue8 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
