### ISSUE TITLE
Resolved

### ISSUE THREAD

**Issue by ganarao** [MicrosoftDocs/OfficeDocs-Support#527]
The script works. Same error occur for sharepoint, uder same command modified the error number. Resolved

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37df5a1c-7436-91da-5d8c-d831155c3d96
* Version Independent ID: 89413c21-92ab-bb5f-47ca-66202aed5bcb
* Content: [Unable to sign in to Office 365 portal - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/sign-In/exchange-online-application-service-principal-disabled#feedback)
* Content Source: [Microsoft365/admin/sign-in/exchange-online-application-service-principal-disabled.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/sign-in/exchange-online-application-service-principal-disabled.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by nam31** [comment]
@ganarao We are happy to hear that your issue was resolved.
Thank you
