### ISSUE TITLE
很抱歉不能立即添加你的文件夹

### ISSUE THREAD

**Issue by zhangersan** [MicrosoftDocs/OfficeDocs-Support#529]
安装桌面版本的最后提示了以上的内容，应该怎么处理

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7f440093-321f-47f7-e893-ffead3e70c88
* Version Independent ID: 6fc68489-3b0e-a6dd-df77-42ab2e128757
* Content: [列出 OneDrive for business 的一些问题](https://docs.microsoft.com/zh-cn/sharepoint/troubleshoot/onedrive#feedback)
* Content Source: [SharePoint/OneDrive/onedrive.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/OneDrive/onedrive.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by AmandaAZ** [comment]
For this issue, you can try to get help from [OneDrive for Business Help](https://support.office.com/article/onedrive-for-business-help-1eaa32e9-3229-47c2-b363-0a5306cb8c37).
