### ISSUE TITLE
9. command-line confusing

### ISSUE THREAD

**Issue by aleghart** [MicrosoftDocs/OfficeDocs-Support#53]
Suggest editing Method 2 step 9 for clarity:
Removing first option:
'9. Run the command-line Outlook.exe /ResetFolders...'
Since this path included deleting the Reminders folder already, it should be performed.

At the very least, insert proper space between the commands.  It currently reads as a single command with multiple executables.  There is no space before the word 'or'.

Thanks for this write-up!  I needed to use the MFCMAPI method to stop the incessant pop-ups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 003b3cba-164f-4443-ad85-9509a54a125b
* Version Independent ID: c237b7a5-7b05-900d-adab-df43daed3d8a
* Content: [You can't successfully dismiss calendar reminders in Outlook - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/calendar-reminders/cannot-dismiss-outlook-calendar-reminders#feedback)
* Content Source: [Exchange/ExchangeHybrid/calendar-reminders/cannot-dismiss-outlook-calendar-reminders.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/calendar-reminders/cannot-dismiss-outlook-calendar-reminders.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by stephaniemad** [comment]
I found it to be confusing on 2 levels and perhaps this is why it did not work:

1. Powershell does not recognize "Outlook.exe" as a valid command, so that was a bust.
2. When you are in the tool, the choice to perform a hard deletion is not even mentioned in the instructions. Are you supposed to check the box for hard deletion?

I ended up running the cmd as a run command just to see and none of this worked for me. Any ideas? Any clarity here on the powershell cmd? This problem is so vexing, would love to resolve. Thanks!

**Comment by Brodur** [comment]
@stephaniemad Run it from the windows run prompt (Windows key+ R) and it seems to work.

**Comment by wayland63** [comment]
None of this has worked for me. 

Although I have alias', I am trying to remove the reminders from my main outlook address, which is not the "default" outlook address that is there. Do I need to include a path or some other information to reach the address I'm actually using?

Thank you,
Sarah

**Comment by nam31** [comment]
@aleghart, this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@aleghart We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
