### ISSUE TITLE
Wrong Information

### ISSUE THREAD

**Issue by xavierliancw** [MicrosoftDocs/OfficeDocs-Support#531]
The 5 steps that are written out are incorrect (and also do not match the given Excel formula).
1. If the year is evenly divisible by 400, go to step 4. Otherwise, go to step 2.
2. If the year is evenly divisible by 4, go to step 3. Otherwise, go to step 5.
3. If the year is evenly divisible by 100, go to step 4. Otherwise, go to step 5.
4. The year is a leap year (it has 366 days).
5. The year is not a leap year (it has 365 days).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6f92333-a9f0-7616-64e8-5aaceb1e3f40
* Version Independent ID: c8136395-44ec-6eb6-3153-53527baf19b3
* Content: [Method to determine whether a year is a leap year - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/determine-a-leap-year#feedback)
* Content Source: [Office/Client/excel/determine-a-leap-year.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/determine-a-leap-year.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The article is updated.
