### ISSUE TITLE
Lost iPad OneNotes created before sign in - lost after sign in

### ISSUE THREAD

**Issue by AmandaNoar** [MicrosoftDocs/OfficeDocs-Support#532]
Hi I cannot see an explanation here where to find notes that were created on an ipad before signing into an account. I have a staff member keeping important notes on an ipad for 4 years but had never signed into aa microsoft account or iCloud to back up. Yesterday she created an outlook.com account and signed into the onenote app to syn her 4 years of notes to onedrive online. Instead of syncing the notes all disappeared. Where can we locate the notes store and retrieve them on her ipad? Kind regards Amanda 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10310c2e-0e26-1b77-4d75-d200dfaa2e3a
* Version Independent ID: 414be698-d0d1-073a-d31b-dea440af3ee5
* Content: [How to locate your OneNote notebooks - Office](https://docs.microsoft.com/en-us/office/troubleshoot/onenote/locate-onenote-notebooks#feedback)
* Content Source: [Office/Client/onenote/locate-onenote-notebooks.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/onenote/locate-onenote-notebooks.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by msbemba** [comment]
@AmandaNoar Thank you for your feedback. 

The data from OneNote can be recovered only when it is signed in as the data gets saved to your one drive. All the troubleshooting steps point to methods that you can recover if you have saved data after signing in. Unfortunately, there is no way to recover it unless it was backed up - https://support.microsoft.com/en-us/office/back-up-notes-f58b34b0-611d-435e-87fa-7942a1767af4

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@AmandaNoar Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
