### ISSUE TITLE
Wrong information provided in the section "How to determine whether a year is a leap year "

### ISSUE THREAD

**Issue by rahulsolankib** [MicrosoftDocs/OfficeDocs-Support#533]
Correction
In the step 2, when year is divisible 4 and not divisible by 100 then go to step 4
In the step 3, when year is divisible 400 then go to step 4

the number should be either divisible by 4 and not divisible by 100 or it should be divisible by 400

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6f92333-a9f0-7616-64e8-5aaceb1e3f40
* Version Independent ID: c8136395-44ec-6eb6-3153-53527baf19b3
* Content: [Method to determine whether a year is a leap year - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/determine-a-leap-year#how-to-determine-whether-a-year-is-a-leap-year)
* Content Source: [Office/Client/excel/determine-a-leap-year.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/determine-a-leap-year.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The article is updated.
