### ISSUE TITLE
Incomplete instructions

### ISSUE THREAD

**Issue by JESii** [MicrosoftDocs/OfficeDocs-Support#537]
Method 1, step 2, item 11 says to "Go to step 13" but there is no step 13 Since my problem was not about corrupted preferences, that makes this page pretty much useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5413e44-74f0-4317-90cc-f4ee40d79cb1
* Version Independent ID: 2146e0ef-8148-3432-44d5-c3d5642dde43
* Content: [Unable to start Excel for Mac - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/fails-starting-excel-mac#feedback)
* Content Source: [Office/Client/excel/fails-starting-excel-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/fails-starting-excel-mac.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@JESii Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1503

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1503 
Thank you
