### ISSUE TITLE
Terrible Workaround

### ISSUE THREAD

**Issue by Luke-Robinett** [MicrosoftDocs/OfficeDocs-Support#539]
This is a laborious and clumsy workaround that isn't practical with large slideshows. Please just issue a patch for these versions of PowerPoint so the feature works as expected. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c48ef92-0783-aed5-93d9-0ee2c2407844
* Version Independent ID: 77db357d-bde5-19e0-0b8c-69885ee059b4
* Content: [Slide transition sounds missing - Office](https://docs.microsoft.com/en-us/office/troubleshoot/powerpoint/slide-transition-sounds-missing#feedback)
* Content Source: [Office/Client/powerpoint/slide-transition-sounds-missing.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/powerpoint/slide-transition-sounds-missing.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by joinimran** [comment]
Hi @Luke-Robinett , thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by Reeced40** [comment]
@Luke-Robinett thank you for reaching out and helping improve MS Docs. I have found this article with other answers/workarounds - https://answers.microsoft.com/msoffice/forum/msoffice_powerpoint-mso_win10-mso_o365b/powerpoint-recording-audio-disappeared-august-2018/574f9c4d-0fe6-47df-868a-2d0e0ab9851c. Please let me know if it helps at all or if you have any other suggestions to add to the article. I also see that this is quite an old issue so please let me know if the issue has been solved in the interim and I'll have it closed.

**Comment by Reeced40** [comment]
@Luke-Robinett please can you let me know if either of the workarounds helped.

**Comment by nam31** [comment]
@Luke-Robinett We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
