### ISSUE TITLE
Incorrect instructions

### ISSUE THREAD

**Issue by sudeepg100** [MicrosoftDocs/OfficeDocs-Support#54]
Under symptoms, second bullet point is
In Central Administration, you click on Monitoring .

This should change to: In Central Administration, you click on Upgrade and Migration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f071c79-f18b-8649-d968-3b95a0b22dba
* Version Independent ID: 74dcf2a0-180a-0eb0-8161-44274c6276da
* Content: [Upgrade Available status in new SharePoint Server 2016 farm - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/administration/upgrade-available-status-in-new-farm#feedback)
* Content Source: [SharePoint/SharePointServer/administration/upgrade-available-status-in-new-farm.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointServer/administration/upgrade-available-status-in-new-farm.md)
* Service: **sharepoint-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by spowriter** [comment]
Thanks for the feedback! Change request submitted.

**Comment by nam31** [comment]
@sudeepg100 the article has been updated accordingly and we are going to close this issue. Thanks.
