### ISSUE TITLE
Excel not openening

### ISSUE THREAD

**Issue by palani2002** [MicrosoftDocs/OfficeDocs-Support#540]
More Useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0926d3de-7dfd-e31d-fcdd-9ba57ed4dd5c
* Version Independent ID: 03d9dec8-d472-a70f-a9fc-c8b352de9eb7
* Content: [An error occurred when sending commands to the program in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/error-when-send-commands-in-excel#feedback)
* Content Source: [Office/Client/excel/error-when-send-commands-in-excel.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/error-when-send-commands-in-excel.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. If you need more help for this issue, you can contact support via https://support.office.com/en-us/excel.
