### ISSUE TITLE
inbox redirect rule and matching the sender based on envelope (not original sender, but the ones that redirects the message)

### ISSUE THREAD

**Issue by pbarsan** [MicrosoftDocs/OfficeDocs-Support#541]
Hello,

When we have a inbox redirect rule where we cannot match the sender to the person doing the redirect. It will always be the original sender no matter if we match both header and envelope. We are trying to block auto-forwarding messages outside the organization, but define an exception based on a list of people that are allowed to forward to any address.

The NDR message received back is quite confusing as it properly identifies the person doing the redirect as the sender. Is this something expected or an edge case scenario that was not considered on your end?

The NDR I get back is something like:
Sender Address:	&lt;internal_recipient@internal_domain.com&gt;
Recipient Address: &lt;redirect_recipient@external_domain.com&gt;
Subject: &lt;mail_subject&gt;
Error Details
Reported error:	550 5.7.1 TRANSPORT.RULES.RejectMessage; the message was rejected by organization policy 
DSN generated by:	VI1PR06MB5999.eurprd06.prod.outlook.com

From: &lt;original_sender@external_domain.com&gt;
To: &lt;internal_recipient@internal_domain.com&gt;
Subject: &lt;mail_subject&gt;
Resent-From: &lt;internal_recipient@internal_domain.com&gt;
Return-Path: &lt;internal_recipient@internal_domain.com&gt;

You can try and see internal Case #:19658996 for more context.

Best regards,
Petru.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83fdda33-b6a9-4aea-e53e-d663f5638ff0
* Version Independent ID: e7e651c2-384a-5714-09a8-b8880152bed3
* Content: [A transport rule doesn't match if user mailbox rules automatically forward messages - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/mailflow/autoforward-mail-exclusions-not-honored-transport-rule?source=docs)
* Content Source: [Exchange/ExchangeOnline/mailflow/autoforward-mail-exclusions-not-honored-transport-rule.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/mailflow/autoforward-mail-exclusions-not-honored-transport-rule.md)
* Service: **exchange-online**
* GitHub Login: @TobyTu
* Microsoft Alias: **Arindam.Thokder**

**Comment by TobyTu** [comment]
it seems we have an official aritcle to guide us fixing  550 5.7.1 issue, you may have a try:
https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-7-1-in-exchange-online
