### ISSUE TITLE
Please update EDU tenant note to include link to pre-provision page to ease our life

### ISSUE THREAD

**Issue by chrisATautomatemystuff** [MicrosoftDocs/OfficeDocs-Support#542]
Help an EDU tenant admin out ...

https://docs.microsoft.com/en-gb/sharepoint/troubleshoot/sites/troubleshooting-guide-for-sites-stopped-at-provisioning

That page states:

>  Note
> The exception to this process is an EDU tenant. Profiles will not be created for a user until the user > logs into SharePoint Online for the first time.

However, nowhere on the page does it indicate that an EDU tenant can pre-provision their users OneDrive.

https://docs.microsoft.com/en-us/onedrive/pre-provision-accounts

That page states we can:

> $users = Get-Content -path "C:\Users.txt"
> Request-SPOPersonalSite -UserEmails $users

Then the personal site will provision.

This is an issue for K-12 schools who are now being asked to move student data to the cloud. When we spoke with Microsoft support they indicated the first link and told us to have the student login. How in the world are we supposed to coordinate students from 7 different school districts logging into their account? Until we pushed Microsoft support for a method that would allow us to handle this on our own, they pointed us to the pre-provision page. We need to be able to use mover.io and have these personal sites provisioned for the move and now that we can feed this Request-SPOPersonalSite a list of failed users from mover.io we can keep this project moving for all our school districts!

Can you please, please, please link the pre-provision page on the EDU tenant Note on the other page ... so other EDU admins don't have to wrestle with support telling us to have users login?

-Chris Thomas
@AutomateMyStuff
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16530c0c-c037-3b4e-1850-48bb609d7ae6
* Version Independent ID: 9a136221-2699-2088-1d12-6db7092f6edb
* Content: [Troubleshooting guide to OneDrive for Business sites stopped at provisioning stage - SharePoint](https://docs.microsoft.com/en-gb/sharepoint/troubleshoot/sites/troubleshooting-guide-for-sites-stopped-at-provisioning#feedback)
* Content Source: [SharePoint/SharePointOnline/sites/troubleshooting-guide-for-sites-stopped-at-provisioning.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sites/troubleshooting-guide-for-sites-stopped-at-provisioning.md)
* Product: **onedrive**
* GitHub Login: @todmccoy
* Microsoft Alias: **v-todmc**

**Comment by todmccoy** [comment]
Thanks for the comment. The second note was updated with a little more information.
