### ISSUE TITLE
temp environment variable

### ISSUE THREAD

**Issue by paul835** [MicrosoftDocs/OfficeDocs-Support#543]
I have Office for Mac installed.  I do not therefore have windows explorer. But on some files I get the notice temp environment variable and cannot open the file.
How do I resolve it, please.
many thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f069189a-7af4-d6df-1509-f30af7d3c01d
* Version Independent ID: df260ca7-16dd-d2f8-1de3-91e0b71f67d4
* Content: [Word could not create the work file error message when you save a document - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/word-could-not-create-the-work-file#feedback)
* Content Source: [Office/Client/word/word-could-not-create-the-work-file.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/word-could-not-create-the-work-file.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. Please check if the following page can help your issue. https://answers.microsoft.com/en-us/msoffice/forum/all/word-could-not-create-the-work-file-check-the/8c24a45d-873c-42a8-a409-9c57efe048ee
