### ISSUE TITLE
What is the workaround?

### ISSUE THREAD

**Issue by rattija** [MicrosoftDocs/OfficeDocs-Support#544]
Assuming we didn't intend to open multiple instances of excel, how do we ensure that multiple workbooks are opened in the same instance?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a058cfe-b5fb-cda0-8cb0-963941787fea
* Version Independent ID: fad0294d-c5c2-8b7f-d03c-abb839be6196
* Content: [Cannot paste any attributes into a workbook in another Excel instance - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/cannot-paste-attributes#feedback)
* Content Source: [Office/Client/excel/cannot-paste-attributes.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/cannot-paste-attributes.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. You can check the following article for more information. https://docs.microsoft.com/en-us/office/troubleshoot/excel/force-excel-to-open-new-instance
