### ISSUE TITLE
What if the account that gets blocked is your ONLY admin

### ISSUE THREAD

**Issue by j0rt3g4** [MicrosoftDocs/OfficeDocs-Support#546]
What would be the process in this case or where should we create the ticket?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f11c3448-a9db-5197-a840-58d1dac4c733
* Version Independent ID: 5328ab5d-7120-ce06-510f-b6e3ca15371c
* Content: [Account has been blocked error when sign in to Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/account-blocked-error-when-sign-in#feedback)
* Content Source: [Microsoft365/admin/access-management/account-blocked-error-when-sign-in.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/access-management/account-blocked-error-when-sign-in.md)
* Service: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. You can get more support via https://support.office.com/home/contact.

**Comment by j0rt3g4** [comment]
Hello @simonxjx  
Well I can't log in into the account.
how should I supposed to login and request a ticket if I'm not able to login to the account? that's the whole thing?
And shouldn't this procedure be on this page?

**Comment by simonxjx** [comment]
Can you check if you can call the support via [Global Customer Service phone numbers](https://support.microsoft.com/help/4051701).

**Comment by msbemba** [comment]
@j0rt3g4 Thank you for your feedback. We have added information on the document stating this scenario and a link to reach out to support.

This can be tracked via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1606

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1606 
Thank you
