### ISSUE TITLE
No site can have the default language changed

### ISSUE THREAD

**Issue by AnatolN** [MicrosoftDocs/OfficeDocs-Support#547]
Change "In this scenario, the setting isn't changed successfully." "In this scenario, the setting cannot be changed. It is not possible to update the default language of a (any) site collection."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe93baa0-01ae-649b-3c31-b7981e3b1061
* Version Independent ID: 2d530e29-0c84-06b5-73c0-46c06c4949a3
* Content: [Can't change the default language for a site collection - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sites/change-default-language-site-collection)
* Content Source: [SharePoint/SharePointOnline/sites/change-default-language-site-collection.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sites/change-default-language-site-collection.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by get-itips** [comment]
Hello @AnatolN 
I can confirm that the article was updated and the sentence improved in [this commit](https://github.com/MicrosoftDocs/OfficeDocs-Support/commit/def10ec7c2a120eda9eb457b727f4c529d50472e).
Thank you

**Comment by nam31** [comment]
@AnatolN We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
