### ISSUE TITLE
This bug may be wider than you think

### ISSUE THREAD

**Issue by ryacoub** [MicrosoftDocs/OfficeDocs-Support#548]
We are experiencing this write conflict problem with only certain records while using MS Access version Office 365 ProPlus Version 2001 build 12430.20264 on a .mdb front end hitting tables in SQL server as the backend. Further, this is occurring with a form that is not multi-table, but uses subforms for other tables for related records.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cb02824-bd50-649b-070d-6c996c8dbfa5
* Version Independent ID: ac80eeae-b291-59a6-2665-ac2fd45eeab3
* Content: [Can't edit a record in a form that's based on a multi-table view - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/error-saving-edited-record#feedback)
* Content Source: [Office/Client/access/error-saving-edited-record.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/error-saving-edited-record.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by Reeced40** [comment]
@ryacoub thank you for reaching out and helping to improve MS Docs. Please can you let me know if this is still an issue as I see the article was updated after your original message.

**Comment by Reeced40** [comment]
@ryacoub please can you let me know if this issue was solved with the update.

**Comment by nam31** [comment]
@ryacoub We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
