### ISSUE TITLE
How is this fix not a part of office?

### ISSUE THREAD

**Issue by shaipetel** [MicrosoftDocs/OfficeDocs-Support#55]
This happens every time for every user who changes the default browser to Chrome.
Seems like a major issue, been having it for years until finally found this fix.
This should be fixed in the product already.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6621f77-f212-d653-6a1f-b53377122299
* Version Independent ID: 00180269-ac22-7154-fe4a-38b9f0a4ecbf
* Content: [Cannot locate the Internet or proxy server when click hyperlink in Office - Office](https://docs.microsoft.com/en-us/office/troubleshoot/error-messages/cannot-locate-server-when-click-hyperlink#feedback)
* Content Source: [Office/Client/error-messages/cannot-locate-server-when-click-hyperlink.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/error-messages/cannot-locate-server-when-click-hyperlink.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Please file a feature request through UserVoice, which is where engineering looks at feedback around feature requests.

This is the URL: [https://powerpoint.uservoice.com/](https://powerpoint.uservoice.com/)

**Comment by shaipetel** [comment]
Word not opening links and showing an error message sounds like a major bug to me, not a feature request... but by all means, keep classifying these things as feature requests and you'll soon end up as a sub-par product IMHO.

I sometimes wonder why do I even bother reporting issues if I always get the regular "add it to UserVoice" reply.

**Comment by jlriesco** [comment]
The UserVoice forum is not only for feature requests but also for bug reports. We appreciate that you keep on reporting issues with our products.

**Comment by shaipetel** [comment]
Oh, ok. So what is the github forum for then?
Sorry, I thought bugs go here and features/changes/ideas go to the user voice. Is that not correct?

**Comment by jlriesco** [comment]
Let me find out the best way to address this issue.
thanks.

**Comment by jlriesco** [comment]
Could you please tell me which version of Office are you using?
thanks.

**Comment by shaipetel** [comment]
this issue happened to me on office 2016 and now happens on office 2019.
pretty sure i seen it even before, but never bothered to research it...

Its as simple as installing office, installing chrome and setting chrome to be your default browser in windows 10. I can reproduce it on a number of devices.

Not using a proxy or anything like that.

Thanks!

**Comment by jlriesco** [comment]
Thank you for the info. I'll follow up on this.

**Comment by jlriesco** [comment]
Working with the Windows Supportability PM trying to find a solution

**Comment by jlriesco** [comment]
Hi Shai,

We haven't been able to reproduce the error using Chrome and Office 2016. Could you please let us know your machine configuration? (version of Windows, Office and type of PC?)
Thank you,
Jose

**Comment by shaipetel** [comment]
Sure,
windows 10 enterprise 64 bit
i7-8700
32GB RAM
Not connected to a domain.

Office 365 ProPlus, installed from my O365 tenant user and logged in. Version 1907

First thing I usually do is to install chrome and set it to be default. Never used IE or Edge on this machine.

The links I'm having trouble with are usually links that point to a SharePoint online site, which requires login.
So, if I put a link in a document to https://[tenant].sharepoint.com/sites/[site] it will never work, it will hang for a few seconds, trying to load and then show an error message. Subsequent clicks will show the error message immediately.

Hope that helps!

**Comment by jlriesco** [comment]
Yes, thank you. We'll follow up with this information.

**Comment by jlriesco** [comment]
Hello again, we are still unable to repro this issue. This is the configuration that we've used:
Windows 10 Enterprise 1903 
Core i7 x64 bit.  Signing in my MS credential.
O365 ProPlus Version 1907 (build 11901.20176) 
Chrome version 76.0.3809.100 set by default 
Save a link pointing at a SharePoint site in Word.  Clicking the link opens the SharePoint with Chrome.  
Save a link pointing at a word doc saved in the SharePoint.  Clicking the link opens the doc with Chrome. 

It seems like it could be an issue with SharePoint instead of Office so I will follow up that lead.

Thanks,
Jose

**Comment by jlriesco** [comment]
Sorry Shai, but we still can't repro your problem.

The best way to proceed is to create an official support request that will go to triage. You can do this at [https://support.microsoft.com/en-gb/hub/4343728/support-for-business](https://support.microsoft.com/en-gb/hub/4343728/support-for-business)

**Comment by jasonagold** [comment]
The easy-fix found here: http://support.microsoft.com/kb/218153 for this problem "Cannot locate the Internet server or proxy server" also fixes this problem:  Unable to open [link]. "Cannot download the information you requested''.

**Comment by shaipetel** [comment]
@jasonagold finding a solution wasn't hard, and the solution isn't hard to implement.
The point was: this is a very basic behavior, and I'm not sure why the users need ANY kb or fix at all, why isn't this fix included in office already?

**Comment by SudoCerb** [comment]
Agreed. This is ridiculous. Going to KB for this is NOT acceptable.
