### ISSUE TITLE
What makes a user federated?

### ISSUE THREAD

**Issue by pstasik** [MicrosoftDocs/OfficeDocs-Support#552]
Does federated mean ADFS, AADC, Hybrid joined?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5f0ba42-c4ad-3179-91e2-fcddc957c319
* Version Independent ID: e4b3b41e-f71a-27da-7837-6d305e709f5c
* Content: [Office applications periodically prompt for credentials - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/office-prompt-for-credentials#feedback)
* Content Source: [Microsoft365/admin/access-management/office-prompt-for-credentials.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/access-management/office-prompt-for-credentials.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Reeced40** [comment]
@pstasik thank you for reaching out. I'll revert soonest with more clarity.

**Comment by Reeced40** [comment]
@pstasik please see these two articles with more information regarding federated users - https://docs.microsoft.com/azure/active-directory/hybrid/how-to-connect-fed-whatis and https://docs.microsoft.com/azure/active-directory/devices/hybrid-azuread-join-federated-domains

**Comment by nam31** [comment]
@pstasik We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
