### ISSUE TITLE
Verification code email not showing up in Junk folder

### ISSUE THREAD

**Issue by astera-cmorrison** [MicrosoftDocs/OfficeDocs-Support#554]
Some users report that they do not receive the email even in their spam or junk folders. I suppose it's possible their company's security protocol filters the email out before it gets to the recipient. I echo aneubau's suggestion of making the verification code emails less spammy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c22f02e6-000b-ca44-2e72-78baeb7378cb
* Version Independent ID: 8e32d30e-05b0-df7d-af4f-fe4c0887c3c1
* Content: [No verification code when external recipients access shared secure links - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sharing-and-permissions/no-verification-code-to-access-shared-secure-link)
* Content Source: [SharePoint/SharePointOnline/sharing-and-permissions/no-verification-code-to-access-shared-secure-link.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sharing-and-permissions/no-verification-code-to-access-shared-secure-link.md)
* Service: **sharepoint-online**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by RAJU2529** [comment]
@astera-cmorrison. I don't know about the SharePoint server. 

Did you added  USERS email address  as trusted  in SharePoint server

**Comment by get-itips** [comment]
Hello @astera-cmorrison how are you? Hope you are doing good.

The best in this scenario, as here we are limited to documentation changes and improvements, would be to submit your idea [here](https://sharepoint.uservoice.com/).

Thank you for your feedback!

**Comment by get-itips** [comment]
Hello @astera-cmorrison Casey, how are you?
Checking back to understand if you could see my message.
Thank you!
cc @nam31

**Comment by nam31** [comment]
@astera-cmorrison We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
