### ISSUE TITLE
Location for Anonymization has changed

### ISSUE THREAD

**Issue by jwojan** [MicrosoftDocs/OfficeDocs-Support#556]
The current settings in the present UI is: Settings, Org Settings, and then Reports.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0586706c-4086-d5f8-9730-f8a305ab65d8
* Version Independent ID: af169905-b62a-842d-1c71-98c8866f44ec
* Content: [O365 reports show anonymous instead of actual user names - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/miscellaneous/reports-show-anonymous-user-name)
* Content Source: [Microsoft365/admin/miscellaneous/reports-show-anonymous-user-name.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/miscellaneous/reports-show-anonymous-user-name.md)
* Service: **o365-administration**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Guillaume-Couture** [comment]
As stated in the previous comment by @jwojan , Documentation would indeed benefit from a little refresher to match the updated UI that placed the option in a different and separate dashboard.   Thanks

**Comment by nam31** [comment]
@jwojan this article has been updated recently and accordingly. Please let us know if your issue is resolved now. Thanks

**Comment by jwojan** [comment]
The instructions are still incorrect. The document states to do the following:

1.     Go to https://portal.office.com<https://portal.office.com/>.
2.     Go to Settings, Org Settings, and then Reports.
3.     Disable the Display anonymous identifiers instead of names in all reports setting.


Step one is the wrong URL. The proper location is http://portal.office.com/adminPortal.

-Jon

**Comment by MaratMussabekov** [comment]
Dear @jwojan ,
please have a look at https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1677
Thank you

**Comment by nam31** [comment]
Closing via #1677 
Thank you
