### ISSUE TITLE
Link for More information is out of date

### ISSUE THREAD

**Issue by mrkeiths** [MicrosoftDocs/OfficeDocs-Support#559]
Hello,

The above appears to be out of date.  I have a customer who was looking for more information and I directed them to the following:
https://docs.microsoft.com/en-us/Exchange/policy-and-compliance/mrm/configure-managed-folder-assistant?view=exchserver-2019&viewFallbackFrom=exchonline-ww

Wondering if the link can be updated with whatever you think is most appropriate please.

Thank you,
Keith

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72346ac5-90ad-4fc8-d123-91ddc51e9d51
* Version Independent ID: 7f14e84c-8620-18a4-8aa6-92e3b24f317e
* Content: [Messages aren't moved to archive mailbox after you create retention policy - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/archive-mailboxes/message-not-moved-to-archive)
* Content Source: [Microsoft365/Compliance/archive-mailboxes/message-not-moved-to-archive.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/Compliance/archive-mailboxes/message-not-moved-to-archive.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
Closing via #1553 
Thank you
