### ISSUE TITLE
Not thrurough

### ISSUE THREAD

**Issue by kstario** [MicrosoftDocs/OfficeDocs-Support#56]
While everything on this page may be true, it's not a thorough handling of the subject. Not all events are displaying organizer name in place of subject, only some are. Some retain their subject. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b9637e-b8e3-8f65-32cb-0161ef0e9905
* Version Independent ID: 2aa831d3-1959-4992-8379-af0f743a92c1
* Content: [Resource mailbox's calendar shows the organizer's name instead of the subject - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/calendars/calendar-shows-organizer-name#feedback)
* Content Source: [Exchange/ExchangeServer/calendars/calendar-shows-organizer-name.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/calendars/calendar-shows-organizer-name.md)
* Service: **exchange-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by oobug** [comment]
@kstario Were the events that retain their subject created via a meeting request, or were they created directly on the calendar?

**Comment by nam31** [comment]
@kstario , this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@kstario We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
