### ISSUE TITLE
Useful !

### ISSUE THREAD

**Issue by AlexLaforge** [MicrosoftDocs/OfficeDocs-Support#561]
Useful, clear, and concise information !
On for one time, not such a 404 removed page from the MS Docs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b413d718-e39a-d7b3-7fb4-7478991b030b
* Version Independent ID: 24da3d76-fb19-195c-7d28-2faffb94e01a
* Content: [Description of .LDB File - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/ldb-file-description)
* Content Source: [Office/Client/access/ldb-file-description.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/ldb-file-description.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment.
