### ISSUE TITLE
There was no predecessor or successor on the parent task or the task that I was trying to make a subtask, and still get this error

### ISSUE THREAD

**Issue by drk-mtr** [MicrosoftDocs/OfficeDocs-Support#562]
Some additional troubleshooting suggestions would be useful. I eventually worked around this by duplicating an existing task, but could find no other way and there were no existing relationships that I could find, because this was attempted with a brand new task and still didn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc92b675-9d70-a0fb-d7c2-52c1622be00b
* Version Independent ID: c51c1975-6251-3f96-0ef9-0edc5586079d
* Content: [Circular Relationship Error when indenting Task - Office](https://docs.microsoft.com/en-us/office/troubleshoot/project/circular-relationship-error-when-indenting-task)
* Content Source: [Office/Client/project/circular-relationship-error-when-indenting-task.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/project/circular-relationship-error-when-indenting-task.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by Reeced40** [comment]
@drk-mtr thank you for pointing this out and helping to improve MS Docs. I'll look into it and hopefully have a solution for you soon.

**Comment by Reeced40** [comment]
@drk-mtr did this not solve your problem: "Workaround - 
To work around this problem, remove the predecessor and successor link between the tasks and then indent the task."

**Comment by drk-mtr** [comment]
Hi @Reeced40 - thanks for taking a look at this. It's a while ago so I can't remember the specifics, however the issue title suggests "There was no predecessor or successor on the parent task or the task that I was trying to make a subtask".

**Comment by nam31** [comment]
@drk-mtr Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
