### ISSUE TITLE
PersonMetadata in Unread Mail

### ISSUE THREAD

**Issue by DaveNTigard** [MicrosoftDocs/OfficeDocs-Support#563]
This page only discusses how to fix searches that return PersonMetadata. How do you get rid o PersonMetada that appears in your Unread Mail folder that is provided by Outlook? Oddly, this same unread email does not appear in the Inbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5d228b-c88c-f396-0680-1974ee3836a9
* Version Independent ID: 5d4feafb-42dd-edce-4caa-06226cbd9e12
* Content: [Outlook search folders show unexpected mail items with an empty subject - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/search/personmetadata-items#feedback)
* Content Source: [Outlook/Client/search/personmetadata-items.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/search/personmetadata-items.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by drewcifur** [comment]
Same here, and unable to modify the Criteria for the "Unread Mail" search folder - it is grayed out.

**Comment by VLG17** [comment]
@DaveNTigard If you’re using an inbuilt Search Folder, then the ‘Criteria’ button may be greyed out. You can instead [create a new Search Folder ](https://support.microsoft.com/en-us/office/use-search-folders-to-find-messages-or-other-outlook-items-c1807038-01e4-475e-8869-0ccab0a56dc5) 

From this New Search Folder window, scroll to the bottom and choose ‘Create a custom Search Folder’. Then press the ‘Choose’ button, which should have the ‘Criteria’ button available.

**Comment by nam31** [comment]
@DaveNTigard Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
