### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by aqua-d** [MicrosoftDocs/OfficeDocs-Support#565]
This does not work.  If I shrink the row height manually to be the correct size and then click "AutoFit Row Height" then it goes back to the incorrect way where it is too big.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 637418b9-c486-0de0-7f52-c79b4b3dc542
* Version Independent ID: a357675b-ee15-92a3-9c82-9abcd9d261c4
* Content: [Wrap text not adjust row height - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/wrap-text-not-adjust-row-height#feedback)
* Content Source: [Office/Client/excel/wrap-text-not-adjust-row-height.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/wrap-text-not-adjust-row-height.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@aqua-d .share the recorded video please

**Comment by RAJU2529** [comment]
@aqua-d .   I tested on office 2019 excel application, Solution works as explained in the article.

**Comment by Reeced40** [comment]
@aqua-d thank you for pointing this out. I'm investigating for you and will revert soonest.

**Comment by Reeced40** [comment]
@aqua-d thanks again for reaching out. I've just checked and the explanation in the article which has been updated works now. Please check again from your side and let me know if it's working for you. Thanks.

**Comment by nam31** [comment]
@aqua-d Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
