### ISSUE TITLE
Links are reversed

### ISSUE THREAD

**Issue by ansarik** [MicrosoftDocs/OfficeDocs-Support#566]
The 2 links in the "How is Microsoft able to help?" section are reversed. The SharePoint one points to OneDrive page and vice-versa.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2595f817-8494-b134-7099-92e6a8a28d5c
* Version Independent ID: fbf033e3-8c44-b78f-5a7f-35cea3ff7ba9
* Content: [Handling ransomware in Sharepoint Online - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/security/handling-ransomware-in-sharepoint-online)
* Content Source: [SharePoint/SharePointOnline/security/handling-ransomware-in-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/security/handling-ransomware-in-sharepoint-online.md)
* Service: **sharepoint-online**
* GitHub Login: @todmccoy
* Microsoft Alias: **v-todmc**

**Comment by Styxxy** [comment]
Submitted PR to fix it.

**Comment by RAJU2529** [comment]
@Styxxy . Checked the PR . Links are working and looks fine
