### ISSUE TITLE
Page not up to date for Windows 10

### ISSUE THREAD

**Issue by jerrycort** [MicrosoftDocs/OfficeDocs-Support#568]
This page is not up to date.  It offers solutions only through Windows 8.  I'm on Windows 10 and the registry values referenced don't seem to exist in Windows 10.  That leaves me without a solution to the problem.  So it ends up that I run into a problem, try to find a solution for it and run into another problem.  Help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 997991a1-a38a-155a-1c6d-c71a878fea4b
* Version Independent ID: 3510de34-861f-de2d-821d-6e5e2431a4dd
* Content: [This feature has been disabled by your administrator error in Microsoft Office - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/office-feature-disabled)
* Content Source: [Microsoft365/admin/access-management/office-feature-disabled.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/access-management/office-feature-disabled.md)
* Service: **sharepoint-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@jerrycort . Which office suite are you using.
Download the latest updated offive administrative templates and install in your windows machine.
I am using windows 10.  Same registry keys exists in windows 10.

**Comment by jerrycort** [comment]
Thanks for the response.  Turns out I didn’t need regedit at all.  All I needed to do was change my privacy settings.  Microsoft has to figure out an easier way to supply access to Office Help.

 

But just for future reference, it was not just a matter of the keys not existing.  The folders/headings themselves have different names from what I saw in the github help.  It looks to me like the enablehelp key(s) have been moved to a different heading and they appeared to already be set correctly…i.e. 2.

 

In answer to your question, here’s what I see as far as version goes:

 

Just shows: Subscription Product Microsoft 365

Under Word it shows: Version 2004 (Build 12730.20270 Click-to-run)

 

I’m on windows 10 pro version 1909, installed 5/31/2019, OS Build 18363.836

 

But my help is working now that I changed my security settings to allow Connected Experiences.  Which I’m going to immediately turn off as soon as I figure a solution to my word problem.

 

Again, though, thanks for the response.

 

-Jerry Cort

**Comment by RAJU2529** [comment]
@jerrycort . Thanks for the reply. Now You are an  Office support expert. congratulations keep it up.

**Comment by VLG17** [comment]
@jerrycort The article has been updated to reflect the changes between different versions.

**Comment by nam31** [comment]
Closing via #1554 
Thank you
