### ISSUE TITLE
/Saved Application State/ is not a folder within User on MacOS

### ISSUE THREAD

**Issue by GoodITCitizen** [MicrosoftDocs/OfficeDocs-Support#57]
The path is wrong and need to be corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5738299a-feb3-740e-aa42-5814f797a607
* Version Independent ID: e5373833-2a2e-0c3b-03fb-933de37c0d42
* Content: [How to do a clean uninstallation of Skype for Business on Mac - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/server-install-or-uninstall/clean-uninstallation#feedback)
* Content Source: [SkypeforBusiness/SkypeServer/server-install-or-uninstall/clean-uninstallation.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeServer/server-install-or-uninstall/clean-uninstallation.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Cloud-Writer** [comment]
The procedure has been updated with the correct commands that need to be run.
