### ISSUE TITLE
Describing the solution to this issue for me

### ISSUE THREAD

**Issue by AndyWoodruff** [MicrosoftDocs/OfficeDocs-Support#570]
This did not solve my problem, but I ran ProcMon and found it was trying to access the internet cache of another user on my machine and was therefore correctly being blocked.  I then found that this value was set incorrectly in my registry:

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders]
"Cache"="C:\Users\THEWRONGUSERNAMEWASHERE\AppData\Local\Microsoft\Windows\INetCache"

I corrected it and everything worked well after that.  This is a pretty vanilla Windows 10 box (latest Windows files are version 10.0.18362.1035), so I suspect you've got an issue on your side somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f069189a-7af4-d6df-1509-f30af7d3c01d
* Version Independent ID: df260ca7-16dd-d2f8-1de3-91e0b71f67d4
* Content: [Word could not create the work file error message when you save a document - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/word-could-not-create-the-work-file)
* Content Source: [Office/Client/word/word-could-not-create-the-work-file.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/word-could-not-create-the-work-file.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Reeced40** [comment]
@AndyWoodruff thank you for reaching out. I'll investigate and be in touch.

**Comment by Reeced40** [comment]
@AndyWoodruff Do you still think this article needs a note added? It has been updated in June this year, but I can't compare it to the previous article so please let me know if you think clarification is still needed somewhere.

**Comment by nam31** [comment]
@AndyWoodruff We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
