### ISSUE TITLE
no sso test on remote connectivity analyzer

### ISSUE THREAD

**Issue by snapshot109** [MicrosoftDocs/OfficeDocs-Support#571]
the link to the connectivity analyzer ( https://www.testconnectivity.microsoft.com/?testid=SingleSignOn ) gets redirected to ( https://www.testconnectivity.microsoft.com/tests/o365 ). an in the o365 tests there is no single sign on test contained.

please update your documentation

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2bd7ef59-8231-0e21-3052-55c1e9a7d74f
* Version Independent ID: d3863b7b-9de2-bf66-d997-92757c19f4f2
* Content: [Verwenden der Remote Verbindungs Untersuchung zur Behandlung von Problemen mit einmaligem Anmelden](https://docs.microsoft.com/de-de/office365/troubleshoot/active-directory/single-sign-on-issues)
* Content Source: [Microsoft365/admin/active-directory/single-sign-on-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/active-directory/single-sign-on-issues.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. The Single Sign-On Test
 is on the page. https://www.testconnectivity.microsoft.com/Default.aspx?testId=singleSignOn
