### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/OfficeDocs-Support#573]
[SDP 3][c6406ad7-cdd8-406e-a409-a7f0c676ccb3] 
What is this in the title?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f6f146-030e-6087-184e-f60c322cdab2
* Version Independent ID: 0ac5617f-6b81-0411-3b65-e3845314dfd2
* Content: [Office Sign-in and Authentication Diagnostic - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/diagnostic-logs/office-sign-in-and-auth-diagnostic)
* Content Source: [Microsoft365/admin/diagnostic-logs/office-sign-in-and-auth-diagnostic.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/diagnostic-logs/office-sign-in-and-auth-diagnostic.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by simonxjx** [comment]
Updated.
