### ISSUE TITLE
Reads Azure AD instead of just AD

### ISSUE THREAD

**Issue by JasonDunbar** [MicrosoftDocs/OfficeDocs-Support#574]
A simple mistake, but right before the second PowerShell example it reads 'To sync the settings by using an on-premises instance of Azure AD'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c5d2597-6e11-7c74-1af1-50dd21364593
* Version Independent ID: 4bdf974e-3408-1408-6272-96323b0ad7b6
* Content: [Set language and region settings for Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/set-language-and-region)
* Content Source: [Microsoft365/admin/access-management/set-language-and-region.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/access-management/set-language-and-region.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. Could you please illustrate the details?

**Comment by JasonDunbar** [comment]
I dohn't know what more to say really. You'll find it here: https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/set-language-and-region#for-all-office-365-services-except-exchange-online under **Synchronized identity model**

**Comment by simonxjx** [comment]
Thanks for your reply. Do you mean the article should mentions AD instead of Azure AD?

**Comment by JasonDunbar** [comment]
Unless I've hugely misunderstood that section, yes.

**Comment by nam31** [comment]
Closing via #1555 
Thank you
