### ISSUE TITLE
After method three, still have one being stubborn

### ISSUE THREAD

**Issue by slestak** [MicrosoftDocs/OfficeDocs-Support#579]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 003b3cba-164f-4443-ad85-9509a54a125b
* Version Independent ID: c237b7a5-7b05-900d-adab-df43daed3d8a
* Content: [Calendar reminders in Outlook can't be dismissed or keep reappearing - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/calendar-reminders/cannot-dismiss-outlook-calendar-reminders)
* Content Source: [Exchange/ExchangeHybrid/calendar-reminders/cannot-dismiss-outlook-calendar-reminders.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/calendar-reminders/cannot-dismiss-outlook-calendar-reminders.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. Could you please try the methods on [Set or remove reminders]
(https://support.office.com/article/7a992377-ca93-4ddd-a711-851ef3597925)?

**Comment by slestak** [comment]
Thank you for reaching out. I'm watching the issue. Yesterday's instance appears to have subsided.  My company is just converting from gw to o365 so we are all learning new ways to foul up calendar management.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by simonxjx** [comment]
Thanks for your reply. If you have any further question, you can also contact support via https://support.office.com/outlook.
