### ISSUE TITLE
"To resolve this issue," don't use the new product we launched

### ISSUE THREAD

**Issue by AmyWaggoner** [MicrosoftDocs/OfficeDocs-Support#58]
This isn't a solution. Microsoft has pushed metadata, then "modernizes" and takes away the most obvious and fool-proof way to collect that metadata. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79cfb5dc-904f-0a2b-aebc-dd6ef7feb6f1
* Version Independent ID: eba26dd2-3b87-4151-cece-c1e3e0793099
* Content: [Upload a file to a library using the new experience version - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/lists-and-libraries/upload-file-using-new-experience?redirectSourcePath=%252fen-us%252farticle%252fyou-aren-t-prompted-for-required-information-when-you-upload-a-file-to-a-sharepoint-online-library-using-the-new-experience-version-bf528653-2cc2-4704-a6ee-0e186abd2497#feedback)
* Content Source: [SharePoint/SharePointOnline/lists-and-libraries/upload-file-using-new-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/lists-and-libraries/upload-file-using-new-experience.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by vidarak** [comment]
When will this be fixed?

**Comment by msbemba** [comment]
@AmyWaggoner Thank you for your feedback. I Understand your concern, however, this platform is set up to fix issues in documents. To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).

Thanks
Sri

**Comment by nam31** [comment]
@AmyWaggoner We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
