### ISSUE TITLE
Screenshots and information missing from current version

### ISSUE THREAD

**Issue by TrixM** [MicrosoftDocs/OfficeDocs-Support#581]
The current version of this document omits information that helps to determine whether `SupportMultipleDomain` has been enabled on the federated O365 domain. 

The [original archived blog post](https://docs.microsoft.com/en-us/archive/blogs/abizerh/supportmultipledomain-switch-when-managing-sso-to-office-365) includes two screenshots (the 2nd and 3rd images on the page) that makes it clear what the text is trying to say.

The text itself is not very clear, and this is exacerbated by formatting that was lost during the conversion to the new documentation site. 

- - -
**Additional note**

It's disappointing that there is no link back to the original article and that the original author's identity (presumably Abizer Hazrat) has been obscured. I realise it's true of most of these converted blog articles. It's another example of one of the poorer aspects of how Microsoft has handled the migration of the old PFE/tech blogs, many of which still have useful information. The other major issue is the _huge_ number of broken links from support forums and other articles/blog posts.

I feel if an old blog is republished with substantially the same content on the official docs.microsoft.com site, it should be properly credited and linked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 533377e9-f90e-b645-cb9a-e52b9879976c
* Version Independent ID: 9bbbc80e-6e40-7184-6ff2-b603d981a9ed
* Content: [SupportMultipleDomain switch when managing SSO to Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/supportmultipledomain-switch-when-manage-sso)
* Content Source: [Microsoft365/admin/administration/supportmultipledomain-switch-when-manage-sso.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/supportmultipledomain-switch-when-manage-sso.md)
* Product: **office 365**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by nam31** [comment]
@TrixM this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@TrixM We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
