### ISSUE TITLE
Where is the Fixit  for method 2 ?

### ISSUE THREAD

**Issue by mtlgirl** [MicrosoftDocs/OfficeDocs-Support#583]
At method 2, it alludes to click a download button to obtain the Fixit. I cannot find that button on this page. There is a chainlink that appears to the far right of that Title method 2 but it only reloads the current page.
https://docs.microsoft.com/en-us/office/troubleshoot/miscellaneous/incompatibilities-between-office-and-adob?source=docs#method-2-use-the-fix-it-to-automatically-disable-acrobat-pdfmaker-office-com-add-in

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. The Fix-it links are added.
