### ISSUE TITLE
Method 5 causes Office not to launch

### ISSUE THREAD

**Issue by wmachanik** [MicrosoftDocs/OfficeDocs-Support#584]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98e24831-584c-77ea-d657-3161a5474604
* Version Independent ID: 0877ebb8-9f8f-92c4-b966-7855de7fac39
* Content: [How to troubleshoot crashing and not responding issues with Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/crashing-issues-with-excel)
* Content Source: [Office/Client/excel/crashing-issues-with-excel.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/crashing-issues-with-excel.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. Can you try to select some Office related startup to check if Office can be launched?

**Comment by wmachanik** [comment]
I went an enabled all Microsoft services. And excel still won’t launch. Which ones are there otherwise?

Warren Machanik (Private)

**Comment by wmachanik** [comment]
Hi I logged a ticket on the forum and it seems other are having the issue - see this ticket: https://answers.microsoft.com/en-us/msoffice/forum/msoffice_excel-mso_win10-mso_365hp/excel-365-crashing-when-i-open-existing-files/f4723b92-8ebc-4d7d-9a20-52267387b3af?tm=1591016900777

**Comment by simonxjx** [comment]
You can check if other account has the same issue.

**Comment by wmachanik** [comment]
Ended up just moving my cloud files to a different folder and resyncing - fixed the isse

**Comment by nam31** [comment]
@wmachanik does this mean that the issue that you raised initially is resolved now?

**Comment by wmachanik** [comment]
@nam31 I fixed it by moving all the cloud files to a different folder, took a while to sync.

**Comment by nam31** [comment]
@wmachanik Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your issue seems to be resolved. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
