### ISSUE TITLE
Win32API_PtrSafe.TXT has bugs

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/OfficeDocs-Support#585]
The Win32API_PtrSafe.TXT is very helpful, except that it has bugs. I had VBA code working for years but had to adapt for 64-bit and took ```declare```s from this file. I started getting crashes and had to find help on StackOverflow.

One example:

```vb
Declare PtrSafe Function MultiByteToWideChar Lib "kernel32" Alias "MultiByteToWideChar" ( _
    ByVal CodePage As Long, _
    ByVal dwFlags As Long, _
    ByVal lpMultiByteStr As String, _
    ByVal cchMultiByte As Long, _
    ByVal lpWideCharStr As String, _
    ByVal cchWideChar As Long _
    ) As Long
```

At best, that returns wrong results; at worst, leads to crashes. The following works (with calls using ```StrPtr()``` for the ```lpWideCharStr``` argument):

```vb
Declare PtrSafe Function MultiByteToWideChar Lib "kernel32" ( _
  ByVal CodePage As Long, _
  ByVal dwFlags As Long, _
  ByVal lpMultiByteStr As LongPtr, _
  ByVal cchMultiByte As Long, _
  ByVal lpWideCharStr As LongPtr, _
  ByVal cchWideChar As Long _
  ) As Long
```

Similarly, this doesn't return correct results:

```vb
Declare PtrSafe Function lstrlen Lib "kernel32" Alias "lstrlenA" (ByVal lpString As String) As Long
```

This does:

```vb
Declare PtrSafe Function lstrlenA Lib "kernel32" (ByVal lpString As LongPtr) As Long
```

There seems to be a pattern of bugs in which ```As String``` is used
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 850e6d40-20b8-85c9-2c19-7bf1ff1e7206
* Version Independent ID: 2959843b-b0e7-17b5-ece2-c0bd2bb3bc59
* Content: [Win32API_PtrSafe with 64-bit Support - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office/win32api_ptrsafe-with-64-bit-support)
* Content Source: [Office/Client/office/win32api_ptrsafe-with-64-bit-support.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office/win32api_ptrsafe-with-64-bit-support.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Reeced40** [comment]
@PeterConstable thank you for pointing this out. I'm looking into it.

**Comment by Reeced40** [comment]
@PeterConstable sorry for the delay in responding. I'm sure the bugs have been fixed and I also see the article has been updated. Please can you confirm from your side. I work on the writing/editing side of MS Docs and looking through the article I'm not seeing any of these commands reflecting. Are you suggesting adding a note with the correct commands to help other users. Please let me know and I'll look into it further.

**Comment by nam31** [comment]
@PeterConstable We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

**Comment by PeterConstable** [comment]
These commands are not listed directly in the article, but rather are in the Win32API_PtrSafe.txt file that can be downloaded from the link mentioned in the article: <https://www.microsoft.com/download/details.aspx?familyid=035b72a5-eef9-4baf-8dbc-63fbd2dd982b>

**Comment by PeterConstable** [comment]
@Reeced40 I added a comment, but I don't have access to re-open the issue.

**Comment by Reeced40** [comment]
@PeterConstable thank you for pointing this out. Seeing that the link is in the article with the download option, do you still think there are any changes needed to this document? Are there still bugs?

**Comment by PeterConstable** [comment]
The bugs were not in the article, but rather in the Win32API_PtrSafe.TXT file that one gets via the download link. Has that been debugged and revised?

**Comment by Reeced40** [comment]
@PeterConstable okay, thanks for clearing that up. It seems fine now as I've just downloaded it this side and it worked without any issues. Please let me know if you're still experiencing any issues your side and I can ask one of the authors or someone else on the support side to assist.

**Comment by PeterConstable** [comment]
The msi download works as expected, and the msi works as expected. But these are not the issue. Rather, the issue I reported was with the content of the Win32API_PtrSafe.TXT file that is installed by the msi. This contains declarations that VBA developers would use in the VBA projects, and the problem is with some of the declarations contained in the file. As I said, earlier, at best they don't work, and at worst they lead to Office crashing. The specific declarations with this issue that I mentioned have not been fixed; there may be additional declarations that have this.

This probably needs to go to an Office engineer to fix the bugs in the declarations in Win32API_PtrSafe.TXT.

**Comment by Reeced40** [comment]
@PeterConstable thanks again for your valuable input. I'll direct it to the relevant team members to look into it and resolve.
