### ISSUE TITLE
Need to use a different account to perform the fix

### ISSUE THREAD

**Issue by Matt-IgniteSolutions** [MicrosoftDocs/OfficeDocs-Support#587]
Hi there,

It makes sense in hindsight, but you CAN'T use the same delegated partner account that's having the problem to perform the fix. 

IE: 
- my account is having this problem with one of my customer's SPO tenants. The fix is to log into the tenant via PS and remove my account from the list of External Accounts. No worries.
- However, when I try to log in with my account via PS, I receive a 401 Unauthorized error. 
- Because this is the only Admin account I have in the customer tenant (they control their original Global Admin user account), there's no way for me to fix the problem. I will need to ask them to perform the fix for me.

This makes perfect sense, but I still held out hope that the Connect-SPOService cmdlet would evaluate the group membership differently to the web UI, and would allow the partner account to connect through. It may be worth adding a clarification to the article to state that you will need to use a different account from that which is experiencing the problem, to perform the fix.

Kind regards,
Matt
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e427056f-d18c-a6ee-ab7a-ffc8dbd91b04
* Version Independent ID: d9c614f9-b074-0387-703c-c254d25b1ad2
* Content: [External sharing is disabled for the site when a delegated partner administrator tries to access a client's SharePoint Online Admin Center - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sharing-and-permissions/troubleshoot-error-when-tries-to-access-center)
* Content Source: [SharePoint/SharePointOnline/sharing-and-permissions/troubleshoot-error-when-tries-to-access-center.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sharing-and-permissions/troubleshoot-error-when-tries-to-access-center.md)
* Service: **sharepoint-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by get-itips** [comment]
Thanks for reporting, will improve the article @Matt-IgniteSolutions
