### ISSUE TITLE
How to handle external table is not in the expected format while import Excel Table into Access.

### ISSUE THREAD

**Issue by SinhaRS-IND** [MicrosoftDocs/OfficeDocs-Support#588]
May be conflicting with the connection string syntax, or the Format of the Excel file is not compatible with other end. Use Xlsx.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 080ab28c-ed48-e340-a119-04fe2f78dbfb
* Version Independent ID: fa9329b5-fbd5-0995-78c3-42f2d633f90b
* Content: [Access errors during import or export to Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/import-export-access-to-excel)
* Content Source: [Office/Client/access/import-export-access-to-excel.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/import-export-access-to-excel.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Reeced40** [comment]
@SinhaRS-IND Thank you for reaching out and helping to improve MS Docs. I'll look into this and revert soon.

**Comment by Reeced40** [comment]
@SinhaRS-IND I see this article has been updated since you raised the issue. Here is a note from the article regarding the limit for the size of file for import - "Access encounters Import/Export errors when working with Excel *.xls files that have cells, which contain more than 8224 bytes of data." Please let me know if this helps provide a solution.

**Comment by nam31** [comment]
@SinhaRS-IND We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
