### ISSUE TITLE
I faced the same issue while copying the data from a spreadsheet

### ISSUE THREAD

**Issue by ShivKumarBS** [MicrosoftDocs/OfficeDocs-Support#589]
I faced the same issue while copying the data from a spreadsheet into another, by using a macro. The source spreadsheet had the autofilter ON. I removed the filter and tried. It worked without any errors.

So, this could also be one or the causes for the error.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 807146b2-066a-a0e8-f363-ae7fafd8871a
* Version Independent ID: c1a5a983-1744-556a-b81a-d997bc729db3
* Content: [How to troubleshoot available resources errors in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/available-resources-errors)
* Content Source: [Office/Client/excel/available-resources-errors.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/available-resources-errors.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@ShivKumarBS . thanks for the new troubleshooting solution, Your solution must be added in this article. I hope the author will add a new solution to this article

**Comment by Reeced40** [comment]
@ShivKumarBS thank you for letting us know and improving MS Docs.  At a glance I see the article has been updated this year so it might already have your suggestions noted. I'll investigate and revert soonest.

**Comment by Reeced40** [comment]
@ShivKumarBS we are trying to determine the exact cause of the issue so we can update the document more accurately. Please see this link about incorrect VBA code which may also cause the issue and let me know what you think - https://stackoverflow.com/questions/33635128/excel-cannot-complete-task-with-available-resources. Thanks again for your valuable input.

**Comment by nam31** [comment]
@ShivKumarBS We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
