### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by rdobbsokc** [MicrosoftDocs/OfficeDocs-Support#59]
What product ID do I use for standard Office 2013 volume license to download for creating an APP-V package for word and excel only? I also need to know if I can create a separate package for Access 2013 with the standalone volume licenses if so, what product ID would I use for that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b0e3f06-bd25-2d92-228b-9b5e1cf47ff3
* Version Independent ID: c8a6ff08-5acf-adcb-855f-5eadce72f7ba
* Content: [Product IDs that are supported by the Office Deployment Tool for Click-to-Run - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/product-ids-supported-office-deployment-click-to-run?redirectSourcePath=%252fen-us%252farticle%252f77654e77-aaeb-4ed6-84eb-1d8b0e086590#feedback)
* Content Source: [Microsoft365/admin/administration/product-ids-supported-office-deployment-click-to-run.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/product-ids-supported-office-deployment-click-to-run.md)
* Service: **o365-solutions**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **stevhord**

**Comment by jlriesco** [comment]
What you are is trying to do is not possible. AppV only works with C2R starting with Office 2013 and standalone 2013 VL apps are only MSI, not C2R. 

Here is an article about how to deploy Office with AppV, [https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/appv-v5/deploying-microsoft-office-2013-by-using-app-v](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/appv-v5/deploying-microsoft-office-2013-by-using-app-v). 

I hope this helps.
