### ISSUE TITLE
You must accept the Office End User License Agreement every time that you start an Office program

### ISSUE THREAD

**Issue by tcacharjee** [MicrosoftDocs/OfficeDocs-Support#591]
[I have tried this method several times exactly the way it was mentioned in the website. However, it did not work out. Therefore, I uninstalled office 365 and reinstalled office 365 again while logging  in 365 website. Finally it was solved. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e55100-6734-a9e5-fcdb-85a9b4c415cb
* Version Independent ID: 41e7554f-6725-76fb-a9b6-1fb1ed383f2a
* Content: [Office End User License Agreement always appears - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office/office-end-user-license-agreement)
* Content Source: [Office/Client/office/office-end-user-license-agreement.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office/office-end-user-license-agreement.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@tcacharjee . we need to choose  16.0  for Microsoft office 365 , office 2016 and office 2019

**Comment by simonxjx** [comment]
Thanks for your comment. The steps in this article apply to Office 2010.
