### ISSUE TITLE
office 365 build by the version16.0 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-Support#592]
we need to choose 16.0,  instead of  14.0, please correct it.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e55100-6734-a9e5-fcdb-85a9b4c415cb
* Version Independent ID: 41e7554f-6725-76fb-a9b6-1fb1ed383f2a
* Content: [Office End User License Agreement always appears - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office/office-end-user-license-agreement)
* Content Source: [Office/Client/office/office-end-user-license-agreement.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office/office-end-user-license-agreement.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. Please notice that the article applies to Office 2010.
