### ISSUE TITLE
Screenshot update

### ISSUE THREAD

**Issue by O365scripts** [MicrosoftDocs/OfficeDocs-Support#593]
Are we able to provide recent screenshots instead of Outlook 2010 ones please?
I can gladly provide them if needed.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 660e3bde-f546-4e40-033d-e29cdb40222f
* Version Independent ID: 565146bb-2414-80a6-8755-a00f752d410a
* Content: [Users can't see free/busy information after a mailbox is moved to Office 365 - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/move-mailboxes/cannot-see-free-busy-information)
* Content Source: [Exchange/ExchangeOnline/move-mailboxes/cannot-see-free-busy-information.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/move-mailboxes/cannot-see-free-busy-information.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@O365scripts Thank you for your feedback. I'll collect the screenshots and update the document.

Thanks
Sri
