### ISSUE TITLE
Applies to

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/OfficeDocs-Support#596]
Why is this item listed in OneDrive for Business troubleshooting when it says
Applies to:
SharePoint Online, SharePoint Server 2013

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a10b6af1-f1bf-add1-caa1-4b59a4bc0f92
* Version Independent ID: 69802e35-7601-da14-ecbb-1420916bb58f
* Content: [Near-duplicate items aren't listed in SharePoint Online or SharePoint Server 2013 on-premises search results - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/search/near-duplicate-items-are-not-listed-in-search-results)
* Content Source: [SharePoint/SharePointOnline/search/near-duplicate-items-are-not-listed-in-search-results.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/search/near-duplicate-items-are-not-listed-in-search-results.md)
* Service: **sharepoint-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by todmccoy** [comment]
Fixed -- thank you for pointing this out.
