### ISSUE TITLE
Improving the example script

### ISSUE THREAD

**Issue by stephent122** [MicrosoftDocs/OfficeDocs-Support#597]
[Enter feedback here]
Currently the sample script from Microsoft has the following line.

$OutFileName = 'AuditLogResults$Date.csv'

This results in an output file literally called AuditLogResults$Date.csv whereas I think the intention was to use the value inside $Date rather than the word.

If I am reading the script correctly then the code should look more like this;

$OutFileName = 'AuditLogResults' + $Date + '.csv'

A couple of lines later you have; 

'Posting results to file : $OutFileName'

This would be better as;

'Posting results to file:'  $OutFileName

Perhaps someone could take a look. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a93c78d-ed18-2fda-d8bb-9f60f64fbc0f
* Version Independent ID: a79b1742-f841-c8a5-71f6-1c1dda533d6a
* Content: [How to use mailbox audit logs in Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/audit-logs/mailbox-audit-logs)
* Content Source: [Microsoft365/compliance/audit-logs/mailbox-audit-logs.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/compliance/audit-logs/mailbox-audit-logs.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@stephent122 The script has been updated and double quotes are now used for the lines you mentioned,  thus appending the file with the day's date which is the intended behavior.

**Comment by VLG17** [comment]
@stephent122 Can you check and let us know if you need anything else added?

**Comment by stephent122** [comment]
I already made the changes and tested them. I wouldn't have raised the issue otherwise.

Just wanted to help out.

**Comment by nam31** [comment]
@stephent122 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
