### ISSUE TITLE
Outlook?

### ISSUE THREAD

**Issue by DuShruikan** [MicrosoftDocs/OfficeDocs-Support#599]
I believe Outlook is an exception to this. I note the document is tagged with all of Microsoft Office but my testing has shown this issue to be caused by links in Word, Excel and PowerPoint but the same link works in Outlook.

It'd be great if the article could have some additional information about why this may be the case. I can only assume Outlook handles links differently.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb4e2409-fde8-8b1b-4dca-01bb6759b006
* Version Independent ID: fd463b22-33c1-a726-6a63-62ee892c5df3
* Content: [Issues when you click a hyperlink to SSO Web site - Office](https://docs.microsoft.com/en-au/office/troubleshoot/office/click-hyperlink-to-sso-website)
* Content Source: [Office/Client/office/click-hyperlink-to-sso-website.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office/click-hyperlink-to-sso-website.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Reeced40** [comment]
@DuShruikan thank you for your help in pointing this out. I'll investigate and see what changes are necessary for this article.

**Comment by Reeced40** [comment]
@DuShruikan I know it's been a while since you raised this issue, but to help other users please can you confirm if its still a case where Outlook is an exception. I also see the article has been updated in May this year with a couple of workarounds. Please let me know if you still need assistance.

**Comment by nam31** [comment]
@DuShruikan We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
