### ISSUE TITLE
Missing information on linked page

### ISSUE THREAD

**Issue by pencer-io** [MicrosoftDocs/OfficeDocs-Support#600]
In this document:

A recent change (made in October 2018) requires one additional step when you configure Exchange on-premises support. Make sure that you follow step 6 in the "Phone System with on-premises environments" section of this document.  The email item class is stripped when it's delivered through SMTP. To prevent this behavior from occurring, you must set up the connector correctly. The Skype for Business and Teams clients show voicemails only if the class is correct.

The link to this: https://docs.microsoft.com/microsoftteams/set-up-phone-system-voicemail?toc=/skypeforbusiness/toc.json&bc=/skypeforbusiness/breadcrumb/toc.json

Does not contain the information. There is no section 6 titled "Phone System with on-premises environments".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef6fd529-a369-9afd-ce21-4cb8b415f6c4
* Version Independent ID: 9e7c3225-ddba-1af5-c2f0-ab3da394f02f
* Content: [Voicemail messages are not delivered in Teams or Skype for Business client - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/hybrid-phone-system/voicemails-not-delivered)
* Content Source: [SkypeforBusiness/SkypeHybrid/hybrid-phone-system/voicemails-not-delivered.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeHybrid/hybrid-phone-system/voicemails-not-delivered.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The mentioned section was removed from the referenced article. The article is updated.
