### ISSUE TITLE
DEVENV does not exist or can't be found

### ISSUE THREAD

**Issue by shadybrady** [MicrosoftDocs/OfficeDocs-Support#601]
Instructions from Visual Studio to execute this command to reset user data.  Command not found when in the directory as specified.  Perhaps there needs to be a comment or two saying where the command can be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 975c1291-1a98-75a2-4cff-6dde6b8592b8
* Version Independent ID: 6069e03d-05d8-a750-0922-6bfba198bca4
* Content: [Unable to cast COM object when exporting to Excel from Team Explorer 2008 - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/team-explorer-export-fails)
* Content Source: [Office/Client/excel/team-explorer-export-fails.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/team-explorer-export-fails.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by lindspea** [comment]
@shadybrady thank you for pointing this out and helping improve MS docs. I'm looking into it.

**Comment by lindspea** [comment]
@shadybrady I see the article has been updated recently and there is a resolution at the bottom of the document with regards to this. Please let me know if it works. If you have any other suggestions please let me know.

**Comment by shadybrady** [comment]
> @shadybrady I see the article has been updated recently and there is a resolution at the bottom of the document with regards to this. Please let me know if it works. If you have any other suggestions please let me know.

Well, it has been a year and I am well past that now.  I have to assume that the fix is good as I just don't have the time to check it out now and frankly,  can't even remember off the top of my head which module I was working on at the time.  Thanks.
