### ISSUE TITLE
Incorrect Content

### ISSUE THREAD

**Issue by jpalarchio** [MicrosoftDocs/OfficeDocs-Support#602]
We should be referencing "Live Events", not "broadcast meetings".

Also, we support sharing of System Audio in Live Events now, you just have to check the box.

https://support.microsoft.com/en-us/office/share-system-audio-in-a-teams-meeting-or-live-event-dddede9f-e3d0-4330-873a-fa061a0d8e3b

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceb0f3b9-c9c2-1723-2ed2-d9687a1c35ae
* Version Independent ID: 17d8328f-63ed-0538-c023-59e47500c8d0
* Content: [Cannot hear sound when sharing content during a Teams meeting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/known-issues/no-audio-when-sharing-content-in-meeting)
* Content Source: [Teams/known-issues/no-audio-when-sharing-content-in-meeting.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/known-issues/no-audio-when-sharing-content-in-meeting.md)
* Service: **msteams**
* GitHub Login: @todmccoy
* Microsoft Alias: **v-todmc**

**Comment by todmccoy** [comment]
Thanks for the heads up, Joe. The article has been updated.

**Comment by todmccoy** [comment]
Just FYI, the content was updated to include information about sharing sound.
