### ISSUE TITLE
The links to the Microsoft fix in this are broken!

### ISSUE THREAD

**Issue by leob48105** [MicrosoftDocs/OfficeDocs-Support#604]
I'm trying to install SharePoint Server 2012 on a Windows 2012R2 server. It can't get pass the verification screen. The links on the page to the fix are broken, and can't uninstall .NET Framework on a Win2012R2 server. Please fix the links!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f467ff86-48f6-82ea-817b-7d19b7b8ad02
* Version Independent ID: 3a81bc47-e572-4e7d-70a3-2706219d6657
* Content: [SharePoint 2013 or Project Server 2013 Setup error if the .NET Framework 4.6 is installed - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/installation-and-setup/setup-error-if-.net-framework-4.6-is-installed)
* Content Source: [SharePoint/SharePointServer/installation-and-setup/setup-error-if-.net-framework-4.6-is-installed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointServer/installation-and-setup/setup-error-if-.net-framework-4.6-is-installed.md)
* Service: **sharepoint-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@simonxjx . issue is conformed by me, after checking the links.

**Comment by simonxjx** [comment]
Checking

**Comment by bowen-liu** [comment]
@RAJU2529 @simonxjx 
These are NOT the correct links. The original links points to a zip of a single file that needs to be patched, not the download link to the entire service packs!

**Comment by simonxjx** [comment]
Thanks for your comments. The links are updated and available now.
