### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by andrewshilliday** [MicrosoftDocs/OfficeDocs-Support#607]
The like referenced on the page (https://aka.ms/skypemeetingjoin-ios) does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f262486e-9853-f12f-7389-34518d94b96c
* Version Independent ID: ec0c5b59-305c-04ad-3591-a3cd1e5c92e9
* Content: [Can't join a meeting on iOS 9.2 and later - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/server-meetings/cant-join-meeting-on-ios-9-2)
* Content Source: [SkypeforBusiness/SkypeServer/server-meetings/cant-join-meeting-on-ios-9-2.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeServer/server-meetings/cant-join-meeting-on-ios-9-2.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@simonxjx . Broken link is conformed by me also. i could not able to find an alternative link , so please add a new link or delete note section

**Comment by simonxjx** [comment]
Checking.
