### ISSUE TITLE
Is this the correct link?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/OfficeDocs-Support#608]
For more information about the unique security scopes in the list or library, see SharePoint Online Limits.
However in that link, I did not find anything that mentions "security scopes".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1adb9746-e32d-8231-10c2-2e162d640c08
* Version Independent ID: d7d51755-a11e-2d39-e2cd-485939cb02ca
* Content: [Unable to reach the server right now - SharePoint](https://docs.microsoft.com/en-us/SharePoint/troubleshoot/performance/share-file-unable-reach-the-server)
* Content Source: [SharePoint/SharePointOnline/performance/share-file-unable-reach-the-server.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/performance/share-file-unable-reach-the-server.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The article was updated. Here is the information about security scopes.

Unique security scopes per list or library - 5,000. For large lists, design to have as few unique permissions as possible.
