### ISSUE TITLE
Not sure if this is redundant or if I'm wrong

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/OfficeDocs-Support#609]
Verify the site's search visibility options at the following location:
<site_name>/_layouts/srchvis.aspx
Make sure that the Allow this web to appear in search results option is selected.

I tested, this URL is the same as Search and Offline Availability mentioned above.
And what's "Allow this web to appear"? Should it be "Allow this site to appear"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03fc1c37-d042-bcc4-5d3e-31ac9f4dc500
* Version Independent ID: 0375882c-42a3-b271-cfa2-51029d6bfb93
* Content: [Search results missing in SharePoint Online - SharePoint](https://docs.microsoft.com/en-us/SharePoint/troubleshoot/search/search-results-missing)
* Content Source: [SharePoint/SharePointOnline/search/search-results-missing.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/search/search-results-missing.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by get-itips** [comment]
Thanks for reporting! will improve the article @hwkwicre
