### ISSUE TITLE
The solution is identitcal to the problem

### ISSUE THREAD

**Issue by wildebaard** [MicrosoftDocs/OfficeDocs-Support#61]
As the title says: the provided solution is a repetition of the stated problem and thus not a solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4df31f-1c3e-f410-bf33-4504db48288f
* Version Independent ID: 8a12043f-e790-6dff-3ad8-33dfa3376e12
* Content: [Site doesn't use the site theme for the Office 365 top navigation bar - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/sites/top-navigation-bar-not-use-site-theme#feedback)
* Content Source: [SharePoint/SharePointOnline/sites/top-navigation-bar-not-use-site-theme.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sites/top-navigation-bar-not-use-site-theme.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by claudialake** [comment]
Thanks for catching this! @simonxjx

**Comment by simonxjx** [comment]
Solution is updated.
