### ISSUE TITLE
Vraag/opmerking over PersonMetadata

### ISSUE THREAD

**Issue by Harm-Bennik** [MicrosoftDocs/OfficeDocs-Support#610]
Is er een permanente oplossing hiervoor beschikbaar of in de maak? Om gelijk alle ongelezen mails van submappen onzichtbaar te maken gaat een beetje voorbij aan het nut en functie van deze zoekmap.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 8b5d228b-c88c-f396-0680-1974ee3836a9
* Version Independent ID: 5d4feafb-42dd-edce-4caa-06226cbd9e12
* Content: [Outlook-zoekmappen tonen onverwachte e-mailitems met een leeg onderwerp - Outlook](https://docs.microsoft.com/nl-nl/outlook/troubleshoot/search/personmetadata-items)
* Content Source: [Outlook/Client/search/personmetadata-items.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/search/personmetadata-items.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@Harm-Bennik Thank you for your feedback. The PersonMetadata folder and the items that are created in it will be removed from the service in the future (Not in the roadmap yet), Currently, we only have the workaround available for this scenario.

The document will be updated once there is a permanent fix.

Thanks
Sri

**Comment by nam31** [comment]
@Harm-Bennik Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
