### ISSUE TITLE
Should this apply to Teams and OneDrive as well?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-Support#611]
While testing this, I can get the different default views working in SharePoint.  However, it doesn't appear to work in Teams at all.  For the same document library in a Teams channel, the new default views per folder don't appear to work--you have to manually change the view.  Is that by design? Or should the default views per folder setup in SharePoint also work when accessing the folders in Teams and/or OneDrive?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93b7fa94-4918-3789-1392-6c88a4abff1f
* Version Independent ID: 8ed491fb-d6bd-47b7-06d1-d01ba7b94e1b
* Content: [Per-location view settings don't work at the folder level - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/lists-and-libraries/per-location-view-settings-fail-working)
* Content Source: [SharePoint/SharePointOnline/lists-and-libraries/per-location-view-settings-fail-working.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/lists-and-libraries/per-location-view-settings-fail-working.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by ThomasVandePol** [comment]
I'm experiencing the same issue. It appears the "per location view" is not working in the modern view and thus not in Teams either.

**Comment by VLG17** [comment]
@Canis-Lupis According to [this UserVoice thread](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/18584719-file-column-sort-order) this issue has been addressed. Are you still seeing it?

More details [here](https://support.microsoft.com/en-us/office/create-a-custom-view-of-a-document-library-8f6b08e0-a9a0-4232-9b9b-b374a2ad3da7?ui=en-US&rs=en-US&ad=US) and [here](https://support.microsoft.com/en-us/office/create-change-or-delete-a-view-of-a-list-or-library-27ae65b8-bc5b-4949-b29b-4ee87144a9c9?ui=en-US&rs=en-US&ad=US).

**Comment by nam31** [comment]
@Canis-Lupis Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
