### ISSUE TITLE
mac tho?

### ISSUE THREAD

**Issue by calebrauxa** [MicrosoftDocs/OfficeDocs-Support#613]
what about for MAc? please help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8675d7c-0870-b2c1-f442-867164e2949d
* Version Independent ID: 3cc6eaf5-37fa-b835-4d81-d3a83e9922bc
* Content: [Control the startup message about updating linked workbooks - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/control-startup-message)
* Content Source: [Office/Client/excel/control-startup-message.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/control-startup-message.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by lindspea** [comment]
@calebrauxa thank you for reaching out. I'll have an answer for you soon - just looking into it.

**Comment by lindspea** [comment]
@calebrauxa let me know if this Microsoft answers article helps at all - https://answers.microsoft.com/msoffice/forum/msoffice_excel-mso_mac-mso_mac2011/excel-mac-2011-auto-update-of-links-between/dc69c175-dcc9-4dda-a106-e30255a56ac3

**Comment by nam31** [comment]
@calebrauxa We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
