### ISSUE TITLE
Link to the exchange troubleshooter PS script is no longer functional

### ISSUE THREAD

**Issue by dutch2005** [MicrosoftDocs/OfficeDocs-Support#614]
[Enter feedback here]
Link to the exchange troubleshooter is no longer functional

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 372aa4a8-6433-ad6e-eece-15a8d9f7cb0f
* Version Independent ID: aa97ea60-52e0-5e17-bd9d-b29d7f2ef789
* Content: [Connecting to the remote server failed when start Management Shell or Console - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/connecting-remote-server-failed)
* Content Source: [Exchange/ExchangeServer/administration/connecting-remote-server-failed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/administration/connecting-remote-server-failed.md)
* Service: **exchange-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The links in the article are updated.
