### ISSUE TITLE
Is that a typo or did I not understand it correctly?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/OfficeDocs-Support#615]
When a delegated partner administrator tries to access the SharePoint Online Admin Center site collection of one of the partner's clients in Microsoft SharePoint Online,

What is "the SharePoint Online Admin Center site collection"? I thought the admin center isn't a site collection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e427056f-d18c-a6ee-ab7a-ffc8dbd91b04
* Version Independent ID: d9c614f9-b074-0387-703c-c254d25b1ad2
* Content: [External sharing is disabled for the site when a delegated partner administrator tries to access a client's SharePoint Online Admin Center - SharePoint](https://docs.microsoft.com/en-us/SharePoint/troubleshoot/sharing-and-permissions/troubleshoot-error-when-tries-to-access-center)
* Content Source: [SharePoint/SharePointOnline/sharing-and-permissions/troubleshoot-error-when-tries-to-access-center.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sharing-and-permissions/troubleshoot-error-when-tries-to-access-center.md)
* Service: **sharepoint-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by get-itips** [comment]
Hello @hwkwicre how are you?
I can confirm that the sentence has been improved in this [commit](https://github.com/MicrosoftDocs/OfficeDocs-Support/commit/5a760a1e6ee4b341fb1154f84760370b0ab7652c).
Thank you for reporting!

**Comment by nam31** [comment]
@hwkwicre We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
