### ISSUE TITLE
Example images

### ISSUE THREAD

**Issue by BinnTech** [MicrosoftDocs/OfficeDocs-Support#62]
The 'Following Figure' comparing the output of ExcludeHTTPSAutoDiscoverDomain being toggled is the same image twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4758d9-52a3-67e9-8e60-b7e503605f38
* Version Independent ID: 57c2f2b7-bceb-c884-495a-39d77d49b6bb
* Content: [Unexpected Autodiscover behavior if settings under the \Autodiscover key - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/unexpected-autodiscover-behavior#feedback)
* Content Source: [Microsoft365/admin/administration/unexpected-autodiscover-behavior.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/unexpected-autodiscover-behavior.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Image is updated.
