### ISSUE TITLE
Thanks for the registry keys

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-Support#620]
just now i added those registry keys for office 2019 suite. Thanks for the authors
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ba35215-9fe9-d08d-a871-112e9253c4ee
* Version Independent ID: ea5dac49-e6d1-4920-38dd-36196f3da051
* Content: [How to enable Microsoft 365 Apps for enterprise ULS logging - Office](https://docs.microsoft.com/en-us/office/troubleshoot/diagnostic-logs/how-to-enable-office-365-proplus-uls-logging)
* Content Source: [Office/OfficeExperts/diagnostic-logs/how-to-enable-office-365-proplus-uls-logging.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/diagnostic-logs/how-to-enable-office-365-proplus-uls-logging.md)
* Service: **o365-solutions**
* GitHub Login: @todmccoy
* Microsoft Alias: **ericspli**

**Comment by nam31** [comment]
@RAJU2529 The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content
Thank you.

**Comment by RAJU2529** [comment]
@nam31 . no I didn't faced any issues. Registry keys are mentioned in this article is working
