### ISSUE TITLE
Are the steps right?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/OfficeDocs-Support#621]
"Search for and select the user account experiencing the issue. Select OK in the dialog box that opens."
After I search for and select an user account, no dialog box pops out and there isn't an OK for me to select.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16530c0c-c037-3b4e-1850-48bb609d7ae6
* Version Independent ID: 9a136221-2699-2088-1d12-6db7092f6edb
* Content: [Troubleshoot OneDrive for Business sites that stop at provisioning stage - SharePoint](https://docs.microsoft.com/en-us/SharePoint/troubleshoot/sites/troubleshooting-guide-for-sites-stopped-at-provisioning?toc=/SharePoint/troubleshoot/onedrivetoc/toc.json&bc=/SharePoint/troubleshoot/breadcrumb/toc.json)
* Content Source: [SharePoint/SharePointOnline/sites/troubleshooting-guide-for-sites-stopped-at-provisioning.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sites/troubleshooting-guide-for-sites-stopped-at-provisioning.md)
* Product: **onedrive**
* GitHub Login: @todmccoy
* Microsoft Alias: **v-todmc**

**Comment by get-itips** [comment]
Hello @hwkwicre how are you?
I can confirm the sentence was improved some time ago.
thank you!

**Comment by nam31** [comment]
@hwkwicre We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
