### ISSUE TITLE
Error in powershell command

### ISSUE THREAD

**Issue by scaryfruit** [MicrosoftDocs/OfficeDocs-Support#624]
In the powershell command for enabling owner logging on an account it has the following:

Set-Mailbox <useridentity> -AuditOwner "Create,HardDelete,Move,MoveToDeletedItems,SoftDelete,Update&quot

I believe it should be the following (i.e. with a quote after the word "update"):

Set-Mailbox <useridentity> -AuditOwner "Create,HardDelete,Move,MoveToDeletedItems,SoftDelete,Update"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a93c78d-ed18-2fda-d8bb-9f60f64fbc0f
* Version Independent ID: a79b1742-f841-c8a5-71f6-1c1dda533d6a
* Content: [How to use mailbox audit logs in Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/audit-logs/mailbox-audit-logs)
* Content Source: [Microsoft365/compliance/audit-logs/mailbox-audit-logs.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/compliance/audit-logs/mailbox-audit-logs.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments. The article is updated.
