### ISSUE TITLE
Clarification on type of DWORD to use and Click to Run registry path

### ISSUE THREAD

**Issue by adamskovron** [MicrosoftDocs/OfficeDocs-Support#628]
First - thanks for this guide it did exactly what I needed (once I got the reg right) .. Few clarifications that if correct could help others using this guide.. 

Step 5 Click the Options subkey, point to New on the Edit menu, and then click DWORD Value.

Should specify 32bit DWORD.  I have the 64bit click to run installed but still needed the DWORD to be 32bit.  

Also, this worked for my click to run by creating the new key in under .. should this doco be updated to reflect that as well?

HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\PowerPoint\Options

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e390c4c9-9cdf-beb1-43dc-6ec45ae5fe77
* Version Independent ID: bb31c9ea-7186-22fb-195f-f481eb5137e4
* Content: [How to change the export resolution of a PowerPoint slide - Office](https://docs.microsoft.com/en-us/office/troubleshoot/powerpoint/change-export-slide-resolution)
* Content Source: [Office/Client/powerpoint/change-export-slide-resolution.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/powerpoint/change-export-slide-resolution.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@adamskovron .Thanks for pointing out. According to you,. In artice for 64bit powerpoint application, still DWORD value should be used.
Above line should be added in article. Am I correct ?

**Comment by adamskovron** [comment]
I've suggested new text to add by adding it in bold below, note I'm using bold to identify what I'm suggesting to add these don't need to be bold in the document

_Under step 1 in sub-step 4_ 

4. Locate one of the following registry subkeys, depending on the version of PowerPoint that you're using:

PowerPoint 2016**, 2019 or Click to o Run**

HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\PowerPoint\Options

--

_Under step 1 in sub-step 5_ 

5. Click the Options subkey, point to New on the Edit menu, and then click DWORD **(32-bit)** Value.

**Comment by RAJU2529** [comment]
@ei0, @simonxjx . Will you agree with @adamskovron his point ?

**Comment by simonxjx** [comment]
The article is updated.

**Comment by adamskovron** [comment]
Nice!
