### ISSUE TITLE
Word could not create the work file. Check the temp environment variable

### ISSUE THREAD

**Issue by mvpromise** [MicrosoftDocs/OfficeDocs-Support#629]
[Enter edback here]

I feel its a temporary fix as i keep getting the same error after Windows update
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f069189a-7af4-d6df-1509-f30af7d3c01d
* Version Independent ID: df260ca7-16dd-d2f8-1de3-91e0b71f67d4
* Content: [Word could not create the work file error message when you save a document - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/word-could-not-create-the-work-file)
* Content Source: [Office/Client/word/word-could-not-create-the-work-file.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/word-could-not-create-the-work-file.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@mvpromise Thank you for your feedback. The issue does not reproduce in the lab after a windows update. Could you please let us know if the issue still persists? Also, did you try the workaround for turning off the preview or sfc.exe /scannow ?

Thanks
Sri

**Comment by msbemba** [comment]
@mvpromise wanted to circle back to check if the issue still persists. If yes, Could you please let us know if the issue still persists? Also, did you try the workaround for turning off the preview or sfc.exe /scannow ?

Thanks
Sri

**Comment by nam31** [comment]
@mvpromise We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
