### ISSUE TITLE
Language Codes Link Incorrrect

### ISSUE THREAD

**Issue by thenotandy** [MicrosoftDocs/OfficeDocs-Support#63]
Under Method 3, the Language Codes Hyperlink goes to an unrelated page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e382bcde-4ad2-c781-e2be-ab5d4f5781e6
* Version Independent ID: 71740043-eab5-b2d6-ecce-07aa59fe107a
* Content: [Folder names are incorrect or displayed in an incorrect language in Outlook - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/folders/incorrect-folder-names#feedback)
* Content Source: [Outlook/Client/folders/incorrect-folder-names.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/folders/incorrect-folder-names.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The link is removed.
