### ISSUE TITLE
 Please update for consistency

### ISSUE THREAD

**Issue by kpinel** [MicrosoftDocs/OfficeDocs-Support#630]
Having an issue where some users are getting shared mailboxes automapped even though the -AutoMapping switch is set to false. On reviewing the doco, I came across this slight discrepancy and have noted in the past when using the incorrect format usually results in an error but it looks like it isn't the case here. 
Which format is actually correct? (Note the difference between the AutoMapping switch)
Syntax
```powershell
Add-MailboxPermission -Identity <Mailbox ID1> -User <Mailbox ID2> -AccessRights FullAccess -AutoMapping:$false
```
 
Example
```powershell
Add-MailboxPermission -Identity johnsmith@contoso.onmicrosoft.com -User admin@contoso.onmicrosoft.com -AccessRights FullAccess -AutoMapping $false
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd6c33b6-24fb-447d-e9de-c5f11f0aaaae
* Version Independent ID: f5fd953d-bcbf-9315-8336-e43c20ef8022
* Content: [Remove automapping for a shared mailbox - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/domain-management/remove-automapping-for-shared-mailbox)
* Content Source: [Outlook/Client/domain-management/remove-automapping-for-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/domain-management/remove-automapping-for-shared-mailbox.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by ScooterComputer** [comment]
I notice this doc _still_ references "-automapping:$false", contrary to what OP highlights, even though it has been updated in April 2021. According to 
https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-permissions-for-recipients
the correct syntax **is** "-automapping $false", with a space not a colon.

**Comment by kpinel** [comment]
> I notice this doc _still_ references "-automapping:$false", contrary to what OP highlights, even though it has been updated in April 2021. According to
> https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-permissions-for-recipients
> the correct syntax **is** "-automapping $false", with a space not a colon.

This is an old post and it looks like all references have been updated but this post hasn't been closed

**Comment by ScooterComputer** [comment]
> Add-MailboxPermission -Identity <Mailbox ID1> -User <Mailbox ID2> -AccessRights FullAccess -AutoMapping:$false

"Attention to detail".
