### ISSUE TITLE
Restoring a corrupted Word file with a hard drive

### ISSUE THREAD

**Issue by enderdez** [MicrosoftDocs/OfficeDocs-Support#632]
So, I was recently (a few hours ago) working on a story that I've been writing for months now. I didn't notice anything strange until I happened to glance at the top of the screen. The filename was _not_ what I had named it; it was something like ~WRL0002. I tried to save it, since I had been writing for literally hours and had several pages churned out. It gave me an error, saying this was not possible. Thinking it was an error, I selected a few pages of text that I'd been writing, copied it, and pasted it in my notes just in case. It turns out, that might have saved my sanity.

When I closed Word and tried to reopen the file, it simply did not exist. I checked my hard drive where I was storing it, and I didn't see it there either. At this point, I was panicking. I had over 190 pages written, and I was not about to lose it all. I found the recovery document, but that was corrupted as well, and nothing I tried helped. I tried checking the trash can, seeing if it was deleted and sent to there - nope. So then, hoping I could find something, I went to the main menu of my hard drive.

On my computer, I have all folders unhidden; that is, the metadata folders and files in my hard drives are always visible. In my hard drive, there is a folder called ".TemporaryItems". I checked inside it just to see, and after a couple of folder paths, I found the file: ~WRL0002. I clicked on it and opened it, and lo and behold - my document! I quickly saved it to multiple locations in case it glitched again, and then I did a damage survey. Only 178 of my 190 pages were recovered, which is depressing, but I remembered the five or six pages I had saved to my notes app, which helped a lot.

So, if your file gets deleted or corrupted like mine, here's what to do:

<img width="769" alt="Screen Shot 2020-06-26 at 12 41 44 AM" src="https://user-images.githubusercontent.com/45862518/85821167-02c0b980-b746-11ea-87a4-339ab60d1526.png">

Unhide all the folders. On a Mac, go into Macintosh HD and press Command+Shift+Period (.)

<img width="772" alt="Screen Shot 2020-06-26 at 12 41 58 AM" src="https://user-images.githubusercontent.com/45862518/85821173-05231380-b746-11ea-8098-3ee48be4fb45.png">

You'll want to go into the folder labeled .TemporaryItems and search there

<img width="770" alt="Screen Shot 2020-06-26 at 12 42 12 AM" src="https://user-images.githubusercontent.com/45862518/85821176-06544080-b746-11ea-888c-a3ad4a6b2a5b.png">

<img width="770" alt="Screen Shot 2020-06-26 at 12 42 22 AM" src="https://user-images.githubusercontent.com/45862518/85821178-06544080-b746-11ea-837b-4464b66bfae9.png">

<img width="771" alt="Screen Shot 2020-06-26 at 12 42 33 AM" src="https://user-images.githubusercontent.com/45862518/85821179-07856d80-b746-11ea-90ae-04f2571ce77e.png">

My word document, safely recovered.

Now, keep in mind this only recovers anything that was saved before it corrupted. So, if you haven't saved since you started working, it won't recover any progress you've made. Just a heads up.

Hope this helps other people!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b95df2f-e3de-e2d1-b48a-3fcd4183463f
* Version Independent ID: 397150eb-b8e0-62c0-55b9-c5277aacb5dd
* Content: [How to troubleshoot damaged documents in Word - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/damaged-documents-in-word)
* Content Source: [Office/Client/word/damaged-documents-in-word.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/damaged-documents-in-word.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@enderdez . For safely measures  and precaution, save the document in cloud level by integrating onedrive in word application and enable saving all documents in onedrive by default

**Comment by nam31** [comment]
@enderdez Thank you for your input. But the intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content ?
Thank you.

**Comment by nam31** [comment]
@enderdez We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
