### ISSUE TITLE
Expand what APAC, NOAM and EMEA are

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/OfficeDocs-Support#635]
I'm sure its obvious to nonidiots like me, but it took me a few seconds to figure out which region I was in. A link with a country pull up confirming who is where would be useful (and yes, my history does show I hate having things on multiple pages, but this is one area where it makes sense.)
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef6fd529-a369-9afd-ce21-4cb8b415f6c4
* Version Independent ID: 9e7c3225-ddba-1af5-c2f0-ab3da394f02f
* Content: [Voicemail messages are not delivered in Teams or Skype for Business client - Skype for Business](https://docs.microsoft.com/en-us/SkypeForBusiness/troubleshoot/hybrid-phone-system/voicemails-not-delivered)
* Content Source: [SkypeforBusiness/SkypeHybrid/hybrid-phone-system/voicemails-not-delivered.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeHybrid/hybrid-phone-system/voicemails-not-delivered.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The explanation is added to the article.

- APAC is Asia Pacific
- EMEA is Europe, Middle-East and Africa
- NOAM is North America
