### ISSUE TITLE
What??

### ISSUE THREAD

**Issue by Coldry** [MicrosoftDocs/OfficeDocs-Support#639]
How can you 'Edit' in Excel Online as this page suggests when the very issue is that you can't Edit a workbook with text queries?

Should this page say RESOLUTION: ... "Select Edit Workbook > **Edit in Desktop App**. ..."?

Forgive me if I've missed something obvious.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02e27780-4676-2af3-3875-2c576b256768
* Version Independent ID: 1a8a9c1f-2b67-7bd2-fc32-9bebb2ea5431
* Content: [Compatibility Report about text queries in Excel Online - Office](https://docs.microsoft.com/en-us/office/troubleshoot/administration/compatibility-report-about-text-queries-in-excel-online)
* Content Source: [Office/OfficeExperts/administration/compatibility-report-about-text-queries-in-excel-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/administration/compatibility-report-about-text-queries-in-excel-online.md)
* Service: **sharepoint-online**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **jhaak**

**Comment by jlriesco** [comment]
@Coldry  Thanks for your feedback. We've updated the article to make it more clear.

**Comment by nam31** [comment]
@Coldry the article has been updated accordingly. Please let us know if you still have any question regarding the issue you have raised initially.

**Comment by nam31** [comment]
@Coldry We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
