### ISSUE TITLE
How to update contact information as a user

### ISSUE THREAD

**Issue by Weychris** [MicrosoftDocs/OfficeDocs-Support#64]
I don't think the above documentation related to Outlook Web Access is accurate any longer. I see no path in the current OWA to the described settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b9d03b7-62fa-21cf-6bad-7474e643ce27
* Version Independent ID: 837d0aec-c3dc-df94-643c-31bffbd72a01
* Content: [How to update contact information in Exchange Online in Office 365 - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/configure-contacts/update-contact-information#feedback)
* Content Source: [Exchange/ExchangeOnline/configure-contacts/update-contact-information.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/configure-contacts/update-contact-information.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by JohnMoor** [comment]
Indeed, Outlook Web App doesn't include a "Account" option under settings. I assume it needs to be done in Delve now, but there is no option for the end user to change his/her mobile number.

**Comment by lanilukas** [comment]
This documentation is not valid,
Outlook Web App doesn't include a "Account" option under settings
and users are not able to edit contact information under actual location (https://portal.office.com/account/#personalinfo)

**Comment by pixelsibyl13** [comment]
I would just like to be the fourth to say this is not an option anymore.

**Comment by lanilukas** [comment]
We found the way how to do it, it was pretty tricky to find, but it works for us. Let's try:
https://outlook.office.com/owa/?path=/options/myaccount

**Comment by pixelsibyl13** [comment]
That doesn’t work for our tenant.

**Comment by nam31** [comment]
@Weychris We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
