### ISSUE TITLE
Book.xlt file in XLSTART does not load upon Ctl+N or clicking on open blank workbook icon

### ISSUE THREAD

**Issue by lisaamante** [MicrosoftDocs/OfficeDocs-Support#640]
Hi, I can't get this solution to work. I created my custom preferences workbook and saved it as Book.xlt to C:\Users\Lisa\AppData\Roaming\Microsoft\Excel\XLSTART. That's the only file in that folder. Yet, that's not the file that opens when I click to create a new workbook. It appears that Microsoft's own default workbook is what's opening. 
Any ideas on how to make it work?
Thanks!!
-Lisa
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 268953bb-2edc-08a1-2afb-7b00e578cd7a
* Version Independent ID: 1b013dad-688a-251b-b3d1-6e15cde11f85
* Content: [How to use startup folders in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/use-startup-folders)
* Content Source: [Office/Client/excel/use-startup-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/use-startup-folders.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. I recommend you to contact [Excel Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.excel) for more help.

**Comment by lisaamante** [comment]
ok thanks
