### ISSUE TITLE
Test Blank cell as a string

### ISSUE THREAD

**Issue by ebmgithub** [MicrosoftDocs/OfficeDocs-Support#643]
Alternatively concatenate the cell value with empty string and evaluate as a string.
`IF(C10 & "" = "0", true, false)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d37aacf0-7de2-a24f-2314-c798bc580b77
* Version Independent ID: 587eb6d2-f47f-fec7-c8e5-2db05cd1a291
* Content: [Create a formula to correctly evaluate blank cells - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/use-formula-evaluate-blank-cell)
* Content Source: [Office/Client/excel/use-formula-evaluate-blank-cell.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/use-formula-evaluate-blank-cell.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@ebmgithub The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content
Thank you.

**Comment by nam31** [comment]
@ebmgithub We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
