### ISSUE TITLE
Needs to cover the case of Linked Tables

### ISSUE THREAD

**Issue by manukautech** [MicrosoftDocs/OfficeDocs-Support#645]
This article needs to cover the case of linked tables e.g. tables linked from MS SQL Server. Do the existing relationships in MSSQL carry over into Access? Or do they need to be remade in Access? The article needs to answer this question or link to another article that explains relationships for linked tables.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b264b1a2-c836-adda-a169-da8bafbb108b
* Version Independent ID: 537820ff-7073-0bc2-3f69-18ad6a1446c8
* Content: [Define relationships between tables in an Access database - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/define-table-relationships)
* Content Source: [Office/Client/access/define-table-relationships.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/define-table-relationships.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by lindspea** [comment]
@manukautech thank you for reaching out and helping improve MS Docs. I'm looking into this and will revert soonest.

**Comment by lindspea** [comment]
@manukautech will a link to this article be helpful? https://support.microsoft.com/office/manage-linked-tables-1d9346d6-953d-4f85-a9ce-4caec2262797

**Comment by nam31** [comment]
@manukautech Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
