### ISSUE TITLE
Exchange Management Troubleshooter download link BROKEN

### ISSUE THREAD

**Issue by markpizz** [MicrosoftDocs/OfficeDocs-Support#646]
Exchange Management Troubleshooter download link 
(https://gallery.technet.microsoft.com/exchange-management-b9d918b1) 
does not contain the specifics of what this page 
(https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/connecting-remote-server-failed) 
refers to, OR it is not publicly accessible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 372aa4a8-6433-ad6e-eece-15a8d9f7cb0f
* Version Independent ID: aa97ea60-52e0-5e17-bd9d-b29d7f2ef789
* Content: [Connecting to the remote server failed when start Management Shell or Console - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/connecting-remote-server-failed)
* Content Source: [Exchange/ExchangeServer/administration/connecting-remote-server-failed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/administration/connecting-remote-server-failed.md)
* Service: **exchange-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The [link](https://techcommunity.microsoft.com/gxcuf89792/attachments/gxcuf89792/Exchange/4274/1/EMTshooter.zip) is updated in the article.
