### ISSUE TITLE
The fix is useless, it doesn't work

### ISSUE THREAD

**Issue by mhanganu** [MicrosoftDocs/OfficeDocs-Support#647]
I attempted to fix it, but is not working. I have created the folder and the problem persists. It persists even if I did the folder in the right place. I have reinstalled MS Office and the problem doesn't go away
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f069189a-7af4-d6df-1509-f30af7d3c01d
* Version Independent ID: df260ca7-16dd-d2f8-1de3-91e0b71f67d4
* Content: [Word could not create the work file error message when you save a document - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/word-could-not-create-the-work-file)
* Content Source: [Office/Client/word/word-could-not-create-the-work-file.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/word-could-not-create-the-work-file.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. I recommend you to contact [Word support](https://support.microsoft.com/en-us/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.word) for more help.
