### ISSUE TITLE
After new update

### ISSUE THREAD

**Issue by SniperDiaper1** [MicrosoftDocs/OfficeDocs-Support#649]
When i attempt to access one contact in outlook, it ask if i would like to continue and open 22 contacts.  On a diffrent contact it ask if i would like to continue and open 19 contacts.  What happened to the contact?!

**Comment by RAJU2529** [comment]
@SniperDiaper1 . Which article are you referring?

**Comment by nam31** [comment]
@SniperDiaper1 The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@SniperDiaper1 We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
