### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by Gmaynard-UR** [MicrosoftDocs/OfficeDocs-Support#652]
Our organization is having severe latency issues using Teams.  I've examined the firewall policy for rules covering the URLs/IP addresses and service ports.  I am not seeing any bandwidth issues.  Any other things I should look for?

**Comment by RAJU2529** [comment]
@Gmaynard-UR. Which article are you referring?

**Comment by nam31** [comment]
@Gmaynard-UR The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@Gmaynard-UR We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
