### ISSUE TITLE
Outlook keeps prompting for password? autodiscovery issue?

### ISSUE THREAD

**Issue by getgcs33** [MicrosoftDocs/OfficeDocs-Support#653]
Hey so office home and business 2016 can this use exchange online license? Also why do I and 5 other people have the same password prompt loop when trying to use outlook 2016? It won't connect for us. Any info for this would be great help! Thanks!

is it related to this? https://support.microsoft.com/en-us/help/3060280/password-prompt-at-every-outlook-start-or-can-t-create-profile

Or is it related to this? https://support.microsoft.com/en-us/office/outlook-license-requirements-for-exchange-features-46b6b7c5-c3ca-43e5-8424-1e2807917c99

**This is my autodiscovery error** (can scroll using bar at the bottom) https://social.technet.microsoft.com/Forums/en-US/70d7fca6-a01a-4ed5-a94a-801442495762/outlook-wont-see-autodiscovery-in-dns?forum=outlook

**Comment by getgcs33** [comment]
Same problem also happens while connected to ProtonVPN

**Comment by getgcs33** [comment]
Is it a DNS issue? Since the Autodiscovery error (above) says this what should I change in the registry?

**Comment by getgcs33** [comment]
Also the webmail version works fine on all accounts

**Comment by RAJU2529** [comment]
@getgcs33 . Which article are you referring to?
 submit your query on answers.microsoft.com or techcommunity.microsoft.com

**Comment by nam31** [comment]
@getgcs33 The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@getgcs33 We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
