### ISSUE TITLE
Step 1: Run the script

### ISSUE THREAD

**Issue by GrahamYoung05** [MicrosoftDocs/OfficeDocs-Support#654]
[The $OutFileName variable needs to be changed to double quotes to allow the $Date variable to work:
$OutFileName = "AuditLogResults$Date.csv" ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a93c78d-ed18-2fda-d8bb-9f60f64fbc0f
* Version Independent ID: a79b1742-f841-c8a5-71f6-1c1dda533d6a
* Content: [How to use mailbox audit logs in Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/audit-logs/mailbox-audit-logs)
* Content Source: [Microsoft365/compliance/audit-logs/mailbox-audit-logs.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/compliance/audit-logs/mailbox-audit-logs.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by GrahamYoung05** [comment]
Same thing for line Write-Host -fore green 'Posting results to file: $OutfileName' , needs to be changed to:
write-host -fore green "Posting results to file: $OutfileName"

**Comment by simonxjx** [comment]
Thanks for your comment. The article is updated.
