### ISSUE TITLE
Aged documentation

### ISSUE THREAD

**Issue by aheusel** [MicrosoftDocs/OfficeDocs-Support#655]
The documentation in this page has not been reviewed for a while.
In Windows 10 there is not Internet Explorer which renders this page useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8928ed26-fda0-0e68-a4e1-cc287a5e5699
* Version Independent ID: c6ff303c-a5b4-4890-6d00-82246b92ea45
* Content: [Mapping and syncing network drives that connect to SharePoint Online - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/troubleshoot-mapped-network-drives)
* Content Source: [SharePoint/SharePointOnline/administration/troubleshoot-mapped-network-drives.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/administration/troubleshoot-mapped-network-drives.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@aheusel , SharePoint expert users can give solutions, so wait for a few days

**Comment by get-itips** [comment]
Hello @aheusel Alexander, how are you?
Windows 10 shipped with IE11. 
Besides that, the note at the top of the article now states that the preferred method is OneDrive sync.
Thank you for your feedback.

**Comment by nam31** [comment]
@aheusel Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
