### ISSUE TITLE
Any updates to this issue?

### ISSUE THREAD

**Issue by Aegrum** [MicrosoftDocs/OfficeDocs-Support#656]
[Enter feedback here]
Is there any update to this issue? Increasing PIM timeout to 24 hours, meaning it'd potentially take up to a day to get to something in the admin console isn't really a viable operational solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d479de0-d982-6979-2108-e35adb507e0e
* Version Independent ID: 03dc1c5c-83ab-8690-0ee7-8ed7e4811440
* Content: [Access denied error for PIM-managed accounts in SharePoint or OneDrive admin center - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/access-denied-to-pim-user-accounts)
* Content Source: [SharePoint/SharePointOnline/administration/access-denied-to-pim-user-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/administration/access-denied-to-pim-user-accounts.md)
* Service: **sharepoint-online**
* GitHub Login: @todmccoy
* Microsoft Alias: **v-todmc**

**Comment by RAJU2529** [comment]
@Aegrum . SharePoint expert users can give solutions, so wait for a few days

**Comment by Aegrum** [comment]
Been two weeks... anybody?

**Comment by msbemba** [comment]
@Aegrum Thank you for your feedback. The feedback has been passed to Azure active directory team and the change in design is in planning status and hopefully this will be complete by the end of the calendar year. For more information -https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/39839785-eliminate-delays-when-activating-the-sharepoint-ad

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@nam31 There are no changes required in the document. 

Thanks
Sri

**Comment by nam31** [comment]
@Aegrum Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
