### ISSUE TITLE
Patch dates don't match behaviour

### ISSUE THREAD

**Issue by clcook-tmrqld** [MicrosoftDocs/OfficeDocs-Support#657]
The patch referred to in this document is dated 2016, but the document says that it was released 7 days ago in 2020. We are seeing an issue where we can't present PowerPoint files to Skype Meeting Broadcast 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f6cee3-8c80-4604-cddd-6df391f80c8e
* Version Independent ID: abc2e13d-2322-66a1-5ead-4f9cc9482742
* Content: [Cannot connect conference modalities after install Security Bulletin MS16-065 - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/server-conferencing/cannot-connect-conferencing-modalities)
* Content Source: [SkypeforBusiness/SkypeServer/server-conferencing/cannot-connect-conferencing-modalities.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeServer/server-conferencing/cannot-connect-conferencing-modalities.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments. The article is updated on 07/03/2020 while the update is released in 2016. If the issue still occurs, you can [contact support](https://support.microsoft.com/en-us/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.skype-for-business) for more help.
