### ISSUE TITLE
Error in List Box SELECT Statement

### ISSUE THREAD

**Issue by yomian** [MicrosoftDocs/OfficeDocs-Support#658]
[Enter feedback here]
In the Row Source for the List Box, the field name should be [First Name] not "FirstName". There is a space in the field name from the employees table.

Thanks for the code sample though. I believe it will prove helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd1a9ec-d992-3fcd-69a4-a53335713d7a
* Version Independent ID: 3c3f6122-cd57-cc9f-8a8f-4568b9c4f55d
* Content: [Store selected items as comma-delimited string - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/retrieve-items-in-multiple-selection-list-box)
* Content Source: [Office/Client/access/retrieve-items-in-multiple-selection-list-box.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/retrieve-items-in-multiple-selection-list-box.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by nam31** [comment]
Closing via #661
Thank you
