### ISSUE TITLE
Page publishing date in the future

### ISSUE THREAD

**Issue by dmenken** [MicrosoftDocs/OfficeDocs-Support#660]
Reviewing the page, the publishing date is set as 10/04/2020, but today is 7/10/2020.  How can that be since Time Travel has not been invented yet.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d2410e2-6e38-59a3-c528-e5ba3becd1ff
* Version Independent ID: 0f3d3418-944b-1f96-7047-e453acf687b0
* Content: [A SharePoint Online list item attachment doesn't open in the Office client app - SharePoint](https://docs.microsoft.com/en-sg/sharepoint/troubleshoot/lists-and-libraries/office-app-fails-opening-list-item-attachment)
* Content Source: [SharePoint/SharePointOnline/lists-and-libraries/office-app-fails-opening-list-item-attachment.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/lists-and-libraries/office-app-fails-opening-list-item-attachment.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@dmenken . Yes are right.

**Comment by simonxjx** [comment]
Thanks for your comment. The date is in the DD/MM/YYYY format. So, the date is April 10th, 2020.
