### ISSUE TITLE
Support for Edge

### ISSUE THREAD

**Issue by ingepepe** [MicrosoftDocs/OfficeDocs-Support#662]
What about Edge? It doesn't work on this browser and there is no extension?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7213684-06c8-73d9-06f0-82e3c53a9722
* Version Independent ID: 2a533223-401a-c5b8-a58e-2d9d19fe6dce
* Content: [You can't start the eDiscovery PST Export Tool from the Exchange admin center in Exchange Online. - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/ediscovery/cannot-start-ediscovery-pst-export)
* Content Source: [Microsoft365/compliance/ediscovery/cannot-start-ediscovery-pst-export.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/compliance/ediscovery/cannot-start-ediscovery-pst-export.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@ingepepe .  scroll to below page for edge browser extension, 

**https://chrome.google.com/webstore/detail/clickonce-for-google-chro/kekahkplibinaibelipdcikofmedafmb/related**

**Comment by ingepepe** [comment]
Thanks
