### ISSUE TITLE
There is a better and simpler sulution

### ISSUE THREAD

**Issue by paxmundi** [MicrosoftDocs/OfficeDocs-Support#663]
### **The number of occurrences of a text string in a range of cells:**

Suppose you have the following data in cells A1:A6:
A1: apple
A2: orange
A3: apple, orange
A4: grape
A5: orange, grape
A6: grape, apple

and you want to count the number of times the string "apple" appears in this range(A1:A6)

The shortest and simplest formula would be an array formula as follows:
{=SUM(--ISNUMBER(FIND("apple",$A$1:$A$6)))}

Best Regards,
Meni Porat

PaxMundi@gmail.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d3af8cc-9482-e5e9-f1d5-a64f9ac0c51f
* Version Independent ID: e48dffa1-fccd-8de4-ef83-90f22a420ab1
* Content: [Formulas to count the occurrences of text, characters, and words in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/formulas-to-count-occurrences-in-excel?source=docs)
* Content Source: [Office/Client/excel/formulas-to-count-occurrences-in-excel.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/formulas-to-count-occurrences-in-excel.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@paxmundi The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content
Thank you.

**Comment by nam31** [comment]
@paxmundi We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
