### ISSUE TITLE
Setup error if the .NET Framework 4.6 is installed

### ISSUE THREAD

**Issue by masadiq** [MicrosoftDocs/OfficeDocs-Support#665]
Hello there,
I am experiencing this issue and unable to find the following provided solution in ZIP format.
Is there anyone file ZIP file or know the location so I could download it.

Thanks
Muzaffar

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f467ff86-48f6-82ea-817b-7d19b7b8ad02
* Version Independent ID: 3a81bc47-e572-4e7d-70a3-2706219d6657
* Content: [SharePoint 2013 or Project Server 2013 Setup error if the .NET Framework 4.6 is installed - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/installation-and-setup/setup-error-if-.net-framework-4.6-is-installed)
* Content Source: [SharePoint/SharePointServer/installation-and-setup/setup-error-if-.net-framework-4.6-is-installed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointServer/installation-and-setup/setup-error-if-.net-framework-4.6-is-installed.md)
* Service: **sharepoint-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by bowen-liu** [comment]
I made a thread on this issue on the MS Tech community here: 

https://techcommunity.microsoft.com/t5/sharepoint/need-quot-svrsetup-15-0-4709-1000-x64-zip-quot-for-sharepoint/m-p/1479145/highlight/true#M42388

Although no one seem to have the file anymore, there are alternative solutions available that may help you to install.

Best of luck!

**Comment by VLG17** [comment]
@masadiq The download links in the article are working for me. Can you confirm?

**Comment by nam31** [comment]
@masadiq We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
