### ISSUE TITLE
SaRA Requires ClickOnce Trust

### ISSUE THREAD

**Issue by Smithja6** [MicrosoftDocs/OfficeDocs-Support#668]
In order to install SaRA I had to change ClickOnce security behavior in RegEdit per https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-configure-the-clickonce-trust-prompt-behavior?view=vs-2019

Setting values to 'AuthenticodeRequired' was sufficient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6702b26f-e265-09e3-9134-1820cc31e5d1
* Version Independent ID: d4acf438-83f0-cf26-b0e8-ad8d67796af0
* Content: [Outlook crash or stop responding when used with Office 365 - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/outlook-crashes/crash-issues)
* Content Source: [Exchange/ExchangeOnline/outlook-crashes/crash-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/outlook-crashes/crash-issues.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by get-itips** [comment]
Hello @Smithja6 how are you? Hope you are doing good.
Tried to reproduce in my lab, but couldn't, I could install SaRA without applying any reg.
Thank you for your feedback.

**Comment by get-itips** [comment]
Hello @Smithja6 returning to check if you could see my answer. Thank you

**Comment by Smithja6** [comment]
Hi Andres,

Thanks for looking into the problem but I'm afraid I can't be of much help. I had forgotten that I even submitted the report and can't remember the specifics of the issue anymore. I do remember that it took quite a while to troubleshoot the system in question but that the regedit that I listed was able to resolve the issue. Sorry to not be of more help but if no other reports have come in in the last year it might not be too common. Have a great day and thanks for your work.

Sincerely,

Jeremy Smith

**Comment by nam31** [comment]
@Smithja6 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed as you are no longer require assistance, feel free to re-open this issue if you feel that there are further suggestions to improve the documentation itself.
Thanks.
