### ISSUE TITLE
Need information on how to view the list of who has been sent an OOF reply.

### ISSUE THREAD

**Issue by jgarruba** [MicrosoftDocs/OfficeDocs-Support#671]
Need information on how to view the list of who has been sent an OOF reply. As Exchange must maintain this for the feature to work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586ba5d7-6b64-530f-7448-186c6abe19c2
* Version Independent ID: 6d64b831-2220-99db-010e-790d8abd114c
* Content: [Only one reply is sent to each sender when Out of Office Assistant is enabled - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/client-connectivity/one-reply-sent-sender)
* Content Source: [Exchange/ExchangeServer/client-connectivity/one-reply-sent-sender.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/client-connectivity/one-reply-sent-sender.md)
* Service: **exchange-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello @jgarruba ,
it is not possible to view this information using GUI.
You can use Powershell to extract the message tracking logs, and view the list of recipients of out of office replies.
Thank you

**Comment by nam31** [comment]
@jgarruba Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
