### ISSUE TITLE
Teams stuck in login loop -- check your system clock and make sure it's correct. 

### ISSUE THREAD

**Issue by robert-studio365** [MicrosoftDocs/OfficeDocs-Support#672]
[Several threads about this on Reddit and apparently was a [known issue with skype for business](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_sfb/skype-for-business-wont-start-because-of-the-clock/5b0ed751-8ec3-4a14-9f2f-083b1c80a1bc?ranMID=24542&ranEAID=msYS1Nvjv4c&ranSiteID=msYS1Nvjv4c-DIlWkthJ0RLsI2tGyDYftw&epi=msYS1Nvjv4c-DIlWkthJ0RLsI2tGyDYftw&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=%28ir__id1peenkkwkftxcakk0sohzibn2xi1fi6lwutkvt00%29%287593%29%281243925%29%28msYS1Nvjv4c-DIlWkthJ0RLsI2tGyDYftw%29%28%29&irclickid=_id1peenkkwkftxcakk0sohzibn2xi1fi6lwutkvt00), so should be updated here. I went through all the recommendations on this page and was still having no luck.   Once I checked my system clock and corrected that everything worked. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c060df7-e881-f6b9-29bb-8ee6ba3cb43a
* Version Independent ID: e614dbf0-9542-9f60-e430-d1aa2471f42c
* Content: [Microsoft Teams is stuck in a login loop in Edge or Internet Explorer - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/troubleshoot/teams-sign-in/sign-in-loop)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment.
