### ISSUE TITLE
Proposed resolution

### ISSUE THREAD

**Issue by martin0641** [MicrosoftDocs/OfficeDocs-Support#673]
[Enter feedback here]

I just wanted to get across to you that there is are security reasons Chrome has disabled NPAPI - it's strange that Microsoft is using the "Netscape Plugin Application Programming Interface" from a defunct browser to connect a modern browser to a modern version of Skype.

You should not be relying on an old and insecure method to do this redirect, especially since you are now moving Microsoft Edge over to a Chromium/Blink base - which means your Option 1 of "Set Internet Explorer as Default" (which no one is going to do) is even less viable than adding GPO entries because even if we used Edge Chromium as my default - it wouldn't work either for the same reasons that Chrome doesn't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62e22224-64c1-ea10-101b-c6ba96c9c1fd
* Version Independent ID: 4bc021f0-7050-4c66-16d9-0f11961e3284
* Content: [Client does not start when click a meeting link if default browser is Chrome - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/server-sign-in/client-not-start-click-meeting-link)
* Content Source: [SkypeforBusiness/SkypeServer/server-sign-in/client-not-start-click-meeting-link.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeServer/server-sign-in/client-not-start-click-meeting-link.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The article is updated. Thanks for your comments.
