### ISSUE TITLE
unable to see creation of mail 

### ISSUE THREAD

**Issue by vipuljhaveri** [MicrosoftDocs/OfficeDocs-Support#674]
i tired this innovative technique for recurring email with my windows 8 and outlook 2007 , on reminder alert and
putting completion yes - recurring task does get created but unable to see creation of mail , i may be missing on somewhere
as many on my websearch has confirmed its working but few also have observed it non working , and i also fail to
get email made up, kindly guide any background needs to be ensured etc as seems somewhere basics needs to be infomed
to make use of this superb functionality

**Comment by nam31** [comment]
@vipuljhaveri The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@vipuljhaveri We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
