### ISSUE TITLE
The Attendee Bug

### ISSUE THREAD

**Issue by DeadlyScope** [MicrosoftDocs/OfficeDocs-Support#675]
[Enter feedback here]
I wanted to inform of a bug on teams me and my classmates found
Basically if you minimize then you can see a small pop up of the teams and even an attendee can share their screen as the share screen works for all over there.

Hope you look into this problem immediately

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 103da6d9-ae2b-dea2-053d-922600686950
* Version Independent ID: 62501206-4fee-8016-bff1-309eae334d75
* Content: [Information about Teams known issues - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-welcome)
* Content Source: [Teams/teams-welcome.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-welcome.md)
* Service: **msteams**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by DeadlyScope** [comment]
I found this error by mistake btw

**Comment by AmandaAZ** [comment]
For this problem, you can try to troubleshoot or get help from [here](https://support.microsoft.com/office/troubleshooting-6fa7c08a-6fd4-47a0-b275-90a5f60f1df9).
