### ISSUE TITLE
Make This Option Available Via a Parameter

### ISSUE THREAD

**Issue by rednender** [MicrosoftDocs/OfficeDocs-Support#678]
This is a bad solution to an easy problem.  Obviously, modern auth is supported.  Put in switch that says "UseModernAuth".  This is a single user solution and isn't scalable to automation services like Azure Automation. We have basic auth disabled for security reasons, but still need to perform automated administrative tasks in SPO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f722b3d-7060-827c-357d-e3acbb5b1eb5
* Version Independent ID: eb0898ea-d02a-31cb-3b8c-e690824a7f92
* Content: [Can't force Modern Authentication when using Connect-SPOService cmdlet in SharePoint Online Management Shell - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/security/cannot-force-modern-authentication)
* Content Source: [SharePoint/SharePointOnline/security/cannot-force-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/security/cannot-force-modern-authentication.md)
* Service: **sharepoint-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello @rednender ,
there is no such switch currently presented for [Connect-SPOService](https://docs.microsoft.com/powershell/module/sharepoint-online/connect-sposervice?view=sharepoint-ps) cmdlet.
Here only feedback related to the documentation is collected. To provide product-related feedback you can use [SharePoint uservoice](https://sharepoint.uservoice.com/).
Thank you

**Comment by nam31** [comment]
Hi @rednender Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
