### ISSUE TITLE
Question about the note on DMARC

### ISSUE THREAD

**Issue by manojska** [MicrosoftDocs/OfficeDocs-Support#679]
The note on DMARC states:
----
For forwarded messages, DKIM always fails because the signed DKIM domain does not match the From header domain.
-----

Why is that? 
Doesn't DKIM validate with alignment as long as the forwarding entity does not modify the message? Does O365 modify headers when emails are forwarded? Does O365 remove original DKIM signatures from the email when forwarding an email?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 230f187a-8786-947f-29b1-b28283f15872
* Version Independent ID: 6662debb-5bef-d33f-0f14-62e32ec65f84
* Content: [Sender Rewriting Scheme (SRS) in Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/antispam/sender-rewriting-scheme)
* Content Source: [Microsoft365/security/antispam/sender-rewriting-scheme.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/security/antispam/sender-rewriting-scheme.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by joinimran** [comment]
Hi @manojska, thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by msbemba** [comment]
@manojska Thank you for your feedback.  In the majority of cases, the DKIM signature (or the result of previous verification) is being retained during email auto-forward, which allows receiving server to make sure that received email is genuine . There are cases when the forwarder appends the compliance footer text to the received email and forwards or auto-forwards it, it alters the original message content, so it breaks message integrity. As a result, the receiving server will not be able to verify the DKIM signature, and the DKIM verification result.

Having said this, ARC(Authenticated Received Chain ) is a protocol designed to provide an authenticated "chain of custody" for messages making it possible for each of the users handling an email to see what other entities handled it previously, as well as determine its authentication assessment at each step during the delivery process.The ARC protocol supplements the DMARC and DKIM email authentication protocols as part of Internet Mail Handlers' effort to combat email spoofing especially when dealing with forwarded messages. A few years ago this was a real challenge for recipient servers to handle such non-authenticated but genuine emails but now, when many major email service providers started to use ARC Protocol, the situation has improved. 

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@manojska Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
