### ISSUE TITLE
still not working

### ISSUE THREAD

**Issue by adielDev** [MicrosoftDocs/OfficeDocs-Support#68]
running on https (green)
In fact, it's pretty weird. Because the logo does load but I still get this error message

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 236f9838-fd32-0154-122e-77725824160a
* Version Independent ID: 76d757f8-a4b1-3bb2-a186-a21b385c6b7e
* Content: [We can't open this add-in from localhost - Office](https://docs.microsoft.com/en-us/office/troubleshoot/error-messages/cannot-open-add-in-from-localhost#feedback)
* Content Source: [Office/Client/error-messages/cannot-open-add-in-from-localhost.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/error-messages/cannot-open-add-in-from-localhost.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by adielDev** [comment]
work around
change reference
from:
<bt:Url id="Commands.Url" DefaultValue="https://127.0.0.1:8000/commands.html" />
        <bt:Url id="Taskpane.Url" DefaultValue="https://127.0.0.1:8000/taskpane.html" />
to:
<bt:Url id="Commands.Url" DefaultValue="https://127.0.0.1:8000/src/commands/commands.html" />
        <bt:Url id="Taskpane.Url" DefaultValue="https://127.0.0.1:8000/src/taskpane/taskpane.html" />

**Comment by Joel-Intact** [comment]
Greetings, this solution does not fix the issue and is no longer applicable.

**Comment by stallter4** [comment]
Doesn't work.  Your out of the box javascript tutorial broke upon last windows update.  Good job Microsoft!

**Comment by nam31** [comment]
@adielDev We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
