### ISSUE TITLE
"relationship id rld8 was not found in the file" issue

### ISSUE THREAD

**Issue by mortkar** [MicrosoftDocs/OfficeDocs-Support#681]
We do a lot of document writing with screenshots. This error is becoming very troublesome. Is there a fix in the works to prevent this from happening? Our users aren't going to be able to always change it to a zip and adjust the xml. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca27a7a8-589a-70a8-699a-83821633a62b
* Version Independent ID: a275bcf8-bd79-8a99-e12b-9701d4259770
* Content: [The image part with relationship rID8 was not found in Microsoft Word - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/image-part-relationship-rld8-not-found-error-microsoft-word)
* Content Source: [Office/Client/word/image-part-relationship-rld8-not-found-error-microsoft-word.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/image-part-relationship-rld8-not-found-error-microsoft-word.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @todmccoy
* Microsoft Alias: **v-todmc, Shuvojit.Ray**

**Comment by nam31** [comment]
@mortkar this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@mortkar We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
