### ISSUE TITLE
Where is UCCP log?

### ISSUE THREAD

**Issue by GitHubSig** [MicrosoftDocs/OfficeDocs-Support#682]
The article mentions "UCCP log" multiple times, but contains no information about where to find that log.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4a4ba17-9f99-145f-f8da-2547e724f782
* Version Independent ID: bff3ecfe-e99c-949f-e130-0c56eb71e1b9
* Content: [Desktop or Application sharing can't connect in a conference - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/online-conferencing/sharing-cannot-connect)
* Content Source: [SkypeforBusiness/SkypeOnline/online-conferencing/sharing-cannot-connect.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeOnline/online-conferencing/sharing-cannot-connect.md)
* Service: **skype-for-business-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by get-itips** [comment]
Thanks for reporting @GitHubSig
