### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ffeldmann** [MicrosoftDocs/OfficeDocs-Support#683]
The provided link following is broken:

>  If the font is not a custom font and does not appear in your Office program, the font may be damaged. To reinstall the font, see Mac OS X: [Font locations and their purposes](https://support.apple.com/HT201722)

I suggest using this one:
https://support.apple.com/kb/HT201749

Best regards,
Felix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c84e63b-2dcc-235d-fe1a-55c6f9f3737c
* Version Independent ID: 86437368-0536-f947-b408-c53e63e0e2cf
* Content: [Third-party installed font does not appear in the font list in Word for Mac - Office](https://docs.microsoft.com/en-us/office/troubleshoot/third-party-add-ins/third-party-installed-font-fails-appearing)
* Content Source: [Office/Client/third-party-add-ins/third-party-installed-font-fails-appearing.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/third-party-add-ins/third-party-installed-font-fails-appearing.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The article is updated.
