### ISSUE TITLE
I have had the blank 2007 Excel when double clicking a file problem for a long time. None of the suggestions have worked. I have Windows 10 installed. I decided to go into the MS Office folder and right clicked on the Excel.exe and look around.  I found it was set to run in compatibility mode for Windows Vista.  Once I unchecked the compatibility option off it works fine.

### ISSUE THREAD

**Issue by buzard49** [MicrosoftDocs/OfficeDocs-Support#684]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62a88c46-43bb-92cf-c409-c8b3071b3865
* Version Independent ID: 19f5e98e-36a5-e2e9-39b1-5fc5ae349b50
* Content: [Excel opens a blank screen when you double-click a file icon or file name - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/excel-opens-blank)
* Content Source: [Office/Client/excel/excel-opens-blank.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/excel-opens-blank.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The article is updated with a note added at the end of the article.
