### ISSUE TITLE
Unable to get svrsetup.dll because the links do not point to .zip files.

### ISSUE THREAD

**Issue by JanTkacSk** [MicrosoftDocs/OfficeDocs-Support#685]
The following links on this page do not point to the .zip files.

•SharePoint Foundation 2013 with Service Pack 1 fix
•SharePoint Server 2013 with Service Pack 1 fix
•Project Server 2013 with Service Pack 1 fix

They point to download pages of service packs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f467ff86-48f6-82ea-817b-7d19b7b8ad02
* Version Independent ID: 3a81bc47-e572-4e7d-70a3-2706219d6657
* Content: [SharePoint 2013 or Project Server 2013 Setup error if the .NET Framework 4.6 is installed - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/installation-and-setup/setup-error-if-.net-framework-4.6-is-installed#feedback)
* Content Source: [SharePoint/SharePointServer/installation-and-setup/setup-error-if-.net-framework-4.6-is-installed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointServer/installation-and-setup/setup-error-if-.net-framework-4.6-is-installed.md)
* Service: **sharepoint-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments. The links are updated and available now.
