### ISSUE TITLE
Incorrectly references Outlook 2010 instead of 2013

### ISSUE THREAD

**Issue by bdleedy** [MicrosoftDocs/OfficeDocs-Support#687]
Basically anywhere 2010 is referenced, it should say 2013.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70dfdda1-e80e-5707-3ecb-38b689633075
* Version Independent ID: 4e53296e-25e1-7120-a563-6a008abb42fc
* Content: [No Add-ins loaded due to group policy settings - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/group-policy/office-add-in-not-loaded)
* Content Source: [Microsoft365/admin/group-policy/office-add-in-not-loaded.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/group-policy/office-add-in-not-loaded.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The article is updated.
