### ISSUE TITLE
d/mm/yyyy formatting

### ISSUE THREAD

**Issue by Plurpley** [MicrosoftDocs/OfficeDocs-Support#688]
Great project, thanks for posting this!  I have found this very useful in a timeline template I've been trying to create for a personal family history project.  Any chance you could write a variant that parses dates in the format d/mm/yyyy?  Regards, P.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ea64829-ed1c-dea9-0cba-6bfecff2ac35
* Version Independent ID: 27ec2e18-941b-9561-cf0f-c0b641321a85
* Content: [How to calculate ages before 1/1/1900 in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/calculate-age-before-1-1-1900)
* Content Source: [Office/Client/excel/calculate-age-before-1-1-1900.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/calculate-age-before-1-1-1900.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by lindspea** [comment]
@Plurpley thank you for reaching out and for the kind words.  I'm looking into this.

**Comment by lindspea** [comment]
@Plurpley it looks like the information has been updated. If not, try this and let me know if it works - Select a blank cell next to the dates you want to convert, type this formula =DATE (VALUE (RIGHT (A9,4)), VALUE (MID (A9,4,2)), VALUE (LEFT (A9,2),  drag fill handle over the cells which need to use this formula. Please let me know.

**Comment by nam31** [comment]
@Plurpley Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
