### ISSUE TITLE
Neither options fix the problem

### ISSUE THREAD

**Issue by CuchulainX** [MicrosoftDocs/OfficeDocs-Support#689]
Fiddler has been updated and no-longer has a Tools menu

CheckNetIsolation LoopbackExempt -a -n="microsoft.win32webviewhost_cw5n1h2txyewy"  runs without error but has no effect

:-(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a3d3e4f-e5cc-21ce-a0f7-4b32bfe03598
* Version Independent ID: 2ee272e9-df28-4a84-3d5e-ccde3affee42
* Content: [We can't open this add-in from localhost - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/cannot-open-add-in-from-localhost)
* Content Source: [Office/Client/office-suite-issues/cannot-open-add-in-from-localhost.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/cannot-open-add-in-from-localhost.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by lindspea** [comment]
@CuchulainX thank you for pointing this out. I'll do some investigating and make any necessary changes to the article.

**Comment by lindspea** [comment]
@CuchulainX Please let me know if you're still having this issue. I found a possible solution if it's still relevant. Please let me know if it works - Take your computer's IP address with IPconfig at the command prompt, then hit the service using the IP address rather than localhost.

**Comment by nam31** [comment]
@CuchulainX Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
