### ISSUE TITLE
No way to do this using powershell?

### ISSUE THREAD

**Issue by ewidance** [MicrosoftDocs/OfficeDocs-Support#69]
I got &gt; 90 lists on a Sharepoint app. 

I tried to get indexes on lists using powershell to 
1/ Get a backup on lists/fields with indexes
2/ Automate deindexing using ($Field.Indexed = $False)
3/ Change Regional settings
4/ Restore Indexes with $Field.Indexed = $True

Unfortunately, i can't figure out how to have a list of indexed fields..

It would be great to add a sample for doing it with powershell..

Thanks a lot!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50ef53e6-18c2-1ff4-403c-0774c06ef07b
* Version Independent ID: 4c1b05cc-49cc-4985-a52a-661ccfaca991
* Content: [Can't change locale setting for SharePoint Online public website - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/Sites/fails-changing-locale-setting#feedback)
* Content Source: [SharePoint/SharePointOnline/sites/fails-changing-locale-setting.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sites/fails-changing-locale-setting.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The article is retired. Thanks.
