### ISSUE TITLE
Text size limit- 32MB

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/OfficeDocs-Support#690]
[Enter feedback here]
There is also a 32MB limit on total text size, the rest of the 512MB is graphics and other non-text elements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d78d3ef8-de77-365b-2f50-1777a119a301
* Version Independent ID: 60ee27a7-a6a8-2452-fa37-5c531fac4b95
* Content: [Operating parameter limitations and specifications in Word - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/operating-parameter-limitation)
* Content Source: [Office/Client/word/operating-parameter-limitation.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/operating-parameter-limitation.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@Ronsss Thank you for your feedback. You are correct! The maximum file size Word can open is 512 MB, however, the Text limit cannot exceed 32MB. This has been added in "Note 1". Let me know if you would like to see any other changes in the document.

Thanks
Sri

**Comment by Ronsss** [comment]
Thanks for the update.
That is the only change I am aware of at this time.

**Comment by msbemba** [comment]
@Ronsss Thank you for confirming.

**Comment by nam31** [comment]
@Ronsss Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
