### ISSUE TITLE
The SpecialCells(xlCellTypeBlanks) VBA function does not work as expected in Excel

### ISSUE THREAD

**Issue by TrevMasson** [MicrosoftDocs/OfficeDocs-Support#693]
[Enter feedback here]

Your CAUSE statement is correct only in respect of the quantity issue.

It seems that the 365 MSO VBA compiler/interpreter is from pre 2010 when the Range().Validation only allowed a list to be on the SAME sheet.

The SpecialCells(xlCellTypeAllValidation) function ONLY RETURNS the validations on the SAME sheet

So the WORKAROUND proposed is not  suitable

The SpecialCells(xlCellTypeSameValidation) function will need to be looked at as well

MS Excel 2013 VBA works 100%  for these functions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48751ee4-2abe-453f-d2bd-816628770347
* Version Independent ID: 7409ae69-4f22-e382-1eb2-86f2a57773e4
* Content: [The SpecialCells(xlCellTypeBlanks) VBA function doesn't work as expected - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/specialcells(xlcelltypeblanks)-vba-function)
* Content Source: [Office/Client/excel/specialcells(xlcelltypeblanks)-vba-function.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/specialcells(xlcelltypeblanks)-vba-function.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by joinimran** [comment]
Hi @TrevMasson, thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by joinimran** [comment]
HI @TrevMasson, what changes you want to purpose in Document.

**Comment by joinimran** [comment]
Hello @TrevMasson - Can you please confirm what changes you want to purpose in the document so that I can work on those. 

Thanks
Imran.

**Comment by nam31** [comment]
@TrevMasson We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
