### ISSUE TITLE
Please add squirrel.exe into exclusion list as well

### ISSUE THREAD

**Issue by howardzhangmsft** [MicrosoftDocs/OfficeDocs-Support#694]
Per discussion with engineering team, please also add the following into exclusion list
%userprofile%\AppData\Local\Microsoft\Teams\stage\squirrel.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23989acb-65f2-d269-66c8-edcdd89c730d
* Version Independent ID: ef65785d-165f-6c91-1e9d-c4e99122c13f
* Content: [How to include or exclude Teams from antivirus or DLP applications - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-administration/include-exclude-teams-from-antivirus-dlp?source=docs)
* Content Source: [Teams/teams-administration/include-exclude-teams-from-antivirus-dlp.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-administration/include-exclude-teams-from-antivirus-dlp.md)
* Service: **teams**
* GitHub Login: @McCoyBot
* Microsoft Alias: **v-todmc**

**Comment by RAJU2529** [comment]
@howardzhangmsft .ok fine, I will create pr

**Comment by simonxjx** [comment]
PR is merged.
