### ISSUE TITLE
Some details not clear

### ISSUE THREAD

**Issue by jimmyeao** [MicrosoftDocs/OfficeDocs-Support#695]
[Enter feedback here]
Step 7 could use more details, for example how to identify the required GUIDs, what version of exchange (this doesnt work in Ex2010 for example, results in the error ```
version 
(14.3.470.0 ServerCaps:, ProxyCaps:, MailboxCaps:,
legacyCaps:05FFFF) isn't supported. Missing API: 'TenantHint')
```


---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b0eef03-98f2-0630-f331-6eedf8a98085
* Version Independent ID: 2302b229-aff5-d18d-dcb9-844a29e28728
* Content: [How to recover when a mailbox exists in both Exchange Online and on-premises - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/move-mailboxes/mailbox-exists-exo-onpremises)
* Content Source: [Exchange/ExchangeHybrid/move-mailboxes/mailbox-exists-exo-onpremises.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/move-mailboxes/mailbox-exists-exo-onpremises.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @TobyTu
* Microsoft Alias: **benwinz**

**Comment by nam31** [comment]
@jimmyeao The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by MaratMussabekov** [comment]
Hello @jimmyeao  ,
please have a look at #1568 
Thank you

**Comment by nam31** [comment]
Closing via #1568 
Thank you
