### ISSUE TITLE
Feedback Client Firewall

### ISSUE THREAD

**Issue by Azurstreams** [MicrosoftDocs/OfficeDocs-Support#699]
[For me, this error was client side. Outlook was blocked on the Norton firewall settings. The user was prompted to block or accept the program and inadvertently clicked to block Outlook.]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 925d55fa-04d9-3178-7404-b0d2a19c1f39
* Version Independent ID: c153c93a-2dea-ffc6-3689-b08498d717ba
* Content: [Can't send emails from security groups, distribution lists, or mail-enabled Public Folders in Outlook for Mac - Exchange](https://docs.microsoft.com/en-nz/exchange/troubleshoot/mailflow/outlook-mac-security-groups-cannot-send-emails)
* Content Source: [Exchange/ExchangeServer/mailflow/outlook-mac-security-groups-cannot-send-emails.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/mailflow/outlook-mac-security-groups-cannot-send-emails.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment.
