### ISSUE TITLE
What if there are no Target Applications?

### ISSUE THREAD

**Issue by jackcorbae** [MicrosoftDocs/OfficeDocs-Support#7]
New Sharepoint Site - unable to invite external users even though every setting we can find in the tenant Sharepoint/Teams/Office365 menu is set to allow access.

When I try the solution above - there are no target application IDs - just the message: 

"There are no Secure Store Target Applications in this Secure Store Service Application.  You can create a new Target Application from the Manage Target Applications group in the Edit ribbon group."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd14b953-36df-d55b-67ff-3b65500703fd
* Version Independent ID: 281b901e-47ef-d40c-3710-c05bda5b10f3
* Content: [You can't add external users to a SharePoint Online External Content Type in the SharePoint admin center](https://docs.microsoft.com/en-us/sharepoint/support/online-admin/cannot-add-external-users-to-content-type#feedback)
* Content Source: [SharePoint/SharePointOnline/online-admin/cannot-add-external-users-to-content-type.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/online-admin/cannot-add-external-users-to-content-type.md)
* Service: **sharepoint-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
To create a Secure Store Target Application, you can follow the steps on the following page:
https://docs.microsoft.com/en-us/sharepoint/create-or-edit-secure-store-target-application
