### ISSUE TITLE
Incorrect command

### ISSUE THREAD

**Issue by suyashbansal** [MicrosoftDocs/OfficeDocs-Support#70]
In the Method 3: Run Outlook commands, the first step that says "Click Start, enter outlook /cleanremindersin the search box, and then press Enter." is not totally correct. 

It seems that the command is "/cleanremindersin" which is not correct. Per the support page for Command-line switches for Outlook for Windows, the actual command is "/cleanreminders". The 'in' suffix is basically due to a missing space between the command and the rest of the sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 734a296a-533a-cf43-4545-7d3f04d8ae2d
* Version Independent ID: 89528fe2-4731-2262-999c-8aae458f4c88
* Content: [You can't remove a calendar item or an email message in Outlook in Office 365 - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/delete-calendar-items/cannot-remove-items#feedback)
* Content Source: [Exchange/ExchangeOnline/delete-calendar-items/cannot-remove-items.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/delete-calendar-items/cannot-remove-items.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by WKenya** [comment]
Looks like this was fixed here: https://github.com/MicrosoftDocs/OfficeDocs-Support/commit/77da565467828a411577187ac8e1bf6be02076ab

So this can probably be closed.

**Comment by ShawnTeng** [comment]
"/cleanremindersin" will make misunderstanding, please modify this.

**Comment by simonxjx** [comment]
Updated.
