### ISSUE TITLE
The export resolution of a PowerPoint 2013 32-bit slide does not change

### ISSUE THREAD

**Issue by andrescrecer** [MicrosoftDocs/OfficeDocs-Support#700]
Hi. I have MS Office 2013 32 bits in Spanish on my computer that has MS Windows 7 64 bits in Spanish and following the steps suggested on the website (https://docs.microsoft.com/en-us/office/troubleshoot/powerpoint/change-export-slide-resolution), it does not work. On another computer, which also has 64-bit MS Windows 7 in Spanish but with 32-bit MS Office 2016 in English, if it works.

What could I be doing wrong with Office 2013?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e390c4c9-9cdf-beb1-43dc-6ec45ae5fe77
* Version Independent ID: bb31c9ea-7186-22fb-195f-f481eb5137e4
* Content: [How to change the export resolution of a PowerPoint slide - Office](https://docs.microsoft.com/en-us/office/troubleshoot/powerpoint/change-export-slide-resolution)
* Content Source: [Office/Client/powerpoint/change-export-slide-resolution.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/powerpoint/change-export-slide-resolution.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. I recommend that you can contact [PowerPoint support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.powerpoint) for more help.
