### ISSUE TITLE
Wrong assumptions on the root cause

### ISSUE THREAD

**Issue by lukasmeirelles** [MicrosoftDocs/OfficeDocs-Support#701]
I have the same "The operation failed. The messaging interfaces have returned an unknown error." error message on sending email from Outlook 2016 MSO (16.0.13001.20266) 32-bit , but I have no profiles created other than Outlook's.

So I guess there's a false assumption on the root cause analysis of this issue.

On note on my issue: I'm not sure how that functionality got broken but it was working fine for some time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bef58e68-ac17-5161-b75c-e554a3810749
* Version Independent ID: c107ddda-c358-40b5-bb35-46fd7e7702c1
* Content: [The operation failed error when you send email messages in Outlook - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/mailflow/operation-failed-send-email-outlook)
* Content Source: [Exchange/ExchangeServer/mailflow/operation-failed-send-email-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/mailflow/operation-failed-send-email-outlook.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. If the resolution does not work, you can contact [Outlook support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.outlook) for more help.
