### ISSUE TITLE
Other affected tabs

### ISSUE THREAD

**Issue by Calvini03** [MicrosoftDocs/OfficeDocs-Support#702]
Other affected tabs include AzureDevOps Teams apps like Pipelines and Repos. Those Apps also rely on Web authentication. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f73d6049-fedc-2383-31cb-a6ec9a893398
* Version Independent ID: 7293fec6-c415-31ca-e106-27f9c252baeb
* Content: [Enabling Conditional Access in Teams causes tabs to stop working - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/known-issues/tabs-dont-work-after-enabling-conditional-access)
* Content Source: [Teams/known-issues/tabs-dont-work-after-enabling-conditional-access.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/known-issues/tabs-dont-work-after-enabling-conditional-access.md)
* Service: **msteams**
* GitHub Login: @McCoyBot
* Microsoft Alias: **v-todmc**

**Comment by nk-gears** [comment]
Hi @Calvini03, 

Thank you for your feedback. We will update the documentation to include the other affected app tabs after checking with our Internal Team.

Will keep you posted in couple of days.

**Comment by nam31** [comment]
@Calvini03 Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
