### ISSUE TITLE
The instructions are confusing.  

### ISSUE THREAD

**Issue by rw5207** [MicrosoftDocs/OfficeDocs-Support#703]
Please check the steps and ActivationFilter values of 0 and 1 and what they do, as the examples and steps don't seem to match.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0567ae9-af24-0539-261a-f9000c20c411
* Version Independent ID: e80b7bb2-771d-d4a1-abff-1dee32f066d7
* Content: [How to control the blocking of OLE/COM components in Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/updates/control-block-ole-com)
* Content Source: [Microsoft365/admin/updates/control-block-ole-com.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/updates/control-block-ole-com.md)
* Service: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@rw5207 Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1504

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1504 
Thank you

**Comment by nam31** [comment]
Closing via #1504
