### ISSUE TITLE
Doesn't work...

### ISSUE THREAD

**Issue by EnigmaV8** [MicrosoftDocs/OfficeDocs-Support#706]
This would be fantastic!  ...if it actually worked.  Rebooted, verified policy application via RSOP and verified available defaults in the referenced Reg key.  Policy does not apply on Windows 10; default app for Email is still set to "Choose default".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce321185-d005-bcfb-74bf-a23bd31850a6
* Version Independent ID: f96194ef-a823-7f29-fda3-4dc6e84f6831
* Content: [How to configure the default e-mail client using Group Policy - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/group-policy/configure-email-client-using-policy)
* Content Source: [Microsoft365/admin/group-policy/configure-email-client-using-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/group-policy/configure-email-client-using-policy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. You can contact [Outlook support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.outlook) for more help.
