### ISSUE TITLE
Apersand in proxyaddresses is not replaced

### ISSUE THREAD

**Issue by AlexCesarini** [MicrosoftDocs/OfficeDocs-Support#707]
I've been testing in a couple of environment and "&" in the **proxyaddresses** is actually not replaced with "_" as stated in the article, after the synchronization I can see 
SMTP:something&something@domain.com

I've also noticed a similar behavior with  the single quotation mark  ' - it does not get replaced with "_"
as I have
SMTP:something'else@domain.com

In what cases the ampersand and the single quotation mark are getting replaced with "_"?
Could the article be more specific?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0638257c-2829-38a7-6bd7-799b96ca8761
* Version Independent ID: 051d257b-e558-7dce-3714-c70fd56eecaa
* Content: [Office 365 email address contains underscore character - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/active-directory/email-address-contain-underscore)
* Content Source: [Microsoft365/admin/active-directory/email-address-contain-underscore.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/active-directory/email-address-contain-underscore.md)
* Service: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@AlexCesarini Thank you for your feedback. I'll test and update the document if need be.

**Comment by jlriesco** [comment]
@AlexCesarini Hi Alex, it would help us a lot if we could collect an example user id that got changed during synchronization? 

We can do a quick testing to confirm.  
Thanks,
Jose
