### ISSUE TITLE
Force new instance not working

### ISSUE THREAD

**Issue by djc2002us** [MicrosoftDocs/OfficeDocs-Support#709]
I added the DWORD and Excel still only opens new instances when I start it from the Search menu using Excel.com /X.

BTW, I consider this a major limitation as I need multiple instances so that Excel does not search and undo across totally unrelated files. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 970cf317-aa45-6f08-5edc-f40825391dca
* Version Independent ID: bc3709a7-0210-c17b-b130-79aa14a956d8
* Content: [Force Excel to open in a new instance by default - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/force-excel-to-open-new-instance)
* Content Source: [Office/Client/excel/force-excel-to-open-new-instance.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/force-excel-to-open-new-instance.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments. You can contact [Excel Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.excel) for more information.
