### ISSUE TITLE
Will this still work when VBScript support is removed from IE?

### ISSUE THREAD

**Issue by skane2600** [MicrosoftDocs/OfficeDocs-Support#71]
When VBScript is removed from IE 11 will this still work? I realize that this script doesn't explicitly use IE but it's not clear to me what the technical boundaries are between IE and it's associated technologies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f81ca9-b30c-86c1-cd3f-fdbf47d3132f
* Version Independent ID: ddde2391-3363-ac16-d0c8-d689e6a16b42
* Content: [How to automate Excel from a client-side VBScript - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-developer/automate-excel-from-client-side-vbscript#feedback)
* Content Source: [Office/Client/office-developer/automate-excel-from-client-side-vbscript.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-developer/automate-excel-from-client-side-vbscript.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by skane2600** [comment]
It's always unfortunate when capabilities are removed although done with
good intentions. But the issue for me was never about running scripts in a
browser, but rather running scripts outside the browser while still being
able to interact with Office. As you know, there was a period where
Microsoft tied other technologies to IE although it wasn't strictly
necessary, so it wasn't clear to me if removing scripting from Edge meant
removing it from Windows altogether.

**Comment by jlriesco** [comment]
VBScript is disabled in IE11 (Edge). It is not available in new browser versions like the new Edge/Chrome browsers, etc., and its use is generally no longer considered current practice.
VBScript is viable only with IE11 in compatibility mode, in legacy browsers, and for scripts run external to a browser in Windows Script Host.

**Comment by skane2600** [comment]
The fact that VBScript can still run in Windows Script Host is good news, although it's only relevant to me for the legacy support of an old application. Back in the day I chose that approach for a combination of reasons including the fact that scripting support was built-in and I wanted to control MS Office without embedding macros in the application or in the documents to be modified. I don't know if there's any other built-in Windows capability that can do the same. Perhaps PowerShell, I don't know.
