### ISSUE TITLE
Lost all calendar items. No warning.

### ISSUE THREAD

**Issue by georgegi** [MicrosoftDocs/OfficeDocs-Support#710]
Method #3 indicated to clear "Offline Items" without warning about what "offline items" are. After following that suggestion, all items in my calendar were removed. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 003b3cba-164f-4443-ad85-9509a54a125b
* Version Independent ID: c237b7a5-7b05-900d-adab-df43daed3d8a
* Content: [Calendar reminders in Outlook can't be dismissed or keep reappearing - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/calendar-reminders/cannot-dismiss-outlook-calendar-reminders)
* Content Source: [Exchange/ExchangeHybrid/calendar-reminders/cannot-dismiss-outlook-calendar-reminders.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/calendar-reminders/cannot-dismiss-outlook-calendar-reminders.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by get-itips** [comment]
Hello @georgegi George,
Can you kindly confirm if you also followed the 2nd step?

> 2. Select Send / Receive > Update Folder in the ribbon to force the items' download.

Thanks

**Comment by get-itips** [comment]
@georgegi George, could you see my message? I followed the instructions and the 2nd step downloaded the items from server.

**Comment by nam31** [comment]
@georgegi We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
