### ISSUE TITLE
Getting Excel Chart Data with VBA - Histograms issue

### ISSUE THREAD

**Issue by mgcasey300** [MicrosoftDocs/OfficeDocs-Support#711]
This VB codes doesn't seem to work with 'Histogram' excel charts. I am using excel 2016 and it fails on the activechart.seriescollection(1).values line.
Any one else have an alternate answer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34332ef-c11f-2a8e-cb2f-8c887bca0fb8
* Version Independent ID: e173df7e-69dc-b107-0d7b-33a6367540ce
* Content: [Macro to extract data from a chart in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/macro-retrieves-chart-data)
* Content Source: [Office/Client/excel/macro-retrieves-chart-data.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/macro-retrieves-chart-data.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nk-gears** [comment]
Hi @mgcasey300,

Thanks for reporting this.  

The mentioned error usually happens when there are no active charts selected.
Before Running the Macro, you need to select the Chart First. Can you try and confirm again.

**Comment by nk-gears** [comment]
@mgcasey300 Does that suggestion worked?.

**Comment by nam31** [comment]
@mgcasey300 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
