### ISSUE TITLE
Bad code

### ISSUE THREAD

**Issue by MauroDLB** [MicrosoftDocs/OfficeDocs-Support#714]
The code in the page it gives an error:

Where it says:
  minutes = Val(Mid(Degree_Deg, InStr(1, Degree_Deg, "°") + 2, _
    InStr(1, Degree_Deg,        '") - InStr(1, Degree_Deg, _
    "°") - 2)) / 60

It should say:

  minutes = Val(Mid(Degree_Deg, InStr(1, Degree_Deg, "°") + 2, _
    InStr(1, Degree_Deg,       **"** '") - InStr(1, Degree_Deg, _
    "°") - 2)) / 60

It lakc an " before the '. Because of that, its readed as comments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be969d50-8518-365f-f3ed-5c0e14d55104
* Version Independent ID: 11bad482-781b-bbae-ce60-53f8164d137e
* Content: [Convert degrees/minutes/seconds angles to or from decimal angles - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/convert-degrees-minutes-seconds-angles)
* Content Source: [Office/Client/excel/convert-degrees-minutes-seconds-angles.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/convert-degrees-minutes-seconds-angles.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The article is updated.
