### ISSUE TITLE
Seems to have been triggered

### ISSUE THREAD

**Issue by Baldgyt** [MicrosoftDocs/OfficeDocs-Support#715]
This problem only appeared for me after the deprecation in June.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5d228b-c88c-f396-0680-1974ee3836a9
* Version Independent ID: 5d4feafb-42dd-edce-4caa-06226cbd9e12
* Content: [Outlook search folders show unexpected mail items with an empty subject - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/search/personmetadata-items)
* Content Source: [Outlook/Client/search/personmetadata-items.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/search/personmetadata-items.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@Baldgyt The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content
Thank you.

**Comment by nam31** [comment]
@Baldgyt We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

**Comment by Baldgyt** [comment]
I have no idea what response you are seeking

I think I gave some feedback on an improvement to the text

**Comment by Baldgyt** [comment]
Thank you.

Looking at the original issue documentation I don’t think this has ongoing implications for documentation as after a further update to office 365 the issue went away (i.e. my occurrence was introduced by one software update and removed by another) – I didn’t use either of the workarounds MS appear to have fixed the software.

Regards

IanC
