### ISSUE TITLE
Clarification of Open Excel and Reasons to use this option

### ISSUE THREAD

**Issue by djc2002us** [MicrosoftDocs/OfficeDocs-Support#716]
The page should clarify how this option works. If you select a file in the Taskbar Excel Icon, it will not open in a new instance. It only opens in a new instance if you open Excel without a file selected, that is if you right-click and select Excel instead of a file.

I would change as follows:
This method works only when you do not select a file when opening Excel. If you use File Open within the Excel application, select a file from the Excel Taskbar icon,  or double-click a file in Windows Explorer, the files will still open in the same instance as designed.

In addition, you should change the description of why one would want to use this option. Since Excel in a single instance shares Undo and Find/Replace across all files open in an instance, if the files one is using are unrelated, this can cause unexpected consequences in undo and having to retype Find items when the user switches between files (since there is only one Find/Replace popup for all files in an instance). 

I would recommend the following wording: 
However, in some situations, you may want to open each file in a new instance. For example, if you're working with large Excel spreadsheets or if spreadsheet files are unrelated and you want "undo" and "Find/Replace" to work for each file independently.

Under Cause I would also add:
As Excel opens each spreadsheet file in one instance, only one set of Undo items is created for all such files. Hence, if you want to undo several items, undo may remove the changes across multiple files. If the files are unrelated, this may be an unexpected result. In addition, Excel has only one shared Find/Replace box. If your files are independent and you want to find items in each file with different Find strings, you will have to reenter the strings as you work between files. By opening each spreadsheet file as a separate instance, independent Undo lists and Find/Replace strings are created.

Hopefully, all of that is clear. It has been a major hassle for me for years and I have finally gotten around to dealing with it. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 970cf317-aa45-6f08-5edc-f40825391dca
* Version Independent ID: bc3709a7-0210-c17b-b130-79aa14a956d8
* Content: [Force Excel to open in a new instance by default - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/force-excel-to-open-new-instance)
* Content Source: [Office/Client/excel/force-excel-to-open-new-instance.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/force-excel-to-open-new-instance.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@e0i  this issue should be verified by experts

**Comment by msbemba** [comment]
@djc2002us Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1570

Thanks
Sri

**Comment by djc2002us** [comment]
Thanks. It looks much better. Wish this was fixed otherwise in Excel as described in the numerous complaints and suggestions but this at least states the situation correctly.

David
________________________________

**Comment by nam31** [comment]
Closing via #1570 
Thank you
