### ISSUE TITLE
Document is not correct and needs critical revision | There is no Fix

### ISSUE THREAD

**Issue by alumanos** [MicrosoftDocs/OfficeDocs-Support#718]
This article's information does not apply to SharePoint Online. SharePoint Online does not use ActiveX controls with Office. Instead, SharePoint Online pages use Javascript for FireFox, Microsoft Edge and Google Chrome in order to leverage the Office Client on the user's local machine.

"_Concerning Lync presence information on a SharePoint page, Chrome is deprecating the plug-in technology that made this feature work. We are currently working on a replacement. In the meantime, if you must access presence information in SharePoint, use Internet Explorer._"

This is not correct. The PG had decided to forego these efforts in SharePoint 2013 and newer, including SharePoint Online.

"_The fix for this issue has been rolled out as of August 11, 2015, and it should be in build 15.0.4745.1000 and later._"

This is also incorrect. The fallout of NPAPI deprecation was never addressed in SharePoint 2013, 2016, 2019 and technically also SharePoint Online. SharePoint PG attempted to address the issue in August 2015's SharePoint 2013 CU but was unsuccessful. A second attempt was released a year later in the August 2016 CU but also was not successful in fixing this issue. Related:

https://blogs.technet.microsoft.com/office_integration__sharepoint/2015/04/24/unable-to-open-sharepoint-documents-in-local-client-rich-client-from-chrome-due-to-npapi-plug-in-missing/

(^Article^ is gone with the deprecation of blogs, use internet archive or similar to pull the last accessible cached version of the page)

For example, if a SharePoint 2016 document library is set to have files "Open in Client" as the user's preference instead of "Open in Browser", the file will default to opening in the browser when the user is in a non-IE browser as there is no way for SharePoint to detect that the user has Office installed without ActiveX controls. There is no fix, only the workaround of using Internet Explorer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f639be5-bd1f-9c1c-7d6a-0fbec36eba76
* Version Independent ID: d65f878a-f75e-e9be-a7b9-8a1102d6b4fc
* Content: [Can't open documents in a local client from Chrome - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/lists-and-libraries/cant-open-sp-documents-from-chrome)
* Content Source: [SharePoint/SharePointServer/lists-and-libraries/cant-open-sp-documents-from-chrome.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointServer/lists-and-libraries/cant-open-sp-documents-from-chrome.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Sivaulis** [comment]
Hello Team, is there any update on this?

**Comment by simonxjx** [comment]
An Content Idea (CONTENT IDEA REQUEST 122116) is already created for this change and the change is being reviewed.

**Comment by nam31** [comment]
Closing via #929 
Thank you
