### ISSUE TITLE
The Fix it For Me 'Download' link leads to a 404 for me

### ISSUE THREAD

**Issue by LenCardinal** [MicrosoftDocs/OfficeDocs-Support#719]
In the Fix it For Me section, the Download link leads to a 404.
I tried a couple different browsers, and tried pasting the URL behind Download directly into the address bar. I ran Dev Tool network traces. The URL immediately returns a 404.
The link worked last week.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 291ef05d-5c3a-8179-8cfb-dd1af16db19b
* Version Independent ID: 68e35ec8-36bb-fdb8-9c7a-70b506cb2bdb
* Content: [Cannot locate the Internet or proxy server when selecting hyperlink in Office - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/cannot-locate-server-when-click-hyperlink#heres-an-easy-fix)
* Content Source: [Office/Client/office-suite-issues/cannot-locate-server-when-click-hyperlink.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/cannot-locate-server-when-click-hyperlink.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@LenCardinal .  Since the file  **MicrosoftEasyFix50655.msi** is  removed from the Microsoft download center, hence we getting 404.  
You can solve yourself by modifying the desired regsitry key.

**Comment by RAJU2529** [comment]
@simonxjx , Downloading file **MicrosoftEasyFix50655.msi** does not exist, So I think, we should remove that link from this article.

**Comment by LenCardinal** [comment]
It existed two weeks ago. I downloaded it on 5-Aug 2020
[cid:544f9fb1-46a7-4784-8768-4ea9f4ff29d5]
________________________________

**Comment by RAJU2529** [comment]
@LenCardinal . today I also checked, same error exits

**Comment by simonxjx** [comment]
As the download link is invalid in the article, I have removed it. Thanks.

**Comment by LenCardinal** [comment]
Shouldn't someone check with Support? Maybe it is just an issue with the download center.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by laurawalker** [comment]
So I found this article and then this issue whilst trying to resolve an problem with Excel on my personal machine opening certain hyperlinks incredibly slowly. This question: https://superuser.com/questions/562598/how-do-i-stop-excel-from-checking-the-validity-of-hyperlinks-before-it-opens-the points to this support article, and the person that answered it notes "I ran the "Fix it for me" application after several unsuccessful attempts to manually make the registry edits.". I now find myself in the same position - having manually added the keys I still have this issue. I would love to run the "Fix it now" to see if it resolves it - is this file still available somewhere?

**Comment by msbemba** [comment]
@laurawalker The Fix it link for MicrosoftEasyFix50655.msi  has been removed from the database and cannot be accessed anymore. Apparently, the fix it file also Adds the Internet Subkey to the registry and sets the Value data.

Hope this helps!
Thanks
Sri

**Comment by msbemba** [comment]
@laurawalker Hopefully we answered your question. Let us know if there are any other updates required in the document.

Thanks
Sri

**Comment by laurawalker** [comment]
> @laurawalker The Fix it link for MicrosoftEasyFix50655.msi has been removed from the database and cannot be accessed anymore. Apparently, the fix it file also Adds the Internet Subkey to the registry and sets the Value data.
> 
> Hope this helps!
> Thanks
> Sri

So what I think you're saying here is that the "fix it" tool simply added the same registry keys I was setting manually? 

FWIW those registry keys did not fix the issue I had.

**Comment by msbemba** [comment]
@laurawalker Sorry about that. you are right the fix-it is no longer available, so any reference to that has been removed from the document. The updated resolution mentioned in the document should work.

Thanks
Sri

**Comment by nam31** [comment]
@laurawalker Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
