### ISSUE TITLE
Missing Vertical Scrollbar in Word 365

### ISSUE THREAD

**Issue by eenberg** [MicrosoftDocs/OfficeDocs-Support#720]
After losing my vertical scrollbar in Word and performing a Quick Repair and online Repair for my Office 365 Word app, my vertical scrollbar did not reappear. After toying around with the toolbar choices, I found that right-clicking on either toolbar at the top of Word and selecting Maximize from the drop-down menu restored it. I had not found this suggestion in any of the top suggestions to solve this problem. It was such an easy fix. :-)

P.S,, selecting Restore on the same menu removes the scrollbar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04a174f0-107a-caf2-09b0-003c90fa1d2f
* Version Independent ID: 91df925f-965a-b706-384e-11e1b66c0e65
* Content: [Scroll bars are missing in Word for Mac - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/word-scroll-bars-missing)
* Content Source: [Office/Client/word/word-scroll-bars-missing.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/word-scroll-bars-missing.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@eenberg . Thanks for the new idea, let authors wil  decide to add your idea. 
Keep posting your ideas to improve documents

**Comment by simonxjx** [comment]
Close this one as the article is already redirected.
