### ISSUE TITLE
Please unify the path TEMPLATES not TEMPLATE 

### ISSUE THREAD

**Issue by wpm-blog** [MicrosoftDocs/OfficeDocs-Support#722]
[Enter feedback here]
There are different path informations for the templates of word and powerpoint. Sometimes \TEMPLATE\, sometimes \TEMPLATES\ ... it is "\TEMPLATES\". It confused me a lot using these informations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1b1afea-11f2-eb9e-19c4-3a9feb973181
* Version Independent ID: c811b9d5-7dc7-4afe-b395-69fdad2ac496
* Content: [Set the default font for Office applications - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/set-default-font)
* Content Source: [Office/Client/office-suite-issues/set-default-font.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/set-default-font.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by RAJU2529** [comment]
@wpm-blog . i am creating PR  now
