### ISSUE TITLE
Question on the TLS 1.2 issue with Office Online Server

### ISSUE THREAD

**Issue by PhuVHuynh** [MicrosoftDocs/OfficeDocs-Support#723]
[Enter feedback here]

Do we need to add the same registry keys to the SharePoint 2016 servers that have OS 2016?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b358195-5c58-761b-404d-245c799a7b59
* Version Independent ID: a6ec5581-c38a-3775-2315-19b093c20d5d
* Content: [Documents aren't displayed in web browser when you're using TLS 1.2 - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/lists-and-libraries/documents-not-displayed-in-web-browser-when-using-tls-1.2)
* Content Source: [SharePoint/SharePointOnline/lists-and-libraries/documents-not-displayed-in-web-browser-when-using-tls-1.2.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/lists-and-libraries/documents-not-displayed-in-web-browser-when-using-tls-1.2.md)
* Service: **sharepoint-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@PhuVHuynh Thank you for your feedback. This issue and cause only pertain to Sharepoint online troubleshooting. There is no requirement to change or add keys on the SharePoint 2016 servers.

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@PhuVHuynh Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
