### ISSUE TITLE
missing space

### ISSUE THREAD

**Issue by bsoutham** [MicrosoftDocs/OfficeDocs-Support#724]
>> Configureyour tenant to grant
should be
Configure your tenant to grant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4b2c631-b8d1-a6f4-e777-cea00732319b
* Version Independent ID: 9219f097-7d77-3096-153d-ae188a9ed7f6
* Content: [Grant Everyone claim to external users in Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/grant-everyone-claim-to-external-users)
* Content Source: [Microsoft365/admin/access-management/grant-everyone-claim-to-external-users.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/access-management/grant-everyone-claim-to-external-users.md)
* Service: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment, the article is updated.
