### ISSUE TITLE
Document not recovered

### ISSUE THREAD

**Issue by tokiioKH** [MicrosoftDocs/OfficeDocs-Support#725]
I tried all the steps to try to recover my documents but nothing. Can anyone help me?

Thanks!
[Poem 5.docx](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/5079967/Poem.5.docx)
[Poem 6.docx](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/5079968/Poem.6.docx)
[Poem 1.docx](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/5079969/Poem.1.docx)
[Poem 2.docx](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/5079970/Poem.2.docx)
[Poem 3.docx](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/5079971/Poem.3.docx)
[Poem 4.docx](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/5079972/Poem.4.docx)

**Comment by nam31** [comment]
@tokiioKH The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@tokiioKH We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
