### ISSUE TITLE
registry path is not in bold

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-Support#726]
Registry path is not bold, hence this article needs to edited.
I need permission from author to make registry path as bold. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 291ef05d-5c3a-8179-8cfb-dd1af16db19b
* Version Independent ID: 68e35ec8-36bb-fdb8-9c7a-70b506cb2bdb
* Content: [Cannot locate the Internet or proxy server when selecting hyperlink in Office - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/cannot-locate-server-when-click-hyperlink#heres-an-easy-fix)
* Content Source: [Office/Client/office-suite-issues/cannot-locate-server-when-click-hyperlink.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/cannot-locate-server-when-click-hyperlink.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. I have made the path bold in the article.
