### ISSUE TITLE
4k is not the same as HDR

### ISSUE THREAD

**Issue by rmanjoney** [MicrosoftDocs/OfficeDocs-Support#728]
4k is not the "same" as HDR. 4k, roughly speaking, is a display resolution, while HDR refers to the monitor's ability to display a wide-range of brightnesses simultaneously. Not all 4k monitors are HDR, and vice versa. 

This article is also confusing because it doesn't state whether the slowness occurs just by virtue of having the external 4k monitor docked, or whether you actually have to have the Teams meeting video being displayed on that monitor. In other words, if I am using my built-in laptop's native monitor for Teams, yet also have an external 4k monitor docked that is displaying some other apps, does that cause slowness? My guess is that the # of users who are using 4k monitors that are also HDR capable, *and* being driven by the required graphics hardware to support HDR are a small percentage of users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df6fe49-939e-8330-07a1-49ff0a2c4ab7
* Version Independent ID: f7cc79e9-6e2a-17a4-36ec-743acc0d679a
* Content: [Teams is slow during video meetings on laptops docked to 4K/HDR monitors - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/known-issues/teams-slow-video-meetings-laptops-4k)
* Content Source: [Teams/known-issues/teams-slow-video-meetings-laptops-4k.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/known-issues/teams-slow-video-meetings-laptops-4k.md)
* Service: **msteams**
* GitHub Login: @v-miegge
* Microsoft Alias: **sgorantl**

**Comment by dariomws** [comment]
Hi @rmanjoney, thank you for your feedback and sorry for the delay.

I think the article talks more generically about high-tech or new-tech monitors with 4K or HDR (or even other features). The first sentence states:
"This can occur if a laptop is docked to an external 4K **or** ultra-high-definition"

I also understand that the article is talking about turning on the video on the 4K monitor. This is a relatively well-known issue and affects other applications too, not only Microsoft Teams.

**Comment by rmanjoney** [comment]
"This can occur if a laptop is docked to an external 4K or ultra-high-definition" – neither of these 2 concepts (4k or ultra-high-definition) has anything to do with HDR. HDR is an entirely different feature/capability and it isn’t present on most monitors. HDR has nothing to do with image resolution or definition. Just because a monitor is 4k, high-tech, etc. doesn’t mean it also has HDR.

Those of us who are trying to troubleshoot and resolve the issues we have with Teams, like myself are confused by this article because it conflates two completely separate technologies. I as the user asks, “Well, which is the culprit? The fact that I am using a 4K monitor? Or that I am using HDR? Or both” I can usually turn off HDR independently for troubleshooting, but the if it’s the panel’s native resolution that is the problem? You’re stuck with that.
