### ISSUE TITLE
This fix did not work for me, though I do have Visual Studio 2019 installed

### ISSUE THREAD

**Issue by dwinrow** [MicrosoftDocs/OfficeDocs-Support#73]
This fix did not work for me, though I do have Visual Studio 2019 installed

The crash is occurring from Spreadsheet Compare 2013, I am unable to compare any spreadsheets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 975c1291-1a98-75a2-4cff-6dde6b8592b8
* Version Independent ID: 6069e03d-05d8-a750-0922-6bfba198bca4
* Content: [Unable to cast COM object when exporting to Excel from Team Explorer 2008 - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/team-explorer-export-fails#feedback)
* Content Source: [Office/Client/excel/team-explorer-export-fails.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/team-explorer-export-fails.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@dwinrow, this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@dwinrow We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
