### ISSUE TITLE
RegKey Name "wrong"

### ISSUE THREAD

**Issue by cmakas** [MicrosoftDocs/OfficeDocs-Support#730]
Hello!

In this article only "Database Size Limit" is formated so highlighted but the correct name is "Database Size Limit in GB".
So " in GB" should also be formated like "Database Size Limit".
(Sorry for my bad english - I hope you understand what I mean.)

Best regards,
 Christian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1affc88-0ec5-ad3f-9793-b110d5ec2b53
* Version Independent ID: 6f779b3e-c052-94d1-15fe-e8e360bb9367
* Content: [Can't mount databases that are larger than 1024 GB - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/exchange-cannot-mount-database-larger-than-1024-gb?source=docs)
* Content Source: [Exchange/ExchangeServer/administration/exchange-cannot-mount-database-larger-than-1024-gb.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/administration/exchange-cannot-mount-database-larger-than-1024-gb.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by RAJU2529** [comment]
@cmakas. Article authors will investigate your issue. So keep waiting for the reply

**Comment by simonxjx** [comment]
Thanks for your comment. The article is updated.
