### ISSUE TITLE
Feedback on 1904/1900 date discrepancy - Excel

### ISSUE THREAD

**Issue by noustsgit** [MicrosoftDocs/OfficeDocs-Support#731]
This page was a great help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8462f7c-3fcb-c891-cca9-8c1ff894d4b0
* Version Independent ID: 78b5d0d6-6de5-e495-20a6-c5b9c34046f7
* Content: [Differences between the 1900 and the 1904 date system - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/1900-and-1904-date-system)
* Content Source: [Office/Client/excel/1900-and-1904-date-system.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/1900-and-1904-date-system.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. It is good to know that the page is helpful.
