### ISSUE TITLE
The referenced download doesn't match the content.

### ISSUE THREAD

**Issue by forktrucka** [MicrosoftDocs/OfficeDocs-Support#732]
Have encountered this problem. Have followed the link as suggested to get the SharePoint 2013 Foundation fix, and am instead getting the SharePoint Foundation 2013 with SP1 download.

My issue is I'm trying to install onto an Azure VM with Server 2012 R2, and the Azure provided image has .NET Framework 4.7 installed by default, and the media won't allow me to install...

have tried the updated installer. same problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f467ff86-48f6-82ea-817b-7d19b7b8ad02
* Version Independent ID: 3a81bc47-e572-4e7d-70a3-2706219d6657
* Content: [SharePoint 2013 or Project Server 2013 Setup error if the .NET Framework 4.6 is installed - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/installation-and-setup/setup-error-if-.net-framework-4.6-is-installed)
* Content Source: [SharePoint/SharePointServer/installation-and-setup/setup-error-if-.net-framework-4.6-is-installed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointServer/installation-and-setup/setup-error-if-.net-framework-4.6-is-installed.md)
* Service: **sharepoint-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@forktrucka . Try to disable .net 4.7 through windows feature option. Then try to install SharePoint.

**Comment by forktrucka** [comment]
Hi,
I wasn't able to disable the feature.

I have traced the issue back to an update that is installed onto the Azure Image by default, which isn't included in the list you've provided. This is KB4054566. By uninstalling that update it drops .NET Framework back to v4.5.51641, I'm going to try this in my environment today, I'm hopeful this should satisfy the requisite for the SharePoint Binaries installer.

**Comment by forktrucka** [comment]
Yes. Confirm. Uninstalling that KB resolves my issue. I am able to install the SharePoint binaries

**Comment by simonxjx** [comment]
Thanks for your comments. The links are updated and available now.
