### ISSUE TITLE
unable to update notes under contact information of a o365 user using powershell

### ISSUE THREAD

**Issue by rizwanassad** [MicrosoftDocs/OfficeDocs-Support#734]

**Comment by RAJU2529** [comment]
@rizwanassad , Which article are you referring?

**Comment by nam31** [comment]
@rizwanassad The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@rizwanassad We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
