### ISSUE TITLE
Suggested Resolution Addition

### ISSUE THREAD

**Issue by jackedwards97** [MicrosoftDocs/OfficeDocs-Support#737]
**Good Afternoon,

I encountered this issue today. Tested on various accounts and the issue persisted on both the Outlook program and the 365 Application. From the 365 Exchange Portal I went to the Shared Mailboxes section, highlighted the mailbox, and converted it to a standard mailbox. I then went into Mailboxes, and changed it back. This immediately resolved this issue. 

Might be worth mentioning in the article. 

Cheers,
Jack**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c037327-3311-a6c5-9510-48ea6aaa5a43
* Version Independent ID: a744bf09-7b1c-2590-7cd6-67fbb7910dd5
* Content: [Can't send email message when Full Access is granted to a shared mailbox - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/mailflow/cannot-send-email-with-full-access)
* Content Source: [Exchange/ExchangeServer/mailflow/cannot-send-email-with-full-access.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/mailflow/cannot-send-email-with-full-access.md)
* Service: **exchange-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment.
