### ISSUE TITLE
"Cannot download the information you requested" is a completely unacceptable error message

### ISSUE THREAD

**Issue by SudoCerb** [MicrosoftDocs/OfficeDocs-Support#741]
I am generally impressed with how far MS has come with their software, but if anything, your error messages have become less and less useful in your attempts to make them less intimidating.

I'm just trying to paste a hyperlink in a presentation and am greeted by this useless error message. I don't want to have to come to GitHub to solve this problem, can you imagine a non-developer trying to fix this problem.

I'm just furious that this doesn't work.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 291ef05d-5c3a-8179-8cfb-dd1af16db19b
* Version Independent ID: 68e35ec8-36bb-fdb8-9c7a-70b506cb2bdb
* Content: [Cannot locate the Internet or proxy server when selecting hyperlink in Office - Office](https://docs.microsoft.com/en-gb/office/troubleshoot/office-suite-issues/cannot-locate-server-when-click-hyperlink)
* Content Source: [Office/Client/office-suite-issues/cannot-locate-server-when-click-hyperlink.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/cannot-locate-server-when-click-hyperlink.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft and your comments. If you have any feedback to the products, you can contact [Office Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.office-support).
