### ISSUE TITLE
Already set up on attempted login

### ISSUE THREAD

**Issue by TomWLake** [MicrosoftDocs/OfficeDocs-Support#743]
[Enter feedback here]This pertains to the web page on the message "Someone has already set up Teams for your organisation.  The "Symptoms" describe this as occurring on attempting to set up an account but I see it on attempting to log in to Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab509e31-52d3-be39-501a-aef6c701201c
* Version Independent ID: 4c2f3f40-91ca-7bb2-3090-6fd38ba82f40
* Content: [Someone has already setup Teams for your organization error in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/someone-has-already-setup-teams)
* Content Source: [Teams/teams-sign-in/someone-has-already-setup-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/someone-has-already-setup-teams.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @TobyTu
* Microsoft Alias: **Bill.Kaupp**

**Comment by nk-gears** [comment]
Hello @TomWLake,

Thanks for reporting this Issue. We understand that the error occurred when you try to Login to Teams. 

This usually happens when you try to sign In using your Personal EmailId in the Work Account. Please confirm are you using a Free Personal EmailId or a Work Email Id to Login to Teams ?

**Comment by nk-gears** [comment]
@TomWLake Did you get a chance to check this ?

**Comment by nam31** [comment]
@TomWLake We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
