### ISSUE TITLE
Exchange 2019 Database Limit

### ISSUE THREAD

**Issue by iliyasshaikh786** [MicrosoftDocs/OfficeDocs-Support#744]
What about the database limits in Exchange server 2019? This article does not specifically talk about 2019. Appreciate your feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1affc88-0ec5-ad3f-9793-b110d5ec2b53
* Version Independent ID: 6f779b3e-c052-94d1-15fe-e8e360bb9367
* Content: [Can't mount databases that are larger than 1024 GB - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/exchange-cannot-mount-database-larger-than-1024-gb)
* Content Source: [Exchange/ExchangeServer/administration/exchange-cannot-mount-database-larger-than-1024-gb.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/administration/exchange-cannot-mount-database-larger-than-1024-gb.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by nam31** [comment]
@iliyasshaikh786 this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@iliyasshaikh786 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
