### ISSUE TITLE
Can not send OOF to EVERY message by using inbox rules

### ISSUE THREAD

**Issue by Gonesy** [MicrosoftDocs/OfficeDocs-Support#747]
[Enter feedback here]

+ Customer complained they can not send OOF to EVERY message by using inbox rules.
+ Then i did test, it really doesn't work!
+ The problem is on the Microsoft page it says "If you would like to have a reply sent for every message, use Rules instead of the Out of Office Assistant."  https://docs.microsoft.com/en-us/exchange/troubleshoot/client-connectivity/one-reply-sent-sender

Now i don't know how to answer my customer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586ba5d7-6b64-530f-7448-186c6abe19c2
* Version Independent ID: 6d64b831-2220-99db-010e-790d8abd114c
* Content: [Only one reply is sent to each sender when Out of Office Assistant is enabled - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/client-connectivity/one-reply-sent-sender)
* Content Source: [Exchange/ExchangeServer/client-connectivity/one-reply-sent-sender.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/client-connectivity/one-reply-sent-sender.md)
* Service: **exchange-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. If you have any issue with setting OOF message in Outlook, you can contact [Outlook Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.outlook) for help.
