### ISSUE TITLE
Tables are displayed wrong

### ISSUE THREAD

**Issue by david-netc** [MicrosoftDocs/OfficeDocs-Support#748]
Hello,

The tables are all displayed wrong on this page.  It is not readable.

Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef984ce5-63ef-6a3d-8ff8-17d170046037
* Version Independent ID: 4c5d6728-a132-8cd8-9d10-83d1ff6e08c8
* Content: [A federated user is repeatedly prompted for credentials during sign-in - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/sign-In/federated-user-repeatedly-prompted-for-credentials)
* Content Source: [Microsoft365/admin/sign-in/federated-user-repeatedly-prompted-for-credentials.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/sign-in/federated-user-repeatedly-prompted-for-credentials.md)
* Service: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The tables are fixed in the article.
