### ISSUE TITLE
Document does not address all cases of the problem

### ISSUE THREAD

**Issue by kmwilber** [MicrosoftDocs/OfficeDocs-Support#749]
No one has set up Teams for my organization.  I am just me, on a personal Windows Computer, using the same email address I use to login to my personal Windows account, which is has Office365 on it.  My email is just my email, not an employer's email.  There is no Active Directory with me in it, anywhere.  I have no work or school credentials.

Yet, trying to use Teams (free version), gives me the "Someone has already set up Teams in your organization" error. 

I've seen other reports of this same problem, under the same conditions I'm reporting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab509e31-52d3-be39-501a-aef6c701201c
* Version Independent ID: 4c2f3f40-91ca-7bb2-3090-6fd38ba82f40
* Content: [Someone has already setup Teams for your organization error in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/someone-has-already-setup-teams)
* Content Source: [Teams/teams-sign-in/someone-has-already-setup-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/someone-has-already-setup-teams.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @TobyTu
* Microsoft Alias: **Bill.Kaupp**

**Comment by TobyTu** [comment]
@kmwilber thanks for your feedback, in this situation, I suggest you contact Microsoft support for assistance.
