### ISSUE TITLE
This needs more clarification 

### ISSUE THREAD

**Issue by zarney03** [MicrosoftDocs/OfficeDocs-Support#75]
You state the following below but you also override the verdict given by Microsoft ATP which is a paid subscription. Additionally overriding RFC's like SPF, DKIM and DMARC should not be allowed. You need to add these Risks into this document and call them out. People purchase ATP not expecting it to be overridden by a client side safe sender list. 

We recommend that you do not use these features because they may override the verdict that is set by Office 365 spam filters. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d39c3f-93c5-f920-5148-8069f5021c83
* Version Independent ID: d1e51705-dec0-baee-80f2-71499fd31b52
* Content: [Cautions against bypassing Office 365 spam filters. - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/antispam/cautions-against-bypassing-spam-filters#feedback)
* Content Source: [Exchange/ExchangeOnline/antispam/cautions-against-bypassing-spam-filters.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/antispam/cautions-against-bypassing-spam-filters.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-zht**

**Comment by nam31** [comment]
@zarney03 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
