### ISSUE TITLE
Excel trendlines not working

### ISSUE THREAD

**Issue by SumpAlarm** [MicrosoftDocs/OfficeDocs-Support#750]
[Enter feedback here]

Im sorry, but there are two problems with this post. 
- First, the "workaround" is terrible written. We have increased to 30 decimal places on every axis, and all the original data. 
- Second, the trendline produced does not even have the same shape over any range examined.
- Third, the workaround should not be necessary. It should do what it was made to do without the user having to invest the time to check Microsoft's work.

It is incumbent upon Microsoft to make tools that always work, not tools that might work and ask the user to search the web for other information to fix them.

Scott@SumpAlarm.Com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2767b894-13dd-fe66-2fea-689d7adaa55d
* Version Independent ID: c8dcc1a3-0526-51a4-7e47-6bc4a919831e
* Content: [Chart trendline formula is inaccurate in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/inaccurate-chart-trendline-formula)
* Content Source: [Office/Client/excel/inaccurate-chart-trendline-formula.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/inaccurate-chart-trendline-formula.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by xinnek** [comment]
I agree with SumpAlarm. This is ridiculous. So far I've spent over a week trying to fix something that worked previously to an update by Microsoft. WTH???? I've been using this same worksheet, producing the same trendlines for years, and one update wipes it out and Microsoft says to look for a workaround? This is seriously an issue that no one appears to care about and needs to be fixed asap without a workaround.

**Comment by dariomws** [comment]
@SumpAlarm @xinnek Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/answers/products/m365).
