### ISSUE TITLE
Url Typo

### ISSUE THREAD

**Issue by O365scripts** [MicrosoftDocs/OfficeDocs-Support#751]
Not sure if anyone has noticed but there's a typo in the link itself in the word "displayed".

Do we add a redirect and/or change the other docs where this page is being referenced?

Thanks and good luck!

https://docs.microsoft.com/en-us/exchange/troubleshoot/meetings/conference-rooms-not-dispalyed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1e6278-ea7f-4eea-fbb1-f2de033ee400
* Version Independent ID: a90193e5-6ed9-8f29-d342-008e6cc904e9
* Content: [Room Finder doesn't display any conference rooms when a user creates a meeting - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/meetings/conference-rooms-not-dispalyed)
* Content Source: [Exchange/ExchangeOnline/meetings/conference-rooms-not-dispalyed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/meetings/conference-rooms-not-dispalyed.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The link is updated.
