### ISSUE TITLE
Page heading needs correction

### ISSUE THREAD

**Issue by RohitY24** [MicrosoftDocs/OfficeDocs-Support#753]
The page header is currently shown as {"Microsoft cannot be opened because of a problem" error when you start an Office program}. The support article title should be corrected to {"Microsoft ***program*** cannot be opened because of a problem" error when you start an Office program}. The right title is reflected correct in the webpage title, but not on the document header.

Image for reference: ![image](https://user-images.githubusercontent.com/35281343/91736040-be7cea00-ebca-11ea-8c14-68fd5d335ecc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e001fd7b-9321-0520-04c7-0cebce108509
* Version Independent ID: 0ebc16f7-97a9-e1c0-6b53-1340b5dd2789
* Content: [Microsoft program cannot be opened because of a problem - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/microsoft-program-cannot-be-opened)
* Content Source: [Office/Client/office-suite-issues/microsoft-program-cannot-be-opened.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/microsoft-program-cannot-be-opened.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@RohitY24 , thanks for reporting, I am fixing now.

**Comment by RohitY24** [comment]
Thank you for the update!

**Comment by RAJU2529** [comment]
@RohitY24. New changes will be published  only after  merging from the article author

**Comment by simonxjx** [comment]
The change is applied. Thanks.
