### ISSUE TITLE
Uninstall instructions do not remove all Skype for Business files (macOS)

### ISSUE THREAD

**Issue by PerMildner** [MicrosoftDocs/OfficeDocs-Support#755]
After following the steps in this document, there are still a lot of things in my file system that look as if they are related to the Skype for Business application, and should have been removed:

```
% sudo find / -xdev -iname '*skypeforbusiness*' 2>/dev/null
/System/Volumes/Data/private/var/folders/yt/g4309t6d6m50dn_g25g551rc0000gp/T/com.microsoft.SkypeForBusiness
/System/Volumes/Data/private/var/folders/yt/g4309t6d6m50dn_g25g551rc0000gp/C/com.microsoft.SkypeForBusiness
/System/Volumes/Data/private/var/folders/yt/g4309t6d6m50dn_g25g551rc0000gp/C/com.microsoft.SkypeForBusiness/com.microsoft.SkypeForBusiness
/System/Volumes/Data/Users/perm/Library/Receipts/SkypeForBusiness.Client.Plugin.plist
/System/Volumes/Data/Users/perm/Library/Receipts/SkypeForBusiness.Client.Plugin.bom
/System/Volumes/Data/Users/perm/Library/Application Support/Google/Chrome/NativeMessagingHosts/com.microsoft.skypeforbusiness.shellapp.json
/System/Volumes/Data/Users/perm/Library/Saved Application State/com.microsoft.skypeforbusiness.shellapp.savedState
/System/Volumes/Data/Users/perm/Library/Preferences/com.microsoft.skypeforbusiness.plugin.plist
/System/Volumes/Data/Users/perm/Library/Logs/SkypeForBusinessPlugin
/System/Volumes/Data/Users/perm/Library/Internet Plug-Ins/HIDE Internet Plug-Ins/SkypeForBusinessPlugin-15.8.bundle
/System/Volumes/Data/Users/perm/Library/Internet Plug-Ins/HIDE Internet Plug-Ins/SkypeForBusinessPlugin-15.8.bundle/Contents/Skype for Business Web App.app/Contents/Resources/AppIcon-SkypeForBusiness.icns
/private/var/folders/yt/g4309t6d6m50dn_g25g551rc0000gp/T/com.microsoft.SkypeForBusiness
/private/var/folders/yt/g4309t6d6m50dn_g25g551rc0000gp/C/com.microsoft.SkypeForBusiness
/private/var/folders/yt/g4309t6d6m50dn_g25g551rc0000gp/C/com.microsoft.SkypeForBusiness/com.microsoft.SkypeForBusiness
/Users/perm/Library/Receipts/SkypeForBusiness.Client.Plugin.plist
/Users/perm/Library/Receipts/SkypeForBusiness.Client.Plugin.bom
/Users/perm/Library/Application Support/Google/Chrome/NativeMessagingHosts/com.microsoft.skypeforbusiness.shellapp.json
/Users/perm/Library/Saved Application State/com.microsoft.skypeforbusiness.shellapp.savedState
/Users/perm/Library/Preferences/com.microsoft.skypeforbusiness.plugin.plist
/Users/perm/Library/Logs/SkypeForBusinessPlugin
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5738299a-feb3-740e-aa42-5814f797a607
* Version Independent ID: e5373833-2a2e-0c3b-03fb-933de37c0d42
* Content: [How to do a clean uninstallation of Skype for Business on Mac - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/server-install-or-uninstall/clean-uninstallation)
* Content Source: [SkypeforBusiness/SkypeServer/server-install-or-uninstall/clean-uninstallation.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeServer/server-install-or-uninstall/clean-uninstallation.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
Hi @PerMildner this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@PerMildner We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
