### ISSUE TITLE
ExO Automapping

### ISSUE THREAD

**Issue by TripleStackJack** [MicrosoftDocs/OfficeDocs-Support#756]
Seems a rather poor design to have a Mbx tied attribute that can only be 'set' by deleting the all ACL's.  Let me guess, you forgot about Automapping and your solution is to make all the Exch Admins do work twice.  I for one, will be very happy to out Microsoft in person, next time I'm in Redmond for any reason.  Really, you should have started development with the Corporate side, and add the single-user, small biz last.  Microsoft's lack of planning/mgmt shows, in many places of their cloud, performance, uptime, usability, migration, hybrid, etc.  NRFPT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd6c33b6-24fb-447d-e9de-c5f11f0aaaae
* Version Independent ID: f5fd953d-bcbf-9315-8336-e43c20ef8022
* Content: [Remove automapping for a shared mailbox - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/domain-management/remove-automapping-for-shared-mailbox)
* Content Source: [Outlook/Client/domain-management/remove-automapping-for-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/domain-management/remove-automapping-for-shared-mailbox.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@TripleStackJack The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content
Thank you.

**Comment by nam31** [comment]
@TripleStackJack We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
