### ISSUE TITLE
Template file location

### ISSUE THREAD

**Issue by bep-puch** [MicrosoftDocs/OfficeDocs-Support#757]
I tried to change my template file location - because it is almost impossible to find it because Microsoft has hidden it so well that when I need to access it, I end up wasting hours;  So the instructions work well for the first two steps - open word, selection Options - and then nothing works.  I'm told to look up file locations in the advanced tab but there is no 'file location'.  I don't understand why templates have to be just a difficult thing with MS - they can be so time saving, but then they are lost in space somewhere so you keep having to recreate them if you need to make changes.  
So the instructions are a big FAIL!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a489782-9398-4158-b630-ec82ee7d82dc
* Version Independent ID: 390f26e1-4ee0-4d01-4637-c25d1cee01ae
* Content: [Manage Office programs templates - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/manage-office-program-templates)
* Content Source: [Office/Client/office-suite-issues/manage-office-program-templates.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/manage-office-program-templates.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@bep-puch . will you record video , upload I'm YouTube, paste the link here, so that I will analyze.
also which office suite are you using

**Comment by joinimran** [comment]
I am looking into this.

**Comment by joinimran** [comment]
Hello @bep-puch, I have followed the instructions, and it's working for me. Please ensure that you are opening a document and then follow the instructions.
![image](https://user-images.githubusercontent.com/47118050/120752500-4362ae80-c523-11eb-83c6-3c582464ddb3.png)

Thanks.

**Comment by helenclu** [comment]
@bep-puch , after you select **Advanced**, you need to scroll down to find the **General** section (as shown in the screenshot above).

**Comment by nam31** [comment]
@bep-puch Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
