### ISSUE TITLE
SSPR+Azure MFA | Even we registered contact details (phone number) still we are getting the POP-UP as we as not getting the sign in profile page 

### ISSUE THREAD

**Issue by harichettuva** [MicrosoftDocs/OfficeDocs-Support#759]
We have enabled SSPR+Azure MFA, only 4-5 users getting the pop-up for information (in case users not registered in azure for this) We verified contact details already updated in azure ad. 

As expected popup, whoever not registered in azure AD.
![image](https://user-images.githubusercontent.com/70627708/91944748-33ac0480-ed1c-11ea-9bc6-90cc0c3d0c47.png)
When we accessing the https://mysignins.microsoft.com or profile URL
![image](https://user-images.githubusercontent.com/70627708/91944567-e9c31e80-ed1b-11ea-88de-a3453c6207e6.png)
Looking at here, shows cookies not downloading. Do anyone how to forcefully download this cookies if that true? (no GPO restricting this)
![image](https://user-images.githubusercontent.com/70627708/91944617-fd6e8500-ed1b-11ea-8bab-3499bda92cef.png)

Do anyone knows how to resolve this issue.

**Comment by RAJU2529** [comment]
@harichettuva . Which article are you referring?

only azure experienced users can give the answer.

**Comment by nam31** [comment]
@harichettuva The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@harichettuva We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
