### ISSUE TITLE
The link at the bottom on GOP AutoDiscover only applies to 2007/2010

### ISSUE THREAD

**Issue by GLComputing** [MicrosoftDocs/OfficeDocs-Support#76]
Specifically, I'm looking at how to disable ExcludeExplicitO365Endpoint by GP.
There's nothing on that setting in this doc on that setting 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: L2VuLXVzL29mZmljZTM2NS90cm91Ymxlc2hvb3QvYWRtaW5pc3RyYXRpb24vdW5leHBlY3RlZC1hdXRvZGlzY292ZXItYmVoYXZpb3I=
* Version Independent ID: L2VuLXVzL29mZmljZTM2NS90cm91Ymxlc2hvb3QvYWRtaW5pc3RyYXRpb24vdW5leHBlY3RlZC1hdXRvZGlzY292ZXItYmVoYXZpb3I=
* Content: [Unexpected Autodiscover behavior if settings under the \Autodiscover key - Office 365 | Microsoft Docs](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/unexpected-autodiscover-behavior)
* Content Source: [Microsoft365/admin/administration/unexpected-autodiscover-behavior.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/unexpected-autodiscover-behavior.md)

**Comment by nam31** [comment]
@GLComputing We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
