### ISSUE TITLE
This page doesn't provide useful information?

### ISSUE THREAD

**Issue by riw777** [MicrosoftDocs/OfficeDocs-Support#760]
This page doesn't actually say anything useful about the problem, such as why this occurs, or how to solve it. The message says "you must move the original appointment," but this message appears _even when_ trying to move the "original appointment" from one calendar to another.

/r

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 515b498e-7336-7f01-ba1e-a309e00ed808
* Version Independent ID: 9222469d-2201-b22e-0366-bc17a7910799
* Content: [Cannot move the items error when you copy an appointment to an Outlook.com folder - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/migration/error-copy-appointment-to-outlook-com-folder)
* Content Source: [Exchange/ExchangeServer/migration/error-copy-appointment-to-outlook-com-folder.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/migration/error-copy-appointment-to-outlook-com-folder.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@riw777 Thank you for your feedback. The issue depends on how you are trying to move and what view you have set on your outlook 

The following table summarizes what occurs when you move or copy appointments to an EAS-based store.



![image](https://user-images.githubusercontent.com/45987684/123160909-629e8d00-d48c-11eb-8fb0-1f0156a348f8.png)

Hope this helps!
Thanks
Sri

**Comment by msbemba** [comment]
@riw777 Just wanted to circle back and check if you still have any questions or if there are any specific updates that you would like to see in the document.

**Comment by nam31** [comment]
@riw777 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
