### ISSUE TITLE
Needs more information about connecting to Windows Remote PowerShell

### ISSUE THREAD

**Issue by dchrno** [MicrosoftDocs/OfficeDocs-Support#761]
```
Step 1
5. Start Windows PowerShell, and then connect to Windows Remote PowerShell.
```

It would be very helpful with pointers or information about how you connect to Windows Remote PowerShell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a93c78d-ed18-2fda-d8bb-9f60f64fbc0f
* Version Independent ID: a79b1742-f841-c8a5-71f6-1c1dda533d6a
* Content: [How to use mailbox audit logs in Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/audit-logs/mailbox-audit-logs)
* Content Source: [Microsoft365/compliance/audit-logs/mailbox-audit-logs.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/compliance/audit-logs/mailbox-audit-logs.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. A link to Running Remote Commands is added.
