### ISSUE TITLE
Garbage decision making again at MS

### ISSUE THREAD

**Issue by dacoach01** [MicrosoftDocs/OfficeDocs-Support#763]
Whom ever felt this was an appropriate way for the software to function made a mistake.  Full size charts are used extensively and now show as unchangeable postage stamp sized collections of garbage when opened in O365, and must be moved to a new sheet and manually resized.  Utter garbage decision making this spec behavior. Shame.

Jason
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f428514-cce2-3051-fa06-c1f262a1b5eb
* Version Independent ID: cb087206-afff-96d3-1ac5-bb4205658990
* Content: [Cannot Resize the Chart Area of a chart - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/cannot-resize-chart-area)
* Content Source: [Office/Client/excel/cannot-resize-chart-area.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/cannot-resize-chart-area.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. If you have further feedback to the products, you can contact [Excel Support](https://support.microsoft.com/en-us/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.excel).
