### ISSUE TITLE
Article links to incorrect author profile

### ISSUE THREAD

**Issue by Sivaulis** [MicrosoftDocs/OfficeDocs-Support#764]
Hi team,

"https://social.technet.microsoft.com/profile/Al+-+MSFT" is not my account. I'm not sure who's account that is, but my profile is linked here: https://social.technet.microsoft.com/profile/alan%20umanos/ though it may be better to use https://docs.microsoft.com/en-us/users/alumanos/.

![account](https://user-images.githubusercontent.com/52183103/92038488-13d70980-ed39-11ea-93a3-b4b0cd19a225.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4546c262-297f-e4a4-e6ff-54500bc9245a
* Version Independent ID: ccca9836-cce8-75a2-ea7e-e4e18d100cda
* Content: [Credential prompts when opening documents by persistent cookies - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sharing-and-permissions/credential-prompt-persistent-cookies)
* Content Source: [SharePoint/SharePointExperts/sharing-and-permissions/credential-prompt-persistent-cookies.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointExperts/sharing-and-permissions/credential-prompt-persistent-cookies.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **arhinesm**

**Comment by simonxjx** [comment]
Thanks for your comment. The link is updated.
