### ISSUE TITLE
Need to include Exchange 2019 version in the article

### ISSUE THREAD

**Issue by Smartboss88** [MicrosoftDocs/OfficeDocs-Support#765]
Article is applicable to 2019 version of Exchange as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1affc88-0ec5-ad3f-9793-b110d5ec2b53
* Version Independent ID: 6f779b3e-c052-94d1-15fe-e8e360bb9367
* Content: [Can't mount databases that are larger than 1024 GB - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/exchange-cannot-mount-database-larger-than-1024-gb)
* Content Source: [Exchange/ExchangeServer/administration/exchange-cannot-mount-database-larger-than-1024-gb.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/administration/exchange-cannot-mount-database-larger-than-1024-gb.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by AmandaAZ** [comment]
Thanks for your comment. A similar feedback had been submitted so close this one.
