### ISSUE TITLE
Expected outcome for step 7 (it's not what you would expect)

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Support#766]
Hello,

I've been discussing this in the comments of the Exchange team blog post (https://techcommunity.microsoft.com/t5/exchange-team-blog/my-user-has-a-mailbox-both-on-premises-and-in-exchange-online/bc-p/1632851#M28763) and with Microsoft Support (case 21556719).

When you keep the EXO mailbox and restore the on-premises mailbox into the EXO mailbox via EXO-PowerShell -> New-MailboxRestoreRequest, the mailbox restore request will always end in status "**FailedOther**".  However, even with this failure status, if we look at the statistics of the restore request, particularly the report, as long as we can see in the "Copy Progress" that all expected items copied, we can consider the job a success.  To find the Copy Progress entry, this following command can be used.  Note it will be the 2nd to last entry in the report that shows Copy Progress, and the last entry will be where the underlying error is shown (which is a negligible error):

```
Get-MailboxRestoreRequest "<mailbox's ID>" | Get-MailboxRestoreRequestStatistics -IncludeReport | select -ExpandProperty Report | select -ExpandProperty Entries | select -Last 2


CreationTime               : 7/21/2020 12:16:36 AM
ServerName                 : YTBPR01MB4016
Type                       : Informational
TypeInt                    : 0
Flags                      : None
FlagsInt                   : 0
Message                    : Copy progress: 799/799 messages, 25 MB (26,215,094 bytes)/25 MB (26,215,094
                             bytes), 0/0 folders completed.
MessageData                : {0, 1, 0, 0...}
MessageBytes               : {10, 68, 67, 111...}
Failure                    :
BadItem                    :
ConfigObject               :
MailboxSize                :
SessionStatistics          :
ArchiveSessionStatistics   :
MailboxVerificationResults : {}
DivergenceFixupResults     : {}
DebugData                  :
Connectivity               :
SourceThrottleDurations    :
TargetThrottleDurations    :
UnknownElements            :
UnknownAttributes          :
XmlSchemaType              :
LocalizedString            : 7/21/2020 12:16:36 AM [YTBPR01MB4016] Copy progress: 799/799 messages, 25 MB
                             (26,215,094 bytes)/25 MB (26,215,094 bytes), 0/0 folders completed.
Identity                   :
IsValid                    : True
ObjectState                : New

CreationTime               : 7/21/2020 12:16:36 AM
ServerName                 : YTBPR01MB4016
Type                       : Error
TypeInt                    : 4
Flags                      : Failure, Fatal
FlagsInt                   : 18
Message                    : Fatal error RecipientNotFoundPermanentException has occurred.
MessageData                : {0, 1, 0, 0...}
MessageBytes               : {10, 29, 70, 97...}
Failure                    : RecipientNotFoundPermanentException: Cannot find a recipient that has mailbox
                             GUID '2ed5d0ca-54e2-4226-a4ce-a48848e18c0f'.
BadItem                    :
ConfigObject               :
MailboxSize                :
SessionStatistics          :
ArchiveSessionStatistics   :
MailboxVerificationResults : {}
DivergenceFixupResults     : {}
DebugData                  :
Connectivity               :
SourceThrottleDurations    :
TargetThrottleDurations    :
UnknownElements            :
UnknownAttributes          :
XmlSchemaType              :
LocalizedString            : 7/21/2020 12:16:36 AM [YTBPR01MB4016] Fatal error
                             RecipientNotFoundPermanentException has occurred.
Identity                   :
IsValid                    : True
ObjectState                : New
```

I can submit a PR to add something to cover this, but wanted to open it as an issue in case there is any feedback you would like to give me before I do.  Just let me know.  If nothing within a few days, I'll do a PR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b0eef03-98f2-0630-f331-6eedf8a98085
* Version Independent ID: 2302b229-aff5-d18d-dcb9-844a29e28728
* Content: [How to recover when a mailbox exists in both Exchange Online and on-premises - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/move-mailboxes/mailbox-exists-exo-onpremises)
* Content Source: [Exchange/ExchangeHybrid/move-mailboxes/mailbox-exists-exo-onpremises.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/move-mailboxes/mailbox-exists-exo-onpremises.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @TobyTu
* Microsoft Alias: **benwinz**

**Comment by TobyTu** [comment]
@JeremyTBradshaw Thanks for your feedback, you can go ahead to create a PR. Once it's approved by SMEs, I will update this article.
