### ISSUE TITLE
Please add information for synced identities

### ISSUE THREAD

**Issue by philschman** [MicrosoftDocs/OfficeDocs-Support#768]
It would be good if you add the information how to change the display language for a synced identity (via AAD Connect) from On-Prem AD. This can be done by the On-Prem attribute "preferredLanguage".

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c5d2597-6e11-7c74-1af1-50dd21364593
* Version Independent ID: 4bdf974e-3408-1408-6272-96323b0ad7b6
* Content: [Set language and region settings for Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/set-language-and-region)
* Content Source: [Microsoft365/admin/access-management/set-language-and-region.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/access-management/set-language-and-region.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@philschman this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@philschman We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
