### ISSUE TITLE
Outlook 2016 for Mac → Outlook.exe /resetfolders

### ISSUE THREAD

**Issue by erik-alm** [MicrosoftDocs/OfficeDocs-Support#769]
The following methods are guaranteed not to work on a mac:

* Method 1: Use the /resetfolders switch — suggests opening run dialogs in Windows and run ".exe"-files
* Method 3: Use the Set-MailboxRegionalConfiguration cmdlet — suggests running PowerShell scripts (I don't even want to know if Mac OS has a PowerShell implementation)

I suggest you drop the "for Mac" in the title, remove the Mac incompatible solutions, or figure out Mac alternatives for them. Given the state of this article, I also suggest you verify the other solutions actually do work for a Mac. Sure, you may have to use a Mac... put on MOPP4-gear if it scares you... :]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 255b5732-ef8a-f040-4cde-d9fc40486764
* Version Independent ID: 053a2e2a-d7a1-2562-8d83-b65263c6ec92
* Content: [Email messages are stuck in Outbox in Outlook 2016 for Mac - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/send-receive-emails/email-stuck-in-outbox-outlook-2016-mac)
* Content Source: [Outlook/Mac/send-receive-emails/email-stuck-in-outbox-outlook-2016-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Mac/send-receive-emails/email-stuck-in-outbox-outlook-2016-mac.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@erik-alm this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@erik-alm We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
