### ISSUE TITLE
Advice for "all other issues" is completely wrong.

### ISSUE THREAD

**Issue by SilvermaneStarlight** [MicrosoftDocs/OfficeDocs-Support#77]
I am using the most recent drivers for my GPU and this problem occurs quite often. I am experiencing the all white or all black display issue. Typing "make text size bigger" at the start menu and switching the scaling to something else and back to its original setting fixes this issue.

On the "more information" section: I find it difficult to understand just why Microsoft Office applications need to be hardware accelerated at all. I'm sure most people will get by just fine if their word processor doesn't make use of their GPU. In fact, I'd prefer this, as it will eliminate this issue entirely, especially on laptops that tend to switch GPU from a high performance chip to the integrated one on the CPU die when they're unplugged to save power.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d43aa283-d5e9-9b92-a7c9-f6bacede1b19
* Version Independent ID: 44cfded9-2ef6-751a-6558-b3bb21e35534
* Content: [Display issues in Office client applications. - Office](https://docs.microsoft.com/en-us/office/troubleshoot/troubleshooting/office-display-issues#feedback)
* Content Source: [Office/Client/troubleshooting/office-display-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/troubleshooting/office-display-issues.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@SilvermaneStarlight, this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@SilvermaneStarlight We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
