### ISSUE TITLE
Powershell parameter is incorrect

### ISSUE THREAD

**Issue by joaolloureiro** [MicrosoftDocs/OfficeDocs-Support#772]
Please change the following line from:

Invoke-RestMethod -Uri "https://outlook.office365.com/autodiscover/autodiscover.json?Email=onpremisemailbox@contoso.com&Protocol=EWS&RedirectCount=5" -Agent Teams

To:

It should be -useragent
Invoke-RestMethod -Uri "https://outlook.office365.com/autodiscover/autodiscover.json?Email=onpremisemailbox@contoso.com&Protocol=EWS&RedirectCount=5" - UserAgent Teams

There was a typo when document was initially submitted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b88a6c5-1b3e-88df-c08d-046f69974039
* Version Independent ID: 531fedcc-8032-fbb2-e41a-9fdaa00b1cde
* Content: [Troubleshoot Microsoft Teams and Exchange Server interaction issues - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/known-issues/teams-exchange-interaction-issue)
* Content Source: [Teams/known-issues/teams-exchange-interaction-issue.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/known-issues/teams-exchange-interaction-issue.md)
* Service: **microsoft-teams**
* GitHub Login: @TobyTu
* Microsoft Alias: **chunlli**

**Comment by TobyTu** [comment]
@joaolloureiro thanks for your feedback, I'll update the article.
