### ISSUE TITLE
F4 Key Does Not Work in Office 365

### ISSUE THREAD

**Issue by writer0101** [MicrosoftDocs/OfficeDocs-Support#775]
[I am very disappointed to see that the F4 key no longer works in Office. I use this key daily. The workaround of "repeat the action" is unhelpful. Certainly, that's the only option and not truly a workaround.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a16b8a6-c655-18ec-8ff5-9eba866e1dba
* Version Independent ID: 841a97ff-8c0e-712c-7bfb-e7863bc5662b
* Content: [F4 keyboard shortcut does not work as expected in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/f4-keyboard-shortcut-not-work)
* Content Source: [Office/Client/excel/f4-keyboard-shortcut-not-work.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/f4-keyboard-shortcut-not-work.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@writer0101 Thank you for your feedback. This is a known issue in Excel 2013, Excel 2010, and Excel 2007. If you are using other versions of office , make sure that you’ve got the Function Lock feature of your keyboard enabled.

Hope this helps!
Thanks
Sri

**Comment by msbemba** [comment]
@writer0101 Just wanted to circle back and check if you still have any questions or if there are any updates required on the document.

Thanks
Sri

**Comment by nam31** [comment]
@writer0101 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
