### ISSUE TITLE
Easiest items, especially Option 8, should be listed first.

### ISSUE THREAD

**Issue by shmuelgerber** [MicrosoftDocs/OfficeDocs-Support#776]
Option 8, "Check for hidden sheets", is surely the most common scenario and is the easiest to fix. Therefore it should be listed as number 1.
In general, these solutions should be listed in order from easiest fix/least destructive to hardest fix/most destructive:
- Check for hidden sheets
- Minimizing and maximizing the window
- Disable hardware acceleration
- Ignore DDE
- Reset file associations
- Repair User Experience Virtualization (UE-V)
- Repair Office (why is this titled "Delete the Word Options registry key"?)
- Turn off add-ins
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62a88c46-43bb-92cf-c409-c8b3071b3865
* Version Independent ID: 19f5e98e-36a5-e2e9-39b1-5fc5ae349b50
* Content: [Excel opens a blank screen when you double-click a file icon or file name - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/excel-opens-blank)
* Content Source: [Office/Client/excel/excel-opens-blank.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/excel-opens-blank.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@shmuelgerber we are going to close this issue as the article has been updated accordingly. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
