### ISSUE TITLE
Page is outdated

### ISSUE THREAD

**Issue by chudkins** [MicrosoftDocs/OfficeDocs-Support#777]
The screenshots and instructions for accessing a mailbox using Outlook on the web are outdated.  As of 2020-09-09, there is no name to right-click on.  Instead, you can access another mailbox by left-clicking on your initials in the upper right corner.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 722948e8-902c-db34-a359-0f3b22200e5d
* Version Independent ID: e4a97de8-7d7f-904f-c611-4f76f48891d1
* Content: [Accessing other people's mailboxes - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/shared-mailboxes/how-to-access-other-mailboxes)
* Content Source: [Exchange/ExchangeOnline/shared-mailboxes/how-to-access-other-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/shared-mailboxes/how-to-access-other-mailboxes.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by get-itips** [comment]
Thanks for reporting @chudkins
