### ISSUE TITLE
I have powerpoint 2016 but there is no "Options" folder under the Powerpoint registry key.

### ISSUE THREAD

**Issue by ATXdesigns** [MicrosoftDocs/OfficeDocs-Support#778]
When I go to this registry location:
HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\PowerPoint\

There is no "Options" folder. The only key under Powerpoint is "Security.

I even added a new key called "Options" and added the ExportBitmapResolution Dword and it makes no difference.

Can you help?

**Comment by nam31** [comment]
@ATXdesigns The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you

**Comment by nam31** [comment]
@ATXdesigns We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
