### ISSUE TITLE
Please help with end tag error: file cannot be opened there are problems with the contents.  The name in the end tag of the element must match the element type in the start tag.

### ISSUE THREAD

**Issue by weksnyder** [MicrosoftDocs/OfficeDocs-Support#779]
[This article didn't solve my problem.  I need help fixing a word error file cannot be opened there are problems with the contents.  The name in the end tag of the element must match the element type in the start tag.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 254fb058-8211-1997-7ef0-c0f1164998bb
* Version Independent ID: 218c84ac-4c57-d52c-fd56-d8b9d30f0fd9
* Content: [You receive an end tag error when you open a DOCX file in Word 2013, 2010, or 2007 - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/end-tag-error-when-open-docx)
* Content Source: [Office/Client/word/end-tag-error-when-open-docx.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/end-tag-error-when-open-docx.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by simonxjx** [comment]
Thanks for your comment. You can contact [Word Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.word) for more help if the issue persists.
