### ISSUE TITLE
Issue because of unsupported reminder times

### ISSUE THREAD

**Issue by Everything-is-taken** [MicrosoftDocs/OfficeDocs-Support#78]
Had the same issue - I was unable to successfully dismiss or open some reminders in my birthday calendar. Turns out, you can set the reminder for "9AM at day of event" in the web-based calendar (Office365), which effectively sets the reminder time to -9 hours, but the desktop version of Outlook is unable to process negative reminder values. After I changed the reminder to "None" (or any non-negative value), everything worked as expected.

**Comment by nam31** [comment]
@Everything-is-taken The issues section of this repository is intended for product documentation issues only. 
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@Everything-is-taken We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
