### ISSUE TITLE
Mention that Exchange 2010 source server doesn't support remote restore

### ISSUE THREAD

**Issue by miryb** [MicrosoftDocs/OfficeDocs-Support#780]
[Scenario 1 Step 7:  it is not supported to remote restore a disconnected mailbox from Exchange 2010 on-premises source server version, it needs to be minimum Exchange 2013 version.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b0eef03-98f2-0630-f331-6eedf8a98085
* Version Independent ID: 2302b229-aff5-d18d-dcb9-844a29e28728
* Content: [How to recover when a mailbox exists in both Exchange Online and on-premises - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/move-mailboxes/mailbox-exists-exo-onpremises)
* Content Source: [Exchange/ExchangeHybrid/move-mailboxes/mailbox-exists-exo-onpremises.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/move-mailboxes/mailbox-exists-exo-onpremises.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @TobyTu
* Microsoft Alias: **benwinz**

**Comment by TobyTu** [comment]
yes, it applies to exchange 2013 and the later versions. you could check **Applies to** section in the article.

**Comment by miryb** [comment]
I am talking from my experience in support, the applies section is overlooked by customers, also Scenario 2 is applicable to Exchange 2010 hybrid environments, also Scenario 1 is partially applicable to Exchange 2010 as well,  it is just the remote restore step from Scenario 1 not supported in Exchange 2010. 
And also our last line mentioning Exchange 2010 doesn't help here and makes it more confusing: 
A member of the Organization Management or Recipient Management group in **Exchange 2010** or above.

Can you please put a Note and make it obvious for customers?

**Comment by TobyTu** [comment]
@miryb thanks for clarifying. In this situation, could you file a CI via https://dev.azure.com/contentidea/ContentIdea/_workitems/create/Content%20Idea%20Request? The SMEs will review this request, once it's approved. I will update the article. Thx!

**Comment by miryb** [comment]
I opened Content Idea Request 123270 and it has been approved.

**Comment by TobyTu** [comment]
the note has been added to the article.
