### ISSUE TITLE
Duplicate email copies on my mailbox

### ISSUE THREAD

**Issue by kum6v** [MicrosoftDocs/OfficeDocs-Support#781]
**Scenario:**
user1@abc.com who has mailbox configured, is part of 3 alias mailer groups as below:
alias1@abc.com
alias2@abc.com
alias3@abc.com

When a user2 sends an email to 3 aliases(alias1,alias2,alias3) simultaneously, user1@abc.com gets 3 copies of same email

**Question** 
1. is this a normal behaviour?
2. If yes, can we configure the exchange server to send only one email , instead of 3 same mails? please advise.

**Comment by nam31** [comment]
@kum6v The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you

**Comment by nam31** [comment]
@kum6v We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
