### ISSUE TITLE
Table not formatted in Format a Date/Time field section.

### ISSUE THREAD

**Issue by AndrewDarkicorn** [MicrosoftDocs/OfficeDocs-Support#782]
In the "Format a Date/Time field" section, the text states "The following table shows how Access stores Date/Time values. The following table also shows how you can display those values by using different formats:" but the text following it has not been formatted as a table, so it appears as the literal text
|Stored value (double number)| Default format (General Date)| Custom format (mm/dd/yyyy hh:nn:ss A.M./P.M.)| |-------------------|---------------------|-----------------------------| |36295.0| 5/15/99| 05/15/1999 12:00:00 AM| |0.546527777777778| 1:07 PM| 12/30/1899 01:07:00 PM| |36232.9375| 3/13/99| 10:30PM 03/13/1999 10:30:00 PM|

The table data needs to be shown as a table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4d1ad1e-ae6a-3eff-7941-b282fffce250
* Version Independent ID: 205a62d0-ee1c-ace5-aa27-77bae04978ce
* Content: [Store, calculate, and compare Date/Time data - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/store-calculate-compare-datetime-data)
* Content Source: [Office/Client/access/store-calculate-compare-datetime-data.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/store-calculate-compare-datetime-data.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by simonxjx** [comment]
Thanks for your comments. The table is fixed.
