### ISSUE TITLE
Links don't update unless "ask to update" is checked

### ISSUE THREAD

**Issue by donfaison** [MicrosoftDocs/OfficeDocs-Support#783]
per this page "When the Ask to update automatic links check box is cleared, the links are automatically updated"  is NOT true.  I have it that way, but I must manually update everytime.  Windows 10 Professional, Excel 365 v16
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8675d7c-0870-b2c1-f442-867164e2949d
* Version Independent ID: 3cc6eaf5-37fa-b835-4d81-d3a83e9922bc
* Content: [Control the startup message about updating linked workbooks - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/control-startup-message)
* Content Source: [Office/Client/excel/control-startup-message.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/control-startup-message.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@donfaison this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@donfaison We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
