### ISSUE TITLE
SCOM shows warnings after Exchange 2016 CU17 Installation

### ISSUE THREAD

**Issue by BeatBrunner** [MicrosoftDocs/OfficeDocs-Support#786]
We have installed Exchange 2016 CU17 and afterwards, we have done the change in web.config like decribed in the article. But then, SCOM have started to show warnings:

Alert: Exchange Health Set
Source: SV*****EX02 - ECP
Path: SVPRWEX02.corp.********.com;SVPRWEX02.corp.********.com
Last modified by: System
Last modified time: 9/14/2020 10:56:32 AM Alert description: Exchange Admin Center is failing to respond to ping request on Mailbox server SV*****EX02.
Availability has dropped to 4REPLACE_PERCENT_SIGN. You can find protocol level traces for the failures on C:\Program Files\Microsoft\Exchange Server\V15\Logging\Monitoring\ECP\EacBackEndPingProbe.

After removing the change in the web.config, the warnings in SCOM disapears, but we are not longer able to show the OU list in EAC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebca74ee-463b-8322-5ee2-30813ddb8127
* Version Independent ID: d9b59f78-7db7-29cb-90b1-986128786674
* Content: [Exchange Server doesn't display all OUs - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/exchange-server-not-display-all-ou)
* Content Source: [Exchange/ExchangeServer/administration/exchange-server-not-display-all-ou.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/administration/exchange-server-not-display-all-ou.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by nam31** [comment]
@BeatBrunner this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by BeatBrunner** [comment]
@nam31 Do not see an update. Are there any news about this topic?

**Comment by nam31** [comment]
Hi @BeatBrunner, were you able to check?

**Comment by nam31** [comment]
@BeatBrunner We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
