### ISSUE TITLE
Sample GUID shows wrong information

### ISSUE THREAD

**Issue by anlorint** [MicrosoftDocs/OfficeDocs-Support#790]
In this article, we have the following example: 

_Sample GUID
Assume that the first 16 digits of a GUID are **"90160000-0011-0407."** This example GUID was created by the initial release build (9) **of a Retail or OEM edition (1), build 15.0000,** of Microsoft Office Professional Plus 2016 (0011). The language of the product is German. In this case, the hexadecimal value 0407 converts to the decimal value 1031. This value represents German._

The GUID has the release type "0", which represents Volume license, and the build 16.0000.
In this example however, it states that we have the release type "1" for a Retail or OEM edition, and the build 15.0000.

I think this is was copied from the article for Office 2013: https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/numbering-scheme-product-code-guids  and needs to be adapted accordingly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a559d43b-dc27-8706-4536-d12dc03c2646
* Version Independent ID: dbf3d841-622e-a70f-6515-b6c17427ef4f
* Content: [Numbering scheme for product code GUIDs - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/numbering-scheme-for-product-guid)
* Content Source: [Office/Client/office-suite-issues/numbering-scheme-for-product-guid.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/numbering-scheme-for-product-guid.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks again for your comment. The article is updated.
