### ISSUE TITLE
Adapt Hyperlink Name for Language Identifiers

### ISSUE THREAD

**Issue by anlorint** [MicrosoftDocs/OfficeDocs-Support#791]
Found this issue: 

_For more information about language identifiers in Office 2016 suites and programs, see **Language identifiers and Option State Id values in Office 2013.**_

The Hyperlink name should say 2016, instead of 2013.

If you click on the hyperlink "Language identifiers and Option State Id values in Office 2013" it points to the correct page: 
Language identifiers and OptionState Id values in Office 2016
https://docs.microsoft.com/en-us/DeployOffice/office2016/language-identifiers-and-optionstate-id-values-in-office-2016?redirectedfrom=MSDN

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a559d43b-dc27-8706-4536-d12dc03c2646
* Version Independent ID: dbf3d841-622e-a70f-6515-b6c17427ef4f
* Content: [Numbering scheme for product code GUIDs - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/numbering-scheme-for-product-guid)
* Content Source: [Office/Client/office-suite-issues/numbering-scheme-for-product-guid.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/numbering-scheme-for-product-guid.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The article is updated.
