### ISSUE TITLE
More detail required for Resolution 2

### ISSUE THREAD

**Issue by mhQuake** [MicrosoftDocs/OfficeDocs-Support#792]
For "Resolution 2: Install the trusted root certificate for error message 3" - please specify whether this resolution should be done on the client or on the server.  Please specify how to access "the Certificate dialog box".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5e9f6c5-af7b-cb22-1bd6-cb87b9cac667
* Version Independent ID: 954b92b3-2d96-2eca-7e55-d3f6ba152dc8
* Content: [Outlook can't connect to a server by an RPC or HTTPS connection - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/connectivity/error-when-outlook-uses-rpc-https-connect-server)
* Content Source: [Outlook/Client/connectivity/error-when-outlook-uses-rpc-https-connect-server.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/connectivity/error-when-outlook-uses-rpc-https-connect-server.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. The certificate should be installed on the client side. You can also [View certificates](https://support.microsoft.com/office/b73abe88-9f85-48a1-b00f-7ade1c0ec49f) in Outlook.

**Comment by nam31** [comment]
@mhQuake we are going to close this issue as the article has been updated accordingly. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
