### ISSUE TITLE
Expand solution for Word 365 accessed through Sharepoint, etc.

### ISSUE THREAD

**Issue by rmc2** [MicrosoftDocs/OfficeDocs-Support#793]
I can't change the file extension of a Word 365 document stored on Sharepoint/OneDrive etc. What's the solution in that case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca27a7a8-589a-70a8-699a-83821633a62b
* Version Independent ID: a275bcf8-bd79-8a99-e12b-9701d4259770
* Content: [The image part with relationship rID8 was not found in Microsoft Word - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/image-part-relationship-rld8-not-found-error-microsoft-word)
* Content Source: [Office/Client/word/image-part-relationship-rld8-not-found-error-microsoft-word.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/image-part-relationship-rld8-not-found-error-microsoft-word.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @McCoyBot
* Microsoft Alias: **v-todmc, Shuvojit.Ray**

**Comment by joinimran** [comment]
Hello, @rmc2 Do you have Read/Write Permission to document stored on Sharepoint/Onedrive?

**Comment by nam31** [comment]
@rmc2 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
