### ISSUE TITLE
Write direct link to log folder 

### ISSUE THREAD

**Issue by EMarcais** [MicrosoftDocs/OfficeDocs-Support#794]
Could it be possible to write the direct link  to the log folder? 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9a7194fa-a20c-433c-a928-9035dfa48c84
* Version Independent ID: 54452f7c-d2af-234b-c830-dab49d3a0864
* Content: [Exécution du suivi Fiddler après l’installation de SaRA - Office 365](https://docs.microsoft.com/fr-fr/office365/troubleshoot/diagnostic-logs/run-fiddler-trace)
* Content Source: [Microsoft365/admin/diagnostic-logs/run-fiddler-trace.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/diagnostic-logs/run-fiddler-trace.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by joinimran** [comment]
I am looking into this issue.

**Comment by nam31** [comment]
Closing via #1533 
Thank you
