### ISSUE TITLE
Steps not upto date with current W10/Office version

### ISSUE THREAD

**Issue by Ebemtb** [MicrosoftDocs/OfficeDocs-Support#795]
[Enter feedback here] 

Active Office Version: 16.0.13127.20296,

Steps do not fit with current W10/Office version, no "Internet" sub under "Common" in registry, see screenshot

![afbeelding](https://user-images.githubusercontent.com/39368961/93456441-fd56b380-f8dd-11ea-81de-3ce8039bbfc6.png)

****

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 291ef05d-5c3a-8179-8cfb-dd1af16db19b
* Version Independent ID: 68e35ec8-36bb-fdb8-9c7a-70b506cb2bdb
* Content: [Cannot locate the Internet or proxy server when selecting hyperlink in Office - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/cannot-locate-server-when-click-hyperlink)
* Content Source: [Office/Client/office-suite-issues/cannot-locate-server-when-click-hyperlink.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/cannot-locate-server-when-click-hyperlink.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by pizzaazzip** [comment]
> [Enter feedback here]
> 
> Active Office Version: 16.0.13127.20296,
> 
> Steps do not fit with current W10/Office version, no "Internet" sub under "Common" in registry, see screenshot
> 
> ![afbeelding](https://user-images.githubusercontent.com/39368961/93456441-fd56b380-f8dd-11ea-81de-3ce8039bbfc6.png)
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 291ef05d-5c3a-8179-8cfb-dd1af16db19b
> * Version Independent ID: 68e35ec8-36bb-fdb8-9c7a-70b506cb2bdb
> * Content: [Cannot locate the Internet or proxy server when selecting hyperlink in Office - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/cannot-locate-server-when-click-hyperlink)
> * Content Source: [Office/Client/office-suite-issues/cannot-locate-server-when-click-hyperlink.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/cannot-locate-server-when-click-hyperlink.md)
> * Product: **office-perpetual-itpro**
> * GitHub Login: @simonxjx
> * Microsoft Alias: **v-six**

Note step 3 in the fix:

`In Registry Editor, browse to one of the following subkeys **(create the keys if they do not exist)**:`

I read up on this problem on several forums and I made the same mistake many people made with this, this must be setup as 9.0, not the current version of office.  Also I wish these all had something faster to run like what I've pasted below, just needs to be ran in an admin command prompt

**For 32-Bit Office on a 64-Bit machine**
`REG add "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Office\9.0\Common\Internet" /v "ForceShellExecute" /t REG_DWORD /d "1" /f`

**For 32-Bit machine or 64-Bit office on a 64-Bit machine**
REG add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\9.0\Common\Internet" /v "ForceShellExecute" /t REG_DWORD /d "1" /f

**Comment by nam31** [comment]
@Ebemtb It seems that the question has been answered by the community, and thus the issue seems to be resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve. Thank you.
