### ISSUE TITLE
Feedback on "Emails stuck in Outbox in Outlook 16 for Mac".

### ISSUE THREAD

**Issue by wambaugh-debug** [MicrosoftDocs/OfficeDocs-Support#796]
This help was about Outlook for Mac, but the solutions refer to Outlook for PC.  Also, I'm seeing this problem while running Teams or other bandwidth intensive apps.  Apparently, based on this doc, if Outlook can't see the Sent folder (my case, it would be because Teams is consuming all resources), then sending emails fails partially and email stays in the Outbox.  Is there a way to work around this (increase timeouts, etc.)?  Thank you for your help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 255b5732-ef8a-f040-4cde-d9fc40486764
* Version Independent ID: 053a2e2a-d7a1-2562-8d83-b65263c6ec92
* Content: [Email messages are stuck in Outbox in Outlook 2016 for Mac - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/send-receive-emails/email-stuck-in-outbox-outlook-2016-mac)
* Content Source: [Outlook/Mac/send-receive-emails/email-stuck-in-outbox-outlook-2016-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Mac/send-receive-emails/email-stuck-in-outbox-outlook-2016-mac.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@wambaugh-debug Thank you for your feedback. Some of the Outlook switches like resetfolders or resetfoldernames do not work on a MAC. Similarly, the instructions provided in Method 4 using MFCMAPI cannot be performed on a MAC. So, you will need to use a windows machine or VM to perform these steps as mentioned in the article.

Alternatively, You can use MAC to change the folder name on the outlook web app as described in method 2.

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@wambaugh-debug Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
