### ISSUE TITLE
Does this article apply to Microsoft Teams as well?

### ISSUE THREAD

**Issue by DevJonBirkett** [MicrosoftDocs/OfficeDocs-Support#797]
[Enter feedback here]
Hi, 

Does this article apply to MS Teams as well? And is there any update on the countries in which tenant to tenant number porting is supported, as the last update on this article was a while ago. 

They both use the same Microsoft Phone System platform to provide telephony services. 

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0650b026-6d38-67a1-c94c-d2cff2e6eeff
* Version Independent ID: 886fb9f8-cdbe-dcb2-95ba-93caabc3d60d
* Content: [Can't transfer numbers from one tenant to another in Skype for Business Online - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/online-phone-system/cannot-transfer-numbers-from-office-365-tenant)
* Content Source: [SkypeforBusiness/SkypeOnline/online-phone-system/cannot-transfer-numbers-from-office-365-tenant.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeOnline/online-phone-system/cannot-transfer-numbers-from-office-365-tenant.md)
* Service: **skype-for-business-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by DevJonBirkett** [comment]
Just to update this. We contacts Microsoft directly about this and received the following feedback: 

> Migrating numbers from one tenant to another is possible, but there can be different limitations depending on the country. For example in Germany and the Netherlands it is not possible to split the number blocks, meaning the whole number block needs to be moved over.
This was from out Cloud Strategist contact in MS Dublin. 
Based on the above, I think this article does need to be updated.

**Comment by VLG17** [comment]
@DevJonBirkett The article applies to Teams as well. All the referenced articles within the linked article talk about Microsoft Teams.

I see two ways of doing this:

1. Creating a port order in Teams - details [here](https://docs.microsoft.com/en-us/MicrosoftTeams/phone-number-calling-plans/transfer-phone-numbers-to-teams?toc=%2Fskypeforbusiness%2Fsfbotoc%2Ftoc.json&bc=%2Fskypeforbusiness%2Fbreadcrumb%2Ftoc.json&redirectSourcePath=%252farticle%252fwhat-is-number-porting-9ca1f247-fb2f-4875-893c-7c94a7808567#create-a-port-order-and-transfer-your-phone-numbers-to-teams)

2. Directly reaching out to the PSTN service desk - details [here](https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk)

**Comment by nam31** [comment]
@DevJonBirkett Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
