### ISSUE TITLE
Unable to get data refreshed from Azure SQL after following the steps.

### ISSUE THREAD

**Issue by roadsidetree** [MicrosoftDocs/OfficeDocs-Support#798]
I am looking for a way to refresh Excel Online from Azure SQL. I follow the steps exactly, with password stored in connection string, check password is there. Saved the file. Uploaded to Sharepoint Online, and tried to click Refresh All, still getting the message: 
----------------------------------------------------------------------------------------
We were unable to refresh one or more data connections in this workbook.
The following connections failed to refresh:

dkldwlive Vendor
Learn more about data refresh

Give Feedback

[Enter feedback here]
------------------------------------------------------------------------------------------
connection string below:
Provider=SQLNCLI11.1;Password=XXXXXXXX;Persist Security Info=True;User ID=XXXXXX;Initial Catalog=dkldwlive;Data Source=XXXXXXX.database.windows.net;Use Procedure for Prepare=1;Auto Translate=True;Packet Size=4096;Workstation ID=DESKTOPXXXXX;Initial File Name="";Use Encryption for Data=True;Tag with column collation when possible=False;MARS Connection=False;DataTypeCompatibility=0;Trust Server Certificate=True;Application Intent=READWRITE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b17dcadc-ed60-4f69-4a18-1d87722edee9
* Version Independent ID: f6fe3396-386d-17e8-da69-3ed9e1f263ea
* Content: [How to refresh data to a SQL Azure Database in Excel Online - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/excel-online-refreshing-data-to-a-sql-azure-database)
* Content Source: [Office/OfficeExperts/excel/excel-online-refreshing-data-to-a-sql-azure-database.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/excel/excel-online-refreshing-data-to-a-sql-azure-database.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **thempel**

**Comment by Reeced40** [comment]
@roadsidetree thank you for reaching out. I'm investigating this and will revert soonest.

**Comment by Reeced40** [comment]
@roadsidetree Please can you confirm if the issue still needs researching or if the update helped and it can be closed?

**Comment by nam31** [comment]
@roadsidetree We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
