### ISSUE TITLE
Set-SPAppPrincipalPermission using wrong scope

### ISSUE THREAD

**Issue by DaleyKD** [MicrosoftDocs/OfficeDocs-Support#8]
This script snippet assumes that the only permissions are "Site" (aka Web). This has caused one of our clients to have COMPLETELY wrong permissions. Some of our apps use Tenant or SiteCollection scope.  What about Taxonomy?

This is a very dangerous script because it doesn't copy the permissions of the old app principal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8f9c9cc-3c05-5d14-5f48-45928f21e738
* Version Independent ID: 3eaa6276-2210-b9f5-9522-e912c179efc9
* Content: [Provider-hosted add-ins stop working and HTTP 401 error after you configure SharePoint farm hybrid features](https://docs.microsoft.com/en-us/sharepoint/support/server-admin/provider-hosted-add-ins-stop-working-and-http-401-error-after-configure-farm-hybrid-features#feedback)
* Content Source: [SharePoint/SharePointServer/server-admin/provider-hosted-add-ins-stop-working-and-http-401-error-after-configure-farm-hybrid-features.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointServer/server-admin/provider-hosted-add-ins-stop-working-and-http-401-error-after-configure-farm-hybrid-features.md)
* Service: **sharepoint-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The scope is updated from Site to Taxonomy as follows:
$Scope = 'Taxonomy'

**Comment by DaleyKD** [comment]
That doesn't resolve the issue.  This just makes it **worse**. Now, instead of giving the app Site access, you're only giving it Taxonomy access.  You totally ignored the part about SiteCollection access.

The issue is that your script isn't copying the permissions that currently exist.  You're creating new ones, and assuming what the permissions should be.

The entire script needs to be rewritten.
