### ISSUE TITLE
Unclear instructions at point 3

### ISSUE THREAD

**Issue by deepika-priyadarshani** [MicrosoftDocs/OfficeDocs-Support#803]
'"3. On the Insert menu, point to Name, and then click Define."

I cannot see a Name on the Insert Menu. Can you pls be clear?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0978476-f804-5686-d24b-99c854db57dd
* Version Independent ID: 68059573-0170-14d3-1876-3e07124f687b
* Content: [How to link a Visio drawing to a specific region in an Excel worksheet - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/link-visio-drawing-to-a-specific-region)
* Content Source: [Office/Client/excel/link-visio-drawing-to-a-specific-region.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/link-visio-drawing-to-a-specific-region.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. You can just right-click the rang of cells and then click **Define Name**.
