### ISSUE TITLE
New SharePoint Admin View (User Permission)

### ISSUE THREAD

**Issue by v-moshai** [MicrosoftDocs/OfficeDocs-Support#804]
Dear Team, 

I am adding feedback for the Microsoft docs related to SharePoint (https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sharing-and-permissions/access-denied-sharepoint-error)

As SharePoint Admin view has been updated, mentioned docs article seems old. It doesn't solve the purpose to navigate admin to access user specific permission by using these URLs "/_layouts/15/people.aspx?MembershipGroupId=0" for example "https://contoso.sharepoint.com/_layouts/15/people.aspx/membershipGroupId=0".

Please find attached picture to understand how this url navigate us to weird color patterns and no action available for managing permission.
![image](https://user-images.githubusercontent.com/71810888/94108037-3356e300-fe5c-11ea-9747-4c7fdba91a86.png)

**Comment by dariomws** [comment]
Hi @v-moshai, thank you for your feedback.

I tested it, and it's working. I think you've not specified the URL correctly. It should be something like:
https://companyname.sharepoint.com/sites/SiteName/_layouts/15/people.aspx?MembershipGroupId=0

**Comment by dariomws** [comment]
This is how it looks:
![image](https://user-images.githubusercontent.com/33589238/125363521-0d5de900-e371-11eb-85fc-fbb2a72a3232.png)

**Comment by nam31** [comment]
@v-moshai Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
