### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by GTAdoum** [MicrosoftDocs/OfficeDocs-Support#805]
[Enter feedback here]
The link for the hold does not give information that works now with new O365 Business Premium, the commandes return empty fields, therefore it does not give a way to remove the licence from a mailbox.
So how can we remove this licence?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900fa4b1-8057-3a6b-5c5e-09c9e4d7eaff
* Version Independent ID: 6a24a0d4-2b90-3b64-465e-8881ec77a8e7
* Content: [IgnoreLegalHold isn't available or functional for Exchange Online user objects - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/holds/ignorelegalhold-not-available?source=docs)
* Content Source: [Microsoft365/compliance/holds/ignorelegalhold-not-available.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/compliance/holds/ignorelegalhold-not-available.md)
* Product: **office 365**
* GitHub Login: @TobyTu
* Microsoft Alias: **lindabr**

**Comment by nam31** [comment]
@GTAdoum, this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@GTAdoum We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
