### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by GTAdoum** [MicrosoftDocs/OfficeDocs-Support#806]
[Enter feedback here]
This trick does not work anymore, please revise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bb20599-ae42-5a73-cc92-82e13b9b06c9
* Version Independent ID: 3de8193f-5107-9a12-2951-9291add8ae36
* Content: [Office 365 users aren't signed in to Office through AD accounts - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/sign-in/office-365-users-not-signed-in-office)
* Content Source: [Microsoft365/admin/sign-in/office-365-users-not-signed-in-office.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/sign-in/office-365-users-not-signed-in-office.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@GTAdoum, this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@GTAdoum We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
