### ISSUE TITLE
Non-Admin Cannot Edit HKLM

### ISSUE THREAD

**Issue by johnaweiss** [MicrosoftDocs/OfficeDocs-Support#807]
Under "For Outlook for Microsoft 365"
"Start Registry Editor"
You don't specify whether to start as CURRENT USER or as WINDOWS ADMINISTRATOR. 
My current user ISN'T Windows Admin, and therefor **CANNOT edit HKLM.** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd107c3b-1087-0241-0795-7afc59aea186
* Version Independent ID: 7abee709-caa5-e6fa-f8a3-c9c0603daace
* Content: [Can't send or receive email and Metered Connection Warning is triggered - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/profiles-and-accounts/metered-connection-warning)
* Content Source: [Outlook/Client/profiles-and-accounts/metered-connection-warning.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/profiles-and-accounts/metered-connection-warning.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. Admin permission is required to edit registry keys. Therefore, please contact the admin to perform the operation.
