### ISSUE TITLE
"SecurityManager" missing from HKLM

### ISSUE THREAD

**Issue by johnaweiss** [MicrosoftDocs/OfficeDocs-Support#808]
Under Office 365, you say to edit 

HKLM\SOFTWARE\Microsoft\Office\ClickToRun\REGISTRY\MACHINE\Software\Microsoft\SecurityManager\CapAuthz\ApplicationsEx

https://docs.microsoft.com/en-us/outlook/troubleshoot/profiles-and-accounts/metered-connection-warning#for-outlook-for-microsoft-365

"Security Manager" doesn't exist. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd107c3b-1087-0241-0795-7afc59aea186
* Version Independent ID: 7abee709-caa5-e6fa-f8a3-c9c0603daace
* Content: [Can't send or receive email and Metered Connection Warning is triggered - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/profiles-and-accounts/metered-connection-warning)
* Content Source: [Outlook/Client/profiles-and-accounts/metered-connection-warning.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/profiles-and-accounts/metered-connection-warning.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@johnaweiss, this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@johnaweiss We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
