### ISSUE TITLE
The substitute function requires ; instead of ,

### ISSUE THREAD

**Issue by generalcss** [MicrosoftDocs/OfficeDocs-Support#809]
I'm on macOS so there might be a difference there. But the substitute function required semicolon separators instead of comma's. I see that all examples are with comma's.

Did not work:
=SUM(LEN(B2:B30)-LEN(SUBSTITUTE(B2:B30,"J","")))   

Did work:
=SUM(LEN(B2:B30)-LEN(SUBSTITUTE(B2:B30;"J";"")))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d3af8cc-9482-e5e9-f1d5-a64f9ac0c51f
* Version Independent ID: e48dffa1-fccd-8de4-ef83-90f22a420ab1
* Content: [Formulas to count the occurrences of text, characters, and words in Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/formulas-to-count-occurrences-in-excel)
* Content Source: [Office/Client/excel/formulas-to-count-occurrences-in-excel.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/formulas-to-count-occurrences-in-excel.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by joinimran** [comment]
@generalcss - Thank you for posting your query here. I have checked and confirmed that the syntax mentioned in the document is correct. 

Excel formulas work independently of OS. 

![image](https://user-images.githubusercontent.com/47118050/119090189-ba2c8180-ba24-11eb-8956-0a14fbe20a64.png)

**Comment by nam31** [comment]
@generalcss Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
