### ISSUE TITLE
Script to fix activation - Admin rights and user context

### ISSUE THREAD

**Issue by mattwailes** [MicrosoftDocs/OfficeDocs-Support#813]
Can you update the doc to reference what the expectation is for user context and admin rights?  Can I run the script to clean or WPJClean up from ConfigMgr under system context or does it have to run as the logged on user with admin rights?  Can I run it as the user without admin rights?  

Thank you

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1375a9d-fa30-75a2-5aea-daca0e74f142
* Version Independent ID: c9510807-f261-5a24-0039-d6bf5ad630e5
* Content: [Reset Microsoft 365 Apps for enterprise activation state - Office](https://docs.microsoft.com/en-us/office/troubleshoot/activation/reset-office-365-proplus-activation-state)
* Content Source: [Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md)
* Service: **o365-solutions**
* GitHub Login: @MJP-MSFT
* Microsoft Alias: **mattphil**

**Comment by ericspli** [comment]
OLicenseCleanup requires Admin rights and will clean for all users on the device. SignOutOfWAMAccounts and WPJCleanup does not require Admin rights and should be ran under the user context for each user.

**Comment by nwe-akantola** [comment]
The batch file mentioned in this article only calls the x86 version of the CleanupWPJ executable. It never calls the _AMD64 variant and therefore doesn't work on an x64 platform.

**Comment by ericspli** [comment]
Correct, we only call x86 in the CleanupWPJ tool, however, that will work for both x86 and x64. The extra code is only there for a place holder in case we want to modify the tool in the future, there is no need to make any changed to run the tool on a 64-bit OS.

**Comment by nwe-akantola** [comment]
Hi Eric,

I got the error “FindAllAccountsAsync failed with error code: 0x80070520” when running the batch file as-is. When I replaced every instance of “CleanupWPJ_X86.exe” to “CleanupWPJ_AMD64.exe”, it seems to work.

Thanks,
Anthony

**Comment by nam31** [comment]
@mattwailes seems that the question has been answered by the community and also the article has been updated recently. Please let us know if the issue has been resolved. Thanks

**Comment by nam31** [comment]
@mattwailes We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
