### ISSUE TITLE
Empty Search Results in Mojave - The provided solution is bunk.

### ISSUE THREAD

**Issue by decuser** [MicrosoftDocs/OfficeDocs-Support#817]
This solution page is nonsense. Outlook search results are empty and this gui-centric approach to rebuilding the Spotlight Index is pathetic and does nothing to fix the issue. Please have a serious engineer take a look at the code. I am on Mojave 10.14.6 with the latest updates, and my version of Office is 16.41.20091302_BusinessPro. I have reset the spotlight index and completely uninstalled and reinstalled Office and still the index is empty (of course it works fine for every non-Microsoft application on my system).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a55b51-85d6-f628-581c-5a1c66675933
* Version Independent ID: 9f626f3a-123d-67ca-3aa8-a3443963fe05
* Content: [Outlook for Mac support tools. - Outlook](https://docs.microsoft.com/en-in/outlook/troubleshoot/outlook-for-mac/useful-tools)
* Content Source: [Outlook/OutlookExperts/outlook-for-mac/useful-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/OutlookExperts/outlook-for-mac/useful-tools.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@decuser, this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by decuser** [comment]
Wow! Great work. This is much more helpful. Thanks. Yes, this helped.
