### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by fdrobnic** [MicrosoftDocs/OfficeDocs-Support#819]
This should absolutely be handled automatically for all installed browsers supplied by MS. For others, an explicit warning should be shown during the installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c17faf2-0e38-0a98-454c-3c2c4387b37f
* Version Independent ID: d9153b98-dc39-fdd1-a798-07da0caaaa64
* Content: [Microsoft Teams is stuck in a login loop in Edge or Internet Explorer - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#resolution)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by KB-Q** [comment]
**It Works.**

I was facing the same error in Edge. I followed the instructions given, essentially copy-pasting the URLs into the Allow section in the Cookie settings, yet it didn't fix anything. That's when I learnt the hard way that you have to copy-paste the **whole URL**, i.e., including the [*.] part as well! I did the same for all 6 URLs given, and it worked like a charm. Let me know if it works for you as well.

Regards,
Karthik.

**Comment by nam31** [comment]
@fdrobnic, seems that the question has been answered by the community and also the article has been updated recently. Please let us know if the issue has been resolved. Thanks

**Comment by nam31** [comment]
@fdrobnic We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
