### ISSUE TITLE
Sort entries 

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/OfficeDocs-Support#820]
https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/fails-accessing-page-connected-access-database 
Specifically In the s "Office Suite Issues" section of this subsite the sub entries start with 
"0x80004005: ..."
"Compile Error: Procedure too Large"
"No Default mail client" error 
...
0x80041015 when ...
...

Remove the quotes from around the "whole" entry, resort the list, and trailing word "error" that is not part of the error message to make all of the heading consistent.  They all represent an error, stating error in the heading is redundant.

Result is 
0x80004005:
0x80041015 When starting ...
etc

It makes the list more logical, easier to find if a specific entry is there, and to find what may be related entries.

Do the same fix to all of the major categories on the "Office Products Troubleshooting" subsite

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78b77aae-c967-714a-c888-e4d451a02585
* Version Independent ID: d4fe8833-3567-c6f6-1b08-8cb5ac356c1a
* Content: [0x80041015 error when you start an Office program - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/0x80041015-start-office-program)
* Content Source: [Office/Client/office-suite-issues/0x80041015-start-office-program.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/0x80041015-start-office-program.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@nam31, @e0i , will you look in to this issue #820.

**Comment by simonxjx** [comment]
Thanks for your comment. The TOC names are updated.
