### ISSUE TITLE
End of Support section: Add link to Office 2010 EOS / EOL page

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/OfficeDocs-Support#821]
This is a better link, than the autogenerated one:
https://docs.microsoft.com/en-us/office/troubleshoot/office-client-welcome 

In the End of Support sub section (on left side of page), add a link to Office 2010 specific EOL EOS information. Or edit Office 2007 page to include 2010 in the heading, if the information i appropriate (I didn't look

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec213ebd-2b72-d07e-0320-fcea5420431d
* Version Independent ID: e83d7588-61c7-69df-168b-2783703f4246
* Content: [0x80004005 General Error Unable to Open Registry Key - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/fails-accessing-page-connected-access-database)
* Content Source: [Office/Client/office-suite-issues/fails-accessing-page-connected-access-database.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/fails-accessing-page-connected-access-database.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Ronsss** [comment]
Thanks. Close the issue.

**Comment by nam31** [comment]
@Ronsss The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
