### ISSUE TITLE
Wrong setting

### ISSUE THREAD

**Issue by ala7470** [MicrosoftDocs/OfficeDocs-Support#823]
[Enter feedback here]

this line is wrong 
Add the following lines in the web.config file just above /appsettings

Should be 
Add the following lines in the web.config file just above appsettings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebca74ee-463b-8322-5ee2-30813ddb8127
* Version Independent ID: d9b59f78-7db7-29cb-90b1-986128786674
* Content: [Exchange Server doesn't display all OUs - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/exchange-server-not-display-all-ou)
* Content Source: [Exchange/ExchangeServer/administration/exchange-server-not-display-all-ou.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/administration/exchange-server-not-display-all-ou.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by RAJU2529** [comment]
@e0i, @nam31 , will you look into this issue #823

**Comment by nam31** [comment]
@ala7470 Thank you for providing feedback to help improve a Microsoft product!  We are goin to close this issue.
Our team has confirmed that the original article is correct.
Thank you
