### ISSUE TITLE
IMHO - A more effective method...

### ISSUE THREAD

**Issue by thisisfutile** [MicrosoftDocs/OfficeDocs-Support#824]
I think it makes more sense to do this:

1. Leave 'Search subfolders' checked
2. UNcheck account/mailstore (user@domain.com)
3. CHECK the Inbox

In this way, all inbox folders (present and future) are searched and the "person metadata" entries are not included (those appear to be stored at the account/mailstore level).

I think the only problem here is someone who might have a rule that moves things to other 'top level' folders (like Sent or Archive) and doesn't mark them as read.  These users are expecting to see the unread, moved emails in this search folder but will not.  In those cases, they should check those top level folders too, otherwise Inbox is really the only thing that needs checked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02975195-17b6-e543-decd-c433e7a0c8c2
* Version Independent ID: a42ef3bc-b695-ccfc-028f-ac4fec1e82f6
* Content: [Outlook search folders show unexpected mail items with an empty subject - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/user-interface/personmetadata-items)
* Content Source: [Outlook/Client/user-interface/personmetadata-items.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/user-interface/personmetadata-items.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@thisisfutile , Your idea is good, But without verification, we can't conform. So wait for the replies from experienced users
