### ISSUE TITLE
Document update request for https://docs.microsoft.com/en-us/exchange/troubleshoot/send-emails/smtp-submission-improvements#new-behavior-when-submitting-messages

### ISSUE THREAD

**Issue by qaehtesh** [MicrosoftDocs/OfficeDocs-Support#827]
[Enter feedback here]
It's been informed from engineering team that for SMTP submission mail we have reverted to the old behavior where the client displayname would be used instead of GAL lookup and using directory displayname.  (WI Issue1494697)
So requesting to change below content in the documentation to update the part where it says this will be same as OWA and the sender’s Office 365 display name will now be shown as part of the From address.
This should be changed to display name behavior is not same as OWA and it would appear as sent as from the client instead of directory displayname

---
Additionally, messages might arrive at the recipient with a different display name than they did before the change. Messages that are sent by using SMTP Authenticated Submission protocol will now behave in the same way as other submission protocols in Office 365, such as the protocol that is used when emails are sent by using Outlook on the web. As a result, the sender’s Office 365 display name will now be shown as part of the From address. 
---

https://docs.microsoft.com/en-us/exchange/troubleshoot/send-emails/smtp-submission-improvements#new-behavior-when-submitting-messages

Could you also help to fix the public documentation so we could use as supporting argument for this change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54261af2-6912-5d9f-e4db-050a6ea62efd
* Version Independent ID: 014d2473-8c3d-b954-62c6-08dbceab9b74
* Content: [Changes in message store and throttling for concurrent connections - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/send-emails/smtp-submission-improvements)
* Content Source: [Exchange/ExchangeOnline/send-emails/smtp-submission-improvements.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/send-emails/smtp-submission-improvements.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
Closing via #1626 
Thank you
