### ISSUE TITLE
Didn't help

### ISSUE THREAD

**Issue by ddesn** [MicrosoftDocs/OfficeDocs-Support#829]
Hi, 

Thank you for writing this article. 
I have the same problem, but your solution isn't working!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b974aa57-35b6-e494-43dc-23dd486938ca
* Version Independent ID: bb658f3e-e4e3-e9a5-bde0-6e0c1c20cfa2
* Content: [Last digits are changed to zeros when you type long numbers in cells of Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/last-digits-changed-to-zeros)
* Content Source: [Office/Client/excel/last-digits-changed-to-zeros.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/last-digits-changed-to-zeros.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your feedback. If you still have the issue, you can contact [Excel support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.excel) for more help.
