### ISSUE TITLE
this script is only for Exchange 2010

### ISSUE THREAD

**Issue by musashiharuno** [MicrosoftDocs/OfficeDocs-Support#83]
when you download the script and run, it will tell you, that it looks for v14, please update the article applies to only for Exchange 2010

jinchl@microsoft.com
OnPrem Exchange Premier Support Team

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9478ec16-b866-03ae-edf7-d1076c0163e7
* Version Independent ID: 1abb2287-645a-5ddf-695f-2e066cf60031
* Content: [Connecting to the remote server failed when start Management Shell or Console - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/management-console/connecting-remote-server-failed#feedback)
* Content Source: [Exchange/ExchangeServer/management-console/connecting-remote-server-failed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/management-console/connecting-remote-server-failed.md)
* Service: **exchange-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The article is updated with Exchange Server 2013 removed.
