### ISSUE TITLE
Command formatting

### ISSUE THREAD

**Issue by Vindicator007** [MicrosoftDocs/OfficeDocs-Support#831]
Get-Recipient -ResultSize Unlimited | Where-Object {$_.EmailAddresses -match "user@contoso.onmicrosoft.com"} | Format-List Name, RecipientType, emailaddresses

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a5082f6-c369-4464-94bd-1a3f13e44393
* Version Independent ID: d06e6e6e-9e7c-9ec7-40c6-01f9b73835ce
* Content: [Proxy address is already being used](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/proxy-address-being-used)
* Content Source: [Exchange/ExchangeOnline/administration/proxy-address-being-used.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/administration/proxy-address-being-used.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments, the formatting is revised.
