### ISSUE TITLE
Report Typo in the VB Code

### ISSUE THREAD

**Issue by ylshao** [MicrosoftDocs/OfficeDocs-Support#832]
Hello,

For the section "Converting Decimal Degrees to Degrees/Minutes/Seconds", there is a typo in the VB code. The line ```Convert_Degree = " " & Degrees & "° " & Int(Minutes) &        ``` ```' " _``` ```& Seconds + Chr(34)``` should be ```Convert_Degree = " " & Degrees & "° " & Int(Minutes) &       ``` ```" ' "``` ```& Seconds + Chr(34)```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be969d50-8518-365f-f3ed-5c0e14d55104
* Version Independent ID: 11bad482-781b-bbae-ce60-53f8164d137e
* Content: [Convert degrees/minutes/seconds angles to or from decimal angles - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/convert-degrees-minutes-seconds-angles)
* Content Source: [Office/Client/excel/convert-degrees-minutes-seconds-angles.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/convert-degrees-minutes-seconds-angles.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments. The code is corrected.
