### ISSUE TITLE
550 5.7.1 Unfortunately, messages from weren't sent. Please contact your Internet service provider since part of their network is on our block list (AS3150)

### ISSUE THREAD

**Issue by syedali198321** [MicrosoftDocs/OfficeDocs-Support#834]
Hi .

I am running Microsoft exchange 2010 Server and i am unable to sent email to external emails ( like Gmail , Hotmail etc ) , in domain emails are working fine.

"550 5.7.1 Unfortunately, messages from weren't sent. Please contact your Internet service provider since part of their network is on our block list (AS3150)"

kindly guide me how can i resolve this problem.

Thanks & Best Regards
Noman

**Comment by syedali198321** [comment]
i have mentioned error in above message.

**Comment by nam31** [comment]
@syedali198321, can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you

**Comment by nam31** [comment]
@syedali198321 We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
