### ISSUE TITLE
Closing the door after the cow is out of the barn.

### ISSUE THREAD

**Issue by GitHubJohn2** [MicrosoftDocs/OfficeDocs-Support#836]
The "resolution" is preventative, not curative.  This error occured after a windows crash and remains despite reboots - resolution would be how to fix it, not how to keep it from happening.  Preventative solutions offered also have nothing to do with the problem.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f16c6d8-1532-4b7d-75ff-888eb887c51a
* Version Independent ID: e2cd5650-5b6f-dc00-8a43-9528dd442d57
* Content: [Unable to open an Access database - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/error-opening-database)
* Content Source: [Office/Client/access/error-opening-database.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/error-opening-database.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by simonxjx** [comment]
Thanks for your comment. The current resolution is a workaround for this issue. The section heading is updated to workaround. For more help, you can contact [Access Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.access) for more help.
