### ISSUE TITLE
Getting this error although I have only few items

### ISSUE THREAD

**Issue by gsannikov** [MicrosoftDocs/OfficeDocs-Support#837]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c938610-4956-5b94-c23c-7523f14c620f
* Version Independent ID: fee2d9da-1d2f-0083-70f9-2e57224348cd
* Content: [Issue when you access a notebook for Microsoft Teams. - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-onenote-integration/issue-access-notebook)
* Content Source: [Teams/teams-onenote-integration/issue-access-notebook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-onenote-integration/issue-access-notebook.md)
* Service: **msteams**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. If this issue still persists, you can contact [Teams support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.teams) for more help.
