### ISSUE TITLE
Heading "Apps for Office don't start" not match contents

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/OfficeDocs-Support#838]
See "Content" below. 
The content on the page/link it does not match the label that links to it in the left column of the page
[Enter feedback here]

---
#### Document Details
![image](https://user-images.githubusercontent.com/33688532/95848225-5c5bec80-0d13-11eb-80ce-61a9f318acbd.png)

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f3b6935-f6af-2cd8-214c-ea2bb5ded4a2
* Version Independent ID: bffedcd3-1dfa-58c4-2fbf-a935fcdeb13e
* Content: [Office Add-in don't start if you disable protected mode for Restricted Sites zone - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/apps-for-office-not-start)
* Content Source: [Office/Client/office-suite-issues/apps-for-office-not-start.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/apps-for-office-not-start.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments. Microsoft Office has Add-ins and they are also called Office Apps.
