### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by stevenc7** [MicrosoftDocs/OfficeDocs-Support#839]
Very great article thanks to the author!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6baec64-2c8f-ed19-b498-369711b79dc3
* Version Independent ID: f2cb07f9-d352-73a5-4351-138f2e71cd9b
* Content: [Another account is already signed in computer when signing in to Office 2013 - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/another-account-already-signed-in)
* Content Source: [Office/Client/office-suite-issues/another-account-already-signed-in.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/another-account-already-signed-in.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your feedback.
