### ISSUE TITLE
"Never warn me about suspicious activity" not working

### ISSUE THREAD

**Issue by RogerCooper11590** [MicrosoftDocs/OfficeDocs-Support#840]
[Enter feedback here]
I followed the instructions. Everything is marked correctly. Office is up to date. I am still not allowed to send automated e-mails with Access. This just started on Monday 10/12. Is there anything else I can try?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef4594d0-1afe-ea6a-ded2-33e12d5fdca8
* Version Independent ID: 6ebee00e-adf4-41bb-ee17-fac16c68548c
* Content: [Program is trying to send an e-mail message on your behalf - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/security/a-program-is-trying-to-send-an-email-message-on-your-behalf)
* Content Source: [Outlook/Client/security/a-program-is-trying-to-send-an-email-message-on-your-behalf.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/security/a-program-is-trying-to-send-an-email-message-on-your-behalf.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comments. If the issue still presists, you can contact [Outlook Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.outlook) for more help.
