### ISSUE TITLE
Resources is not the issue..

### ISSUE THREAD

**Issue by xanbrennan** [MicrosoftDocs/OfficeDocs-Support#843]
I'm having severe (as in can't use the app) issues on my iMac (2019) 3.6 GHz 8-Core i9, 128 GB of RAM, Radeon Pro 580x 8GB + eGPU Vega 64 w/ 8GB. Looking at my resource use, Teams is barely touching anything. I do have 2 4K monitors (neither are HDR) plugged into the eGPU. But I can definitively say that is not the issue, as other members of my team are having the same issues on their brand new maxed out MacBook Pro's w/o anything extra plugged in.

The 'fixes' outlined on this page do not solve the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df6fe49-939e-8330-07a1-49ff0a2c4ab7
* Version Independent ID: f7cc79e9-6e2a-17a4-36ec-743acc0d679a
* Content: [Teams is slow during video meetings on laptops docked to 4K/HDR monitors - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/known-issues/teams-slow-video-meetings-laptops-4k)
* Content Source: [Teams/known-issues/teams-slow-video-meetings-laptops-4k.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/known-issues/teams-slow-video-meetings-laptops-4k.md)
* Service: **msteams**
* GitHub Login: @v-miegge
* Microsoft Alias: **sgorantl**

**Comment by nam31** [comment]
@xanbrennan, this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@xanbrennan We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
