### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by luamcortez** [MicrosoftDocs/OfficeDocs-Support#844]
[Enter feedback here]

"3. At the top of the information store, select Inbox, and then right-click Open associated contents table."
I spent basically 10 minutes looking for these menus and didn't find. Could this be more clearly written, perhaps with more screenshots?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36cd3afe-ae4e-ab14-ad5d-4c0c2c18bab2
* Version Independent ID: 6e256339-6074-5c83-6630-858a65ff7cf5
* Content: [Understanding and troubleshooting Out of Office (OOF) replies - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/send-emails/understand-troubleshoot-oof-replies)
* Content Source: [Exchange/ExchangeOnline/send-emails/understand-troubleshoot-oof-replies.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/send-emails/understand-troubleshoot-oof-replies.md)
* Product: **office 365**
* GitHub Login: @TobyTu
* Microsoft Alias: **damande**

**Comment by nam31** [comment]
@luamcortez We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
