### ISSUE TITLE
"452 4.3.1 Insufficient system resources: error happened in Exchange 2016

### ISSUE THREAD

**Issue by glinwise** [MicrosoftDocs/OfficeDocs-Support#845]
We have got a "452 4.3.1 Insufficient system resources: error happened in Exchange 2016 recently. We have about 50 Message Count showd in "SMTP RElay to Malbox DElivery Group" in 2 Exchange 2016 Server.

Both servers have plenty disk spaces (over 50% disk space free)  and memory. 

Could any experts help?

**Comment by nam31** [comment]
@glinwise, can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you

**Comment by nam31** [comment]
@glinwise We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
