### ISSUE TITLE
-backupfile argument either doesn't work or needs a more complete Note

### ISSUE THREAD

**Issue by twalp** [MicrosoftDocs/OfficeDocs-Support#847]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0013ac99-8442-ee88-95d8-c5f459c518e5
* Version Independent ID: 6679377c-f8c6-4e1e-696e-ebf61342e31b
* Content: [Inbox Repair tool (Scanpst.exe) run multiple passes - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/data-files/inbox-repair-tool-scanpst-exe-run-multiple-passes)
* Content Source: [Outlook/Client/data-files/inbox-repair-tool-scanpst-exe-run-multiple-passes.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/data-files/inbox-repair-tool-scanpst-exe-run-multiple-passes.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by joinimran** [comment]
Hello @twalp thank you for posting your query. I have checked and verified the command is executed properly. See the screenshot.
![image](https://user-images.githubusercontent.com/47118050/120314422-ab7f7d80-c2f4-11eb-9c6d-0784e7869808.png)

I have tested this on my windows 10 computer and office 2019. If you are using any other version let me know so I can check.
Thanks.
Imran.

**Comment by nam31** [comment]
@twalp We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
