### ISSUE TITLE
This SampleCode Doesn't work because it Doesn't indented

### ISSUE THREAD

**Issue by akrolayer** [MicrosoftDocs/OfficeDocs-Support#849]
[フィードバックをこちらに入力してください]
This page have samplecode to send Mail Automatically. I copy samplecode and paste ScriptEditer in outlook.   SampleCode Doesn't work. Message is "Line 1 expected statement". But, it is work  by indenting.  

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 455af345-721d-c616-7247-be0f4b1e9c66
* Version Independent ID: 9c5b6c72-5a80-84e6-3b1e-928a44e182c7
* Content: [Outlook で定期的に送信する電子メール メッセージを作成する方法 - Outlook](https://docs.microsoft.com/ja-jp/outlook/troubleshoot/user-interface/create-recurring-email)
* Content Source: [Outlook/Client/user-interface/create-recurring-email.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/user-interface/create-recurring-email.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The code is corrected.
