### ISSUE TITLE
Switching certificate root

### ISSUE THREAD

**Issue by mesykkor** [MicrosoftDocs/OfficeDocs-Support#85]
worked. Step 1 was enough in my case. Actually not sure of the root cause. My colleagues didn't have the same problem. The same happened to me on Citrix and Laptop. It seems to be like the server certificate was replaced with a different one, with the chain signed by a different root. This new roor, however, was known to the client.

Anyway, thanks for te recipe,

Mojmir Elias

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b22174c4-06b7-dc2e-0bec-3e9380f576d3
* Version Independent ID: 2da4d9d6-ca84-d2d6-c3d3-f5c042ad5afd
* Content: [How to troubleshoot being unable to sign in to Skype for Business - Skype for Business](https://docs.microsoft.com/en-us/SkypeForBusiness/troubleshoot/server-sign-in/unable-to-sign-in-to-sfb#feedback)
* Content Source: [SkypeforBusiness/SkypeServer/server-sign-in/unable-to-sign-in-to-sfb.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeServer/server-sign-in/unable-to-sign-in-to-sfb.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @TobyTu
* Microsoft Alias: **corbinm**

**Comment by TobyTu** [comment]
Thanks for your feedback!
