### ISSUE TITLE
METODA 4 - SKUTECZNA (WINDOWS 10)

### ISSUE THREAD

**Issue by kwikk** [MicrosoftDocs/OfficeDocs-Support#850]
[Wprowadź tutaj swoją opinię]
Jeżeli nie działają Hiperłącza i pojawia się komunikat:
" Zasady Twojej organizacji uniemożliwiają nam ukończenie tej akcji. Aby uzyskać więcej informacji, skontaktuj się z pomocą techniczną. "

Kliknij -> START -> USTAWIENIA ->APLIKACJE ->(w prawym górnym rogu) PROGRAMY I FUNKCJE -> (po lewej stronie) WŁĄCZ LUB WYŁĄCZ FUNKCJE SYSTEMU WINDOWS -> (znajdź pole INTERNET EXPLORER 11)  i zaznacz kwadrat "ptaszkiem" Kliknij OK. Uruchom ponownie komputer.
Po ponownym uruchomieniu komputera w polu WYSZUKAJ wpisz REGEDIT. Po otworzeniu edytora rejestru wklej u góry ścieżkę " Komputer\HKEY_CLASSES_ROOT\.html" (w oknie po prawej stronie) kliknij prawym przyciskiem myszy na (Domyślna) i następnie wybierz Modyfikuj... wpisz w polu Dane wartości: HTMLFILE, następnie wklej ścieżkę u góry edytora rejestru Komputer\HKEY_CLASSES_ROOT\.htm (w oknie po prawej stronie) kliknij prawym przyciskiem myszy na (Domyślna) i następnie wybierz Modyfikuj... wpisz w polu Dane wartości: HTMLFILE. 
Zakończ działanie edytora rejestru i ciesz się działającymi Hiperłączami.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 7f736e25-4b81-c26f-ee4d-640519094af6
* Version Independent ID: 9343708d-ccf7-2e46-d377-13564037a5b9
* Content: [Hiperłącza nie działają - Outlook](https://docs.microsoft.com/pl-pl/outlook/troubleshoot/message-body/hyperlinks-not-working-in-outlook)
* Content Source: [Outlook/Client/message-body/hyperlinks-not-working-in-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/hyperlinks-not-working-in-outlook.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by joinimran** [comment]
Hello @kwikk can you tell which operating system are you using? 

Thanks.
Imran.

**Comment by joinimran** [comment]
Hello @kwikk - Can you please confirm which operating system / Windows version you are using so that we can better guide you.
Thanks.

**Comment by nam31** [comment]
@kwikk We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
