### ISSUE TITLE
Expand to include all version of Office since 2013

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/OfficeDocs-Support#851]
I understand that this is a new security feature. Ideally, the SARA tool could be modified to include this scenario.

i.e. "We found x and y user accounts. Which account is the primary and would you like to remove y account?"
The customer is looking to work with the account and of course we, Microsoft, want to provide them with a secure experience. The problem is that in this condition the product is not functional. And the error message does not lend to a self-resolve path.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6baec64-2c8f-ed19-b498-369711b79dc3
* Version Independent ID: f2cb07f9-d352-73a5-4351-138f2e71cd9b
* Content: [Another account is already signed in computer when signing in to Office 2013 - Office](https://docs.microsoft.com/en-gb/office/troubleshoot/office-suite-issues/another-account-already-signed-in)
* Content Source: [Office/Client/office-suite-issues/another-account-already-signed-in.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/another-account-already-signed-in.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
The steps are covered in the OLicenseCleaup script. you can find it here: https://msdnshared.blob.core.windows.net/media/2018/05/OLicenseCleanup.vbs_.txt

Thanks,
Jose
