### ISSUE TITLE
Outdated screenshots

### ISSUE THREAD

**Issue by norto2mr** [MicrosoftDocs/OfficeDocs-Support#853]
The information is correct, but the images are outdated, so it references UX elements that are no longer present, such as the gear icon in OWA when looking at groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae5837d9-04a2-ffb7-19f4-1b6538cd7630
* Version Independent ID: 97de6157-49d3-99e6-91a5-6d669b95cd90
* Content: [No email notifications for responses to Group Forms - Office](https://docs.microsoft.com/en-us/office/troubleshoot/microsoft-forms/no-email-notifications-for-responses-to-group-forms)
* Content Source: [Office/OfficeExperts/microsoft-forms/no-email-notifications-for-responses-to-group-forms.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/microsoft-forms/no-email-notifications-for-responses-to-group-forms.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **zakirh**

**Comment by nam31** [comment]
@norto2mr, this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by norto2mr** [comment]
Looks good now, thank you!
