### ISSUE TITLE
Hyperlinks are not working - Outlook

### ISSUE THREAD

**Issue by babble2fish** [MicrosoftDocs/OfficeDocs-Support#858]
I wonder if someone can explain the following to me.  I had the problem with hyperlinks not working on a Windows 10 computer ("Your organization's policies are preventing us from completing this action for you....").

The registry HKEY_CLASSES_ROOT .html key was correct (htmlfile) when the user was a Standard user.

When the user was an Administrator, and I looked at the same registry entry, it was now displayed as CCleanerHTML.  

Changing it to htmlfile fixed the hyperlink problem.  

I had the same problem on another computer, and had to change that user to Admin also to see the incorrect value of CCleanerHTML.  

What would cause the registry entry to be changed, or maybe just displayed differently, as a Standard or Admin?

(I have since uninstalled CCleaner.)

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f736e25-4b81-c26f-ee4d-640519094af6
* Version Independent ID: 9343708d-ccf7-2e46-d377-13564037a5b9
* Content: [Hyperlinks are not working - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/message-body/hyperlinks-not-working-in-outlook)
* Content Source: [Outlook/Client/message-body/hyperlinks-not-working-in-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/hyperlinks-not-working-in-outlook.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@babble2fish Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Comment by vinyar** [comment]
I am having this same problem. Everything was working fine, and after the last update or two (somewhere between July 2021 and Sept 2021) clicking on links in OneNote 2013 suddenly stopped.

I dont have IE installed, and this is infuriating. Please add OneNote repair steps for computer where IE is not installed.
