### ISSUE TITLE
Typo in content header "Search results isn't rerutned"

### ISSUE THREAD

**Issue by EviTweetie** [MicrosoftDocs/OfficeDocs-Support#86]
Hello, I just noticed that the content header for this page https://docs.microsoft.com/en-us/sharepoint/support/search/search-results-not-return has a little typo in the content directory (don't know whether this is the correct expression ;) ):
"Search results isn't rerutned" &gt;&gt; "Search results isn't returned"
Thanks for alle the useful documentation!!!
Kind regards, Evi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3d47010-ca38-4ae9-62b6-ebb408f95836
* Version Independent ID: fa08b23c-bb1d-1021-5fbe-a605c53da113
* Content: [SharePoint Online doesn't return search results - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/search/search-results-not-return#feedback)
* Content Source: [SharePoint/SharePointOnline/search/search-results-not-return.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/search/search-results-not-return.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
It is fixed.
