### ISSUE TITLE
Can not upload folders with Firefox, Chrome!?

### ISSUE THREAD

**Issue by aponoran** [MicrosoftDocs/OfficeDocs-Support#862]
Are you guyz serious?! Basic fiele operations are utter crap in sharepoint. Please take a look at other and wake up Microsoft - we are in the year 2020. Check: google drive, dropbox, icloud.
I am forced to used form work, otherwise I would not touch the whole Sharepoint, OneDrive ecosystem.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8068176e-c7e4-4c98-e4ec-453b24763771
* Version Independent ID: 79643fef-c5c1-94fe-5a00-8ce43d6b4773
* Content: [Info about dragging files into SharePoint libraries by using a web browser - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/lists-and-libraries/dragging-files-using-web-browser)
* Content Source: [SharePoint/SharePointOnline/lists-and-libraries/dragging-files-using-web-browser.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/lists-and-libraries/dragging-files-using-web-browser.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. The drag files feature is limited to files. It is recommended to use the Open with Explorer feature when you recieve the error message.
