### ISSUE TITLE
Compatibility Level 150 - is this still an issue

### ISSUE THREAD

**Issue by hardkorehak** [MicrosoftDocs/OfficeDocs-Support#863]
We just upgraded our SQL server to 2019 (Compatibility Level 150) and are suddenly experiencing this issue. We have added Timestamp columns, we don't have Datetime2 columns, and I am still getting the Write Conflict warning. We are dropping to 120, but I don't feel that should be our end solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c4635a6-1d2b-3155-a2a7-625958332caa
* Version Independent ID: 1f689b25-968f-8e6f-3eb7-e6b05d295340
* Content: [Access linked table to SQL Server database returns Deleted - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/access-linked-table-deleted)
* Content Source: [Office/Client/access/access-linked-table-deleted.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/access-linked-table-deleted.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nk-gears** [comment]
Hello @hardkorehak,

Thanks for reporting this Issue.

Could you please shed some lights when do you get this error?. When you try to Insert,Update or while Importing the Data to the Table ?

**Comment by hardkorehak** [comment]
We have our primary database at CL110 right now. These were happening on linked tables in MSAccess, our primary UI at the time, on Insert/Update. We have decided to move on, since it's been 8 months since my initial issue was sent in. We are in the process of upgrading our entire interface from Access to Blazor pages, and eventually moving the SQL Server from fully on-prem to Azure.

**Comment by nk-gears** [comment]
ok @hardkorehak , Thanks for the details. Will forward this to the technical team to look into further.
