### ISSUE TITLE
Move calendar items or accept meetings with a non primary calendar?

### ISSUE THREAD

**Issue by tigerloo** [MicrosoftDocs/OfficeDocs-Support#864]
Hi team!

I organize different projects in different calendars to have the opportunity to share the calendars with project specific people. There is no problem, when I create the meetings myself, but I have not found any option to either accept a meeting with another calendar then the primary, or to move meetings from one calendar to another (since this feature is not available anymore).

I need at least one of the options for a proper organization of project meetings. Is there a feasible workaround?

Best regards!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e589348f-cb75-dc9e-eab8-19bc1c5b7c38
* Version Independent ID: 7995b5bf-a0d3-43da-a1a1-bd293df72a94
* Content: [How to copy Calendar items to another folder - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/calendaring/how-to-copy-calendar-items-to-another-folder)
* Content Source: [Outlook/Client/calendaring/how-to-copy-calendar-items-to-another-folder.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/calendaring/how-to-copy-calendar-items-to-another-folder.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. For your question, you can contact [Outlook Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.outlook) for more help.

**Comment by tigerloo** [comment]
@simonxjx Is there a feasible workaround?

**Comment by simonxjx** [comment]
You can reference [Move items between calendars](https://support.microsoft.com/office/set-default-calendar-7c546486-0c7c-4870-964a-0d6eb4de83e0#_moveitems)
