### ISSUE TITLE
Add more info/links

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/OfficeDocs-Support#87]
For example, when you list "Enable Safe and Blocked senders in Outlook or Outlook on the Web", you might want to mention that it's enabled by default, and you might also want to add information on how to edit the RAP to remove this functionality in OWA, or how to block it in Outlook, etc.

Same for the other items, add a link to the corresponding documentation page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d39c3f-93c5-f920-5148-8069f5021c83
* Version Independent ID: d1e51705-dec0-baee-80f2-71499fd31b52
* Content: [Cautions against bypassing Office 365 spam filters. - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/antispam/cautions-against-bypassing-spam-filters)
* Content Source: [Exchange/ExchangeOnline/antispam/cautions-against-bypassing-spam-filters.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/antispam/cautions-against-bypassing-spam-filters.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-zht**

**Comment by msbemba** [comment]
@michevnew We have made some changes to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1498. Once the author reviews and approves the document will be updated.
Thanks
Sri

**Comment by nam31** [comment]
Closing via #1498 
Thank you
