### ISSUE TITLE
SMH  This is your solution?

### ISSUE THREAD

**Issue by dennisaston** [MicrosoftDocs/OfficeDocs-Support#870]
Please review your "IMCEAEX" process.  This needs to be ripped out and PDQ, it's a horrible pain in the real world and the solution below is complex enough to be a non starter.  Everybody else in the world uses email addresses with domains to route email, this is the equivalent of telling somebody to use DNS to look up a domain name, and then substitute the IP address for the website you want to go to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcf2cee9-e8b0-69ef-16b2-a6be2e42bfa9
* Version Independent ID: edd0958a-ce16-9432-b03b-b2c0472e8c43
* Content: [IMCEAEX non-delivery report when you send email messages to an internal user - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/email-delivery/imceaex-ndr)
* Content Source: [Exchange/ExchangeOnline/email-delivery/imceaex-ndr.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/email-delivery/imceaex-ndr.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@dennisaston Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
