### ISSUE TITLE
Possible memory issue

### ISSUE THREAD

**Issue by k3tonan** [MicrosoftDocs/OfficeDocs-Support#871]
We don't have Saleforce add-in and even in safemode we got the error. Also re-creating a profile does not resolve. I had a user run into this and a simple reboot fixed the issue leading me to believe some form of memory issue. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6f757c4-a18a-dd0a-49bf-d1d6f632b690
* Version Independent ID: f8282152-3210-6631-05cc-99f648c4ae6b
* Content: [The time limit for logging on was reached error in Outlook - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/performance/time-limit-logging-reached-error-outlook-2016)
* Content Source: [Outlook/Client/performance/time-limit-logging-reached-error-outlook-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/performance/time-limit-logging-reached-error-outlook-2016.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment and feedback. It seems the issue can also occur by other cause. It is happy to hear that your issue is resovled.
