### ISSUE TITLE
Error for: "On the Tools menu, point to Forms, and then click Publish Form."

### ISSUE THREAD

**Issue by eldwinc** [MicrosoftDocs/OfficeDocs-Support#872]
There is no longer a tools menu in Outlook2016, so accessing "Design This Form" in latter steps was not possible. Instead, you can "customize top ribbon" and add "Design This Form" shortcut from the Developer section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 455af345-721d-c616-7247-be0f4b1e9c66
* Version Independent ID: 9c5b6c72-5a80-84e6-3b1e-928a44e182c7
* Content: [How to create a recurring e-mail message in Outlook - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/user-interface/create-recurring-email)
* Content Source: [Outlook/Client/user-interface/create-recurring-email.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/user-interface/create-recurring-email.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@eldwinc  This article has been retired because the content was very old and didn’t apply to the versions of Outlook still in Support.
Thank you
