### ISSUE TITLE
I also had failure of Excel loading when double clicking on a file in W10. None of the suggestions worked. I decided to use explorer to go into the MS Office directory and look at the Excel.exe file. For some reason when it was installed it was set to compatibility mode for VISTA. I unchecked this and left compatibility mode blank, hit apply and then rebooted. It works perfectly now.

### ISSUE THREAD

**Issue by buzard49** [MicrosoftDocs/OfficeDocs-Support#874]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62a88c46-43bb-92cf-c409-c8b3071b3865
* Version Independent ID: 19f5e98e-36a5-e2e9-39b1-5fc5ae349b50
* Content: [Excel opens a blank screen when you double-click a file icon or file name - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/excel-opens-blank)
* Content Source: [Office/Client/excel/excel-opens-blank.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/excel-opens-blank.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your feedback.
