### ISSUE TITLE
Method 2 works, setting iexplore.exe even with iexplore deleted from PC

### ISSUE THREAD

**Issue by Pipris** [MicrosoftDocs/OfficeDocs-Support#875]
### Method 2 - Export and import the registry key from another computer
Worked for me with Outlook 2010, Windows version 10.0.19041. 

There was no HKEY_LOCAL_MACHINE\Software\Classes\htmlfile\shell\**open\command**  so created **open** and **command** keys

Created two string registry values for **command** copied from another PC without Outlook installed.
Value: _(Default)_ 
string: _"C:\Program Files\Internet Explorer\IEXPLORE.EXE" %1_
Value: _DelegateExecute_
string: _{17FE9752-0B5A-4665-84CD-569794602F5C}_

This works, despite iexplore NOT installed on either PC – both use Edge and have iexplore.exe deleted.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f736e25-4b81-c26f-ee4d-640519094af6
* Version Independent ID: 9343708d-ccf7-2e46-d377-13564037a5b9
* Content: [Hyperlinks are not working - Outlook](https://docs.microsoft.com/en-nz/outlook/troubleshoot/message-body/hyperlinks-not-working-in-outlook)
* Content Source: [Outlook/Client/message-body/hyperlinks-not-working-in-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/hyperlinks-not-working-in-outlook.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your feedback.
