### ISSUE TITLE
Do not see choices for registry subkeys 

### ISSUE THREAD

**Issue by CathyB1959** [MicrosoftDocs/OfficeDocs-Support#877]
[Enter feedbIn Step 4 of this document it says to "locate the registry subkey". There is nothing in my registry box that looks like this.  I am usingPowerpoint in Office 365. HELP  I need to be able to export my slides into png with 300 dpi. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e390c4c9-9cdf-beb1-43dc-6ec45ae5fe77
* Version Independent ID: bb31c9ea-7186-22fb-195f-f481eb5137e4
* Content: [How to change the export resolution of a PowerPoint slide - Office](https://docs.microsoft.com/en-us/office/troubleshoot/powerpoint/change-export-slide-resolution?fbclid=IwAR3D64hFlvFyfOmxti9f_485fBChhnH9x0qUP9OsssM0Wc2RIgOpTEdYQcA)
* Content Source: [Office/Client/powerpoint/change-export-slide-resolution.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/powerpoint/change-export-slide-resolution.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. If you are using PowerPoint in Office 365, the registry key should be HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\PowerPoint\Options. If you cannot find the registry key, you can contact [PowerPoint support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.powerpoint) for help.
