### ISSUE TITLE
Screen tearing in Office issues and fix

### ISSUE THREAD

**Issue by NadavKolodner** [MicrosoftDocs/OfficeDocs-Support#878]
Hello!
Just reporting an issue and a fix that I have ran into a few times on a few different PCs with dedicated GPUs and integrated graphics -
The office suite (mostly Word, Excel, and OneNote) seem to pretty aggressively try and use the dedicated GPU which causes screen tearing 
The fix for this is going into the windows 10 "Graphics Settings" and manually setting the office programs to use the integrated graphics.
I thought this was useful, and took a while to troubleshoot - thought it may be something to add!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8d561d1-d212-5808-25f5-965cb97e83ea
* Version Independent ID: f94c75c6-b141-691a-49d2-c885cc3ffa1e
* Content: [Display issues in Office client applications. - Office](https://docs.microsoft.com/en-us/office/troubleshoot/settings/office-display-issues)
* Content Source: [Office/Client/settings/office-display-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/settings/office-display-issues.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Thanks for your workaround but we have a section of the article that tells you to update your video drivers. In this case, you probably have a bad driver, so we should focus on getting a proper driver, rather than reverting back to the less powerful video card.
