### ISSUE TITLE
64 & 32 Bit Paths are swapped on all Typical Locations listing...

### ISSUE THREAD

**Issue by cj1067b** [MicrosoftDocs/OfficeDocs-Support#879]
[Enter feedback here]
All the path designations are swapped as far as 64-bit and 32-bit...
"<disk drive\Programs Files(x86)\Microsoft Office\root\Office16 -> 64-bit"
"<disk drive\Programs Files\Microsoft Office\root\Office16 -> 32-bit"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec731c23-a945-5a08-06ed-4d30731a4f3f
* Version Independent ID: dff9a66f-bf56-795e-2f6d-68d33919079c
* Content: [How to repair personal folder file (.pst) - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/data-files/how-to-repair-personal-folder-file)
* Content Source: [Outlook/Client/data-files/how-to-repair-personal-folder-file.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/data-files/how-to-repair-personal-folder-file.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The article is updated.
