### ISSUE TITLE
Product names referenced in this article is incorrect - there is no such thing as Offices Online 2013

### ISSUE THREAD

**Issue by alumanos** [MicrosoftDocs/OfficeDocs-Support#881]
This documentation applies to Office Web Apps 2013, an On-Premise server product used to view and Edit Office files through the browser as documented here:

- Office Web Apps Server overview: https://docs.microsoft.com/en-us/webappsserver/office-web-apps-server-overview

The following articles need to be corrected to reflect the correct product names (Office Web Apps 2013 vs. Offices Online 2013):

- https://docs.microsoft.com/en-us/office/troubleshoot/administration/rebuild-an-office-web-apps-2013-farm-easily
- https://docs.microsoft.com/en-us/office/troubleshoot/administration/office-web-apps-and-vmware

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e618844c-1c1f-b704-997a-8fe85240a02b
* Version Independent ID: 9577586a-22a7-3830-5d69-18cfc449a56b
* Content: [Rebuild an Microsoft Offices Online 2013 farm easily - Office](https://docs.microsoft.com/en-us/office/troubleshoot/administration/rebuild-an-office-web-apps-2013-farm-easily)
* Content Source: [Office/OfficeExperts/administration/rebuild-an-office-web-apps-2013-farm-easily.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/administration/rebuild-an-office-web-apps-2013-farm-easily.md)
* Service: **sharepoint-online**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **brbering**

**Comment by jlriesco** [comment]
the articles have been updated with the correct product names.
Thanks for the feedback,
