### ISSUE TITLE
Windows 10 not mentioned in the resolution section. 

### ISSUE THREAD

**Issue by psi-m1** [MicrosoftDocs/OfficeDocs-Support#886]
This problem was identified by the Support and Recovery assistant, but the resolution for Windows 10 is not mentioned.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e0c338-4676-a7ca-c72e-93ad39b79b4c
* Version Independent ID: 4eacd191-f62a-73a4-b114-b4e386f90180
* Content: [MAPI custom solutions do not work as expected - Outlook](https://docs.microsoft.com/en-gb/outlook/troubleshoot/user-interface/custom-mapi-solutions-not-working)
* Content Source: [Outlook/Client/user-interface/custom-mapi-solutions-not-working.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/user-interface/custom-mapi-solutions-not-working.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
Closing via #1551 
Thank you
