### ISSUE TITLE
Site update with link to exchange powershell steps.

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/OfficeDocs-Support#887]
Would it be possible to have a link or such after section 1, that explains what the difference exchange powershell is, so that people are not just blindly putting in the listed PowerShell command and wondering why it isn't working?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a549802a-934e-9dc0-8b77-ba48b10af1d3
* Version Independent ID: 15b81fad-f4ba-ce9d-a186-65599bc6ce84
* Content: [Messages sent from a shared mailbox aren't saved to the Sent Items folder - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/user-and-shared-mailboxes/sent-mail-is-not-saved)
* Content Source: [Exchange/ExchangeOnline/user-and-shared-mailboxes/sent-mail-is-not-saved.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/user-and-shared-mailboxes/sent-mail-is-not-saved.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The link of Exchange PowerShell is added.
