### ISSUE TITLE
code block on this page missing the leading 'P' in the 'Param()' block statement.

### ISSUE THREAD

**Issue by exactmike** [MicrosoftDocs/OfficeDocs-Support#889]
Code excerpt from the page:

```Powershell
aram([Parameter(Mandatory = $false)]
[string]$TenantCloudDomain,
[Parameter(Mandatory = $false)]
[string]$Domain,
[Parameter(Mandatory = $false)]
[Switch]$Fix,
[Parameter(Mandatory = $false)]
[Switch]$FindAllUsersInForest
)
```

should be 

```Powershell
Param([Parameter(Mandatory = $false)]
[string]$TenantCloudDomain,
[Parameter(Mandatory = $false)]
[string]$Domain,
[Parameter(Mandatory = $false)]
[Switch]$Fix,
[Parameter(Mandatory = $false)]
[Switch]$FindAllUsersInForest
)
```
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a86a4c37-3cb1-53cc-5e31-6c5ae38c0a39
* Version Independent ID: ac48a4d6-e866-1b0d-a3b9-218648eefb68
* Content: [Archive mailbox issues for a mailbox that's migrated to or from Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/archive-mailboxes/archive-mailbox-issues)
* Content Source: [Microsoft365/compliance/archive-mailboxes/archive-mailbox-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/compliance/archive-mailboxes/archive-mailbox-issues.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The code is updated.
