### ISSUE TITLE
Document not recovered

### ISSUE THREAD

**Issue by Iqbalak** [MicrosoftDocs/OfficeDocs-Support#89]
I have tried everything mentioned on this age but I couldn't open document. Kindly help me in recovery of my document as I have spent a lot of time and effort in creating it. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b95df2f-e3de-e2d1-b48a-3fcd4183463f
* Version Independent ID: 397150eb-b8e0-62c0-55b9-c5277aacb5dd
* Content: [How to troubleshoot damaged documents in Word - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/damaged-documents-in-word#feedback)
* Content Source: [Office/Client/word/damaged-documents-in-word.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/damaged-documents-in-word.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Iqbalak** [comment]
[Physics Book I.docx](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/3504428/Physics.Book.I.docx)
Here is the file that I am trying to open, please help

**Comment by jlriesco** [comment]
This document seems to be protected under Rights Management so you probably don't have permissions to access it. Do you have the rights to it?

**Comment by Iqbalak** [comment]
I wrote it myself.

________________________________

**Comment by jlriesco** [comment]
Something is corrupted in this file, but you can try to open it with Notepad (right click on the file and choose Open with... Notepad). You won't get the document format but you will get its content.

I hope this helps.

**Comment by Brune-maker** [comment]
Hello, 

My name is Brune. I've tried for now more than a day to recover my corrupted Word document. As of course all of us here, it was of an extreme importance to me. I've tried all the tricks on this page. I've also tried a dozen more on the net - none have yet functioned. I'm ready to pay, I'm ready to anything for someone to help recover the document. Can I send it to someone ? 
Thank you so much for your help.

**Comment by jlriesco** [comment]
@Brune-maker Have you tried what I've suggested? I can read the content of the document this way. You will lose the format but not the content...
------------------------------------
Something is corrupted in this file, but you can try to open it with Notepad (right click on the file and choose Open with... Notepad). You won't get the document format but you will get its content.

**Comment by Brune-maker** [comment]
Hello, 

Thank you for your answer ! I dont have Notepad as I am on a Mac, yet I've tried to open it on every single program I have: TextEdit, Script editor, Pages, Preview...none have worked. 
Any other idea ?

**Comment by jlriesco** [comment]
Hello @Brune-maker ,
I've partially recovered the document. Most of the text is there (I think) but it lost the format. Please take a look and let me know if you can use it.
Thanks,
Jose
[Physics.Book.I.recovered.docx](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/3708456/Physics.Book.I.recovered.docx)

**Comment by jlriesco** [comment]
@Brune-maker. Could you please send me the document? I will try to open it with Notepad and save it so that you can open it in your Mac.
Thanks,
Jose

**Comment by davidmencik** [comment]
I have the same problem. I have been writing a scientific paper, saved it and it didn't save properly or who knows what, but now when I open it I can see only the first page. I have tried all your methods but they didn't work.

**Comment by oolukayode78** [comment]
Hello,
Can someone please help me? I worked on some MS Word documents and some of them could not open today. It was coming up with dialog box that says the file need to be recovered by text recovery converter. I have tried all the methods but still wouldn't except Notepad opened some and they were corrupted text. Please help.

**Comment by jlriesco** [comment]
@davidmencik I've recovered the attached text. I don't know if it is complete.

Regards,
Jose
[David Menčik.docx](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/3837941/David.Mencik.docx)

**Comment by jmr5599** [comment]
Hello I had my files of a college essay corrupted. I was wondering if you could help?
 "C:\Users\mrenf\OneDrive\Documents\Matthew Renfr4.docx"

**Comment by akanneh** [comment]
Do you have an email i can send my confidential file to because i have tried everything and followed the steps on this page but nothing is working, thanks

**Comment by nnitzan** [comment]
Dear Jose,  I have a word document with integrated images and references from Mendeley. 
My computer crashed and it is no longer possible to open the document anymore I either get a message saying the file is corrupt or if I open the .asd file I get just a bunch of boxes. 
Could you please help me restore this? this document is really important for me

**Comment by nnitzan** [comment]
[INTRODUCTION.docx](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/3923715/INTRODUCTION.docx)
attached is the file

**Comment by jlriesco** [comment]
@nnitzan unfortunately, this document is corrupted beyond recovery. I can't even open it with Notepad.  You should always backup important documents in case of computer failure. Sorry.

**Comment by rpblanker** [comment]
Hi, I have done the methods but none worked. The file is not 0kb. I can open it with notepad and wordpad but it is all spaces. Hope you can take a look. Would love to learn from this.
Thanks,
[doc.docx](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/4125709/doc.docx)

**Comment by jlriesco** [comment]
@rpblanker I’m sorry but I can’t read any text with any of the tools. This document is blank. Please remember to always create backups of your important documents.

Sorry that I couldn’t be of more help,
Jose

**Comment by rpblanker** [comment]
@jlriesco no worries and thank you for your time to check the file. I am quite curious why this case happened and hope someone can look into it in the future. :-)
Roel

**Comment by webby2103** [comment]
[Centuries.docx](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/4200723/Centuries.docx)
I am having the same problem and have tried all the steps above. Can you help me please?

**Comment by skandi13** [comment]
I am having the same problem and have tried all the steps above. Can you help me please?

[26-01-21 Cap. 3 La danza-teatro de Los Santiagos y las diferentes formas de manifestarse la identidad.docx](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/5896805/26-01-21.Cap.3.La.danza-teatro.de.Los.Santiagos.y.las.diferentes.formas.de.manifestarse.la.identidad.docx)
