### ISSUE TITLE
The advice seems not to work. 

### ISSUE THREAD

**Issue by GerardTromp** [MicrosoftDocs/OfficeDocs-Support#892]
The advice about setting the options to R1C1 notation does not work.

I have the R1C1 box checked in the formula section of options, end yet the columns remain numbered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20135f47-590f-3fd8-64b8-4bc9ffca5e4a
* Version Independent ID: 1c1f427d-3e94-e3a4-df33-beeca03b3db0
* Content: [Columns and rows are labeled numerically - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/numeric-columns-and-rows)
* Content Source: [Office/Client/excel/numeric-columns-and-rows.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/numeric-columns-and-rows.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. You can contact [Excel Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.excel) for more help.
