### ISSUE TITLE
Missing Registry Key HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\PowerPoint\Options

### ISSUE THREAD

**Issue by zhanzhaoli** [MicrosoftDocs/OfficeDocs-Support#899]
Dear Developers,

I am trying to follow the steps, but I cannot find the PowerPoint key under \Office\16.0\. There is only one key, which is for Outlook.

I am using Windows 10 and PowerPoint from Office 365, which was installed from the Microsoft Store before I purchased my laptop. The virtualized registry caused by the Microsoft Store may be an issue.

I was wondering if you would have any suggestions.

Thank you so much in advance.

Best,
Z

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e390c4c9-9cdf-beb1-43dc-6ec45ae5fe77
* Version Independent ID: bb31c9ea-7186-22fb-195f-f481eb5137e4
* Content: [How to change the export resolution of a PowerPoint slide - Office](https://docs.microsoft.com/en-us/office/troubleshoot/powerpoint/change-export-slide-resolution)
* Content Source: [Office/Client/powerpoint/change-export-slide-resolution.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/powerpoint/change-export-slide-resolution.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. Here is the screenshot of the registry key:
![image](https://user-images.githubusercontent.com/16147799/98493807-602d5100-2276-11eb-8379-3a50ad2b3326.png)
If you cannot find the key, you can contact [PowerPoint Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.powerpoint) for help.

**Comment by zhanzhaoli** [comment]
Below is what is shown on my laptop:
![image](https://user-images.githubusercontent.com/67124551/98494112-21fa4800-220a-11eb-87d8-5446a4d2c376.png)
