### ISSUE TITLE
Inaccurate

### ISSUE THREAD

**Issue by colt64** [MicrosoftDocs/OfficeDocs-Support#9]
"This article contains information about accessing Unified Logging System (ULS) logs for SharePoint Online."

This statement is incorrect as this page provides no information on how to access ULS. In fact, below, it says that Microsoft does not provide access to ULS. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8969b34-de56-9e17-b0a2-6902014e7305
* Version Independent ID: 51fb1dd7-cebd-c9dc-efe6-85202e59e84c
* Content: [Information about ULS log access for SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/support/online-admin/information-about-uls-log-access#feedback)
* Content Source: [SharePoint/SharePointOnline/online-admin/information-about-uls-log-access.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/online-admin/information-about-uls-log-access.md)
* Service: **sharepoint-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by spowriter** [comment]
Updated. Thanks!
