### ISSUE TITLE
It is simply because Office thinks it is an App from the store

### ISSUE THREAD

**Issue by tschuyler99** [MicrosoftDocs/OfficeDocs-Support#90]
You are suggesting people spend hours doing all kinds of unnecessary work to try and resolve a simple problem. The pre-installed version of office coming on many new laptops is from the Microsoft store and is considered an APP. We, especially corporate users, try to install another version of office and it fails with Error 1935 because it conflicts with the fact that Windows thinks Office in an APP. Do the following and the problem is resolved instantly and takes two seconds. Please give people a "fix it" for this or change this website to show this simple solution

Delete this whole registry folder so office stops thinking it is an app and office installs fine. I hope this helps other people.

HKEY_LOCAL_MACHINE\SOFTWARE\MICROSOFT\APPMODEL
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0b08071-7c09-2a48-b32a-4fd00d2a8464
* Version Independent ID: 9e8fce76-2355-6b74-504d-970636884b1a
* Content: [Error 1935 when you try to install Microsoft Office 2010 or 2007 - Office](https://docs.microsoft.com/en-us/office/troubleshoot/activation-installation/error-1935-when-install-office-2010)
* Content Source: [Office/Client/activation-installation/error-1935-when-install-office-2010.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/activation-installation/error-1935-when-install-office-2010.md)
* Service: **sharepoint-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by tschuyler99** [comment]
Maybe my solution is not intended for this page. I realize now it is for older OS and not Windows 10

**Comment by jlriesco** [comment]
Yes, The suggestions in the article still make sense instead of editing the registry. Thank you for your correction.

**Comment by jlriesco** [comment]
We will be updating the article.
