### ISSUE TITLE
MSOL_AD_Sync_RichCoexistence not used any more

### ISSUE THREAD

**Issue by mardahl** [MicrosoftDocs/OfficeDocs-Support#900]
The article seems a bit misleading as the MSOL_AD_Sync_RichCoexistence group is no longer deployed by newer instances of Azure AD Connect when enabling Hybrid Exchange.

Please amend the details to clearly indicate that this is for legacy environments that use DirSync.
Or maybe just mark it all as deprecated as the DirSync tool should no longer be used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e70d48-7cbf-75c6-6115-9c9a29629e55
* Version Independent ID: aebf2d28-b509-6147-65ea-ef7389776e59
* Content: [Exchange Online attributes aren't written back to on-premises AD directory service - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/attribute-not-written-to-azure-ad)
* Content Source: [Exchange/ExchangeHybrid/administration/attribute-not-written-to-azure-ad.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/administration/attribute-not-written-to-azure-ad.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello @mardahl , please have a look at #1640 
Thank you

**Comment by mardahl** [comment]
article delete :)
