### ISSUE TITLE
Typo "Visip"

### ISSUE THREAD

**Issue by campbellkerr** [MicrosoftDocs/OfficeDocs-Support#901]
[Enter feedback here]
Typo on left side tree under the Visio section:

https://docs.microsoft.com/en-us/office/troubleshoot/visio/visio-not-have-certain-shapes-and-stencils

![image](https://user-images.githubusercontent.com/38451588/98487883-cc5d8400-2279-11eb-858d-9e9126d69f28.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6909052a-e343-76bd-b1ed-db75a26f97b4
* Version Independent ID: 6556cffb-3f2b-f558-cec6-500cd12c344b
* Content: [Visio 2010 or 2013 does not have certain shapes and stencils included - Office](https://docs.microsoft.com/en-us/office/troubleshoot/visio/visio-not-have-certain-shapes-and-stencils)
* Content Source: [Office/Client/visio/visio-not-have-certain-shapes-and-stencils.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/visio/visio-not-have-certain-shapes-and-stencils.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by lucciz01** [comment]
Resolved.
