### ISSUE TITLE
iOS outlook email asks to re-enter password every 2 days 

### ISSUE THREAD

**Issue by campbelljoiners** [MicrosoftDocs/OfficeDocs-Support#904]
I am constantly being asked to re-enter my password on my iPhone for all my outlook accounts every 2-3 days, this is also on my wife’s phone who shares the same emails and also her own accounts. 

Is this a iPhone issue or outlook issue that could be rectified?

**Comment by nam31** [comment]
@campbelljoiners The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@campbelljoiners We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
