### ISSUE TITLE
Solução não se aplica

### ISSUE THREAD

**Issue by edinaldo-at** [MicrosoftDocs/OfficeDocs-Support#908]
Estou Utilizando o Office 365.

A Descrição descreve exatamente o meu problema, mas a solução não se aplica porque os valores já estão corretos no meu outlook e no regedit

alguma outra opção?

**Comment by nam31** [comment]
@edinaldo-at The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@edinaldo-at We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
