### ISSUE TITLE
Commands incomplete

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/OfficeDocs-Support#91]
a) You need to document HOW to create the $Members. An older article shows an equivalent "https://docs.microsoft.com/en-us/previous-versions/office/exchange-server-2010/ee633471(v=exchg.141)" BUT that way of creating $Members does not work.
b) You need to document where one can find " Show a room list " box.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1e6278-ea7f-4eea-fbb1-f2de033ee400
* Version Independent ID: a90193e5-6ed9-8f29-d342-008e6cc904e9
* Content: [Room Finder doesn't display any conference rooms when a user creates a meeting - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/meetings/conference-rooms-not-dispalyed)
* Content Source: [Exchange/ExchangeOnline/meetings/conference-rooms-not-dispalyed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/meetings/conference-rooms-not-dispalyed.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
Hi @blouwagie , this article has been updated and moved to https://docs.microsoft.com/en-us/exchange/troubleshoot/calendars/conference-rooms-not-displayed
Please let us know if you are still facing the issue you raised initially.
Thanks

**Comment by nam31** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
