### ISSUE TITLE
Shared Calendars on Outlook for Mac for Office 365 - New Outlook Interface

### ISSUE THREAD

**Issue by S-Bowen** [MicrosoftDocs/OfficeDocs-Support#910]
It does not seem to be possible to access shared calendars in Outlook for Mac for Office 365 within the New Outlook interface. I would like to request an update to the documents to reflect this attempted use case.

These forms and answers also reflect the unavailability of this feature in New Outlook:
* https://outlook.uservoice.com/forums/924856-the-new-outlook-for-mac/suggestions/38980501-open-view-shared-calendars
* Under "Known Issues": https://support.microsoft.com/en-us/office/the-new-outlook-for-mac-6283be54-e74d-434e-babb-b70cefc77439
* https://answers.microsoft.com/en-us/msoffice/forum/all/shared-calendars-in-new-outlook/7094d0fb-5675-41fc-9ea7-d76bbe43eb97
* https://answers.microsoft.com/en-us/msoffice/forum/all/viewing-peoples-calendars-in-new-outlook-for-mac/04f94323-cf88-404a-98fe-d08ab31f32f6

If this page is not intended to apply to the New Outlook Interface, I apologize.

Many thanks for your time, hope you're all doing well! 😄
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93d47644-35c4-308b-e8f4-d1ab20ff3199
* Version Independent ID: 3c2e669e-16a5-1424-f56a-58eb5409d7e9
* Content: [Open Shared Calendar option is unavailable - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/calendars/cannot-open-a-shared-calendar-in-outlook-2016)
* Content Source: [Outlook/Mac/calendars/cannot-open-a-shared-calendar-in-outlook-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Mac/calendars/cannot-open-a-shared-calendar-in-outlook-2016.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The article is updated with the websites added to the More information section.
