### ISSUE TITLE
Die Skype Funktion wird bei jedem Start erneut ausgeblendet

### ISSUE THREAD

**Issue by CreatedName** [MicrosoftDocs/OfficeDocs-Support#911]
[Feedback hier eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von Problemen docs.microsoft.com ➟ GitHub erforderlich.*

* ID: 55180151-8170-613f-af27-29d935937b37
* Version Independent ID: 73283581-32a1-7412-4383-a7dbb43bba4d
* Content: [Skype-Besprechungs Steuerelement wird nicht angezeigt - Outlook](https://docs.microsoft.com/de-ch/outlook/troubleshoot/user-interface/skype-meeting-control-is-not-displayed)
* Content Source: [Outlook/Client/user-interface/skype-meeting-control-is-not-displayed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/user-interface/skype-meeting-control-is-not-displayed.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Do you mean the configuration will be reset after the restart?

**Comment by CreatedName** [comment]
Jap

Simonx Xu <notifications@github.com> schrieb am Fr., 13. Nov. 2020, 03:00:

**Comment by msbemba** [comment]
@CreatedName Thank you for your feedback. Does it reset after the registry changes are made? I was able to test it and it sticks even after a restart. Did you also check fi there are any windows updates pending?

Thanks
Sri

**Comment by msbemba** [comment]
@CreatedName Wanted to circle back to check if the issue persists. If yes, Does it reset after the registry changes are made? I was able to test it and it sticks even after a restart. Did you also check fi there are any windows updates pending?

Thanks
Sri

**Comment by nam31** [comment]
@CreatedName We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
