### ISSUE TITLE
The change does not remain

### ISSUE THREAD

**Issue by eochagavia** [MicrosoftDocs/OfficeDocs-Support#912]
Each time there is a product patch, the solution must be reapplied

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebca74ee-463b-8322-5ee2-30813ddb8127
* Version Independent ID: d9b59f78-7db7-29cb-90b1-986128786674
* Content: [Exchange Server doesn't display all OUs - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/exchange-server-not-display-all-ou)
* Content Source: [Exchange/ExchangeServer/administration/exchange-server-not-display-all-ou.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/administration/exchange-server-not-display-all-ou.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by dariomws** [comment]
Hi @eochagavia, thank you for your feedback and sorry for the delay.

This is very well-known and documented here:
https://docs.microsoft.com/exchange/plan-and-deploy/install-cumulative-updates

Anyway, I think it's a good addition to this article, and I'll update it.
