### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by silviews** [MicrosoftDocs/OfficeDocs-Support#913]
Hello, 
This is a useful tool in Office 365 world and would be even better if the documentation is kept updated with the new features. 
Check screenshots and the steps , some match others don't. 
A handout for Office 365 admins to share with end-users would be very helpful too. 
Otherwise just keep up the good work and develop the tool. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8d636cc-bc81-84ad-0e05-ffcb60ba8224
* Version Independent ID: 82cda844-eb2e-4a1a-60ec-c017fe189638
* Content: [Scan by using Microsoft Support and Recovery Assistant - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/performance/how-to-scan-outlook-by-using-microsoft-support-and-recovery-assistant)
* Content Source: [Outlook/Client/performance/how-to-scan-outlook-by-using-microsoft-support-and-recovery-assistant.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/performance/how-to-scan-outlook-by-using-microsoft-support-and-recovery-assistant.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment and feedback.
