### ISSUE TITLE
How to determine the license type of your Microsoft Office product for macOS

### ISSUE THREAD

**Issue by RabbitMC** [MicrosoftDocs/OfficeDocs-Support#914]
Hi,

you describe in "How to determine the license type of your Microsoft Office product" by open up one of the Office Apps. This is great. But I need a solution how to determine the license type without open up the Application. 

How can I determine the license type of Microsoft Office for macOS using Command-Line, or other detection methods? This is necessary for enterprise customers for their license audits.

Thanks

**Comment by nam31** [comment]
@RabbitMC The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@RabbitMC We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
