### ISSUE TITLE
I have a similar problem, but it has nothing to do with data "On My Computer."  When I enter a new contact in MS Outlook for Mac (desktop app) (latest version 16.43), it shows up in my OWA account and syncs quickly with my iPhone, but it disappears in the original place -- MS Outlook for Mac desktop app!  Very strange!

### ISSUE THREAD

**Issue by dlchan8** [MicrosoftDocs/OfficeDocs-Support#916]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e317903-a3f0-5f5b-184b-bfae60b1b170
* Version Independent ID: c9676582-234d-6e48-20ac-9167b2de8666
* Content: [New appointments and contacts not synchronized to Outlook Web App - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/client-connectivity/added-appointments-contacts-not-synchronized-to-owa)
* Content Source: [Exchange/ExchangeServer/client-connectivity/added-appointments-contacts-not-synchronized-to-owa.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/client-connectivity/added-appointments-contacts-not-synchronized-to-owa.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. If the issue persists, you can contact [Outlook Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=6dd15f3c-b096-436f-95dc-6f4ad08e1980) for more help.
