### ISSUE TITLE
Per-Location and Hierarchy-Based View Settings Still Broken in Modern Interface

### ISSUE THREAD

**Issue by Shoujin** [MicrosoftDocs/OfficeDocs-Support#918]
I am confused why the prior report of this issue was removed. This is still not working and has been broken for years in the modern interface while it works fine in the classic interface. The direction to "just use the classic interface" is not acceptable since the classic interface is being phased out.

Why can Microsoft not take this issue seriously and give it some attention. It is a common need for users to be able to assign different column views in sub-folders versus the top-level folder. Not all data storage and access schemas work properly in a flattened storage environment despite the rhetoric of Microsoft's marketing department.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93b7fa94-4918-3789-1392-6c88a4abff1f
* Version Independent ID: 8ed491fb-d6bd-47b7-06d1-d01ba7b94e1b
* Content: [Per-location view settings don't work at the folder level - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/lists-and-libraries/per-location-view-settings-fail-working)
* Content Source: [SharePoint/SharePointOnline/lists-and-libraries/per-location-view-settings-fail-working.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/lists-and-libraries/per-location-view-settings-fail-working.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The behavior is by design, sorry for the inconvenience. If you need more help, you can contact [SharePoint Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.sharepoint).
