### ISSUE TITLE
The link to article about creawting of Room List is outdated

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/OfficeDocs-Support#92]
This 2019 article links to an article that talks about "Exchange Server 2010 SP2, Exchange Server 2010 SP3" and the syntax of those commands does not work to create the $Member content. You need to get this article fleshed out more completely and/or explain why/when/how room lists are to be used. When I apply the little information I find here, our users still do not see any rooms in the Room finder although I did manage to create the Room List and Add rooms as members (by adding them one by one in PowerShell)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1e6278-ea7f-4eea-fbb1-f2de033ee400
* Version Independent ID: a90193e5-6ed9-8f29-d342-008e6cc904e9
* Content: [Room Finder doesn't display any conference rooms when a user creates a meeting - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/meetings/conference-rooms-not-dispalyed)
* Content Source: [Exchange/ExchangeOnline/meetings/conference-rooms-not-dispalyed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/meetings/conference-rooms-not-dispalyed.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@blouwagie, this article has been updated and moved to https://docs.microsoft.com/en-us/exchange/troubleshoot/calendars/conference-rooms-not-displayed
Please let us know if you are still facing the issue you raised initially.
Thanks

**Comment by nam31** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
