### ISSUE TITLE
did not resolve issue

### ISSUE THREAD

**Issue by ksanzi** [MicrosoftDocs/OfficeDocs-Support#921]
I tried to follow the steps documented for google chrome, but these steps did not line up with my chrome settings. I added all the sites to the "see all cookies and site data" but that did not resolve my issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c17faf2-0e38-0a98-454c-3c2c4387b37f
* Version Independent ID: d9153b98-dc39-fdd1-a798-07da0caaaa64
* Content: [Microsoft Teams is stuck in a login loop in Edge or Internet Explorer - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#resolution)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. If the issue persists, you can contact [Teams Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.teams) for more help.
