### ISSUE TITLE
Typo in PowerShell example

### ISSUE THREAD

**Issue by cspargo-apria** [MicrosoftDocs/OfficeDocs-Support#924]
Under Option 2, under the example **For Exchange 2013 and later versions**, the command is missing the first opening parenthesis:

```Get-SendConnector "outbound to office 365").SourceTransportServers | foreach {get-transportservice $_.name} | Select-Object name,SendProtocolLogPath```

Should be:

```(Get-SendConnector "outbound to office 365").SourceTransportServers | foreach {get-transportservice $_.name} | Select-Object name,SendProtocolLogPath```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea6d1f62-928b-9378-5326-214503baa567
* Version Independent ID: 403dda41-c9fd-831c-c5d9-5de3af8a71b3
* Content: [550 5.7.64 TenantAttribution; Relay Access Denied SMTP when users send mails - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/email-delivery/relay-access-denied-smtp)
* Content Source: [Exchange/ExchangeOnline/email-delivery/relay-access-denied-smtp.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/email-delivery/relay-access-denied-smtp.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The article is updated.
