### ISSUE TITLE
Derived Trunk Group - Not able to add New-CsOnlineVoiceRoute

### ISSUE THREAD

**Issue by prakash12305** [MicrosoftDocs/OfficeDocs-Support#925]
Hi Team,
 
I configured the same EnterpriseVoiceEnabled $True, still same issue

`Cannot find specified Gateway "demo2.sbc.mobex4teams.com".
    + CategoryInfo          : InvalidArgument: (Description=;Nu...e=US and Canada:OnlineRoute) [New-CsOnlineVoiceRoute
   ], ArgumentException
    + FullyQualifiedErrorId : CustomValidationFailed,Microsoft.Rtc.Management.Internal.NewOnlineVoiceRouteCmdlet
    + PSComputerName        : adminin1.online.lync.com`

Carrier Tenant:
 carrier-domain- sbc.mobex4teams.com - Domain is added and Activated the domain 
PSTN-Gateway is created and active (OPTIONS going both ways)

Customer Tenant:
customer Derived Trunk FQDN -  demo2.sbc.mobex4teams.com
FQDN demo2.sbc.mobex4teams.com - added as domain and Activated the domain and created a test user and associated E5 license and enabled 

EnterpriseVoiceEnabled set to true to this derived Trunk Group user

then create  New-CsOnlineVoiceRoute failed

` New-CsOnlineVoiceRoute -Identity "US and Canada" -NumberPattern “^\+1(\d{10})$” -OnlinePstnG
atewayList demo2.sbc.mobex4teams.com -OnlinePstnUsages To_Mobex4Teams
Cannot find specified Gateway "demo2.sbc.mobex4teams.com".
    + CategoryInfo          : InvalidArgument: (Description=;Nu...e=US and Canada:OnlineRoute) [New-CsOnlineVoiceRoute
   ], ArgumentException
    + FullyQualifiedErrorId : CustomValidationFailed,Microsoft.Rtc.Management.Internal.NewOnlineVoiceRouteCmdlet
    + PSComputerName        : adminin1.online.lync.com`

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ad8db89-c334-bbec-5695-76207739934d
* Version Independent ID: c98f79d5-7d0c-3563-bdbc-ed7835980a4a
* Content: [Can't add a new derived SBC for Direct Routing - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/online-phone-system/add-new-derived-sbc-direct-routing)
* Content Source: [SkypeforBusiness/SkypeOnline/online-phone-system/add-new-derived-sbc-direct-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeOnline/online-phone-system/add-new-derived-sbc-direct-routing.md)
* Service: **skype-for-business-online**
* GitHub Login: @TobyTu
* Microsoft Alias: **scapero**

**Comment by TobyTu** [comment]
Thanks for your feedback! In this case, I suggest you submit a request to Microsoft for further assistance.
