### ISSUE TITLE
Which computer are we supposed to do this on?

### ISSUE THREAD

**Issue by clairestreb** [MicrosoftDocs/OfficeDocs-Support#926]
There are instructions to follow, but they need to say whether to do them on the client or the server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab957b20-e97d-5705-c5ea-882f9965769d
* Version Independent ID: a14f80f7-6f4d-fe41-e40e-9000b3cd66fb
* Content: [WinRM client cannot process the request when connect to Exchange Online - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/winrm-cannot-process-request)
* Content Source: [Exchange/ExchangeOnline/administration/winrm-cannot-process-request.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/administration/winrm-cannot-process-request.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@clairestreb Thank you for your feedback. This problem occurs when you try to use remote Windows PowerShell to connect to Microsoft Exchange Online in Microsoft Office 365, The main cause is that the windows remote management service is either not installed or not started. So the solution needs to be applied to the machine that you are using to connect to EXO.

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@clairestreb Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
