### ISSUE TITLE
MS teams showing as out of office even after joined back

### ISSUE THREAD

**Issue by sudeeshkalam** [MicrosoftDocs/OfficeDocs-Support#927]
Seems there is a bub in the flow between outlook and MS teams. I was on vacation till friday and joined back today , monday . However MS teams still shows out of office and not allowing me to change status . Fix was to check all the out of office emails whcih other sent in the outlook and instead of accept those change to tentative . After  doing this , issue on MS teams got fixed.

**Comment by nam31** [comment]
@sudeeshkalam The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@sudeeshkalam We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.
