### ISSUE TITLE
Remote window powershell connection issue

### ISSUE THREAD

**Issue by yogendraemail** [MicrosoftDocs/OfficeDocs-Support#93]
Getting below error while trying Remote window powershell connection, 

System.Management.Automation.Remoting.PSRemotingTransportException: Processing data from remote server webmail.candchealthcare.co.uk failed with the following error message: [ClientAccessServer=CASServer,BackEndServer=exchange01.local,RequestId=769b0043-a1f4-4556-8297-46f606c8aa37,TimeStamp=21/08/2019 10:27:07] [FailureCategory=WSMan-MultipleClientMessages] The WS-Management service cannot process the request. Operations involving multiple messages from the client are not supported. For more information, see the about_Remote_Troubleshooting Help topic

**Comment by nam31** [comment]
@yogendraemail The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by nam31** [comment]
@yogendraemail We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
