### ISSUE TITLE
Update to clarify impact and any risk - customers have concerns making such changes without understanding the risks

### ISSUE THREAD

**Issue by KevinShaugh** [MicrosoftDocs/OfficeDocs-Support#931]
In CFLs I've worked on customers are concerned about any negative perf or queueing impact these settings might have. Would be good for the article to explain in more layman's terms how all these work together and any caveats around perf, e.g. if it's not just used to route mail to O365 how does this impact any other mail? 

Here's what I wrote for one customer CFL today:

Mehak>> The connections are exclusive to office 365 , but after making these changes ..the impact on queue is something we want to know ..as in queue would decrease as we are decreasing the SmtpConnectorQueueMessageCountThresholdForConcurrentConnections to a lower value..decraesing this would decrease the number of connections its making to o365, if yes ..the number of message count remains the same and queue would still swell? and this change has to be made on last hop and we recommend this change to be permnent as a pro active approach?

[11:11 AM] Kevin Shaughnessy
    Mehak Virmani (TIER 3) SMTPConnectorQueueMessageCountThresholdForConcurrentConnections is lowering the # of messages  transmitted per connection so more connections are spawned thus spreading the load and reducing the chance of connectivity timeout error from holding a connection open to long while waiting to deliver 20 messages
​[11:14 AM] Kevin Shaughnessy
    It's just load balancing connections / message transmission over lots more pipes so if any one goes down you have plenty left to continue processing messages, so queues go down not swell - yes on the typically edge server that's connecting to O365, and yes permanent recommended setting - we're working on publishing a KB (or docs I guess) article on these recommended settings, and are working with Exchange engineering to change their default settings to more closely align to these recommendations so that by default with future versions of Exchange customers will have more optimized settings for resilient connectivity to O365. 
<https://teams.microsoft.com/l/message/19:cddade9f147a404eb0468fc215d89f61@thread.skype/1606245086113?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&amp;groupId=d9aff0be-41ea-4635-9e63-bb3599f46a57&amp;parentMessageId=1606230709746&amp;teamName=Exchange-Outlook-EOP Live Site Response&amp;channelName=Sev 2 (DAG, CFL, EME, PSI)&amp;createdTime=1606245086113>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4d7d69c-07d2-d1ce-4aaa-eb0fb088390a
* Version Independent ID: 09564c67-96dc-aa99-c64a-3933178e5889
* Content: [Email messages are stuck in Exchange Server queues for several minutes - Exchange](https://review.docs.microsoft.com/en-us/exchange/troubleshoot/administration/email-stuck-queues?branch=pr-en-us-2238)
* Content Source: [Exchange/ExchangeServer/administration/email-stuck-queues.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/administration/email-stuck-queues.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @TobyTu
* Microsoft Alias: **sesteven**

**Comment by TobyTu** [comment]
add new content to clarify the impacts after making these changes.
