### ISSUE TITLE
Typo on page

### ISSUE THREAD

**Issue by ssnedeker** [MicrosoftDocs/OfficeDocs-Support#932]
There is a typo on this page: Instal Calendar Printing Assistant fails

![image](https://user-images.githubusercontent.com/26071790/100141859-06757b00-2e61-11eb-8eb7-b12dbd21a250.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85126cbd-c464-7965-9d71-328cb41ed2a5
* Version Independent ID: 39abc797-2cdf-59e9-63f8-39889f584d12
* Content: [Can't install Calendar Printing Assistant - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/installation/installing-calendar-printing-assistant-fails#feedback)
* Content Source: [Outlook/Client/Installation/installing-calendar-printing-assistant-fails.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/Installation/installing-calendar-printing-assistant-fails.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by simonxjx** [comment]
Thanks for reporting this issue. The name is updated.
