### ISSUE TITLE
Possible solution...

### ISSUE THREAD

**Issue by arturochent** [MicrosoftDocs/OfficeDocs-Support#935]
The solution here didn't work for me. By toying around with the indexing options, I noticed that Microsoft Outlook was not present in the Indexing Options. After adding it by clicking on modify, all searches completed without problems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6fb6580-b751-971f-f631-c26b57c8da9b
* Version Independent ID: 8fb1112e-0dd6-2a81-e34a-19f1cd7dd83f
* Content: [Error (Something went wrong and your search couldn't be completed) when searching from an additional mailbox in Outlook - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/user-interface/can't-search-additional-mailbox)
* Content Source: [Outlook/Client/user-interface/can't-search-additional-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/user-interface/can't-search-additional-mailbox.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @TobyTu
* Microsoft Alias: **aruiz**

**Comment by MaratMussabekov** [comment]
Hello, if outlook is not presented in the indexed options, then you are not to perform any search, not only the search in shared mailbox performed using the primary mailbox user's credentials, so I believe this is different scenario.
Thank you

**Comment by nam31** [comment]
@arturochent Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
