### ISSUE TITLE
MS Teams stuck in Firefox as well

### ISSUE THREAD

**Issue by eudoxos** [MicrosoftDocs/OfficeDocs-Support#936]
Please add Firefox instructions. Or better, fix Teams to be compliant with no-tracking browsers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c17faf2-0e38-0a98-454c-3c2c4387b37f
* Version Independent ID: d9153b98-dc39-fdd1-a798-07da0caaaa64
* Content: [Microsoft Teams is stuck in a login loop in Edge, Internet Explorer or Google Chrome - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#resolution)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by KB-Q** [comment]
**It Works.**

I was facing the same error in Edge. I followed the instructions given, essentially copy-pasting the URLs into the Allow section in the Cookie settings, yet it didn't fix anything. That's when I learnt the hard way that you have to copy-paste the **whole URL**, i.e., including the [*.] part as well! I did the same for all 6 URLs given, and it worked like a charm. Let me know if it works for you as well.

Regards,
Karthik.

**Comment by eudoxos** [comment]
I ditched Teams, so cannot test, sorry.  It is their business to make a working product, following standards (we all know MS hast pretty bad track record in that) without requiring quirks like this.
