### ISSUE TITLE
Excessingly slow performance when using Tracked Changes

### ISSUE THREAD

**Issue by Traveler4** [MicrosoftDocs/OfficeDocs-Support#937]
Rather than to provide a workaround, the **root cause** of the excessingly slow performance should be solved. Tracked changes could be a very valuable feature but practical use is severely hampered by this performance issue.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81cf0dee-0e3c-5347-495b-0556c5d99a23
* Version Independent ID: c6b80d23-701d-a693-7e4c-37cd1db5fc69
* Content: [Word slows or stops responding - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/word-stops-responding)
* Content Source: [Office/Client/word/word-stops-responding.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/word-stops-responding.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. The steps in the article is a resolution but not a workaround. If you need more help and suggestions, you can contact [Word support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.word).
