### ISSUE TITLE
Syntax error in 'seconds' section of code

### ISSUE THREAD

**Issue by nfisher86** [MicrosoftDocs/OfficeDocs-Support#939]
I am getting a syntax error in the 'seconds' section.  Please correct the code and repost to the original page.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be969d50-8518-365f-f3ed-5c0e14d55104
* Version Independent ID: 11bad482-781b-bbae-ce60-53f8164d137e
* Content: [Convert degrees/minutes/seconds angles to or from decimal angles - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/convert-degrees-minutes-seconds-angles)
* Content Source: [Office/Client/excel/convert-degrees-minutes-seconds-angles.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/convert-degrees-minutes-seconds-angles.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
The code works just fine. When you enter the example, please make sure that you don't enter a period at the end. Enter 10.46 no 10.46.

**Comment by nfisher86** [comment]
To make it work I had to apply the fix mentioned from comment #714 to the 'seconds' section of the 'Convert_Decimal' code.  I think there is still a syntax error in the original code.  Here is what was in that comment: 

The code in the page it gives an error:

Where it says:
minutes = Val(Mid(Degree_Deg, InStr(1, Degree_Deg, "°") + 2, _
InStr(1, Degree_Deg, '") - InStr(1, Degree_Deg, _
"°") - 2)) / 60

It should say:

minutes = Val(Mid(Degree_Deg, InStr(1, Degree_Deg, "°") + 2, _
InStr(1, Degree_Deg, " '") - InStr(1, Degree_Deg, _
"°") - 2)) / 60

It lakc an " before the '. Because of that, its readed as comments.

**Comment by jlriesco** [comment]
Thanks for your feedback. The article has been updated.

**Comment by nfisher86** [comment]
Thank you very much!

**Comment by samnawi** [comment]
May I re-open this issue since I still got a return of "Compile error; Syntax error" 
![image](https://user-images.githubusercontent.com/8871958/115830981-31c5bb80-a43b-11eb-943e-7d0a34df620b.png)

**Comment by r-u-n123** [comment]
This should work 

Function Convert_Decimal(Degree_Deg As String) As Double
 ' Declare the variables to be double precision floating-point.
 Dim degrees As Double
 Dim minutes As Double
 Dim seconds As Double
 ' Set degree to value before "°" of Argument Passed.
 degrees = Val(Left(Degree_Deg, InStr(1, Degree_Deg, "°") - 1))
 ' Set minutes to the value between the "°" and the "'"
 ' of the text string for the variable Degree_Deg divided by
 ' 60. The Val function converts the text string to a number.
 minutes = Val(Mid(Degree_Deg, InStr(1, Degree_Deg, "°") + 2, _
 InStr(1, Degree_Deg, "'") - InStr(1, Degree_Deg, _
 "°") - 2)) / 60
 ' Set seconds to the number to the right of "'" that is
 ' converted to a value and then divided by 3600.
 seconds = Val(Mid(Degree_Deg, InStr(1, Degree_Deg, "'") + _
 2, Len(Degree_Deg) - InStr(1, Degree_Deg, "'") - 2)) _
 / 3600
 Convert_Decimal = degrees + minutes + seconds
End Function

**Comment by Reeced40** [comment]
@nfisher86 @samnawi please can you confirm if @r-u-n123 suggestion above has worked for you?

**Comment by Reeced40** [comment]
@nfisher86 please can you confirm the above, if the suggestion from @r-u-n123 has worked for you.

**Comment by nam31** [comment]
@nfisher86 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
