### ISSUE TITLE
How is this workaround carried out?

### ISSUE THREAD

**Issue by swjensen** [MicrosoftDocs/OfficeDocs-Support#94]
How do you add "Everyone except external users" to an Azure Active Directory group? I can't find an interface in any of the O365/Azure admin portals where this is possible

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 81a93f5a-6e89-4811-9c34-41932077e4eb
* Version Independent ID: 7598878f-e9b4-2fc7-f20a-37438e010dc1
* Content: [Everyone except external users group is removed on Office 365 - SharePoint](https://docs.microsoft.com/da-dk/sharepoint/support/sharing-and-permissions/everyone-except-external-user-removed#feedback)
* Content Source: [SharePoint/SharePointOnline/sharing-and-permissions/everyone-except-external-user-removed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sharing-and-permissions/everyone-except-external-user-removed.md)
* Service: **sharepoint-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VeroniquePalmer** [comment]
Agree with Dean.  Also, when you create a new visitors group, also overnight, it is deleted and reset to the original one.  The permissions model is broken.

**Comment by markgort86** [comment]
I also tried this work-around. But agree that it's not possible. I hope there will be a fix soon! A customer is waiting for a solution. At the moment it's not possible to give read access to a private or public team. If i'm remember it right, on a public team everyone except of external users have "modify" rights and it's not possible to change that to read on a SharePoint site connected with a group. For example if you're using Microsoft Teams.

**Comment by claudialake** [comment]
The article has been updated to clarify.
