### ISSUE TITLE
Multiple selection error message occuring even for single selection

### ISSUE THREAD

**Issue by srpremkumar** [MicrosoftDocs/OfficeDocs-Support#942]
[Enter feedback here]
I am aware of the multiple selection rules and i have successfully pasted before without any issue.
My present issue is:
When I try to copy a single cell from one file and try to paste it into another, I am getting the Multiple selection error message and I am forced to type the text.
Any solution please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f199f229-6d90-07bc-c26b-971a8ee42e96
* Version Independent ID: a763a38b-fad4-f31e-512e-96bb276ed1a8
* Content: [That command cannot be used on multiple selections - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/command-cannot-be-used-on-selections)
* Content Source: [Office/Client/excel/command-cannot-be-used-on-selections.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/command-cannot-be-used-on-selections.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your feedback. You can contact [Excel Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.excel) for more help.
