### ISSUE TITLE
点击键盘布局只显示出数字，没有字母

### ISSUE THREAD

**Issue by dorotheazhang** [MicrosoftDocs/OfficeDocs-Support#943]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a9488d8a-214e-8f83-6dd1-cfdf60c61ecb
* Version Independent ID: 301fddc3-756e-1053-c0c9-9f3e452457f2
* Content: [列出 Outlook 的一些问题 - Outlook](https://docs.microsoft.com/zh-cn/outlook/troubleshoot/outlook-client-welcome)
* Content Source: [Outlook/Client/outlook-client-welcome.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/outlook-client-welcome.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by AmandaAZ** [comment]
Thanks for your feedback. You can try to troubleshoot this issue from [here](https://support.microsoft.com/office/troubleshooting-74644ed7-268a-4e0d-a4eb-52257726e624) or go to [Outlook Q&A](https://docs.microsoft.com/answers/topics/office-outlook-itpro.html).
