### ISSUE TITLE
Proxy address

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/OfficeDocs-Support#948]
In regards to point 3: "If you have an Exchange hybrid deployment, make sure that the proxy address of the Active Directory mail contact object is set to the correct email address. If it's not, update the SMTP value, and then run directory synchronization."
--> In my opinion this should be "Target address" instead of "Proxy address". Since the user is external (like in Hybrid deployment where we stamp the target address with the routing address), Exchange should not lookup the user inside the org but use the target address instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcd64a83-b924-813e-cc44-a24d5e1909d4
* Version Independent ID: a6af6691-438c-72dc-5a72-07d6c83e3770
* Content: [Remote Server returned 550 5.2.0 RESOLVER.ADR.BadPrimary in Office 365 - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/email-delivery/badprimary-ndr)
* Content Source: [Exchange/ExchangeOnline/email-delivery/badprimary-ndr.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/email-delivery/badprimary-ndr.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@JeroenDronkers Thank you for your feedback. I have tested this scenario and when you update or create a new mail contact, the attribute updated via PowerShell is Externalemailaddress and which when updated updates the Primary SMTP of the mail contact object in AD and not the target address. 


Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@JeroenDronkers Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
