### ISSUE TITLE
Ctrl+F for "gourd" to find a typo!

### ISSUE THREAD

**Issue by Andygoes** [MicrosoftDocs/OfficeDocs-Support#949]
Way down at the bottom of the page you discuss group names, and then it looks like an autocorrect changed "group" to "gourd".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dc5543b-4cea-7daa-fc2e-ba183f2e9ec0
* Version Independent ID: 8c0e79a1-fdd6-a1b2-1651-956db18905b0
* Content: [You receive an error when accessing Project Web App - Office](https://docs.microsoft.com/en-us/office/troubleshoot/project/error-when-access-pwa)
* Content Source: [Office/Client/project/error-when-access-pwa.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/project/error-when-access-pwa.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your comment. The article is updated.
