### ISSUE TITLE
URL error

### ISSUE THREAD

**Issue by dll128** [MicrosoftDocs/OfficeDocs-Support#95]
This article intrigues me and I would like to learn more. Unfortunately, the link to the third-party website (http://www.outlookcode.com/article.aspx?id=62) isn't working. Might there be a typo?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e06b4935-24d7-124a-5f6c-ebaed4e679d2
* Version Independent ID: b2c14660-e8ed-ca53-13f4-8b423a748af9
* Content: [How to create a script for the Rules Wizard in Outlook - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-developer/create-script-for-rule-wizard-in-outlook#feedback)
* Content Source: [Office/Client/office-developer/create-script-for-rule-wizard-in-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-developer/create-script-for-rule-wizard-in-outlook.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
The third-party website is not working now. Deleted it from the article.
