### ISSUE TITLE
Not complete example value

### ISSUE THREAD

**Issue by erottier** [MicrosoftDocs/OfficeDocs-Support#952]
The example value given is "adatum.com" for the autodiscover URL "https://adatum.com". While it's valid, is's not complete.
It should have a subdomain in it's place, or as an extra example.

Like: for the autodiscover URL: "https://autodiscover.adatum.com", the String Value should be: "autodiscover.adatum.com", NOT just the root domain.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a570c42-0a95-609b-96fc-83d5c3c855e4
* Version Independent ID: 6d1bf911-f3bf-c00e-8fef-6df9bc80ba34
* Content: [How to suppress AutoDiscover redirect warning - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/connectivity/how-to-suppress-autodiscover-redirect-warning)
* Content Source: [Outlook/Client/connectivity/how-to-suppress-autodiscover-redirect-warning.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/connectivity/how-to-suppress-autodiscover-redirect-warning.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello,
example looks completely fine for me.
**the String Value should be: "autodiscover.adatum.com", NOT just the root domain.** - why? autodiscover service checks root domain as well as the subdomain. Have a look [here](https://enterpriseit.co/microsoft-exchange/outlook-autodiscover-order/).

Thank you

**Comment by nam31** [comment]
@erottier Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
