### ISSUE TITLE
Missing info

### ISSUE THREAD

**Issue by copywritepaste** [MicrosoftDocs/OfficeDocs-Support#957]
This page doesn't include any reference to the fact that giving ownership of a form to a group not only breaks the submission notification feature (the right people don't get an email when a response is received) but it ALSO breaks any Power Automate Flow that uses the form. That is a DEAL BREAKER, and it needs to be abundantly clear that the forms connector in Power Automate REQUIRES that a user be a direct owner of any form they wish to use in order to function at all. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae5837d9-04a2-ffb7-19f4-1b6538cd7630
* Version Independent ID: 97de6157-49d3-99e6-91a5-6d669b95cd90
* Content: [No email notifications for responses to Group Forms - Office](https://docs.microsoft.com/en-us/office/troubleshoot/microsoft-forms/no-email-notifications-for-responses-to-group-forms)
* Content Source: [Office/OfficeExperts/microsoft-forms/no-email-notifications-for-responses-to-group-forms.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/microsoft-forms/no-email-notifications-for-responses-to-group-forms.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **zakirh**

**Comment by msbemba** [comment]
@copywritepaste Thank you for your feedback. The Document discusses why email notifications are not received when a group is blocked from receiving emails outside of the organization. While what you say is correct, about power automate, it cannot be added to this document.

@nam31 There are no changes required in the document.

Thanks
Sri

**Comment by nam31** [comment]
@copywritepaste Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
