### ISSUE TITLE
Please Edit

### ISSUE THREAD

**Issue by filipne** [MicrosoftDocs/OfficeDocs-Support#958]
Hello , 

Please Edit this page. 
Directions are very confusing and unclear. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bdb9e4e-58bb-0b83-2b67-666aca01b889
* Version Independent ID: af966098-3448-53a7-e18a-0116ae61fc24
* Content: [Reconnect inactive or soft-deleted mailboxes to AD - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/reconnect-inactive-or-soft-deleted-mailboxes-to-ad)
* Content Source: [Exchange/ExchangeOnline/administration/reconnect-inactive-or-soft-deleted-mailboxes-to-ad.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/administration/reconnect-inactive-or-soft-deleted-mailboxes-to-ad.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@filipne Thank you for your feedback. We have made some changes to the instructions in the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1373

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1373 
Thank you
