### ISSUE TITLE
Excel Hyperlink issues

### ISSUE THREAD

**Issue by jayBiTech** [MicrosoftDocs/OfficeDocs-Support#96]
Hi, will this work for an excel file users access from a share drive that has hyperlinks to files all over said share drive? Had links break after a user moved the Excel file to another folder in the structure.

**Comment by nam31** [comment]
@jayBiTech We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
