### ISSUE TITLE
Problem also exists with SharePoint Server/on-premises version?

### ISSUE THREAD

**Issue by SharePointBlackBelt** [MicrosoftDocs/OfficeDocs-Support#960]
We're seeing the same behavior in SharePoint Server/on-prem, so apparently one of the security patches has pushed this removal of file protocol down to on-prem too. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81717c69-3a8d-9a8d-19a2-dbe6a86cfe9a
* Version Independent ID: b9555ea1-3f56-f3f0-ad1a-d7546d21ab52
* Content: [Invalid URL when clicking a SharePoint Online Promoted Link - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/promoted-link-invalid-url)
* Content Source: [SharePoint/SharePointOnline/administration/promoted-link-invalid-url.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/administration/promoted-link-invalid-url.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@SharePointBlackBelt What SharePoint on-premises version are you seeing this on? Are you still able to reproduce it?

Also, does the fix described [here](https://social.technet.microsoft.com/Forums/ie/en-US/53e8147d-4d8d-4995-b411-8cc01716a560/promotedlinks-issue-invalid-pageurl?forum=sharepointgeneral) help?

**Comment by SharePointBlackBelt** [comment]
The article states Applies to: SharePoint Online
I'm asking someone to fix the article so it also applies to SharePoint Server. The article with the "fix" does not work on SharePoint Server 2019. Not sure about older version.

**Comment by VLG17** [comment]
@SharePointBlackBelt So you can reproduce the issue on SharePoint Server 2019, right? That's what I'm asking.

Also, did you try the fix that I mentioned above? Does it work in your situation?

**Comment by SharePointBlackBelt** [comment]
Right, file protocol does nothing/does not work in SP2019.

Vince
________________________________

**Comment by VLG17** [comment]
@SharePointBlackBelt Thanks for confirming you are seeing the issue also on SharePoint 2019.

Could you also check if [the fix described here](https://social.technet.microsoft.com/Forums/ie/en-US/53e8147d-4d8d-4995-b411-8cc01716a560/promotedlinks-issue-invalid-pageurl?forum=sharepointgeneral) works in your case?

**Comment by nam31** [comment]
@SharePointBlackBelt We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
