### ISSUE TITLE
The UseOnlineContent reg setting was missing. I've tried to add it as a hex, value 2. Restarted the machine, but it didn't take. Any suggestions?

### ISSUE THREAD

**Issue by strudwim** [MicrosoftDocs/OfficeDocs-Support#962]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 752ad938-d26c-d516-4edc-187a45d3509e
* Version Independent ID: d91ab0f4-844b-03e0-32f7-964d398bca48
* Content: [Password prompt at every start or cannot create profile - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/authentication/password-prompt-at-every-start-or-cannot-create-profile#more-information)
* Content Source: [Outlook/Client/authentication/password-prompt-at-every-start-or-cannot-create-profile.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/authentication/password-prompt-at-every-start-or-cannot-create-profile.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@strudwim this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@strudwim We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
