### ISSUE TITLE
Document clarification Needed

### ISSUE THREAD

**Issue by haydanbarry** [MicrosoftDocs/OfficeDocs-Support#965]
[Enter feedback here]
This document needs to be amended to include also Word documents. I'm getting this error when a sender is sending meeting invite with NO attachments. Meeting invites use <meta name="Generator" content="Microsoft Word 15 (filtered medium)">
Also, on the workaround needs to indicate if the transport rules on the sender or recipient side need to be reviewed. The assumption is that it would be the rules on the recipient side... but what if both the sender and recipient use Exchange Online... Ahh .. then it's not so clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd616f0f-e889-297c-8bf4-09f6d3f9764e
* Version Independent ID: c27e6b3c-ed83-d212-c15f-45a9ef6bf499
* Content: [554 5.6.0 Invalid message content in Office 365 - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/email-delivery/invalid-message-ndr)
* Content Source: [Exchange/ExchangeOnline/email-delivery/invalid-message-ndr.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/email-delivery/invalid-message-ndr.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@haydanbarry Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1374

Meanwhile, The workaround is to check if the transport rule is to defer the message if rules do not work. The rule can be an outbound or an inbound rule. So it is better to check on both sender and recipient sides.

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1374 
Thank you
