### ISSUE TITLE
Information about increasing bitmap resolution when exporting to PDF is missing

### ISSUE THREAD

**Issue by DavidGP** [MicrosoftDocs/OfficeDocs-Support#968]
The information on this page is incomplete, since nothing is said about how to increase the resolution of bitmaps **when exporting to PDF**. Please add respective information to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e390c4c9-9cdf-beb1-43dc-6ec45ae5fe77
* Version Independent ID: bb31c9ea-7186-22fb-195f-f481eb5137e4
* Content: [How to change the export resolution of a PowerPoint slide - Office](https://docs.microsoft.com/en-us/office/troubleshoot/powerpoint/change-export-slide-resolution)
* Content Source: [Office/Client/powerpoint/change-export-slide-resolution.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/powerpoint/change-export-slide-resolution.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. The step 1 of the article includes the information about how to set the bitmap resolution.

**Comment by DavidGP** [comment]
The resolution that is changed in step 1 does not apply to PDF export.

**Comment by simonxjx** [comment]
Do you want to export PowerPoint to PDF? In this case, you can reference [Save PowerPoint presentations as PDF files](https://support.microsoft.com/office/9b5c786b-9c6e-4fe6-81f6-9372f77c47c8). If the steps do not help, you can contact [PowerPoint support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.powerpoint) for more help.

**Comment by DavidGP** [comment]
In this case the title of the article needs to be changed, because it mistakenly makes you believe that the article talks *in general* about any file type export, where in fact it is only about the export of *bitmap* files like JPG, PNG, TIFF etc.

A corrected title could read: "How to change the export resolution of a PowerPoint slide when exporting the slide as image file".
