### ISSUE TITLE
No such files or commands

### ISSUE THREAD

**Issue by ahorowit2006** [MicrosoftDocs/OfficeDocs-Support#97]
Hello,
I tried to follow your suggestions for PP 2008 or later (I have the latest version 16.28 and I run OS 10.14.6 on iMac). First, home doesn't bring me to a library. I found the library myself but none of the files you mentioned as present in Preferences exists, including Microsoft. Obviously none of your suggestions worked. Additionally, there is no Repair Disk Permissions when I select first aid in Disk Utility. I can't understand how such a discrepancy can happen between your notions and reality. Have you double-checked your own suggestions on the latest Mac OS? 
Thank you,
Arie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f20e4c64-5a39-c446-2b6d-eaaa7063da22
* Version Independent ID: 14e0dc17-c870-c38a-7f93-0713b2ea3859
* Content: [Powerpoint for Mac closes unexpectedly - Office](https://docs.microsoft.com/en-us/office/troubleshoot/activation-installation/powerpoint-mac-closes-unexpectedly#feedback)
* Content Source: [Office/Client/activation-installation/powerpoint-mac-closes-unexpectedly.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/activation-installation/powerpoint-mac-closes-unexpectedly.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
This is a very old article covering versions out of support. We will be archiving it.
