### ISSUE TITLE
Persistent Notification

### ISSUE THREAD

**Issue by DesignsWithDavid** [MicrosoftDocs/OfficeDocs-Support#970]
Notifications for activities and chats are only cleared when the main Teams window is on top.  As a result, if I am in a Teams call with the window on top and someone enters a message into the chat for that respective call, I receive a persistent notification that does not clear when opening the chatbox, but only when switching windows and viewing the main Teams window.  This results in poor workflow where I must constantly be changing windows from the call I am in so that the taskbar notification can clear.  

For more clarity, by notification, I am referring to the highlighted Teams icon in the taskbar.  My taskbar is usually hidden but becomes visible when there is a notification.  The persistent notification means that my taskbar will continue to overlap a portion of the Teams call window until it is cleared.  The attached image shows this exact thing happening as I type this issue.

![image](https://user-images.githubusercontent.com/47994883/101529259-f4620500-3955-11eb-83e7-e4be96110298.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 103da6d9-ae2b-dea2-053d-922600686950
* Version Independent ID: 62501206-4fee-8016-bff1-309eae334d75
* Content: [Information about Teams known issues - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-welcome)
* Content Source: [Teams/teams-welcome.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-welcome.md)
* Service: **msteams**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. This issue may be related to some settings or user interface. You can contact [Teams support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.teams) for more help if there is no article for this.
