### ISSUE TITLE
no forward slash name, problem still occurred

### ISSUE THREAD

**Issue by rezatbahtera** [MicrosoftDocs/OfficeDocs-Support#971]
I have Check All OU name there is no forward slash, but i still found the problem, actually problem  is when we try to manage on sibling domain, 

let say 
1. Exchange install on domain a.contoso.local, we can manage from EAC
2. User Can't manage from EAC on domain b.contoso.local

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d102e5a6-31e1-8d45-7c1d-46e3238ccd22
* Version Independent ID: 4f82da14-6b32-6d5e-5eb2-7f76d50b6727
* Content: [Can't manage a user in Exchange Admin Center - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/cannot-find-the-organizational-unit)
* Content Source: [Exchange/ExchangeServer/administration/cannot-find-the-organizational-unit.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/administration/cannot-find-the-organizational-unit.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. I understand that the issue cannot fixed by the article. If it is the case, you can contact [Exchange Support](https://support.serviceshub.microsoft.com/supportforbusiness/onboarding?origin=%2Fsupportforbusiness%2Fcreate) for more help.
