### ISSUE TITLE
.msg Preview in Explorer doesn't work!

### ISSUE THREAD

**Issue by COMEDZimmermann** [MicrosoftDocs/OfficeDocs-Support#973]
[Sadly i got the situation that the .msg preview doesnt work on Terminalserver (Windows Server 2019 Std) with Office 2019 Std. Its Office 32bit installed but still doesnt work. This Problem we found on several Terminalservers all Windows Server 2019 and Office 2019. With Office 365 we dont have this issue. 
Happy if anyone has an idea what we could try.]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a4013c67-30ec-eb6d-ee1d-7de0f899f2ad
* Version Independent ID: ea8c54b7-7b53-ba44-3ca9-2c15abda4fee
* Content: [Msg-Dateien können im Windows-Datei-Explorer nicht angezeigt werden - Outlook](https://docs.microsoft.com/de-de/outlook/troubleshoot/performance/cannot-preview-msg-files-in-windows-file-explorer)
* Content Source: [Outlook/Client/performance/cannot-preview-msg-files-in-windows-file-explorer.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/performance/cannot-preview-msg-files-in-windows-file-explorer.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. I suggest that you can contact [Outlook support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.outlook) for more help.
