### ISSUE TITLE
Out of Office Notification Works When Forwarding to an Internal User

### ISSUE THREAD

**Issue by VShrubowich** [MicrosoftDocs/OfficeDocs-Support#974]
I set forwarding to another internal user on the mailbox in the Exchange Online admin center and set an Out of Office notification.  When sending to this user, the email is forwarded AND the sender receives the Out of Office notification.  I did not test it with external forwarding.

I ran the following command:

`Get-Mailbox -identity testuser | FL *forwarding*,*deliver*`

The command output was the following:

```
ForwardingAddress          : testuser2
ForwardingSmtpAddress      :
DeliverToMailboxAndForward : True
```

So, configuring forwarding on a mailbox to another internal user (as opposed to forwarding to an SMTP address) works as expected with the email being forwarded and the sender getting the Out of Office notification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 380a4415-9a6b-c8a6-b261-1a2f262254cd
* Version Independent ID: 48b5ae21-3a22-a41a-eac5-2b8a6b21e9d0
* Content: [Senders do not receive Out of Office notifications - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/send-emails/senders-not-receiving-out-of-office-notifications)
* Content Source: [Exchange/ExchangeOnline/send-emails/senders-not-receiving-out-of-office-notifications.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/send-emails/senders-not-receiving-out-of-office-notifications.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft with your feedback. Do you have any comment on this article?

**Comment by VShrubowich** [comment]
I also tested this with forwarding configured on the mailbox to an internal user's SMTP address.  The sender received the Out of Office notification and the email was forwarded correctly.  So, there are at least some circumstances not mentioned in the article where this will not cause an issue.

This is what the Get-Mailbox command output showed:

```
ForwardingAddress          :
ForwardingSmtpAddress      : smtp:testuser2@contoso.com
DeliverToMailboxAndForward : True
```

Note, both tests were done in a GCC tenant.

**Comment by msbemba** [comment]
@VShrubowich Thank you for your feedback. I have added a note to the document stating that this affects only external forwarding. This can be tracked via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1633

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1633 
Thank you
