### ISSUE TITLE
The 'Cause' Section in this Article is Incorrect

### ISSUE THREAD

**Issue by VShrubowich** [MicrosoftDocs/OfficeDocs-Support#975]
There are a few issues with the wording in this article:

1. The way the 'Cause' section is currently written, one of the conditions that can result in this issue occurring is if an automatic reply notification is set up in the user's mailbox (even without a forwarding rule or a transport rule).
2. The wording for the Out of Office notification should be more consistent throughout the article; in some places, it's referred to as "Out of Office notification" while in other places as "automatic reply notification".
3. The phrase "forwarding rule" is misleading.  When I first read the article, I thought it was talking about an Inbox rule that does forwarding.  It can also be confused with a mail flow rule (a.k.a., transport rule).  Is this really a "rule" internally or is it an attribute (or three) that is read to determine whether to forward emails and, if so, where?
4. In Exchange Online, transport rules are typically referred to as mail flow rules.
5. Since Exchange Online doesn't have the concept of Mailbox servers and Edge Transport servers (at least not to an Exchange Online admin) and since there is only one set of transport rules configurable per tenant and these transport rules are evaluated globally, the word "global" before "Exchange transport rule" in the 'Cause' section is unnecessary and may even be confusing to some people.
6. Wouldn't the transport rule need to be one that forwards the email (or possibly also one that blocks or quarantines the email)?  Most organizations likely have one or more transport rules created that apply to emails sent to all mailboxes.

Note, as I submitted in feedback in #974 earlier in the day, the sender receives the Out of Office notification if forwarding to another internal user is configured on the mailbox.  I did not test forwarding to an external address.  Perhaps having forwarding configured on the mailbox doesn't affect the Out of Office notification at all?  Perhaps it's only when a mail flow rule prevents the message from getting to the mailbox?  (Testing was done with a GCC tenant.)

Also, the 'Resolution - Step 2: Identify and remove Exchange transport rules' section should include what to look for in the mail flow rules (e.g., redirect the message).

If I understand what the article is trying to say, better wording for the 'Cause' section would be:

### Cause

This issue may occur if an Out of Office notification is set up for the user's mailbox and one of the following conditions is true:

- Forwarding to an external address is set up on the user's mailbox.
- An Exchange Online mail flow rule for forwarding email is created for this mailbox.

By design, a mailbox cannot have forwarding to an external address or a mail flow forwarding rule and an Out of Office notification active at the same time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 380a4415-9a6b-c8a6-b261-1a2f262254cd
* Version Independent ID: 48b5ae21-3a22-a41a-eac5-2b8a6b21e9d0
* Content: [Senders do not receive Out of Office notifications - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/send-emails/senders-not-receiving-out-of-office-notifications)
* Content Source: [Exchange/ExchangeOnline/send-emails/senders-not-receiving-out-of-office-notifications.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/send-emails/senders-not-receiving-out-of-office-notifications.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your feedback. We will have a check.
