### ISSUE TITLE
URL to Exchange Hybrid Configuration Diagnostik does not work

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/OfficeDocs-Support#976]
At the bottom of the article there is a link to the "Hybrid Configuration Diagnostic" to [https://aka.ms/hcwcheck](url) that does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27f7a7e5-bce4-d74c-f04a-641d1c5934c3
* Version Independent ID: 335567f2-2046-a5a5-26b6-22899175864c
* Content: [Warning occurs when running Hybrid Configuration - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/hybrid-configuration-wizard-errors/hcw-has-completed-but-was-not-able-to-perform-oauth)
* Content Source: [Exchange/ExchangeHybrid/hybrid-configuration-wizard-errors/hcw-has-completed-but-was-not-able-to-perform-oauth.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/hybrid-configuration-wizard-errors/hcw-has-completed-but-was-not-able-to-perform-oauth.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your feedback. We will update the link. Thanks.
