### ISSUE TITLE
The Excel printing problem only happens on home wifi network

### ISSUE THREAD

**Issue by pbsjr455** [MicrosoftDocs/OfficeDocs-Support#978]
The home network uses Dell C2660dn printer. No other applications have a problem, only Excel.

Worksheets print blank.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b27ee4-81f7-b439-f8c2-ae0036a12d77
* Version Independent ID: c4cbb42f-9f83-8326-678a-5f142900a1c3
* Content: [Blank pages are unexpectedly printed - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/blank-pages-unexpectedly-printed)
* Content Source: [Office/Client/excel/blank-pages-unexpectedly-printed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/blank-pages-unexpectedly-printed.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. I suggest that you can reinstall Excel to have a check. If the issue persists, you can contact [Excel Support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.excel) for more help.
