### ISSUE TITLE
Wrong information

### ISSUE THREAD

**Issue by rsbeckerca** [MicrosoftDocs/OfficeDocs-Support#979]
There is no About Microsoft Outlook on the Help Menu in the latest build.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b1e21ab-f7d9-6c75-c2d8-7d7a38d9b5a6
* Version Independent ID: 72571720-c634-6a03-a239-7d65c4e36e92
* Content: [How to determine Outlook version information - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/user-interface/how-to-determine-outlook-version-information)
* Content Source: [Outlook/Client/user-interface/how-to-determine-outlook-version-information.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/user-interface/how-to-determine-outlook-version-information.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your feedback. The article is applied to Outlook 2007 and Outlook 2003.
