### ISSUE TITLE
Creating inbox rule to trigger auto email template for every emails

### ISSUE THREAD

**Issue by XixiHuang333** [MicrosoftDocs/OfficeDocs-Support#98]
customer has OOF turn on for mailbox, however only one OOF email is sent on a daily basis. As workaround, customer created a inbox rule on mailbox to trigger a auto reply email for every received emails. Customer asks for us to create or update document or KB article referencing this new method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65d28096-bc2d-7c6f-f3cd-5c18e08a6c92
* Version Independent ID: 3f2cb43c-a0e7-2937-ae4c-7c19b08662ad
* Content: [How to set automatic replies on a user's mailbox in Office 365 - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/configure-mailboxes/set-automatic-replies#feedback)
* Content Source: [Exchange/ExchangeOnline/configure-mailboxes/set-automatic-replies.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/configure-mailboxes/set-automatic-replies.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@XixiHuang333 Thank you for your feedback. We have added related links to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1497 which talks about other scenarios.

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1497
Thank you
