### ISSUE TITLE
Article seems to be outdated

### ISSUE THREAD

**Issue by AdrianRaduMS** [MicrosoftDocs/OfficeDocs-Support#985]
It seems like the Web Address field is no longer available under the Title, Logo and Description settings. Now the only way to edit a site address is either via the SPO admin center, or Powershell. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e178c771-f083-87d1-c165-e078388589ad
* Version Independent ID: de4ab354-13c1-d466-cf9d-e440adade3a1
* Content: [Unexpected error when creating a calendar overlay - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/lists-and-libraries/fails-creating-calendar-overlay)
* Content Source: [SharePoint/SharePointOnline/lists-and-libraries/fails-creating-calendar-overlay.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/lists-and-libraries/fails-creating-calendar-overlay.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
It is still there, it seems like you were on the “root” of a classic site OR you were on a modern site and didn’t see the option in the UI to navigate there. 

To change the URL while at the root level of a classic or Modern site, you must change the site address. For more information, see Change a site address. (Note that navigation on a Modern site is not shown by default.)

The title, description, and logo settings page can be accessed directly by browsing to https://contoso.sharepoint.com/web1/_layouts/15/prjsetng.aspx (where "contoso" is your website).

I've updated the article to reflect these comments.
Thanks,
Jose
