### ISSUE TITLE
Drive C is Denied

### ISSUE THREAD

**Issue by isvan313** [MicrosoftDocs/OfficeDocs-Support#986]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17760d02-bda5-2d47-ad3e-cfbd46468f84
* Version Independent ID: 5ff5d2a4-0f83-91f6-2c75-77256c834e89
* Content: [Listing some issues for Exchange Online - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/exchange-online-welcome)
* Content Source: [Exchange/ExchangeOnline/exchange-online-welcome.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/exchange-online-welcome.md)
* Service: **exchange-online**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by nam31** [comment]
@isvan313 The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Are you facing any issue with the article linked as Content ?
Thank you.

**Comment by nam31** [comment]
@isvan313 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
