### ISSUE TITLE
Google Chrome add trusted site URLs listed are not accepted

### ISSUE THREAD

**Issue by joz-f** [MicrosoftDocs/OfficeDocs-Support#987]
The page says add the following sites:

https://*.microsoft.com
https://*.microsoftonline.com
https://*.teams.skype.com
https://*.teams.microsoft.com
https://*.sfbassets.com
https://*.skypeforbusiness.com

But you cannot add a URL with an asterisk in Chrome preferences.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c17faf2-0e38-0a98-454c-3c2c4387b37f
* Version Independent ID: d9153b98-dc39-fdd1-a798-07da0caaaa64
* Content: [Microsoft Teams is stuck in a login loop in Edge, Internet Explorer or Google Chrome - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#resolution)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. If you want to add a site in Chrome, you should add the site with an asterisk. For example, [*.]microsoft.com.

**Comment by joz-f** [comment]
The renderer parsed the asterisks out of my comment. The MS teams page says use this format URL to add to the safe list:

`https://*.microsoft.com

https://*.microsoftonline.com

https://*.teams.skype.com

https://*.teams.microsoft.com

https://*.sfbassets.com

https://*.skypeforbusiness.com`

rather than, as you say, this format:
`[*.]microsoft.com.`

Perhaps adjust the page.

**Comment by simonxjx** [comment]
Thanks for the clarification. The page is updated.
