### ISSUE TITLE
Grammar, syntax and word choice

### ISSUE THREAD

**Issue by Urbs3w** [MicrosoftDocs/OfficeDocs-Support#990]
I believe that the article can be improved for EN-US audiences by changing the grammar, syntax, and word choice to better reflect the style and conventions of American English. The current grammar, style and syntax is kind of hard to understand and follow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d25557df-12d9-2b76-eba2-a3c8134d294a
* Version Independent ID: c8a4f4fd-dbbe-0c41-5c4a-0dd10f7caa93
* Content: [How to merge multiple Word documents into one - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/merge-word-documents)
* Content Source: [Office/Client/word/merge-word-documents.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/merge-word-documents.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for your feedback. The article is an old article which is migrated from other platform. The article is updated now to make it clear.
