### ISSUE TITLE
not much help here

### ISSUE THREAD

**Issue by mikejboss** [MicrosoftDocs/OfficeDocs-Support#996]
hey, i'm trying to unscrew myself and get work done.  instead, i follow a link TO SEE HOW I CAN FIX THE FACT THAT I CAN'T COPY ONEDRIVE files from one place to another because some threshold was exceeded.  but i don't get an answer, i just get pointed elsewhere.  well, i am freaking sick and gd tired of getting bounced around to dissertations and dead ends when you could have provided a simple answer.  SO DO IT.  prop-heads....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 137de6d6-027d-e798-08d4-8f81dbcd732b
* Version Independent ID: 0b81624b-679e-7413-ddba-9882e74113be
* Content: [The number of items in this list exceeds the list view threshold - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/lists-and-libraries/items-exceeds-list-view-threshold)
* Content Source: [SharePoint/SharePointOnline/lists-and-libraries/items-exceeds-list-view-threshold.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/lists-and-libraries/items-exceeds-list-view-threshold.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. You can contact [OneDrive support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.onedrive) for more help.
