### ISSUE TITLE
update for Chrome

### ISSUE THREAD

**Issue by siliconglen** [MicrosoftDocs/OfficeDocs-Support#997]
[Enter feedback here]

The info is out of date for Chrome. Instead go to Settings-> Privacy and Security -> Cookies and Other Site Data -> scroll down to Sites that can always use cookies then add this one line
[*.]microsoft.com
and check the box for "Including third-party cookies on this site"
Then click the Add button and refresh the page. That's it. Did it on my browser which blocks third party cookies by default and it worked. Chrome Version 87.0.4280.88 (Official Build) (64-bit)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c17faf2-0e38-0a98-454c-3c2c4387b37f
* Version Independent ID: d9153b98-dc39-fdd1-a798-07da0caaaa64
* Content: [Microsoft Teams is stuck in a login loop in Edge, Internet Explorer or Google Chrome - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#resolution)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@siliconglen The article and the list of sites to be added have been updated to reflect the changes.

**Comment by nam31** [comment]
@siliconglen Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
