### ISSUE TITLE
Edge

### ISSUE THREAD

**Issue by SharePointBlackBelt** [MicrosoftDocs/OfficeDocs-Support#998]
Problem also exists in Edge Chromium, but the documented workaround only applies to Internet Explorer. There appears to be no workaround to fix the broken presence indicator on SharePoint sites in Edge Chromium.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3945fa40-8914-e356-f569-50edcd17cfef
* Version Independent ID: c0add01f-a482-87fc-cb2c-40ad61d8f234
* Content: [Presence information isn't displayed on a SharePoint page - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/presence-information-fails-showing)
* Content Source: [SharePoint/SharePointOnline/administration/presence-information-fails-showing.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/administration/presence-information-fails-showing.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment]
Thanks for contacting Microsoft. You can contact [Skype for Business support](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.skype-for-business) for more help.
